### ISSUE TITLE
line.py example: different results with python2 and python3

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#1000]
In the basics/visuals/line.py example from vispy the lines on the third row are both thick in python 2, but in python 3 the left line is thin and the right line is thick.

Vispy is the latest from github (commit 5d0f0f1ffb6b456ad4cbfec9aedeb592f2dfbdad)
I am using ubuntu 14.04. Both python 2 and 3 are running with the PyQt4 backend. I am running nvidia 349.16 drivers.

**Comment by QuLogic** [comment]
Do you have a screenshot? I do not see any difference between the two columns.

Also, congratulations on being #1000. :cake:

**Comment by eendebakpt** [comment]
Here is a screenshot: Python 2 on the left, Python 3 on the right.

![vispy-line-width](https://cloud.githubusercontent.com/assets/883786/8541328/9af3c112-248d-11e5-9419-9ce9d1148c5e.png)

**Comment by almarklein** [comment]
What the ...  Can this be an integer division thing?

**Comment by eendebakpt** [comment]
I did some more tests. I have 2 systems which show the problem described above. One other system (also ubuntu 14.04) does not show the problem. Integer division does not seem likely for that reason. I suspect it is something in the drivers (opengl, graphics card, PyQt) that is triggered by python3.

I can provide more information about the systems, but I am not sure which information is relevant.

**Comment by kmuehlbauer** [comment]
Please reopen, if the problem still persist. Or open a new issue with current details.
