### ISSUE TITLE
ipython shader errors should print context

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#1001]
I am getting this error in ipython:

```
ERROR: 0:16: '==' :  wrong operand types  no operation '==' exists that takes a 
left-hand operand of type 'mediump float' and a right operand of type 'const int' 
(or there is no acceptable conversion)
```

There are several visuals in the scene; it would help a lot if a few lines of GLSL context were printed with this error so I can track down the source.

@rossant?

**Comment by rossant** [comment]
i think you can activate a debug mode to display all commands, including the shader source...

**Comment by djhoese** [comment]
I don't think this is something that we can control too much in vispy. Doesn't the error come from the browser's compilation of the shader code? I'm closing this for now since I'm not even sure the desktop version of these errors is consistent. Just to avoid stale issues I'm closing this for now.
