### ISSUE TITLE
transparency for RectangleVisual

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#1007]
The RectangleVisual object does not become semi-transparent when setting the alpha channel of the color. This seems to be the same issue as #848. There the problem could be fixed by setting the depth value of the coordinates, but this does not work for the rectangle.

**Comment by Eric89GXL** [comment]
Can you see if it is fixed by #928?

**Comment by eendebakpt** [comment]
Yes, latest commit of vispy together with a gloo.set_state(depth_test=False) makes the transparency work. Thanks!
