### ISSUE TITLE
Use pre-built Docker containers once Travis CI enables this

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#1009]
The [Travis CI blogpost](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/) that introduced container builds also noted that users would be able to use custom Docker containers in the future.

This would help speed up builds, since we could just use custom Docker containers with all dependencies (Numpy,  IPython, OpenGL bindings, Qt, Pyglet,...) preinstalled, so the install / download times would be cut down on.

To quote the original blog post,

> Can I provide my own Docker containers?
> ...
> The question for providing your own images is a natural one.
> ...
> We're not there yet in allowing you to bring your own, but it's something we have in mind for the future.

**Comment by QuLogic** [comment]
Whether it's any faster probably depends on where the containers need to be hosted...

**Comment by bollu** [comment]
@Eric89GXL : Travis looks like it supports caching build dependencies, like [pip](http://docs.travis-ci.com/user/caching/#pip-cache) and [arbitrary directories](http://docs.travis-ci.com/user/caching/#Arbitrary-directories). Does VisPy use this? 

If it doesn't, I'll try and take a look at it.

**Comment by Eric89GXL** [comment]
No we don't cache anything. At one point I considered doing it, but I'm not sure it would buy us too much since we'd still want to update conda and the like every time. But it could make things a little bit faster, so if you're keen on it then go for it.

**Comment by kmuehlbauer** [comment]
@djhoese We could think about having docker containers for testing, again. This would at least give us a well defined testing environment.

**Comment by djhoese** [comment]
@kmuehlbauer I'm not sure it would buy us much in our case. As @larsoner pointed out (3+ years ago 😨 ) we would want to update conda every time. Is caching or "saving" a conda environment in a docker image any faster than downloading and installing miniconda with ci-helpers from scratch?

It would be nice for the system changes that Travis does but we risk not being compatible with new versions of Ubuntu (unlikely) or other operating systems. If you or someone else can point out the benefits I'm missing and have the time to work on this then I'm ok trying it out.

**Comment by kmuehlbauer** [comment]
@djhoese I agree, that it would not buy us much time. My point is more that we would have a working CI environment in any case, especially for PR's. So if something breaks it would not be induced by conda/pip/travis but by the changes in vispy code.

This dedicated docker thingy could also be recreated/tested once in a while/regular basis with updated packages to keep things fresh.

**Comment by djhoese** [comment]
Ok, I'm guessing travis allows user custom docker images now? I'm ok with it for system changes (same version of Ubuntu with the same X or other system/version) but would still like the newest conda packages. Although conda has its own issues sometimes when updating itself from older versions...they've been getting better with that though.

**Comment by kmuehlbauer** [comment]
To get the newest conda-packages is for testing vispy with these packages? This would be something for the cron-job. For PR's it would be good to have a known working environment, IMHO.

For the conda aspect: the experiments in #1570 showed, that we could get all needed packages from conda-forge nowadays.

**Comment by djhoese** [comment]
I would agree except for the cases where the PRs need the newest versions of things (new numpy function, new optional dependency, bug fixes, etc). We could have a conda-forge fully updated environment that is listed as an expected failure.

**Comment by kmuehlbauer** [comment]
> I would agree except for the cases where the PRs need the newest versions of things (new numpy function, new optional dependency, bug fixes, etc).

Sure, did not think about that. :cry: 

> We could have a conda-forge fully updated environment that is listed as an expected/allowed failure.

:+1: Yes, if that would be easy to release, I think.

**Comment by djhoese** [comment]
I think we use to have OSX as an allowed failures before we used ci-helpers (@larsoner worked on that iirc, or maybe I'm thinking of another project I work on). Either way https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail

**Comment by almarklein** [comment]
Closing because outdated - CI is now using GH actions.
