### ISSUE TITLE
Set aspect ratio for image and volume plots

### ISSUE THREAD

**Issue by raacampbell13** [vispy/vispy#1013]
Hello,

As far as I can tell the aspect ratio for image and volume plots can't be changed from 1:1. Is this correct? If so, are there plans to allow for user-settable axis ratios?

Thanks!

**Comment by Eric89GXL** [comment]
I think you can do it by setting e.g. `image.transform = STTransform(...)`, have you tried that?

**Comment by raacampbell13** [comment]
No I didn't tr that. I guess you mean this?
http://vispy.org/util.html?highlight=transform#module-vispy.util.transforms
It states " vispy.util.transforms.scale(s, dtype=None) ...  Non-uniform scaling along the x, y, and z axes", so I guess it also works for volumes as well as 2D images. I'll give it a shot!

**Comment by Eric89GXL** [comment]
I mean `vispy.visuals.transforms.STTransform`, it should allow you to scale and translate in your visual coordinate system however you want

**Comment by campagnola** [comment]
For 2D plots, you can also set the x and y axis ranges of the view box independently as long as `viewbox.camera.aspect == None`.

**Comment by michaelaye** [comment]
We are in the need of a Transform tutorial, I'm also currently trying to understand it. As I'm not educated in OpenGL, I was shocked to learn, apparently, that to attach a transform is the only way to move an object after creation? Could we maybe, at least on scene level, have an interface similar to [vpython](vython.org), where I can just do `object.pos = new_pos` ?

**Comment by campagnola** [comment]
A tutorial is a good idea..
We've also been thinking about adding a default transform to all visuals.

**Comment by Eric89GXL** [comment]
It might be worth having at least a `STTransform` there by default. It shouldn't really hurt performance, and it seems to be the 90% use case if people use it.

**Comment by Eric89GXL** [comment]
Or maybe `SRTTransfrom` after we create it.

**Comment by raacampbell13** [comment]
I would also agree that a tutorial would help. Especially for the 3D case.

**Comment by raacampbell13** [comment]
I played with the ./vispy/examples/basics/scene/volume.py example and adding scale=(1,1,2) to the STTransform line (55) does indeed get me where I want to be.

**Comment by Eric89GXL** [comment]
Ahh, good to know @raacampbell13
