### ISSUE TITLE
Provide warning when vispy.scene and vispy.visuals is mixed

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#1015]
The correct way to use visuals in the context of the scenegraph is to load the visuals from `vispy.scene.visuals`. However, right now, using a visual from `vispy.visuals` will fail silently with no warning whatsoever. 

A warning / error could be emitted when a raw `Visual` is attached to the scene.

**Comment by campagnola** [comment]
Agreed, but.. how do you "attach" a raw visual to a scene?

**Comment by bollu** [comment]
This was an example given by @NGXII when we were trying to debug his code:

```
from vispy import scene
from vispy import visuals

canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
view = canvas.central_widget.add_view('arcball')

testpoint = visuals.MarkersVisual()
testpoint.set_data(pos=np.array([[5,5,5],[7,7,7]]).T, face_color=(1,1,1,1), size = 20, edge_width=5, edge_color = (1,1,1,1))
testpoint.parent = view.scene

```

setting `testpoint.parent` works, but doesn't actually _do_ anything, since it's a `Visual`, not a `Node`. I'll have to check where the `parent` field is getting into the `Visual`, but point is, it exists and doesn't throw an error :)


IPython says: 


```
In [8]: testpoint.parent?
Type:        SubScene
String form: <SubScene at 0x9136940>
File:        f:\prog\vispy\vispy\scene\subscene.py
Docstring:
A Node subclass that serves as a marker and parent node for certain
branches of the scenegraph.

SubScene nodes are used as the top-level node for the internal scenes of
a canvas and a view box.
```

**Comment by Eric89GXL** [comment]
It gets added as part of Node.

I wonder if we can add a "parent" attribute of Visual where, if set, throws
an error. This seems to be a nice safeguard.

**Comment by campagnola** [comment]
..Or perhaps we should consider again making it more difficult to set attributes that don't already exist? That would solve one of my biggest frustrations with vispy--the heavy use of properties invites bugs that are very difficult to diagnose.
