### ISSUE TITLE
How to use Compute Shaders?

### ISSUE THREAD

**Issue by ghost** [vispy/vispy#1016]
Hello. Tell me please, how to use Compute Shaders with Vispy? How to use writible shader resources and image store.

**Comment by rougier** [comment]
Vispy is mainly compatible with GL ES 2.0 only so there is no compute shaders available.

**Comment by almarklein** [comment]
We should be able to support it though, now that we have gl+

**Comment by campagnola** [comment]
Would love to have this support. @acterhd if you have a spare week to kill some day, we should discuss strategies for implementing OpenGL 3/4 shader features :)

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
@almarklein @rossant any ideas if there is an easy way to support this? Luke added geometry shaders a couple years ago. I'm not familiar with the difference and implications of compute versus geometry shaders.

**Comment by rossant** [comment]
I think the use of geometry shaders is now discouraged, for the benefit of compute shaders. I'm unsure of OpenGL support of compute shaders, it might depend on the OpenGL version and hardware. I doubt that adding compute shader support to the existing VisPy codebase would be easy, but perhaps I'm wrong!
Note that compute shaders support is mandatory in newer APIs such as Vulkan.

**Comment by djhoese** [comment]
@rossant I suppose compute shaders would be a main feature of a vispy 2.0 redesign? Maybe we close this as something that won't be possible in the current vispy design, but will be implemented in future redesigns?

**Comment by rossant** [comment]
Absolutely. Supporting compute shaders in predefined visuals will be easy in the redesign.
Supporting custom (user-written) compute shaders will be a bit trickier as that's going to be user-exposed GPU code, but I think it would definitely be in the scope.
