### ISSUE TITLE
scenegraph-update branch: oscilloscope demo fails

### ISSUE THREAD

**Issue by michaelaye** [vispy/vispy#1025]
$ python oscilloscope.py
Traceback (most recent call last):
  File "oscilloscope.py", line 198, in <module>
    fft_samples = mic.chunksize \* n_fft_frames
AttributeError: 'MicrophoneRecorder' object has no attribute 'chunksize'
(py27)

Just realized: Why is there no possibility for me to address this issue to the scenegraph-update branch only? Wouldn't branch-connected issues make more sense?

**Comment by Eric89GXL** [comment]
I don't think Github had that feature unfortunately.

I also have that error, but I assumed is due to a problem with that
package. But if you can find a workaround/more general solution that would
be great.

**Comment by jvtrudel** [comment]
Maybe  you could use a label `scenegraph-update branch` or `branch specific`? 
But would it be useful?

**Comment by QuLogic** [comment]
I think it's because you don't have `pyaudio` installed. There's a fake `MicrophoneRecorder` object if it can't be imported, but it doesn't seem to implement everything the "real" one does.

**Comment by QuLogic** [comment]
Please try #1026.

**Comment by Eric89GXL** [comment]
@jvtrudel yeah we could come up with those labels, but I agree the usefulness might be limited as hopefully the `scenegraph-update` branch will be merged very soon.

**Comment by kmuehlbauer** [comment]
Closing. Resolved by #1026.
