### ISSUE TITLE
Use of triangle

### ISSUE THREAD

**Issue by rkern** [vispy/vispy#1029]
[visply/geometry/triangulation.py](https://github.com/vispy/vispy/blob/master/vispy/geometry/triangulation.py) silently attempts to use the [triangle](https://pypi.python.org/pypi/triangle) package. This is problematic from a licensing standpoint. Although the Python wrappers claim to be LGPL, the [underlying library](http://www.cs.cmu.edu/~quake/triangle.html) that it wraps is proprietary. Automatically using proprietary libraries when available may make vispy unable to be used in GPLed programs.

There is another issue in that the module name `triangle` is unfortunately not unique. I had installed [triangle_plot](https://pypi.python.org/pypi/triangle_plot) which installs a `triangle.py` module. In the conditional import, there is no check that the `triangle` module that is imported actually exports the expected names. The result is a somewhat inscrutable traceback when `triangle.triangulate()` is attempted.

**Comment by Eric89GXL** [comment]
Ahh, yes that does seem problematic. Makes sense to me to remove it, and maybe rely on e.g. `scipy`'s `Delaunay` or so if we can. We'll mark that one for 0.5.

**Comment by campagnola** [comment]
I'm confused about the licensing issue--surely it is possible for GPL software to import from non-GPL libraries?

**Comment by Eric89GXL** [comment]
It might be okay for GPL software to do it, but not for us, see the license terms on the site:

> Please note that although Triangle is freely available, it is copyrighted by the author and may not be sold or included in commercial products without a license.

Thus incompatible with our BSD license.

**Comment by Eric89GXL** [comment]
(I'm actually not sure if GPL software can use it, but I'm pretty sure we can't, unless someone got relicensing permission along the way)

**Comment by campagnola** [comment]
> It might be okay for GPL software to do it, but not for us, see the license terms on the site:

> Please note that although Triangle is freely available, it is copyrighted by the author and may not be sold or included in commercial products without a license.

What's the problem? Triangle is not included in vispy. If you have GPL software that uses vispy, then Triangle won't be included there either.

**Comment by Eric89GXL** [comment]
We can't link to software that doesn't allow commercial use

**Comment by campagnola** [comment]
Like PyQt?

**Comment by Eric89GXL** [comment]
Ahh, you must be right. @rkern can you clarify? I thought I understood why we couldn't use it, but I don't.

**Comment by rkern** [comment]
PyQt allows commercial use. And I can opt out of PyQt. I can't opt out of `triangle`. Even if I distribute vispy with a third-party GPLed component and without `triangle`, it will automatically combine with `triangle` on the user's system. While it's possible that the author of that GPLed component won't mind, the fact that vispy automatically finds and combines `triangle` with the whole GPLed work seems like it is working around the restrictions of the GPL. If I use a freezing tool to distribute my binary, it is likely that `triangle` will get picked up without my knowledge, and that really would be a GPL violation.

I would prefer to opt in to dependencies that have stricter licenses than what the outer project advertises. At the very least, the chain of non-BSD-licensed dependencies, optional or not, opt-in or opt-out, should be documented clearly in `LICENSE.txt`.

**Comment by campagnola** [comment]
> Even if I distribute vispy with a third-party GPLed component and without triangle, it will automatically combine with triangle on the user's system. While it's possible that the author of that GPLed component won't mind, the fact that vispy automatically finds and combines triangle with the whole GPLed work seems like it is working around the restrictions of the GPL.

IANAL, of course, but I don't think there are any restrictions about what kind of code can be imported by GPL software at runtime--the license is more concerned with ensuring that closed software cannot make use of GPL code.

> If I use a freezing tool to distribute my binary, it is likely that triangle will get picked up without my knowledge, and that really would be a GPL violation.

That's true, but in that case the person doing the freezing is to blame, not vispy.

**Comment by rkern** [comment]
> That's true, but in that case the person doing the freezing is to blame, not vispy.

vispy can help by advertising its dependencies and the licenses of those dependencies and making it possible to make an informed choice not to use an optional dependency that has a non-BSD license. It's good open source hygiene.

**Comment by campagnola** [comment]
No complaint there.

**Comment by Eric89GXL** [comment]
@campagnola could we use `scipy`'s Delaunay functionality instead of `triangle`? Have you looked into it? I wonder if we can just use a different library altogether.

**Comment by rossant** [comment]
fwiw I've got segfaults in tiger demo with triangle about 30% of the time

**Comment by campagnola** [comment]
Delaunay is a very limited version of the complete triangulation routine--it does not implement constraints, which are the most difficult part of the process.

@rossant, is that using `triangle` or vispy's implementation?

**Comment by rossant** [comment]
it was with triangle exclusively. no segault with vispy, but it was slower obviously
that was a few months ago, on Ubuntu, haven't tried it again since then

**Comment by rkern** [comment]
I also got segfaults on the tiger demo in the past week, using `triangle` on OS X.

**Comment by campagnola** [comment]
This would be my vote for the first place vispy needs cython.

**Comment by rkern** [comment]
:+1: You may want to look at these recent packages:

https://pypi.python.org/pypi/geompreds
https://pypi.python.org/pypi/tri

If you do Cythonize, I do recommend using the C versions of those geometric predicates (also by Shewchuk, but fortunately public domain). It can help avoid getting into an inconsistent state, which can lead to segfaults or other failures.

**Comment by kmuehlbauer** [comment]
@larsoner Should this finally be clarified before the 0.6 release?

**Comment by larsoner** [comment]
I still think using `scipy` is a reasonable / easy option. @kmuehlbauer does it work on the Raspberry Pi?

**Comment by kmuehlbauer** [comment]
Will check!

**Comment by kmuehlbauer** [comment]
Works on the Raspberry Pi, but is takes considerably longer compared to my linux box. I had to install `scipy` to get it to work (Delaunay from scipy.spatial).

**Comment by kmuehlbauer** [comment]
@djhoese @larsoner Did we get to conclusion here? If not this could be discussed at the next dev meeting.

**Comment by djhoese** [comment]
No, I don't think so. Looking at the last relevant work to triangulation.py by @larsoner, it looks like `triangle` is technically optional and will fallback to a python triangulation if it isn't available. That looks like it was done in ~2019, but it is still a dependency on `triangle`. It has been 6 years since the original suggestions by @rkern so we may need to re-research what packages exist (and check their licenses).

**Comment by rougier** [comment]
Licence from the showme.c on https://www.cs.cmu.edu/~quake/triangle.html. It does not looks like LGPL:

```
/*  This program may be freely redistributed under the condition that the    */
/*    copyright notices (including this entire header and the copyright      */
/*    notice printed when the `-h' switch is selected) are not removed, and  */
/*    no compensation is received.  Private, research, and institutional     */
/*    use is free.  You may distribute modified versions of this code UNDER  */
/*    THE CONDITION THAT THIS CODE AND ANY MODIFICATIONS MADE TO IT IN THE   */
/*    SAME FILE REMAIN UNDER COPYRIGHT OF THE ORIGINAL AUTHOR, BOTH SOURCE   */
/*    AND OBJECT CODE ARE MADE FREELY AVAILABLE WITHOUT CHARGE, AND CLEAR    */
/*    NOTICE IS GIVEN OF THE MODIFICATIONS.  Distribution of this code as    */
/*    part of a commercial system is permissible ONLY BY DIRECT ARRANGEMENT  */
/*    WITH THE AUTHOR.  (If you are not directly supplying this code to a    */
/*    customer, and you are instead telling them how they can obtain it for  */
/*    free, then you are not required to make any arrangement with me.)      */
```

**Comment by djhoese** [comment]
To me the `triangle` library puts us in a weird legal gray area. If the scipy library's functionality (https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html) can provide better performance than our current pure-python triangulation algorithm, even if its worse that `triangle`, then I say we switch to that.

**Comment by djhoese** [comment]
In our meeting today, @kmuehlbauer is going to try to look further (again) into using scipy instead of the `triangle` library. If things look good then we will switch to `scipy` as an optional dependency for improved performance in triangulation.

**Comment by kmuehlbauer** [comment]
@djhoese I'm not sure what @larsoner and I where talking about back then, but `scipy.spatial.Delaunay` can't be used here. In our case we need a constrained Delaunay triangulation (CDT) which `scipy` doesn't provide. 

Currently libraries which provide CDT and accessible python-bindings are:

- Triangle (see above, C, triangle-python package)
- CGAL (GPL,C++, swig-bindings)

There is a pure Python implementation:

- https://github.com/lycantropos/sect (MIT)

And there is a C++ implementation:

- https://github.com/artem-ogre/CDT [MPL-2.0)

I did not check the permissive licensed implementations, but they both have recent commits. 

So there is no drop-in replacement for "Triangle" currently available. I can have a PR ready removing "Triangle" from VisPy codebase, leaving only the internal implementation. To move forward relying on an external implementation the mentioned  C++ package looks like a good candidate if it would provide python-bindings.

**Comment by mikedh** [comment]
You might also look at [mapbox_earcut](https://github.com/skogler/mapbox_earcut_python) which performed pretty well for me in tests and has much clearer licensing.

**Comment by djhoese** [comment]
@mikedh Thanks for the heads up! How would you feel about making a pull request trying to use `mapbox_earcut` in place of triangle inside vispy?

**Comment by rossant** [comment]
I don't know how triangle is used in VisPy but make sure to check they do the same thing. As far as I remember earcut is not able to add extra points in triangles whereas triangle is, but I may be wrong.
