### ISSUE TITLE
Need 3D sphere/ellipsoid primitive/visual

### ISSUE THREAD

**Issue by michaelaye** [vispy/vispy#1032]
So, there are `scene.visuals.Cube` and `scene.visuals.Box`, and IIUC, spheres are hard to do in OpenGL b/c everything is based on triangles, but I'm really in urgent need of a 3D Sphere/Ellipsoid primitive. The only thing I found `scene.visuals.Ellipse` only works in 2D apparently (according to docstring). 
I tried to (ab-) use the `scene.visual.Markers` for that but they don't seem to scale correctly/endlessly with the size parameter? At some point (`size>500` or so) the marker just did not get larger (I compared it visually to an embedded x-axis, so that was my reference.)
Is there a quick work-around I could use for a sphere/ellipsoid in 3D?

**Comment by campagnola** [comment]
You can use `Mesh` and `vispy.geometry.create_sphere()` together. And you might as well just implement it as a subclass of `Mesh`. And while you're at it, you might as well make it into a PR ;)

**Comment by campagnola** [comment]
(correction: a subclass of `vispy.visuals.MeshVisual`)

**Comment by michaelaye** [comment]
ok, will start something and then do a WIP PR if I need any help, okay?

**Comment by michaelaye** [comment]
will it work from current master, or does it require anything from scenegraph-update?

**Comment by campagnola** [comment]
`master` should be fine.  I expect the behemoth PR will be merged in the next few days anyway.

**Comment by michaelaye** [comment]
Darn, it's `resolves` not `solves` for auto-closing. Closing! ;)

**Comment by Eric89GXL** [comment]
I usually just put a one-liner in my PR descriptions saying "Closes #XXX."

**Comment by michaelaye** [comment]
Yes, for some reason I chose to write `solves`, confusing it with `resolves` that also auto-closes the referenced issue.
