### ISSUE TITLE
Post-update-scenegraph issues

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#1033]
cc @Eric89GXL, @campagnola 
- [ ] ViewNode and a way to automatically create a view on a scenegraph subtree
- [ ] using fly-camera keys in volume.py example, while fly camera is not yet active results in errors
- [ ] moving mouse with CTRL+RMB gives errors in fly-camera `AttributeError: 'SceneMouseEvent' object has no attribute 'map_to_canvas'`
- [ ] document limitations of `_visual_bounds_at` (e.g. does not work in 3D now)
- [ ] Fix basisc/scene/stereo.py example
- [ ] Fallback for picking on IPython
- [ ] Make the `picking` property of visuals private (or a property on the draw event instead?)
- [ ] Ticks and gridlines should be 1px width or positioned with subpixel precision.

**Comment by Eric89GXL** [comment]
@almarklein I'm going to eliminate the issues from the list that already have their own place for discussion (#926, #914, #628)

**Comment by almarklein** [comment]
sure

**Comment by KelSolaar** [comment]
I'm adding my share of issues (as described on Gitter):

- [ ] `Viewbox.canvas` returns `None` and not the current `SceneCanvas` instance.
- [ ] `SceneCanvas` `resize` signal is not emitted anymore, @Eric89GXL suggesting using `transform_change` instead but this does not exist:
```python
Traceback (most recent call last):
  File "./../colour_analysis/commands.py", line 168, in system_exit_wrapper
    if object(*args, **kwargs):
  File "./../colour_analysis/commands.py", line 353, in main
    arguments.layout)
  File "./../colour_analysis/analysis.py", line 252, in __init__
    self.__create_views()
  File "./../colour_analysis/analysis.py", line 859, in __create_views
    border_color=border_colour)
  File "./../colour_analysis/views/gamut_view.py", line 219, in __init__
    self.__scene_canvas.events.transform_change.connect(
AttributeError: 'EmitterGroup' object has no attribute 'transform_change'
```
Ultimately I was using that to put a `TextVisual` as a title on my views and make it react to `SceneCanvas` geometry changes. If there is a cleaner alternative please let me know (I suppose there should be one).
- [ ] The nasty one: Setting a `ViewBox` camera seems to prevent proper hotkeys processing, and as a result the hotkey pressed event is repeatedly happening forever. Here is my Gitter report doctored:

> Allright found why the application hangs, it is quite weird.
The context is as follows: I have the hotkey *0* bound to a change of reference colourspace, thus I need to reconstruct all the visuals.
Once the `ViewBox` has been initialised, you can change the reference colourspace property and it will trigger the reconstruction of all the `ViewBox` content : https://github.com/colour-science/colour-analysis/blob/master/colour_analysis/views/gamut_view.py#L362

> Now what's happening is that the application when I hit the *0* key is hanging. I isolated that to be linked to the camera creation: `self.__create_camera()`
I thought it was related to *Vispy* camera code itself and after fiddling for a while it is actually nastier: It looks like that the *0* key event is not processed properly and keeps happening forever: If I comment the `self.__create_camera()` statement it is behaving correctly and the *0* key event happens just once, however if I uncomment it, the event keeps happening forever.

> This is where I process the key events: https://github.com/colour-science/colour-analysis/blob/master/colour_analysis/analysis.py#L755
Am I doing something incorrect in my processing of the key events?

**Comment by campagnola** [comment]
> Ultimately I was using that to put a TextVisual as a title on my views and make it react to SceneCanvas geometry changes. If there is a cleaner alternative please let me know (I suppose there should be one).

I would use `scene.Label` and layouts to manage the position of the label; this will automatically react to resizing. You can look at the way PlotWidget works to see how this is done. If you want the text to appear within the boundaries of the viewbox, then you can stack a new grid layout on top of the viewbox using `Widget.add_grid`.

**Comment by Eric89GXL** [comment]
@KelSolaar any progress yet? Any way we could help?

**Comment by KelSolaar** [comment]
@Eric89GXL Unfortunately I haven't been able to look into that yet, quite swamped at work, I'll try to drop an eye maybe next week. I'll keep you updated!

**Comment by Eric89GXL** [comment]
No rush from my end, just checking :)

**Comment by KelSolaar** [comment]
Back onto that one :)

- I fixed the overlays on the `Viewbox`(es) by using what Luke suggested, working great and better than what I had before! I would for now still need the `Viewbox.canvas` to return the current `SceneCanvas` instance if possible although I may end up doing it another way which will be better for encapsulation of my objects.
- I still have the nasty crash even after pulling all the current commits from upstream master, I would need some help on this one as there is something ugly going on here.

**Comment by bollu** [comment]
@KelSolaar I'm interested - could you tell me how to repro the crash? I have some free time right now :)

**Comment by KelSolaar** [comment]
@bollu I haven't created a small reproducible case, so it leaves in the repo with the full codebase on this branch: https://github.com/colour-science/colour-analysis/tree/graph_overhaul, dependency wise if you want to run the code I think you need Vispy, Numpy, Scipy, Colour and OpenImageIO (if you don't have it the code should just produce a blank noise image by default).
In order to reproduce the error, the steps are described in my above comment: https://github.com/vispy/vispy/issues/1033#issuecomment-128900503

Let me know if you need anything!

**Comment by KelSolaar** [comment]
I also just noticed that I have now serious performance issues when zooming while orbiting / panning doesn't seem to be affected.

Here is a screen-capture illustrating that: https://drive.google.com/open?id=0B_IQZQdc4Vy8ZEZzQkZQLVB5b2M

The less things displayed, the better though.

**Comment by KelSolaar** [comment]
More on that one, it is related to trackpad gesture somehow: on my Macbook, if I use the two fingers gesture for zooming, the zoom is really choppy as in the screen-capture, however if I use the right click drag gesture for zooming there it is perfectly fluid.

**Comment by KelSolaar** [comment]
I had a bit of time so I managed to do a reproducible simple example for the **nasty** issue:

```python
from vispy.scene import SceneCanvas, ViewBox
from vispy.scene.cameras import TurntableCamera


class Canvas(SceneCanvas):
    def __init__(self):
        SceneCanvas.__init__(self, keys='interactive')

        self.unfreeze()

        self.__view = ViewBox()
        self.__view.camera = TurntableCamera()
        self.__grid = self.central_widget.add_grid()
        self.__grid.add_widget(self.__view)

        self.show()

    def on_key_press(self, event):
        key = event.key.name.lower()
        if key == 'c':
            print('Creating a "TurntableCamera"!')
            self.__view.camera = TurntableCamera()
        else:
            print('Please press "c" key!')


if __name__ == '__main__':
    c = Canvas()
    c.app.run()
```

If you press the **c** key, the event seems to not be processed completely because of the camera creation and just keep happening.

**Comment by KelSolaar** [comment]
Hi,

I'm reporting that this issue is still currently happening with the latest Vispy codebase (I pulled the latest yesterday).

**Comment by kmuehlbauer** [comment]
@KelSolaar @almarklein What's teh current status of this issue? Is it partly solved?

**Comment by KelSolaar** [comment]
@kmuehlbauer : I haven't touched Vispy in many years so I don't know the state of things.

**Comment by KelSolaar** [comment]
Looking at the issue that is referenced it seems like @campagnola fixed the callback problem at least!

**Comment by kmuehlbauer** [comment]
@KelSolaar Thanks for responding. Let's see if @almarklein can clear things up then.

**Comment by almarklein** [comment]
The original issues that I posted are either fixed or not that relevant anymore. The later issue by @KelSolaar seems to be fixed. So lets close!
