### ISSUE TITLE
ENH: More uniform tessellation of spheres

### ISSUE THREAD

**Issue by Eric89GXL** [vispy/vispy#1040]
Right now our sphere tessellation is done using latitute-longitute type calculations, which are not uniform. I have some code for more even tessellation of sphere that I or someone else could add if they feel like it.

**Comment by almarklein** [comment]
A very good approach is to start with a tetrahedon and subdividing N times: https://code.google.com/p/visvis/source/browse/functions/solidSphere.py#14

**Comment by Eric89GXL** [comment]
I have pretty efficient icosahedron and octahedron subdividing, I don't know if those are better or worse

**Comment by almarklein** [comment]
I think the only difference is the exact level of smoothness that you can reach. Each time you do a subdivision, the mesh will be "twice as smooth", you cannot go in between. But you could if you chose a different initial geometry. Don't think that this point will actually be an issue. I'd just pick one shape and go with that :P

**Comment by pradeep-pyro** [comment]
I can take this up if nobody else is assigned. I already have code for sphere generation by subdividing an icosahedron. Btw, will the existing `create_sphere()` function be replaced or do we create a new function say `create_icosphere(radius, subdivisions)`?

**Comment by Eric89GXL** [comment]
I think `create_sphere` could just be enhanced with a `method` argument or so

**Comment by pradeep-pyro** [comment]
Ready for review, please ignore the first closed PR that is mentioned in this conversation, I regret using Github For Windows :P
