### ISSUE TITLE
view.camera.set_range() crashes app

### ISSUE THREAD

**Issue by michaelaye** [vispy/vispy#1041]
I have a small working app using the upcoming SphereVisual and I was playing with large sizes that require to set the camera range.
I read in the Gitter channel that `view.camera.set_range()` should autofit things, but it crashes the app instead:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-027817928a06> in <module>()
     28 axis = visuals.XYZAxis(parent=view.scene, width=5)#,scale=-280, )
     29 
---> 30 view.camera.set_range()
     31 
     32 if __name__ == '__main__' and sys.flags.interactive == 0:

/Users/klay6683/Dropbox/src/vispy/vispy/scene/cameras/base_camera.py in set_range(self, x, y, z, margin)
    270         # Get bounds from viewbox if not given
    271         if all([(b is None) for b in bounds]):
--> 272             bounds = self._viewbox.get_scene_bounds()
    273         else:
    274             for i in range(3):

/Users/klay6683/Dropbox/src/vispy/vispy/scene/widgets/viewbox.py in get_scene_bounds(self, dim)
    148                     if (dim is not None) and dim != axis:
    149                         continue
--> 150                     b = ob.bounds(axis)
    151                     if b is not None:
    152                         b = min(b), max(b)  # Ensure correct order

/Users/klay6683/Dropbox/src/vispy/vispy/visuals/visual.py in bounds(self, axis, view)
    246             view = self
    247         if axis not in self._vshare.bounds:
--> 248             self._vshare.bounds[axis] = self._compute_bounds(axis, view)
    249         return self._vshare.bounds[axis]
    250 

/Users/klay6683/Dropbox/src/vispy/vispy/visuals/visual.py in _compute_bounds(self, axis, view)
    651                     bounds = vb
    652                 else:
--> 653                     bounds = [min(bounds[0], vb[0]), max(bounds[1], vb[1])]
    654         return bounds
    655 

TypeError: 'NoneType' object is not subscriptable
```

The script is this (don't be surprised about the scale in XYZAxis, that's an upcoming PR ;) )

```python
import sys
import numpy as np
from vispy import scene
from vispy.scene import visuals

#
# Make a canvas and add simple view
#
canvas = scene.SceneCanvas(keys='interactive', show=True, bgcolor='w')

view = canvas.central_widget.add_view()
# view.camera = 'turntable'
view.camera = 'arcball'
view.camera.fov = 30

enc = visuals.Sphere(radius=252, parent=view.scene)


# add a colored 3D axis for orientation
axis = visuals.XYZAxis(scale=-280, parent=view.scene,
                       width=5)

view.camera.set_range()

if __name__ == '__main__' and sys.flags.interactive == 0:
    canvas.app.run()
```

**Comment by Eric89GXL** [comment]
Can you change line 649 of `visuals/visual.py` from `else:` to `elif vb is not None:` and see if it fixes your problem?

**Comment by michaelaye** [comment]
I guess you refer to the status in my branch (because in master that reference doesn't make any sense, should I rebase?).
But still not a precise hit here, you must mean line 652 ? https://github.com/michaelaye/vispy/blob/solve_1032_sphere_visual/vispy/visuals/visual.py#L645-L654

It works! Want a PR for that?

**Comment by Eric89GXL** [comment]
Yeah, that's the one. Yes please open a quick PR if you have time

**Comment by michaelaye** [comment]
My editor would like to clean up PEP8 issues with that visual.py. Do I have a GO for that?

**Comment by michaelaye** [comment]
FYI, we had a little discussion on this during the SciPy sprint, and I remember that Luke likes to keep whitespace only lines for indentation (not PEP8 adherent) but to remove whitespace at the end of lines. My editor (Atom) can distinguish between them and only correct the latter, if wished.

**Comment by Eric89GXL** [comment]
Yeah, we talked about it a bit at the sprint back in Paris, and the consensus was that we'd start removing those lines. A lot of editors make it standard to remove them and it's more standard-compliant to do so. We should probably make a PR to do it all at once at some point...

**Comment by Eric89GXL** [comment]
I think that another PR actually fixed those issues in `visual.py`, if you rebase they might be gone already.

**Comment by michaelaye** [comment]
Confirmed. Rebasing has solved this. Closing.
