### ISSUE TITLE
Framebuffer stack problem on Python 2.6 and Travis

### ISSUE THREAD

**Issue by lrvdijk** [vispy/vispy#1042]
You can see the stack traces here:
https://travis-ci.org/vispy/vispy/jobs/73569457#L1851

Removing the line

```
arrow.parent = None
```

and creating the TestingCanvas inside the for loop does not fix the error. Travis build link:
https://travis-ci.org/vispy/vispy/jobs/73603473#L1850

**Comment by Eric89GXL** [comment]
There is also some strange issues with old numpy, see #1110

**Comment by kmuehlbauer** [comment]
Closing this as Python 2.6 support was dropped recently.

Ref:
https://github.com/vispy/vispy/pull/1351
https://github.com/vispy/vispy/pull/1353
