### ISSUE TITLE
Running vispy ipython notebook extension from a remote server

### ISSUE THREAD

**Issue by epifanio** [vispy/vispy#1047]
I just cloned and installed vispy from git
i wanted to give a try to the ipynb examples
i’m using python3 on a remote server, vispy is correctly installed . when I run the webgl_example1 notebook i got the following log : 

```
xdpyinfo:  unable to open display “".

Can't open display
```

is this because i’m running it on a remote host ? 
or do I need to initializate a monitor somehow ? 

the `%load_ext vispy.ipython` shows me : `Vispy IPython module has loaded successfully`

I tryied with both _py2_ and _py3_.

The colormaps notebook works fine.

**Comment by Eric89GXL** [comment]
I am not sure, it's weird that it's trying to open a display. @rossant have you done any of this remotely?

**Comment by epifanio** [comment]
i was 'finally' able to test the example notebooks on my laptop, they are not fully functional, i reported the log [here]([here](https://github.com/vispy/vispy/issues/1081) .

Trying on the remote machine the logs changed with an additional worning :  

```

WARNING: could not determine DPI
WARNING:vispy:could not determine DPI

xdpyinfo:  unable to open display "".


Can't open display 
```

**Comment by julienr** [comment]
I am running into the same issue (I am getting a black canvas). The "Can't open display" actually comes from `util/dpi/_linux.py` trying to run `xrandr` or `xdpyinfo` (adding print before and after the get_dpi call in `app/canvas.py` confirms this). But this is a non-fatal error as get_dpi is called with `raise_error=False`, so I don't think this message is the reason nothing is displayed.

**Comment by julienr** [comment]
Mmh ok actually my problem seem to be that when re-running the cell containing
`c = Canvas(size=(300, 300))` multiple time, after some times, I get an error in the console (in Firefox) saying : `Error: WebGL: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.`

Not sure if this is a separate issue or the same problem as @epifanio

**Comment by Californian** [comment]
Is there any way to run this in a Jupyter Notebook from a remote server yet? I'm still getting the same error.

**Comment by djhoese** [comment]
With the new `jupyter_rfb` backend this is now possible.
