### ISSUE TITLE
Fonts are pixellated on retina displays

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1056]
I am using VisPy on a Mac with a retina display, and when showing axes in plots, the text is not at full resolution for the retina display:

<img width="800" alt="screen shot 2015-08-16 at 2 52 57 pm" src="https://cloud.githubusercontent.com/assets/314716/9293314/b95146bc-4426-11e5-84df-2df058ff22ca.png">

The 'VisPy canvas' text is from the MacOS X window and is at twice the resolution of the 'Wave Fourier' text from VisPy.

**Comment by rossant** [comment]
cc @nippoo

**Comment by rougier** [comment]
It may depend on you backend (GLFW vs Qt). Can you try with GLFW ?

**Comment by astrofrog** [comment]
@rougier - I can't easily try with GLFW, since I'm using conda and there isn't an official package for it. In any case, my use case is for embedding a VisPy plot into a Qt application, so I think I'll need to use Qt for the app backend.

**Comment by rougier** [comment]
Ok. Do you know if your version of Qt handles retina display ?

**Comment by astrofrog** [comment]
@rougier - I'm using PyQt4 and it does seem to handle retina displays. All the text labels I've added inside the app look nice and smooth.

**Comment by rougier** [comment]
Yes, but I suspect things can be different for the GL window. I'm not familiar with Qt but @almarklein or @campagnola can be of some help on this matter.

**Comment by nippoo** [comment]
Yep, Qt4 doesn't seem to present a HiDPI-capable backend to the GL window as @rougier said. GLFW should work. I also presume Qt5 should work, but I haven't tested it...

**Comment by astrofrog** [comment]
Indeed, with PyQt5 the fonts are nice and smooth. There are other issues there but I'll open another issue since this is not related to fonts. I'll close this issue now since it seems this is just a fundamental limitation of PyQt4.
