### ISSUE TITLE
ImageVisual: attaching Isoline Filter - interpolation problem

### ISSUE THREAD

**Issue by kmuehlbauer** [vispy/vispy#1068]
Since ImageVisual is now capable of several interpolation methods, I tried to setup a isoline creation in pure glsl. 

Therefore I took advantage of @rougier https://github.com/glumpy/glumpy/blob/master/examples/isocurves.py for isoline tracing. I adapted this to have isocolor, isowidth and isolevel as parameter to the `Isoline` class. The example can sweep (via Left/Right key) trough the available interpolation functions (plus `bicubic2D` because I want to show the differences) and add/remove isolines with Up/Down. If you remove the comments from the `curve` IsocurveVisual you will get those CPU computed isolines on top.

So far the preamble. The problem you see, when zooming in a bit and switching the interpolations. On my systems only the `bicubic2D` interpolator accounts for clear, smooth isolines. In recent discussions texture precision was claimed as possible issue.

My humble request is, please test this self contained program https://gist.github.com/kmuehlbauer/db681d889cec36c56394 and write your experiences. 

Here are two images which show the behaviour I experience. The differences between the interpolated images are not seen to the human eye, but the isoline trace routine clearly gets them.

This is bicubic interpolation from 1DTexture
![isoline_bicubic](https://cloud.githubusercontent.com/assets/5821660/9340877/c9837820-45f2-11e5-85e8-ba5997d30430.jpg)
This is bicubic2D interpolation (implementation from scratch)
![isoline_bicubic2d](https://cloud.githubusercontent.com/assets/5821660/9340882/cd431358-45f2-11e5-956c-24fcc1bd959b.jpg)

Thanks for the patience!

**Comment by rougier** [comment]
I remember having had the same kind of problem when I used GL_NEAREST instead of GL_LINEAR in the kernel interpolation. In isocurves.py, if you replace 
```
program['u_kernel'].interpolation = gl.GL_LINEAR
```

with

```
program['u_kernel'].interpolation = gl.GL_NEAREST
```

and zoom in  (mouse scroll), you see comparable artefacts. So in the end, the kernel interpolation should be  linear, not nearest (I think I said the contrary in the other thread, sorry)

**Comment by kmuehlbauer** [comment]
@rougier I did experiment with that too, but the improvement is minimal:

![isoline_bicubic_linearkernel](https://cloud.githubusercontent.com/assets/5821660/9341586/14124f70-45f7-11e5-8e4a-8bd0986209b3.jpg)

As matter of fact, on my system(s) only the straight forward bicubic implementation produces nice results. I have this here on four different systems, all linux flavours. Anyway, do you get the other results when you change the kernel texture interpolation to 'linear' with the VisPy implementation?

**Comment by kmuehlbauer** [comment]
@Eric89GXL could this Isoline class go into visuals/filters as discussed in the Interpolation PR #1051? WDYT? Only thing, this works for me only with the straighforward bicubic implementation. Could you test the gist file, if you find time?

**Comment by rougier** [comment]
I get no isolines at all.

**Comment by Eric89GXL** [comment]
@rougier you probably need to use "up" to increase the number of isolines, I had no lines until I did that.

`bicubic2D` is the only one that is artifact-free for me, although it introduces a shift (downward and rightward). I see similar artifacts that you see @kmuehlbauer.

@kmuehlbauer I suppose this could be a type of filter you could use. I'm trying to think where else it might be useful. We might want to wait until @campagnola can comment on the appropriateness of it as a `filter` -- I think he designed that system, so he might know how it fits best.

**Comment by kmuehlbauer** [comment]
@rougier the isoline filter is attached after the first Up/Down key operation, because it needed a rendered scene first for correct operation. 

@Erix89GXL, ahh the shift, I had fixed this already, must be reintroduced by copy and paste. 

At the moment this works only on 2D if I correctly understood the isoline tracer, but it should be extended to use 3 dimensions as well. I'll have a look.

**Comment by rougier** [comment]
Ok, got them.

One of the problem might be this line in isoline:
```
float value = gl_FragColor.r;
```

You should instead read the value from texture directly because I'm not sure of the content of the fragment at this stage.

**Comment by kmuehlbauer** [comment]
@rougier, this is intended, this should fit in visuals as a filter. If I understood the concept of visual/filters they can work on gl_FragColor like this color filter from visuals/filters:

```
class ColorFilter(object):
    def __init__(self, filter=(1, 1, 1, 1)):
        self.shader = Function("""
            void apply_color_filter() {
                gl_FragColor = gl_FragColor * $filter;
            }
        """)
        self.filter = filter
    
    @property
    def filter(self):
        return self._filter
    
    @filter.setter
    def filter(self, f):
        self._filter = tuple(f)
        self.shader['filter'] = self._filter
        
    def _attach(self, visual):
        self._visual = visual
        hook = visual._get_hook('frag', 'post')
        hook.add(self.shader(), position=8)
```

They just grab the output of gl_FragColor of the parent Visual and add their function on that. Maybe @campagnola can have a look if the isoline filter has some flaws.

But nevertheless, I get same effects when I read from texture directly. It seems, that setting the kernel texture precision to 'r16f' did not finally solve the issue.

**Comment by rougier** [comment]
What about isocurves.py from glumpy, does it work as expected ?

**Comment by kmuehlbauer** [comment]
This is with latest glumpy, and it doesn't change whether gl_NEAREST or gl_LINEAR is used for kernel texture interpolation. I'll test on other system too.
![glumpy_isocurves](https://cloud.githubusercontent.com/assets/5821660/9349719/0922e0ea-464a-11e5-9319-ac2c0ae37d6a.png)

**Comment by rougier** [comment]
Could you try to change

```
program['u_kernel'] = data.get("spatial-filters.npy")
```

to

```
program['u_kernel'] = (data.get("spatial-filters.npy")).view(gloo.TextureFloat2D)
```

**Comment by kmuehlbauer** [comment]
Yessss...
![glumpy_isocurves_floattex](https://cloud.githubusercontent.com/assets/5821660/9349966/9dae8afa-464c-11e5-86f4-9a2472d71ed4.png)

**Comment by kmuehlbauer** [comment]
Ups, it's not available in vispy.gloo yet. @rougier do you have plans to incorporate this also within VisPy?

**Comment by rougier** [comment]
I guess we'll have to implement it at some point. What I don't quite understand is why it does not work with your implementation. Do you have access to r32f instead of r16f in the texture object ?

**Comment by kmuehlbauer** [comment]
Now I think I finally have it.

This gives smooth lines on almost interpolation methods, with some glitches.
```
self._kerneltex = Texture2D(self._kernel, interpolation='nearest',
                                    internalformat='r32f')
```

With `linear`, as you suggested it works perfectly, the two bicubic implementations are identical. And the others work also more nice.
```
self._kerneltex = Texture2D(self._kernel, interpolation='linear',
                                    internalformat='r32f')
```

So, this was again a problem with precision and the 'r16f' didn't do the trick in the first place, but 'r32f' in combination with 'linear' does. So I will have an PR ready for ImageVisual to correct for that. 

@rougier thanks again for guidance.

**Comment by rougier** [comment]
Cool.
