### ISSUE TITLE
Texture arrays

### ISSUE THREAD

**Issue by gregersn** [vispy/vispy#1080]
I am trying to look into how to implement support for Texture arrays with Vispy. 
That is, the possibility to use sampler2DArray and texture2DArray in the fragment shaders.
And I am sure I could get most of the job done with doing that myself, I am just not quite sure how to load/add OpenGL extensions with Vispy, and could use a few pointers as to where to look.

I have come to the point where shader compilation gives me something like this:
 on line 7: error C7531: global function texture2DArray requires "#extension GL_EXT_texture_array : enable" before use or #extension GL_NV_texture_array : enable

**Comment by campagnola** [comment]
Can these `#extension` directives appear anywhere within the shader code, or is it necessary to put them at the beginning?

**Comment by queenish001** [comment]
@gregersn Did you get the answer?

**Comment by gregersn** [comment]
I wish I could remember. But sadly I can not.

**Comment by djhoese** [comment]
Given the age of this and that no one probably remembers what was going on, I'm going to close this. I'm sure it is possible, but at this time vispy doesn't provide any builtin way of doing an array of textures that I know of. The "cheating" way of doing it I think would be a 3D texture, but even that has its problems I'm sure. If someone is looking for a solution to this problem in the modern age, please create a new issue. Thanks.
