### ISSUE TITLE
Different output when run inside IPython

### ISSUE THREAD

**Issue by ngoldbaum** [vispy/vispy#1083]
I have an example that I'm working on to visualize the star particles in one my galaxy simulations.

The example is here: https://bitbucket.org/ngoldbaum/vispy-particles/src/87622390c16412af3a6b497e76b6ceaffbe48059/blackbody_stars_galaxy.py?at=default&fileviewer=file-view-default

When I run the example outside of IPython, the camera ends up centered on the origin of vispy's coordinate system, staring down one of the axes:

![image](https://cloud.githubusercontent.com/assets/3126246/9795590/2bd51be8-57b7-11e5-8e94-424c6030e75a.png)

However, when I run the exact same script inside of IPython using the `%run` magic, the view ends up centered elsewhere:

![image](https://cloud.githubusercontent.com/assets/3126246/9795652/7b8d9228-57b7-11e5-86d4-b1b06cbb9a91.png)

If you'd like me to upload the data file I'm using in my script so you can reproduce locally, let me know.

**Comment by bollu** [comment]
What version are you running on? (IPython, as well as VisPy).

And yes please, a data file would help :) Along with a `.ipynb` if you're using a notebook

**Comment by ngoldbaum** [comment]
So I've just rewritten my example for this bug report and the issue seems to have stopped happening?

Perhaps unsatisfying, but given that I'm not able to reproduce my own issue here I'm going to close this...

**Comment by Eric89GXL** [comment]
Feel free to reopen if it comes back. It's possible it's an intermittent bug. If it comes back, try resizing the window to see if that "fixes" the problem. If it does, it suggests a `resize` event might be missed.
