### ISSUE TITLE
Routing events for multi-canvas ganged views?

### ISSUE THREAD

**Issue by karlcz** [vispy/vispy#1090]
Can you recommend a way to have mouse, keyboard, and resize events on one canvas get delivered to other canvases in the same app, with a way to turn this routing on and off? Ideally, I'm looking for an idiom that can be layered on top of an existing canvas implementation and its handlers for local events, so I can continue to use it as a single-canvas application or in this new multi-canvas form...

I have an existing visualization as a gloo app (not using any of the vispy scene/visual stuff). This renders one data file. I want to make a ganged interaction mode where several renderers are looking at different data files with the same mouse-based rotations, translations, etc.  The canvases have separate gloo contexts since they have completely different data loaded into textures, etc.  But, they share the same responses to UI events.

Another use case might open a single file but show several views on it. In this case, I'd need to decouple the events to allow manual setup of different views in each window, but then for example relink the events so that this array of views would be further manipulated as a gang.  In this case, I might try to share a gloo context to reuse some textures; I only mention that in case it would effect event handling options.

**Comment by karlcz** [comment]
I solved my problem with running two canvases but would still appreciate advice on the mouse/keyboard event routing to allow ganged control of two canvases. Should I edit this issue to refocus it, or is that frowned upon in your community...?

**Comment by Eric89GXL** [comment]
Yes please edit the title. I'm not sure the cleanest way to ensure events go both places. Maybe @almarklein or @campagnola have some ideas.

**Comment by Eric89GXL** [comment]
(you can also edit the description if you want, but please comment in that case that you've done it so that people know they'll need to re-read it)

**Comment by karlcz** [comment]
I've updated this issue title and description to focus on an event-routing problem I face...

**Comment by almarklein** [comment]
My first thought is to use the scenegraph and make the plots share a camera. Is this feasible for what you want to do? If not, what do you have now and what is the remaining problem?

**Comment by karlcz** [comment]
@almarklein, I have my own custom app.Canvas sub-class, not using any
of the vispy scene or visual infrastructure.  It currently runs as a
standalone app, calling only gloo APIs and defining methods
on_keypress, on_resize, on_mouse_press, on_mouse_move,
on_mouse_release, on_mouse_wheel, and on_draw with its own monolithic
interaction model and custom, multi-pass GLSL renderers for
ray-casting, object picking etc.

I'd like to keep this overall structure if possible, since it remains
useful and easy enough to maintain and extend for experimentation.
So, what I really want is to allow the canvas receiving a
user-generated event to react normally with its current handlers but
also add a new handler that can redistribute the event and re-inject
it into peer canvases in the same multi-canvas app so their normal
handlers can process it, but distinguishing these events somehow so
that I don't end up with a rebroadcast loop.

I have considered monkey-patching the canvas instances in the
multi-view app, but wonder if there is any clean place to patch rather
than explicitly mangling every individual on_whatever handler
method...?

**Comment by almarklein** [comment]
Maybe you can put a variable on the event object that tells what its originating canvas is, and use that to avoid re-broadcasting? This seems like a very special case though, so you can expect to need a "special solution" :P

**Comment by karlcz** [comment]
I forgot about this old issue... closing since I don't think it is relevant to anyone.
