### ISSUE TITLE
Ben Cipollini: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by bcipolli** [vispy/vispy#1091]
I am looking for web-based visualizations for my Python analysis code. To start, I can probably help build tests while I learn about the capabilities.<p><br><blockquote>This issue was created by @bcipolli via <a href='http://collaborate.mozillascience.org'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by Eric89GXL** [comment]
@rossant @almarklein you are probably best to talk about this.

**Comment by Eric89GXL** [comment]
@bcipolli if you're still interested, we can try to figure out what you can do. Seems like you've been productive over on nibabel :) In the meantime I'll close this issue, feel free to comment anyway if you're still interested and need tips about things to work on.
