### ISSUE TITLE
Event for unicode characters not just hardware keys.

### ISSUE THREAD

**Issue by alexjc** [vispy/vispy#1092]
Currently it's not possible to determine what character the users pressed (in their own locale), only a standard keycode is returned.  The GLFW backend for example has support with a function called `glfwSetCharCallback` which returns a stream of unicode.

Do you want this kind of support in VisPy? It makes things possible like text-based input or mapping by key name (in a locale correct way) rather than by keycode.  If so, I can add the events and GLFW support relatively easily.

**Comment by alexjc** [comment]
I made a prototype that I'm currently using for an interactive console. See #1093 for my thoughts on implementing this. It's much simpler than I expected!

**Comment by Eric89GXL** [comment]
PR merged
