### ISSUE TITLE
Running basics/plotting/plot.py example fails

### ISSUE THREAD

**Issue by Overdrivr** [vispy/vispy#1096]
I cannot run this example
<https://github.com/vispy/vispy/blob/master/examples/basics/plotting/plot.py>

I get the following error, line 21
```
plot() got an unexpected keyword argument 'title'
```

**Comment by kuldeepdhaka** [comment]
:+1: same for me.

**Comment by kuldeepdhaka** [comment]
@Overdrivr trying to run repo example on 0.4 ?
(when i downloaded 0.4 source and run them, they worked fine.)
title, xLabel and yLabel are looks new to me.

**Comment by delooper** [comment]
I also have the same problem, running Vispy 0.4. Most of the repo demonstrations work, but strangely this very basic one does not. If I remove title, it complains about xlabel.  If I remove xlabel it complains about ylabel.  If I remove that, it won't run with "too many coordinates given (1000; max is 2)."

**Comment by delooper** [comment]
This one also appears to be fixed in 0.5.0 dev0
