### ISSUE TITLE
Matplotlib Backend not found

### ISSUE THREAD

**Issue by lcota** [vispy/vispy#1099]
How do you get the matplotlib backend to work? Should I be setting this in the matplotlibrc file, or elsewhere?

**Comment by Eric89GXL** [comment]
There is still pretty incomplete support for it. You can't do it by setting up matplotlibrc, but by calling something after making a Matplotlib plot. See an example here:

https://github.com/vispy/vispy/blob/master/examples/basics/plotting/mpl_plot.py

**Comment by delooper** [comment]
vispy.mpl_plot plots all come up blank.  The viewing window appears, this one is broken into 3 subplots.  But no data is rendered in the plot. 

Do you have a sense for what might be causing this?

**Comment by delooper** [comment]
I installed 0.5.0 dev0 and the problem went away.

**Comment by Eric89GXL** [comment]
The `matplotlib` backend isn't really actively developed. @astrofrog I think we might want to remove it for 0.5 actually. It was experimental for 0.4 IIRC anyway.
