### ISSUE TITLE
Could not import backend "Glfw"

### ISSUE THREAD

**Issue by Yanniclord** [vispy/vispy#1100]
When i try running the command "python shadertoy-render.py gargantua-SUHD.glsl out.mp4 --size=3840x2160 --rate=60 --duration=120.0"  from alexjc its ShaderToy Render python file (https://github.com/alexjc/shadertoy-render), i get this error code:

>lokeyourlord@lokeyourlord-VirtualBox:~/Desktop/shadertoy-render-master$ python shadertoy-render.py gargantua.glsl out.mp4 --size=3840x2160 --rate=60 --duration=120.0
Traceback (most recent call last):
  File "shadertoy-render.py", line 133, in <module>
    vispy.use(app='glfw')
  File "/home/lokeyourlord/anaconda3/lib/python3.4/site-packages/vispy/util/wrappers.py", line 84, in use
    vispy.app.use_app(app)
  File "/home/lokeyourlord/anaconda3/lib/python3.4/site-packages/vispy/app/_default_app.py", line 46, in use_app
    default_app = Application(backend_name)
  File "/home/lokeyourlord/anaconda3/lib/python3.4/site-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/lokeyourlord/anaconda3/lib/python3.4/site-packages/vispy/app/application.py", line 204, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Glfw":
>GLFW library not found

What can i do to fix this? I tried in numerous ways to install custom libraries, as well as starting fresh, just install numpy and vispy (along follows of course pyopengl and such), but nothing has worked so far. Help is appreciated :)

**Comment by Yanniclord** [comment]
Ok i managed to get GLFW3 installed by doing "sudo apt-get install libglfw3", but now i get this:

>lokeyourlord@lokeyourlord-VirtualBox:~/Desktop/shadertoy-render-master$ python shadertoy-render.py gargantua.glsl out.mp4 --size=3840x2160 --rate=60 --duration=120.0
ffmpeg: error while loading shared libraries: libssl.so.10: cannot open shared object file: No such file or directory
pci id for fd 7: 80ee:beef, driver (null)
OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
OpenGL Warning: glVertexArrayRangeNV not found in mesa table
OpenGL Warning: glCombinerInputNV not found in mesa table
OpenGL Warning: glCombinerOutputNV not found in mesa table
OpenGL Warning: glCombinerParameterfNV not found in mesa table
OpenGL Warning: glCombinerParameterfvNV not found in mesa table
OpenGL Warning: glCombinerParameteriNV not found in mesa table
OpenGL Warning: glCombinerParameterivNV not found in mesa table
OpenGL Warning: glFinalCombinerInputNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glDeleteFencesNV not found in mesa table
OpenGL Warning: glFinishFenceNV not found in mesa table
OpenGL Warning: glGenFencesNV not found in mesa table
OpenGL Warning: glGetFenceivNV not found in mesa table
OpenGL Warning: glIsFenceNV not found in mesa table
OpenGL Warning: glSetFenceNV not found in mesa table
OpenGL Warning: glTestFenceNV not found in mesa table
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
Traceback (most recent call last):
  File "shadertoy-render.py", line 163, in <module>
    duration=args.duration)
  File "shadertoy-render.py", line 88, in __init__
    self.size = (size[0] / self.pixel_scale, size[1] / self.pixel_scale)
  File "/home/lokeyourlord/anaconda3/lib/python3.4/site-packages/vispy/app/canvas.py", line 340, in size
    size[1] * self._px_scale)
  File "/home/lokeyourlord/anaconda3/lib/python3.4/site-packages/vispy/app/backends/_glfw.py", line 330, in _vispy_set_size
    glfw.glfwSetWindowSize(self._id, w, h)
>ctypes.ArgumentError: argument 2: <class 'TypeError'>: Don't know how to convert parameter 2

**Comment by Eric89GXL** [comment]
The shared library thing is a warning from ffmpeg, might not be relevant. Can you run the examples from the `vispy` repo? I suspect the example you're trying to run requires some extensions you don't have -- it looks like it's trying to use some NVIDIA extensions, but you're rendering using MESA perhaps.

The type error is strange. After getting the error, can you do:
```
>>> import pdb; pdb.pm()
(pdb) p (self._id, w, h)
(pdb) p type(w)
```

**Comment by Yanniclord** [comment]
Sure, just let me start up my Virtual Machine :)

**Comment by Eric89GXL** [comment]
Ahh, if you're in a VM you're most likely using software rendering. Try some of the simpler examples first, I suspect the OpenGL warnings stem from using a complicated shadertoy example that uses NVidia-specific extensions.

**Comment by Yanniclord** [comment]
Well, i really want to render this thing, and i did create system links and all, but on windows i cannot get the GFWL3 to work at all :/

**Comment by Yanniclord** [comment]
See, this i found out gets the GFWL3 library for LINUX: "sudo apt-get install libglfw3".
But what do i do on Windows with Anaconda? I tried everything from installing VisPy and NumPy to installing custom libs, but i then get that error i put up in the first post.

**Comment by Eric89GXL** [comment]
Are you running a linux VM only because you couldn't get it to work on Windows (your VM host)?

Try the Windows binaries here:

http://www.glfw.org/download.html

**Comment by Eric89GXL** [comment]
(GLFW is not a Python library, but a generic window/GL library. `vispy` ships with Python wrappers that can access it.)

**Comment by Yanniclord** [comment]
Ye i did use LINUX for that purpose mostly (i use it for other small stuff though). I try that, see if it works. Ok so now i have the Windows Binaries, where do i put them?

**Comment by Eric89GXL** [comment]
I can't remember exactly, you could try moving the "lib-vc2013/glfw3.dll" to C:\Windows\System32 or the 64-bit equivalent if you are on 64-bit. You might need to read a bit about how to install shared dll files on Windows to debug it. But `vispy` should tell you if it's able to load it or not.

You could also try getting rid of the `vispy.use` line altogether, I don't *think* GLFW is actually required for shadertoy examples -- that line might be unnecessary.

**Comment by Yanniclord** [comment]
You mean remove the "vispy.use(app='glfw')" on line 133 in the shadertoy-render.py script file?

**Comment by Yanniclord** [comment]
Well ok so i did that, now i get this: 

>Traceback (most recent call last):
  File "shadertoy-render.py", line 155, in <module>
    stdin=subprocess.PIPE)
  File "C:\Anaconda3\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
>

That last part is in German, sorry. It says "The system cannot find the specified file"

**Comment by Eric89GXL** [comment]
I'm not sure I can help you much further since I'm not too familiar with what "shadertoy-render-master" is, but it sounds like it can't find the file you're trying to load.

**Comment by Yanniclord** [comment]
Well the shadertoy render is exactly what it says. However, i dont know what file it is trying to load. I did install all the Anaconda libs, if you need more info just ask, i get what you need.

**Comment by Yanniclord** [comment]
So ye, i actually just added the "vispy.use" line back, and also added the GLFW libs to System32 and SysWow64, and it seems to not give me that error anymore. However, now i get the exact same error as i would receive without the "vispy.use" line. It fails to find whatever file it cant find.

**Comment by Eric89GXL** [comment]
I don't think that is a problem with `vispy`, so much as a general path issue. It sounds like it can't find the GLSL file you're trying to load. You could potentially use `pdb` to try to figure out what file it can't find, but it's probably better if you ask the creators of the `shadertoy-render.py` script.

**Comment by Yanniclord** [comment]
Well, if the creators would be answering questions i would, but thank you for the help so far. I did also try to specify the whole path, i think i just try a bit more, then i ask that dev (if he is even still alive). Thanks for the help, i close this thread now :)

**Comment by Yanniclord** [comment]
Wait, one more thing: Could you tell me what commands i have to run exactly to get pdb to show me what i need? I am new to this, so i wanna start off with something like this so i can see where i can work myself further up.

**Comment by Eric89GXL** [comment]
`p` is print, so you can print whatever variables you want. This is probably a decent tutorial of the debugger:

https://pythonconquerstheuniverse.wordpress.com/2009/09/10/debugging-in-python/

**Comment by Yanniclord** [comment]
Ok thanks, i will see if i can get it to work.
