### ISSUE TITLE
Using Scene is slow

### ISSUE THREAD

**Issue by aracid** [vispy/vispy#1102]
Hi there

Using vispy with any example using the scene infrastructure is sticky/slow.

I've tested this by bypassing the scene node and just update the vbo and rotation matrix on the camera manually its fine however when using any of the examples that use the scene cameras, 

I'm testing on 0.5.0dev0 

Thanks in advance
Brian

**Comment by Eric89GXL** [comment]
We have a generic issue open for this in #894, feel free to comment on specific use cases over there. Closing this as dup.

**Comment by Eric89GXL** [comment]
Or I guess #628 is the correct issue
