### ISSUE TITLE
Widget.remove_widget calls Widget.remove_parent, but this method does not exist

### ISSUE THREAD

**Issue by inclement** [vispy/vispy#1105]
This is called at https://github.com/vispy/vispy/blob/master/vispy/scene/widgets/widget.py#L348

I guess maybe the fix is just to do 'widget.parent = None' instead, but I'm not sure how this has come about or if there is more to it.

**Comment by inclement** [comment]
I see this is left behind from when Widget inherited from Node (which no longer has that method either) - actually I'm not sure Widget even tracks its parent any more, should both the setting and unsetting of this be removed from the add_widget and remove_widget methods?

**Comment by Eric89GXL** [comment]
I don't think it should be necessary anymore, but @campagnola should know
for sure

**Comment by queenish001** [comment]
@campagnola :)

**Comment by djhoese** [comment]
It looks like this was fixed and we would have run into this by now so I'm closing this. Thanks for identifying it @queenish001.
