### ISSUE TITLE
Raise exceptions

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#1106]
How to raise exceptions when an error occurs during drawing, instead of logging it? This is to make sure that unit tests fail when an exception occurs during drawing.

**Comment by Eric89GXL** [comment]
IIRC there isn't a good way currently since it happens in the event loop of the backend. Although maybe if you use `app.process_events()` to do the drawing it would throw the error?

**Comment by almarklein** [comment]
When you're running an event loop, any errors that occur during handling of an event are caught and logged. No errors fall are "uncaught".

However, when an error occurs during handling a vispy event, we set `sys.last_value` and friends to allow postmortem debugging. So maybe you can set that to `None` and afterwards check that it is still `None`.

**Comment by rossant** [comment]
If I detect that `sys.last_value` is not None, how do I print the last exception?

FWIW I think it isn't a good practice for a library to catch its own exceptions...

**Comment by almarklein** [comment]
> If I detect that sys.last_value is not None, how do I print the last exception?

you can print it, `last_value` is the exception instance. `last_traceback` has the traceback info.

> FWIW I think it isn't a good practice for a library to catch its own exceptions...

That's what (almost) all event driven frameworks do: catch uncaught errors in callbacks, show the exception, and then continue main loop.

**Comment by Eric89GXL** [comment]
Closing as something we can't really fix, but feel free to reopen if there is a proposal I'm missing @rossant
