### ISSUE TITLE
Vispy always tries to import gl2 by default

### ISSUE THREAD

**Issue by inclement** [vispy/vispy#1109]
At https://github.com/vispy/vispy/blob/master/vispy/gloo/gl/__init__.py#L235-L238, vispy always tries to import gl2 and call use_gl with 'gl2' as the default argument. This fails on Android (and I assume other places) because only gles is available. I fixed it for that by patching to import es2 by default instead.

I'd like to change it so that Vispy works without modification on Android, but I'm not sure how since gloo.gl does need to import something as a default. One option would be to try the current method, then if it fails catch the Exception and try es2 instead, but I'm not sure if there are downsides to that.

Any ideas?

**Comment by Eric89GXL** [comment]
I think it would be fine to try to import the most compete gl possible. We
could triage based on platform or fall back as you suggest. Systematically
going from most compete to most restrictive GL seems like it would work
well.

**Comment by almarklein** [comment]
I think ideally you would detect the platform; when its Android or Raspberry pi use es2, otherwise use gl2.

**Comment by Eric89GXL** [comment]
@inclement do you have time to try the autodetection?

**Comment by inclement** [comment]
Sure, but I missed this - is that something now in master?

**Comment by Eric89GXL** [comment]
Sorry, I meant try *implementing* the autodetection :)

**Comment by inclement** [comment]
Oh, right! In that case, still sure, it's been on my list of things to
try for a while but hasn't been a priority. I might return to Vispy on
Android soon to try to get it working properly, in which case I'll
certainly take a loot at it.

**Comment by stuaxo** [comment]
I may be able to implement code to detect raspberry pi if you let me know where it should go.

**Comment by djhoese** [comment]
@kmuehlbauer What does rpi do for this? Does it have a full GL library available or only ES?

Either way I'm moving this to 0.7.

**Comment by kmuehlbauer** [comment]
@djhoese There seems to be not much detailed information out there. According to the specs it is

- OpenGL ES 1.1, 2.0 graphics for Raspberry Pi 3B+
- OpenGL ES 3.0 graphics for the new Raspberry Pi 4
