### ISSUE TITLE
Window freezes

### ISSUE THREAD

**Issue by oskarsinger** [vispy/vispy#1117]
I tried running the sample code on this page: http://vispy.org/plot.html, and the plot window freezes a few seconds after I run "fig = Fig()". Then, none of the rest of the code works. 

Also, you need to transpose the data matrix for the dimensions to be what your code expects.

**Comment by bollu** [comment]
could you elaborate on what you mean "freezes and doesn't work"? are you able to get a (blank) window open?

**Comment by oskarsinger** [comment]
It gets a blank window open, yes. Then the window goes a few shades darker and stops responding before I ever alter the figure.

**Comment by kmuehlbauer** [comment]
Please reopen with added information, if needed.
