### ISSUE TITLE
Test script freezes.

### ISSUE THREAD

**Issue by oskarsinger** [vispy/vispy#1118]
At the test on 'iso-something curve capabilities', the test just freezes as far as I can tell.

**Comment by bollu** [comment]
AFAIK, It tries to download data to render before it actually brings up the UI. I think the workflow should be fixed to show a loading bar or something, however.

**Comment by oskarsinger** [comment]
Yes, that would be nice.

**Comment by kmuehlbauer** [comment]
The https://github.com/vispy/vispy/blob/master/examples/basics/scene/isocurve_updates.py example uses pure python marching-squares algorithm which can be really slow. Installation of scikit-image will use more performant algorithm.
