### ISSUE TITLE
Clarify the installation instructions

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#1120]
The default installation instructions should appear clearly on the website:
- install miniconda/anaconda
- `conda install numpy vispy pyqt`
- install the latest proprietary GPU drivers
- run some of the examples
- note that the test suite might be unstable on some systems, which is somewhat unrelated to the working state of the examples

**Comment by Eric89GXL** [comment]
PR welcome

**Comment by 00krishna** [comment]
I can write a PR for the doco if you want. Do you just want the change in the README.rst or elsewhere?

**Comment by 00krishna** [comment]
PR #2 submitted under vispy/vispy-website for this change.
