### ISSUE TITLE
Running examples/demo/scene/scrolling_plots.py fails

### ISSUE THREAD

**Issue by kaklik** [vispy/vispy#1122]
If I try to run examples/demo/scene/scrolling_plots.py a black window is created and stdout is filled by this output:

$ python scrolling_plots.py 
INFO: Could not import backend "PyQt4":
cannot import name QtOpenGL
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Traceback (most recent call last):
  File "scrolling_plots.py", line 55, in <module>
    app.run()
  File "/home/kaklik/repos/vispy/vispy/app/_default_app.py", line 62, in run
    return default_app.run()
  File "/home/kaklik/repos/vispy/vispy/app/application.py", line 137, in run
    return self._backend._vispy_run()
  File "/home/kaklik/repos/vispy/vispy/app/backends/_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "/home/kaklik/repos/vispy/vispy/app/backends/_qt.py", line 657, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/kaklik/repos/vispy/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/kaklik/repos/vispy/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/home/kaklik/repos/vispy/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/kaklik/repos/vispy/vispy/scene/canvas.py", line 207, in on_draw
    self._draw_scene()
  File "/home/kaklik/repos/vispy/vispy/scene/canvas.py", line 253, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/kaklik/repos/vispy/vispy/scene/canvas.py", line 291, in draw_visual
    node.draw()
  File "/home/kaklik/repos/vispy/vispy/scene/visuals.py", line 98, in draw
    self._visual_superclass.draw(self)
  File "/home/kaklik/repos/vispy/vispy/visuals/visual.py", line 440, in draw
    self._vshare.index_buffer)
  File "/home/kaklik/repos/vispy/vispy/visuals/shaders/program.py", line 77, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/kaklik/repos/vispy/vispy/gloo/program.py", line 470, in draw
    canvas.context.flush_commands()
  File "/home/kaklik/repos/vispy/vispy/gloo/context.py", line 171, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/kaklik/repos/vispy/vispy/gloo/glir.py", line 232, in flush
    self._shared.flush(parser)
  File "/home/kaklik/repos/vispy/vispy/gloo/glir.py", line 146, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/kaklik/repos/vispy/vispy/gloo/glir.py", line 458, in parse
    self._parse(command)
  File "/home/kaklik/repos/vispy/vispy/gloo/glir.py", line 430, in _parse
    ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer
  File "/home/kaklik/repos/vispy/vispy/gloo/glir.py", line 1071, in set_size
    gl.GL_BYTE, shape[:1])
  File "/home/kaklik/repos/vispy/vispy/gloo/glir.py", line 1162, in glTexImage1D
    width, border, format, type, None)
  File "/usr/lib/python2.7/dist-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/usr/lib/python2.7/dist-packages/OpenGL/wrapper.py", line 792, in wrapperCall
    raise err
GLError: GLError(
	err = 1281,
	description = 'invalid value',
	baseOperation = glTexImage1D,
	pyArgs = (
		GL_TEXTURE_1D,
		0,
		GL_RGB32F,
		10000,
		0,
		GL_RGB,
		GL_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_1D,
		0,
		GL_RGB32F,
		10000,
		0,
		GL_RGB,
		GL_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_1D,
		0,
		GL_RGB32F,
		10000,
		0,
		GL_RGB,
		GL_BYTE,
		None,
	)
)
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f8a8abfe5d0>> for DrawEvent
INFO: Program has unset variables: set([u'u_trans_max', u'u_mag', u'u_trans', u'pos_size', u'u_enabled', u'u_translate', u'u_center', u'pos_offset', u'u_id_color', u'u_scale_2', u'u_view', u'u_filter', u'u_scale_1', u'u_color', u'u_radii', u'offset', u'u_scale', u'u_translate_2', u'u_translate_1', u'position'])
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f8a8abfe5d0>> repeat 2
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f8a8abfe5d0>> repeat 4
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f8a8abfe5d0>> repeat 8
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7f8a8abfe5d0>> repeat 16
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>
WARNING: Error drawing visual <ScrollingLines at 0x7f8a64b26dd0>

python -c "import vispy; print(vispy.sys_info())"  creates this output: 

Platform: Linux-3.19.0-31-generic-x86_64-with-Ubuntu-15.04-vivid
Python:   2.7.9 (default, Apr  2 2015, 15:33:21)  [GCC 4.9.2]
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.4.1', '5.4.1')
pyside:   None
pyglet:   None
glfw:     None
sdl2:     sdl2 0.9.3
wx:       wxPython 3.0.1.1
egl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES OpenGL_ES2 OpenGL_ES3
osmesa:   OSMesa
_test:    None

GL version:  u'3.0 Mesa 10.5.9'
MAX_TEXTURE_SIZE: 8192

**Comment by rossant** [comment]
What is your GPU? Mesa is badly supported by VisPy, so you might have better luck with proprietary drivers (notably if you have an NVIDIA card).

**Comment by QuLogic** [comment]
You probably need to change the dimensions of the plot. It's 10000 points in each row, but your GL only supports 8192 pixels for textures. Just cut it to 8000 or something less and I think it will work.

**Comment by kaklik** [comment]
Thanks QuLogic! I have set N = 5000 on line 29 and the example starts to work! 
The resulting plot is gigantic even with this setting. Therefore I think it should be better to modify example for working on most machines.  I have tried two different computers with different GPU's  according to  rossant  answer. But I was successful only on one with GeForce GTX560 Ti. Standard integrated Intel GPU cannot handle previous original textures settings.

**Comment by Eric89GXL** [comment]
@kaklik feel free to open a PR to tweak the example, I agree it would be useful

**Comment by braingram** [comment]
see pull request #1126

**Comment by kaklik** [comment]
@braingram Yes it is the simplest solution. I have tried to create a code which could set the N value based on vispy.sys_info() data. But I have not found a simple solution.
