### ISSUE TITLE
SceneGraph: shared_context.py example broken

### ISSUE THREAD

**Issue by kmuehlbauer** [vispy/vispy#1123]
The example should create two canvases which share a visual. The visual is only rendered in the second canvas.

I'm aware that multi-parenting was removed from the SceneGraph recently.  IIRC this should be replaced by the ability to create different views of one scene. 

Is it possible to have one scene viewed from different angels (eg. top view, front view and side view) without recreating the scene three times? Can the shared_context.py example be made working?

**Comment by Eric89GXL** [comment]
Shared context is more for when you want to share OpenGL objects across multiple *OpenGL contexts*, what you're probably looking for is sharing one *scene* across multiple *viewboxes* (which typically all live inside the same OpenGL context). I think this might be what you are looking for:

https://github.com/vispy/vispy/blob/master/examples/basics/scene/one_scene_four_cams.py

But yes the shared context example is currently broken, closing this as dup of #862
