### ISSUE TITLE
Use sphinx-apidoc to create API docs fully automatic

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#113]
Right now we specify all classes manually. sphinx-apidoc does it fully automated and generates a nice index too.

**Comment by kmuehlbauer** [comment]
The docs were removed from this repo with ec00f7fea7682c79c1face192d4cd35fcbf7285e and added to the vispy-website repository with https://github.com/vispy/vispy-website/commit/970ba3b547ca7fb71686fc49ea3c83a0b51b3c42. 

AFAICT this issue transferred with this move to the https://github.com/vispy/vispy-website repo also. 

I'll close this one and create a new one over there.
