### ISSUE TITLE
Multichannel viewer (Qt/VisPy)

### ISSUE THREAD

**Issue by cimbi** [vispy/vispy#1135]
Hi,
I started working on a multichannel viewer for EEG data using Qt. Right now I am using pyqtgraph library for this but I'd like to switch to VisPy. I am just wondering if there is anybody else already working on this so I don't reinvent the wheel. I noticed things like:

https://www.youtube.com/watch?v=arSLMooNfHY

But nothing for Qt and Vispy so far.

**Comment by kmuehlbauer** [comment]
Resolved with #1217

**Comment by davidh-ssec** [comment]
@kmuehlbauer How does #1217 fix this issue?

**Comment by kmuehlbauer** [comment]
Argh, wrong windows. Issue #1133 was meant.

**Comment by kmuehlbauer** [comment]
BTW, @cimbi Did you find any solutions for your specific problem?

**Comment by campagnola** [comment]
@cimbi, you might consider http://github.com/pyacq/pyacq as a starting point.

**Comment by cimbi** [comment]
@campagnola thanks! That looks great. I think I'll make a fork and try to use Vispy for visualization..

**Comment by campagnola** [comment]
@cimbi while you're headed that way, check out the vispy PR: https://github.com/pyacq/pyacq/pull/50

**Comment by kmuehlbauer** [comment]
@cimbi I'll close this issue for now. It seems that @campagnola set you on the right track.
