### ISSUE TITLE
Allow unclipped float32 textures

### ISSUE THREAD

**Issue by vasole** [vispy/vispy#114]
The current limitation of having to pass 32-bit floating point textures normalized in the [0., 1.] interval becomes quite penalizing because the normalization has to be carried at the Python side. 

It would be nice if you could provide the user the option not to be full OpenGL ES compliant. The default behavior could be kept as now.

**Comment by almarklein** [comment]
You can now do `gloo.gl.use_gl('gl+')` and then use `gl.GL_ANY_DESKTOP_ENUM`
