### ISSUE TITLE
Incorrect size before resizing, when using visuals

### ISSUE THREAD

**Issue by mdelorme** [vispy/vispy#1140]
Hi, 

I'm having a problem and can't figure if it is a bug or something I completely overlooked. When I am using visuals with a homemade subclass of SceneCanvas. In my app everything works perfectly as long as I don't use visuals. When i do, the rendering appears shrunk a lot and gets to the right size only when I resize the window. This was not happening before but I moved to the latest commit on `master`, and since then it does not seems to be working.

Here is a minimal example :

``` python
import vispy
from vispy import scene
from vispy import app
from vispy import gloo
from vispy import visuals

class Frame(scene.SceneCanvas):
    def __init__(self):
        super(Frame, self).__init__(size=(800, 800))
        self.unfreeze()
        self.x_legend = visuals.TextVisual(u'Temperature', font_size=20., color=(1,1,1,1))
        self.y_legend = visuals.TextVisual(u'Luminosity', font_size=20., color=(1,1,1,1), rotation=-90)
        self.x_axis = visuals.AxisVisual(pos=((self.size[0]*0.1, self.size[1]*0.9),(self.size[0]*0.1, self.size[1]*0.1)))
        self.y_axis = visuals.AxisVisual(pos=((self.size[0]*0.1, self.size[1]*0.1),(self.size[0]*0.9, self.size[1]*0.1)),tick_direction=(0.0, 1.0))


    def on_resize(self, event):
        self.size = event.size
        gloo.set_viewport(0, 0, *self.size)
        self.adjust_visuals()


    def adjust_visuals(self):
        self.x_legend.pos = (self.size[0] / 2, self.size[1]*0.975)
        self.y_legend.pos = (self.size[0]*0.025, self.size[1] / 2)
        self.x_axis.pos = ((self.size[0]*0.075, self.size[1]*0.925),(self.size[0]*0.075, self.size[1]*0.075))
        self.y_axis.pos = ((self.size[0]*0.075, self.size[1]*0.925),(self.size[0]*0.925, self.size[1]*0.925))

        self.x_legend.transforms.configure(canvas=self, viewport=(0, 0, self.size[0], self.size[1]))
        self.y_legend.transforms.configure(canvas=self, viewport=(0, 0, self.size[0], self.size[1]))
        self.x_axis.transforms.configure(canvas=self, viewport=(0, 0, self.size[0], self.size[1]))
        self.y_axis.transforms.configure(canvas=self, viewport=(0, 0, self.size[0], self.size[1]))

    def on_draw(self, event):
        gloo.clear(color=True, depth=True)

        self.adjust_visuals()

        self.x_legend.draw()
        self.y_legend.draw()
        self.x_axis.draw()
        self.y_axis.draw()


if __name__ == '__main__':
    f = Frame()
    f.show()
    app.run()
```

Here are two images showing the problem :

Before resizing :
![minimal1](https://cloud.githubusercontent.com/assets/2743366/11713064/eacafa50-9f28-11e5-9105-cb2f4fccaa00.png)

After resizing :
![minimal2](https://cloud.githubusercontent.com/assets/2743366/11713063/eaca5e38-9f28-11e5-9bad-f54e8a192394.png)

The problem appears no matter what backend I choose (I tried Pyqt4 and GLFW)

I'm not entirely sure if it is a bug or something I overlooked :) So I'd be glad if you had any answer !

**Comment by campagnola** [comment]
Any reason you are drawing the visuals yourself instead of using the scenegraph?

**Comment by mdelorme** [comment]
Yes, I need to use gloo to draw pure opengl objects before and after the rendering of the visuals. I didn't figure a way to do this in a clean way using scenegraph.

**Comment by queenish001** [comment]
@mdelorme Is this resolved now?

**Comment by djhoese** [comment]
Given the age of this issue I'm guessing this isn't really an issue any more. Either you aren't working on this or it was fixed by someone over the last 6 years. There have been some fixes to resizing updates for some backends, but I agree with Luke's original question. There is a lot of functionality provided by SceneCanvas that would help here and you're directly overriding it. As for your need of drawing opengl objects before/after rendering the visuals, this would like be implemented as a custom subclass of a visual or a new visual altogether.

If this is still an issue and something you want to work on we can reopen this, but for now I'm closing it.
