### ISSUE TITLE
Volume rendering dataset >1 Gb causes error

### ISSUE THREAD

**Issue by ronpandolfi** [vispy/vispy#1141]
I am volume rendering an array. When subsampling my data set it works fine, but with the full array it doesn't display, and produces the linked error. I have 2 GTX Titan cards, so I guess its not a GPU memory issue? The linked unsolved github post sounds similar. The data set is 1.2 GB in full.

Fails: (540,1058,2120) array
Works: (540,1058,1060) array

http://pastebin.com/UWCNDHTS
http://stackoverflow.com/questions/29687320/vispy-get-error-gl-invalid-value-when-data-is-too-large

**Comment by campagnola** [comment]
You can see many reasons for getting INVALID_VALUE here:
https://www.opengl.org/sdk/docs/man2/xhtml/glTexImage3D.xml
The most likely is that the texture exceeds MAX_TEXTURE_SIZE, which you can see by calling `print(vispy.sys_info())`.

**Comment by ronpandolfi** [comment]
On my system, MAX_TEXTURE_SIZE is 16384, so this limit is far greater than each dimension of my array:
> GL_INVALID_VALUE is generated if width, height, or depth is less than 0 or greater than 2 + GL_MAX_TEXTURE_SIZE.

**Comment by karlcz** [comment]
I can't explain why 1060 works for you and 2120 doesn't unless it is rejecting anything over 2048.  But I have also experienced problems if the major axis is not 16-pixel aligned with my own volume rendering tools (using gloo but not the vispy volume visual).

**Comment by tperciano** [comment]
I'm experiencing the exact same issue using a dataset of size (1992, 2288, 100). I have 2 Titan Black cards. Had anyone come up with a solution for that problem? I would really appreciate some help. Thanks!

conda version : 4.5.9
conda-build version : 3.0.27
python version : 3.5.4
platform : linux-64
vispy: 0.6.0.dev0
PySide2: 5.9.0a1

**Comment by djhoese** [comment]
@tperciano Just to make sure, you are getting the exact same error as the original poster and your data works fine if you stride (subsample) it?

**Comment by tperciano** [comment]
@djhoese Exactly!

**Comment by karlcz** [comment]
Have you tried padding your data out to a multiple of a larger
power of 2?

As I recall, NVIDIA requires 3D textures to be aligned but the
alignment requirements are different for each axis, and I don't
recall the exact values off hand.

If I were you, I would try padding 1992 -> 2048 as a first test. If
that works, you can search for a smaller alignment in between. But,
you might also have to align the 2288 to a higher multiple like
32 instead of 16.


Karl

On Aug 14, Talita Perciano modulated:

**Comment by tperciano** [comment]
@karlcz I see... I will give it a try! I will keep you guys updated.

BTW Thank you @djhoese @karlcz for the prompt response!

**Comment by djhoese** [comment]
My only other thought beyond the alignment would be some GPU memory allocation issue like not being able to allocate all of that memory in one chunk. But I wouldn't expect that to show up as an error and I also would expect GPU drivers to be smart about handling that.

So alignment or driver bug/limitation?

**Comment by tperciano** [comment]
@karlcz @djhoese I tried padding the data but it didn't solve the problem. However, after looking around a little bit more I think I found the issue. Taking a look at some info using glxinfo, there is a "GL_MAX_3D_TEXTURE_SIZE = 2048" entry. So, I believe that's what's limiting the rendering...

**Comment by djhoese** [comment]
Interesting, so there is a separate limiting factor for textures. I suppose that makes sense since a max texture size of 16384 on a 3D texture is ~4400GB where as 2048 is ~8.5GB. If you limit your array to 2048 or less in each dimension does that still work?

**Comment by tperciano** [comment]
So, I did some tests with different datasets... it seems that as long as I limit the arrays to 2048 in each dimension, everything works fine!

**Comment by djhoese** [comment]
Awesome @tperciano. Thanks for testing all of this. I think I'm going to close this as a limitation of the hardware and it just took forever to figure out because it isn't something `vispy.sys_info()` current lists (and I don't think it needs to be necessarily). Not anything vispy can do.

**Comment by tperciano** [comment]
@djhoese Can I ask you a related question though? I've mentioned before that I have 2 GPUs. I was just wondering if vispy would be able to use both of them to handle the 3D rendering in parallel. I mean, theoretically that would double the limit we've been talking about. Would that be possible?

**Comment by karlcz** [comment]
Normally, linking two GPUs with OpenGL would duplicate the same data
onto both and just divide the pixel filling and texture sampling
workload between them. This has the least application-visible
programming impact, but they'd still show the same overall limits.

To work with a larger volume than the 3D texture size limits, you
would need to use multiple textures, each meeting the texture size
limit.  A 2048**3 texture is 8 gigavoxels so you can already imagine
having larger volumes than this with 8-bit single channel data on a
single recent large-RAM GPU.  Of course, volumes often lack 1:1:1
aspect ratio, so you can easily hit the per-axis limit even with
multiple channels or higher bit-depths.

Using multiple textures is basically a block-decomposition of the
naive volume rendering method where the entire volume is in one
texture.  This either adds conditional logic to the inner loop for a
ray casting algorithm (to switch between texture samplers as you move
along the ray) or requires adopting a more image-based method where
you can separately render blocks and then sort and blend these
intermediate images to make the final scene.

Complicating the rendering path to handle multiple textures will make
it slower, so you'll find it even less practical for interactive use
(and even the naive renderer is already struggling when you are
talking about large volumes on high resolution displays).  I think
many volume rendering projects are abandoned around this point when
the developer discovers that they are no longer working on an
interactive problem, and there are many other non-interactive tools
with rich feature sets already...


Karl

**Comment by tperciano** [comment]
Thank you @karlcz, that's very informative and helpful!
