### ISSUE TITLE
ColorArray can't be initialized with numpy arrays

### ISSUE THREAD

**Issue by glyg** [vispy/vispy#1142]
Hi,

Thank you for making vispy.

It would be nice to be able to pass a numpy array of hex colors to ColorArray, but this is not working.
Is there a good reason for this?

Here is the (https://github.com/vispy/vispy/blob/master/vispy/color/color_array.py#L49)[relevant code]

``` python
def _user_to_rgba(color, expand=True, clip=False):
...
    elif isinstance(color, (list, tuple)):
        if any(isinstance(c, string_types) for c in color):
            color = [_user_to_rgba(c, expand=expand, clip=clip) for c in color]
            if any(len(c) > 1 for c in color):
                raise RuntimeError('could not parse colors, are they nested?')
            color = [c[0] for c in color]
```

Maybe just writing:
 `elif isinstance(color, (list, tuple, np.ndarray))` here would be enough?

I can prepare a small PR with this and a test if you want.

Best,

Guillaume

**Comment by flutefreak7** [comment]
Perhaps using Abstract Base Classes to check for the desired behavior instead of checking classes explicitely...

If we were only meaning to check for things like lists and tuple, I'd say use Sequence, but numpy.ndarray fails checking for Sequence, I think because ndarray has the potential to represent a 0-d scalar/container.  Checking Iterable ensures it can be iterated over, and checking Sized makes sure it has __len__ (so it won't accept an infinite generator).  This would be more robust than checking specific classes.  This would also accept pandas.Series, for example, another very common list-like class, or something like a custom color class - so long as it's iterable.

    from collections.abc import Iterable, Sized
    ...
    isinstance(color, (Iterable, Sized))

**Comment by glyg** [comment]
Didn't know about `collections.abc`, but sounds like the right thing to do!

**Comment by Eric89GXL** [comment]
There are some reasons to prefer it actually be an `ndarray` as oppose to a generic iterable variable. For example, using `tostring()` to dump data bytes, reconfiguring data order, checking dtype, etc. are all facilitated by using `numpy`. When putting data onto the GPU these things have to be taken into consideration. It's not impossible to do with any generic iterable class, but it's a lot easier to have people provide data as `ndarray`, or something that can be cast that way. So I'm -1 on going to ABC, and maybe just making judicious use of `np.asarray()` calls in the right places.

**Comment by Eric89GXL** [comment]
Ahh, sorry, didn't read the issue fully. This is a bit different than the use case I had in mind...

Doing some sort of iterable checking might actually be reasonable. But one problem with that is it might inadvertantly catch iterable things (like `ndarray` or list of RGBA values) that are iterable, but should probably be cast directly to the right size array, as opposed to being transformed using string-checking. Not sure what an elegant solution would be.

**Comment by glyg** [comment]
Doing some cleaning, and I think this is very outdated. I'm closing this issue, feel free to reopen if still relevant

**Comment by djhoese** [comment]
Thanks @glyg. I think if anyone wants to do what was discussed in this issue and it isn't already possible, please file a new issue.

side question: @glyg are you just going through old issues you've created and cleaning them out? I admire the time this must take.

**Comment by glyg** [comment]
Yes that's exactly what I was doing :) I did not have _that_ much to go through
