### ISSUE TITLE
allow more than three sided polygons in `vispy.io.writemesh()`

### ISSUE THREAD

**Issue by glyg** [vispy/vispy#1155]
Hi,

Wavefront OBJ file format allows faces with more than 3 vertices, according to [wikipedia](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Face_Elements).

The `WavefrontWriter` class currently only supports triangular faces, due to the reshape happening here:

https://github.com/vispy/vispy/blob/master/vispy/io/wavefront.py#L307

```python
        # Reshape faces
        Nfaces = faces.size // 3
        faces = faces.reshape((Nfaces, 3))
```

I think commenting out these lines, and being more specific in the docstring regarding the format of the `faces` argument is enough to allow that, as `writefaces` doesn't explicitly expects `val` to have 3 elements.

I think the users understand they need to pass `faces` such that it iterates over the faces any way, so even for triangles, `faces` is already passed a a (NFaces, 3) ndarray. 

To ensure backward compat, maybe the above lines can be wrapped in a try block?

**Comment by glyg** [comment]
A quick follow up:

I did the above on my local repo, tests are passing and I can write polygonal meshes in .OBJ, which are parsed correctly by blender.

Here is a simple example:

```python
from vispy.io import write_mesh

vertices = np.array([[ 0.5  ,  1.375,  0.   ],
                     [ 0.5  ,  0.625,  0.   ],
                     [ 3.25 ,  1.   ,  0.   ],
                     [ 1.   ,  0.375,  0.   ],
                     [ 2.   ,  0.375,  0.   ],
                     [ 1.5  ,  0.625,  0.   ],
                     [ 1.5  ,  1.375,  0.   ],
                     [ 1.   ,  1.625,  0.   ],
                     [ 2.   ,  1.625,  0.   ]])

faces = np.array([[1, 0, 7, 6, 5, 3],
                  [4, 5, 6, 8, 2]])
write_mesh('vp_test.obj', vertices=vertices,
           faces=faces, normals=None, 
           texcoords=None, overwrite=True)
```

Here is the generated file:
```
# Wavefront OBJ file
# Created by vispy.
#
# unnamed object
# 9 vertices, no texcords, no normals, 2 faces

v 0.5 1.375 0.0
v 0.5 0.625 0.0
v 3.25 1.0 0.0
v 1.0 0.375 0.0
v 2.0 0.375 0.0
v 1.5 0.625 0.0
v 1.5 1.375 0.0
v 1.0 1.625 0.0
v 2.0 1.625 0.0
f 2 1 8 7 6 4
f 5 6 7 9 3
```

Note that this file **cannot be read back by vispy**, as raised here:
https://github.com/vispy/vispy/blob/master/vispy/io/wavefront.py#L178

It is nevertheless a valid .OBJ file. Maybe a warning can be issued at writing time, eg:
 
```python
    try:
        Nfaces = faces.size // 3
        faces = faces.reshape((Nfaces, 3))
    except ValueError:
        logger.warning('''Faces doesn't appear to be triangular, be advised the file won't be read back by vispy''')

What are your thoughts?

I can submit a PR if you want.

**Comment by almarklein** [comment]
That sounds like it could be useful. a PR would be good!

**Comment by glyg** [comment]
sure, I'll get into it rapidly
