### ISSUE TITLE
Any solution to the OS X OpenGL 2.1 vs 3.0 problem?

### ISSUE THREAD

**Issue by gapster** [vispy/vispy#1157]
I just installed vispy to try it out.  I'm on OS X, python 2.7 installed by Anaconda.   I get this error:

 WARNING: OpenGL version 3.0 or higher recommended, got 2.1 NVIDIA-10.4.2 310.41.35f01. Some functionality may fail.

It says warning, but the demos don't run.  They print that message and nothing else happens.  (I have to kill the process manually.)   A search returned mention of this problem, but no solution or work-around.  My OpenGL.__version__ reports 3.1.  Is there a solution to this?

**Comment by philshvarcz** [comment]
See [this thread] (https://github.com/vispy/vispy/issues/1138).

**Comment by gapster** [comment]
Yes, I saw that, and the thread that links to.  It looks like the same question, but no answer.

**Comment by larsoner** [comment]
Closing for #952 as I think that would indeed fix this problem
