### ISSUE TITLE
Lag between VisPy and Qt window when using a Qt MDI area

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1158]
I am using VisPy inside a Qt widget, which is inside a Qt MDI area - minimal code here:

https://gist.github.com/astrofrog/aa1b4a490e61b82f9aa7

When I move around the window inside the MDI area, the Qt window and VisPy canvas are out of sync:

<img width="1394" alt="screen shot 2016-01-20 at 4 33 10 pm" src="https://cloud.githubusercontent.com/assets/314716/12455449/add1a686-bf93-11e5-9fab-46f278bf4a9a.png">

A video of the effect can be found here: https://www.youtube.com/watch?v=wBg8SRpa580&feature=youtu.be

Is this a bug in the Qt canvas for VisPy?

**Comment by campagnola** [comment]
Looks like a Qt bug to me. I can't think of anything we could do within vispy to avoid that.
I'm going to close this for now, but please reopen if you find otherwise..
