### ISSUE TITLE
Text isn't occluded properly

### ISSUE THREAD

**Issue by kaymes** [vispy/vispy#1165]
When using the Text visual in a 3D scene graph, occlusion of text isn't handled properly. 
All visuals that were created after the text was added to the scene will "occlude" the text even if the text is in front.
All visuals that were created before the text cannot occlude the text and the text remains visible regardless.

It seems that the text is not properly incorporated into the 3D scene and instead it is just painted over.

I created a demo scene to illustrate the issue. Note how the numbers are always visible through the green plane, even when the numbers are behind the green plane. The red plane always hides the numbers, even when numbers are in front of the plane.

``` python
import numpy as np
import vispy
import vispy.scene

canvas = vispy.scene.SceneCanvas(keys='interactive', bgcolor=(1,1,1))
canvas.show()

view = canvas.central_widget.add_view()
view.camera = vispy.scene.TurntableCamera(up='z', fov=60)

view.camera.set_range(x=(-5, 5), y=(-5, 5), z=(-5, 5))

x_coords = np.array((-5,5))
y_coords = np.array((-5,5))
z_data = np.array([(3,3),(3,3)])

item = vispy.scene.visuals.SurfacePlot(x=x_coords, y=y_coords, z=z_data, color=(0, 1, 0, 1))
view.add(item)

for i in range(-5, 5):
    item = vispy.scene.Text(text="%i" % i, color='black', bold=True, font_size=200, pos=(0,0,i))
    view.add(item)

item = vispy.scene.visuals.SurfacePlot(x=x_coords, y=y_coords, z=-z_data, color=(1, 0, 0, 1))
view.add(item)

vispy.app.run()
```

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
This is a drawing order issue. It can be worked around by forcing the drawing order with `.order` on each of the visuals. Here is the result:

![image](https://user-images.githubusercontent.com/1828519/142741570-4cb21a0f-3293-49d9-8d53-027aecfde827.png)

When I set the first surface to `.order = 3`, the text to `.order = i`, and the last surface to `.order = -3`.

**Comment by djhoese** [comment]
Given the age of this issue I'm going to close this assuming that I probably won't get a response and that I provided a reasonable workaround.

**Comment by kaymes** [comment]
@djhoese you still get a response. Even though I'm not using vispy anymore in my current projects.

The workaround wouldn't have helped though. Because the issue remains that the text occlusion isn't calculated correctly. All you've done is to manually wirk out the occlusion for this particular scene and camera angle. In the example posted here, if you start moving the camera to a new position, e.g. looking from below rhe red plane, it will be all wrong again.

The app I was working on at the time had vehicles driving around and their name was hovering above each vehicle. You could then see the name of vehicles even when they where behind a mountain or similar which was rather odd and ugly. Working out the occlusion manually in such a setting would have been about impossible.

But like I said, I'm no longer working on this so you can leave the issue closed - unless you actually want to solve the occlusion issue properly. :-)

**Comment by djhoese** [comment]
Ugh you are absolutely right. I thought I had checked looking from the red surface. We definitely want to make this easier or just fix it all around, but there are also other similar issues. I think I'll reopen this as it is a pretty simple and clear example compared to some of the others I've seen.

**Comment by almarklein** [comment]
Could it be as simple that the text visual is not writing to the depth buffer?

**Comment by djhoese** [comment]
Very likely. I don't have much experience with the text visual or writing to the gl_FragDepth. @almarklein any chance you have a little time to throw together a PR?

**Comment by almarklein** [comment]
Probably not this week. I'll keep the notification open in my mailbox, so I can see if I can find some time next week or so.

**Comment by isamabdullah88** [comment]
@djhoese 
Is there anyway we can display a 3D text in a view? TextVisual currently can only display 2D text, as far as I've seen! Please correct me if I'm wrong.
