### ISSUE TITLE
version 0.5 ETA 

### ISSUE THREAD

**Issue by evizbiz** [vispy/vispy#1169]
Thanks for this awesome resource. Is there a schedule for the next version release?

**Comment by astrofrog** [comment]
It would be great to have a release, given that quite a lot has changed since 0.4!

**Comment by etale-cohomology** [comment]
I'm also very interested in this!

**Comment by rossant** [comment]
Agreed! @Eric89GXL do you think you'll have time to tackle this?

**Comment by Eric89GXL** [comment]
Hmm... maybe next month? @bollu will you have time to polish your grid PR?

**Comment by bollu** [comment]
I'm not really sure, I have a lot of college work on my plate. If we break
it up into sub tasks, then I think I can do it with a timeline in mind

**Comment by astrofrog** [comment]
@Eric89GXL - is there any reason not to release the package as-is, since it's already significantly improved compared to v0.4? It's taking a fair bit of effort to support v0.4 and the latest developer version and I would much rather support only v0.5 and drop support for v0.4.

**Comment by Eric89GXL** [comment]
Sometime needs to find time to do it. All the steps (at least uploading to
PyPi, updating the website, changing version numbers, making announcements,
probably others I'm forgetting) usually takes a number of hours. I don't
have time now unfortunately.

**Comment by astrofrog** [comment]
@campagnola @rossant @almarklein - would any of you have time to do a release?

If not, sorry for the noise, but I just wanted to check before I take the drastic step of bundling the latest developer version of VisPy in Glue - at the moment, supporting VisPy 0.4 and the latest developer version is costing me days of development, and I'm now running into the issue that some critical features in the developer version are missing from 0.4, so I have no other choice.

(On a more general note, VTK 7.0 is out with Python 3 support and OpenGL by default, so it would be good to keep the releases up to stay competitive)

**Comment by evizbiz** [comment]
Is there a detailed set of (step-by-step) instructions for performing a release? In not, please provide some info, and I'll attempt to script it in bash or python. Then proceed from there?

**Comment by Eric89GXL** [comment]
@evizbiz we are working on this actively now, cleaning up for a 0.5 release. It won't be perfect (look at the issue log, yikes!) but hopefully it will get things moving more.

**Comment by evizbiz** [comment]
Cool! Thanks for the feedback; and thanks for keeping the dream alive. :)

**Comment by femtogram** [comment]
Any update on this? I'm pretty excited for a vispy release :)

**Comment by hadim** [comment]
Same here. Any updates ?

**Comment by jakirkham** [comment]
This should probably be closed as there is another issue ( https://github.com/vispy/vispy/issues/1322 ) that duped this one, but has more active discussion relevant to this issue.
