### ISSUE TITLE
hide mouse pointer

### ISSUE THREAD

**Issue by meduz** [vispy/vispy#1170]
When designing a stimulus for a psychophysics experiment, we need to hide the mouse's pointer. 

I have found nothing in the examples / code, though I guess it's possible.

**Comment by rossant** [comment]
This might be the responsibility of the backend. Which backend are you using? For example, in Qt, I found [this SO thread that might be helpful](http://stackoverflow.com/questions/19930794/qt-4-8-hide-cursor-in-fullscreen).

**Comment by meduz** [comment]
Thanks for the quick answer!
I am using the pyglet backend on MacOsX 10.11.

**Comment by rossant** [comment]
[this](http://pyglet.readthedocs.org/en/latest/programming_guide/mouse.html#changing-the-mouse-cursor)?

I think you can retrieve the pyglet window with `canvas.native` or something like that...

**Comment by meduz** [comment]
:+1: 
exactly, that made the trick:
`c.native.set_mouse_visible(False)`

**Comment by rossant** [comment]
great!
