### ISSUE TITLE
vispy.app.Canvas.__init__ behaviour deprecated

### ISSUE THREAD

**Issue by miktoki** [vispy/vispy#1171]
The default behaviour of initializing `vispy.app.Canvas` seems to be utilizing `paint` instead of `draw`

```
app.Canvas.__init__(self)
```

 "... miniconda/lib/python3.4/site-packages/vispy/app/canvas.py", line 162, in **init**
    self.events.add(paint=emitter)
  File "... /miniconda/lib/python3.4/site-packages/vispy/util/event.py", line 662, in add
    emitter.connect((self.source, self.auto_connect_format % name))
  File "... /miniconda/lib/python3.4/site-packages/vispy/util/event.py", line 528, in connect
    self._warn(cb)
  File "... /miniconda/lib/python3.4/site-packages/vispy/util/event.py", line 543, in _warn
    traceback.print_stack()
WARNING: Canvas.events.paint and Canvas.on_paint are deprecated; use Canvas.events.draw and Canvas.on_draw instead.
WARNING:vispy:Canvas.events.paint and Canvas.on_paint are deprecated; use Canvas.events.draw and Canvas.on_draw instead

using version '0.5.0.dev0'

**Comment by larsoner** [comment]
This example is not complete so I can't replicate. Feel free to provide a fully working minimal example showing the problem if you have time
