### ISSUE TITLE
port signal processing of gravitational waves example to vispy.plot

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#1173]
The [example IPython notebook](https://losc.ligo.org/s/events/GW150914/GW150914_tutorial.html) that shows off the gravitational waves data uses matplotlib. It would be cool to see the same plots rendered in VisPy using `vispy.plot` and the IPython/Jupyter interface.

**Comment by rossant** [comment]
Good idea! Do you know if there's the code/data somewhere for the 3D simulation of the black hole merger and GW?

**Comment by bollu** [comment]
Nope, but I could hunt for it tonight :)

**Comment by larsoner** [comment]
Closing, someone feel free if they have time though
