### ISSUE TITLE
Missing tiles in rendering of isosurface example

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1174]
Running the ``examples/basic/scene/isosurface.py`` example produces the following output for me with the latest developer version of VisPy:

![screen shot 2016-02-23 at 12 22 25 pm](https://cloud.githubusercontent.com/assets/314716/13251448/43442af0-da28-11e5-8c18-0e506db488cd.png)

That doesn't seem quite right since by default one shouldn't be seeing through the main isosurface. It looks like some tiles are missing?

**Comment by PennyQ** [comment]
@astrofrog Yeah, this could be fixed by setting 
`canvas = scene.SceneCanvas(keys='interactive', config={'depth_size': 24})`
here is a issue for reference https://github.com/vispy/vispy/issues/896

**Comment by astrofrog** [comment]
@PennyQ - ok thanks! I'll close this as a duplicate of #896
