### ISSUE TITLE
Depth order incorrect with isosurface visual

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1175]
If I run the following simple example for an isosurface:

```python
import sys
import numpy as np

from vispy import app, scene

# Create a canvas with a 3D viewport
canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()


data = np.arange(1000).reshape(10, 10, 10)

surface = scene.visuals.Isosurface(data, level=data.max()/4.,
                                   color=(0.5, 0.6, 1, 1.0), shading=None,
                                   parent=view.scene)

surface2 = scene.visuals.Isosurface(data, level=data.max()/2.,
                                   color=(1.0, 0.2, 0.2, 1), shading=None,
                                   parent=view.scene)


axis = scene.visuals.XYZAxis(parent=view.scene)

cam = scene.TurntableCamera(elevation=30, azimuth=30)
cam.set_range((-10, 10), (-10, 10), (-10, 10))
view.camera = cam
```

I get the right output from some viewing angles:

![screen shot 2016-02-23 at 12 28 19 pm](https://cloud.githubusercontent.com/assets/314716/13251590/24a5bf0e-da29-11e5-90ef-3cd202a1fd39.png)

but if I turn it around, and look from a point of view where the red should be in front of the blue, there are artifacts:

![screen shot 2016-02-23 at 12 28 26 pm](https://cloud.githubusercontent.com/assets/314716/13251600/36082426-da29-11e5-92f8-7a04d6ccb175.png)

**Comment by rougier** [comment]
Maybe depth_test is off ?

**Comment by astrofrog** [comment]
@rougier - I don't think so: ``IsoSurfaceVisual`` uses ``MeshVisual`` which includes this line:

```python
        self.set_gl_state('translucent', depth_test=True,
                          cull_face=False)
```

**Comment by astrofrog** [comment]
@rougier - just out of curiosity, do you also see this issue? I'm trying to figure out if all my issues are somehow related to OpenGL version?

**Comment by rougier** [comment]
Yes, I got this issue. It's hard to tell where is the problem (I've becoming unfamiliar with scene stuff).

**Comment by astrofrog** [comment]
This appears to be fixed by setting depth_size to 24:

canvas = scene.SceneCanvas(keys='interactive', config={'depth_size': 24})

as suggested by @PennyQ in #1174. As such, this is a duplicate issue of #896, so I'll close it.
