### ISSUE TITLE
Issue with transparency in isosurface

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1176]
If I run the following example:

``` python
import sys
import numpy as np

from vispy import app, scene

# Create a canvas with a 3D viewport
canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()


data = np.arange(1000).reshape(10, 10, 10)

surface = scene.visuals.Isosurface(data, level=data.max()/4.,
                                   color=(0.5, 0.6, 1, 0.1), shading=None,
                                   parent=view.scene)

surface2 = scene.visuals.Isosurface(data, level=data.max()/2.,
                                   color=(1.0, 0.2, 0.2, 1), shading=None,
                                   parent=view.scene)


axis = scene.visuals.XYZAxis(parent=view.scene)

cam = scene.TurntableCamera(elevation=30, azimuth=30)
cam.set_range((-10, 10), (-10, 10), (-10, 10))
view.camera = cam
```

the first isosurface visual should be almost transparent (alpha=0.1) but instead it is opaque:

![screen shot 2016-02-23 at 12 31 43 pm](https://cloud.githubusercontent.com/assets/314716/13251637/63419832-da29-11e5-8196-6ee71f12f7fa.png)

**Comment by rougier** [comment]
You have to turn blending on  think.

**Comment by astrofrog** [comment]
@rougier - could you provide an example of how to do this? Thanks!

**Comment by rougier** [comment]
I do not know actually, hence my enigmatic answer :)
I'll look into that.

**Comment by rougier** [comment]
`gloo.set_state(blend=True)`

**Comment by astrofrog** [comment]
@rougier - unfortunately this doesn't seem to make any difference - does it work for you?

**Comment by rougier** [comment]
Yes, I added it just after your last line:
```
gloo.set_state(blend=True)
canvas.show()
app.run()
```

**Comment by astrofrog** [comment]
@rougier - did you change anything else? At the moment I have:

```python
import sys
import numpy as np

from vispy import app, scene
from vispy import gloo

# Create a canvas with a 3D viewport
canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()


data = np.arange(1000).reshape(10, 10, 10)

surface = scene.visuals.Isosurface(data, level=data.max()/4.,
                                   color=(0.5, 0.6, 1, 0.1), shading=None,
                                   parent=view.scene)

surface2 = scene.visuals.Isosurface(data, level=data.max()/2.,
                                   color=(1.0, 0.2, 0.2, 1), shading=None,
                                   parent=view.scene)

axis = scene.visuals.XYZAxis(parent=view.scene)

cam = scene.TurntableCamera(elevation=30, azimuth=30)
cam.set_range((-10, 10), (-10, 10), (-10, 10))
view.camera = cam

gloo.set_state(blend=True)
canvas.show()
app.run()
```

with the latest dev version of vispy, and it doesn't work. I'm on MacOS X 10.8. Could it be an OpenGL version thing?

**Comment by rougier** [comment]
Yes, just pulled from master, Python 3.5, MacOS X 10.11 (El Capitan)

**Comment by astrofrog** [comment]
@rougier - what OpenGL version are you using? It looks like I have ``2.1 NVIDIA-8.16.80 310.40.00.20f04``, but can you confirm whether yours is more recent?

**Comment by rougier** [comment]
```
$ glxinfo
...
OpenGL vendor string: ATI Technologies Inc.
OpenGL renderer string: AMD Radeon R9 M370X OpenGL Engine
OpenGL version string: 2.1 ATI-1.40.16
OpenGL shading language version string: 1.20
...
```

**Comment by rougier** [comment]
But I doubt this would be a problem. To test, you can any simple demo (gloo) and change the color for a transparent  + blending enabled and you'll see if this works.

**Comment by liubenyuan** [comment]
@astrofrog 

You should draw surface2 first, and then surface, the second isosurface will be transparent, see

![capture](https://cloud.githubusercontent.com/assets/171338/13917813/132c4bf0-ef9e-11e5-9b60-c8c56066bda0.PNG)

@rougier 

Also, there is a bug in `IsosurfaceVisual` class in `visuals/isosurface.py`, where the `color` parameter may not work. For example,  in your example, it will generate two `isosurface` with the same color (default = 0.5, 0.5, 1.0, 1.0). For example,

![capture](https://cloud.githubusercontent.com/assets/171338/13917891/aebd2058-ef9e-11e5-9ae9-f6526eca61c5.PNG)

A work around is passing the color parameter to `set_data`,

```python
self.set_data(data, color=color)
```

in line 42 of `visuals/isosurface.py`.

I think a PR is required to fix this problem. But I do not know whether this fix would affect other demos.

**Comment by rougier** [comment]
@astrofrog Does the (merged) fix by @liubenyuan fixed your problem ?

**Comment by larsoner** [comment]
This one sounds fixed, closing. Feel free to reopen if not. FYI if it's not fixed, the proper fix might need to be `surface.set_gl_state(blend=True)`
