### ISSUE TITLE
Segmentation fault when finding OpenGL version

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1177]
The following code segfaults for me on MacOS X 10.8:

```python
In [1]: from vispy.gloo import gl

In [2]: gl.glGetParameter(gl.GL_VERSION)
/Users/tom/miniconda3/envs/dev35/bin/python.app: line 3: 15223 Segmentation fault: 11  /Users/tom/miniconda3/envs/dev35/python.app/Contents/MacOS/python "$@"
```

what could this be due to, and are there other ways to find the OpenGL version?

**Comment by Eric89GXL** [comment]
You might need to have an active context to query that parameter

**Comment by astrofrog** [comment]
@Eric89GXL - could you provide an example of how to define an OpenGL context with ``vispy.gloo``? I tried the following but still end up with the same crash:

```python
In [1]: from vispy.gloo.context import GLContext

In [2]: context = GLContext()

In [3]: from vispy.gloo import gl

In [4]: gl.glGetParameter(gl.GL_VERSION)
```

Thanks!

**Comment by rougier** [comment]
An open GL context means you have to create a GL window where and then you ask for the GL_VERSION.

**Comment by astrofrog** [comment]
@rougier - ah I see, it works now, thanks! For info, I get:

```
2.1 NVIDIA-8.16.80 310.40.00.20f04
```
