### ISSUE TITLE
add light to plot.Fig

### ISSUE THREAD

**Issue by bendichter** [vispy/vispy#1185]
Is there a way to change the position of the light source, or add another light to a plot.Fig? I have a mesh that is too dark when I rotate it. The code I have now is simply 

```
fig = Fig(config={'depth_size': 24})
ax = fig[0, 0]
m = ax.mesh(vertices=vert, faces=tri, color=[.4, .4, .4])
app.run()
```

**Comment by almarklein** [comment]
The mesh being too dark may be related to some issues we seem to be having with the Mesh visual. Lights are unfortunately still hardcoded AFAIK. We would love lights to be objects that can be added to the scene though.

**Comment by bendichter** [comment]
Thanks for the info, @almarklein!

If you are referring to normals not being rendered correctly on OSX, I was having that problem as well but adding `config={'depth_size': 24}` resolved it.

 Just so it is clear what I mean, here is the "front" of the mesh object, which is lit appropriately
![screen shot 2016-03-14 at 4 28 33 pm](https://cloud.githubusercontent.com/assets/844306/13763224/debedf28-ea01-11e5-8e25-09c4c8419665.png)

and here is the "back" that I get to by rotating the object with my mouse. It is so dark it is almost a complete silhouette:
![screen shot 2016-03-14 at 4 28 46 pm](https://cloud.githubusercontent.com/assets/844306/13763259/205f1894-ea02-11e5-85d4-02b7ddb58e20.png)


I realize that it's asking a lot to have fine control of things like lighting from the high level plot interface, but I would really appreciate development in that direction. For example, MATLAB's implementation of this gives the user high level control:

```
l=light;
set(l,'Position',[-1 0 0],'Color',[0.8 0.8 0.8]); 
```

**Comment by drafter250** [comment]
Long time lurker here <. as a quick fix
Is there an ambient lighting level that can be increased? Or in the scene can the default light be made stationary .

**Comment by almarklein** [comment]
mmm... I though that the primitive light that we do use is "attached to the camera", this looks like its not ...

**Comment by bendichter** [comment]
Yeah that sounds like the ideal solution but it does not appear to be the case from my experience. The light appears to be fixed. BTW I was able to get around the issue by flipping the y coordinates but that obviously doesn't address the underlying issue.

**Comment by Eric89GXL** [comment]
@bendichter I agree that we need better lighting control. Unfortunately it will take some work and OpenGL skills to get it right...

**Comment by larsoner** [comment]
Closing as a dup of #553

**Comment by asnt** [comment]
FYI, see https://github.com/vispy/vispy/issues/1479#issuecomment-386883178 for forcing the light to follow the camera.
