### ISSUE TITLE
Python 3.5 lowers OpenGL Version to 1.1.0 on Windows

### ISSUE THREAD

**Issue by akrolsmir** [vispy/vispy#1188]
After upgrading my Python installation to 3.5, vispy stopped working because it seemed to think that my OpenGL version was 1.1.0 instead of 3.1.0:

```
>>> print(vispy.sys_info())
Platform: Windows-10-10.0.10586-SP0
Python:   3.5.1 |Anaconda 2.3.0 (64-bit)| (default, Jan 29 2016, 15:01:46) [MSC v.1900 64 bit (AMD64)]
Backend:  PyQt4
pyqt4:    ('PyQt4', '4.11.4', '4.8.7')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '1.1.0'
MAX_TEXTURE_SIZE: 1024
Extensions: 'GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture'
```

When I go back to 3.4 with a virtual environment, though, vispy correctly understands the OpenGL version to be 3.1.0:

```
>> print(vispy.sys_info())
Platform: Windows-10-10.0.10586
Python:   3.4.4 |Continuum Analytics, Inc.| (default, Jan 29 2016, 15:20:20) [MSC v.1600 64 bit (AMD64)]
Backend:  PyQt4
pyqt4:    ('PyQt4', '4.11.4', '4.8.7')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
_test:    None

GL version:  '3.1.0 - Build 9.17.10.4229'
MAX_TEXTURE_SIZE: 8192
Extensions: 'GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array 
...
```

There seemed to be something similar going on [here](https://sourceforge.net/p/pyopengl/mailman/message/24424342/), but it seemed to be related to wxpython which I'm not using. From Googling around, it seems that in some situations Windows might fall back to its 1.1.0 driver, but I can't figure out why that would happen in Python 3.5 and not 3.4.

**Comment by almarklein** [comment]
Very strange. Could you try with another backend on Python 3.5 (e.g. pyglet)?

**Comment by rossant** [comment]
I have a similar problem. I think the vispy conda package is out of date. It depends on old versions of Python and NumPy, so I had to uninstall it and use `pip install vispy` instead. Would it be possible to make a new conda package of VisPy?

**Comment by davidh-ssec** [comment]
There is a new conda package for vispy 0.5 and new versions of everything *should* be supported. If this becomes an issue again and people remember this is here we can reopen this. Closing for now.
