### ISSUE TITLE
Problem with SceneCanvas._render_picking

### ISSUE THREAD

**Issue by ombschervister** [vispy/vispy#1196]
Greetings!

I tried to implement visual vertexes selection with the mouse. However, I noticed I cannot select some of the vertexes in my example script. The red point cannot be selected.
![image](https://cloud.githubusercontent.com/assets/3264643/14067918/61361410-f48b-11e5-9907-eb48f86a7531.png)

In order to select points, my visual should accept mouse press event. However, this event does not occur on some of the points. I found out the reason could be in SceneCanvas._render_picking method, which does not draw some of the points.
I tried to simplify the example as I can, so:

``` python
# coding=utf-8
import sys
import numpy as np
from PyQt4 import QtCore, QtGui
from vispy import gloo, visuals, scene
from vispy.scene import Markers

class Widget(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        l = QtGui.QVBoxLayout(self)
        l.setContentsMargins(0, 0, 0, 0)

        # For choose drawing mesh (as like in _render_picking or not)
        self._cb = QtGui.QCheckBox(u"Render picking mesh")
        self._cb.setChecked(False)
        l.addWidget(self._cb)
        self._cb.stateChanged.connect(self._on_cb_state_changed)

        # Vispy canvas
        self._canvas = scene.SceneCanvas(bgcolor=(0.3, 0.3, 0.3, 1.0))
        l.addWidget(self._canvas.native)

        # ViewBox
        self.view = self._canvas.central_widget.add_view()
        self.view.camera = 'panzoom'

        # Simple visual
        self._drag_vis = Markers()
        self._drag_vis.interactive = True

        # Data for visual
        data = np.zeros((4, 3), dtype=np.float32)
        data[:, 0] = [100, 200, 100, 200]
        data[:, 1] = [100, 100, 200, 200]
        data[:, 2] = [-0.0, -0.1, -0.2, -0.3]
        self._drag_vis.set_data(data)
        self.view.add(self._drag_vis)

        self.view.camera.set_range()

    def _on_cb_state_changed(self):
        if self._cb.isChecked():
            # This configuration is used in _render_picking.
            self.view._picking_mesh.visible = True
            self.view._mesh.visible = False
        else:
            # This configuration is used in general drawing.
            self.view._picking_mesh.visible = False
            self.view._mesh.visible = True

        self._canvas.update()

if __name__ == "__main__":
    qapp = QtGui.QApplication(sys.argv)
    w = Widget()
    w.show()
    sys.exit(qapp.exec_())
```

As you see, when using _picking_mesh in ViewBox (which is used in render_picking mode), some points disappear!
![image](https://cloud.githubusercontent.com/assets/3264643/14068052/dcb2d97a-f490-11e5-92bc-8490da750a1c.png)
![image](https://cloud.githubusercontent.com/assets/3264643/14068055/df46d786-f490-11e5-98d5-bcd969a35b54.png)

If I set z==0 for the vertexes (data[:, 2] = [0.0, 0.0, 0.0, 0.0]), points are not drawn at all!
![image](https://cloud.githubusercontent.com/assets/3264643/14068076/79c6dfe0-f491-11e5-922b-55050fbd3cf2.png)

Can anybody help to resolve this issue?

Full code of vertex selection script:
[vertex_selection.py.txt](https://github.com/vispy/vispy/files/191132/vertex_selection.py.txt)

**Comment by ombschervister** [comment]
I replace 'trangle_fan' mode to 'triangle_strip' and got picture:
![image](https://cloud.githubusercontent.com/assets/3264643/14234420/ef51e68c-f9fb-11e5-8b47-a0f87d475642.png)
From this picture it is clear that Widget._picking_mesh cuts the point at z >= 0, when Widget._mesh does not.

**Comment by ombschervister** [comment]
So, SceneCanvas has a cental widget, which draw rect [0, 0, canvas.width, canvas.height]  at z == 0. Therefore, SceneCanvas.visual_at return my interactive widget only for points that are closer to the observer than the Widget._picking_mesh.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
This issue has been neglected and I'm sorry for that. This may still be an issue, but since the example code is with PyQt4 (which is relatively difficult to install now and will likely be deprecated by vispy soon) it is hard to test this. I'm going to close this, but if this is still an issue and something you are worried about we can reopen it.
