### ISSUE TITLE
Visuals should deal with texture limits automatically

### ISSUE THREAD

**Issue by Enchufa2** [vispy/vispy#1200]
I want to represent a real time signal coming from a DAQ card. So, consider the following script (an adapted version of [scrolling_plots.py](https://github.com/vispy/vispy/blob/master/examples/demo/scene/scrolling_plots.py)):

``` python
from vispy import app, scene
import numpy as np

canvas = scene.SceneCanvas(keys='interactive', show=True, size=(1024, 768))
grid = canvas.central_widget.add_grid()
view = grid.add_view(0, 0, camera='panzoom')

M = 8192 + 1 # MAX_TEXTURE_SIZE + 1
view.camera.rect = (0, 0, M, 10)

lines = scene.ScrollingLines(n_lines=1, line_size=M, dx=1.0,
                             pos_offset=np.zeros((M, 3), dtype=np.float32),
                             parent=view.scene)

def update(ev):
    m = 500
    data = np.abs(np.random.normal(size=(1, m), scale=0.3))
    data[data > 1] += 4
    lines.roll_data(data)

timer = app.Timer(connect=update, interval='auto')
timer.start()

if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        app.run()
```

The script fails if M is equal to MAX_TEXTURE_SIZE + 1 (with GL_INVALID_VALUE). In my view, the user shouldn't care about texture limits at this layer, and visuals should deal with that issues automagically.

For instance, let's suppose I have a signal sampled at 100 kHz and I want to visualise 1 second of that signal. Then, I would expect to be able to pass the RAW signal and set `M=100000`, to be able to pause the signal, zoom in and see all the samples.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
At least at the level of vispy you are using/describing, I don't think this can be implemented. What you're describing is something like a data manager that controls what data is in CPU versus in GPU versus not generated yet. There are other issues related to this concept and it has come up in meetings in the last year or so (can't find the issues right now and don't know if there are any direct plans to implement them).

I'm going to consider this a "won't fix" issue as it is not really possible with how the Visuals layer of vispy is meant to be used or meant to work and that the solution would involve a lot of work. Putting your issue another way you are basically saying "why can't I visualize more data than my computer can hold", it isn't a straight forward solution. I'm going to close this in favor of a more generic solution which I believe there are other issues for. I have no problem reopening this if the discussion can move towards a realistic implementation.
