### ISSUE TITLE
A few minor bugs

### ISSUE THREAD

**Issue by scottpaine** [vispy/vispy#1203]
I've been working with this package for about a month now building my own methods to visualize 2D datasets and am loving the fast speeds and intuitive methods for using canvases/visuals.

That being said, I've found two bugs.

**First**, in ColorBarVisual, setting the size doesn't actually set the size - it sets the halfdims:
```python
@size.setter
    def size(self, size):
        ...
        if self.orientation in ["top", "bottom"]:
            (width, height) = size
        else:
            (height, width) = size
        ...
        self._halfdim = (width, height)
        self._update()
```
I think that the halfdims should be `width // 2, height // 2`, but in either case if I make a visual called `cbar` and say `cbar.size = (200, 100)`, I end up with a visual that is 400 x 200 pixels.

**Second**, in ImageVisual, resetting the `clim` doesn't redraw the image. When setting the `clim`, the bool `_need_vertex_update` is set to true:

```python
@clim.setter
def clim(self, clim):
        ...
        self._need_vertex_update = True
        self.update()
```

In `_prepare_draw`, this makes the visual call `_build_vertex_data`, which itself doesn't use `clim` at all:

```python
def _prepare_draw(self, view):
        ...
        if self._need_vertex_update:
            self._build_vertex_data()
        ...
```

The only method in ImageVisual which does use the `clim` is in `_build_texture`:

```python
def _build_texture(self):
        ...
        if data.ndim == 2 or data.shape[2] == 1:
            # deal with clim on CPU b/c of texture depth limits :(
            # can eventually do this by simulating 32-bit float... maybe
            clim = self._clim
            if isinstance(clim, string_types) and clim == 'auto':
                clim = np.min(data), np.max(data)
            clim = np.asarray(clim, dtype=np.float32)
            data = data - clim[0]  # not inplace so we don't modify orig data
            if clim[1] - clim[0] > 0:
                data /= clim[1] - clim[0]
            else:
                data[:] = 1 if data[0, 0] != 0 else 0
            self._clim = np.array(clim)

        self._texture.set_data(data)
        self._need_texture_upload = False
```

And this is called from `_prepare_draw` when `_need_texture_upload` is `True`. So, I think the fix to this is easy - instead of setting `_need_vertex_update` to `True`, `_need_texture_upload` needs to be set when resetting the `clim`.

**Third**, in PlotWidget, calling the method `colorbar` with `position="right"` causes a bad drawing. This mainly comes from what happens when assigning with `right`:

```python
def colorbar(self, cmap, position="right",
                 label="", clim=("", ""),
                 border_width=0.0, border_color="black",
                 **kwargs):
        ...
        elif cbar.orientation == "left":
            self.grid.remove_widget(self.cbar_left)
            self.cbar_left = self.grid.add_widget(cbar, row=2, col=1)
            self.cbar_left.width_max = self.cbar_left.width_min = CBAR_LONG_DIM

        else:  # cbar.orientation == "right"
            self.grid.remove_widget(self.cbar_right)
            self.cbar_right = self.grid.add_widget(cbar, row=2, col=1)
            self.cbar_right.width_max = \
                self.cbar_right.width_min = CBAR_LONG_DIM
        ...
```

The method is trying to put `cbar_right` where `cbar_left` should be.  When `cbar_right` is initially defined, it is in a different row/col location:

```python
def _configure_2d(self, fg_color=None):
        ...
        self.cbar_right = self.grid.add_widget(None, row=2, col=5)
        ...
```

All that needs to change for this to work is that when `cbar_right` is redefined in the `colorbar` method, the `add_widget` method should be called with `row=2, col=5`. This will also fix the buggy demo `colorbar.py`.

That's all I've found thus far. Small things, but easily fixable.

**Comment by Eric89GXL** [comment]
Closing because your PR was merged. BTW adding a line `Closes #XXX` to your PR will auto-close the related issue
