### ISSUE TITLE
Canvas position property

### ISSUE THREAD

**Issue by giumas** [vispy/vispy#1205]
In the `Canvas` method:

```
@property
def position(self):
    """ The position of canvas/window relative to screen """
    return self._backend._vispy_get_position()
```

the docstring is not consistent with the backend implementations. 

For `wx`, `GetPosition()` returns "the position [is] in client coordinates for child windows and screen coordinates for the top level ones" http://www.wxpython.org/docs/api/wx.Window-class.html#GetPosition

For `qt`, `geometry()` is used, but to get the screen coordinates for a child widget it should be used something like: `self.mapToGlobal(self.pos())`

So, what is the expected behavior for Canvas `position()`? To return always the position to screen? Or to return the client coordinates when a child widget?

**Comment by Eric89GXL** [comment]
I suspect we'd want it to give the client coords when a child. Which would you expect it to be?

**Comment by queenish001** [comment]
@giumas

**Comment by djhoese** [comment]
This looks like this is probably still an issue, but I'm not really sure what the best solution is. As far as I know no one else has complained about this.

**Comment by giumas** [comment]
I am fine closing this ticket. I don't even remember my use case for opening it!

**Comment by djhoese** [comment]
Works for me. If someone finds an issue similar to this please open a new ticket.
