### ISSUE TITLE
How to access 'texture names' (GLuints) for Texture2D object for lower level OpenGL use

### ISSUE THREAD

**Issue by benlansdell** [vispy/vispy#1208]
Hi, 

forgive me if I'm missing something obvious. I think most of these details are irrelevant, but I'm providing them just in case. I create a Texture2D object as follows:

`rendertex1 = gloo.Texture2D((self.shape + (1,)), format="luminance", internalformat="r8")`

which is bound to a FrameBuffer object:

`fbo1 = gloo.FrameBuffer(rendertex1, gloo.RenderBuffer(self.shape))`

and rendered to offscreen. 

Using pyopengl I then want to unpack the contents of the texture to a pixel buffer object (for use in pycuda). I tried for a while using

`glBindTexture(GL_TEXTURE_2D, rendertex1.id)`

thinking 'id' was the texture's name as seen by OpenGL. After much experimenting I eventually realized this is _not_ the OpenGL name. Currently the only way I can find the correct name is trial and error, playing around with small integers... 

Is there a way to find the correct id for use with lower level opengl functions??

Regards,
Ben

**Comment by rougier** [comment]
I think the texture.id refers to the glir id which is different from the actual GL id. Tis was necessary for exporting vispy to webgl. This means you'll have to request the actual id from the glir object.

@rossant @almarklein Do you know how to do that ?

Else (and if you're only using gloo), you can use gloo from glumpy (http://glumpy.github.io)

**Comment by benlansdell** [comment]
Thanks, I'll look into getting the handle from the glir object. 

And thanks for bringing glumpy to my attention, I wasn't aware of it!

**Comment by benlansdell** [comment]
If renderer is a class derived from vispy.app.Canvas then

`renderer.context.shared._parser.get_object(rendertex1.id)._handle`

seems to do the job...

**Comment by almarklein** [comment]
Yes the `id` property is for the glir object and means nothing to opengl. In principal gloo was designed to be agnostic about opengl id's because these are handled by the "renderer" which might not be the same process (e.g. webgl). 

Glad you found a trick to make it work.
