### ISSUE TITLE
Vikram Singh Sikarwar: new volunteer via Mozilla Science Lab Collaborate

### ISSUE THREAD

**Issue by pydevhacker** [vispy/vispy#1210]
Data visualization is always a challenging task in todays world of big data.
I am interested to be part of this project, This could solve many scientific problems.
I can contribute as a developer and designer.<p><br><blockquote>This issue was created by @vsikarwar87 via <a href='https://mozillascience.org/collaborate'>Mozilla Science Lab Collaborate</a></blockquote></p>

**Comment by Eric89GXL** [comment]
@pydevhacker it would be great to have you start contributing -- feel free to take a look at the list of open issues and tackle any that sound doable.
