### ISSUE TITLE
Difficulty Finding Mesh Example

### ISSUE THREAD

**Issue by bennames** [vispy/vispy#1211]
I have been working on a project for a while in which I need to plot many quadrilateral finite elements along with some contour for each of them. I have been using mayavi for a while, but if I were to plot every single element individually as opposed to a whole series of them together in numpy arrays, it takes FOREVER! I was considering switching to vispy for my visualization but am having a hard time finding tutorials for plotting a series of (or even single) 2D contoured quadrilateral shape in 3D space. Do you have any suggestions/examples you can think of in your documentation etc?

Thanks.

Also this is the kind of surface I want to be able to plot:
![image](https://cloud.githubusercontent.com/assets/11602163/15127735/fa76f978-1605-11e6-965b-345685605bf5.png)

![image](https://cloud.githubusercontent.com/assets/11602163/15127753/0e3a7336-1606-11e6-8f70-0abab9c22a33.png)

**Comment by Eric89GXL** [comment]
Do you have them as triangulated meshes? Then it should be fairly easy, and we should indeed add an example for doing that sort of thing.

**Comment by bennames** [comment]
Correct, that's what they currently are. I just want to give vispy a try and see if I can plot individual elements fast enough for it to be worth it.

**Comment by drewm1980** [comment]
The following example:

https://github.com/vispy/vispy/blob/master/examples/basics/visuals/mesh.py

shows 3 examples of rendering meshes, including for two different vertex orderings.  Note that the `mdata.get_vertices()` is a numpy array containing vertices, and is what you would substitute with your mesh data. The two examples use different data layouts.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
I'm going to close this given the age and the suggestions so far. There are a few new examples related to meshes and adding textures that may also help anyone looking for more mesh use cases. Feel free to comment if we need to reopen this if it is still a problem and we can reopen it. Otherwise, other users should create a new issue if they have a similar question.
