### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by ghisvail** [vispy/vispy#1215]
Dear vispy community,

I have taken over Fred Picca's initial [effort](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=759820) to package vispy for Debian and Ubuntu. I am opening this issue to centralize future questions regarding vispy from a packaging perspective.

Right now, I am able to produce the binary packages for Python 2 and 3 off this repository (from the `v0.4.0` tag), but work is still on-going to adapt your CI to ours and the question of the documentation remains (#1209). Hopefully, with your assistance, I should be able to sort this out quickly.

I'll close this bug once a candidate package is accepted to the archive.

Thank you in advance,
Ghis

**Comment by Eric89GXL** [comment]
@ghisvail are you up for setting up the `git submodule` for docs?

**Comment by ghisvail** [comment]
> are you up for setting up the git submodule for docs?

:+1:

**Comment by Eric89GXL** [comment]
If you can get to it in, say, the next week that would be good because we could get it into 0.5

**Comment by ghisvail** [comment]
I'll do my best to get that done by the end of next week.

**Comment by ghisvail** [comment]
What are the minimum set of dependencies required to run the `unittest` testsuite successfully?

**Comment by ghisvail** [comment]
I have looked at the travis file but it is quite a mess.

**Comment by Eric89GXL** [comment]
A GUI package (one of qt, Pyglet, GLFW3, some others) should get most of the tests to run. But even without those it should work, and only run a subset of trials. But we use `py.test`, not `unittest` to run tests. You can try it with `make test` or `python make test` from the source root.

Keep in mind that you will also need an X11 display if you want to run many of the tests, which is why we run Xvfb on Travis, which is headless.

**Comment by ghisvail** [comment]
Still trying to get the packaging right, please be patient ^^.

So the minimal install dependencies should be `libglfw3` and `numpy` and the rest of `PyQt`, `PySide`, `Pyglet`, `WxPython`, `PySDL2`, `ipython` and `tornado` are all optional dependencies. Am I correct?

Then, running the minimal testsuite requires `py.test`, `xauth` and `xfvb`. The testsuite is ran by first firing an xfvb daemon, before running `python make test unit` for all targeted Python versions. All good?

Finally, tests for each backend will run if the latter are detected by vispy at runtime?

Thanks for your help

**Comment by Eric89GXL** [comment]
Yeah that's the idea. Hopefully it works that way in practice :)

**Comment by ghisvail** [comment]
The Debian linter flagged a usage of a non-free Lena picture in the docs. I filed an issue asking for its replacement [here](https://github.com/vispy/vispy-website/issues/4). Once done, the tip of the docs submodule needs to be updated.

**Comment by ghisvail** [comment]
Alright, I made some progress but cannot get the testsuite to succeed with `nobackend`. I run the following command during the build:

`xvfb-run -s "-screen 0 640x480x24 -ac +extension GLX +render" python2.7 -c "import vispy; vispy.test('nobackend')`

and obtain the following output:

```
----------------------------------------------------------------------
Running tests with no backend:
_VISPY_TESTING_APP=nobackend   -m "not vispy_app_test"
============================= test session starts ==============================
platform linux2 -- Python 2.7.11+, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /<<PKGBUILDDIR>>, inifile: 
collected 275 items

vispy/app/backends/tests/test_ipynb_util.py ....
vispy/app/tests/test_app.py ..
vispy/app/tests/test_backends.py F
vispy/app/tests/test_interactive.py .
vispy/app/tests/test_ipython.py s
vispy/color/tests/test_color.py .........
vispy/geometry/tests/test_calculations.py .
vispy/geometry/tests/test_generation.py .....
vispy/geometry/tests/test_meshdata.py .
vispy/geometry/tests/test_triangulation.py .........
vispy/gloo/gl/tests/test_names.py ..ss..
vispy/gloo/gl/tests/test_use.py s
vispy/gloo/tests/test_buffer.py .................................
vispy/gloo/tests/test_context.py ...
vispy/gloo/tests/test_framebuffer.py ..
vispy/gloo/tests/test_glir.py .
vispy/gloo/tests/test_globject.py .
vispy/gloo/tests/test_program.py .......
vispy/gloo/tests/test_texture.py .....................ss....sssss
vispy/gloo/tests/test_util.py ..
vispy/gloo/tests/test_wrappers.py ..
vispy/io/tests/test_image.py .s
vispy/io/tests/test_io.py F..
vispy/scene/tests/test_node.py .
vispy/scene/tests/test_visuals.py ..
vispy/testing/tests/test_testing.py .
vispy/util/dpi/tests/test_dpi.py F
vispy/util/fonts/tests/test_font.py .F
vispy/util/tests/test_config.py F
vispy/util/tests/test_docstring_parameters.py .
vispy/util/tests/test_emitter_group.py ........
vispy/util/tests/test_event_emitter.py .......................
vispy/util/tests/test_fourier.py .
vispy/util/tests/test_import.py .......s.
vispy/util/tests/test_key.py .
vispy/util/tests/test_logging.py ..
vispy/util/tests/test_run.py .
vispy/util/tests/test_transforms.py .
vispy/visuals/graphs/tests/test_layouts.py ...
vispy/visuals/shaders/tests/test_function.py ..........
vispy/visuals/shaders/tests/test_multiprogram.py .
vispy/visuals/shaders/tests/test_parsing.py ..
vispy/visuals/tests/test_isosurface.py s
vispy/visuals/tests/test_mesh.py s
vispy/visuals/tests/test_volume.py s
vispy/visuals/transforms/tests/test_transforms.py ......

=================================== FAILURES ===================================
________________________________ test_template _________________________________

    def test_template():
        """Test application module template"""
>       _test_module_properties(_template)

vispy/app/tests/test_backends.py:136: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/app/tests/test_backends.py:118: in _test_module_properties
    canvas = vispy.app.Canvas(create_native=False, app=DummyApplication())
vispy/app/canvas.py:139: in __init__
    dpi = get_dpi(raise_error=False)
vispy/util/dpi/_linux.py:54: in get_dpi
    lambda x_px, y_px, x_mm, y_mm: 25.4 * (x_px / x_mm + y_px / y_mm) / 2)
vispy/util/dpi/_linux.py:26: in _get_dpi_from
    return func(*map(float, match.groups()))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x_px = 640.0, y_px = 480.0, x_mm = 0.0, y_mm = 0.0

>   lambda x_px, y_px, x_mm, y_mm: 25.4 * (x_px / x_mm + y_px / y_mm) / 2)
E   ZeroDivisionError: float division by zero

vispy/util/dpi/_linux.py:54: ZeroDivisionError
----------------------------- Captured stdout call -----------------------------
_vispy_close
_vispy_get_fullscreen
_vispy_get_position
_vispy_get_size
_vispy_set_current
_vispy_set_fullscreen
_vispy_set_position
_vispy_set_size
_vispy_set_title
_vispy_set_visible
_vispy_swap_buffers
_vispy_update
________________________________ test_wavefront ________________________________

    def test_wavefront():
        """Test wavefront reader"""
>       fname_mesh = load_data_file('orig/triceratops.obj.gz')

vispy/io/tests/test_io.py:18: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/util/fetching.py:66: in load_data_file
    os.makedirs(op.abspath(op.dirname(fname)))
/usr/lib/python2.7/os.py:150: in makedirs
    makedirs(head, mode)
/usr/lib/python2.7/os.py:150: in makedirs
    makedirs(head, mode)
/usr/lib/python2.7/os.py:150: in makedirs
    makedirs(head, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = '/sbuild-nonexistent', mode = 511

    def makedirs(name, mode=0777):
        """makedirs(path [, mode=0777])
    
        Super-mkdir; create a leaf directory and all intermediate ones.
        Works like mkdir, except that any intermediate path segment (not
        just the rightmost) will be created if it does not exist.  This is
        recursive.
    
        """
        head, tail = path.split(name)
        if not tail:
            head, tail = path.split(head)
        if head and tail and not path.exists(head):
            try:
                makedirs(head, mode)
            except OSError, e:
                # be happy if someone already created the path
                if e.errno != errno.EEXIST:
                    raise
            if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
                return
>       mkdir(name, mode)
E       OSError: [Errno 13] Permission denied: '/sbuild-nonexistent'

/usr/lib/python2.7/os.py:157: OSError
___________________________________ test_dpi ___________________________________

    def test_dpi():
        """Test dpi support"""
>       dpi = get_dpi()

vispy/util/dpi/tests/test_dpi.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/util/dpi/_linux.py:54: in get_dpi
    lambda x_px, y_px, x_mm, y_mm: 25.4 * (x_px / x_mm + y_px / y_mm) / 2)
vispy/util/dpi/_linux.py:26: in _get_dpi_from
    return func(*map(float, match.groups()))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x_px = 640.0, y_px = 480.0, x_mm = 0.0, y_mm = 0.0

>   lambda x_px, y_px, x_mm, y_mm: 25.4 * (x_px / x_mm + y_px / y_mm) / 2)
E   ZeroDivisionError: float division by zero

vispy/util/dpi/_linux.py:54: ZeroDivisionError
_______________________________ test_font_glyph ________________________________

    def test_font_glyph():
        """Test loading glyphs"""
        # try both a vispy and system font
        sys_fonts = set(list_fonts()) - set(_vispy_fonts)
        assert_true(len(sys_fonts) > 0)
        for face in ['OpenSans'] + sorted(list(sys_fonts)):
            print(face)  # useful for debugging
            font_dict = dict(face=face, size=12, bold=False, italic=False)
            glyphs_dict = dict()
            chars = 'foobar^C&#'
            for char in chars:
                # Warning that Arial might not exist
                with warnings.catch_warnings(record=True):
                    warnings.simplefilter('always')
>                   _load_glyph(font_dict, char, glyphs_dict)

vispy/util/fonts/tests/test_font.py:37: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/util/fonts/_freetype.py:50: in _load_glyph
    face = _load_font(f['face'], f['bold'], f['italic'])
vispy/util/fonts/_freetype.py:34: in _load_font
    fname = _get_vispy_font_filename(face, bold, italic)
vispy/util/fonts/_vispy_fonts.py:20: in _get_vispy_font_filename
    return load_data_file('fonts/%s' % name)
vispy/util/fetching.py:66: in load_data_file
    os.makedirs(op.abspath(op.dirname(fname)))
/usr/lib/python2.7/os.py:150: in makedirs
    makedirs(head, mode)
/usr/lib/python2.7/os.py:150: in makedirs
    makedirs(head, mode)
/usr/lib/python2.7/os.py:150: in makedirs
    makedirs(head, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = '/sbuild-nonexistent', mode = 511

    def makedirs(name, mode=0777):
        """makedirs(path [, mode=0777])
    
        Super-mkdir; create a leaf directory and all intermediate ones.
        Works like mkdir, except that any intermediate path segment (not
        just the rightmost) will be created if it does not exist.  This is
        recursive.
    
        """
        head, tail = path.split(name)
        if not tail:
            head, tail = path.split(head)
        if head and tail and not path.exists(head):
            try:
                makedirs(head, mode)
            except OSError, e:
                # be happy if someone already created the path
                if e.errno != errno.EEXIST:
                    raise
            if tail == curdir:           # xxx/newdir/. exists if xxx/newdir exists
                return
>       mkdir(name, mode)
E       OSError: [Errno 13] Permission denied: '/sbuild-nonexistent'

/usr/lib/python2.7/os.py:157: OSError
----------------------------- Captured stdout call -----------------------------
OpenSans
_________________________________ test_config __________________________________

    def test_config():
        """Test vispy config methods and file downloading"""
        assert_raises(TypeError, config.update, data_path=dict())
        assert_raises(KeyError, config.update, foo='bar')  # bad key
        data_dir = op.join(temp_dir, 'data')
        assert_raises(IOError, set_data_dir, data_dir)  # didn't say to create
        orig_val = os.environ.get('_VISPY_CONFIG_TESTING', None)
        os.environ['_VISPY_CONFIG_TESTING'] = 'true'
        try:
            assert_raises(IOError, set_data_dir, data_dir)  # doesn't exist yet
            set_data_dir(data_dir, create=True, save=True)
            assert_equal(config['data_path'], data_dir)
            config['data_path'] = data_dir
            print(config)  # __repr__
>           load_data_file('CONTRIBUTING.txt')

vispy/util/tests/test_config.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/util/fetching.py:68: in load_data_file
    _fetch_file(url, fname)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

url = 'http://github.com/vispy/demo-data/raw/master/CONTRIBUTING.txt'
file_name = '/tmp/tmpKuveBA/data/CONTRIBUTING.txt', print_destination = True

    def _fetch_file(url, file_name, print_destination=True):
        """Load requested file, downloading it if needed or requested
    
        Parameters
        ----------
        url: string
            The url of file to be downloaded.
        file_name: string
            Name, along with the path, of where downloaded file will be saved.
        print_destination: bool, optional
            If true, destination of where file was saved will be printed after
            download finishes.
        """
        # Adapted from NISL:
        # https://github.com/nisl/tutorial/blob/master/nisl/datasets.py
    
        temp_file_name = file_name + ".part"
        local_file = None
        initial_size = 0
        # Checking file size and displaying it alongside the download url
        n_try = 3
        for ii in range(n_try):
            try:
                data = urllib.request.urlopen(url, timeout=15.)
            except Exception as e:
                if ii == n_try - 1:
                    raise RuntimeError('Error while fetching file %s.\n'
>                                      'Dataset fetching aborted (%s)' % (url, e))
E                   RuntimeError: Error while fetching file http://github.com/vispy/demo-data/raw/master/CONTRIBUTING.txt.
E                   Dataset fetching aborted (<urlopen error [Errno 111] Connection refused>)

vispy/util/fetching.py:243: RuntimeError
----------------------------- Captured stdout call -----------------------------
{'profile': None, 'gl_debug': False, 'include_path': [], 'gl_backend': 'gl2', 'default_backend': '', 'data_path': '/tmp/tmpKuveBA/data', 'glir_file': '', 'test_data_path': '/sbuild-nonexistent/.vispy/test_data', 'qt_lib': 'any', 'audit_tests': False, 'logging_level': 'info', 'dpi': None}
=============== 66 tests deselected by "-m 'not vispy_app_test'" ===============
======= 5 failed, 188 passed, 16 skipped, 66 deselected in 2.99 seconds ========
Failed: unit failure (1)
Testing failed (['nobackend'] failed, 0 skipped) in 3.288 seconds
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "vispy/testing/_runners.py", line 420, in test
    raise RuntimeError('FAILURE')
RuntimeError: FAILURE
```

I should point out that the build is performed in a *clean* and *isolated* chroot with no internet access.

**Comment by Eric89GXL** [comment]
The tests need to download a few files, so those will fail. They also need to save them somewhere. We could add something like `VISPY_SKIP_NETWORK_TESTS`, but that will disable a ton of tests.

**Comment by QuLogic** [comment]
Are they not cached, though? So @ghisvail could pre-provide them in the default location for testing, and then vispy wouldn't need to download them.

**Comment by Eric89GXL** [comment]
They are cached, so that could work

**Comment by ghisvail** [comment]
>  So @ghisvail could pre-provide them in the default location for testing

Everything the builders have access to at build time are the Debian archive and the unpacked source tree. Nothing can be fetched remotely at package build time. Should these test data be made available for testing, they would have to be provided within the source tree somehow.

Perhaps with a git submodule under `data/`? Then, I could dispatch them wherever testing wants them at build time, but also package them for CI purposes on Debian.

**Comment by QuLogic** [comment]
I'm pretty sure Debian packages can be built from multiple source tarballs [1] just like Fedora, so I'm not sure a submodule is necessary.

[1] https://raphaelhertzog.com/2010/09/07/how-to-use-multiple-upstream-tarballs-in-debian-source-packages/

**Comment by ghisvail** [comment]
> Debian packages can be built from multiple source tarballs

You are correct, although It is also not as trivial a workflow from a maintainer's perspective. Just look at the *beware* section towards the end of [Raphael's post](https://raphaelhertzog.com/2010/09/07/how-to-use-multiple-upstream-tarballs-in-debian-source-packages/). Perhaps things are simpler in Fedora's world, but this is off-topic. The Debian tools now integrates nicely the concept of submodules, which makes the generation and management of the combined sources much simpler.

 Hence the proposal to add a submodule for the test data. Afterall that is part of what submodules are [useful](http://blogs.atlassian.com/2013/03/git-submodules-workflows-tips/) for, i.e. aggregate pieces of source code with different life management and rate of updates. Plus, usage of a submodule could avoid using hard-coded download paths to the test data inside the code base, which sounds rather fragile and not flexible. This is probably a separate issue though.

**Comment by Eric89GXL** [comment]
If you can do it with `submodule` that would be fine by me.

**Comment by ghisvail** [comment]
Just to be sure, we are talking about [this](https://github.com/vispy/test-data) repository for the test data ? The corresponding README suggests it but I'd rather ask for confirmation.

**Comment by Eric89GXL** [comment]
Yeah there is that repo. You might also need the demo-data repo for some
tests, I can't remember.

**Comment by ghisvail** [comment]
> You might also need the demo-data repo for some tests.

It would probably be better to move / copy the relevant testing data to `test-data` and leave `demo-data` separate from the main repository. The problem with `demo-data` is that it contains a lot of stuff which is unfit for distribution, such as pre-compiled dll, embedded fonts and lena.

I could need some help building the comprehensive list of data required by the test suite to run. I am not that familiar with the code base.

**Comment by Eric89GXL** [comment]
>  it contains a lot of stuff which is unfit for distribution, such as pre-compiled dll, embedded fonts and lena

Unfortunately some of these things -- at least the embedded fonts -- are loaded on demand by the tests.

I'm not sure what the path of least resistance would be here. It seems like the options are:

1. Refactor the tests to skip ones that require more than `test-data`. This hurts coverage but is probably the easiest solution.

2. Move files necessary for testing to `test-data`. This is a bit ugly because some of them, like the font files, aren't specifically for testing but really on-demand downloading and use, so putting them in `test-data` is a minomer (and mismatches with how `load_data_file` works under the hood).

I guess we could make `load_data_file` smart enough to look for some files in `test-data` instead, which makes (2) less annoying. We could try moving the fonts over and see how close that gets you. WDYT?

**Comment by ghisvail** [comment]
`vispy` version 0.4.0 is now available in [Debian](https://packages.debian.org/source/sid/python-vispy). It would be nice for 0.5.0 to have a release in PyPI which contains the docs (accessible via the submodule) and appropriate data (perhaps in a submodule later) to run a (partial) testsuite.

**Comment by davidh-ssec** [comment]
@ghisvail As we prepare for a 0.5.0 release I want to make sure that the requests in this issue are still important to you. Are there other ways to solve the test data issues now that it's been over a year? Have things changed in the Debian package world? Do you need the docs and test data in a PyPI package or would cloning from git work well enough?

**Comment by ghisvail** [comment]
Having the docs in PyPI tarball would be nice, and should not take much more space once compressed in the tarball. I don't care how the test data are handled, as long as I can run the test suite (or a limited subset of it) from the PyPI tarball.

**Comment by davidh-ssec** [comment]
@ghisvail Is there a standard directory name that debian packaging expects for the documentation? Right now we have a temporary directory called `_gh-pages` with the HTML output for the website that I can include with a different name. Did you need something else? Better?

**Comment by ghisvail** [comment]
I would need the source files used for generating the HTML documentation via Sphinx. The current location under `doc` is fine.

**Comment by davidh-ssec** [comment]
@ghisvail Vispy 0.5.0 is now on PyPI. Let me know if you need anything else.

**Comment by djhoese** [comment]
@ghisvail Any updates on this? I think the package was last released the way you needed it. I'm working on version 0.6, but I'd like to know that this debian packaging is still possible (or already working). I'm going to close this for now and if you still have issues let's reopen it.
