### ISSUE TITLE
Use ci-helpers for Travis

### ISSUE THREAD

**Issue by astrofrog** [vispy/vispy#1222]
In https://github.com/vispy/vispy/pull/1221, I switched the AppVeyor config to use [ci-helpers](github.com/astropy/ci-helpers). It would be nice to see if we can switch the Travis configuration too (but it looks like there are special things like output redirection for the logs that we'd need to think about).

cc @bsipocz

**Comment by davidh-ssec** [comment]
Link to repository: https://github.com/astropy/ci-helpers

**Comment by larsoner** [comment]
I got rid of the output redirection, that was a workaround a long time ago for when Travis wasn't properly collapsing logs. This one isn't absolutely necessary so we can close and get to it next time the CIs break
