### ISSUE TITLE
Visual_at not behaving as expected

### ISSUE THREAD

**Issue by jpoeppel** [vispy/vispy#1231]
Hi everyone.
First of all thanks a lot for this great package! I am currently diving in to vispy because I want to build an interactive visualization for bayesian networks. Playing with the first scene examples (force_directed_graph.py), I tried to add some interactions. I thought, that I should be able to click on the created markers (even if I only select the entire markers object) since the SceneCanvas already does the picking selection for me. However, I only get the ViewBox as selected visual, never any Marker or Line. 

I am sure I am just missunderstanding something or using it wrong, but I currently cannot understand why I only get the ViewBox in that example, but I can get LinePlots in the picking.py example (using visualS_at instead of visual in the force_directed example also only picks up the Viewbox). (BTW I did set markers.interactive = True, since I found that they are not drawn otherwise in picking mode).

I am on the current master.

I would greatly appreciate it if anybody could enlighten me on this.

**Comment by Eric89GXL** [comment]
There is probably some bug in the graph visual that makes it not work. That
or the Markers visual, which graph uses, doesn't work properly with
picking.

**Comment by jpoeppel** [comment]
Thanks for the quick reply. 
Just tested it with Rectangles instead of the Markers with the same result. I am currently using the _visual_bounds_at- method to avoid this problem. Since I most likely won't have to deal with hundreds of elements in the scenegraph, performance should be good enough. I'll report here, if I happen to run into anything that might narrow it down further.

**Comment by jpoeppel** [comment]
Evan mentioned on the Mailinglist (https://groups.google.com/forum/#!topic/vispy/sUNKoDL1Gc0)
that temporarily setting the view to not interactive is a workaround. This does work (although visual_at does not always seem to pick up my rectangle, maybe because I have text on top of it and that interferes sometimes). So I'm guessing it has something to do with the z-buffer?

**Comment by djhoese** [comment]
As mentioned in #1232 there have been a couple updates to the involved Visuals here and this may not behave as badly as it did. As mentioned above the Markers/Mesh visuals do not allow sub-picking of their elements and is something that has to be added. It is possible but not builtin (search the issues if you're curious, I can't find the related issues at the moment).

As you've discovered using `.interactive` on a Visual can make it available for picking. Along with various bounds fixes this should work better. If this is still an issue please open a new issue with a simple code example that can be used to reproduce the issue.
