### ISSUE TITLE
Possible bug with the bounds of CompoundVisuals

### ISSUE THREAD

**Issue by jpoeppel** [vispy/vispy#1232]
Hi everyone,

as mentioned in #1231, I've had some trouble with visual(s)_at in the sceneCanvas. To circumvent that problem, I used _visual_bounds_at instead. I am currently displaying a subclass of RectangleVisual which I want to drag around with the mouse. I got that working fine, but only the very first time. After I've moved them, I cannot select them again by clicking because _visual_bounds_at will not find anything at that position. After a couple of hours of reading the source and experimenting, I think I've found the cause (please correct me if I'm wrong):

When changing the center attribute of the Rectangle, the underlying mesh correctly computes new vertices and updates ITS _bounds attribute. However, the _vshare.bounds of the mesh is not changed, which means that Rectangle.bounds() will still return the old bounds, as the ones from _vshare are used. 
The mesh should therefore probably call "self._bounds_changed" in the set_data method. 

This alone does not help with the rectangle case however, since a RectangleVisual is a CompoundVisual which itself does have it's own _vshare which will be used when calling Rectangle.bounds().
This _vshare would also need to be invalidated when the Rectangle is moved. 

I have currently "solved" this problem for me, by overriding the method "_bounds_changed" in the CompoundVisual which then calls this method on all it's component visuals and clears the _vshare.bounds.
This way I can invalidate the Rectangle in the setter for center to compute the new bounds.

Could this be a general fix for CompoundVisuals or does this break certain types, or is there a more performant way of signaling changes in the bounds of components (e.g. somehow using a single _vshare for the CompoundVisual and all it's components)?

(On a sidenote, I had to change Line 199 of rectangle.py from

```
if not self._center:
```

to

```
if self._center is None:
```

in order to avoid Numpy crashes since not np.array() is not supported anymore.)

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
Given the age of this issue, I think we can close this. The RectangleVisual has been updated a couple times now and should behave a little better with bounds changing. The MeshVisual that it is based on has also had some changes related to bounds detection. I also don't see any use of `self._center` like you described so that must have also changed.

If this is still an issue then comment here and we can reopen. Otherwise closing...
