### ISSUE TITLE
3D line drawing broken with 'agg' anti-aliasing

### ISSUE THREAD

**Issue by drewm1980** [vispy/vispy#1239]
```
#pos=numpy.array([[0, 0, 0], growth_direction])
pos=[numpy.array([0, 0, 0]), growth_direction]
scene.Line(pos=pos,
                                           color='green',
                                           width=2,
                                           method='agg',
                                           connect='strip',
                                           name='growth_direction',
                                           parent=view.scene)
```

If pos is a 2x3 numpy array, agg_bake calls len() on it like it should be a list, and then tries to reshape by the wrong amount:

```
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/line/line.py", line 472, in _agg_bake
    P = np.array(vertices).reshape(n, 2).astype(float)
ValueError: total size of new array must be unchanged
```

If you try to pass the list, prepare_draw tries to treat the input as a numpy array:

```
  File "/usr/local/lib/python2.7/dist-packages/vispy-0.5.0.dev0-py2.7.egg/vispy/visuals/line/line.py", line 436, in _prepare_draw
    self._parent._pos.astype(np.float32))
AttributeError: 'list' object has no attribute 'astype'
```

A workaround is to use 'gl' in place of 'agg' and pass a numpy array.  

The docs say pos should be a 2D array, so I ~think passing a list should be an early error, and __agg_bake should just check the array size without doing any reshaping. 

Do you want me to attempt a patch, or do you want to fix this internally? I'm new to the codebase, and line drawing is pretty fundamental :)

I am on 

> commit 6b2fe809d53b401e44abaf57fde32e5c1a634826
> Merge: 39d4a81 eb88e5a
> Author: Eric Larson larson.eric.d@gmail.com
> Date:   Wed Jun 15 11:18:19 2016 -0400
> 
> ```
> Merge pull request #1237 from chemelnucfin/trivial
> 
> trivial typo
> ```

**Comment by djhoese** [comment]
Hello 4 years later! I'm not sure if this is still an issue, but if you'd still like to attempt a fix to fail earlier when passed a list I would be ok with it. Otherwise I think this is an unexpected use of the LineVisual (passing an argument of the wrong type) so I'll consider this a "wontfix" in the spirit of cleaning out old issues.
