### ISSUE TITLE
Make visuals serializable

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#124]
In order to create a static WebGL backend, we'll need to make any visualization serializable.

Any visual instance should be serializable, containing:
- the list of gloo objects
- the list of instructions during initialization
- the list of instructions during paint
- the list of instructions during resize

**Comment by djhoese** [comment]
As mentioned in #143, I think this is too much work for the current vispy project and should probably not be something that is vispy-specific unless it has to be. Balancing the GLIR specification and the maintaining the existing python classes is not possible at this time. If someone wants to make a new issue to define a *real* implementation of this while not breaking anything in the existing python then go for it.
