### ISSUE TITLE
Test infrastructure broken with tiling window managers?

### ISSUE THREAD

**Issue by drewm1980** [vispy/vispy#1247]
I am trying to run a test case in preparation for writing one. 

Concretely, when I run the following test in Ubuntu 14.04 with the i3 window manager:

> awagner@hal:/home/awagner/src/vispy/vispy/visuals/tests
> $ python test_rectangle.py 

I see windows momentarily getting created and destroyed, and I get the following output:

> ================================================================= test session starts =================================================================
> platform linux2 -- Python 2.7.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
> rootdir: /home/awagner/src/vispy, inifile: 
> collected 4 items 
> 
> test_rectangle.py /home/awagner/src/vispy/vispy/testing/image_tester.py:101: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
>   if image == "screenshot":
> FFF.
> 
> ====================================================================== FAILURES =======================================================================
> _________________________________________________________________ test_rectangle_draw _________________________________________________________________
> /usr/local/lib/python2.7/dist-packages/numpy/testing/decorators.py:146: in skipper_func
>     return f(_args, *_kwargs)
> test_rectangle.py:22: in test_rectangle_draw
>     assert_image_approved(c.render(), 'visuals/rectpolygon1.png')
> ../../testing/image_tester.py:129: in assert_image_approved
>     (ims1, ims2))
> E   TypeError: Test result shape [  333.  1064.     4.] is not an integer factor larger than standard image shape [ 100.  100.    4.].
> ________________________________________________________________ test_rectpolygon_draw _____________________________________________________________

I suspect it is failing because it tries to render on-screen, and fails when the size of the window created is different from the one requested, resulting in a size mismatch in the test images.

Am I running the test wrong, or does the test infrastructure just not support tiling window managers yet?

**Comment by Eric89GXL** [comment]
Tests will fail if the WM does not respect the size request, yeah

**Comment by kmuehlbauer** [comment]
@larsoner Can this be closed or should we implement a kind of size check in the testing framework for graceful error message?
