### ISSUE TITLE
sampler2D values are clamped to range [0, 1]

### ISSUE THREAD

**Issue by keunhong** [vispy/vispy#1248]
Vispy seems to be truncating texture values to be within 0 and 1. This is causing errors in fragment shader code with un-normalized texture values (i.e. HDR textures).

I've attached a sample program which demonstrates this.

The texture is just a simple float32 array

```
[0, 0, 0],
[1, 1, 1],
[2, 2, 2],
```

Rendering this texture divided by two should yield the three different values but in reality the 2 is clamped to 1 making both values 0.5.

``` python
import numpy as np
from vispy import app, gloo
app.use_app('pyglet')


vs = """
#version 120

attribute vec3 a_pos;
attribute vec2 a_uv;
varying vec2 v_uv;

void main() {
  gl_Position = vec4(a_pos, 1.0);
  v_uv = a_uv;
}
"""

fs = """
#version 120

uniform sampler2D samp;
varying vec2 v_uv;

void main() {
  gl_FragColor = texture2D(samp, v_uv) / 2.0;
}

"""
class Canvas(app.Canvas):
  def __init__(self, size=(800, 600)):
      app.Canvas.__init__(self, size=size, show=True)
      self.program = gloo.Program(vs, fs)

      self.program['a_pos'] = np.array([
        [-1, -1, 0],
        [-1, 1, 0],
        [1, -1, 0],
        [1, 1, 0],
      ], dtype=np.float32)
      self.program['a_uv'] = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1],
      ], dtype=np.float32)
      tex = np.array([
        [0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
      ], dtype=np.float32)
      self.program['samp'] = np.dstack([tex, tex, tex])

  def on_draw(self, event):
    gloo.clear(color=(1, 1, 1))
    self.program.draw('triangle_strip')


if __name__=='__main__':
  canvas = Canvas()
  app.run()
```
### Expected output

![expected](https://cloud.githubusercontent.com/assets/297680/16329159/82cb021c-3995-11e6-93fd-fb080c57ea04.png)
### Actual output

![actual](https://cloud.githubusercontent.com/assets/297680/16329158/8179883e-3995-11e6-8890-3032631e9922.png)

**Comment by void42** [comment]
Never mind. It was a precision issue--setting the internal format of the texture to 'rgb32f' fixes this issue.

I think it would be useful to have a warning message or at least some guidance in the documentation of this.

**Comment by kmuehlbauer** [comment]
@keunhong 

Glad this worked with setting internal format. Closing as resolved.

> I think it would be useful to have a warning message or at least some guidance in the documentation of this.

PR is welcome, if you find the time.
