### ISSUE TITLE
vispy.test() failure on fresh install

### ISSUE THREAD

**Issue by thereisnoquarter** [vispy/vispy#1253]
I am trying to install VisPy on Ubuntu 16.04 LTS using the latest Anaconda package for Python 2.7. After running `conda install vispy`, `import vispy` works fine from a python shell, but `vispy.test()` produces the output `ValueError: no option named u'remote_data'` for all backends and fails the test. I have been unable to find anything like this online, and am not sure how to proceed. Am I simply missing a dependency or something here?

**Comment by scottpaine** [comment]
Don't run `conda install vispy`. It installs vispy 0.4.0, but the current recommendation is to install the master branch from here, using the following steps laid out in the README:

`git clone https://github.com/vispy/vispy.git && cd vispy && python setup.py install --user`

This will get you the latest version, which should work (I just ran some examples in Python 2.7.11, they all still work fine for me).

**Comment by thereisnoquarter** [comment]
Success, thanks very much.
