### ISSUE TITLE
"Module backends._qt" should not be imported directly 

### ISSUE THREAD

**Issue by fuchstraumer** [vispy/vispy#1261]
Hello - I'm trying to get vispy to work with pyqt5 and I'm having a hell of a time. here's the header of my code where I import the various libraries:

```
import sys
sys.path.insert(0,'../lib/')
from pyqt5.QtWidgets import (QMainWindow,QTextEdit,QAction,QFileDialog,QApplication,qApp)
from pyqt5 import QtGui,QtCore
from numpy_stl import mesh
from vispy.app import timer, backends
from vispy.scene import visuals, SceneCanvas
from vispy.scene.widgets import ViewBox
```

Since this error is being thrown up, I've tried importing the vispy parts first and the PyQt bits last, and I still get the same error. I'm completely boggled and stuck, and have no idea what's wrong. I'm not sure if its a bug (and if its not, sorry for submitting a non-issue) but any help with figuring this out would be wonderful and highly appreciated. 

The exact error is:
   " File "../lib/vispy\app\qt.py", line 29, in <module>
    raise RuntimeError("Module backends._qt should not be imported directly.")
    RuntimeError: Module backends._qt should not be imported directly."

Based on the qt.py code at this line, it suggests to me that its not importing or finding the right library? I'm using pyqt5 and it imports fine for use elsewhere. Do I need to tell the qt.py module to search in my project lib folder by using sys.path.insert or something?

**Comment by pevhall** [comment]
Hi I fixed this problem by adding these two lines at the beginning of my program (it may work for you).
```
import vispy
vispy.use('PyQt5')
```
I'm using PyQt5 and Python3.7 on windows10

**Comment by davidh-ssec** [comment]
I'm not able to reproduce this with the newest version of vispy. If you can please reopen this. I tried:
```
from PyQt5.QtWidgets import (QMainWindow,QTextEdit,QAction,QFileDialog,QApplication,qApp)
from PyQt5 import QtGui,QtCore,QtWidgets
#from numpy_stl import mesh
from vispy.app import timer, backends
from vispy import app
from vispy.scene import visuals, SceneCanvas
from vispy.scene.widgets import ViewBox


app.create()
w = QtWidgets.QWidget()
w.show()
app.run()
```

And it worked.
