### ISSUE TITLE
Vispy volume rendering over time

### ISSUE THREAD

**Issue by nmboffi** [vispy/vispy#1262]
I'm modifying the `volume.py` example available in `vispy/examples/basics/scene` to create a volume visualization over time. I am doing this by loading two volume datasets onto the scene at once: one is the current timestep, and one is the next timestep, and only the current timestep has its `visible` parameter ste to `True`. Pressing the '1' key on the keyboard makes the next timestep visible, and overrides the previous timestep with new data. This seems to work relatively well, except there are some issues with the isosurface rendering method:

1) No matter what I do, I get a warning `INFO: Program has unset variables: set([u'u_threshold'])`. This happens whether or not I provide a `threshold=[float_here]` to the `scene.visuals.Volume`, and whether or not I manually set `volume.threshold = [float_here]` after setting `volume` equal to the return of the `scene.visuals.Volume` call. This warning is also produced when running the example code.

2) If I do not manually set `volume.threshold = [float_here]`, even if I provide a `threshold` keyword argument to the `scene.visuals.Volume` call, any time new data is loaded the isosurface appears to render with whatever the default value for threshold is. This must be related to issue 1).

3) The documentation claims that the default value of threshold is the mean of the dataset, but this appears to be incorrect. When I print out the default threshold value if I do not set it myself, it is not equal to the mean of the dataset. If I set the threshold value to the mean of the dataset manually, no visualization is rendered, as if there are no contours for that value. When I print out the values of `volume.threshold` which correct produce contour visualizations, they correspond to values which are much lower than the values in the dataset. Thus, what is the interpretation of the threshold parameter?

I can provide code if necessary. I am also open to doing a volume visualization over time using a different method if that would be advisable.

**Comment by scottpaine** [comment]
What version of VisPy are you running? If you're running 0.4.0 (which is what happens if you use Anaconda and try to run `conda install vispy`), I can see why updating the threshold is causing problems -  here is the setter for `VolumeVisual.threshold` in Vispy 0.4.0:

```python
@threshold.setter
def threshold(self, value):
    self._threshold = float(value)
    self.update()
```

For comparison, here is the code in the current branch:

```python
@threshold.setter
def threshold(self, value):
    self._threshold = float(value)
    if 'u_threshold' in self.shared_program:
        self.shared_program['u_threshold'] = self._threshold
    self.update()
```

So the old 0.4.0 branch does appear to be buggy, in that it doesn't update the `shared_program` in the visual.

To fix this, try working with the latest branch of vispy. The recommendation for installing is on the [main repository page](https://github.com/vispy/vispy), under "Installation".

**Comment by thereisnoquarter** [comment]
What is the easiest way to check? I believe that I uninstalled the anaconda VisPy and switched to the development version, but I am unsure how to print out the version installed on my machine.

**Comment by scottpaine** [comment]
I think the easiest way is just to run the following in a python console:
```python
import vispy
vispy.__version__
```

**Comment by thereisnoquarter** [comment]
Using the above approach, the version is `0.5.0.dev0`. I will also download the development version a bit later today.

I notice that you are using the `print()` syntax. Should I be using Python 3 with VisPy?

**Comment by scottpaine** [comment]
I do, but I don't think it is necessary. Vispy should work with Python 2.7+ (it has in other dev environments I've used it with).

Let me know if it still fails with the latest from the Github repository, and post code just in case.

**Comment by thereisnoquarter** [comment]
I still get the same issues. Again, the code runs, but there are many `INFO` outputs about the unset variable `u_threshold` and furthermore the isosurface threshold value appears to reset on loading in new data, despite settings `threshold=[threshold_value]` on the `scene.visuals.Volume()` call. I've attached the code here; if you would like some of the data as well, I can provide it, but any volume data should reproduce the issue.

`import numpy as np
from vispy.color import get_colormaps, BaseColormap
from vispy.visuals.transforms import STTransform
from vispy import app, scene, io

# Value of TZ
num_images = 250
TZ = 21000

# Read in the volume data for all time
input_data_folder = "/home/nick/research/data/from_katahdin/mu_550_sig_15_cube/chi_grid."
all_data = []
for tt in range(num_images):
    data_str = input_data_folder + str(tt)
    all_data.append(np.fromfile(data_str, dtype=np.float32).reshape((64, 128, 128), order='F') * TZ)

# Prepare the canvas
canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
canvas.measure_fps()

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

# Set whether we are emulating a 3D texture
emulate_texture = False
method = 'iso'
thresh = 0.75

# Create the volume visuals, only one is visible
volumes = []
volumes.append(scene.visuals.Volume(all_data[0], parent=view.scene, threshold=thresh, emulate_texture=emulate_texture, method=method))
volumes.append(scene.visuals.Volume(all_data[1], parent=view.scene, threshold=thresh, emulate_texture=emulate_texture, method=method))
volumes[0].threshold = thresh
volumes[1].threshold = thresh
volumes[0].visible = True
volumes[1].visible = False 

# Create some cameras
fov = 60.
cam1 = scene.cameras.FlyCamera(parent=view.scene, fov=fov, name='Fly')
cam2 = scene.cameras.TurntableCamera(parent=view.scene, fov=fov, name='Turntable')
cam3 = scene.cameras.ArcballCamera(parent=view.scene, fov=fov, name='Arcball')
view.camera = cam2

# Global variables for loading the data
curr_image = 0
curr_switch = 0

# Key presses
@canvas.events.key_press.connect
def on_key_press(event):
    global curr_image, curr_switch, method, thresh

    # Move forward in time
    if event.text == '1':
        # Switch around which image is visible
        volumes[(curr_switch + 1) % 2].threshold = thresh
        volumes[(curr_switch + 1) % 2].visible   = True
        volumes[curr_switch].visible             = False

        # Figure out which volume we need to load next
        curr_image = (curr_image + 1) % num_images 

        # Load the next image and overwrite the hidden visualization 
        volumes[curr_switch] = scene.visuals.Volume(all_data[curr_image], parent=view.scene, threshold=thresh, emulate_texture=emulate_texture, method=method)
        volumes[curr_switch].threshold = thresh
        volumes[curr_switch].visible = False

        # Load up the next switch
        curr_switch = (curr_switch + 1) % 2

    # Move backwards in time
    elif event.text == '2':
        # Switch around which image is visible
        volumes[(curr_switch + 1) % 2].threshold = thresh
        volumes[curr_switch].visible           = False
        volumes[(curr_switch + 1) % 2].visible = True

        # Figure out which volume we need to load next
        curr_image = (curr_image - 1) % num_images 

        # Load the next image and overwrite the hidden visualization 
        volumes[curr_switch] = scene.visuals.Volume(all_data[curr_image], parent=view.scene, threshold=thresh, emulate_texture=emulate_texture, method=method)
        volumes[curr_switch].threshold = thresh

        # Load up the next switch
        curr_switch = (curr_switch + 1) % 2

    # Change rendering method
    elif event.text == '3':
        if method == 'mip':
            volumes[curr_switch].method              = 'iso'
            volumes[(curr_switch + 1) % 2].method    = 'iso'
            method = 'iso'
            volumes[curr_switch].threshold           = thresh
            volumes[(curr_switch + 1) % 2].threshold = thresh
        else:
            volumes[curr_switch].method              = 'mip'
            volumes[(curr_switch + 1) % 2].method    = 'mip'
            method = 'mip'

    # If rendering an isosurface, change the value of the contour
    elif event.text != '' and event.text in '[]':
        s = -.01 if event.text == '[' else .01
        volumes[curr_switch].threshold += s
        volumes[(curr_switch + 1) % 2].threshold += s
        th = volumes[curr_switch].threshold
        thresh = th
        print("Isosurface threshold: %0.3f" % th)
        
if __name__ == '__main__':
    app.run()`

**Comment by scottpaine** [comment]
I'm reproducing your issue now, getting the same problems as you are.

I think the biggest issue is that, for whatever reason, the line `'u_threshold' in self.shared_program` in `visuals.volume` is evaluating as `False`, which means it's never set, which causes the warning. As to WHY it isn't set, I'm trying to dig around and find out. For now, this is definitely a bug.

**Comment by thereisnoquarter** [comment]
Great, thanks a lot.

While we're at it, any idea why adding more data to the `volumes` array causes a massive drop in fps? Does creating a `scene.visuals.Volume` object automatically send the data to the GPU? If there's one volume, it's quite smooth. Two volumes goes down to about 5-10fps. With all 250 for my dataset, which is what I originally tried, I get 1fps if I'm lucky.

**Comment by scottpaine** [comment]
So I can definitely tell you what's wrong there - every time you switch, you're creating a brand new VolumeVisual. This means you're reinitializing a VolumeVisual and all of the preprocessing that goes with it every single time you switch data. For more FPS, try creating only one volume visual, and use `visual.set_data` to update. That should be a lot quicker (hopefully)

**Comment by thereisnoquarter** [comment]
Any update on this?

Also, using `visual.set_data` does improve the speed. However, it seems to introduce rendering artifacts across the surface, and the visualization does not look as clean as the previous approach. Furthermore, after going backwards/forwards in time for a fair amount of time, the visualization disappears entirely and it is impossible to get it to come back without closing the window and rerunning the script.

**Comment by scottpaine** [comment]
Somewhere in there some kind of data is being lost. I've been looking at it but can't really trace where the problem lies. This may be a better question for @Eric89GXL - there is definitely some kind of bug in the VolumeVisual.

Here's the code I put in the replicates the same problems you have:

```python
import numpy as np
from vispy.color import get_colormaps, BaseColormap
from vispy.visuals.transforms import STTransform
from vispy import app, scene, io

vol1 = np.load(io.load_data_file('volume/stent.npz'))['arr_0']
vol2 = np.load(io.load_data_file('brain/mri.npz'))['data']
vol2 = np.flipud(np.rollaxis(vol2, 1))

all_data = [vol1, vol2]
transform_frame_1 = scene.STTransform(translate=(64, 64, 0))
transform_frame_2 = scene.NullTransform()
transforms = [transform_frame_1, transform_frame_2]

# Prepare the canvas
canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
canvas.measure_fps()

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

# Set whether we are emulating a 3D texture
emulate_texture = False
method = 'iso'
thresh = 0.2

# Create the volume visual
volume = scene.visuals.Volume(all_data[0],
                              parent=view.scene,
                              threshold=thresh,
                              emulate_texture=emulate_texture,
                              method=method)
volume.transform = transforms[0]

# Create some cameras
fov = 60.
cam = scene.cameras.TurntableCamera(parent=view.scene, fov=fov, name='Turntable')
view.camera = cam

# Global variables for loading the data
curr_image = 0

# Key presses
@canvas.events.key_press.connect
def on_key_press(event):
    global curr_image, method, thresh

    # Move forward in time
    if event.text == '1':
        # Figure out which volume we need to load next
        curr_image = (curr_image + 1) % num_images
        print('Switching to Image '+str(curr_image + 1))

        # Load the next image and overwrite the hidden visualization
        volume.set_data(all_data[curr_image])
        volume.transform = transforms[curr_image]

    # Move backwards in time
    elif event.text == '2':
        # Figure out which volume we need to load next
        curr_image = (curr_image - 1) % num_images
        print('Switching to Image ' + str(curr_image + 1))

        # Load the next image 
        volume.set_data(all_data[curr_image])
        volume.transform = transforms[curr_image]

    # Change rendering method
    elif event.text == '3':
        if method == 'mip':
            print('Switching to method iso')
            volume.method = 'iso'
            volume.threshold = thresh
            method = 'iso'
        else:
            print('Switching to method mip')
            volume.method = 'mip'
            volume.method = 'mip'
            method = 'mip'

    # If rendering an isosurface, change the value of the contour
    elif event.text != '' and event.text in '[]':
        s = -.01 if event.text == '[' else .01
        volume.threshold += s
        th = volume.threshold
        thresh = th
        print("Isosurface threshold: %0.3f" % th)

if __name__ == '__main__':
    app.run()

```

**Comment by Eric89GXL** [comment]
I don't think I can help with the VolumeVisual much unfortunately.

**Comment by thereisnoquarter** [comment]
Has anybody had any luck with this? I'm planning on giving a presentation some time soon and would like to use my visualizations during it - it would be helpful to have this ironed out. I can potentially take a look as well, but I'm not very proficient in OpenGL so I'm not sure how much help I'll actually be.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
The VolumeVisual has been rewritten by @brisvag and @alisterburt a couple times in the last year or two. I know at least some of these issues have been addressed or discussed. I'm going to close these assuming they are fixed given the age of the issue and the amount of work that has gone into the VolumeVisual. If these things are still an issue comment here and we can reopen it. Or make a new issue if there are similar but different issues.
