### ISSUE TITLE
PyQt version support

### ISSUE THREAD

**Issue by geraldstanje** [vispy/vispy#1264]
Hi,

Are there any plans to make vispy compatible with PyQt5 (5.6 or 5.7)?

I have a PyQt5 application. Do you have an example which shows how to plot a time series on my Canvas using Vispy?

Thanks

**Comment by QuLogic** [comment]
I partially implemented compatibility with the new API in #960, and though it's not mentioned there, I still ran into some issues with a few broken examples. I don't quite remember what they were so I will have to try it out again to see what those were, though.

**Comment by Eric89GXL** [comment]
Closing for deeper discussion in #1264 and #960
