### ISSUE TITLE
Make the scenegraph serializable

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#127]
In order to create a static WebGL backend, we'll need to make any visualization serializable.

The entire scene graph should be serializable, containing:
- The graph of entities
- The visual and transform for each entity
- ...

**Comment by campagnola** [comment]
@rossant, can this be closed?

**Comment by rossant** [comment]
Although this is no longer necessary for the WebGL backend, maybe having an export feature for the scene graph would be useful? But maybe there's another issue for it already?

**Comment by djhoese** [comment]
See #124.
