### ISSUE TITLE
Mouse events in basic plotting example very laggy

### ISSUE THREAD

**Issue by codypiersall** [vispy/vispy#1274]
(I'm sorry if this is a known issue.)

Whenever I run the example `examples/basics/plotting/plot.py`,  the plot responds very slowly to mouse events (panning and zooming in particular).  Dragging the plot around uses 100% of a CPU, and my graphics card is using about 1%.  I'm using  PyQt4 for the backend.  I increased the logging information to DEBUG, but I didn't really understand the output.  Is it a known issue that the high-level plotting stuff doesn't handle mouse events very efficiently?  The example in `examples/basics/scene/axes_plot.py` behaves more like I was expecting: nice fluid panning and zooming.  All the examples in `examples/basics/plotting/` have the same behavior, where they feel unresponsive whenever pretty much anything happens.

I've noticed that making the window receive focus and lose focus a few times a second (by hitting Alt+Tab) also can use up a pretty good chunk of a processor, which makes me think the event handling may be the bottleneck.

**Comment by rougier** [comment]
I think this issue has been already identified but I don't remember it exactly. Did you search the issues (opened and closed) ?

**Comment by codypiersall** [comment]
@rougier I found two issues that might be related before I posted this one, but I wasn't sure if they had the same cause: Issue #1194 and Issue #1182. @Eric89GXL linked to 1182 from 1194.  Are those the issues you were thinking of?

**Comment by codypiersall** [comment]
Any ideas about what's causing this issue?  I may be able to look into it if someone can point me in the right direction.

**Comment by Eric89GXL** [comment]
Take a look at #1182, the idea for how to fix it is in there. cc @nfoti

**Comment by Eric89GXL** [comment]
Closing as duplicate issue
