### ISSUE TITLE
Anaconda - Vispy not working

### ISSUE THREAD

**Issue by Davide-sd** [vispy/vispy#1275]
Hello,
I'm running Anaconda with Python 2.7.12.final.0 on Windows (10) 64bit
I've tryed to install the vispy package with the following command, [as pointed out in this page](https://anaconda.org/anaconda/vispy):
`conda install -c anaconda vispy=0.4.0.106.gf8a69d0`
As you can see in the attachment vispy-1, some packages have been downgraded. After the install, Spyder is not able to launch because the package pandas need the updated version of numpy. Unfortunately, a lot of examples don't run and print out some error. For instance, I was looking at the example\basic\scenes\surface_plot.py and the following error message appears:

```
File "surface_plot.py", line 15, in <module>
    from vispy.visuals.transforms import MatrixTransform
ImportError: cannot import name MatrixTransform
```

 If I try to run contour.py, I get the following message:

```
File "contour.py", line 13, in <module>
    from vispy.visuals.filters import IsolineFilter
ImportError: cannot import name filters
```

Is there anything I can do to have vispy working with Anaconda without messing around with other packages? And what about all the errors?
![vispy-1](https://cloud.githubusercontent.com/assets/9921777/18815318/119fa9f8-832d-11e6-938f-56c9c05b340d.jpg)

**Comment by kmuehlbauer** [comment]
@Davide-sd `MatrixTransform` and `IsolineFilter` are not available in vispy 0.4.0. You would need to install bleeding edge vispy from the repo.

**Comment by Davide-sd** [comment]
@kmuehlbauer Thank you, I've installed the latest package with this command:
`git clone https://github.com/vispy/vispy.git && cd vispy && python setup.py install --user`
The vispy package is working, but it isn't added to Anaconda, do you know how can i add it?

**Comment by kmuehlbauer** [comment]
@Davide-sd You would need to create the conda package by yourself. Here is some docs from conda about creation of packages from scratch (http://conda.pydata.org/docs/build_tutorials/pkgs2.html). You might also have a look at the vispy conda recipe [here](https://github.com/conda/conda-recipes/tree/master/python/vispy) for guidance.

**Comment by hadim** [comment]
Note that a vispy recipe is waiting the 0.5.0 release to be available in conda forge : https://github.com/conda-forge/staged-recipes/pull/1657

**Comment by Davide-sd** [comment]
@hadim do you know how much do we have to wait?

**Comment by hadim** [comment]
It depends on the vispy core team.

**Comment by QuLogic** [comment]
If you want to install the development version in conda, you shouldn't use `--user`; that installs to `~/.local/`. To install in a conda environment, just activate the environment and install without extra arguments. Also, it's better to use `pip` instead of `setup.py` because then you get working uninstall, and conda understands pip installations and should list them properly.

**Comment by kmuehlbauer** [comment]
> Thank you, I've installed the latest package with this command:
> git clone https://github.com/vispy/vispy.git && cd vispy && python setup.py install --user
> The vispy package is working, but it isn't added to Anaconda, do you know how can i add it?

@Davide-sd Closing this, as the original problem is resolved. Please follow #1322 for updates on the coming 0.5.0 Release.
