### ISSUE TITLE
Write a gloo interpreter in Javascript

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#128]
Given a serialized visualization (e.g. JSON), we need a Javascript engine that interprets it and render it in the browser with WebGL.

In particular, we need a gloo engine in Javascript, implementing:
- Program
- Texture
- VertexBuffer
- FrameBuffer
- etc.

These classes can be instantiated with the information contained in the serialized gloo objects.

**Comment by almarklein** [comment]
@rossant this is done now, no?

**Comment by rossant** [comment]
No, not yet. We have a GLIR interpreter, but not gloo. It would be handy to have gloo.js.

**Comment by almarklein** [comment]
I think this is now out of scope, right?

**Comment by djhoese** [comment]
Yep. It'd still be cool and could be done in vispy.js...but not going to happen by any of us.
