### ISSUE TITLE
Circles and lines in VisPy

### ISSUE THREAD

**Issue by iberinsk** [vispy/vispy#1286]
I am a new user of VisPy and try to start from simple example (modified from the tutorial). A code below plots nodes on canvas. 1. How can I plot circles instead of points? 2. How can I connect these nodes by lines (randomly or nearest neighbors or neighbors situated closer than r_max)?

```
import numpy as np
from vispy import app, scene
from vispy import gloo

c = app.Canvas(keys='interactive')
#c = scene.SceneCanvas(keys='interactive')

vertex = """
attribute vec2 a_position;
void main (void)
{
    gl_Position = vec4(a_position, 0.0, 1.0);
}
"""

fragment = """
void main()
{
    gl_FragColor = vec4(1.0, 1.0, 1.0, 1.0);
}
"""

program = gloo.Program(vertex, fragment)

program['a_position'] = np.c_[
        np.random.uniform(-0.5, +0.5, 1000).astype(np.float32),
        np.random.uniform(-0.5, +0.5, 1000).astype(np.float32)]



@c.connect
def on_resize(event):
    gloo.set_viewport(0, 0, *event.size)

@c.connect    
def on_draw(event):
    gloo.clear((0,0,0,1))
    program.draw('points')

c.show()
app.run()
```

**Comment by kmuehlbauer** [comment]
@iberinsk Did you find a solution so far?

**Comment by iberinsk** [comment]
Yes and no. I started to use visuals instead of gloo.  Currently I use scene.Visual.markers for the circles and scene.Visuals.line to connect them with the lines.

**Comment by kmuehlbauer** [comment]
Good that `Visuals` work for you. Might this issue be closed then, or do you want this to be pursued further?

**Comment by iberinsk** [comment]
Let's close it. Thanks!

20 мая 2017 г. 19:40 пользователь "Kai Mühlbauer" <notifications@github.com>
написал:
