### ISSUE TITLE
Write a Visual interpreter in Javascript

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#129]
Given a serialized visualization (e.g. JSON), we need a Javascript engine that interprets it and render it in the browser with WebGL.

In particular, we need a Javascript interpreter that renders a serialized Visual. This engine uses the Javascript gloo engine.

**Comment by djhoese** [comment]
See #161 and #124. I think this is too much work and a custom serialized format for Visuals is not the long term solution to this problem/wish.
