### ISSUE TITLE
incorrect warning about unset variables

### ISSUE THREAD

**Issue by ombschervister** [vispy/vispy#1294]
video card: NVIDIA GeForce GT 240

shader code contains:
    const int top_x_shift[6] = int[6](0, 1, 0, 1, 1, 0);
    const int top_y_shift[6] = int[6](0, 0, 1, 0, 1, 1);

glir.py,  _get_active_attributes_and_uniforms function
     return  '_main_top_y_shift_1[1]', '_main_top_x_shift_0[4]'  and so on.

After that I saw this warning:
INFO: Program has unset variables: {'_main_top_y_shift_1[1]', '_main_top_x_shift_0[4]', '_main_top_x_shift_0[2]', '_main_top_x_shift_0[1]', '_main_top_y_shift_1[5]', '_main_top_y_shift_1[4]', '_main_top_y_shift_1[3]', '_main_top_x_shift_0[5]', '_main_top_y_shift_1[0]', '_main_top_x_shift_0[0]', '_main_top_y_shift_1[2]', '_main_top_x_shift_0[3]'}

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
We talked about this at our monthly vispy dev meeting and there is a chance that vispy's parser can't handle this syntax. Given the age of this issue I'm going to close it, but if you still have issues with this then please give a simple and complete example of vispy code that fails as you've described so I can look into it further. Thanks.
