### ISSUE TITLE
geometry without create_plane attribute

### ISSUE THREAD

**Issue by fwzhuang** [vispy/vispy#1295]
Is there cancel the create_plane attribute in the geometry in the new version
`
vertices, faces, outline = geometry.create_plane(width=2, height=4,
                                                 width_segments=4,
                                                 height_segments=8,
                                                 direction='+y')
`

but got 
"AttributeError: 'module' object has no attribute 'create_plane' "

**Comment by scottpaine** [comment]
Did you install using git or using Anaconda?

If you installed with Anaconda, you're on version 0.4.0, which is waaaay behind this version. Please follow the instructions in the README to install the most up-to-date version of the package:

`git clone https://github.com/vispy/vispy.git && cd vispy && python setup.py install --user`

**Comment by fwzhuang** [comment]
I fix the problem, becasue I installed  the vispy  using pip, and also install using  git. after pip uninstall, the problem is fixed. thanks.
