### ISSUE TITLE
Multiple OpenGL windows not working

### ISSUE THREAD

**Issue by kelvinlawson** [vispy/vispy#1298]
Tested using the latest Github code from today.

The GL tutorial tests (e.g. fireworks.py, cube.py) work fine within a PyQT application. But if you attempt to display two of them simultaneously (two widgets in one app) then both of them break, either corrupted graphics or failure to repaint the widget. Should two GL widgets be possible with vispy?

Attached a simple test app "test.py" that shows the issue. Code is as follows and uses the standard fireworks.py, cube.py examples:

```
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import cube, fireworks
 
class Form(QWidget):
    def __init__(self, parent=None):
        super(Form, self).__init__(parent)
 
        cube_canvas = cube.Canvas()
        fireworks_canvas = fireworks.Canvas()
        Layout1 = QVBoxLayout()
        Layout1.addWidget(fireworks_canvas.native)
        Layout1.addWidget(cube_canvas.native)
 
        mainLayout = QGridLayout()
        mainLayout.addLayout(Layout1, 0, 1)
        self.setLayout(mainLayout)
        self.setWindowTitle("Vispy")
 
 
if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    screen = Form()
    screen.show()
    sys.exit(app.exec_())

```
[2glviews.tar.gz](https://github.com/vispy/vispy/files/685855/2glviews.tar.gz)

**Comment by kmuehlbauer** [comment]
@kelvinlawson I'm not really sure, but this seems to be connected with the propagation of events.

This gist [here](https://gist.github.com/kmuehlbauer/c521e2b05f5383651d157d5c44344949) shows adaptions of this [fireworks](https://github.com/vispy/vispy/blob/master/examples/demo/gloo/fireworks.py) and this [rotating_cube](https://github.com/vispy/vispy/blob/master/examples/basics/gloo/rotate_cube.py) inside one QT5 Application side-by-side.

@rougier might shed some light, what would be needed to get the low level gl-stuff working instead.

**Comment by kmuehlbauer** [comment]
@kelvinlawson Did you get along with it? A short notice will be sufficient.

**Comment by rougier** [comment]
The difficulty is to route the event to the right context anytime and I'm not sure how things are handled with glir. For glumpy, there is an explicit switch to one context or the other when necessary (see https://github.com/glumpy/glumpy/blob/master/examples/app-two-windows.py)

**Comment by davidh-ssec** [comment]
I'd also be curious if something like this works in PyQt4 since it is a more heavily tested backend. Or at least works better. The GLIR "CURRENT" command (`set_current`/`_vispy_set_current` in vispy) should direct the GL calls to the right context. Mouse, keyboard, and timer events are another story.

**Comment by davidh-ssec** [comment]
@kmuehlbauer Is your gist something that we should consider making an example? How much modifying needed to be done to get this to work?

**Comment by kmuehlbauer** [comment]
@davidh-ssec I can try to set this up also for qt4. Is it what you meant with *modifying work*? Should be fairly easy 😬.

**Comment by davidh-ssec** [comment]
@kmuehlbauer You mentioned having to modify the example code a bit to get this to work. Would it be possible to just import the examples in *this* new example? Maybe modify the existing examples so they work better, but without stopping them from working independently.

**Comment by kmuehlbauer** [comment]
@davidh-ssec I'll have a look into this, didn't thought about `importing` so far. Keep you posted!

**Comment by kmuehlbauer** [comment]
@davidh-ssec I added a example. Fairly straightforward.
