### ISSUE TITLE
Write a Javascript/WebGL backend for serialized visualizations

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#130]
Write a Javascript engine that renders a serialized visualization with WebGL.

Requires #128 and #129.

**Comment by djhoese** [comment]
As pointed out in other issues, I'm closing ideas related to the "serialized visualizations". I think developing this serialized form of visualizations and gloo is out of scope for vispy and is too large of a task for the current contributor and user base. I do think improvements could be made to the GLIR parsing including examples (see #1905).
