### ISSUE TITLE
Using 'scene' 

### ISSUE THREAD

**Issue by iberinsk** [vispy/vispy#1308]
Hi! I would like to draw a mass-and-spring model. Currently I use scene.Visuals.line to draw springs and scene.Visual.markers for the balls (masses). Is it possible to draw 3D spheres instead of markers and cylinders instead of lines using scene? This example https://www.youtube.com/watch?v=uOSrplCF4kU looks nice, is it possible to make something similar using 'scene'?

**Comment by scottpaine** [comment]
I've written something using the visuals package that generates a spring using TubeVisual. You can see it [here](https://github.com/vispy/vispy/blob/master/examples/demo/visuals/wiggly_bar.py). It involves using PyQt4, but the code for a spring is present in there regardless.

**Comment by kmuehlbauer** [comment]
@iberinsk Could you use @scottpaine's example to get your model running? This would be a nice addition to the examples/demo section.

**Comment by kmuehlbauer** [comment]
@iberinsk I'll close this for now. Hopefully the example set you on the right track. Feel free to reopen, if necessary.
