### ISSUE TITLE
Write a Python serializer and Javascript deserializer of binary data with PNG images

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#132]
The idea is to save an arbitrary data buffer as a PNG image in Python (serialization), and deserialize it in Javascript with an HTML canvas. The use case is the online and offline WebGL backend. This seems to be an efficient way of transferring binary data to the browser.

This task can be done independently and doesn't require any OpenGL knowledge.

See this [reference](http://cg.alexandra.dk/?p=1386).

**Comment by sh4wn** [comment]
Is it an idea to use msgpack [1] for this? msgpack is a sort of "binary JSON", so this would allow us to send almost any arbitrary object over the network, and use it in Javascript. The downside is that we would add another dependency.

[1]: http://msgpack.org/

**Comment by rossant** [comment]
Actually now that IPython 3.0 is here, we have binary websocket support, so this issue can probably be closed (sorry if that's something you wanted to do!)...

**Comment by almarklein** [comment]
Dunno; binary websockets just allows transmitting blobs of bytes. We still need a format to serialize a data structure to bytes and back.

**Comment by rossant** [comment]
Yeah maybe this issue might be useful for the offline backend, but it's really not high priority because we can always start with base64 encoding (performance is less of an issue for the offline backend). For the online backend we now have everything we need already. But feel free to reopen if you need this @almarklein

**Comment by sh4wn** [comment]
Haha well it sounded like a fun project, but I'll search for another!
