### ISSUE TITLE
viridis colormap.py fails with stride 2 but works with stride changed to 4

### ISSUE THREAD

**Issue by pocdn** [vispy/vispy#1331]
Problem: colorbar crashes when using viridis colormap. The problem seems to be
the size of the _viridis_data passed to Colormap(ColorArray(...)).

To reproduce the crash, the example colorbar.py file with a slight modification as follows:

replace "hsl" with "viridis" in 
https://github.com/vispy/vispy/blob/master/examples/basics/plotting/colorbar.py

line 36:
plot.image(img, cmap="viridis")

line 45: 
cmap="viridis"

Then run test.py (=colorbar.py with 'viridis' change) ... complains (see error message at appendix below) and does NOT show any color bars.

But if I manually change the system wide vispy installed file:
https://github.com/vispy/vispy/blob/master/vispy/color/colormap.py
by changing the stride from [::2] to [::**4**] (reducing sampled _viridis_data

 passed length to 64 samples) on

Line 956:
viridis=Colormap(ColorArray(_viridis_data[::**4**])),

The original colorbar.py test file works now works with (4 instead of 2 for stride).

Is there a better fix? Or can this simple one character change be merged into the colormap.py?

For those interested the complete error message is

> $ python test.py
> WARNING: Error drawing visual <Image at 0x7f0387ce9510>
> WARNING: Traceback (most recent call last):
>   File "test.py", line 49, in <module>
>     fig.show(run=True)
>   File "/scratch/tmp/vispy/vispy/app/canvas.py", line 431, in show
>     self.app.run()
>   File "/scratch/tmp/vispy/vispy/app/application.py", line 137, in run
>     return self._backend._vispy_run()
>   File "/scratch/tmp/vispy/vispy/app/backends/_qt.py", line 229, in _vispy_run
>     return app.exec_()
>   File "/scratch/tmp/vispy/vispy/app/backends/_qt.py", line 431, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "/scratch/tmp/vispy/vispy/app/backends/_qt.py", line 431, in event
>     out = super(QtBaseCanvasBackend, self).event(ev)
>   File "/scratch/tmp/vispy/vispy/app/backends/_qt.py", line 703, in paintGL
>     self._vispy_canvas.events.draw(region=None)
>   File "/scratch/tmp/vispy/vispy/util/event.py", line 455, in __call__
>     self._invoke_callback(cb, event)
>   File "/scratch/tmp/vispy/vispy/util/event.py", line 475, in _invoke_callback
>     self, cb_event=(cb, event))
>   << caught exception here: >>
>   File "/scratch/tmp/vispy/vispy/util/event.py", line 471, in _invoke_callback
>     cb(event)
>   File "/scratch/tmp/vispy/vispy/scene/canvas.py", line 207, in on_draw
>     self._draw_scene()
>   File "/scratch/tmp/vispy/vispy/scene/canvas.py", line 253, in _draw_scene
>     self.draw_visual(self.scene)
>   File "/scratch/tmp/vispy/vispy/scene/canvas.py", line 291, in draw_visual
>     node.draw()
>   File "/scratch/tmp/vispy/vispy/scene/visuals.py", line 98, in draw
>     self._visual_superclass.draw(self)
>   File "/scratch/tmp/vispy/vispy/visuals/visual.py", line 440, in draw
>     self._vshare.index_buffer)
>   File "/scratch/tmp/vispy/vispy/visuals/shaders/program.py", line 77, in draw
>     Program.draw(self, *args, **kwargs)
>   File "/scratch/tmp/vispy/vispy/gloo/program.py", line 470, in draw
>     canvas.context.flush_commands()
>   File "/scratch/tmp/vispy/vispy/gloo/context.py", line 171, in flush_commands
>     self.glir.flush(self.shared.parser)
>   File "/scratch/tmp/vispy/vispy/gloo/glir.py", line 232, in flush
>     self._shared.flush(parser)
>   File "/scratch/tmp/vispy/vispy/gloo/glir.py", line 146, in flush
>     parser.parse(self._filter(self.clear(), parser))
>   File "/scratch/tmp/vispy/vispy/gloo/glir.py", line 458, in parse
>     self._parse(command)
>   File "/scratch/tmp/vispy/vispy/gloo/glir.py", line 436, in _parse
>     ob.set_shaders(*args)
>   File "/scratch/tmp/vispy/vispy/gloo/glir.py", line 640, in set_shaders
>     % gl.glGetProgramInfoLog(self._handle))
> RuntimeError: Program linking error:
> Fragment info
> 
> Internal error: assembly compile error for fragment shader at offset 17541:
>  error message 
> line 477, column 7:  error: IF statement nested too deeply.
> line 480, column 5:  error: ELSE already found at current nesting level.
> line 483, column 7:  error: IF statement nested too deeply.
> line 486, column 5:  error: ELSE already found at current nesting level.
> line 489, column 7:  error: IF statement nested too deeply.
> line 492, column 5:  error: ELSE already found at current nesting level.
> line 495, column 7:  error: IF statement nested too deeply.
> line 498, column 5:  error: ELSE already found at current nesting level.
> line 501, column 7:  error: IF statement nested too deeply.
> line 504, column 5:  error: ELSE already found at current nesting level.
> line 507, column 7:  error: IF statement nested too deeply.
> line 510, column 5:  error: ELSE already found at current nesting level.
> line 513, column 7:  error: IF statement nested too deeply.
> line 516, column 5:  error: ELSE already
> ERROR: Invoking <bound method Fig.on_draw of <Fig (PyQt4) at 0x7f039c5f5610>> for DrawEvent
> WARNING: Error drawing visual <Image at 0x7f0387ce9510>
> ERROR: Invoking <bound method Fig.on_draw of <Fig (PyQt4) at 0x7f039c5f5610>> repeat 2
> WARNING: Error drawing visual <Image at 0x7f0387ce9510>
> WARNING: Error drawing visual <Image at 0x7f0387ce9510>
> ERROR: Invoking <bound method Fig.on_draw of <Fig (PyQt4) at 0x7f039c5f5610>> repeat 4

**Comment by davidh-ssec** [comment]
@pocdn This is actually a limitation of your GPU, but you are not the first to encounter it. This has been described in #1052 and my own issue #1089. You'll see in the first issue that there are suggestions for how it could be implemented, but as far as I know no one has started work on this.

**Comment by davidh-ssec** [comment]
Dup of #1052

**Comment by pocdn** [comment]
A NVIDIA 1050 GTX and Nvidia Quadro K2200 has such a limitation, that's unfortunate to see since I testedboth of those. The referenced [#1052](https://github.com/vispy/vispy/issues/1052) started Aug 15, 2015, almost 2 years ago. IMHO It would be good to at least have a band aid fix (change a "2" to a "4" in a single file, colormap.py)  for to enable a non-crash with viridis colormap choice until the more general and better 2D texture lookup version gets implemented.

**Comment by davidh-ssec** [comment]
@pocdn Now I'm just curious, is this on Windows? iirc I only had problems with viridis on Windows.

As for the striding I found this commit https://github.com/vispy/vispy/commit/1bb2a766ca07afa742b1dc3bfcb8936dd3e931cc
My biggest worry with bumping the stride to 4 is that we are cutting a 256 point colormap down to 64 points. That's quite a bit. I'm open to testing it to see the difference. Another short term solution could be to add a "viridis_64" or similar colormap to the builtins. @Eric89GXL Thoughts?

**Comment by Eric89GXL** [comment]
> My biggest worry with bumping the stride to 4 is that we are cutting a 256 point colormap down to 64 points.

It should still do linear interpolation between those 64 points, so it depends on how non-linear the `viridis` colormap is. So let's look at just the `red` channel at least:
```
>>> import matplotlib.pyplot as plt
>>> cmap = plt.get_cmap('viridis')
>>> x = np.linspace(0, 1, 256); plt.plot(x, cmap(x)[:, 0])
>>> x2 = np.linspace(0, 1, 64); plt.plot(x2, cmap(x2)[:, 0])
>>> plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/2365790/26231277/58855720-3c1c-11e7-9549-1d86899155c2.png)

Or to be more quantitative:
```
>>> np.abs(np.interp(x, x2, cmap(x2)[:, 0]) - cmap(x)[:, 0]).max() * 256
1.6228261647058844
```
So it's roughly triple what would otherwise be the rounding error. Turns out red is the worst, too:
```
>>> np.abs(np.interp(x, x2, cmap(x2)[:, 1]) - cmap(x)[:, 1]).max() * 256
0.79180799999998897
>>> np.abs(np.interp(x, x2, cmap(x2)[:, 2]) - cmap(x)[:, 2]).max() * 256
0.97488112941175586
```
I'd say it's fine to decimate more for now.

The texture solution isn't so hard in principle, but nobody has had time to work on it. :(

**Comment by pocdn** [comment]
@davidh-ssec Now I'm just curious, is this on Windows? iirc I only had problems with viridis on Windows.

I had the exact same result on Windows (Nvidia Quadro K2200) as on Linux (Nvidia 1050GTX Driver 375.66). To my eye, the 64-sampled version of viridis looked clean with no observable banding | degradation in both cases. The quantitative analysis is much better than my eye; being off by at most 1.6/256<1% seems to be a good compromise until the texture solution is implemented. That small change to 64 instead of 128 samples would be nice to have implemented. For me and colorblind coworkers the Viridis colormap is the better/best one to show key subtle features in some recent measurements results.

**Comment by Eric89GXL** [comment]
@pocdn assuming @davidh-ssec agrees with this, could you make a PR? It might be a one-liner

**Comment by pocdn** [comment]
Yes, if @davidh-ssec  agrees I will make a PR to change the stride from 2 to 4 in the colormap.py file.

> Line 956:
> viridis=Colormap(ColorArray(_viridis_data[::4])),

As a side note, just to show what I see with the 64-bit interpolated viridis colormap;
![viridis_64](https://cloud.githubusercontent.com/assets/6920644/26232495/8415af90-3c0b-11e7-81ce-588b79e69cf8.png)

**Comment by davidh-ssec** [comment]
Works for me. Thanks.

**Comment by pocdn** [comment]
Thank you.

I completed the PR.
