### ISSUE TITLE
3D picking with scenegraph

### ISSUE THREAD

**Issue by dcam0050** [vispy/vispy#1336]
I am wondering if there is a tutorial from which I can understand how to do picking in 3D. To give an example my current simple application is this:

```
from vispy import scene
import numpy as np

c = scene.SceneCanvas(keys='interactive', show=True)

view = c.central_widget.add_view()
view.camera = 'fly'
view.camera.depth = 10

pos = np.array([(0, 0, 0), (2, 1, 1)])
s = scene.Markers(pos=pos, parent=view.scene)
s.interactive = True

@c.connect
def on_mouse_press(event):
    global c
    print event.pos
    print c.visual_at(event.pos)

c.app.run()
```

When I run this I get `[566 340] <ViewBox at 0x7f15f4fcc990>` which has been referenced in Issue #1231.

I then substituted `print c.visual_at(event.pos)` with the following in order to address the markers with their world coordinates.
```
print c.visual_at([0, 0, 0])
print c.visual_at([2, 0, 0])
```
but received the following output:
`None None`

My question is: Which coordinate frame do I need to translate to, to get the visual id? And which coordinate frame is event.pos in?

Thanks for any help!

**Comment by dcam0050** [comment]
Ok my bad so I updated the code as said on the google groups link.

```
def on_mouse_press(event): 
   view.interactive = False
   print c.visual_at(event.pos)
   view.interactive = True
```
and I now get `Markers at 0x7f28a9c4d690` but I get the same reply for both markers. Is it possible to return an id for the individual markers?

**Comment by davidh-ssec** [comment]
@dcam0050 I don't have a ton of experience with `visual_at` more than the basics and I had trouble getting a `Markers` object returned by clicking on the second (right most) Marker point. My guess for why you are getting the same Markers object is that `visual_at` only returns `Visual` objects, it can't give you identifiers for sub-components of a Visual object because they don't have individual IDs. It would be like drawing a shape with a LineVisual and expecting it to tell you which specific line segment was clicked on.

You could try making two separate Markers visuals and test that.

**Comment by rougier** [comment]
Note that there exists a different techniques based on color. Each object is painted (virtually) with a different color that encodes the id of the object. By getting the color under the pointer, you get the ide of object. See an example in glumpy: https://github.com/glumpy/glumpy/blob/master/examples/gloo-picking.py

**Comment by dcam0050** [comment]
Thanks for the suggestions! I've tried having an array of markers but this is not the way forward for me because I need to frequently change marker positions (force directed graph) so iterating through an array becomes slow even at just 200 markers.

I've been trying to piece together the other suggestion and so far I've managed to extract an array of pixels with vispy. I also understand that I need to have an alternative fragment shader populated with the ids in the form of colour. However I can't figure out how to read the particular buffer before calling read_pixels because as I understand read_pixels on its own returns the values present in the current viewport for glFrag_Color

**Comment by davidh-ssec** [comment]
@dcam0050 Could you show some of your code for getting this far? I've never done this in vispy, but if you can get access to the vispy `FrameBuffer` object that you are drawing to you should be able to do `fb.read()` to get the content of the buffer.

**Comment by dcam0050** [comment]
I've attached all of the code I have. Changing the parameter 'pickable' from main to 'True' demonstrates the implementation using an array of markers. This allows you to pick a node and prints the node id and the corresponding data but it is very slow to initialise and to update.

Setting 'pickable' to 'False' switches to the pixel array implementation. For this I've only figured out how to get an array of pixels as you can see from `@self.canvas.connect` and I print out the array details

```
from vispy import app, scene, color, util, gloo
import numpy as np


class MyNodes(scene.Markers):
    def __init__(self, nodeData=None, **kwargs):
        self.nodeData = nodeData
        scene.Markers.__init__(self, **kwargs)


# Display the data
class GraphVisual():
    def __init__(self, nodePos, edgePairs, nodeColors, parameters):

        self.nodePos = nodePos
        self.nPts = nodePos.shape[0]
        self.layoutDims = nodePos.shape[1]
        self.edgePairs = edgePairs
        self.nodeColors = nodeColors
        self.edges = []
        self.nodes = []
        self.canvas = None
        self.view = None
        self.parameters = parameters
        self.initCanvas()

        if self.parameters['pickable']:
            self.initNodesEdges_pickable()
        else:
            self.initNodesEdges()

        self.t = 1
        self.forceUpdateTimer = app.Timer(interval=0, connect=self.forceUpdate, start=True)

    def initCanvas(self):
        self.canvas = scene.SceneCanvas(keys='interactive', show=True)
        self.view = self.canvas.central_widget.add_view()
        self.view.camera = 'fly'
        self.view.camera.aspect = 1
        self.view.camera.set_range()

        @self.canvas.connect
        def on_mouse_press(event):

            print 'buttonNum:', event.button, '| eventType:', event.type, '| modifiers:', event.modifiers, '| delta:', event.delta

            if event.handled or event.button != 1:
                return

            if self.parameters['pickable']:
                self.view.interactive = False
                for v in self.canvas.visuals_at(event.pos, radius=20):
                    if isinstance(v, scene.Markers):
                        print v.nodeData
                        break
                self.view.interactive = True
            else:
                pixelArray = gloo.read_pixels()
                print type(pixelArray), pixelArray.shape, event.pos


    def initNodesEdges_pickable(self):
        # #convert edge pairs to vertices
        # edgeVerts = pos[edges.reshape(1, edges.size), :].squeeze()

        self.edges = scene.Line(pos=self.nodePos, connect=self.edgePairs,
                                antialias=True, method='gl',
                                color=(1, 1, 1, 0.6), parent=self.view.scene)

        for j in range(self.nPts):
            self.nodes.append(MyNodes(pos=self.nodePos[j, np.newaxis], parent=self.view.scene,
                                      scaling=self.parameters['scaling'],
                                      face_color=self.nodeColors[j], size=self.parameters['nodeSize'],
                                      nodeData=np.array([j, "filePathOfData_String", "dataType_String"])))
            self.nodes[-1].interactive = True

    def initNodesEdges(self):
        # #convert edge pairs to vertices
        # edgeVerts = pos[edges.reshape(1, edges.size), :].squeeze()

        self.edges = scene.Line(pos=self.nodePos, connect=self.edgePairs,
                                antialias=True, method='gl',
                                color=(1, 1, 1, 0.6), parent=self.view.scene)

        self.nodes = scene.Markers(pos=self.nodePos, face_color=self.nodeColors, symbol='o',
                                   parent=self.view.scene, scaling=self.parameters['nodeSize'],
                                   size=self.parameters['nodeSize'])
        self.nodes.interactive = True

    def forceUpdate(self, ev):
        dx = np.empty((self.nPts, self.nPts, self.layoutDims), dtype='float32')
        dx[:] = self.nodePos[:, np.newaxis, :]
        dx -= self.nodePos[np.newaxis, :, :]

        dist = (dx ** 2).sum(axis=2) ** 0.5
        dist[dist == 0] = 1.
        ndx = dx / dist[..., np.newaxis]

        force = np.zeros((self.nPts, self.nPts, self.layoutDims), dtype='float32')

        # all points push away from each other
        force -= 0.1 * ndx / dist[..., np.newaxis] ** 2

        # connected points pull toward each other
        # pulsed force helps to settle faster:
        s = 0.3
        # s = 0.05 * 5 ** (np.sin(i/20.) / (i/100.))

        # s = 0.05 + 1 * 0.99 ** i
        mask = np.zeros((self.nPts, self.nPts, 1), dtype='float32')
        mask[self.edgePairs[:, 0], self.edgePairs[:, 1]] = s
        mask[self.edgePairs[:, 1], self.edgePairs[:, 0]] = s
        force += dx * dist[..., np.newaxis] * mask

        # points do not exert force on themselves
        force[np.arange(self.nPts), np.arange(self.nPts)] = 0

        force = force.sum(axis=0)
        self.nodePos += np.clip(force, -3, 3) * 0.09

        self.edges.set_data(pos=self.nodePos)

        if self.parameters['pickable']:
            for j in range(self.nPts):
                self.nodes[j].set_data(pos=self.nodePos[j, np.newaxis], face_color=self.nodeColors[j], size=self.parameters['nodeSize'])
        else:
            self.nodes.set_data(pos=self.nodePos, face_color=self.nodeColors, size=self.parameters['nodeSize'])

        self.t += 1


if __name__ == '__main__':
    # Initialize arrays for position, color, edges, and types for each point in
    # the graph.
    npts = 200
    nedges = 500
    ngroups = 8
    np.random.seed(127396)
    dims = 3
    dx = 1234567890
    pos = np.empty((npts, dims), dtype='float32')
    colors = np.empty((npts, 3), dtype='float32')
    edges = np.empty((nedges, 2), dtype='uint32')
    types = np.empty(npts, dtype=int)

    # Assign random starting positions
    pos[:] = np.random.normal(size=pos.shape, scale=4.)

    # Assign each point to a group
    grpsize = npts // ngroups
    ptr = 0
    typ = 0
    while ptr < npts:
        size = np.random.random() * grpsize + grpsize // 2
        types[int(ptr):int(ptr + size)] = typ
        typ += 1
        ptr = ptr + size

    # Randomly select connections, with higher connection probability between
    # points in the same group
    conn = []
    connset = set()
    while len(conn) < nedges:
        i, j = np.random.randint(npts, size=2)
        if i == j:
            continue
        p = 0.7 if types[i] == types[j] else 0.01
        if np.random.random() < p:
            if (i, j) in connset:
                continue
            connset.add((i, j))
            connset.add((j, i))
            conn.append([i, j])
    edges[:] = conn
    print np.min(edges)
    # Assign colors to each point based on its type
    cmap = color.get_colormap('cubehelix')
    typ_colors = np.array([cmap.map(x)[0, :3] for x in np.linspace(0.2, 0.8, typ)])
    colors[:] = typ_colors[types]

    # Add some RGB noise and clip
    colors *= 1.1 ** np.random.normal(size=colors.shape)
    colors = np.clip(colors, 0, 1)

    parameters = dict()
    parameters['pickable'] = True
    parameters['nodeSize'] = 30
    parameters['scaling'] = True

    myGraph = GraphVisual(nodePos=pos, edgePairs=edges, nodeColors=colors, parameters=parameters)

    app.run()
```

**Comment by dcam0050** [comment]
For it to work I need to make a copy of the markers class and add something like 
`varying float v_id;` to the fragment shader but I'm not sure about how to go about adding this to something similair to `gl_FragColor`

**Comment by dcam0050** [comment]
Also thanks for the help! I'm what you call a noob in OpenGl haha

**Comment by dcam0050** [comment]
Might I add I'm using python 2.7 and vispy 0.5.0-dev

**Comment by davidh-ssec** [comment]
I made a small change (besides print statements for python 3 compatibility) in your mouse event handler:

```
                self.view.interactive = False
                for v in self.canvas.visuals_at(event.pos, radius=20):
                    if v is self.nodes:
                        pixelArray = gloo.read_pixels()
                        print(type(pixelArray), pixelArray.shape, event.pos, pixelArray[event.pos[1], event.pos[0]])
                        break
                self.view.interactive = True```

I am not an expert when it comes to doing fancier picking like this, but as you should see the last value printed there `pixelArray[event.pos[1], event.pos[0]]` is the actual color under the cursor. Once you have the color you should be able to search your colors to get the index of that Marker so something like `np.where(self.nodeColors == pixelArray[event.pos[1], event.pos[0]])[0]` should give you the index of the first node that has the color under the cursor. There is a small problem when you click the lines/edges of the graph it sees the gray color of the line rather than the marker underneath. Like I said I'm not an expert.

**Comment by dcam0050** [comment]
Ok so I've found a way to do this by creating a CompoundVisual class copy which I've called CompundVisualMultiBuffer with some extras.

During __init__ the class receives a list of subvisuals together with a list of buffers to draw these subvisuals to. 

'default' draws to screen while any other buffer names result in the creation of a blank small texture that is rendered to everytime draw is issued and resized everytime there is a physical event.

With this I've managed to create a picking interface for a 3D graph and also added some visual nuggets such as highlighting which highlights the picked node, adjoining edges and the first level of connected nodes.

If you want to try it check it out here https://github.com/Sheffield-XPrize/SAM-Visualiser

**Comment by davidh-ssec** [comment]
@dcam0050 Very interesting and glad you got it working. Would you mind doing a little bit more work and making a pull request to add it to vispy? First a couple questions:

1. What does this buy you that rendering to a new framebuffer couldn't? By that I mean, couldn't you just add logic to your `nodeID` markers (possibly as a subclass) that creates the FrameBuffer, draws, and then reads the results? It would only need to be called during picking. You could also avoid all the `visual_frametarget` logic.
2. Is there a reason that `CompoundVisualMultiBuffer` should be a subclass of `CompoundVisual`? Wouldn't this remove a lot of the methods that you copied?
3. You seem to do some `deepcopy`s for every pick. Is it possible to do this without copying every time? Also if these are numpy arrays you could just do `arr.copy()`. Instead of making copies in some of the stuff it would probably be better to just reassign the values `my_arr[:] = orig_arr[:]` if that really is needed.

If you do consider adding some of this logic somewhere in vispy could you please:

1. Replace camel case variable names with underscored names: `nodePos` -> `node_pos`.
2. Change `graphData` items to individual instance attributes and then `change_edge_color` to a property getter/setter.
3. `class GraphVisual(<some base class>)`

**Comment by dcam0050** [comment]
Thanks a lot for the pointers! I've implemented all of them and pushed to my project for now. How do you propose I include my code? As a tutorial? Or as an addition to the visual class?

**Comment by davidh-ssec** [comment]
Good question. Maybe @Eric89GXL, @kmuehlbauer, @rougier have some thoughts? If it can be put in to a small single subclass of Markers for a new "pick" method or something then adding it to the Markers class or adding it as a tutorial would be a good idea. I think the CompoundVisualMultiBuffer can be simplified to drawing a single Visual to a framebuffer off screen. If the colors on screen are used for identifying then it is pretty easy. If the colors shouldn't be drawn on screen and only off, then a separate Visual class might be useful, like hot spots. At least that's what comes to me off the top of my head.

**Comment by rougier** [comment]
It can probably be extended beyond the markers subclass but that would require more work.

**Comment by kmuehlbauer** [comment]
@dcam0050 I'm currently trying to get an impression of how this works. It would be good to have kind of self contained example (like your initial two marker example) for testing. At least for me it would be a lot easier to get behind the scenes then.

**Comment by dcam0050** [comment]
No problem I'll post an MWE later on next week as I'm currently busy but I'm interested to do this!

**Comment by kmuehlbauer** [comment]
@dcam0050 Thanks for the heads-up. And no rush, take your time.

**Comment by os-gabe** [comment]
I realize this is a pretty stale thread but I also need to implement 3D picking of indvidual markers (as well as other things) within a scene graph. Any chance you can provide example code for how you accomplished this @dcam0050 ?

**Comment by f0k** [comment]
I was also interested in getting this to work. What I did in the end was to replicate the color-based picking approach of vispy, but using a separate color per marker, not per visual. I didn't use a shader, instead I disabled blending and antialiasing. See the example code below.

```python
#!/usr/bin/env python3
# encoding: utf8
"""
Vispy 3d scatter plot with clickable markers demo.

Author: Jan Schlüter
"""

import numpy as np
from vispy import app, visuals, scene, color


def distance_traveled(positions):
    """
    Return the total amount of pixels traveled in a sequence of pixel
    `positions`, using Manhattan distances for simplicity.
    """
    return np.sum(np.abs(np.diff(positions, axis=0)))


def scatter3d(positions, colors, symbol='o', size=4.5, click_radius=2,
              on_click=None):
    """
    Create a 3D scatter plot window that is zoomable and rotateable, with
    markers of a given `symbol` and `size` at the given 3D `positions` and in
    the given RGBA `colors`, formatted as numpy arrays of size Nx3 and Nx4,
    respectively. Takes an optional callback function that will be called with
    the index of a clicked marker and a reference to the Markers visual
    whenever the user clicks a marker (or at most `click_radius` pixels next to
    a marker).
    """
    # based on https://github.com/vispy/vispy/issues/1189#issuecomment-198597473
    # create canvas
    canvas = scene.SceneCanvas(keys='interactive', show=True, bgcolor='gray')
    # create viewbox for user interaction
    view = canvas.central_widget.add_view()
    view.camera = 'turntable'
    view.camera.fov = 45
    view.camera.distance = abs(positions).max() * 2.5
    # create visuals
    p1 = scene.visuals.Markers(parent=view.scene)
    p1.set_gl_state('translucent', blend=True, depth_test=True)
    #axis = scene.visuals.XYZAxis(parent=view.scene)
    # set positions and colors
    kwargs = dict(symbol=symbol, size=size, edge_color=None)
    p1.set_data(positions, face_color=colors, **kwargs)
    # prepare list of unique colors needed for picking
    ids = np.arange(1, len(positions) + 1, dtype=np.uint32).view(np.uint8)
    ids = ids.reshape(-1, 4)
    ids = np.divide(ids, 255, dtype=np.float32)
    # connect events
    if on_click is not None:
        def on_mouse_release(event):
            if event.button == 1 and distance_traveled(event.trail()) <= 2:
                # vispy has some picking functionality that would tell us
                # whether any of the scatter points was clicked, but we want
                # to know which point was clicked. We do an extra render pass
                # of the region around the mouseclick, with each point
                # rendered in a unique color and without blending and
                # antialiasing.
                pos = canvas.transforms.canvas_transform.map(event.pos)
                try:
                    p1.update_gl_state(blend=False)
                    p1.antialias = 0
                    p1.set_data(positions, face_color=ids, **kwargs)
                    img = canvas.render((pos[0] - click_radius,
                                         pos[1] - click_radius,
                                         click_radius * 2 + 1,
                                         click_radius * 2 + 1),
                                        bgcolor=(0, 0, 0, 0))
                finally:
                    p1.update_gl_state(blend=True)
                    p1.antialias = 1
                    p1.set_data(positions, face_color=colors, **kwargs)
                # We pick the pixel directly under the click, unless it is
                # zero, in which case we look for the most common nonzero
                # pixel value in a square region centered on the click.
                idxs = img.ravel().view(np.uint32)
                idx = idxs[len(idxs) // 2]
                if idx == 0:
                    idxs, counts = np.unique(idxs, return_counts=True)
                    idxs = idxs[np.argsort(counts)]
                    idx = idxs[-1] or (len(idxs) > 1 and idxs[-2])
                # call the callback function
                if idx > 0:
                    # subtract one; color 0 was reserved for the background
                    on_click(idx - 1, p1)

        canvas.events.mouse_release.connect(on_mouse_release)

    # run application
    app.run()


if __name__ == "__main__":
    data = np.random.randn(1000, 3)
    cmap = color.get_colormap('viridis')
    colors = np.concatenate(list(map(cmap.map, np.linspace(0, 1, len(data)))))
    def on_click(idx, markers):
        # turn the clicked marker white just for demonstration
        colors[idx] = (1, 1, 1, 1)
        markers.set_data(data, face_color=colors, symbol='o', size=4.5,
                         edge_color=None)

    scatter3d(data, colors, on_click=on_click)
```

**Comment by os-gabe** [comment]
This is exactly what I needed @f0k, thank you for sharing!

I'm finding the call to `canvas.render` quite slow even though my click radius is 0 pixels so the region I'm rendering is a single pixel. Perhaps it is still due to my scene being fairly complex (pointcloud plus mesh with > 1M faces).

Was performance acceptable for you? How many individual markers are you plotting?

**Comment by f0k** [comment]
> Was performance acceptable for you? How many individual markers are you plotting?

I didn't see any performance problems. I was plotting about 1.2M markers, but nothing else. If you run my example script and bump up the number of markers (in the `data = np.random.randn(1000, 3)` line), does it also feel too slow to you?

**Comment by freckletonj** [comment]
I noticed a PR with a relevant example: https://github.com/vispy/vispy/pull/1225
file: https://github.com/vispy/vispy/blob/64e76c40c8d7d38efc53c9a1a50ca7f336b9ffc2/examples/basics/scene/points_selection.py

**Comment by iPsych** [comment]
> I was also interested in getting this to work. What I did in the end was to replicate the color-based picking approach of vispy, but using a separate color per marker, not per visual. I didn't use a shader, instead I disabled blending and antialiasing. See the example code below.
> 
> ```python
> #!/usr/bin/env python3
> # encoding: utf8
> """
> Vispy 3d scatter plot with clickable markers demo.
> 
> Author: Jan Schlüter
> """
> 
> import numpy as np
> from vispy import app, visuals, scene, color
> 
> 
> def distance_traveled(positions):
>     """
>     Return the total amount of pixels traveled in a sequence of pixel
>     `positions`, using Manhattan distances for simplicity.
>     """
>     return np.sum(np.abs(np.diff(positions, axis=0)))
> 
> 
> def scatter3d(positions, colors, symbol='o', size=4.5, click_radius=2,
>               on_click=None):
>     """
>     Create a 3D scatter plot window that is zoomable and rotateable, with
>     markers of a given `symbol` and `size` at the given 3D `positions` and in
>     the given RGBA `colors`, formatted as numpy arrays of size Nx3 and Nx4,
>     respectively. Takes an optional callback function that will be called with
>     the index of a clicked marker and a reference to the Markers visual
>     whenever the user clicks a marker (or at most `click_radius` pixels next to
>     a marker).
>     """
>     # based on https://github.com/vispy/vispy/issues/1189#issuecomment-198597473
>     # create canvas
>     canvas = scene.SceneCanvas(keys='interactive', show=True, bgcolor='gray')
>     # create viewbox for user interaction
>     view = canvas.central_widget.add_view()
>     view.camera = 'turntable'
>     view.camera.fov = 45
>     view.camera.distance = abs(positions).max() * 2.5
>     # create visuals
>     p1 = scene.visuals.Markers(parent=view.scene)
>     p1.set_gl_state('translucent', blend=True, depth_test=True)
>     #axis = scene.visuals.XYZAxis(parent=view.scene)
>     # set positions and colors
>     kwargs = dict(symbol=symbol, size=size, edge_color=None)
>     p1.set_data(positions, face_color=colors, **kwargs)
>     # prepare list of unique colors needed for picking
>     ids = np.arange(1, len(positions) + 1, dtype=np.uint32).view(np.uint8)
>     ids = ids.reshape(-1, 4)
>     ids = np.divide(ids, 255, dtype=np.float32)
>     # connect events
>     if on_click is not None:
>         def on_mouse_release(event):
>             if event.button == 1 and distance_traveled(event.trail()) <= 2:
>                 # vispy has some picking functionality that would tell us
>                 # whether any of the scatter points was clicked, but we want
>                 # to know which point was clicked. We do an extra render pass
>                 # of the region around the mouseclick, with each point
>                 # rendered in a unique color and without blending and
>                 # antialiasing.
>                 pos = canvas.transforms.canvas_transform.map(event.pos)
>                 try:
>                     p1.update_gl_state(blend=False)
>                     p1.antialias = 0
>                     p1.set_data(positions, face_color=ids, **kwargs)
>                     img = canvas.render((pos[0] - click_radius,
>                                          pos[1] - click_radius,
>                                          click_radius * 2 + 1,
>                                          click_radius * 2 + 1),
>                                         bgcolor=(0, 0, 0, 0))
>                 finally:
>                     p1.update_gl_state(blend=True)
>                     p1.antialias = 1
>                     p1.set_data(positions, face_color=colors, **kwargs)
>                 # We pick the pixel directly under the click, unless it is
>                 # zero, in which case we look for the most common nonzero
>                 # pixel value in a square region centered on the click.
>                 idxs = img.ravel().view(np.uint32)
>                 idx = idxs[len(idxs) // 2]
>                 if idx == 0:
>                     idxs, counts = np.unique(idxs, return_counts=True)
>                     idxs = idxs[np.argsort(counts)]
>                     idx = idxs[-1] or (len(idxs) > 1 and idxs[-2])
>                 # call the callback function
>                 if idx > 0:
>                     # subtract one; color 0 was reserved for the background
>                     on_click(idx - 1, p1)
> 
>         canvas.events.mouse_release.connect(on_mouse_release)
> 
>     # run application
>     app.run()
> 
> 
> if __name__ == "__main__":
>     data = np.random.randn(1000, 3)
>     cmap = color.get_colormap('viridis')
>     colors = np.concatenate(list(map(cmap.map, np.linspace(0, 1, len(data)))))
>     def on_click(idx, markers):
>         # turn the clicked marker white just for demonstration
>         colors[idx] = (1, 1, 1, 1)
>         markers.set_data(data, face_color=colors, symbol='o', size=4.5,
>                          edge_color=None)
> 
>     scatter3d(data, colors, on_click=on_click)
> ```

@f0k Hello f0k,
Since you posted awesome example to pick and change the 'object' in scenegraph, do you have any idea to pick faces or vertices of mesh in scenegraph? I adopted the example, but it randomly select overlapped vertices ignoring the depth.

**Comment by f0k** [comment]
> I adopted the example, but it randomly select overlapped vertices ignoring the depth.

I'm not a vispy expert at all -- try to find out why it ignores the depth in rendering. Does the scene look correct? What about the small image resulting from the `canvas.render()` call, does it look correct except for changed colors?

**Comment by kmuehlbauer** [comment]
It looks like the example by @f0k solves the immediate problem. Considering the age of the issue, I'll close. If there is still something to discuss, we can reopen. Or open a new issue, if your problem does not really match.
