### ISSUE TITLE
matplotlib's plot_surface to vispy

### ISSUE THREAD

**Issue by skostrichegg** [vispy/vispy#1339]
Hi,

Is it possible to transform matplotlib's plot_surface to vispy?

x.shape : (51, 51)
y.shape : (51, 51)
z.shape : (51, 51)

In matplotlib:
plot_surface(y, x, z, color=(0.9, 0.9, 0.9), edgecolor="none", alpha=0.8)

I tried to use scene.visuals.SurfacePlot(), but it takes 1D array for X, Y.

Could anyone help me?....

Thanks.

**Comment by kmuehlbauer** [comment]
@skostrichegg 

AFAIK the `SufarcePlotVisual` is capable of plotting regular cartesian grids. So if your data is structured like this you can plot your 2D `z` array using 1D `x` and `y` arrays. 

```scene.visuals.SurfacePlot(x=x[:, 0], y=y[0, :], z=z, color=(0.3, 0.3, 1, 1))```

Or you just plot your 2D z array.

```scene.visuals.SurfacePlot(z=z, color=(0.3, 0.3, 1, 1))```

You may also use the higher level plot interface like this:

```python
import numpy as np

from vispy import plot as vp
from vispy.util.filter import gaussian_filter

z = np.random.normal(size=(250, 250), scale=200)
z[100, 100] += 50000
z = gaussian_filter(z, (10, 10))

fig = vp.Fig(size=(800, 400), show=False)
fig[0, 0].surface(z)
fig.show(run=True)
```
![screenshot_20170707_084637](https://user-images.githubusercontent.com/5821660/27946191-d95794b2-62f0-11e7-9e9f-629a5d8a9382.png)

Note that `plot.surface` doesn't have the capability of automated grids and axes, but you can add those to your liking.

If your data is on a non regular grid, than you can't use `SurfacePlotVisual` out of the box. I assume that you would need to subclass `MeshVisual`, but there might be other solutions.

**Comment by kmuehlbauer** [comment]
@skostrichegg Did you manage to get along with this? A short notice will suffice.

**Comment by skostrichegg** [comment]
@kmuehlbauer Oh, so sorry for late.. I just tested like you mentioned. It works fine for the case using meshgrid() in matplotlib. But in some cases (like below data), it doesn't work.
====================================================
u = np.linspace(0, 2 * np.pi, 100)
v = np.linspace(0, np.pi, 100)

x = 10 * np.outer(np.cos(u), np.sin(v))
y = 10 * np.outer(np.sin(u), np.sin(v))
z = 10 * np.outer(np.ones(np.size(u)), np.cos(v))

**Comment by kmuehlbauer** [comment]
@skostrichegg AFAIK  `SurfacePlotVisual` and therefore `plot.surface` is bound to a rectangular (x,y)-grid with corresponding z-values to form the surface from.

If you want to plot spheriods and alike you would need to use some other vispy functions, eg. `IsosurfaceVisual`. There is an [example here](https://github.com/vispy/vispy/blob/master/examples/basics/scene/isosurface.py).

However, `IsoSurfaceVisual` isn't available via the higher level `plot`.

**Comment by skostrichegg** [comment]
@kmuehlbauer Thanks for the answer.
