### ISSUE TITLE
typeError in vispy collection module

### ISSUE THREAD

**Issue by ThomJea** [vispy/vispy#1340]
hay,
I checked if the issue existed but couldn't find it, which is odd because here is the thing:
when running the collection examples from python35, I get several typeError which can be corrected (at least so that the example runs)

example : agg_fast_path_collection.py line 127, "itemcount" is defined by a division which returns a float whereas it should be an integer. the fix is simply to "int()" the division or "//".

I don't know the code and implications of such a change.

Regards,

**Comment by kmuehlbauer** [comment]
@ThomJea Thanks for reporting. AFAIK this behaviour changed between python 2.7 and 3.X. As `itemcount` is wanted an int, we can safely use the `int()` to do this conversion. 

Do you mind issuing a PR with the needed changes for the collection examples?

**Comment by ThomJea** [comment]
Not so many people under python3 here =)
No pb, I'm currently at work, i'll do it in a few hours

**Comment by ThomJea** [comment]
ok, I forked it but it is too late by now, I won't have the time this WE. Sorry!
regards

**Comment by kmuehlbauer** [comment]
@ThomJea No worries, take your time. There is time left, until vispy 0.5 will be released.

**Comment by davidh-ssec** [comment]
@ThomJea Have you had a chance to look at this at all? No problem if not, but wanted to know if you've made any progress.
