### ISSUE TITLE
Vispy can't see OpenGL version on Windows

### ISSUE THREAD

**Issue by crubalcaba** [vispy/vispy#1342]
I have a proyect using Vispy + PyQt5. It work perfectly on OS X and Linux, but, on windows i'm getting an error on the call to _gl_initialize made by vispy.
The error is:
```
QWindowsWindow::setGeometry: Unable to set geometry 1440x785+8+31 on QWidgetWindow/'MainWindowWindow'. Resulting geometry: 1440x749+8+31 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 127x45, maximum size: 16777215x16777215).
WARNING: Error drawing visual <vispy.visuals.mesh.MeshVisual object at 0x000001F3041F7E80>
WARNING: Traceback (most recent call last):
File "E:\Ivan\Cibernetica\Duetto\@PROYECTOS@\SoundLab\app\ui\widgets\main_windows.py", line 24, in open_action_handler
self.open_file(filename)
File "E:\Ivan\Cibernetica\Duetto\@PROYECTOS@\SoundLab\app\ui\widgets\main_windows.py", line 29, in open_file
self.known_formats[ext](filename)
File "E:\Ivan\Cibernetica\Duetto\@PROYECTOS@\SoundLab\app\ui\widgets\main_windows.py", line 34, in open_signal
self.open(signal, name)
File "E:\Ivan\Cibernetica\Duetto\@PROYECTOS@\SoundLab\app\ui\widgets\main_windows.py", line 37, in open
s = SignalWidget(signal)
File "E:\Ivan\Cibernetica\Duetto\@PROYECTOS@\SoundLab\app\ui\widgets\signal.py", line 18, in __init__
super().__init__(handler=self.handler, *args, *kwargs)
File "E:\Ivan\Cibernetica\Duetto\@PROYECTOS@\SoundLab\duetto\widgets\SignalWidget.py", line 90, in __init__
self.canvas.render()
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\scene\canvas.py", line 244, in render
self._draw_scene(bgcolor=bgcolor)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\scene\canvas.py", line 253, in _draw_scene
self.draw_visual(self.scene)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\scene\canvas.py", line 291, in draw_visual
node.draw()
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\scene\visuals.py", line 98, in draw
self._visual_superclass.draw(self)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\visuals\visual.py", line 588, in draw
v.draw()
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\visuals\mesh.py", line 387, in draw
Visual.draw(self, *args, *kwds)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\visuals\visual.py", line 440, in draw
self._vshare.index_buffer)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\visuals\shaders\program.py", line 77, in draw
Program.draw(self, *args, *kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\gloo\program.py", line 470, in draw
canvas.context.flush_commands()
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\gloo\context.py", line 170, in flush_commands
self.shared.parser.parse([('CURRENT', 0)])
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\gloo\glir.py", line 458, in parse
self._parse(command)
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\gloo\glir.py", line 385, in _parse
self._gl_initialize()
File "C:\ProgramData\Anaconda3\lib\site-packages\vispy-0.5.0.dev0-py3.6.egg\vispy\gloo\glir.py", line 483, in _gl_initialize
if this_version < '2.1':
File "C:\ProgramData\Anaconda3\lib\distutils\version.py", line 52, in __lt__
c = self._cmp(other)
File "C:\ProgramData\Anaconda3\lib\distutils\version.py", line 335, in _cmp
if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'

```

I'm pretty sure that the reason is that vispy cannot find the current version of OpenGL installed on the machine. This is the output of sys_info():

```
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import vispy
>>> import pprint
>>> pprint.pprint(vispy.sys_info())
('Platform: Windows-10-10.0.15063-SP0\n'
'Python:   3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) '
'[MSC v.1900 64 bit (AMD64)]\n'
'Backend:  PyQt5\n'
'pyqt4:    None\n'
"pyqt5:    ('PyQt5', '5.6', '5.6.2')\n"
'pyside:   None\n'
'pyglet:   None\n'
'glfw:     None\n'
'sdl2:     None\n'
'wx:       None\n'
'egl:      None\n'
'osmesa:   None\n'
'_test:    None\n'
'\n'
"GL version:  ''\n"
'MAX_TEXTURE_SIZE: ()\n'
"Extensions: ''\n")
```

The version of PyOpenGL is 3.1.0 and the OpenGL in the system si also 3.1.0. 
Windows 10 
![capture](https://user-images.githubusercontent.com/15991242/28041799-c1e49d70-6598-11e7-9f87-1f7f3e73553a.PNG)

BTW in another computer with the same python and the same packages installed works fine.

**Comment by davidh-ssec** [comment]
Could you try the following in python or ipython REPL:

```
from vispy.app import use_app, Canvas
from vispy.gloo import gl
app = use_app()
canvas = Canvas('Test', (10, 10), show=False, app=app)
canvas._backend._vispy_set_current()
gl.glGetParameter(gl.GL_VERSION)
```

Please tell us any warning messages produced by `use_app()` and the result of the final command. Is it an empty string or None or other? This is basically repeating what sys info does, but I just want to be sure.

**Comment by davidh-ssec** [comment]
It seems your system's OpenGL installation (video driver?) is a little messed up. As shown by sys info your gl implementation isn't reporting anything back for max texture size, version, or extensions. Could you try updating your video drivers and try again?

Since you are using Anaconda could you also try an installation with PyQt4 and Python 3.6 and see if that gives you the same error?

**Comment by stark9337** [comment]
Using use_app alone didn't work (it tries to use PyQt4 and I don't have it). Using use_app('PyQt5') works fine and returns a `<Vispy app, wrapping the PyQt5 GUI toolkit>`. 
The final command returns an empty string, not None. Let me try to reproduce on PyQt4.
![capture 2](https://user-images.githubusercontent.com/15991242/28042687-5b3e4e5a-659c-11e7-8ef9-bd55e4424b0d.PNG)
 Updating my drivers might be a problem, I have a very limited internet connection.

**Comment by stark9337** [comment]
I can't try PyQt4. Aparently `conda` fails and there is no PyQt4 on pip.

**Comment by davidh-ssec** [comment]
Although you may have gotten warnings when using `use_app()` about PyQt4 it still should have given you a PyQt5 app. What kind of errors are you getting with install PyQt4 with conda? You could try adding the `conda-forge` channel and trying again (https://conda-forge.org/). I tend to have better luck using their packages. After looking at more of the code I don't know if it matters which backend is used. What do you get with:

```
from vispy.gloo.gl.gl2 import _lib
print(_lib)
```

Video drivers and therefore the OpenGL implementation are the only other thing I can think of. I'm not the one who implemented the low level library loading stuff for vispy so I may need to check with some of the other maintainers.

**Comment by kmuehlbauer** [comment]
@stark9337 @davidh-ssec There are reported issues with some Intel HD GPU involing OpenGL. I didn't follow up that much, so this is merely a suggestion to check if that might be the source.

**Comment by kmuehlbauer** [comment]
@stark9337 According to the stack trace you are working in the conda root environment and with the `defaults` channel. That is the cause of not getting PyQt4 installed (no python 3.6 version of pyqt4 available). Either you need to use python 3.5 with `defaults` or use `conda-forge` channel.

You might thus create a dedicated PyQt4 enviroment and use conda-forge channel:

- open anaconda console
- `conda create -n pyqt4_env python=3.6`
- `activate pyqt4_env`
-` conda install -c conda-forge pyqt=4*`

Then install other needed packages as usual.

Note: It is generally recommended to not use the anaconda root environment but dedicated conda environments. There you can install (mostly the packages are just symlinked) the needed packages for your specific task and keep a clean and reproducible environment regarding package versions and stuff. It also helps much for debugging problems of all sorts.

**Comment by kmuehlbauer** [comment]
@stark9337 Did you get along with this? If you need any further help, please let us know.

**Comment by kmuehlbauer** [comment]
@stark9337 Is this still an issue for you?

We have VisPy v0.5.1 out as conda-forge packages also for Windows. You might try this.

**Comment by stark9337** [comment]
I'll.

**Comment by chouran** [comment]
I have installed vispy with both conda and the developer mode (separated) and I'm still having the same issue with windows 7 64 bits, OpenGL 3.1 (working properly according to the tests) and PyQt5 as backend. In addition I can't run any of the examples.

When I try to run the examples a recurring error is that no OpenGL context is available. On the PyOpenGL [website](http://pyopengl.sourceforge.net/documentation/installation.html) is said that OpenGLContext is not include with PyOpenGL. Does vispy correct that ? 

I have run the command
 `from vispy.app import use_app, Canvas
from vispy.gloo import gl
app = use_app()
canvas = Canvas('Test', (10, 10), show=False, app=app)
canvas._backend._vispy_set_current()
gl.glGetParameter(gl.GL_VERSION)` 
which raises no error. The final command just produces ' ', same as the vispy.sys_info() for the GL version.

**Comment by chouran** [comment]
I didn't know why but I could get the GL version with iPynb_webgl a few days ago with the normal conda install, and pyglet did work for the examples. However it does not solve the problem (but it might help) since I absolutely need to work with PyQt5 as backend to continue a project (pyside2 gave the same errors).  

Here was my output to the vispy.sys_info() : 

`Platform: Windows-7-6.1.7601-SP1
Python:   3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)]
NumPy:    1.18.1
Backend:  ipynb_webgl 
pyqt4:    None  
pyqt5:    ('PyQt5', '5.12.1', '5.12.2')
pyside:   None
pyside2:  None
pyglet:   pyglet 1.5.2
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '3.1.0 - Build 9.17.10.4229'
MAX_TEXTURE_SIZE: 8192
Extensions: 'GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_texture_edge_clamp GL_EXT_separate_specular_color GL_ARB_multitexture GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_ARB_fragment_program_shadow GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_color_buffer_float GL_ARB_half_float_pixel GL_ARB_texture_float GL_ARB_pixel_buffer_object GL_EXT_framebuffer_object GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_occlusion_query2 GL_EXT_draw_buffers2 GL_WIN_swap_hint GL_EXT_texture_sRGB GL_ARB_multisample GL_EXT_packed_float GL_EXT_texture_shared_exponent GL_ARB_texture_rg GL_ARB_texture_compression_rgtc GL_NV_conditional_render GL_EXT_texture_swizzle GL_ARB_sync GL_ARB_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_ARB_depth_buffer_float GL_EXT_transform_feedback GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_ARB_framebuffer_object GL_EXT_texture_array GL_EXT_texture_integer GL_ARB_map_buffer_range GL_EXT_texture_snorm GL_INTEL_performance_queries GL_ARB_copy_buffer GL_ARB_sampler_objects GL_NV_primitive_restart GL_ARB_seamless_cube_map GL_ARB_uniform_buffer_object GL_ARB_depth_clamp GL_ARB_vertex_array_bgra GL_ARB_shader_bit_encoding GL_ARB_draw_buffers_blend GL_ARB_texture_query_lod GL_ARB_explicit_attrib_location GL_ARB_draw_elements_base_vertex GL_ARB_instanced_arrays GL_ARB_fragment_coord_conventions GL_EXT_gpu_program_parameters GL_ARB_texture_buffer_object_rgb32 GL_ARB_compatibility GL_ARB_texture_rgb10_a2ui GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_timer_query GL_INTEL_map_texture GL_ARB_vertex_array_object GL_ARB_provoking_vertex '
App info-gathering error:
Traceback (most recent call last):
  File "C:\Users\CCAthree\Anaconda3\lib\site-packages\vispy\util\config.py", line 438, in sys_info
    canvas.close()
  File "C:\Users\CCAthree\Anaconda3\lib\site-packages\vispy\app\canvas.py", line 457, in close
    self._backend._vispy_close()
  File "C:\Users\CCAthree\Anaconda3\lib\site-packages\vispy\app\backends\_ipynb_webgl.py", line 203, in _vispy_close
    raise NotImplementedErr
 `

**Comment by djhoese** [comment]
@chouran Let's start over. If you create a conda environment like this, what do you get when doing the `sys_info` call:

```
conda create -c conda-forge -n vispy_test python=3.7 vispy pyqt
conda activate vispy_test
```

Then:

```
import vispy
print(vispy.sys_info())
```

(use three backticks on separate lines to paste blocks of code ```)

**Comment by chouran** [comment]
Here is my output 
`Python:   3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MS
C v.1916 64 bit (AMD64)]
NumPy:    1.18.1
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.12.3', '5.12.5')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''`

**Comment by chouran** [comment]
Here is my output : 
```
Python:   3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MS 
C v.1916 64 bit (AMD64)]
NumPy:    1.18.1
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.12.3', '5.12.5')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: '' `

**Comment by djhoese** [comment]
In my experience this usually comes down to the GPU (OpenGL) drivers not working properly. I'm not sure there is much VisPy can do itself. We (vispy) are trying to talk to the C-level OpenGL libraries (your drivers) and ask what the version of OpenGL is, the C library is returning an empty string.

To help track this down, do you know what GPU you have @chouran? Do you have a dedicated GPU (ex. Nvidia or AMD) or an integrated GPU in your CPU (usually Intel integrated graphics)? If both, do you know if you are able to switch between them? If you have both and you were able to get this to mostly work in a jupyter notebook then it is possible that your browser is allowed to use the dedicated graphics card, but running normally `python my_script.py` is defaulting to the integrated GPU. We've seen issues in the past with integrated GPUs so if you can find a way to use a dedicated GPU or try it on another machine that would be our best chance of getting something working.

**Comment by chouran** [comment]
I have an integrated intel HD graphics 3000 GPU. 
I have tried to run the [real time signals](example) with both PyQt5 and Pyglet as a backend. Pyglet works, however I get this error with PyQt5 :   
```
WARNING: Traceback (most recent call last):
  File "real_time.py", line 151, in <module>
    c = Canvas()
  File "real_time.py", line 107, in __init__
    keys='interactive')
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\canv
as.py", line 205, in __init__
    self.create_native()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\canv
as.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 345, in __init__
    self._vispy_set_visible(True)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 412, in _vispy_set_visible
    self.showNormal()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 818, in resizeGL
    physical_size=(w, h))
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 471, in _invoke_callback
    cb(event)
  File "real_time.py", line 128, in on_resize
    gloo.set_viewport(0, 0, *event.physical_size)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\wra
ppers.py", line 111, in set_viewport
    self.glir.command('FUNC', 'glViewport', int(x), int(y), int(w), int(h))
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\wra
ppers.py", line 585, in glir
    raise RuntimeError('Gloo requires a Canvas to run.\n' + msg)
RuntimeError: Gloo requires a Canvas to run.
If you want to use gloo without vispy.app, use a gloo.context.FakeCanvas.
ERROR: Invoking <bound method Canvas.on_resize of <Canvas (PyQt5) at 0x3658e08>>
 for ResizeEvent
WARNING: Traceback (most recent call last):
  File "real_time.py", line 151, in <module>
    c = Canvas()
  File "real_time.py", line 107, in __init__
    keys='interactive')
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\canv
as.py", line 205, in __init__
    self.create_native()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\canv
as.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 345, in __init__
    self._vispy_set_visible(True)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 412, in _vispy_set_visible
    self.showNormal()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 471, in _invoke_callback
    cb(event)
  File "real_time.py", line 149, in on_draw
    self.program.draw('line_strip')
AttributeError: 'Canvas' object has no attribute 'program'
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x3658e08>> f
or DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x3658e08>> r
epeat 2
WARNING: Traceback (most recent call last):
  File "real_time.py", line 152, in <module>
    app.run()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\_def
ault_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\appl
ication.py", line 152, in run
    return self._backend._vispy_run()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 279, in _vispy_run
    return app.exec_()
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 508, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\app\back
ends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gl\
_gl2.py", line 116, in glBlendFuncSeparate
    nativefunc = glBlendFuncSeparate._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gl\
gl2.py", line 72, in _get_gl_func
    func = getattr(_lib, name)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\ctypes\__init__.py", line 37
7, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\ctypes\__init__.py", line 38
2, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'glBlendFuncSeparate' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\util\eve
nt.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\con
text.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gli
r.py", line 572, in flush
    self._shared.flush(parser)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gli
r.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gli
r.py", line 819, in parse
    self._parse(command)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gli
r.py", line 750, in _parse
    getattr(gl, id_)(*args)
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gl\
_gl2.py", line 118, in glBlendFuncSeparate
    nativefunc = glBlendFuncSeparate._native = _get_gl_func("glBlendFuncSeparate
", None, (ctypes.c_uint, ctypes.c_uint, ctypes.c_uint, ctypes.c_uint,))
  File "C:\Users\CCAthree\anaconda3\envs\v_test\lib\site-packages\vispy\gloo\gl\
gl2.py", line 87, in _get_gl_func
    raise RuntimeError('Using %s with no OpenGL context.' % name)
RuntimeError: Using glBlendFuncSeparate with no OpenGL context.
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x3976ac
8>> for DrawEvent
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x3976ac
8>> repeat 2
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x3658e08>> r
epeat 4
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x3976ac
8>> repeat 4
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x3658e08>> r
epeat 8
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x3976ac
8>> repeat 8
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x3658e08>> r
epeat 16
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x3976ac
8>> repeat 16
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x3658e08>> r
epeat 32
ERROR: Invoking <bound method GLContext.flush_commands of <GLContext at 0x3976ac
8>> repeat 32

**Comment by djhoese** [comment]
I'm confused. I would have thought you'd get an error like the original poster (LooseVersion). It really seems like your OpenGL drivers just aren't working properly. If you can't run some of the simpler examples like `examples/basics/gloo/rotate_cube.py` then I'm not sure what else we can do. You can try reinstalling or updating your drivers, but I'm not sure what else to do. As far as I know the PyQt5 backend is doing everything correctly and works for a lot of other people.

**Comment by chouran** [comment]
I'm thinking about trying to install Linux with VM or dual boot. But if the core of the problem is the Intel drivers, it wouldn't change anything right ?

**Comment by djhoese** [comment]
Virtual Machines can have limited OpenGL support. I've even had virtual machines that were supposed to be able to handle OpenGL *not* be able to draw anything. A dual boot with Linux would have a better chance of showing something, however I would expect the Windows drivers to be the "best" version (since Intel is likely trying to support Windows the most). That said, it is worth a shot if you're comfortable doing it.

**Comment by monzelr** [comment]
I had similar problems and OpenGL shows me like above
`GL version:  ''`

OpenGL Extensions Viewer shows me:
![opengl_version_1_1](https://user-images.githubusercontent.com/60315601/128645720-ea223efd-8e78-4804-8b21-3d7f669e0d33.png)


However, installing the latest intel graphics driver ([https://www.intel.com/content/www/us/en/download-center/home.html](https://www.intel.com/content/www/us/en/download-center/home.html) fixed my problem. The driver also shows now the latest version:

![image](https://user-images.githubusercontent.com/60315601/128645815-7379f98a-364d-4883-91e8-05c0fcd7c7af.png)

**Comment by djhoese** [comment]
I'm not sure I remember the entire history of this thread, but I think the main point is still consistent: VisPy's OpenGL version that it reports is based on the GPU/OpenGL drivers it is able to discover. If it isn't reporting a version number then:

1. You don't have OpenGL compatible drivers installed.
2. You don't have up-to-date ones installed.
3. VisPy can't find them because they are in a non-default location.
4. Your system doesn't actually support OpenGL (certain virtual machine setups, remote servers - ssh, etc)
5. Your drivers or system are buggy or not telling VisPy what it needs to know.

Anyone with these issues in the future, please create a new issue. Thanks.
