### ISSUE TITLE
GIMP as VisPy context

### ISSUE THREAD

**Issue by mrrm92** [vispy/vispy#1348]
Hello everyone.
I wonder if it's possible to use a GIMP drawing as the context to open VisPy, how if so, and if not, if this will be implemented and when.
Excuse me for asking here, but this may be the only question I have about VisPy and creating an account for just 5 usage minutes is not an option for me.

**Comment by davidh-ssec** [comment]
Could you provide a little more information on what you want to do? You want to view a GIMP drawing in VisPy? What is the input format you want to open in VisPy? What is your end goal?

You mean a github account?

**Comment by mrrm92** [comment]
I'd like to use GIMP as context for VisPy, but I discovered isn't possible.
No, I mean a Gitter chat one.

**Comment by davidh-ssec** [comment]
Maybe I just haven't used GIMP for a long time, but I wanted clarification on what "GIMP as context for VisPy". Repeating the same thing from your original question doesn't provide any additional information. You also asked if this could/would be added in the future. I'm curious what you wanted to accomplish. Did you want to open a XCF file in VisPy?
