### ISSUE TITLE
minor: border width bug in rectangleVisual

### ISSUE THREAD

**Issue by cstrub** [vispy/vispy#1349]
Hi,

the border width argument of the rectangle.py (visuals) is not passed to the polygon class.
The last lines of code in the file should be:

`if not self._border_color.is_blank:`
`   self.border.set_data(pos=vertices[1:, ..., :2],`
`   color=self._border_color.rgba,`
 **`width=self._border_width`**)

**Comment by davidh-ssec** [comment]
The border width is provided to the `PolygonVisual.__init__` class. It is not currently possible to change the border width after init so it shouldn't need to be passed from what I understand.

https://github.com/vispy/vispy/blob/master/vispy/visuals/rectangle.py#L62

Do you have some example code that doesn't work as you would expect?

**Comment by cstrub** [comment]
In this code the border width of the rectangles is ignored (at least in my setup vispy-0.5.0dev).
with the above change in the rectangle.py code, the border width can be set...

`

    import numpy as np
    from vispy import gloo
    from vispy import app
    from vispy.util.transforms import perspective, translate, rotate
    from vispy import color
    from vispy import visuals
    from vispy.visuals import TextVisual


    class Canvas(app.Canvas):

        def __init__(self):
            app.Canvas.__init__(self, title='ToF Point Cloud', keys='interactive', decorate=False, size=(1024, 800))
            self.mainVP = (0, 0, 1024, 800)
        
            self.textClose = visuals.TextVisual('Back', bold=False, color='white', font_size=18, pos=[50, self.mainVP[3] - 20])
            self.textClose.transforms.configure(canvas=self, viewport=self.mainVP)
            self.boxClose = visuals.RectangleVisual(center=[49, self.mainVP[3] -24], color=None, border_color=[33/255,57/255,91/255], border_width=2, height=50.0, width=100.0, radius=[0.0, 10.0, 0.0, 0.0])
            self.boxClose.transforms.configure(canvas=self, viewport=self.mainVP)

            self.textReset = visuals.TextVisual('Reset', bold=False, color='white', font_size=18, pos=[self.mainVP[2] -50, self.mainVP[3] / 3 +5])
            self.textReset.transforms.configure(canvas=self, viewport=self.mainVP)
            self.boxReset = visuals.RectangleVisual(center=[self.mainVP[2] -49, self.mainVP[3] / 3 -1 ], color=None, border_color=[33/255,57/255,91/255], border_width=8, height=50.0, width=100.0, radius=[10.0, 00.0, 00.0, 10.0])
            self.boxReset.transforms.configure(canvas=self, viewport=self.mainVP)
    
            self.show()

        def on_timer(self, event):        
                self.update()

        def on_resize(self, event):
            self.apply_zoom()

        def on_mouse_press(self, event):
            self.mousePress = event.pos
            clickRatio = self.mousePress / self.size
            if clickRatio[0] < 0.125 and clickRatio[1] > 0.9:
                print("close button")
            elif clickRatio[0] > 0.875 and clickRatio[1] > 0.28 and clickRatio[1] < 0.38:
                print("reset button")

        def on_draw(self, event):
            gloo.clear(color=True, depth=True,  stencil=True)      
            gloo.set_viewport(*self.mainVP)
            self.boxClose.draw()
            self.boxReset.draw()
            self.textClose.draw()
            self.textReset.draw()


        def apply_zoom(self):
            gloo.set_viewport(0, 0, *self.physical_size)


    if __name__ == '__main__':
            c = Canvas()
    app.run()
`

**Comment by davidh-ssec** [comment]
@cstrub Looks good and makes sense. Looks like this was caused by some changes a long time ago when some non-related updates were made to the RectangleVisual. While I'm not super happy about how those changes were done, your change is the simplest solution. Would you mind making a pull request?

**Comment by davidh-ssec** [comment]
@Eric89GXL If they make a pull request and add a test for this, should they make a pull request for the `test-data` repository (https://github.com/vispy/test-data/tree/master/visuals)?

**Comment by Eric89GXL** [comment]
I think that's how it's supposed to work, yeah

**Comment by cstrub** [comment]
@davidh-ssec Could you replicate the problem and the "fix"?
In my setup the "fix" only works if I have pyopengl installed (3.1.1), rather than just pyqt (4.10.4).
Without pyopengl the border width is always ignored.
I am not deep enough into vispy to understand this effect... I would prefer if someone else could take a look at this and eventually make the changes in the repository(?)
