### ISSUE TITLE
New example: data acquisition system

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#135]
Imagine a Data Acquisition System receiving real-time multi-channel digital signals. There are two ways to display the incoming data:
- Scrolling: the window shows `[t-h:t]` where `t` is the current time, and `h` the size (duration) of the window. Old data is discarded, and new buffered data comes from the right side of the window.
- Rotating: the window is split in two parts. The left part (new data) shows `[t-a*t,t]`, the right part (old data) shows `[t-b*t,t-a*t]`. In other words, the screen is constantly refreshed following a rotating vertical line (current time) that goes from left to right.

It should be possible to toggle dynamically between the two.

Technically, this could be made efficient by considering a VBO containing only the data samples (not the time samples). This VBO is updated in real-time with `set_subdata` on a circularly changing sub-window. There is another VBO with integer indices for all vertices (static).

Besides, there are variables containing the current time, the window duration, and the current position (integer) within the window. The time samples should not be computed on the CPU and transferred to the GPU. Rather, they should be generated dynamically on the vertex shader using the vertex indices and the current time. This saves 2x memory transfer.

Suggested by @samuelgarcia.

**Comment by nippoo** [comment]
@rossant is still waiting on the wine ;)

**Comment by samuelgarcia** [comment]
I known. Nobody get the wine. Luke is in Lyon and have a chance to get the wine during the week.
