### ISSUE TITLE
Example doesn't work because LinePlotVisual accepts only 2 coordinates.

### ISSUE THREAD

**Issue by ritchie46** [vispy/vispy#1352]
I tried to create a plot following this example:

https://github.com/vispy/vispy/blob/master/examples/basics/visuals/line_plot3d.py

Traceback (most recent call last):
  File "C:/Users/vik/Dropbox/Code/Wintrack/pydia/core/rebar/viplot.py", line 93, in <module>
    parent=view.scene)
  File "C:\Anaconda3\lib\site-packages\vispy\scene\visuals.py", line 41, in __init__
    subclass.__init__(self, *args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\vispy\visuals\line_plot.py", line 70, in __init__
    edge_width=edge_width, connect=connect)
  File "C:\Anaconda3\lib\site-packages\vispy\visuals\line_plot.py", line 102, in set_data
    % pos.shape[1])
TypeError: Too many coordinates given (3; max is 2).

**Comment by davidh-ssec** [comment]
Did you install VisPy from PyPI (`pip install vispy`) or from github (`pip install git+git://github.com/vispy/vispy.git`)?

The example you linked to is meant to work with the latest development version. If you installed from PyPI you likely have version 0.4.0 which is not compatible with the latest version of the examples available on github. Until we can come out with a new version (0.5) you'll need to install from github.

**Comment by ritchie46** [comment]
Ah.. Clear.. I indeed installed from PyPI.

If it helps anybody. I got it running by replacing `plot3D  = scene.visuals.create_visual_node(visuals.LinePlotVisual)` with `plot3D = scene.visuals.create_visual_node(visuals.LineVisual)`
