### ISSUE TITLE
Translucent GL visuals with PyQt5

### ISSUE THREAD

**Issue by davidh-ssec** [vispy/vispy#1379]
See #1377. This may be fixed if #960 is merged and the new API is used for PyQt5.

Using this example code:
```
# pylint: disable=no-member
""" scatter using MarkersVisual """

import numpy as np
from vispy import app, visuals, scene

# build your visuals
Scatter3D = scene.visuals.create_visual_node(visuals.MarkersVisual)

# The real-things : plot using scene
# build canvas
canvas = scene.SceneCanvas(keys='interactive', show=True)

# Add a ViewBox to let the user zoom/rotate
view = canvas.central_widget.add_view()
view.camera = 'turntable'
view.camera.fov = 45
view.camera.distance = 500

# data
n = 500
pos = np.zeros((n, 3))
colors = np.ones((n, 4), dtype=np.float32)
radius, theta, dtheta = 1.0, 0.0, 5.5 / 180.0 * np.pi
for i in range(500):
    theta += dtheta
    x = 0.0 + radius * np.cos(theta)
    y = 0.0 + radius * np.sin(theta)
    z = 1.0 * radius
    r = 10.1 - i * 0.02
    radius -= 0.45
    pos[i] = x, y, z
    colors[i] = (i/500, 1.0-i/500, 0, 0.8)

# plot
p1 = Scatter3D(parent=view.scene)
p1.set_gl_state('translucent', blend=True, depth_test=True)
p1.set_data(pos, face_color=colors)
p1.symbol = visuals.marker_types[10]

# run
app.run()
```

At least on OSX the circles are partially transparent *through* the window. It is possible to see the windows of other applications underneath. This doesn't change even if the background is changed to white `canvas.central_widget.bgcolor = 'white'` (it's not just light colors that are see through).

**Comment by davidh-ssec** [comment]
The issue is actually related to the alpha value. Any non-1 alpha values are transparent through the window. It is more obvious in the above if you set the background to be partially transparent: `canvas.central_widget.bgcolor = (1, 1, 1, 0.5)`. However, if you take a screenshot of the window (using OSX's `Ctrl+Cmd+Shift+4`) it doesn't show the transparency through the window.

![image](https://user-images.githubusercontent.com/1828519/32173719-dd945af8-bd4d-11e7-9ee2-dd920b9c7f08.png)

**Comment by davidh-ssec** [comment]
Taking a screenshot of the whole display shows the problem:

<img width="1440" alt="screen shot 2017-10-30 at 8 40 48 am" src="https://user-images.githubusercontent.com/1828519/32173874-4706ea50-bd4e-11e7-92cb-66bc07f9a440.png">

**Comment by davidh-ssec** [comment]
I tried a few combinations of those options with some of the existing ones in the `_qt.py` and wasn't able to get it to work. Someone with a non-OSX will need to test this to see if it is just OSX.

**Comment by larsoner** [comment]
I see it on Linux as well, e.g. with `conda` env:
```
pyqt                      5.6.0            py36h0386399_5  
qt                        5.6.2               h974d657_12  
```

**Comment by larsoner** [comment]
@davidh-ssec I'll close as dup :)
