### ISSUE TITLE
Wrong install location for docs

### ISSUE THREAD

**Issue by ghisvail** [vispy/vispy#1382]
From `setup.py`:
```
setup(
   [...]
    package_data={
        'vispy': [op.join('io', '_data', '*'),
                  op.join('html', 'static', 'js', '*'),
                  op.join('app', 'tests', 'qt-designer.ui'),
                  op.join('..', 'doc', '*'),
                  ],
```
This line `op.join('..', 'doc', '*')` is wrong for a system-wide install. It leads to the documentation being install under `dist-packages` or `site-packages`, which is definitely non-standard. IMO, the best would be to just not install the docs yourself, and let the package build system (conda or Debian) handle it.

**Comment by davidh-ssec** [comment]
Hm I thought I had tested this before committing it and that it was going in the vispy directory. I had added that line to include the `doc` directory in the PyPI tarball for your Debian packaging. What would be the proper way to add the `doc` directory to `setup.py` for your packaging?

**Comment by davidh-ssec** [comment]
As far as I can tell there is no proper way to add a directory *outside* the package directory to be inside the package directory. I would have to move the `doc` submodule (or symlink it) to inside the package. @ghisvail my understanding was that you needed the `doc` directory in PyPI, is that correct?
