### ISSUE TITLE
Update gloo canvas with external information

### ISSUE THREAD

**Issue by pablogarciaaunon** [vispy/vispy#1384]
Hi
First, I have to say that this is my first attempt to use Vispy.
Basically I want to run a simulation that generates the position of point, and visualize it using Vispy. Let's say that the simulation runs in a main function, calculates at each iteration the new position _X_, and I would like to pass it to a class _Visualize2DMovV1Class_ in order to update the visualization.

This would be my simplified main:

```
from VisualizationClasses import Visualize2DMovV1Class
import numpy as np
from vispy import app
import time

t = 0
t_max = 100
d_t = 0.1

X = np.array([0.0, 0.0, 0.0])
V = np.array([0.0, 0.0, 0.0])
V[0] = 1

visualization = Visualize2DMovV1Class(X)
app.run()

while t < t_max:

    X += V*d_t
    visualization.update_visualization(X)

    t += d_t

    print(X)

    time.sleep(d_t)
```
And this is my attempt of the visualization class:

```
from vispy import gloo
from vispy import app
import numpy as np

class Visualize2DMovV1Class(app.Canvas):
    def __init__(self, X):

        VERT_SHADER = """
        #version 120
        attribute vec3 position;
        attribute vec4 color;
        attribute float size;

        varying vec4 v_color;
        void main (void) {
            gl_Position = vec4(position, 1.0);
            v_color = color;
            gl_PointSize = size;
        }
        """

        FRAG_SHADER = """
        #version 120
        varying vec4 v_color;
        void main()
        {
            float x = 2.0*gl_PointCoord.x - 1.0;
            float y = 2.0*gl_PointCoord.y - 1.0;
            float a = 1.0 - (x*x + y*y);
            gl_FragColor = vec4(v_color.rgb, a*v_color.a);
        }

        """

        app.Canvas.__init__(self, keys='interactive')

        ps = self.pixel_scale

        self.agent = np.zeros(1, [('position', 'f4', 3),
                                  ('color', 'f4', 4),
                                  ('size', 'f4', 1 * ps)])

        self.agent['position'] = np.float32(X)
        self.agent['size'] = 10 * ps
        self.agent['color'] = 1, 1, 1, 1

        width, height = self.physical_size
        gloo.set_viewport(0, 0, width, height)

        # Create program
        self.program = gloo.Program(VERT_SHADER, FRAG_SHADER)

        # Create vertex buffers
        self.vbo_position = gloo.VertexBuffer(self.agent['position']
                                              .copy())
        self.vbo_color = gloo.VertexBuffer(self.agent['color'].copy())
        self.vbo_size = gloo.VertexBuffer(self.agent['size'].copy())

        # Bind vertex buffers
        self.program['color'] = self.vbo_color
        self.program['size'] = self.vbo_size
        self.program['position'] = self.vbo_position

        gloo.set_state(clear_color=(0, 0, 0, 1), blend=True,
                       blend_func=('src_alpha', 'one'))

        self.show()

    def update_visualization(self, X):
        self.agent['position'] = np.float32(X)

    def on_draw(self, event):
        gloo.clear()
        # Draw
        self.program.draw('points')
```
which is based on the boids example. After _app.run()_ the code in not executed.

Any idea about how I could make it work?
I know I could insert the code inside on_draw, but the simulation is quite complex and I would like to have the code separated like this.

Thanks!

**Comment by davidh-ssec** [comment]
Your code is not executed because `app.run()` starts the execution of the GUI Event Loop. Normally this function call does not return until the GUI window has been closed. The normal way of doing something like this is to create a timer and that runs every X seconds and runs a callback function. This callback function would be where you put the processing/updating code (or call that code).

**Comment by pablogarciaaunon** [comment]
Thanks! There is something missing: every second it does call the function but it does not represent the position. Did you mean this?:

```
t = 0
t_max = 100
d_t = 0.1

X = np.array([0.0, 0.0, 0.0])
V = np.array([0.0, 0.0, 0.0])
V[0] = 1

visualization = Visualize2DMovV1Class(X)
app.Timer(1, connect=visualization.update_visualization(X), start=True)

while t < t_max:

    X += V*d_t
    visualization.update_visualization(X)

    t += d_t

    print(X)

    time.sleep(d_t)
```

And the visualization:

```
class Visualize2DMovV1Class(app.Canvas):
    def __init__(self, X):
        ....
        ....
    def update_visualization(self, X):
        self.agent['position'] = np.float32(X)
        gloo.clear()
        self.program.draw('points')
```

So I have added the Timer in the main and changed _update_visualization_ to get the position _X_ and represent it.

**Comment by davidh-ssec** [comment]
Not exactly. Right now you are passing the value of the the `update_visualization` method **NOT** the method itself. You'll want to do something like:

```
app.Timer(d_t, connect=do_update, start=True)
```

With something like the following function:

```
def do_update():
    if t >= t_max:
        return
    X += V * d_t
    visualization.update_visualization(X)
    t += d_t
    print(X)
```

I'm not exactly sure what you are doing so I can't fill in specifics, but this code should run the `do_update` function every `d_t` seconds. You may want to change it to get the actual time since just because your timer says run every `T` seconds doesn't mean that it will run exactly at that interval. The timer event is put in a queue with all the other GUI events so it is called when ever the GUI gets to it.

Now the important part is that this code probably won't work exactly how you want it or at all because I'm assigning to `t` inside the callback function, but `t` is an immutable integer so that inplace assignment probably doesn't affect the global variable. Your options are:

1. Don't use a global and pass the new `t` every time. You may be able to use `datetime.utcnow()` to get the current time instead of counting. You may also find `from functools import partial` to be helpful and using keyword arguments in your `do_update` function.

2. Put this time logic inside the Visualize2DMovV1Class or inside another class so you can modify the instance variables directly instead of needing to worry about global variables.

Lastly, note that in my `do_update` function (and in any of the code) I am not using a loop. Your timer callback *must* return as fast as possible or the GUI will stop responding. The GUI event loop needs to continue on to the next event so it can handle draw, mouse, and keyboard events among others. I hope this helps a little. This is one of those subjects that is difficult until you know how to do it so good luck.

**Comment by pablogarciaaunon** [comment]
Thanks David, but I am not even close to have it working =D
To be more clear, the main simulates flying robots, represented as points, traveling along a specific area, with a certain intelligence inside them. 

The main part of the program would go in the line where the new positions are calculated, and it is quite big. It calls the dynamics of the robots, updates their knowledge, they take decisions, store information for posteriors analysis, etc.

Basically I would like to simulate the position of the robots (in the example, is only one) as fast as possible, and every (lets say) 0.1 seconds, update their visualization, just to see what is going on approximately. The simulation actually would go faster, not in real time.

This is my next attempt. I do not understand why, the callback _do_update_ executes only once:

```
class SimulationClass:
    def __init__(self):
        self.t = 0
        self.t_max = 100
        self.d_t = 0.1

        self.X = np.array([0.0, 0.0, 0.0])
        self.V = np.array([0.0, 0.0, 0.0])
        self.V[0] = 1

        self.visualization = Visualize2DMovV1Class(self.X)

    def do_update(self):
        if self.t >= self.t_max:
            return
        
        # Here comes the simulation (toy example)
        # ...............................
        self.X += self.V * self.d_t
        print(self.X)
        # ...............................
        
        self.visualization.update_visualization(self.X)
        self.t += self.d_t


simulation = SimulationClass()
app.Timer(0.1, connect=simulation.do_update(), start=True)

while simulation.t < simulation.t_max:
    True 
```
I had to add the last part (_while simulation..._) because the program closes immediately. Thanks again.

**Comment by davidh-ssec** [comment]
You still need to have `app.run()` at the bottom and then you should be able to remove the `while` loop since `app.run()` should execute until the GUI closes.

**Comment by davidh-ssec** [comment]
You also probably need to keep a handle on the timer that is produced by `app.Timer` or python may garbage collect it...maybe.

**Comment by pablogarciaaunon** [comment]
It seems the Timer is not executing.. It executes the callback only once. I have made this change:

```
simulation = SimulationClass()
timer_handle = app.Timer(0.1, connect=simulation.do_update(), start=True)
app.run()
```

**Comment by davidh-ssec** [comment]
Sorry I missed this, remove the `()` after `connect=simulation.do_update`. You want to pass a handle to the function *NOT* actually call the function.

**Comment by pablogarciaaunon** [comment]
Yes, thank. Now it looks like the callback is executed (I see the printed values), but the screen is not updated! I have placed an additional point to have a reference point, and it does not move:
 
```
    def update_visualization(self, X):
        self.agent['position'][1] = np.float32(X)
        gloo.clear()
        self.program.draw('points')
```

The element 1 of the array is the one that moves, and the element 0 is static. But none moves. Any idea why?

**Comment by davidh-ssec** [comment]
Just a hunch but try `self.update()` before the draw call. You might also have some issues with setting the array in `self.agent` but it not actually updating the gloo buffer and pushing the new data. You may have luck looking at some of the vispy visuals to see how they handle stuff like updating position.

**Comment by davidh-ssec** [comment]
For example in `vispy/visuals/linear_region.py` you can see this code:

```

        if self._changed['pos']:
            self.pos_buf.set_data(self._pos)
            self._changed['pos'] = False

        if self._changed['color']:
            self.color_buf.set_data(self._color)
            self._program.vert['color'] = self.color_buf
            self._changed['color'] = False

        return True
```

So if you take out the parts about `_changed` and think about what you are using you should be able to figure it out.

**Comment by davidh-ssec** [comment]
@pablogarciaaunon Were you able to get this to work? I'm going to close this for now since we've gotten you passed the initial problem. If you need more help feel free to continue commenting here or ask questions on gitter: https://gitter.im/vispy/vispy
