### ISSUE TITLE
Wrong scale on X and Y axis LinePlot

### ISSUE THREAD

**Issue by CTT-Hamilton** [vispy/vispy#1385]
On lineplot initialisation the X and Y axis will often be incorrect by 1 (major) division. This can be fixed by scrolling which updates the axis numbers. This problem doesn't happen every time however.

Example:

`self.x = np.linspace(0, 1000, 1000)
self.y = np.linspace(0, 50000, 1000)`

will sometimes produce a line from -10k to 40k rather than 0 to 50k

`

        def initGraph(self):

        self.line = None
        self.fig = None
        self.fig = vp.Fig(size=(1200, 380), position=(-40, -50))
        self.fig.create_native()
        self.fig.native.setParent(self.ui.canvas)

        self.x = np.linspace(0, 1000, 1000)
        self.y = np.linspace(0, 50000, 1000)

        self.line = self.fig[0, 0].plot((self.x, self.y), width=1, color='blue', xlabel='',
                                        ylabel='', marker_size=-10)
        self.line._line.method = 'agg'

`

**Comment by davidh-ssec** [comment]
Currently looking in to this. Here is a complete test case:
```
import numpy as np
import vispy.plot as vp
from vispy import app
x = np.linspace(0, 1000, 1000)
y = np.linspace(0, 50000, 1000)
line = None
fig = None
fig = vp.Fig(size=(1200, 380), position=(-40, -50))
fig.create_native()
#fig.native.setParent(ui.canvas)

x = np.linspace(0, 1000, 1000)
y = np.linspace(0, 50000, 1000)

line = fig[0, 0].plot((x, y), width=1, color='blue', xlabel='',
                                ylabel='', marker_size=-10)
line._line.method = 'agg'
#fig[0, 0].xaxis._view_changed()

app.run()
```

The issue seems to be some kind of race condition on the transform changing. If you uncomment the commented line above you *should* consistently get the right ranges on load. I'm still looking for a long term fix.

**Comment by davidh-ssec** [comment]
@CTT-Hamilton Could you do a test for me and test the panning around the plot? When I do it on my machine the line continues to be drawn outside of the plot axes/box. Otherwise I think I've figured out a solution.
