### ISSUE TITLE
ENH: picking

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#140]
Vispy needs a system for picking that can provide:

* The top-most visual drawn at (x,y) on a canvas
* A depth-ordered list of all visuals drawn at (x,y)
* The same for larger / arbitrary areas such as all visuals drawn within a rectangular area or a lasso
* Which primitives (triangle / line / sprite) of a visual are in the picking area
* The location in the local coordinate system of an entity that corresponds to a canvas pixel

**Comment by campagnola** [comment]
Update: #822 allows us to attach filters to the beginning and end of a Visual's shaders. This will allow us to easily and transparently force any visual to render with a solid color, which brings us much closer to making picking possible.

**Comment by Eric89GXL** [comment]
Oh I hadn't even considered that use case... yes that is a nice benefit indeed.

**Comment by almarklein** [comment]
I was going to say that it would not be that simple, because you'd want to write simpler shaders for this case. But maybe by setting `gl_Color` to a color at the end will make the compiler optimize out all the complicated stuff that we do (casting rays, calculating aa). That would be sweet.

**Comment by rossant** [comment]
@almarklein it might depend on the driver, but I think at least some of them do it, because you sometimes get error messages about non-existing attributes and uniforms which have been optimized out.

**Comment by campagnola** [comment]
I think we generally don't want to skip the work that is done in the fragment shader because it may have discards or set the alpha=0, which should change the picking area. If it becomes a performance issue, then we will need to let each visual override the default behavior and define its own picking behavior.

**Comment by almarklein** [comment]
I don't think a compiler would optimize the discards out. Having it ignore `alpha=0` is probably ok; they will be e.g. the semi-transparent fragments for aa. If we want a visual to become non-pickable in transparent areas, we should discard  `if alpha==0`.
