### ISSUE TITLE
BUG: TextVisual SDF calculation on GPU is too slow

### ISSUE THREAD

**Issue by larsoner** [vispy/vispy#1408]
... perhaps we should just use bitmapped fonts (how it was originally implemented!).

Alternatively we could use Cython to compute the SDF (it was also this way at one point...).

@rougier which method did you end up going with for fonts in Glumpy?

**Comment by kmuehlbauer** [comment]
@larsoner Would it be possible to have this as options? So that the user can decide which implementation he want to use?

**Comment by larsoner** [comment]
It increases complexity, but if there are clear advantages to each, sure.

**Comment by kmuehlbauer** [comment]
Is the shader version of better quality?

**Comment by larsoner** [comment]
In principle the CPU and GPU should produce equivalent SDFs, but both can be a bit slow. (And the GPU one is slow enough that some people seem unable to use it e.g. with older Intel GPUs.)

The bitmap is the fastest and will also look good, but not scale as nicely.

**Comment by davidh-ssec** [comment]
There is also WebGL. The current SDF technique requires a lot of frame buffers and swapping which doesn't perform very well on the jupyter notebook backend (last I checked).

**Comment by kmuehlbauer** [comment]
@larsoner glumpy uses a small c extension https://github.com/vispy/vispy/issues/1312#issuecomment-306229733

**Comment by larsoner** [comment]
I had this to say [back in 2014](https://github.com/vispy/vispy/pull/317#issuecomment-49615068) about the 8SSEDT Cython algorithm:

> The SDF calculation in Python was much slower, even after I put in a decent amount of effort to try to vectorize / parallelize / speed it up with little success. In Cython on my machine it's about 10ms per character, requiring no caching at all. In Python, I was getting around 200 ms per character, and this was on my six-core 3.6 GHz Linux workstation (it was brutal on my Macbook Air laptop). You can see how this would become very slow for most users. Using lots of fonts and lots of characters would become untenable, even if we did cache. And all of these stats are when using an SDF calculation method that isn't as good as what Nico used, but was over an order of magnitude faster...

I managed to restore an old branch I had that had SDF (and bitmapped fonts, for that matter):

https://github.com/larsoner/vispy/blob/old-sdf/vispy/scene/visuals/text/_sdf.pyx

Now that I've fonud this, it wouldn't be too hard in principle to add back in the CPU SDF calculation. The big potential maintenance overhead will come from adding a Cython build step / dependency.

**Comment by davidh-ssec** [comment]
Regarding cython build step/dependency: I haven't had too much trouble with cython in my projects lately except for the occasional user who has an old version of setuptools which doesn't handle C++ cython extensions properly.

**Comment by larsoner** [comment]
@davidh-ssec I haven't set up Cython stuff in a long time. Do you have time to try using my Cython file as a drop-in replacement for the GPU computation code?

**Comment by davidh-ssec** [comment]
I don't have time this week or next, but January I can designate as a VisPy month and will take a look then. Just point me to the files and any special compilation flags. New vispy branch?

**Comment by larsoner** [comment]
I don't think we need a branch on `vispy`, just a standard PR. Are you worried that the Cython stuff will be too problematic from a packaging perspective?

I'll see if I have time to look before Jan.

**Comment by davidh-ssec** [comment]
I was just thinking a branch that we could both access. So if you could push python changes and I could handle the setup.py stuff if needed.

**Comment by larsoner** [comment]
The GitHub default "enable edits from contributors" will already allow you to do this if I open a PR

**Comment by rougier** [comment]
@larsoner Sorry late response. I've been using the method by @stegu, it is in https://github.com/glumpy/glumpy/tree/master/glumpy/ext/sdf
