### ISSUE TITLE
Insert images in canvas display

### ISSUE THREAD

**Issue by Super-Tree** [vispy/vispy#1413]
if I want to insert an image in the canvas,How can I make it? I have tried manys ways and the display isn't ideal.
I want to set the image in the bottomleft window and it doens't change view as the main canvas camera's varing .

`    pos = scans[:, :3]`
`    canvas = vispy.scene.SceneCanvas(title=name, keys='interactive', size=vis_size, show=True)`
 `   vb = canvas.central_widget.add_view()`
  `  vb.camera = 'turntable'`
 `   vb.camera.elevation = 19.0`
 `   vb.camera.center = (3.9, 3.0, 7.1)`
 `   vb.camera.azimuth = -90.0`
 `   vb.camera.scale_factor = 48`
 ` # inserting an mage in the sceneCanvas`
 ` #TODO :How can I make it`
   ` scatter = visuals.Markers()`
 `   scatter.set_gl_state('translucent', depth_test=False)`
  `  scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, 1), size=0.01, scaling=True)`
  `  vb.add(scatter)`
 ` vispy.app.run()`
![question](https://user-images.githubusercontent.com/24618712/35185071-0715c0ac-fe39-11e7-8c10-54a277acfb4a.png)

**Comment by Super-Tree** [comment]
by the way how can I save the view as an image ?

**Comment by davidh-ssec** [comment]
If I understand you correctly you should take a look at the `ImageVisual` class for displaying an image on the canvas. As for the camera not affecting that image you'll need to make sure the camera is not applied to the same node graph as the image visual. The camera will affect everything "underneath" it in tree of visual nodes. I'm not sure what the best way of doing this is. @kmuehlbauer @larsoner is there a recommended/suggested way to do this?

To save a canvas to an image you can use a combination of the `_screenshot` utility function (`from vispy.gloo.util import _screenshot`) and the pillow package. The screenshot function will give you a numpy array of the canvas as RGBA values. This function is a simple wrapper around `read_pixels` and it looks like `_screenshot` was only made private (prefixed with a `_`) because the original author wasn't sure where to put it. You can then use PIL by doing:

```
from PIL import Image
im = Image.fromarray(x)
im.save("my_filename.png")
```

If you'd like to make a utility function that does all this and submit it via a pull request it would be much appreciated.

**Comment by Super-Tree** [comment]
I have completed the first problem by using two cameras,but  i can't save the display by the _screenshot.Is there something wrong? The demo I use are as below
p.s. changing the filename '000000bin.png' to '000000.bin' when using the attached file

import numpy as np
import vispy
import cv2
from vispy.scene import visuals
import vispy.io as vispy_file
from vispy.gloo.util import _screenshot as screenshot


def pcd_vispy(scans=None,img=None, name=None,vis_size=(800, 600),save_img=False):
    canvas = vispy.scene.SceneCanvas(title=name, keys='interactive', size=vis_size, show=True)
    grid = canvas.central_widget.add_grid()
    vb = grid.add_view(row=0, col=0, row_span=2)
    vb_img = grid.add_view(row=1, col=0)

    pos = scans[:, :3]
    scatter = visuals.Markers()
    scatter.set_gl_state('translucent', depth_test=False)
    scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, 1), size=0.01, scaling=True)

    vb.camera = 'turntable'
    vb.camera.elevation = 19.0
    vb.camera.center = (3.9, 3.0, 7.1)
    vb.camera.azimuth = -90.0
    vb.camera.scale_factor = 48
    vb.add(scatter)

    photo = visuals.Image(data=img, method='auto')
    vb_img.camera = 'turntable'
    vb_img.camera.elevation =-90.0
    vb_img.camera.center = (2100, -380, -500)
    vb_img.camera.azimuth =0.0
    vb_img.camera.scale_factor = 1500
    vb_img.add(photo)

    if save_img:
        res = screenshot(alpha=False)
        vispy_file.write_png("screenshot.png",res)

    vispy.app.run()
    return canvas


if __name__ =='__main__':
    image =cv2.imread('000000.png')
    points = np.fromfile('000000.bin', dtype=np.float32).reshape(-1,4)[:,0:3]

    pcd_vispy(scans=points, img=image,save_img=True)

![000000](https://user-images.githubusercontent.com/24618712/35256233-ca93bc14-002d-11e8-980e-b3a441fd9640.png)
![000000bin](https://user-images.githubusercontent.com/24618712/35256274-02284398-002e-11e8-8ae8-8c5fe355568a.png)

**Comment by davidh-ssec** [comment]
The screenshot functionality has to read the data from the GPU buffer. If there hasn't been anything drawn to the buffer then there is nothing (useful) to save to an image. I'm guessing that since you are reading the buffer before the application has started (and therefore before anything has been drawn) you are getting a black image back. You'll have to make sure the application draws first then read the buffer. I'm not sure we have any examples that do something like this, but we do something similar when generating example imagery automatically: https://github.com/vispy/vispy/blob/master/make/make.py#L262

@larsoner may have some ideas since I believe he wrote this original functionality.

**Comment by Super-Tree** [comment]
vispy.scene.SceneCanvas.render() can generate a current canvas image and it solved the problem.

**Comment by davidh-ssec** [comment]
@Super-Tree Do you mean you used `render` and then `_screenshot`? How does this change the above code (for reference)?

**Comment by Super-Tree** [comment]
Try this demo


import numpy as np
import vispy
import cv2
from vispy.scene import visuals
import vispy.io as vispy_file


def pcd_vispy(pos=None, img=None, name=None, vis_size=(800, 600), save_img=False, visible=True):
    canvas = vispy.scene.SceneCanvas(title=name, keys='interactive', size=vis_size, show=visible)
    grid = canvas.central_widget.add_grid()
    vb = grid.add_view(row=0, col=0, row_span=2)
    vb_img = grid.add_view(row=1, col=0)

    scatter = visuals.Markers()
    scatter.set_gl_state('translucent', depth_test=False)
    scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, 1), size=0.1, scaling=True)

    vb.camera = 'turntable'
    vb.camera.elevation = 21.0
    vb.camera.center = (6.5, -0.5, 9.0)
    vb.camera.azimuth = -75.5
    vb.camera.scale_factor = 32.7
    vb.add(scatter)

    if img is None:
        img=np.zeros(shape=[1,1,3],dtype=np.float32)
    image = visuals.Image(data=img, method='auto')
    vb_img.camera = 'turntable'
    vb_img.camera.elevation = -90.0
    vb_img.camera.center = (2100, -380, -500)
    vb_img.camera.azimuth = 0.0
    vb_img.camera.scale_factor = 1500
    vb_img.add(image)

    if save_img:
        res = canvas.render(bgcolor='black')[:, :, 0:3]
        vispy_file.write_png('test.png', res)

    @canvas.connect
    def on_key_press(ev):
        if ev.key.name in '+=':
            a = vb.camera.get_state()
        print(a)

    if visible:
        pass
        vispy.app.run()

    return canvas


if __name__ == '__main__':
    photo = cv2.imread('000000.png')
    points = np.random.randn(200, 3) * 10
    pcd_vispy(pos=points, img=photo, save_img=True, visible=True)

**Comment by Super-Tree** [comment]
@davidh-ssec

**Comment by Super-Tree** [comment]
Try this demo @davidh-ssec 

import numpy as np
import vispy
import cv2
from vispy.scene import visuals
import vispy.io as vispy_file

def pcd_vispy(pos=None, img=None, name=None, vis_size=(800, 600), save_img=False, visible=True):
canvas = vispy.scene.SceneCanvas(title=name, keys='interactive', size=vis_size, show=visible)
grid = canvas.central_widget.add_grid()
vb = grid.add_view(row=0, col=0, row_span=2)
vb_img = grid.add_view(row=1, col=0)

scatter = visuals.Markers()
scatter.set_gl_state('translucent', depth_test=False)
scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, 1), size=0.1, scaling=True)

vb.camera = 'turntable'
vb.camera.elevation = 21.0
vb.camera.center = (6.5, -0.5, 9.0)
vb.camera.azimuth = -75.5
vb.camera.scale_factor = 32.7
vb.add(scatter)

if img is None:
    img=np.zeros(shape=[1,1,3],dtype=np.float32)
image = visuals.Image(data=img, method='auto')
vb_img.camera = 'turntable'
vb_img.camera.elevation = -90.0
vb_img.camera.center = (2100, -380, -500)
vb_img.camera.azimuth = 0.0
vb_img.camera.scale_factor = 1500
vb_img.add(image)

if save_img:
    res = canvas.render(bgcolor='black')[:, :, 0:3]
    vispy_file.write_png('test.png', res)

@canvas.connect
def on_key_press(ev):
    if ev.key.name in '+=':
        a = vb.camera.get_state()
    print(a)

if visible:
    pass
    vispy.app.run()

return canvas
if name == 'main':
photo = cv2.imread('000000.png')
points = np.random.randn(200, 3) * 10
pcd_vispy(pos=points, img=photo, save_img=True, visible=True)

**Comment by davidh-ssec** [comment]
I changed a few things and got it to work based on a key press. I think the main question is when do you want a screenshot taken? If you want it whenever a key is pressed or a user uses a dialog in the UI to click "Save..." then that should not be a problem for the `_screenshot` function as the canvas is already rendered. If you want to save an image of the initial frame then you have to make sure you wait for the entire scene to be rendered. Your solution is forcing a render to an offscreen buffer which I think is fine, especially for the initial frame. However, it does result in redrawing everything. Using `_screenshot` would read the existing buffer as it is and return that array. Here is my code which can take a screenshot on 's' or every time the canvas is drawn (not smart for performance):

```
import numpy as np
import vispy
import cv2
from vispy.scene import visuals
import vispy.io as vispy_file
from vispy.gloo.util import _screenshot

def pcd_vispy(pos=None, img=None, name=None, vis_size=(800, 600), save_img=False, visible=True):
    canvas = vispy.scene.SceneCanvas(title=name, keys='interactive', size=vis_size, show=visible)
    grid = canvas.central_widget.add_grid()
    vb = grid.add_view(row=0, col=0, row_span=2)
    vb_img = grid.add_view(row=1, col=0)

    scatter = visuals.Markers()
    scatter.set_gl_state('translucent', depth_test=False)
    scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, 1), size=0.1, scaling=True)

    vb.camera = 'turntable'
    vb.camera.elevation = 21.0
    vb.camera.center = (6.5, -0.5, 9.0)
    vb.camera.azimuth = -75.5
    vb.camera.scale_factor = 32.7
    vb.add(scatter)

    if img is None:
        img = np.zeros(shape=[1,1,3], dtype=np.float32)
    image = visuals.Image(data=img, method='auto')
    vb_img.camera = 'turntable'
    vb_img.camera.elevation = -90.0
    vb_img.camera.center = (2100, -380, -500)
    vb_img.camera.azimuth = 0.0
    vb_img.camera.scale_factor = 1500
    vb_img.add(image)

    @canvas.connect
    def on_key_press(ev):
        print(ev.key.name)
        if ev.key.name in '+=':
            a = vb.camera.get_state()
            print(a)
        elif ev.key.name in 'S':
            print("Saving...")
            res = _screenshot()
            vispy_file.write_png('test.png', res)
    @canvas.connect
    def on_draw(ev):
        res = _screenshot()
        vispy_file.write_png('test.png', res)

    return canvas

if __name__ == '__main__':
    #photo = cv2.imread('000000.bin')
    #points = np.random.randn(200, 3) * 10
    photo = cv2.imread('000000.png')
    points = np.fromfile('0000002.bin', dtype=np.float32).reshape(-1,4)[:,0:3]
    c1 = pcd_vispy(pos=points, img=photo, save_img=True, visible=True)
    vispy.app.run()
```
