### ISSUE TITLE
Nvidia switchable graphics + Linux

### ISSUE THREAD

**Issue by hmaarrfk** [vispy/vispy#1416]
Hi,

I wanted to open a thread to help those using Nvidia switchable graphics.

I have a machine running 
- Intel 7700HQ
- Nvidia GTX 1050
- Fedora 27
- bumblebee
- Gnome 3.26.2
- Wayland
- 4k screen (this causes more problems than it is worth)

You can check which graphics card is being used by looking at the output of 
```
import vispy
print(vispy.sys_info())
```

When running with `primusrun python` I get a line
```
GL version:  '4.6.0 NVIDIA 390.25'
```
near the top and when running simply `python` I get:
```
GL version:  '3.0 Mesa 17.2.4'
```

Things are a little different between conda and Fedora's version of Qt. So I'll have to document them seperately:

## Conda
Things seem ok with PyQt5.6.2-7.
You can use the graphics card with
```
primusrun python examples/basic/scene/magnify.py
```
You will get 
```
WARNING: Unrecognized OpenGL version
WARNING: Unrecognized OpenGL version
```
but it seems benign

Optirun doesn't work for me with the following error:
```
optirun python examples/basics/scene/magnify.py 
WARNING: This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
```

## System python + virtualenv
If you are using virtualenv (or what seems to be the successor, pipenv), then you need to be careful with the provided versions of PyQt5 from PyPi. Using the prebuilt wheels gave a segfault for me when running a super simple script
```python
import vispy
vispy.sys_info()
```
PyQt5 from PyPi doens't even let you run vispy with your Intel graphics.

I had to [compile PyQt5](http://pyqt.sourceforge.net/Docs/PyQt5/installation.html) from scratch.
It took maybe 30-50 minutes on my laptop, and then everything seems to work.

The best part, is that it doesn't have the warning about the unrecognised OpenGL version.

Once you have compiled and install PyQt5 yourself, you can use 
```
primusrun python examples/basics/scene/grid.py
```
to test that things work.

`optirun` tries to display something, but it looks very strange. It seems that `primusrun` has succeeded `optirun` in anycase.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
I think this can be closed now as most if not all of this has been mentioned in the installation instructions now: https://vispy.org/installation.html#switchable-graphics
