### ISSUE TITLE
Nvidia switchable graphics + Windows

### ISSUE THREAD

**Issue by hmaarrfk** [vispy/vispy#1418]
If you have a laptop with NVidia switchable graphics, the default settings for an application should be to use the integrated graphics.

The NVidia tray icon should be able to tell what applications are using the graphics card.

![image](https://user-images.githubusercontent.com/90008/35782808-afbf9faa-09b2-11e8-97ea-59003e4dcc07.png)

With no modifications, your GPU will be unused, that is no fun!

The instructions assume you have conda installed with `spyder` and `pyqt` as well as `vispy`.

To get your GPU working, you should 
1. Open the Nvidia-control-panel
2. Manage 3D settings
3. Program Settings
4. Click "Add"
5. If you had opened `spyder` recently, then it should be at the top of the list.
6. Check that it is the correct python for your conda environment.
7. Select "High performance NVidia Graphics"
8. Press apply.

Now when you run your program again and the tray icon should tell you that your GPU is being used.

![image](https://user-images.githubusercontent.com/90008/35782833-4a9a7d2e-09b3-11e8-9cf6-7ba1c7af10ec.png)

**Comment by djhoese** [comment]
@hmaarrfk I think you've added the relevant documentation to the sphinx docs (installation sections). Can this be closed? Same for #1417?
