### ISSUE TITLE
Load STL files into vispy

### ISSUE THREAD

**Issue by JPFrancoia** [vispy/vispy#1425]
Hello,

I just discovered vispy, it seems to be the perfect tool for what I want to do. I would like to create a STL viewer that I can embed in a PyQt5 application.

So I started with the example I found here:
https://github.com/vispy/vispy/blob/master/examples/basics/visuals/mesh.py

The mesh is created from the ```create_sphere``` function:

```
mdata = create_sphere(20, 40, 1.0)
```

I wanted to replace this line by a call to the ```read_mesh``` function, but sadly it doesn't support stl files.

So now I'm looking at the ```MeshData``` object:

```
MeshData(vertices=None, faces=None, edges=None, vertex_colors=None, face_colors=None, vertex_values=None)
```

To create a mesh, I need vertices, faces and edges. The rest is not really necessary (maybe vertex_values ?)

The numpy-stl module has a ```mesh.Mesh.from_file()``` function that can load STL files. This function returns a mesh object (doc here: http://pythonhosted.org/numpy-stl/stl.html#stl-mesh)

And this object has several attributes, like ```data```, ```normals```, ```vectors```, etc.

I believe there is everything to send that directly to ```MeshData``` in vispy.

However I'm clearly not an expert in geometry/CAD, so I could use your help to understand which is what. Basically, I'd like to know what attribute of a numpy-stl mesh object is the vertices in vispy, which one is faces, and which one is edges.

Could you give me a hand please ?

**Comment by JPFrancoia** [comment]
Ok so I think it's possible. I didn't bother to understand which is what, I just used trimesh which directly provides ```faces``` and ```vertices``` attributes. Here is my code:

```python
# -*- coding: utf-8 -*-
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.

"""
Simple demonstration of Mesh visual.
"""

import numpy as np
from vispy import app, gloo, visuals, geometry
from vispy.geometry import create_sphere
from vispy.visuals.transforms import (STTransform, MatrixTransform,
                                      ChainTransform)

import trimesh


class Canvas(app.Canvas):

    def __init__(self):
        app.Canvas.__init__(self, keys='interactive', size=(800, 550))

        self.meshes = []
        self.rotation = MatrixTransform()

        # Generate some data to work with
        # global mdata
        # mdata = create_sphere(20, 40, 1.0)
        mesh = trimesh.load('test.stl')
        mdata = geometry.MeshData(mesh.vertices, mesh.faces)

        # Mesh with pre-indexed vertices, uniform color
        # self.meshes.append(visuals.MeshVisual(meshdata=mdata, color='b'))
        self.meshes.append(visuals.MeshVisual(meshdata=mdata))

        # Mesh with pre-indexed vertices, per-face color
        # Because vertices are pre-indexed, we get a different color
        # every time a vertex is visited, resulting in sharp color
        # differences between edges.
        rng = np.random.RandomState(0)
        verts = mdata.get_vertices(indexed='faces')
        nf = verts.size//9
        fcolor = np.ones((nf, 3, 4), dtype=np.float32)
        fcolor[..., 0] = np.linspace(1, 0, nf)[:, np.newaxis]
        fcolor[..., 1] = rng.randn(nf, 1)
        fcolor[..., 2] = np.linspace(0, 1, nf)[:, np.newaxis]
        mesh = visuals.MeshVisual(vertices=verts, face_colors=fcolor)
        self.meshes.append(mesh)

        # Mesh with unindexed vertices, per-vertex color
        # Because vertices are unindexed, we get the same color
        # every time a vertex is visited, resulting in no color differences
        # between edges.
        verts = mdata.get_vertices()
        faces = mdata.get_faces()
        nv = verts.size//3
        vcolor = np.ones((nv, 4), dtype=np.float32)
        vcolor[:, 0] = np.linspace(1, 0, nv)
        vcolor[:, 1] = rng.randn(nv)
        vcolor[:, 2] = np.linspace(0, 1, nv)
        self.meshes.append(visuals.MeshVisual(verts, faces, vcolor))
        self.meshes.append(visuals.MeshVisual(verts, faces, vcolor,
                                              shading='flat'))
        self.meshes.append(visuals.MeshVisual(verts, faces, vcolor,
                                              shading='smooth'))

        # Mesh with color indexed into a colormap
        verts = mdata.get_vertices(None)
        faces = mdata.get_faces()
        values = rng.randn(len(verts))
        mesh = visuals.MeshVisual(vertices=verts, faces=faces,
                                  vertex_values=values, shading='smooth')
        mesh.clim = [-1, 1]
        mesh.cmap = 'viridis'
        mesh.shininess = 0.01
        self.meshes.append(mesh)

        # Lay out meshes in a grid
        grid = (3, 3)
        s = 300. / max(grid)
        for i, mesh in enumerate(self.meshes):
            x = 800. * (i % grid[0]) / grid[0] + 400. / grid[0] - 2
            y = 800. * (i // grid[1]) / grid[1] + 400. / grid[1] + 2
            transform = ChainTransform([STTransform(translate=(x, y),
                                                    scale=(s, s, s)),
                                        self.rotation])
            mesh.transform = transform
            mesh.transforms.scene_transform = STTransform(scale=(1, 1, 0.01))

        self.show()

        self.timer = app.Timer(connect=self.rotate)
        self.timer.start(0.016)


    def rotate(self, event):
        # rotate with an irrational amount over each axis so there is no
        # periodicity
        self.rotation.rotate(0.2 ** 0.5, (1, 0, 0))
        self.rotation.rotate(0.3 ** 0.5, (0, 1, 0))
        self.rotation.rotate(0.5 ** 0.5, (0, 0, 1))
        self.update()

    def on_resize(self, event):
        # Set canvas viewport and reconfigure visual transforms to match.
        vp = (0, 0, self.physical_size[0], self.physical_size[1])
        self.context.set_viewport(*vp)

        for mesh in self.meshes:
            mesh.transforms.configure(canvas=self, viewport=vp)

    def on_draw(self, ev):
        gloo.set_viewport(0, 0, *self.physical_size)
        gloo.clear(color='black', depth=True)

        for mesh in self.meshes:
            mesh.draw()


if __name__ == '__main__':
    win = Canvas()
    import sys
    if sys.flags.interactive != 1:
        app.run()
```

And here is a stl file I use for tests (just remove .txt at the end of the file to use it):

[test.stl.txt](https://github.com/vispy/vispy/files/1719681/test.stl.txt)


Now my problem is I think the mesh is too big to be displayed in a small window. Is there a way to implement mouse control in this Cancas ? I'd like to be able to unzoom.

**Comment by davidh-ssec** [comment]
Glad you got it working. I was going to look at this today. To get panning and zooming functionality you will want to use a `SceneCanvas` instead of a basic canvas and add a Camera. Then I think you can remove the other transforms you are assigning (I think). There are scene canvas examples in the examples directory. I don't know which ones will help most off the top of my head.

Would you be able to make a pull request and add the ability to read these files to the normal mesh reading functionality? Maybe check file extension and import scipy if needed?

**Comment by JPFrancoia** [comment]
Yes, I can make a PR. It shouldn't be too difficult to add this feature. Actually the code is already written here:
https://github.com/mikedh/trimesh/blob/master/trimesh/io/stl.py

You don't need the entire module trimesh. Using just the stl loading part would not add any dependency to your code.

I just would need to add a couple of lines here:
https://github.com/vispy/vispy/blob/master/vispy/io/mesh.py

The question is: can I take the code from the trimesh repo (license, credits, etc) ?

**Comment by davidh-ssec** [comment]
It is probably ok to copy it, but you would need to include a copyright and stuff in the top of the file. It might make more sense to require trimesh as a dependency depending on what the code looks like. You mentioned that scipy can read STL files but that the output wasn't as easy to use as trimesh. If you figured out how to convert that output to what vispy needs maybe that would be easier?

@larsoner may have more experience with this. Now that I look at the trimesh code, maybe that would be best.

**Comment by larsoner** [comment]
MIT license is compatible with BSD, so sounds good to me, can add it to `vispy/ext`

**Comment by JPFrancoia** [comment]
Well trimesh includes a lot of stuff, including viewer and all (so maybe depency to pyglet). I don't know exactly to what extent it would make your code heavier, and in the end it's your decision.

I mentionned that numpy-stl does something like that, but it's just a wrapper around numpy.

Trimesh internally just uses numpy, so we can't go more low-level than that. And it does what I would do if I figure out how to read a STL. And it does it for binary and text stl. So that's basically the best we can hope for. I probably can't do better.

**Comment by davidh-ssec** [comment]
@larsoner The issue with putting the entire trimesh package in to `vispy/ext` is that it depends on a lot of stuff and has a lot of features that we won't use. The single `stl.py` module (linked above) only depends on numpy and is fairly short. @JPFrancoia Why don't you copy the file, maybe add the copyright and reference the project, license, etc to the top of the file and put it somewhere that makes sense. Maybe in a util subpackage or io or something? Looks like you could put it in `vispy/io/mesh_stl.py` or something.

**Comment by JPFrancoia** [comment]
Ok I just started a PR.

The code works.

Here are an ascii stl file, and a bin stl file. They can both be read with:

```
vertices, faces, normals, texcoords = io.read_mesh('test.stl')
mdata = geometry.MeshData(vertices, faces)
```
[test.stl.txt](https://github.com/vispy/vispy/files/1720566/test.stl.txt)
[test_bin.stl.txt](https://github.com/vispy/vispy/files/1720567/test_bin.stl.txt)

I modified the doc strings. I might need to do a bit more cleaning but it should be quick.

I however don't know how to modify the header to include the copyright.

**Comment by JPFrancoia** [comment]
Ok, I implemented a SceneCanvas class:

```python
# -*- coding: utf-8 -*-
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.

"""
Simple demonstration of Mesh visual.
"""

import numpy as np
from vispy import app, gloo, visuals, geometry, io
from vispy.geometry import create_sphere
from vispy.visuals.transforms import (STTransform, MatrixTransform,
                                      ChainTransform)

import trimesh
import vispy.scene


class MyCanvas(vispy.scene.SceneCanvas):

    def __init__(self):
        vispy.scene.SceneCanvas.__init__(self, keys='interactive', size=(1080, 720))
        self.unfreeze()

        self.meshes = []
        self.rotation = MatrixTransform()

        view = self.central_widget.add_view()
        view.camera = 'turntable'
        view.padding = 100

        mesh = trimesh.load('test.stl')
        mdata = geometry.MeshData(mesh.vertices, mesh.faces)

        self.meshes.append(visuals.MeshVisual(meshdata=mdata, shading='flat'))

        # Scaling factor
        s = 7

        for i, mesh in enumerate(self.meshes):
            x = self.physical_size[0] / 2
            y = self.physical_size[0] / 3
            transform = ChainTransform([STTransform(translate=(x, y),
                                                    scale=(s, s, s)),
                                        self.rotation])
            mesh.transform = transform
            mesh.transforms.scene_transform = STTransform(scale=(1, 1, 0.01))

        self.show()

    def on_resize(self, event):
        # Set canvas viewport and reconfigure visual transforms to match.
        vp = (0, 0, self.physical_size[0], self.physical_size[1])
        self.context.set_viewport(*vp)

        for mesh in self.meshes:
            mesh.transforms.configure(canvas=self, viewport=vp)

    def on_draw(self, event):

        gloo.set_viewport(0, 0, *self.physical_size)
        gloo.clear(color='white', depth=True)

        for mesh in self.meshes:
            mesh.draw()


    # def on_mouse_press(self, event):
        # print("boum")


if __name__ == '__main__':
    win = MyCanvas()

    import sys
    if sys.flags.interactive != 1:
        app.use('qt')
        app.run()
        print(app)
```

But I can't get it to work with a camera. How should I do it ? Should the camera be part of the class ?

**Comment by davidh-ssec** [comment]
This took me way longer than I'm willing to admit:

```
import numpy as np
from vispy import app, gloo, geometry, io
from vispy.geometry import create_sphere
from vispy.scene import visuals, cameras
from vispy.visuals.transforms import (STTransform, MatrixTransform,
                                      ChainTransform)

import trimesh
import vispy.scene


class MyCanvas(vispy.scene.SceneCanvas):

    def __init__(self):
        vispy.scene.SceneCanvas.__init__(self, keys='interactive', size=(1080, 720))
        self.unfreeze()

        self.meshes = []
        view = self.central_widget.add_view()
        view.camera = 'turntable'
        mesh = trimesh.load('test_bin.stl')
        mdata = geometry.MeshData(mesh.vertices, mesh.faces)
        self.meshes.append(visuals.Mesh(meshdata=mdata, shading='flat', parent=view.scene))

        self.freeze()

if __name__ == '__main__':
    win = MyCanvas()
    win.show()
    app.run()
```

Note that I'm using `Mesh` from `vispy.scene.visuals`.

**Comment by JPFrancoia** [comment]
Aaaaaaaah! I tried this exact same thing, but with ```Mesh``` from ```vispy.visuals```. And I got an exception like "Mesh doesn't have a parent attribute". Thank you very much for this piece of code, it works.

Last small question: is there a way to change the mouse buttons used for interactions ? I'd like to use the right button to translate the center of my mesh, with camera 'arcball'. For now I have to do it with Shift+button eft.

**Comment by davidh-ssec** [comment]
I can't remember what kind of customization is allowed out of the box with the cameras. You'll probably have to subclass one of them and assign an instance of it to `view.camera`. The camera code shouldn't be too difficult to figure out.
Arcball:
https://github.com/vispy/vispy/blob/master/vispy/scene/cameras/arcball.py
And its base class for 3D perspective:
https://github.com/vispy/vispy/blob/master/vispy/scene/cameras/perspective.py

**Comment by JPFrancoia** [comment]
Ok perfect thank you very much, I have everything I need :)

Should I let this issue open until you guys decide what to do with the PR ? I leave it to you.

Thank you for your help !
