### ISSUE TITLE
No antialiasing on my computer

### ISSUE THREAD

**Issue by thomasdeneux** [vispy/vispy#1435]
Hello,

I have no antialias on my computer on a simple vispy line drawing test, whereas the same code successfully (with `antialias=True`) resulted in antialiased lines on an other computer.

Could you please help me find out what can I do to have it!

***

Some more information below. Here is the test code, which produces antialias for my colleague (i.e. line appears smooth with shadings) but not for me (i.e. line have steps, and are pure black on the white background).

```
import numpy as np
from vispy import use, app, scene
use('PyQt5')
canvas = scene.SceneCanvas(size=(600, 600), bgcolor='white')
canvas.show()
pos = np.random.normal(loc=300, scale=100, size=(100, 2))
line = scene.visuals.Line(pos=pos, parent=canvas.scene, antialias=True, color='black')
app.run()
```
I am on Ubuntu 16.04 LTS
Graphic card AMD TURKS (DRM 2.50.0 / 4.13.0-32-generic, LLVM 5.0.0)

vispy 0.5.2
PyOpenGL 3.1.0

Removing `use('PyQt5')` does not bring back antialias. Neither adding `from OpenGL import GL` followed by `GL.glEnable(GL.GL_LINE_SMOOTH)` (which anyway I saw is in the code of vispy LineVisual). No other idea what to try!

**Comment by davidh-ssec** [comment]
@thomasdeneux Could you please tell me the output of `print(vispy.sys_info())`? If possible, on both machines you're testing with.

What if you use the PyQt4 backend instead? We've had some issues with the PyQt5 backend but as far as I know they weren't related to antialiasing.

**Comment by thomasdeneux** [comment]
Thank for the quick reply!
Here is the result of `print(vispy.sys_info())` on my computer. I don't have access to the "working" one right now. I will try with PyQt4 later today, yet i hope i can use PyQt5 at the end!

Platform: Linux-4.13.0-32-generic-x86_64-with-debian-stretch-sid
Python:   3.6.4 (default, Feb  2 2018, 14:04:04)  [GCC 5.4.0 20160609]
NumPy:    1.14.0
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.10', '5.10.0')
pyside:   None
pyside2:  None
pyglet:   pyglet 1.3.0
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.5 (DRI2) Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None
GL version:  '3.0 Mesa 17.2.4'
MAX_TEXTURE_SIZE: 16384
Extensions: 'GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_NV_vdpau_interop GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth 
GL_ARB_internalformat_query GL_ARB_map_buffer_alignment 
GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled 
GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_AMD_pinned_memory GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_seamless_cubemap_per_texture GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_context_flush_control GL_KHR_no_error GL_MESA_shader_integer_functions '

**Comment by davidh-ssec** [comment]
Do you see any difference in the output between `antialias=False` and `antialias=True`?

It's possible that `GL_LINE_SMOOTH` isn't supported on your GPU or with your graphics drivers. I recall one of the other maintainers bringing up deprecations for `glLineWidth` and possibly `GL_LINE_SMOOTH` in newer GPUs (newer OpenGL standards iirc).

**Comment by thomasdeneux** [comment]
No difference between `antialias=False` or `True`.
Besides, i noticed that i do not have a `vispy.gloo.gl.GL_LINE_SMOOTH` constant (but there is a `OpenGL.GL.GL_LINE_SMOOTH` constant). Is this expected? Can this be related to my issue?

**Comment by davidh-ssec** [comment]
What does `import OpenGL.GL as GL` get you?

**Comment by davidh-ssec** [comment]
My basic research seems to suggest that GL_LINE_SMOOTH is likely deprecated. Your best workaround, if you can call it that, is to use `Line(..., method='agg')`. Keep in mind that if you end up using VisPy's plotting API you may have to do some roundabout things to set this attribute, `line.method = 'agg'`.

**Comment by rougier** [comment]
Yes, GL_LINE_SMOOTH is deprecated in modern GL.

**Comment by davidh-ssec** [comment]
@rougier Thanks. Is it your suggestion then that maybe the 'agg' line drawing method should be used as the default for vispy and 'gl' be used by anyone wishing to do extremely high rate drawings?

**Comment by thomasdeneux** [comment]
Indeed, `method='agg'` works, great and thank you!

Note that we chose to use vispy for our visualization precisely because we want to go high rate, so in the future we might feel the need to use 'gl' method. Therefore the questions remains open of what is the new equivalent for GL_LINE_SMOOTH in "modern GL".

My modest advice on which method should be the default would be to keep the fastest, since vispy specificity is its efficiency (at least this is how I understand it), with some more visibility about the different drawing methods in the documentation. In particular, regarding antialiasing, mention this in https://github.com/vispy/vispy/wiki/Tech.-Antialiasing.

**Comment by davidh-ssec** [comment]
@thomasdeneux Speed is a relative thing. VisPy should always be faster than traditional CPU based plotting/drawing methods when it comes to most things. Similarly you wanted to draw things at a high rate depends on how high of a rate you are really talking about. Depending on how you implement it drawing matplotlib plots at half-second updates with 20 or so plots can start to reach the limits of the CPU (at least that was my experience 2-4 years ago). Doing the same on a GPU should be nothing, if it is implemented correctly and what you send to the GPU is sent in the best format possible.

The 'gl' method is the fastest way to draw lines on a GPU, but is limited by what you can do with them (antialiasing, line width, etc). It is drawing a primitive GPU element on the buffer. The 'agg' method has a lot more flexibility for what the lines can look like. The 'agg' method implemented in vispy may not be the most advanced (especially as new techniques are developed), but it works and was likely the easiest to implement at the time.

So I think changing the default to 'agg' will give the most flexibility for the most users and as long as we document that 'gl' will be faster but offer less visually I think most users won't care for the change. In fact over the last 6 months or so I've received a lot more issues about the default 'gl' line method not producing expected results because of issues with line width and (like you) antialiasing. I'd rather the default work for more users than work for the few users who need extremely fast line draws.

**Comment by thomasdeneux** [comment]
Ok, this makes sense! Thanks.

**Comment by davidh-ssec** [comment]
I'll leave this open as a reminder to change the default line method to 'agg' or to decide not to change it. @larsoner @kmuehlbauer Thoughts on changing the default line method to 'agg'?

**Comment by rougier** [comment]
@thomasdeneux there's no equivalent for line smoothing in modern GL. This means you have to compute everything by yourself if you want antialias, thickness, joints and caps. If speed is a concern, then "raw" lines are the best.

**Comment by kmuehlbauer** [comment]
@davidh-ssec I think the `docstring` of `line`-visual is quite meaningful on the topic. So I'm +0 for the change. What is really missing for many issues here is a quite meaningful `vispy` FAQ aiming these issues.

**Comment by davidh-ssec** [comment]
@kmuehlbauer @larsoner Thoughts on changing the default line method to 'agg' in vispy 0.6? Or should we wait for 0.7?

**Comment by djhoese** [comment]
See #588 for an example of a rendering bug from agg and see my new #1907 which points out the limitations of our agg method and why it can't be made the default. Closing this as the original problem is either described by these other issues or 'agg' was good enough as a solution.
