### ISSUE TITLE
'EventEmitter loop detected!' error when calling render() on app.Canvas

### ISSUE THREAD

**Issue by rgkirch** [vispy/vispy#1436]
In the demo/gloo/cloud.py example, if I add a call to render in the 'on_draw' method then I get an error.

I want to get the rendered frame so that I can save it off to a video file. I modified the cloud.py example to do what I need but now I'm stuck.

```
    def on_draw(self, event):
        gloo.clear()
        self.program.draw('points')
        self.render()
```
I have vispy version 0.5.2 and I'm running python 3.6.3 from Anaconda.

http://vispy.org/app.html#vispy.app.Canvas.render

Thank you.

```
WARNING: Traceback (most recent call last):
  File "C:\Users\richie\Documents\github\vispy\examples\demo\gloo\cloud.py", line 299, in <module>
    app.run()
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\app\application.py", line 142, in run
    return self._backend._vispy_run()
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 229, in _vispy_run
    return app.exec_()
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 436, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 708, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "C:\Users\richie\Documents\github\vispy\examples\demo\gloo\cloud.py", line 287, in on_draw
    self.render()
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\app\canvas.py", line 538, in render
    self.events.draw()
  File "C:\Users\richie\Anaconda3\lib\site-packages\vispy\util\event.py", line 428, in __call__
    raise RuntimeError('EventEmitter loop detected!')
RuntimeError: EventEmitter loop detected!
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x29f7923f400>> for DrawEvent
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x29f7923f400>> repeat 2
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x29f7923f400>> repeat 4
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x29f7923f400>> repeat 8
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x29f7923f400>> repeat 16
ERROR: Invoking <bound method Canvas.on_draw of <Canvas (PyQt5) at 0x29f7923f400>> repeat 32
```

**Comment by davidh-ssec** [comment]
What's happening here is your asking to render the canvas inside the function that gets called when the canvas is rendered (a loop). What you will want to look in to is similar to what we do for generating screenshots of our examples that include animations. See this semi-complicated code here: https://github.com/vispy/vispy/blob/master/make/make.py#L262

Note the `grabscreenshot` function and how it is used. The most important part is the `_screenshot` utility (eventually it will be made a public function and be better documented). You can find the source for that function here: https://github.com/vispy/vispy/blob/master/vispy/gloo/util.py#L11

**Comment by rgkirch** [comment]
Thank you so much for your help! This is what I came to as a solution for recording cloud.py. I'm putting it here for reference.

The closest example that I found was the basics/scene/save_animation.py but I didn't know how to make that work for me. It makes a Scene and adds visuals to it.

Don't forget to import imageio.

```
    def on_draw(self, event):
        gloo.clear()
        self.program.draw('points')
        im = gloo.read_pixels(alpha=False)
        writer.append_data(im)


if __name__ == '__main__':
    writer = imageio.get_writer('whatwhat.mp4', fps=60)
    c = Canvas()
    app.run()
    writer.close()
```

Thank you so much for your help!

**Comment by davidh-ssec** [comment]
You'll want to be careful with doing this the way that you are. You are adding an operation to every draw operation. Another option would be to read the buffer on a timer so you can space out the frames you are getting.

**Comment by rgkirch** [comment]
You're right, thank you again. I think this is how I could do that.
```
diff --git a/examples/demo/gloo/cloud.py b/examples/demo/gloo/cloud.py
index e748969..2485e90 100644
--- a/examples/demo/gloo/cloud.py
+++ b/examples/demo/gloo/cloud.py
@@ -11,6 +11,7 @@ import numpy as np
 from vispy import gloo
 from vispy import app
 from vispy.util.transforms import perspective, translate, rotate
+import imageio

 vert = """
 #version 120
@@ -252,6 +253,7 @@ class Canvas(app.Canvas):
         gloo.set_state('translucent', clear_color='white')

         self.timer = app.Timer('auto', connect=self.on_timer, start=True)
+        self.record = app.Timer(1/30, connect=self.on_record, start=True)

         self.show()

@@ -292,7 +294,12 @@ class Canvas(app.Canvas):
                                       float(self.size[1]), 1.0, 1000.0)
         self.program['u_projection'] = self.projection

+    def on_record(self, event):
+        im = gloo.read_pixels(alpha=False)
+        writer.append_data(im)

 if __name__ == '__main__':
+    writer = imageio.get_writer('whatwhat.mp4', fps=30)
     c = Canvas()
     app.run()
+    writer.close()
```

**Comment by davidh-ssec** [comment]
Yes that looks like it should work. To avoid global variables you could also pass the writer object to the init of your canvas, assign it to an instance variable, and use it that way from `on_record`. Additionally, although this may be obvious, you should probably add a limit to the number of frames added to the video or a file size limit (additionally see if the writer objects have a `flush` method). @almarklein might know more on that. I'm not an `imageio` expert, he's the maintainer of it.

**Comment by almarklein** [comment]
Exporting to mp4 (which uses the ffmpeg plugin) wil stream the file directly to the file system, so no worries about filling up your RAM.
