### ISSUE TITLE
VisPy isocurve incompatible with matplotlib 2.2.0

### ISSUE THREAD

**Issue by davidh-ssec** [vispy/vispy#1437]
Matplotlib 2.2 is now out and the private contour api `from matplotlib import _cntr` has been removed. We knew this day would come. @QuLogic pointed this thread out on gitter: https://mail.python.org/pipermail/matplotlib-users/2018-March/001313.html

The TL;DR of that is that we can either copy the source from old mpl releases or we could try using skimage. I'm not a huge fan of adding such a huge (optional) dependency on to vispy, but as `isocurve.py` sits right now it uses the `_cntr` classes as an optional dependency so it shouldn't be a huge deal.

http://scikit-image.org/docs/dev/auto_examples/edges/plot_contours.html

As a quick hack I will try to make a PR in the next couple days to switch the import of `_cntr` to a try/except and use the slow contouring method if it isn't found. That should at least let our tests pass and give github users working code.

**Comment by rougier** [comment]
Note that there is GPU only solution but I don't know to what extent "real" contour lines are needed.

**Comment by kmuehlbauer** [comment]
Yes, we also have the IsolineFilter which can be attached to eg. Image Visual.

**Comment by rougier** [comment]
Ah, ok. Sorry for the noise.

**Comment by kmuehlbauer** [comment]
@rougier Did you mean with GPU-method something like in IsolineFilter?

**Comment by rougier** [comment]
I'm not sure actually. I've made them for glumpy (https://github.com/glumpy/glumpy/blob/master/examples/isocurves.py) but I don't remember if I've ported them to vispy...

![isocurves](https://user-images.githubusercontent.com/327203/37111152-48d41e4c-223f-11e8-8211-456ccffca40d.png)

**Comment by kmuehlbauer** [comment]
@rougier Actually we, means you, @larsoner and I discussed this some years ago. This was implemented when we did the spatial-filters using packed floats stuff. Here is the example https://github.com/vispy/vispy/blob/master/examples/basics/scene/contour.py
You surely remember the eye of Mona Lisa.

**Comment by davidh-ssec** [comment]
I'm currently working on replacing the mpl cntr usage with skimage. Is everyone (@larsoner, @kmuehlbauer, @rougier) ok with me completely deprecating the mpl usage?

My thinking is if someone wants new vispy features then they should be ok making updates to all packages including MPL. Then again, they may not have skimage installed.

**Comment by larsoner** [comment]
Yes mpl 1.2 is too old to bother with a `try`/`except`. Feel free to do a `try/except` with `skimage` to make it fast if you want

**Comment by davidh-ssec** [comment]
@larsoner my message on gitter had the wrong version. This is mpl 2.2 which is the latest release.

**Comment by larsoner** [comment]
I'm fine with a `try`/`except` for `skimage`. Just make sure similar functionality isn't available in `scipy` as it seems like a more common thing to have.

**Comment by davidh-ssec** [comment]
Google shows nothing from scipy (but that could be me messing up my google cache with skimage results). The mailing list I linked to at the top suggests skimage from the mpl devs: https://mail.python.org/pipermail/matplotlib-users/2018-March/001313.html
