### ISSUE TITLE
Access to Gl 2.1 functions (like glClampColorARB)

### ISSUE THREAD

**Issue by mabl** [vispy/vispy#1443]
Hi,

I'm currently trying to access glClampColorARB. However, even with ``use_gl('gl+')``, access via self.context.glir.command only raises a warning ``WARNING: Invalid gl command: 'glClampColorARB'``.

Is there an easy way to access these functions when appropriate driver support is available?

**Comment by mabl** [comment]
Okay so I solved this: vispy is designed to not allow access to GL calls >2.0 and only exposes these in its internal gloo.gl layer. Even when using pyopengl, only these functions get patched into the library. If one wants to access other functions, pyopengl needs to be imported directly. This is for example done in 3D texture support.

In the specific case of glClampColor, I needed direct access to the unclamped frambuffer output. This could be achieved by defining the render texture internal format to r32f.

**Comment by davidh-ssec** [comment]
@mabl Can you link me to the part of vispy that does this? IIRC all of the texture types are available even though they aren't technically GL ES compatible.

@larsoner Is this expected? Can't we just pass attribute access straight through?

**Comment by mabl** [comment]
> @mabl Can you link me to the part of vispy that does this? IIRC all of the texture types are available even though they aren't technically GL ES compatible.

See [here in gloo.glir](https://github.com/vispy/vispy/blob/7e7c8c3df8ad4c5a881f1cfef9f292df64d08707/vispy/gloo/glir.py#L1151) 

Regarding getting unclamped values, it worked really nicely for me to do just this:

```python
        rendertex = gloo.Texture2D(shape=size + (1,),  format='luminance', internalformat='r32f')
        fbo = gloo.FrameBuffer(rendertex, gloo.RenderBuffer(size))
```
