### ISSUE TITLE
vispy.visuals.TextVisual() doesn't responds to standard C escape sequences

### ISSUE THREAD

**Issue by mkkb** [vispy/vispy#1447]
Modify the vispy.visuals.TextVisual() to respond and be displayed properly in compliance to escape sequences used by Standard C.

![image](https://user-images.githubusercontent.com/7489565/37413915-534a8942-27a8-11e8-8f73-e61683de93e7.png)

(https://docs.python.org/3.3/reference/lexical_analysis.html)

**Comment by almarklein** [comment]
Looks like this has been fixed in #1454, or is there something left?

**Comment by djhoese** [comment]
I think you're right. Let's close this.
