### ISSUE TITLE
Line colors

### ISSUE THREAD

**Issue by iberinsk** [vispy/vispy#1448]
Hi! Is it possible to set the array of colors to the array of lines? I have an array of coordinates (pos), an array of connections (pairlist) and the array of colors. An I try to use the following structure: 
```
line = scene.visuals.Line(pos=pos, connect=pairlist, width = 3, parent = view.scene)
line.set_data(pos=pos, connect=pairlist, color=colors, width = 3)
```

But it does not work. I managed to use a different way:
```
lines = []
for pair in pairlist:
   ...
    line = scene.visuals.Line(pos=posline, color=color, width = 3, parent = view.scene)
    lines.append(line)
...
for k in range(len(pairlist)):
        lines[k].set_data(pos=pos[pairlist[k]], color=colors[k], width = 3)
```
but it works very slow unfortunately. Is it possible to use the 'connect' option with the colors array?

**Comment by davidh-ssec** [comment]
What are the shapes of your original `pos` and your original `colors`? And in your first code block is there a reason you don't put all of the `set_data` arguments in to the `Line` creation?

From the documentation of `Line`:

```
    color : Color, tuple, or array
        The color to use when drawing the line. If an array is given, it
        must be of shape (..., 4) and provide one rgba color per vertex.
        Can also be a colormap name, or appropriate `Function`.
```

So I would assume that if you make the `colors` parameter the right size then you should be able to do whatever you want. Your second block of code is definitely not what you want to do. You'll want to prepare the colors as a numpy array before handle. The fastest way depending on how your colors are organize would be to preallocate the array `colors = np.zeros((num_colors, 4), np.float32)` and then fill in what you have to. I think the colors have to be in a 0 to 1 range and have to be floats (could be wrong).

**Comment by iberinsk** [comment]
'pos' is an array (n, 2), 'pairlist' is an array (m, 2), where m and n are some numbers an m>n. 'colors' is an array (m,3) filled with numbers from 0 to 1.   

The second block of code works perfectly for me: it draws the lines with colors from 'colors' corresponding to lines connecting the pairs from 'pairlist'.

**Comment by davidh-ssec** [comment]
Do you get an error with your first code block or wrong results?

**Comment by davidh-ssec** [comment]
Have you tried `colors = np.repeat(colors, 2, axis=0)`? That would make the color value apply to each vertex instead of each segment.

**Comment by iberinsk** [comment]
An error :(

**Comment by davidh-ssec** [comment]
...and what is the error?

**Comment by iberinsk** [comment]
`WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x0000000013C96A20>
WARNING: Traceback (most recent call last):`
(...)
`ValueError: data.shape[-1] must be 4 not 1 for u_color

ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7afe0f0>> for DrawEvent

WARNING: Error drawing visual <vispy.visuals.line.line._GLLineVisual object at 0x0000000013C96A20>

ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x7afe0f0>> repeat 2
`
...

**Comment by iberinsk** [comment]
I can not initialize the 'line' object with the set of colors such as: 
`line = scene.visuals.Line(pos=pos, connect=pairlist, color = np.random.rand(len(pairlist),3), width = 3, parent = view.scene) ` 

The same method with one color works: 
`line = scene.visuals.Line(pos=pos, connect=pairlist, color = np.random.rand(1,3), width = 3, parent = view.scene) `

**Comment by iberinsk** [comment]
> Have you tried colors = np.repeat(colors, 2, axis=0)? That would make the color value apply to each vertex instead of each segment.

@davidh-ssec ,  Thank you, I think I got your message. The 'color' parameter must correspond not to the number of lines, but to the number of vertices. Here is a working code:

```
import numpy as np
from vispy import scene

canvas = scene.SceneCanvas(keys='interactive', bgcolor='white',size=(1600, 900)) ##00ff00
view = canvas.central_widget.add_view()

pos = np.random.rand(4,2)
pairlist = np.array([[0,1],[0,2], [0,3], [2,1], [2,3]])
line = scene.visuals.Line(pos=pos, connect=pairlist ,  color=np.random.rand(4,3), width = 3, parent = view.scene)  

# add a colored 3D axis for orientation
axis = scene.visuals.XYZAxis(parent=view.scene)


scatter = scene.visuals.Markers()
scatter.set_data(pos, edge_color=(1,0,1,1), face_color=(1, 0, 1, 1), size=10)
view.add(scatter) 

view.camera = 'turntable'  # 'arcball', 'fly', or 'turntable' or 'panzoom'    

im = canvas.render()
canvas.show()

```

**Comment by davidh-ssec** [comment]
Awesome! I'm glad you got it to work.
