### ISSUE TITLE
Any example of 3D scene with several objects?

### ISSUE THREAD

**Issue by yesint** [vispy/vispy#1451]
Sorry if this question is dumb - I'm new to vispy.
I'm trying to understand how to use scene graph in vispy to draw several geometric shapes (spheres, tubes) in given positions. There is no example for this and documentation is too brief to understand how to achieve this. What is the preferable way of positioning the visual at given point in space?

**Comment by kmuehlbauer** [comment]
@yesint Have a look at this example https://github.com/vispy/vispy/blob/acc4c4b24ff4e628253641df887a6e58fbd24a8e/examples/basics/scene/sphere.py
There the STTransform is used to move the spheres apart in xy-space. If you set the z coordinate in the transform accordingly then you can move the spheres to arbitrary locations in xyz-space .
