### ISSUE TITLE
vispy.test() failure 

### ISSUE THREAD

**Issue by gautham949** [vispy/vispy#1453]
I installed Vispy in my linux system and tried testing the installation using `Vispy.test()`. 

It shows the following error. I am new to using python and Vispy and I am unable to comprehend the error. Can someone help me with the solution? 

Here is the error

```
vispy.test()

Skipping backend pyqt4, not installed or working properly

Running tests with pyqt5 backend:
_VISPY_TESTING_APP=pyqt5   -m vispy_app_test
Failed: unit failure (2)

Skipping backend pyside, not installed or working properly

Skipping backend pyglet, not installed or working properly

Skipping backend glfw, not installed or working properly

Skipping backend sdl2, not installed or working properly

Skipping backend wx, not installed or working properly

Skipping backend egl, not installed or working properly

Skipping backend osmesa, not installed or working properly

Running tests with ipynb_webgl backend:
_VISPY_TESTING_APP=ipynb_webgl   -m vispy_app_test
Failed: unit failure (2)

Skipping backend _test, not installed or working properly

Running tests with no backend:
_VISPY_TESTING_APP=nobackend   -m "not vispy_app_test"
Failed: unit failure (2)
Skipping example test: Cannot test examples unless in vispy git directory
Running line endings check... 
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'ipynb_webgl', 'nobackend'] failed, ['pyqt4', 'pyside', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', '_test', 'examples'] skipped) in 15.466 seconds
Traceback (most recent call last):

  File "<ipython-input-8-e78e52328cb1>", line 1, in <module>
    vispy.test()

  File "/home/gautham/anaconda3/lib/python3.6/site-packages/vispy/testing/_runners.py", line 446, in test
    raise RuntimeError('FAILURE')

RuntimeError: FAILURE`
```

## Package Versions

* Spyder:3.2.7
* Python:3.6.4
* Qt:
* PyQt:5.6.0
* Operating System:Ubuntu 17.10

### Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by kmuehlbauer** [comment]
@gautham949 Doesn't look suspicious to me.

How did you install vispy? As you are using conda, can you try the following?

Create dedicated vispy environment:

```
conda create -c conda-forge -n vispy_env python=3.6 vispy pyqt=4* numpy
source activate vispy_env
```

This pulls in vispy 0.5.2 from conda-forge channel using pyqt4 instead of pyqt5. There are still issues with pyqt5. Just let's try this setup first. I just checked here locally on my linux-box, tests are running properly.

**Comment by kmuehlbauer** [comment]
@gautham949 I remember there where issues with missing test framework. So what helped here is to manually install `nose`.

```source activate vispy_env
conda install -c conda-forge nose
```

**Comment by kmuehlbauer** [comment]
@larsoner Do we have kind of a `requirements-test.txt` or the like? At least it would be good to have the test-machinery check for nose/pytest dependencies and graceful exit if those are missing. 

@gautham949 I think the missing test framework is your problem, so you might also try the tests with pyqt5 after resolving the dependencies.

**Comment by gautham949** [comment]
@kmuehlbauer  
I installed vispy using pip as mentioned in the installation page of Vispy.org

I installed the dependencies using `conda install numpy pyqt`
And then I used `pip install --upgrade vispy` 
When I found it not working I tried the following 
`$ git clone git://github.com/vispy/vispy.git  # creates "vispy" folder`
`$ cd vispy`
`$ python setup.py develop`

I have the Anaconda scientific python distribution from Continuum Analytics.

I tried installing test framework manually and test for `vispy.test()` and it shows the following error

```
vispy.test()
----------------------------------------------------------------------
Skipping backend pyqt4, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with pyqt5 backend:
_VISPY_TESTING_APP=pyqt5   -m vispy_app_test
Failed: unit failure (2)
----------------------------------------------------------------------
Skipping backend pyside, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend pyglet, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend glfw, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend sdl2, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend wx, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend egl, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Skipping backend osmesa, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with ipynb_webgl backend:
_VISPY_TESTING_APP=ipynb_webgl   -m vispy_app_test
Failed: unit failure (2)
----------------------------------------------------------------------
Skipping backend _test, not installed or working properly
----------------------------------------------------------------------
----------------------------------------------------------------------
Running tests with no backend:
_VISPY_TESTING_APP=nobackend   -m "not vispy_app_test"
Failed: unit failure (2)
Skipping example test: Cannot test examples unless in vispy git directory
Running line endings check... 
Passed

Skipping flake8 test, flake8 not installed
Passed

Testing failed (['pyqt5', 'ipynb_webgl', 'nobackend'] failed, ['pyqt4', 'pyside', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', '_test', 'examples'] skipped) in 17.581 seconds
Traceback (most recent call last):

  File "<ipython-input-2-e78e52328cb1>", line 1, in <module>
    vispy.test()

  File "/home/gautham/anaconda3/lib/python3.6/site-packages/vispy/testing/_runners.py", line 446, in test
    raise RuntimeError('FAILURE')

RuntimeError: FAILURE
```

Thank you.

**Comment by kmuehlbauer** [comment]
@gautham949 Could you please create a dedicated conda environment from the command line as I suggested before. This will at least rule out any dependency clashes.

**Comment by djhoese** [comment]
It looks like your vispy tests failed but for some reason numpy tests are also being run. By that I mean the ones *from numpy*. I think this is probably do to recent changes in numpy to drop nose for testing. I don't recall what version of numpy this was done in, but from what I can tell your vispy tests are fine.

**Comment by trees4me** [comment]
You're right, the examples are working now!  Looks amazing, thanks!

**Comment by philCryoport** [comment]
> 
> 
> @gautham949 Doesn't look suspicious to me.
> 
> How did you install vispy? As you are using conda, can you try the following?
> 
> Create dedicated vispy environment:
> 
> ```
> conda create -c conda-forge -n vispy_env python=3.6 vispy pyqt=4* numpy nose pytest
> source activate vispy_env
> ```
> 
> This pulls in vispy 0.5.2 from conda-forge channel using pyqt4 instead of pyqt5. There are still issues with pyqt5. Just let's try this setup first. I just checked here locally on my linux-box, tests are running properly.
> 
> Update: added `nose`
> Update2: added `pytest`

Thank you for this!   I finally could run vispy.test() on Windows 10 after I found this.

**Comment by djhoese** [comment]
@philCryoport Glad you figured it out. I'm going to close this as it seems everyone got things working. If anyone reading this still has trouble running certain things about vispy they should open a new issue. That said, some tests may fail (we're making them better) on some systems for small things like race conditions that are unlikely to arise in real life use cases.

**Comment by noshaba** [comment]
> I was getting a similar error on a win10 laptop with Q M2000M GPU and Intel onboard graphics.
> 
> Setup a conda env using the @kmuehlbauer suggested command:
> 
> ```
> conda create -c conda-forge -n vispy_env python=3.6 vispy pyqt=4* numpy nose pytest
> activate vispy_env
> ```
> 
> `vispy.test()` still failed.
> 
> Opened a new anaconda prompt and forced the graphics card to the Quadro card. Then it made it through some of the tests, but is still failing. Let me know if you have any other suggestions.
> 
> Attached files: sys_info for intel (prior conda env with pyqt5) [vispy_sysinfo_intel.txt](https://github.com/vispy/vispy/files/2142436/vispy_sysinfo_intel.txt)
> 
> sys_info for quadro (conda env = vispy_env) [vispy_sysinfo_Quadro.txt](https://github.com/vispy/vispy/files/2142437/vispy_sysinfo_Quadro.txt).
> 
> vispy.test() output [vispy_test.txt](https://github.com/vispy/vispy/files/2142438/vispy_test.txt)

How did you force it use the Quadro card? For me it's using the Intel integrated one :/
