### ISSUE TITLE
examples/basics/visuals/line_draw.py

### ISSUE THREAD

**Issue by marco-mf3** [vispy/vispy#1455]
Hi,
I can't run the example line_draw.py. Someone can try if it is only my problem or if there is an issue?

```

Traceback (most recent call last):
  File "/home/........../basics/visuals/line_draw.py", line 178, in <module>
    win = Canvas()
  File "/home/........../basics/visuals/line_draw.py", line 154, in __init__
    self.pos = np.zeros((n, 3), dtype=np.float32)
  File "/home/........../lib/python3.6/site-packages/vispy/util/frozen.py", line 16, in __setattr__
    'attributes' % (key, self))
AttributeError: 'pos' is not an attribute of class <Canvas (PyQt5) at 0x7f4334088f98>. Call "unfreeze()" to allow addition of new attributes

Process finished with exit code 1

```

**Comment by kmuehlbauer** [comment]
@marco-mf3 This example needs update. There were changes to the scene API since committing, so this won't work atm. ping @fschill the original author, if he can give some guidance here.

**Comment by davidh-ssec** [comment]
@kmuehlbauer I have this almost fixed, but need to sanity check something. Should sub-nodes (sub-visuals) be able to define `on_mouse_press` methods and have them automatically connected to the events? I can't seem to get it to work unless the canvas passes them to the line.

**Comment by fschill** [comment]
Hi, 
sorry about the slow response, very busy at the moment. I just checked my local copy, and it seems I've already done some fixes last year but forgot to push. I just updated my local version to current master and it seems to work for me. Can you maybe test my new version, and let me know if it works for you? I'll do a pull request soon if that fixes it.
https://github.com/fschill/vispy/blob/master/examples/basics/visuals/line_draw.py

**Comment by davidh-ssec** [comment]
Looks like we have all the same fixes I think. Yours looks a little cleaner with the way you did the mouse event handling.

**Comment by fschill** [comment]
PS: what I've been looking for in a long time is a basic, simple package to do interactive vector drawing with the mouse (the line_draw example was a first foray in that direction, but did not pursue it for now, lack of time...). Does anyone know if something like that is around now, or planned for vispy? (apologies if this is off-topic...)

**Comment by frozenranger** [comment]
Hey guys I'm getting the same error but with the line?


C:\ProgramData\Anaconda3\python.exe C:/Users/peter/PycharmProjects/graphs/vispy_test2.py
Traceback (most recent call last):
  File "C:/Users/peter/PycharmProjects/graphs/vispy_test2.py", line 27, in <module>
    win = Canvas()
  File "C:/Users/peter/PycharmProjects/graphs/vispy_test2.py", line 21, in __init__
    self.line = visuals.Line(pos, color, parent=self.scene)
  File "C:\ProgramData\Anaconda3\lib\site-packages\vispy\util\frozen.py", line 16, in __setattr__
    'attributes' % (key, self))
AttributeError: 'line' is not an attribute of class <Canvas (PyQt5) at 0x261ceadba08>. Call "unfreeze()" to allow addition of new attributes

Process finished with exit code 1

**Comment by djhoese** [comment]
@frozenranger Your issue isn't quite the same as the original one here. The original issue was with an example in the vispy repository. The bug being that the example hadn't been updated to match changes in vispy.

Your error message is intended for the way you are subclassing the Canvas class. You should follow the instructions of the error message to be able to assign your own attributes to your subclass. So in your `__init__` method of your subclass do:

```

def __init__(self, ...):
    ... stuff ...
    self.unfreeze()
    self.line = visuals.Line(pos, color, parent=self.scene)
    ... assign other attributes if you'd like
    self.freeze()
    ... stuff ...
```

If you're still having issues, please open a new bug report. Thanks.

**Comment by frozenranger** [comment]
Awesome! thank you very much for the fast reply and answer :)

I look forward to learning vispy!!! :)
