### ISSUE TITLE
Render to VR headset using pyopenvr

### ISSUE THREAD

**Issue by godber** [vispy/vispy#1472]
I've played with vispy a bit off and on since I saw it presented at SciPy several years ago and have always been impressed with its functionality.  I've also been looking at the nascent [pyopenvr](https://github.com/cmbruns/pyopenvr) library and reading the code for both trying to figure out the best approach for rendering vispy visualizations in an Oculus Rift VR headset.  I've been reading vispy code with the intent of trying to implement this on my own, but figured I might be able to speed things up if I asked for pointers in an issue here.

The best I've figured out is that I would expect I can use the [pyopenvr interface](https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/__init__.py) (here is [an example of that interface being used](https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/gl_renderer.py
), I think.)

I'm thinking I need to either extend an existing vispy gl backend or implement a new one?  There's a lot of abstraction going on in vispy that I don't fully grasp yet ... combined with the fact that I don't really know GL complicates my efforts.  Am I close here?

I know I need to do some more reading of the vispy docs, so I'll go do that for now, but if anyone has any suggestions off the bat, that would be cool.

Also, this is a spare time/hobby effort on my part so I expect it to drag on.

Thanks for any suggestions in advance.

**Comment by godber** [comment]
There are simple examples for pyopenvr, like this one, that renders a cube:

https://github.com/cmbruns/pyopenvr/blob/master/src/samples/wx/hello_wx.py

the cube is defined here:

https://github.com/cmbruns/pyopenvr/blob/master/src/openvr/color_cube_actor.py

As for what is put on the computer screen, it's either a blank window or a mirror of what is shown to the left eye depending on an argument you pass when creating the OpenVrGlRenderer.  You can see the window optionally being rendered to below (if that option if False then the window is just black):

https://github.com/cmbruns/pyopenvr/blob/1.0.1301/src/openvr/gl_renderer.py#L188-L191

And then below the window, you see it render to the left eye, then the right eye.

Another thing to note is that the code above calls [`display_gl`](https://github.com/cmbruns/pyopenvr/blob/1.0.1301/src/openvr/gl_renderer.py#L206-L210) which loops over all of the Actors (like the cube) and calls their `display_gl` methods.

It's also worth noting that they have examples using multiple GUI tools as well.  You can see here, in the WX example, where the `gl_renderer.render_scene()` is called:

https://github.com/cmbruns/pyopenvr/blob/1.0.1301/src/openvr/glframework/wx_app.py#L83

Which I guess is somehow called periodically by WX windows through the implementation of this `OnCanvasPaint` method:

https://github.com/cmbruns/pyopenvr/blob/1.0.1301/src/openvr/glframework/wx_app.py#L77-L78

**Comment by godber** [comment]
Thank you very much for your suggestion, they seem to make sense.  Perhaps I will break 1 down a little further and see if I can implement an example without using their Actor abstractions since I think those are the most obvious "GL bits" I am not understanding right now.

I think one big thing to get my head around is with vispy, we explicitly set the camera position and then optionally move that camera around with events.  In pyopenvr, there is some initial position of the camera and then moving your head around provides the events for moving the cameras around the scene.

Hmm, I'm getting the feeling that the functionality embodied in ther `gl_renderer` would be implemented as maybe a couple things.

Thanks again, I'll think about this and probably do some more work on it this weekend.

**Comment by krichardsson** [comment]
Hi @godber !
I'm interested in this functionality as well, did you manage to get any further?

**Comment by queenish001** [comment]
Heya @godber is this issue resolved now? Can it be closed?

**Comment by godber** [comment]
Sadly, I don't have time to pursue this.  I'll close for now and come back to it if I end up having an opportunity.
