### ISSUE TITLE
Refresh canvas after adding markers to view

### ISSUE THREAD

**Issue by Attila94** [vispy/vispy#1477]
I am trying to write a function which can add point clouds to an existing SceneCanvas based on this example: https://github.com/vispy/vispy/blob/master/examples/basics/scene/point_cloud.py

However, after calling my custom 'pointcloud' function from my main file, the points do not show up on the canvas. Is there any function that needs to be called to update the canvas or view? What is the exact relationship between a canvas and a view anyway?

Any help would be appreciated :)

My code:

```python
import vispy
from vispy import scene
from vispy.scene import visuals
from vispy.visuals import transforms

class Environment(scene.SceneCanvas):
    
    def __init__(self, *args):
        # Make a canvas and add simple view
        scene.SceneCanvas.__init__(self, keys='interactive', show=True)
        Environment.unfreeze(self)
        self.view = self.central_widget.add_view()

        # define camera
        self.view.camera = vispy.scene.TurntableCamera(fov=60.0,elevation=25.0,azimuth=-90.0,distance=20.0)
        self.view.camera.center = (0,0,0)
        
        visuals.XYZAxis(parent=self.view.scene)
        print('Environment created')
    
    def pointcloud(self, pointcloud, color):
        # create scatter object and fill in the data
        points = visuals.Markers()
        points.set_data(pointcloud[:,:3], edge_color=None, face_color=color, size=2)
        
        self.view.add(points)
        print('Pointcloud added')
        
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
```

**Comment by djhoese** [comment]
When do you call your `pointcloud` method? And for that matter, when do you create the canvas object? You never call `canvas = Environment()` which should be in the `if __name__` part of your script.

**Comment by Attila94** [comment]
Found it: my color argument was `(0,0,1,0)` so I was plotting everything in transparent. I know, wauw...
Thanks for your help, it works as supposed to.
