### ISSUE TITLE
Rendering issue when exporting to image

### ISSUE THREAD

**Issue by JPFrancoia** [vispy/vispy#1478]
Hi,

I'm developing some sort of stl viewer. STL are simple meshes, so it's quite straightfoward to build such an app. Here is my code:

```python
#!/usr/bin/python
# coding: utf-8

import os
from vispy import app, geometry, gloo
import vispy.scene
from vispy.scene import visuals
from vispy.app import use_app
from typing import Tuple, Union
from vispy.visuals.filters import Alpha
import vispy.io


# TODO: remove trimesh, vispy should soon be able to load STL files
import trimesh

use_app('PyQt5')


class STLViewer(vispy.scene.SceneCanvas):

    def __init__(self, size: Tuple[int, int]=(800, 500)):

        """
        size is the size in pixels (x, y).
        """

        vispy.scene.SceneCanvas.__init__(self, keys='interactive',
                                         size=size, bgcolor='white')

        # Unfreeze the class, so adding attributes is possible
        self.unfreeze()

        # Create a dict to store several meshes
        # Meshes are stored with their names so they can be reloaded/reviewed
        # namely
        self.meshes = dict()

        # Add an 'arcball' camera
        self.view = self.central_widget.add_view()
        self.view.camera = 'arcball'

        # Freeze the class again. Might not be necessary
        self.freeze()


    def viewMesh(self, file_name: str):

        """
        Will load the file file_name in the STL viewer. If the mesh didn't
        exist before, it will be created. Else, it will be updated
        """

        # file_name is passed wo extension, so add .stl
        file_name = file_name + ".stl"

        file_to_view = os.path.join(file_name)

        try:
            # Load the stl file. Works with binary or ascii stl files
            mesh = trimesh.load(file_to_view)
            mdata = geometry.MeshData(mesh.vertices, mesh.faces)

        except Exception as e:
            return

        # Try to update the mesh, if it doesn't exist, create it
        try:
            self.meshes[file_name].set_data(meshdata=mdata)
        except KeyError:
            # Create a Mesh visual, with the view as parent
            self.meshes[file_name] = visuals.Mesh(meshdata=mdata,
                                                  shading='flat',
                                                  parent=self.view.scene)


    def screenshot(self):

        img = self.render()

        vispy.io.write_png("wonderful.png", img)

        pass


    def on_mouse_release(self, event):

        self.screenshot()


if __name__ == '__main__':
    win = STLViewer()
    win.viewMesh("beaker")
    win.show()

    import sys
    if sys.flags.interactive != 1:
        app.run()
        print(app)
```

I subclassed on_mouse_release to take a screenshot. I simply render the canvas to an image. The problem is that there is some sort of rendering/transparency glitch in the image:

My canvas:

![screen](https://user-images.githubusercontent.com/2399090/39532283-7869d028-4e24-11e8-96a0-365ffa106a89.png)

The outputed image:

![wonderful](https://user-images.githubusercontent.com/2399090/39532311-86e64cd0-4e24-11e8-88f3-a57974c3ab34.png)

I have the latest version of vispy, cloned from master. Is it a known issue, is it possible to fix it ?

Cheers

EDIT:

Here is the STL if you want to reproduce:

[beaker.stl.txt](https://github.com/vispy/vispy/files/1967922/beaker.stl.txt)

**Comment by djhoese** [comment]
This may be related to: https://github.com/vispy/vispy/issues/1412

@astrofrog Any ideas?

@JPFrancoia What happens if you use pyqt4?

**Comment by JPFrancoia** [comment]
I tried with PyQt4 and pyglet, same problem.

**Comment by djhoese** [comment]
Try using `from vispy.gloo.util import _screenshot; img = _screenshot()` instead of `render` and see if that gives you different results.

**Comment by JPFrancoia** [comment]
It works, I don't get any visual glitch on the image. I suppose it's not possible to set the resolution of the image then ?

**Comment by djhoese** [comment]
The `_screenshot` is just reading the display buffer so it is based on the size of the canvas iirc. You may be able to figure out how to customize it if you read the source code for `_screenshot` and `render` and figure out the differences. At least that's my best guess at the moment.

**Comment by JPFrancoia** [comment]
ok thanks, that will do at the moment.

Thanks
