### ISSUE TITLE
Light reflection and transparency

### ISSUE THREAD

**Issue by JPFrancoia** [vispy/vispy#1482]
Hi,

I'm trying to implement some sort of STL viewer with vispy. So far everything works, but I'm not satisfied with the general look.

Here is a sample of an object I can view:

![test](https://user-images.githubusercontent.com/2399090/40178666-1378c842-59da-11e8-83dd-e51cd41909bb.png)

- Is it possible to change the lighting to avoid this white reflection on some faces ? It seems when the light shines directly on one face, the face becomes completely white. Since I have a white background, it looks like this face disappears.

Here is a sample of the object with an Alpha filter:

![transparent](https://user-images.githubusercontent.com/2399090/40178764-57d4bbea-59da-11e8-9973-8ccd3ac6ebdc.png)

The result is not great. I would like it to look more like the X-ray view in Cura (Ultimaker's slicer):

![screen](https://user-images.githubusercontent.com/2399090/40178807-7823968c-59da-11e8-9c2d-a81913d0912c.png)

I tried to set the shading of the object to None and to set the alpha filter at the same time, but it doesn't really work. When I play with the alpha channel, the faces just become transparent, but the light reflection is still there, making the view almost unusable.

- Is there a way to make the transparency look like the X-ray view in Cura ?

Here is the code I use:

```python
#!/usr/bin/python
# coding: utf-8

import os
from vispy import app, geometry, gloo
import vispy.scene
from vispy.scene import visuals
from vispy.app import use_app
from typing import Tuple, Union
from vispy.visuals.filters import Alpha
import vispy.io


# TODO: remove trimesh, vispy should soon be able to load STL files
import trimesh

use_app('PyQt5')


class STLViewer(vispy.scene.SceneCanvas):

    def __init__(self, size: Tuple[int, int]=(800, 500)):

        """
        size is the size in pixels (x, y).
        """

        vispy.scene.SceneCanvas.__init__(self, keys='interactive',
                                         size=size, bgcolor='white')

        # Unfreeze the class, so adding attributes is possible
        self.unfreeze()

        # Create a dict to store several meshes
        # Meshes are stored with their names so they can be reloaded/reviewed
        # namely
        self.meshes = dict()

        # Add an 'arcball' camera
        self.view = self.central_widget.add_view()
        self.view.camera = 'arcball'

        self.translucent = False

        # Create an alpha filter. alpha=1
        self.translucent_filter = Alpha()

        # Freeze the class again. Might not be necessary
        self.freeze()


    def viewMesh(self, file_name: str):

        """
        Will load the file file_name in the STL viewer. If the mesh didn't
        exist before, it will be created. Else, it will be updated
        """

        # file_name is passed wo extension, so add .stl
        file_name = file_name + ".stl"

        file_to_view = os.path.join(file_name)

        try:
            # Load the stl file. Works with binary or ascii stl files
            mesh = trimesh.load(file_to_view)
            mdata = geometry.MeshData(mesh.vertices, mesh.faces)

        except Exception as e:
            return

        # Try to update the mesh, if it doesn't exist, create it
        try:
            self.meshes[file_name].set_data(meshdata=mdata)
        except KeyError:
            # Create a Mesh visual, with the view as parent
            self.meshes[file_name] = visuals.Mesh(meshdata=mdata,
                                                  shading='flat',
                                                  parent=self.view.scene)

            self.meshes[file_name].unfreeze()
            self.meshes[file_name].filter = self.translucent_filter
            self.meshes[file_name].attach(self.translucent_filter)
            self.meshes[file_name].freeze()



    def setTranslucent(self, translucent: bool):

        # TODO: toggle translucent state for meshes, separately
        """Toggle the translucent state of all the meshes"""

        for mesh in self.meshes.values():

            # Change the alpha value of the mesh's alpha filter
            if translucent:
                mesh.filter.alpha = 0.3
                mesh.shading = None
            else:
                mesh.filter.alpha = 1

        # Update the scene immediately
        self.view.scene.update()


    def on_mouse_release(self, event):

        self.translucent = not self.translucent

        self.setTranslucent(self.translucent)



if __name__ == '__main__':
    win = STLViewer()
    win.viewMesh("beaker")
    win.show()

    import sys
    if sys.flags.interactive != 1:
        app.run()
        print(app)
```

And here is the STL for the simple object:

[beaker.stl.txt](https://github.com/vispy/vispy/files/2013209/beaker.stl.txt)

**Comment by JPFrancoia** [comment]
Thanks. Actually changing ambient_light_color didn't do anything. But thanks for the link, because 3 lines below the line you highlighted, there is the ```shininess``` attribute. Setting it to 0 solved my reflection problem.

Now, I just have a problem with the transparency. I still accept/enjoy input !

**Comment by djhoese** [comment]
I meant to do that 😜 

Have a look at specifying the `color` (via property) or the face color (via init keyword argument), at least as a test. I'm not seeing a face color property at the moment but that might be what you need. You could specify an RGBA color with a lower alpha.

**Comment by JPFrancoia** [comment]
Hum, I tried this (in my code above):

```python
        try:
            # Load the stl file. Works with binary or ascii stl files
            mesh = trimesh.load(file_to_view)
            mdata = geometry.MeshData(mesh.vertices, mesh.faces)
            verts = mdata.get_vertices(indexed='faces')
            nf = verts.size // 9
            fcolor = [[1, 1, 0, 0.3]] * nf
            mdata.set_face_colors(fcolor)
        except Exception as e:
            return
```

So I can easily setup color and transparency. Here is what I get:

![screen](https://user-images.githubusercontent.com/2399090/40230068-37d11172-5a8e-11e8-8323-3b2d8fd4d8a1.png)

So basically, same results as before, but with a different color...

I think the problem is that when the transparency is set, some faces have this weird grey colours, all different. I'd like the colour of the faces to be the same everywhere, but transparent (I don't know if it makes sense physically, but you get the idea. See the X-ray view in the Cura screenshot).

**Comment by djhoese** [comment]
@JPFrancoia It's hard to tell from the screenshot but is the center of the figure not transparent in Cura? Or is this from multiple faces being put on top of each other and making it look not transparent?

Also, the Cura screenshot doesn't seem to have any lighting effects on it in the xray view, could that be making things weird?

**Comment by JPFrancoia** [comment]
> @JPFrancoia It's hard to tell from the screenshot but is the center of the figure not transparent in Cura? Or is this from multiple faces being put on top of each other and making it look not transparent?

I don't understand what you mean.

> 
Also, the Cura screenshot doesn't seem to have any lighting effects on it in the xray view, could that be making things weird?

Definitely, I think this it. I think we're not too far to achieving the same result. For the X-ray view, I think I need to set the shading of the mesh to None, and disable ligthing effects. But I don't know how to disable the lighting effects. Any idea ?

**Comment by djhoese** [comment]
For the first question, I was talking about if you add up enough semi-transparent objects they end up looking opaque, right? So I was wondering if the center cylinder in your Cura image just looks opaque from the screenshot or if it actually is opaque.

I would think turning off shininess should turn it off or maybe playing with the `light_dir` property: https://github.com/vispy/vispy/blob/master/vispy/visuals/mesh.py#L480

**Comment by JPFrancoia** [comment]
> For the first question, I was talking about if you add up enough semi-transparent objects they end up looking opaque, right? So I was wondering if the center cylinder in your Cura image just looks opaque from the screenshot or if it actually is opaque.

I'm not sure I understand, but the screenshot exactly looks like what I have on my screen. But yeah the center cylinder is actually opaque in Cura. So strictly speaking, I'm not sure Cura uses transparency.

I tried the ```light_dir``` solution (I set it to 0, 0, 0):

![screen](https://user-images.githubusercontent.com/2399090/40239340-afc49748-5aad-11e8-9730-09bde7336a11.png)

So it's darker but it's still not what I want.

The shininess is set to 0 by default in my code.

**Comment by djhoese** [comment]
What if you set the face colors so the outside is semi-transparent but the inside cylinder is opaque? I'm sure it won't look perfect, but it would be good to see the difference.

Also, is Cura showing the data loaded from the stl file? Or is it the software that created the file? The image from vispy looking like it is made of a lot of smaller shapes (with faces in between chunks of the cylinder even) rather than two connected cylinders. I've never used stl files so I'm not sure what type of information they hold.

**Comment by JPFrancoia** [comment]
> What if you set the face colors so the outside is semi-transparent but the inside cylinder is opaque? I'm sure it won't look perfect, but it would be good to see the difference.

It's not possible. The object is not two cylinders, it's a beaker. So the "inside cylinder" in Cura's screenshot is void.

> Also, is Cura showing the data loaded from the stl file?

Yes

> The image from vispy looking like it is made of a lot of smaller shapes (with faces in between chunks of the cylinder even) rather than two connected cylinders. I've never used stl files so I'm not sure what type of information they hold.

The stl file store vertices and unit normals: https://en.wikipedia.org/wiki/STL_(file_format). The  smaller shapes you see are probably the faces of my object. There are plenty, since the object is rendered in a decent resolution.

But on the same file, Cura is capable of doing what I want, so there must be a way.

**Comment by djhoese** [comment]
So I think what is happening is that vispy or opengl is drawing each of the STLs shapes and each face of those "wedges" is having an additive effect so the faces that are next to each other appear less transparent (more opaque) which produces weird results.

You may have luck playing with the GL state (`my_vis.set_gl_state('translucent', blend=True)` and/or other GL state options (depth_test...probably not). This may also help: https://www.khronos.org/opengl/wiki/Transparency_Sorting

Maybe the default mesh state is messing this up (from mesh.py):
```
        self.set_gl_state('translucent', depth_test=True,
                          cull_face=False)
```

**Comment by campagnola** [comment]
Three points:

1. There is a mesh example that includes meshes without lighting:
examples/basics/visuals/mesh.py

2. Transparency in openGL is tricky because you either need to draw all
faces in the mesh sorted from farthest to nearest (which vispy currently
does not support) or you need to use an order-independent blending mode. A
quick way to achieve the latter is to use visual.set_gl_state('additive').
If you're curious, there are many, many articles you can find on the topic
of transparency in opengl.

3. One nice way to draw transparent meshes is with a shader that changes
color based on the angle between the viewing direction and the surface
normal at any point on the surface. It should be easy for us to implement a
visual filter to achieve this. Here's an example of the effect (not made by
vispy):

**Comment by JPFrancoia** [comment]
Thank you all for your answers.

So I did some tests:

@djhoese :

> You may have luck playing with the GL state (my_vis.set_gl_state('translucent', blend=True) and/or other GL state options (depth_test...probably not). This may also help: https://www.khronos.org/opengl/wiki/Transparency_Sorting

Actually the only test that helped was ```depth_test```. By using:

```python
 mesh.set_gl_state('translucent', depth_test=False)
```

I get a more suitable result:

![screen](https://user-images.githubusercontent.com/2399090/40278134-561314b4-5c23-11e8-9f23-fbce9e9b1cae.png)

I could live with that, but it's still not perfect.

>So I think what is happening is that vispy or opengl is drawing each of the STLs shapes and each face of those "wedges" is having an additive effect so the faces that are next to each other appear less transparent (more opaque) which produces weird results.

Do you have any idea how I could disable these additive effects ?

@campagnola :

1: yes, thank you. They disable the shininess for the 3 first meshes I think ? I now draw my object without shininess, and it doesn't affect the transparency. So it's not the lighting that produces my unexpected results.

2: I tried ```visual.set_gl_state('additive')``` on my mesh. My mesh simply disappeared :/

3: it seems a bit complicated but why not. Did you forget to attach the link ?
