### ISSUE TITLE
Visualization for Point cloud series

### ISSUE THREAD

**Issue by sanketgujar** [vispy/vispy#1485]
How can I visualize a series of point cloud from a rosbag in vispy?

**Comment by djhoese** [comment]
I'm not familiar with what format that is although a quick google search shows me a little information. You probably want to start with a `MarkersVisual`. We have many example scripts that can give you ideas for how to do things: https://github.com/vispy/vispy/tree/master/examples

As far as reading the format, we don't provide anything to read rosbag but it looks like the tools come with a python library. Once the data is in a numpy array then any appropriate vispy Visual should be able to load the data.

**Comment by sanketgujar** [comment]
Thanks for the help. I am using the script in the above examples to visualize point clouds, Actually I wanted to know what changes should I make to the   https://github.com/vispy/vispy/blob/master/examples/basics/scene/point_cloud.py. script to visualize temporal point cloud arrays.

**Comment by djhoese** [comment]
@sanketgujar You would want to use a timer most likely and update the location of the points based on time. There are multiple ways to do it and there are many examples showing how to use a Timer and/or customizing a Visual/shader. It really depends what your data looks like, what your end goal is, and how you want to handle it. If you have more specific questions we can try to help.

**Comment by sanketgujar** [comment]
Thanks for the help :)

**Comment by brunoeducsantos** [comment]
@sanketgujar  Did you manage to do it?
