### ISSUE TITLE
python setup.py crash

### ISSUE THREAD

**Issue by raphaelvallat** [vispy/vispy#1490]
Hello,
I am trying to install the latest version of VisPy using `git clone` and `python setup.py install`. However, I am getting the following error:
 
![image](https://user-images.githubusercontent.com/25703792/42232862-a7efa506-7ea4-11e8-8718-695635e66ee1.png)

I have used previous version of VisPy (0.5.2 and 0.5.3) and they worked perfectly fine.
I am using Python 3.6.5 on Windows 10 64-bit with Anaconda (conda version 4.5.4, conda-build version 3.10.2).

Thank you,
Raphael

**Comment by djhoese** [comment]
Very interesting. We do test vispy on appveyor using anaconda so I would expect this to work. Do you know if you have cython and setuptools installed?

**Comment by codypiersall** [comment]
Looks like this is a problem building the extension with cygwin, as opposed to using Visual Studio.  I'm guessing the appveyor build uses VS.

**Comment by raphaelvallat** [comment]
Thank both of you for your prompt answers. I just upgraded `cython` and `setuptools` using pip but the bug is still there. @codypiersall How can I force the build with VS then?

**Comment by kmuehlbauer** [comment]
@raphaelvallat Is this still an issue for you? Did you work around it somehow?

**Comment by raphaelvallat** [comment]
Hi @kmuehlbauer, I am using the stable version 0.5.3 for now, which works just fine, so no, it's not an issue anymore. Thanks

**Comment by kmuehlbauer** [comment]
@raphaelvallat Thanks for coming back. I'm closing this. Please reopen, when needed.
