### ISSUE TITLE
Vispy Plot and Scene not using GPU 

### ISSUE THREAD

**Issue by FrancescoFFA** [vispy/vispy#1493]
Hello everyone, aware that there have already been discussions about the slow responsiveness of scene and plot modules, I would like to propose again this subject from another point of view.
Recently I ran into the aforementioned problem when, moving from matplotlib, I sadly noted the same (or even worse) slowness in vispy when managing thousands (or even millions) of curves within a plot with axes. Beside not figuring out how to plot multiple lines in one shot to optimize the data loading time, I noted that the plot managing and rendering is always pushing the CPUs to high usages, while the GPU is basically doing nothing. Is this something done on purpose or a known problem?

Best regards,
Francesco

**Comment by yhql** [comment]
Hi, I made a gist to try and circumvent the problem : https://gist.github.com/yhql/70c3e59019cb73ec83870e946166b95f

One problem is it's not super easy to pick a color for independent lines from there, but feasible nonetheless.

**Comment by queenish001** [comment]
@FrancescoFFA I hope your query is resolved, Can this issue be closed?
