### ISSUE TITLE
legend support for vispy plot?

### ISSUE THREAD

**Issue by neurochen** [vispy/vispy#1497]
Hi, I am very much amazed by vispy project. I always use it in my UI now. I am wondering if there is a plan to support legends as well, which could make the graph much more clear. Thanks.

Right now, I always use colors to differentiate lines int he same plot, with a sort of legend with colored texts.

**Comment by djhoese** [comment]
The core developers have no immediate plans to add legend functionality but are definitely not against it if someone wants to try to add it. We can try to provide whatever guidance is needed. The plotting API may be a focus in the future, but we are currently working on improving performance and compatibility of vispy.

**Comment by neurochen** [comment]
It sounds reasonable. Performance and compatibility are definitely more important. Sorry that I am now busy with another project, although adding support for legends seems quite interesting to me.
