### ISSUE TITLE
Migrate from cassowary to kiwisolver

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1500]
As discussed in #1498 there were some performance issues discovered that were reduced/mitigated by reducing the number of times cassowary needed to be involved with solving where widgets/plots should show up on the canvas. The performance issues seemed to be related to a memory leak inside cassowary. As far as I know cassowary is only used in vispy in the plotting API (@kmuehlbauer correct me if I'm wrong). Cassowary is also embedded/bundled in the vispy package.

@codypiersall pointed out the kiwi (kiwisolver) library which @MatthieuDartiailh is one of the maintainers of. Kiwi is faster, uses less memory, and is used by popular libraries like matplotlib.

My question for @MatthieuDartiailh: how much effort would be involved in migrating to kiwi for vispy (either by you, me, or some other vispy user/developer)?

**Comment by djhoese** [comment]
https://pypi.org/project/kiwisolver/

**Comment by larsoner** [comment]
The VisPy constraints are pretty simple so I hope the effort required is small. +1 for migrating

**Comment by djhoese** [comment]
I think it mainly depends on how the interfaces change between the two.

**Comment by MatthieuDartiailh** [comment]
Could you point me at the relevant files in the vispy codebase ? I will give a look at much work would be needed.

**Comment by djhoese** [comment]
@MatthieuDartiailh the only use of the solver is here in the grid module: https://github.com/vispy/vispy/blob/c1fd20ba5a8976edceee9b0838502054079d6791/vispy/scene/widgets/grid.py#L382

The other mention is here, but I think this is still used in the grid.py module: https://github.com/vispy/vispy/blob/a6ec64bb7b56739b463e3c16245a31940ca4f5f7/vispy/scene/widgets/widget.py#L72

**Comment by djhoese** [comment]
Just realized the PR for this was never linked: https://github.com/vispy/vispy/pull/1501

**Comment by almarklein** [comment]
Closed by #1501
