### ISSUE TITLE
No module named 'vispy.visuals.text._sdf_cpu'

### ISSUE THREAD

**Issue by lonnibesancon** [vispy/vispy#1506]
I do manage to get some of the examples working but not all of them. For instances, all the examples in the collections folder do not run and I get the following traceback when trying to run chloropleth.py for instance:

Traceback (most recent call last):
```
  File "/Users/xxx/Documents/vispy-master/examples/collections/chloropleth.py", line 11, in <module>
    from vispy.visuals.collections import PathCollection, PolygonCollection
  File "/Users/xxx/Documents/vispy-master/vispy/visuals/__init__.py", line 14, in <module>
    from .axis import AxisVisual  # noqa
  File "/Users/xxx/Documents/vispy-master/vispy/visuals/axis.py", line 13, in <module>
    from .text import TextVisual
  File "/Users/xxx/Documents/vispy-master/vispy/visuals/text/__init__.py", line 7, in <module>
    from .text import TextVisual  # noqa
  File "/Users/xxx/Documents/vispy-master/vispy/visuals/text/text.py", line 18, in <module>
    from ._sdf_cpu import _calc_distance_field
ModuleNotFoundError: No module named 'vispy.visuals.text._sdf_cpu'
```

Here is the print from vispy.sys_info():

```
Platform: Darwin-17.6.0-x86_64-i386-64bit
Python:   3.7.0 (default, Jun 28 2018, 07:39:16)  [Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy:    1.15.0
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.9.2', '5.9.6')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None
GL version:  '2.1 ATI-1.66.42'
MAX_TEXTURE_SIZE: 16384
[I removed the extensions part]
```

You can also find this question on stackoverflow here: https://stackoverflow.com/questions/51893868/vispy-no-module-named-vispy-visuals-text-sdf-cpu

**Comment by lonnibesancon** [comment]
I used Conda and did: 

- ` conda install numpy pyqt`
- `pip install Cython`
- `pip install git+https://github.com/vispy/vispy.git`

**Comment by djhoese** [comment]
Your error message shows a different path. Your error message shows `/Users/xxx/Documents/vispy-master/vispy/visuals/text/text.py`. Is it possible you had vispy installed from this local directory at some point? You may have to make sure you uninstall this installed version first.

If the version was installed with that pip command you listed above then it would most likely show a `site-packages` location in the error message.

**Comment by lonnibesancon** [comment]
I mean I downloaded the git repo to have the examples and imported it in PyCharm so that I could try them. I don't think I installed from that downloaded directory.

**Comment by djhoese** [comment]
Are you running python (`python examples/...`) from that directory? If you are then when python tries to import vispy it will look in the current directory first and find that one. That's my only other guess so far.

**Comment by lonnibesancon** [comment]
Yes I am trying to run from that directory indeed. So how should I proceed to avoid that?

**Comment by djhoese** [comment]
You could change in to the examples directory `cd examples` and then run the examples from there. Or run from any other directory that isn't the root of the repository.

**Comment by djhoese** [comment]
@lonnibesancon Did that work?

**Comment by lonnibesancon** [comment]
@djhoese yes it did, sorry for the late reply and thanks for the help :)

**Comment by Bhargav-Ravinuthala** [comment]
pip install vispy

**Comment by djhoese** [comment]
@Bhargav-Ravinuthala If you need installation help, please create a new issue.
