### ISSUE TITLE
tkinter integration?

### ISSUE THREAD

**Issue by Harvie** [vispy/vispy#1507]
Hello. I have python UI application written using tkinter and i want to replace tkinter canvas using vispy to get 3D acceleration. Is that possible?

Thanks.

**Comment by djhoese** [comment]
As far as I know there is no tkinter backend for vispy. It is possible to add it, but won't be simple. @larsoner are you aware of any work on a tkinter backend?

**Comment by larsoner** [comment]
I don't think anyone has worked on it.

**Comment by Harvie** [comment]
I am working on bCNC (https://github.com/vlachoudis/bCNC) and it renders 3D lines (CNC toolpaths) using Tkinter Canvas, it's slow and the view can't be rotated in realtime using mouse. I was thinking that Vispy might be nice solution, but i have no idea, how to embed it into Tkinter GUI of bCNC :-(

**Comment by almarklein** [comment]
Closed by #1918
