### ISSUE TITLE
set xlim and ylim for plot() in vispy.plot, or use plot(data=, x=, y=) 

### ISSUE THREAD

**Issue by 229668880** [vispy/vispy#1519]
Hi, I am using plot(), image() with vispy.plot. Is there a method to set xlim and ylim for them? or use plot(data=, x=, y=) 

Thanks.

**Comment by kmuehlbauer** [comment]
@229668880 You can change the camera range like this:

```python
plot.camera.set_range((xmin, xmax), (ymin, ymax))
```

**Comment by kmuehlbauer** [comment]
@229668880 Please report back, if that helps. For questions like this, please use our [gitter channel](https://gitter.im/vispy/vispy).

**Comment by 229668880** [comment]
It doesn't work.
My codes:
import vispy.plot as plt
import vispy.scene
fig=plt.Fig()
ax=fig[0,0]
ax.plot(randn(10))  # the corresponding xdata will be (0,9)
line=scene.LinePlot(randn(10))
ax.view.add(line)  # I want plot the data against (10,20)

Neither ax.camera.set_range nor line.camera.set-range work.

**Comment by 229668880** [comment]
If I want to  ax.image(randn(100)) againt xdata=arange(200,300), not the default (0,100)

**Comment by kmuehlbauer** [comment]
@229668880 This is not implemented yet. But you can adapt the `transform ` of image to suit your needs.
```python
from vispy.visuals.transforms import STTransform
img = ax.image(...)
img.transform = STTTransform(translate=[200, 300, 0])
```

**Comment by 229668880** [comment]
It works now. Thank you.

**Comment by kmuehlbauer** [comment]
@229668880 Glad it works now. I'll close this issue for now, reopen if appropriate. If you like to see this in the vispy codebase, PR is always welcome.
