### ISSUE TITLE
Most provided filters cannot be detached.

### ISSUE THREAD

**Issue by kne42** [vispy/vispy#1522]
# Description
Most filters provided by `vispy` itself cannot be detached due to a missing `_detach` method. This issue is meant to collect references to all such filters and document related issues.

# References
## [color.py](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/color.py)
[IsolineFilter](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/color.py#L11)
[Alpha](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/color.py#L113) (see #1434)
[ColorFilter](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/color.py#L137)
[ZColormapFilter](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/color.py#L161)

## [material.py](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/material.py)
What is even going on here? On [line 15](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/material.py#L15), it attempts to import from a non-existent module.

## [picking.py](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/picking.py)
[PickingFilter](https://github.com/vispy/vispy/blob/master/vispy/visuals/filters/picking.py#L10)

**Comment by kne42** [comment]
@djhoese

> a base class for all filters that actually gets used and implements a basic _attach and _detach

I was thinking this as well. I would additionally like to subclass from `Frozen` to prevent future errors like the one in #1518. I will work on this tonight and/or tomorrow.

**Comment by djhoese** [comment]
Makes sense. My only problem with using `Frozen` is that deep down I was hoping to get rid of `Frozen` from Visuals in the future. It feels very un-pythonic to me but I suppose with the complexity of these classes it is needed...fine 😫

**Comment by kne42** [comment]
@djhoese You're right, it is rather un-Pythonic. However, I just remembered the Pythonic equivalent to this which is accomplished by defining [`__slots__`](http://book.pythontips.com/en/latest/__slots__magic.html):

```python
In [1]: class foo(object):
   ...:     __slots__ = ('bar',)
   ...:     

In [2]: a = foo()

In [3]: a.bar = 42

In [4]: a.baz = 'SPAM'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-fcd88f8527c9> in <module>()
----> 1 a.baz = 'SPAM'

AttributeError: 'foo' object has no attribute 'baz'

In [5]: class foo_subclass(foo):
   ...:     __slots__ = ('baz',)
   ...:     

In [6]: b = foo_subclass()

In [7]: b.bar = 42

In [8]: b.baz = 'SPAM'

In [9]: b.foo = 'aliiiens'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-0e0c8dbed872> in <module>()
----> 1 b.foo = 'aliiiens'

AttributeError: 'foo_subclass' object has no attribute 'foo'
```

This additionally has the benefit of taking up less RAM.

**Comment by djhoese** [comment]
I like it...but at the same time it makes it harder for users to add their own "stuff" to a visual in their own application. Usually this means user are doing something hacky, but we don't want to break someones entire application. Maybe it will just have to be something for us to keep in mind. @larsoner @kmuehlbauer FYI ^

**Comment by kmuehlbauer** [comment]
@kne42 Yes, I tested @JPFrancoia example #1434, but didn't follow up on that. Big thanks for bringing this back and taking the lead with #1523.

We should discuss the `Frozen` vs `__slots__` stuff in a separate issue. Might need to get insight from the original authors.

**Comment by kne42** [comment]
I will note that classes defined with `__slots__` will not work when used as a base with any other base:
```python
class Subclass(SlotsClass, AnotherSlotsClass):
    ...
```
will raise a `TypeError` for having two superclasses with `__slots__` defined and
```python
class Subclass(SlotsClass, NotASlotsClass):
    ...
```
will allow arbitrary attribute setting again (since `NotASlotsClass` has a `__dict__`)

A `__slots__`-like system can however work with custom metaclasses but will not have the same speed benefits and will run into trouble when another metaclass is used.

**Comment by djhoese** [comment]
Also an only slightly-off-topic topic: In the future of vispy I would like to remove the need for the `Node` or rather `VisualNode` class. It is annoying to me that the logic of the VisualNode can't be part of the base Visual class and either disabled or go unused. Having to defined a Visual class twice (create_visual_node) is annoying IMO. At the same time, I don't want to have to refactor all of that. 😉
