### ISSUE TITLE
AttributeError: 'VispyWidget' object has no attribute 'on_msg'

### ISSUE THREAD

**Issue by yileichen123** [vispy/vispy#1530]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-7c5b6e06e2a7> in <module>()
----> 1 c.show()
      2 app.run();

f:\anaconda3\vispy-master\vispy\app\canvas.py in show(self, visible, run)
    427             Run the backend event loop.
    428         """
--> 429         self._backend._vispy_set_visible(visible)
    430         if run:
    431             self.app.run()

f:\anaconda3\vispy-master\vispy\app\backends\_ipynb_webgl.py in _vispy_set_visible(self, visible)
    206             return
    207         if self._widget is None:
--> 208             self._widget = VispyWidget()
    209             self._widget.set_canvas(self._vispy_canvas)
    210         display(self._widget)

f:\anaconda3\vispy-master\vispy\app\backends\ipython\_widget.py in __init__(self, **kwargs)
     60     def __init__(self, **kwargs):
     61         super(VispyWidget, self).__init__(**kwargs)
---> 62         self.on_msg(self.events_received)
     63         self.canvas = None
     64         self.canvas_backend = None

AttributeError: 'VispyWidget' object has no attribute 'on_msg'

**Comment by djhoese** [comment]
Could you please provide more information? What code are you running that generates this error message? How have you divided up your notebook cells (I'm guessing you are using a notebook given the backend module mentioned in the traceback)?

There is a chance that the current vispy master is no longer compatible with current notebook. There were already limitations and notebook development (specifically ipywidgets) has been moving very fast over the last 6-12 months. Try putting everything in one cell in the notebook as far as vispy is concerned and try again. The canvas instance may need to be initialized/created and shown in the same cell.

**Comment by queenish001** [comment]
@yileichen123

**Comment by djhoese** [comment]
The old webgl backend is no longer supported and is been replaced by the jupyter_rfb backend.
