### ISSUE TITLE
Shader Compilaton Error, GLSL Version 120 not Supported

### ISSUE THREAD

**Issue by Paraphase** [vispy/vispy#1532]
Hi everyone,

When I run some examples, for example examples/basic/scene/cube.py or point_cloud.py, I get the Error Message:

RuntimeError: Shader compilation error in vertex shader:
    on line 1: error: GLSL 1.20 is not supported. Supported versions are: 1.00 ES
      #version 120

The Complete Error Message is inside the Attachement
I'm trying to get vispy running on a RaspBerry PI 3B+ with RaspBian and PyQt5 as Backend.
I'm almost sure PyQt is Working fine because i'm able to create Windows etc in Pure Qt Code.
The OpenGL python module is installed Too, with the ES1-3 Versions, vispy just doesn't "see" it, is my guess..

I'm a total newby to PyQt5/VisPy so i'd be glad, if someone could help me solve the issue.
Thanks for any Help 
Joel

[Full Error Message.txt](https://github.com/vispy/vispy/files/2445934/Full.Error.Message.txt)

**Comment by djhoese** [comment]
@kmuehlbauer Has the most experience with vispy on rpi that I know of. @kmuehlbauer Any ideas?

**Comment by kmuehlbauer** [comment]
@Paraphase I see you use berryconda. I contacted the maintainer of berryconda a while ago concerning OpenGL/pyopengl/pyqt on raspberry. I remember I had issues too but finally managed to get vispy to run on raspberry. Digging up the issue now.

**Comment by kmuehlbauer** [comment]
https://github.com/jjhelmus/berryconda/issues/15

**Comment by kmuehlbauer** [comment]
Unfortunately I did not pursue this further because of lack of time. But I can assist with debugging when I find the time.

**Comment by Paraphase** [comment]
@kmuehlbauer yes i am trying to use vispy in a Berryconda Environment. 
Thanks for the references, i'll have a look at it

**Comment by kmuehlbauer** [comment]
@Paraphase Found my raspy **and** the fitting SD-Card. Got it to work. Here are my findings so far:

This [gloo example](https://github.com/vispy/vispy/blob/master/examples/basics/gloo/rotate_cube.py) works nice. The [mentioned scene example](https://github.com/vispy/vispy/blob/master/examples/basics/scene/cube.py) runs also, but the quality is bad (cube edges not "nice").

Do not get any error besides the well known, `libGL error MESA-LOADER failed to retrieve device information`.

I'll try investigate how I installed everything, but I can say that I `conda-build` the `pyqt` recipe (pyqt 4.11.4).

**Comment by kmuehlbauer** [comment]
@Paraphase I also found this issue again with more details (at the end): https://github.com/vispy/vispy/issues/495

**Comment by kmuehlbauer** [comment]
@Paraphase I have good news, ehm, bad news. Using a self compiled `PyQt5` (via `conda-build`) I get a similar error like in your error message. 

`TypeError: '<' not supported between instances of 'str' and 'int'`

This does not happen with my `PyQt4` (via `conda-build`).

@djhoese Does that ring a bell? It seems that there is a problem with the version comparison in `glir.py`. Any ideas? I think it has something to do with the backend. Something which works on qt4 and not on qt5.

**Comment by kmuehlbauer** [comment]
@djhoese Thanks for the other branch, but the error stays the same. I suspect some problem with Mesa reporting the version, which is somehow working on qt4.

**Comment by djhoese** [comment]
Note a similar issue with the mesa backend: #1517

**Comment by Paraphase** [comment]
@kmuehlbauer @djhoese
Thanks for your invesgigation in this issue, i will try the installation with pyqt4

**Comment by kmuehlbauer** [comment]
@Paraphase have a look also here: https://github.com/vispy/vispy-website/issues/16

It would be nice, if you write down some notes while doing the installation steps, so that we can probably finetune the installation howto mentioned in the above link. Also problems you encounter and resolve during the procedure would be good to know. Thanks!

**Comment by kmuehlbauer** [comment]
@Paraphase We have installation instructions for raspberry online http://vispy.org/raspberry.html. Please try this way, which worked for me.

Please reopen, if necessary.
