### ISSUE TITLE
GLFW glfw.glfwSetWindowTitle issue

### ISSUE THREAD

**Issue by Gotham13121997** [vispy/vispy#1533]
Hello there, 
I am using a library https://github.com/p5py/p5 which is dependent on vispy. When passing a new title as str to glfw.glfwSetWindowTitle only the first letter of the passed string is coming up as the changed title. I was able to find a workaround to this by passing the title by encoding it to utf-8 in
https://github.com/vispy/vispy/blob/0ff2bacef0ec941c039708935a4cbd694ecf02ab/vispy/app/backends/_glfw.py#L327
 like the implementation in
https://github.com/vispy/vispy/blob/0ff2bacef0ec941c039708935a4cbd694ecf02ab/vispy/ext/glfw.py#L483

Now I am confused wether to make a pull request to p5py or vispy about this issue as p5py is accepting title as str. 
Thank You

**Comment by djhoese** [comment]
@Gotham13121997 Thanks for the issue (and the pull request). What version of python are you using? I'm wondering if this is some python 2/3 incompatibility. I would think that glfw would handle this directly.

@larsoner I recall you having a little more experience with the glfw backend than me. Thoughts?

**Comment by Gotham13121997** [comment]
@djhoese I am on python 3.6. O.S is ubuntu 18.04
