### ISSUE TITLE
Create TextVisual separate from camera transforms

### ISSUE THREAD

**Issue by cimbi** [vispy/vispy#1551]
I want to create a visual of text within a rectangle so that the text does not become invisible when moved over the background with the same color. This is easy but I cannot figure out how to detach the rectangle visual from scaling. So I basically want to be able to scale the scene but the rectangle visual should not be scaled and stay just around the text.

This becomes even more complicated when for example arcball camera is used. Because then the rectangle turns.

I presume I will have play with the transform system but I don't know where to begin. Any ideas appreciated.

**Comment by djhoese** [comment]
I feel like I remember @kmuehlbauer or @larsoner helping someone else with this recently. There may even be another issue on this topic. I've never done this myself so not sure how much help I can be. You are correct that the transforms are the part that need to be considered. I feel like there is a semi-builtin way to do this, but can't remember and can't find the related issues right now. Hopefully one of the other devs mentioned here has an idea.

**Comment by kmuehlbauer** [comment]
@cimbi I can't remember adhoc, if this was discussed before. 

What comes to mind is the AxisWidget which creates an axis with labels. These text labels keep their sizes regardless of the zoom factor of the data. Maybe we can get some inspiration from that. I'll try to dig a bit deeper in the issues.

**Comment by kmuehlbauer** [comment]
@cimbi 

I adapted the (volume example](https://github.com/vispy/vispy/blob/master/examples/basics/scene/volume.py). Is this what you want to achieve?

The main difference between the `Sphere`  on one side and the `Text` and `Rectangle` on the other side is `Sphere`'s parent is `view.scene` whereas the others parent is `view`.

```python
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# -----------------------------------------------------------------------------

"""
Example text rendering in rectangle

Controls:

* 1  - toggle camera between first person (fly), regular 3D (turntable) and
       arcball
* 0  - reset cameras

With fly camera:

* WASD or arrow keys - move around
* SPACE - brake
* FC - move up-down
* IJKL or mouse - look around
"""

from vispy import app, scene
from vispy.scene.visuals import Rectangle, Sphere, Text
from vispy.visuals.transforms import STTransform

# Prepare canvas
canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), show=True)
canvas.measure_fps()

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

sphere = Sphere(radius=1, method='ico', parent=view.scene,
                edge_color='black')

rect = Rectangle(center=(0, 0), width=6, height=1,
                 color='lightblue', border_color='blue',
                 radius=0.02, parent=view)
# TextVisual
text = Text('Text in rectangle (18 pt)', parent=view, color='black')
text.font_size = 18

# Transform
s = STTransform(translate=(400, 400), scale=(50, 50, 50, 1))
affine = s.as_matrix()
rect.transform = affine
text.transform = affine


# Create three cameras (Fly, Turntable and Arcball)
fov = 60.
cam1 = scene.cameras.FlyCamera(parent=view.scene, fov=fov, name='Fly')
cam2 = scene.cameras.TurntableCamera(parent=view.scene, fov=fov,
                                     name='Turntable')
cam3 = scene.cameras.ArcballCamera(parent=view.scene, fov=fov, name='Arcball')
view.camera = cam2  # Select turntable at first

# Implement key presses
@canvas.events.key_press.connect
def on_key_press(event):
    global opaque_cmap, translucent_cmap
    if event.text == '1':
        cam_toggle = {cam1: cam2, cam2: cam3, cam3: cam1}
        view.camera = cam_toggle.get(view.camera, cam2)
        print(view.camera.name + ' camera')
    elif event.text == '0':
        cam1.set_range()
        cam3.set_range()


if __name__ == '__main__':
    print(__doc__)
    app.run()
```

**Comment by cimbi** [comment]
Yes, exactly. Thanks @kmuehlbauer!
