### ISSUE TITLE
transparency when using line width=0 in plot

### ISSUE THREAD

**Issue by cosmoni** [vispy/vispy#1552]
when running the vispy/examples/basics/plotting/scatter_histogram.py example the window becomes transparent in high point density areas and other windows and the desktop show through. this problem goes away when you set line width to anything but 0.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
This was likely a PyQt5 backend issue that may have been fixed. Given the age of this issue (sorry for no response), I'm going to close this. If this is still an problem please create a new issue.
