### ISSUE TITLE
Rendering of 2d images using viridis on GPU does not work (also cubehelix)

### ISSUE THREAD

**Issue by EricThomson** [vispy/vispy#1560]
I'm flagging this for viridis more than cubehelix because viridis is the default for matplotlib, and is fairly ubiquitous, but I tried it for all built-in colormaps and found the same thing for cubehelix as well. When I render 2d data as an image in vispy, and set viridis as the cmap (and use my GPU) it comes out extremely sparse-looking. As you zoom in you see that the data is there, it is just not rendered correctly. The other colormaps work fine (except cubehelix), and it works fine with rgb data (an nxmx3 array).

Code to reproduce problem:
```
import numpy as np
from vispy import scene
data = np.array(np.random.rand(500,500) * 255, dtype=np.uint8)    
canvas = scene.SceneCanvas(keys='interactive', bgcolor = 'w')
view = canvas.central_widget.add_view()
img = scene.visuals.Image(data, interpolation='nearest', cmap= 'viridis',
                            parent=view.scene, method='subdivide')
view.camera = scene.PanZoomCamera(aspect=1)
view.camera.flip = (0, 1, 0)
view.camera.set_range()
view.camera.zoom(1, center = (700, 400))
canvas.title = 'Viridis image'
canvas.show()
```
Screenshot:
![gnarly_viridis](https://user-images.githubusercontent.com/6643322/50745284-527c8f80-11f7-11e9-9f59-b358cf9e3143.png)

If you do it with pseudo-rgb data, it looks fine (e.g., replace (500,500) above with (500,500,3).

I poked around in vispy.color.colormap.py and the viridis map starts on line 701: based on the comments there, it clearly has had a tough life, so I'm not sure if this is a duplicate of one of those issues, or a completely new issue.

I am in Windows 10, and this happens in Python 3.7 and Python 3.6, and vispy 0.5.2 and 0.5.3. If I do not use my GPU, this doesn't happen.

**Comment by hmaarrfk** [comment]
Right, launching vispy from spyder seems to force it to try to use jupyter notebooks as a backend.

I typically chagne my spyder configuration to use pyqt5 as the default rendering backend.

Glad to hear that this issue has been resolved!
