### ISSUE TITLE
After closing cube example, it still seems to be running in background

### ISSUE THREAD

**Issue by EricThomson** [vispy/vispy#1561]
I noticed this when things started to slow down as I worked longer and longer on my project. I can reproduce it with the `visuals.cube.py` example from the repository, slightly modified with a print statement to illustrate it. This example shows a rotating cube in the canvas, and when you close the canvas, it continues to print the statement from the `on_timer()` method:

```

import sys
from vispy import app, gloo
from vispy.visuals import CubeVisual, transforms


class Canvas(app.Canvas):
    def __init__(self):
        app.Canvas.__init__(self, 'Cube', keys='interactive',
                            size=(400, 400))

        self.cube = CubeVisual((1.0, 0.5, 0.25), color='red',
                               edge_color="k")
        self.theta = 0
        self.phi = 0
        self.counter = 0
        # Create a TransformSystem that will tell the visual how to draw
        self.cube_transform = transforms.MatrixTransform()
        self.cube.transform = self.cube_transform

        self._timer = app.Timer('auto', connect=self.on_timer, start=True)

        self.show()

    def on_resize(self, event):
        # Set canvas viewport and reconfigure visual transforms to match.
        vp = (0, 0, self.physical_size[0], self.physical_size[1])
        self.context.set_viewport(*vp)
        self.cube.transforms.configure(canvas=self, viewport=vp)

    def on_draw(self, event):
        gloo.set_viewport(0, 0, *self.physical_size)
        gloo.clear('white', depth=True)

        self.cube.draw()

    def on_timer(self, event):
        self.theta += .5
        self.phi += .5
        if self.counter == 500:
            print("don't mind me")
            self.counter = 0
        else:
            self.counter += 1
        self.cube_transform.reset()
        self.cube_transform.rotate(self.theta, (0, 0, 1))
        self.cube_transform.rotate(self.phi, (0, 1, 0))
        self.cube_transform.scale((100, 100, 0.001))
        self.cube_transform.translate((200, 200))
        self.update()

if __name__ == '__main__':
    win = Canvas()
    win.show()
    if sys.flags.interactive != 1:
        win.app.run()
```

This code is pretty much exactly the code from the repository, but with a print thrown in:    
https://github.com/vispy/vispy/blob/master/examples/basics/visuals/cube.py

I am in Windows 10, Python 3.7 (same happens in 3.6), working in iPython 7.2 (Conda). Using vispy 0.5.3.

**Comment by GuillaumeFavelier** [comment]
I tried your version of the script and I didnt reproduce the issue: when I closed the window, the "don't mind me" message stopped popping completely.
I have Ubuntu 18.04.1, Python 3.6 and vispy 0.6.0.

**Comment by djhoese** [comment]
@EricThomson If you have a chance to use the master branch to test this on your system that would be great. I can't seem to reproduce what you're seeing. I'm going to close this for now. If you still have this problem with vispy 0.6 we can reopen this.
