### ISSUE TITLE
How to surface plot with set of {x,y,z} points?

### ISSUE THREAD

**Issue by philCryoport** [vispy/vispy#1562]
Hi there,

I have a large set of {x,y,z} points (which I load into a pandas dataframe).  In order to get `matplotlib.plot_surface` to work, I:
```
###
# x, y via meshgrid for vectorized evaluation of
# 2 scalar/vector fields over 2-D grids, given
# one-dimensional coordinate arrays x1, x2,..., xn.
###
x1 = np.linspace(df['col1'].min(), df['col1'].max(), len(df['col1'].unique()))
y1 = np.linspace(df['col2'].min(), df['col2'].max(), len(df['col2'].unique()))
x2, y2 = np.meshgrid(x1, y1)

# Interpolate unstructured D-dimensional data.
z2 = griddata((df['col1'], df['col2']), df['col3'], (x2, y2), method='cubic')

# Ready to plot
fig = plt.figure()
ax = fig.gca(projection='3d')
surf = ax.plot_surface(x2, y2, z2, rstride=1, cstride=1, cmap=cm.RdYlGn_r,
                       linewidth=0, antialiased=False)
```
...and voila! I get a plot_surface.

If I want a tri_surface plot, I can:
```
x = np.asarray(df.iloc[:,0:1].values).squeeze()
y = np.asarray(df.iloc[:,1:2].values).squeeze()
z = np.asarray(df.iloc[:,2:3].values).squeeze()
trisurf_fig = plt.figure()
trisurf_ax = trisurf_fig.gca(projection='3d')

trisurf_plot = trisurf_ax.plot_trisurf(x, y, z,cmap=cm.RdYlGn_r, linewidth=0.2, antialiased=True)
```

But with 330k data points...matplotlib is kinda slow.  But hey, I've got this midrange nVidia GPU on my laptop.  Let's try Vispy!

```
class SurfacePlotVisual(MeshVisual):
    """Displays a surface plot on a regular x,y grid

    Parameters
    ----------
    x : ndarray | None
        1D array of values specifying the x positions of vertices in the
        grid. If None, values will be assumed to be integers.
    y : ndarray | None
        1D array of values specifying the x positions of vertices in the
        grid. If None, values will be assumed to be integers.
    z : ndarray
        2D array of height values for each grid vertex.
```

So I get I'll use:
```
x = np.asarray(df.iloc[:,0:1].values).squeeze()
y = np.asarray(df.iloc[:,1:2].values).squeeze()
```

But what should I be showing for a "2D array of height values for each grid vertex."???

Do I just turn my 1D `z` array into a set of {z1,z1},{z2,z2}, etc.?

**Comment by kmuehlbauer** [comment]
@philCryoport AFAIU, you would need your data in a regular grid, which can be described via a 1D X-array and 1D Y-array. Same logic as you do in your first example (x1, x1).

So for plotting you would also need the 2D Z-array (z2 in your case). With this you should get SurfacePlotVisual running.

I'm not sure, if there is some GL-driven interpolation of irregular data available in VisPy.

**Comment by philCryoport** [comment]
@kmuehlbauer thank you for the tip!  I checked the shape of x,y,x1,y1,x2,y2, and various combinations of x*,y*->z* and found a matching set of arrays that worked :)

**Comment by kmuehlbauer** [comment]
@philCryoport Glad it works for you!
