### ISSUE TITLE
pyopengl issues

### ISSUE THREAD

**Issue by kmuehlbauer** [vispy/vispy#1568]
See for further discussion:

https://github.com/mcfletch/pyopengl/issues/19
https://github.com/conda-forge/pyopengl-feedstock/issues/16

First I installed pyopengl and pyopengl-accelerate from latest github master (https://github.com/mcfletch/pyopengl). Then I applied the following patch to vispy:
[FIX__pyopengl.patch.txt](https://github.com/vispy/vispy/files/2817944/FIX__pyopengl.patch.txt)

That fixed the pyopengl-tests. Did not had the time to dig further.

**Comment by djhoese** [comment]
Is pyopengl master needed for these to work? Or does 3.1.3b2 (current conda-forge version) work with this patch? Can you make a PR for this? In your patch you have some stuff commented out that looks the same as the "new" lines, is that true or am I missing something? Why isn't the `:length` truncation needed for the name variable?

@mcfletch, what do you think of this (if you understand our usage of the functions at all)?

**Comment by kmuehlbauer** [comment]
@djhoese I think so, I just had to install pyopengl-accelerate somehow.

**Comment by kmuehlbauer** [comment]
OK, I tracked that down to a stale redefinition of `glGetBufferParameteriv-wrapper` in [pyopengl](https://github.com/mcfletch/pyopengl/pull/20)(needs final confirmation from @mcfletch). The other problem is in vispy where `glGetActiveAttrib` needed some tweaking. Patches are PR'ed [here](#1569 ) and in [pyopengl](https://github.com/mcfletch/pyopengl/pull/20). I also tried to patch latest [conda-forge pyopengl](https://github.com/conda-forge/pyopengl-feedstock/pull/17) to get things along quickly, but this also has some issues.

**Comment by kmuehlbauer** [comment]
Damn, thought that this was easy. It's not! :disappointed: 

The change have to be done [here](https://github.com/vispy/vispy/blob/master/codegen/annotations.py#L415)!

**Comment by kmuehlbauer** [comment]
> Damn, thought that this was easy. It's not! disappointed
> 
> The changes have to be done [here](https://github.com/vispy/vispy/blob/master/codegen/annotations.py#L415)!

@larsoner Do you know when the [codegen-part](https://github.com/vispy/vispy/blob/master/codegen/annotations.py#L415) is executed?

**Comment by larsoner** [comment]
I think it gets run manually when updates are needed (rarely), but not sure

**Comment by mcfletch** [comment]
Hey folks, wondering if we ever came up with a test I could run that would reproduce the error? That is, I have vispy checked out, I've tried replicating the proximate error, and failed. Is there a test case (from vispy or stand alone) I can run to isolate the error. The change/patch proposed for PyOpenGL requires that we remove a wrapper feature (namely generating the output buffer if it's not passed in), so I'm somewhat hesitant to do that.

The commit https://github.com/mcfletch/pyopengl/commit/f4d93b8bc5b7da500d09b62fdb896aa4085652a4 tries to create test cases for the function, but they seem to work correctly on the `v3.1.4` branch.

**Comment by kmuehlbauer** [comment]
@mcfletch Thanks for coming back to this.

So removing the redefinition as in my PullRequest at [pyopengl](https://github.com/mcfletch/pyopengl/issues/19) is not the way to go? 

On [line 56](https://github.com/mcfletch/pyopengl/blob/bf11e7e59bff4a57dffbe79e1b27dac5a09166fc/OpenGL/GL/VERSION/GL_1_5.py#L56) `glGetBufferParameteriv` is defined. There is no use of it until on [line 127](https://github.com/mcfletch/pyopengl/blob/bf11e7e59bff4a57dffbe79e1b27dac5a09166fc/OpenGL/GL/VERSION/GL_1_5.py#L127) it get's redefined. Right before the function it is used inside.

From my understanding either the first definition is not needed or the second definition. As the second definition is the used one, I just thought that I might try with the first definition of that wrapper. And it solved the problem. With this I followed that the second definition might be just a leftover or stale thing. Hopefully you can shed a bit more light on that. Thanks!

**Comment by kmuehlbauer** [comment]
@mcfletch Just had a look on `v3.1.4` branch. There you have incorporated my [PR #19 ](https://github.com/mcfletch/pyopengl/issues/19) which removes the redefinition. So this will not be an issue any more.

So with 3.1.4 everything is OK. At vispy we have only to fix the changes not in our autogenerated files but in the codegen template-files.

Seems all good with pyopengl `3.1.4`

**Comment by mcfletch** [comment]
Huh, I didn't actually recalling integrating that pull request... okay, well, guess I'll move on then. Cheer.

**Comment by kmuehlbauer** [comment]
@mcfletch Yes, the PR is still pending, but in the `3.1.4` branch the proposed changes are applied.

**Comment by kmuehlbauer** [comment]
Finally solved in #1306.
