### ISSUE TITLE
Implement mouse arcball for 3D interaction

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#157]
Would make 3D examples much more convenient.

Renaud Blanch has a nice implementation using quaternions:

https://bitbucket.org/rndblnch/opengl-programmable/src/tip/linalg/
https://bitbucket.org/rndblnch/opengl-programmable/src/tip/09-gles2.py#cl-333

**Comment by Eric89GXL** [comment]
@almarklein your cameras have this now, right?

**Comment by Eric89GXL** [comment]
Looked through the source code and answered my own question (no) -- sorry for the noise...

**Comment by Eric89GXL** [comment]
FYI the license on the code linked above appears to be GPLv3, so we'd need to ask relicensing permission

**Comment by rossant** [comment]
> FYI the license on the code linked above appears to be GPLv3, so we'd need to ask relicensing permission

cc @rndblnch

**Comment by rndblnch** [comment]
which license would suit your needs?

**Comment by Eric89GXL** [comment]
We use BSD

**Comment by rndblnch** [comment]
there you go, a dual license quaternion implementation in python :)

https://bitbucket.org/rndblnch/linalg/src

**Comment by almarklein** [comment]
Thanks @rndblnch !

I don't particularly like the Arcbal camera, but yes, we should add it to vispy. Note that we already have quaternions in `vispy.util.quaternion.Quaternion`, so it should be relatively easy to implement it.
