### ISSUE TITLE
Inconsistent imap coordinates

### ISSUE THREAD

**Issue by yhql** [vispy/vispy#1579]
Hi, I'm having trouble getting back coordinates of a click to match what is displayed on an axis.

Setup is roughly : 

```python
class plot:
    def __init__(self, curve):
        self.canvas = scene.SceneCanvas(keys='interactive' )

        self.grid = self.canvas.central_widget.add_grid(spacing=0)
        self.view = self.grid.add_view(row=0, col=1, camera='panzoom')

       self.line = scene.Line(curve, parent=self.view.scene)

        self.x_axis = scene.AxisWidget(orientation='bottom')
        self.y_axis = scene.AxisWidget(orientation='left')
        self.x_axis.stretch = (1, 0.1)
        self.y_axis.stretch = (0.1, 1)
        self.grid.add_widget(self.x_axis, row=1, col=1)
        self.grid.add_widget(self.y_axis, row=0, col=0)
        self.x_axis.link_view(self.view)
        self.y_axis.link_view(self.view)
```
and a mouse event handler like so 
```python
def on_mouse_release(self, event):
        x,y,_,_ = self.view.scene.transform.imap(event.pos)
        print(x,y)
```

When clicking on the canvas just above let's say the 9000 mark on the x-axis, the imap coordinates are something like 9090. The result gets closer to what the x-axis says it is when I zoom in.

Am I using the correct `imap` function to retrieve those coordinates ?

**Comment by djhoese** [comment]
I *think* (it's early here, need to wake up more) using `imap` the way you are is trying to convert screen pixel coordinates to scene coordinates (locations internal to the Scene canvas). You may need to use the `transforms` object (TransformSystem) to `get_transform()` to get one that represents "document" to axis "visual". You can find more information on this [here](https://github.com/vispy/vispy/blob/master/vispy/visuals/transforms/transform_system.py#L15). Something like:

```python
tr = self.x_axis.axis.transforms.get_transform('visual', 'document')
x, y, _, _ = tr.imap(event.pos)
```

This is just a guess. I may have some things wrong or backwards.

You may have also found a bug. I'm also not sure the transforms for the axes are meant to give you the data point from a screen coordinate. Let me know what you find.

**Comment by yhql** [comment]
Thanks for the tip. I tried the line you wrote which seems to be exactly what I need, but it gives :  
`x = 30.27`
when clicking somewhere with x= 0, and then when sliding the canvas to the right (moving x=0 to the right) I get
`x = 304`
So it doesn't seem to be really linked to the x_axis somehow.

**Comment by djhoese** [comment]
Ok so it seems the AxisWidget which is using the AxisVisual is doing some complicated things. You may have to dig in to the internal workings of this in this file: https://github.com/vispy/vispy/blob/master/vispy/scene/widgets/axis.py#L84

I'm not sure I fully understand how this is working or why your transform conversion isn't giving you what you expect. It is very possible that the screen pixel to data coordinate conversion isn't possible without copying some of the math of the AxisVisual. As far as I can tell the AxisWidget is the only thing updating the AxisVisual's position directly (see AxisWidget code). There may be some transforms involved here that aren't being included in the `transforms.get_transform` that you need or like I mentioned math that is done inside the AxisVisual...or something.

Sorry, I'm not familiar enough with the plotting API or the axis visual. @larsoner any ideas?

**Comment by yhql** [comment]
Ok thanks, I'll look around !

**Comment by danielhrisca** [comment]
Hello all,

I have the same problem trying to get the X value from a mouse click on a vispy.plot.Fig object. Is there any progress with debugging this problem?

**Comment by yhql** [comment]
Hi, sadly I could not find what's wrong.

**Comment by campagnola** [comment]
`view.scene.transform` only handles the mapping from the view's bounding box to the coordinate system inside the view. This does not take into account the offset between the view bounding rect and the canvas bounding rect (these differ due to the space taken up by the axes). 

The following transform should work:
```
    tr = canvas.scene.node_transform(view.scene)    
    x,y,_,_ = tr.map(event.pos)
```
There are examples of this in `examples/demo/scene/picking.py` and `examples/demo/scene/flow_lines.py`

**Comment by yhql** [comment]
It's working indeed. Thanks a lot !

Waiting on @danielhrisca 's confirmation and I'll close this issue.

**Comment by danielhrisca** [comment]
It is working !

@campagnola
thank you very much Luke!
