### ISSUE TITLE
RuntimeError: Could not import backend "Pyglet":

### ISSUE THREAD

**Issue by iris0329** [vispy/vispy#1580]
when running
`
app.use_app('pyglet')   # Set backend 
`
it shows 
```
  File "/data/iris/test/rendering/renderer.py", line 8, in <module>
    app.use_app('pyglet')   # Set backend pyqt5
  File "/usr/local/lib/python3.6/dist-packages/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/usr/local/lib/python3.6/dist-packages/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/usr/local/lib/python3.6/dist-packages/vispy/app/application.py", line 223, in _use
    raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
Cannot connect to "None"
```
version information:
- vispy
Requirement already satisfied: vispy in /usr/local/lib/python3.6/dist-packages (0.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.6/dist-packages (from vispy) (1.14.5)
- pyglet
Requirement already satisfied: pyglet in /usr/local/lib/python3.6/dist-packages (1.3.2)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyglet) (0.17.1)
- I run this code in pycharm

but if I use `pyqt5` as backend, this backend could be found,
I don't know why it happens, could anyone help me ? thanks for help !

**Comment by djhoese** [comment]
What does `print(vispy.sys_info())` give you? What happens if you run the code directly from the terminal and not through pycharm?

**Comment by iris0329** [comment]
1. print(vispy.sys_info())
```
>>> import vispy
>>> print(vispy.sys_info())
WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
2. if directly run from terminal, it shows same error

thanks !

**Comment by djhoese** [comment]
Are you running this on a virtual machine or docker container? It seems like you are missing a lot of OpenGL/GPU drivers or they are improperly installed or have become corrupt. Are you running this from an SSH connection (no display)? I'm not sure there is much I can help with until these are reinstalled.

I'm not sure I understand how you were able to get the PyQt5 backend to load properly, but can't get `sys_info` to print. You may want to try uninstalling and reinstalling pyglet.

**Comment by iris0329** [comment]
1. yes, I run this from a SHH connection, because  I run the code from server. 

2. also if I use `pyqt5`, it shows 
```
WARNING: could not connect to display 
WARNING: Could not load the Qt platform plugin "xcb" in "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), linuxfb (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), minimal (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), minimalegl (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), offscreen (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), xcb (from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms), eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

bash: line 1: 45373 Aborted                 (core dumped) env "PYTHONPATH"="/root/.pycharm_helpers/pycharm_matplotlib_backend:/data/lirong/ssd_6d" "PYCHARM_MATPLOTLIB_PORT"="36365" "JETBRAINS_REMOTE_RUN"="1" "PYTHONIOENCODING"="UTF-8" "PYCHARM_HOSTED"="1" "QT_QPA_PLATFORM_PLUGIN_PATH"="/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" "PYTHONUNBUFFERED"="1" /usr/bin/python3.6 -u /data/lirong/ssd_6d/run.py --network /data/lirong/ssd_6d/data/hinterstoisser/model/hinterstoisser_obj_01.pb --dataset /data/lirong/ssd_6d/data/
```
the problem is different, both are from my GPU driver ?

3. I have tried several time uninstalling and installing pyglet, but it doesn't work. I  install the pyglet by `pip install pyglet`
 
thanks for help !

**Comment by djhoese** [comment]
Someone can correct me if I'm wrong, but I don't think there is any way to use OpenGL over an SSH/X Window connection, at least not consistently. I don't have any experience with pyglet, but PyQt5 needs to be run on the local system using the local system's GPU. If you are running from a remote server there is only limited support for OpenGL (iirc) and that's if the server has the proper GPU drivers and a "real" GPU. Do you know if your server has a dedicated GPU and has been used for display functionality like you are trying for?

@larsoner @kmuehlbauer correct me if I'm wrong and am completely missing something.

**Comment by iris0329** [comment]
Ok, my remote server has four `GeForce GTX 1080` GPUs, I am nor sure they have this ability.
maybe the solution is to install an local GPU.
Thank you for your generosity.

**Comment by djhoese** [comment]
To clarify, OpenGL is not meant to run remote displays (running on your server, displaying on your local system). Typically, in my experience, GPUs on a remote server are meant for OpenCL/CUDA-type applications that are using the GPUs for computation resources, not display.

It is possible to do offscreen rendering with OpenGL/vispy in certain cases, but if you want to show an on-screen GL Canvas then you'll need a local GPU to run your code locally.

**Comment by iris0329** [comment]
yes, I solved this problem as your guide by using a local GPU computer. 
Thanks a lot !
