### ISSUE TITLE
Slowdown with Grid and AxisWidget + possible solution?

### ISSUE THREAD

**Issue by felixwoolford** [vispy/vispy#1588]
Hi!

I'm new to all this so sorry if this isn't the right way to go about things. I've encountered a slowdown issue when using Grid and Axis widgets. After a few minutes running a simple animation I begin to see a steady drop in fps.

Here's a fairly minimal example which produces the issue.

```
from vispy import app, scene
import numpy as np

class Test:
    def __init__(self):

        self.canvas = scene.SceneCanvas(keys = "interactive", show=True, bgcolor = 'b')
        self.canvas.measure_fps()
        self.grid = self.canvas.central_widget.add_grid(margin=10)

        self.yaxis = scene.AxisWidget(orientation='left',
                                 axis_label='Y Axis',
                                 axis_font_size=12,
                                 axis_label_margin=50,
                                 tick_label_margin=5)
        self.yaxis.width_max = 80
        self.grid.add_widget(self.yaxis, row=0, col=0)

        self.xaxis = scene.AxisWidget(orientation='bottom',
                                 axis_label='X Axis',
                                 axis_font_size=12,
                                 axis_label_margin=50,
                                 tick_label_margin=5)

        self.xaxis.height_max = 80
        self.grid.add_widget(self.xaxis, row=1, col=1)


        right_padding = self.grid.add_widget(row=1, col=2, row_span=1)
        right_padding.width_max = 50

        self.view = self.grid.add_view(row=0,col=1, border_color='white')
        self.view.camera = 'panzoom'
        self.view.camera.set_range(x=(-1,1),y=(-1,1))

        self.xaxis.link_view(self.view)
        self.yaxis.link_view(self.view)

        self.pos = np.zeros(2).reshape(1,2)
        self.m = scene.Markers(pos=self.pos,parent=self.view.scene)

        self.t = 0


    def update(self, ev):
        self.t = (self.t + 0.01) % (2*np.pi)
        self.pos[0,0] = np.sin(self.t*2)
        self.pos[0,1] = np.cos(self.t)
        self.m.set_data(pos = self.pos)


if __name__ == '__main__':
    test = Test()
    timer = app.Timer(interval=0, connect=test.update, start=True)
    app.run()
```

Now, I believe I have identified the source of the problem. In the `_update_child_widget_dim` function in `grid.py`, the loop which creates a new `Rect` is entered every time. I'm not 100% sure what is going on with this, but I do know that when that new Rect is created, the Axis recalculates all of its tick spacing etc, which seems to get pretty expensive if it has to happen every frame. If i make a change so that the loop is only entered if either of the two preceding if statements were true (which I think means the grid has been resized), this no longer happens and I no longer see the slowdown:

```
    def _update_child_widget_dim(self):
        # think in terms of (x, y). (row, col) makes code harder to read
        ymax, xmax = self.grid_size
        if ymax <= 0 or xmax <= 0:
            return

        rect = self.rect  # .padded(self.padding + self.margin)
        if rect.width <= 0 or rect.height <= 0:
            return
        if self._need_solver_recreate:
            self._need_solver_recreate = False
            self._recreate_solver()

        changed = False

        # we only need to remove and add the height and width constraints of
        # the solver if they are not the same as the current value
        if rect.height != self._var_h.value:
            changed = True
            if self._height_stay:
                self._solver.remove_constraint(self._height_stay)

            self._var_h.value = rect.height
            self._height_stay = self._solver.add_stay(self._var_h,
                                                      strength=STRONG)

        if rect.width != self._var_w.value:
            changed = True
            if self._width_stay:
                self._solver.remove_constraint(self._width_stay)

            self._var_w.value = rect.width
            self._width_stay = self._solver.add_stay(self._var_w,
                                                     strength=STRONG)

        if changed:

            value_vectorized = np.vectorize(lambda x: x.value)

            for (_, val) in self._grid_widgets.items():
                (row, col, rspan, cspan, widget) = val

                width = np.sum(value_vectorized(
                               self._width_grid[row][col:col+cspan]))
                height = np.sum(value_vectorized(
                                self._height_grid[col][row:row+rspan]))
                if col == 0:
                    x = 0
                else:
                    x = np.sum(value_vectorized(self._width_grid[row][0:col]))

                if row == 0:
                    y = 0
                else:
                    y = np.sum(value_vectorized(self._height_grid[col][0:row]))

                if isinstance(widget, ViewBox):
                    widget.rect = Rect(x, y, width, height)
                else:
                    widget.size = (width, height)
                    widget.pos = (x, y)
```

I haven't tested this solution too thoroughly but it works for me and thought I should share it here. I wonder if this may be the same issue as in #1498, but the discussion there is a bit over my head and I don't think a simple solution was mentioned.

**Comment by kmuehlbauer** [comment]
@foloxweilf Thanks for digging into this. In #1498 @mkubanski proposed a fix in the same subfunction. Could you both check, where the differences are? Also, there was a memory leak mentioned, did you ( @foloxweilf ) expirience that too?

**Comment by foloxweilf** [comment]
@kmuehlbauer Yes there is a minor memory leak, which is partially reduced by my proposed fix. There is also an increase in CPU load, which seems to be completely removed by my fix. If I run my test for 5 minutes, memory load goes from 73.7MB to 94.5MB and (perhaps more significantly) CPU load goes from 3% to 6%. With my proposed fix the memory load goes from 73.7MB to 81.4MB, and CPU load is steady at 3%.

My proposed fix is different from @mkubanski 's: As i understand it, that proposed fix changes the conditions of the two if statements:

```  
        # we only need to remove and add the height and width constraints of
        # the solver if they are not the same as the current value
        if abs(rect.height - self._var_h.value) > 1e-4:
            if self._height_stay:
                self._solver.remove_constraint(self._height_stay)

            self._var_h.value = rect.height
            self._height_stay = self._solver.add_stay(self._var_h,
                                                      strength=STRONG)

        if abs(rect.width - self._var_w.value) > 1e-4:
            if self._width_stay:
                self._solver.remove_constraint(self._width_stay)
```

whereas mine puts the for loop at inside a new if statement:

```

        changed = False

        # we only need to remove and add the height and width constraints of
        # the solver if they are not the same as the current value
        if rect.height != self._var_h.value:
            changed = True
            if self._height_stay:
                self._solver.remove_constraint(self._height_stay)

            self._var_h.value = rect.height
            self._height_stay = self._solver.add_stay(self._var_h,
                                                      strength=STRONG)

        if rect.width != self._var_w.value:
            changed = True
            if self._width_stay:
                self._solver.remove_constraint(self._width_stay)

            self._var_w.value = rect.width
            self._width_stay = self._solver.add_stay(self._var_w,
                                                     strength=STRONG)

        if changed:

            value_vectorized = np.vectorize(lambda x: x.value)

            for (_, val) in self._grid_widgets.items():
                (row, col, rspan, cspan, widget) = val 
```

With my example above, @mkubanski 's doesn't seem to remove the increasing CPU load and FPS slowdown after a few minutes.

I am using vispy 0.5.3 by the way.

**Comment by kmuehlbauer** [comment]
@foloxweilf Thanks for checking. It would be nice if you could check this too on latest vispy github master (PR welcome). I'm currently travelling and can test tomorrow earliest. Anyway, it would be good if we can sort this issue out, finally. :+1:

**Comment by foloxweilf** [comment]
@kmuehlbauer Well, it looks like I can't reproduce this problem in the latest master. It looks like `_view_changed` in axis.py is no longer being called every frame in the latest version, as it was in 0.5.3. I guess this issue is resolved then, sorry!

**Comment by kmuehlbauer** [comment]
@foloxweilf Let's wait a bit what @djhoese has to say about this. Good chance that your findings can still be of value. We really appreciate your contribution.

**Comment by djhoese** [comment]
@foloxweilf Thanks for looking in to this and already having a fix. I do think we recently (past 6 months) had an update to reduce the number of times `_view_changed` is called which as you pointed out should help if not solve this issue, although maybe indirectly. As @kmuehlbauer says I think your solution may still be helpful in the future.

If it wouldn't be too hard for you it would be nice to see a PR to make your changes more obvious to me and see if they would be good to add (I think they are based on what I'm reading). I'm taking care of some personal stuff for the next couple days so I may not be quick to reply the rest of the week. Thanks again.

**Comment by codypiersall** [comment]
I may have found the root  issue that is going on, both with the performance issue and the memory leak, with the help of the [objgraph](https://mg.pov.lt/objgraph/) package.  That package is really amazing.

The issue at least with _a_ memory leak is in [`Buffer.__getitem__`](https://github.com/vispy/vispy/blob/master/vispy/gloo/buffer.py#L258).  The value of buffer._views grows without bound.  To demonstrate, change the `Test.update` method above to this one:

```python
    def update(self, ev):
        # print the length of 
        if not hasattr(self, 'i'):
            self.i = 0
        self.t = (self.t + 0.01) % (2*np.pi)
        self.pos[0,0] = np.sin(self.t*2)
        self.pos[0,1] = np.cos(self.t)
        self.m.set_data(pos=self.pos)

        if self.i % 100 == 0:
            print('len _views:', len(self.m._vbo._views))

        self.i += 1
```

I'm not sure yet how Buffer._views gets used, so it could still be that there are no performance implications.  But the growth without bound is concerning.  I'm not sure what the right fix is at this point; haven't got that far yet.

**Comment by codypiersall** [comment]
Here's a patch that prevents `Buffer._views` from growing without bound:

```
diff --git a/vispy/gloo/buffer.py b/vispy/gloo/buffer.py
index e899821..219c108 100644
--- a/vispy/gloo/buffer.py
+++ b/vispy/gloo/buffer.py
@@ -260,8 +260,17 @@ class DataBuffer(Buffer):
 
         view = DataBufferView(self, key)
         self._views.append(weakref.ref(view))
+        self._remove_stale_views()
         return view
 
+    def _remove_stale_views(self):
+        # iterate backwards so we can remove while iterating
+        # remove stale references to the view
+        for i in reversed(range(len(self._views))):
+            view = self._views[i]
+            if view() is None:
+                del self._views[i]
+
     def __setitem__(self, key, data):
         """ Set data (deferred operation) """

```

This comes at a cost of iterating over `Buffer._views` every time the buffer is accessed via `__getitem__`.  I'm not sure this is the best solution, since I don't really understand what the point of `DataBufferView` is.

**Comment by codypiersall** [comment]
There's a second leak associated with (I think) mouse events that I haven't tracked down yet.

**Comment by codypiersall** [comment]
There's a leak in `EventEmitter` as well.  The problem is that the `_callbacks` list is growing without bound.  To show that, just add a `print(len(self.view._transform._inverse.changed._callbacks))`.  It's growing because the weak references are not getting cleanup up properly, just as in the buffer code.

**Comment by codypiersall** [comment]
Here's a patch that fixes the issue in `EventEmitter`: 

```
diff --git a/vispy/util/event.py b/vispy/util/event.py
index 82538dc..3937eea 100644
--- a/vispy/util/event.py
+++ b/vispy/util/event.py
@@ -312,6 +312,7 @@ class EventEmitter(object):
         callback that is connected _last_ will be the _first_ to receive
         events from the emitter.
         """
+        self._remove_stale_callbacks()
         callbacks = self.callbacks
         callback_refs = self.callback_refs
 
@@ -372,6 +373,17 @@ class EventEmitter(object):
         self._callback_refs.insert(idx, ref)
         return callback  # allows connect to be used as a decorator
 
+    def _remove_stale_callbacks(self):
+        # remove callbacks which have a weakref that have expired
+        # iterate backwards so we can remove callbacks as we iterate
+        for i in reversed(range(len(self._callbacks))):
+            obj = self._callbacks[i]
+            if isinstance(obj, tuple) and isinstance(obj[0], weakref.ref):
+                ref = obj[0]()
+                if ref is None:
+                    del self._callbacks[i]
+                    del self._callback_refs[i]
+
     def disconnect(self, callback=None):
         """Disconnect a callback from this emitter.

```

This comes at the cost of iterating over `_callbacks` every time `connect` is called.  I feel pretty confident that this is the right thing to do in this case; the list of callbacks is probably pretty short, and it already gets looped over a couple other times in the function.

I'd be happy to open one or two PRs with the two patches that I suggested here.

I kind of took over this issue.  Sorry @foloxweilf :-(

**Comment by kmuehlbauer** [comment]
@foloxweilf Could you please test your application with latest github master (after commit bd14494de960e3b7dfbc377edc10a15a47cd3572) if the slowdown persists?

**Comment by djhoese** [comment]
I commented on #1591, but @felixwoolford if you have the time it'd be great if you could test the master branch for performance issues.

**Comment by djhoese** [comment]
Based on the comment by @felixwoolford in #1591:

>  I have used applications like the one in #1588 quite extensively since then (currently using 0.6.2) with no performance issues whatsoever!

I'm going to considered this closed. If someone finds this and still has performance issues like the ones discussed here then please open a **new** issue and reference this one for context.
