### ISSUE TITLE
How can I get the data in self.program['a_position']?

### ISSUE THREAD

**Issue by junrenge** [vispy/vispy#1597]
I init the data like this:
  self.program['a_position'] = y.reshape(-1, 1)
and add some data:
    def on_timer(self, event):
        x, max_len = get_waves(self.temp)
        if self.counter >= self.N_wf:
            self.counter = 0
            x = x[:, :self.N_wf - self.counter]
        self.program['a_position'].set_subdata(x.ravel().astype(np.float32), offset=offset)
then how can I get the data in self.program['a_position']?Not only y, but the whole data it displayed.

**Comment by djhoese** [comment]
I'm sorry for the late response. This issue must have gotten lost in my inbox.

In general, from what I understand, this is bad practice and may not be possible in OpenGL from what I know. It is best to keep a copy of any arrays you send to the GPU if you need to access/modify them again. There are `readPixels`-like functions for getting the frame buffer contents, but I don't think there is anything for a vertex buffer.

Is there a reason you can't hold on to the results yourself?

I should also point out @thomasdeneux's pull request #1607 where the user of the buffer can create it with an explicit CPU-side copy of the data. This would potentially let you get a copy of what is sent to the GPU, but there is no reason you couldn't do the same thing yourself in your application.

**Comment by junrenge** [comment]
I solve this problem by, just like you said, keeping a copy of the data before I use set_data(), so I can access the data later.Thank you for your response.
