### ISSUE TITLE
error triggered in parametric.py from klein.py demo

### ISSUE THREAD

**Issue by prelich** [vispy/vispy#1604]
Hello, I tried to run the klein bottle demo and I had a type error: https://github.com/vispy/vispy/tree/master/examples/demo/scene/klein.py
I'm copying the command line traceback below:

E:\Code\playground>python klein.py
C:\ProgramData\Anaconda3\lib\site-packages\vispy\visuals\isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
Traceback (most recent call last):
  File "klein.py", line 38, in <module>
    vertices, indices = surface(klein, urepeat=3)
  File "C:\ProgramData\Anaconda3\lib\site-packages\vispy\geometry\parametric.py", line 55, in surface
    indices.reshape(len(indices) / 3, 3))
TypeError: 'float' object cannot be interpreted as an integer

**Comment by GuillaumeFavelier** [comment]
Are you sure you used the master version of the code?

I think the instruction available on master at [line 55](https://github.com/vispy/vispy/blob/master/vispy/geometry/parametric.py#L55) should be :
`indices.reshape(len(indices) // 3, 3))` instead of 
`indices.reshape(len(indices) / 3, 3))`

**Comment by prelich** [comment]
I think Anaconda has the wrong package by default.  I just did an autoclean on my libraries and then I tried to upgrade vispy via pip and it still didn't change the code.  I'll just build from the master instead in the meantime.  Thanks.

**Comment by kmuehlbauer** [comment]
@prelich anaconda, conda-forge and pip do only have aged versions of vispy (0.5.3 max IIRC). If you install via pip, you will likely get the same version.

You can install vispy from latest github master via pip too:

```
pip install git+https://github.com/vispy/vispy.git@master
```

**Comment by prelich** [comment]
python

**Comment by prelich** [comment]
Awesome, that worked.
