### ISSUE TITLE
MAINT: Wheels

### ISSUE THREAD

**Issue by larsoner** [vispy/vispy#1606]
Now that VisPy uses some compiled code, we should probably produce wheels for releases. (Forcing end users of Windows and macOS to properly set up a dev environment is cruel.)

@djhoese any experience with this? If not, I can look into it. I've been curious to do so at some point anyway.

**Comment by djhoese** [comment]
The aggdraw project that I maintain builds wheels (https://github.com/pytroll/aggdraw) using the cibuildwheels project (https://github.com/joerick/cibuildwheel).

**Comment by kmuehlbauer** [comment]
This aims on users using plain system python installation, no conda etc., right? .

**Comment by larsoner** [comment]
Yes indeed

**Comment by larsoner** [comment]
(really anything other than `conda` I guess, which will take care of building a different way)

**Comment by kmuehlbauer** [comment]
resolved by #1663
