### ISSUE TITLE
vispy postpones pyqt events

### ISSUE THREAD

**Issue by neurochen** [vispy/vispy#1613]
In my program, I use vispy roll_data to animate my data visualization. In the same time, qtimer events are also repetitively scheduled in the main process and thread. Although the callback for plot updates only takes ~1 ms to finish CPU-wise, but the vispy callback postponed qtimer events until the swap was finished. Please be clear that vsync in vispy is already turned off here. 

This looks a bit weird for me, as the cpu callback is already fully executed and returned. After this, all the plotting should be uploaded to the GPU already. However, this is not observed, as the qtimer callback without any GPU code is delayed tens of milliseconds. 

My system configuration is:
```
OS: windows 10
Python: 3.7.2
vispy: the latest master branch
pyqt: PyQt5, qtpy
```

Thanks.

**Comment by djhoese** [comment]
Do you have a code example that I can run to test this and show the timing you are experiencing?

**Comment by djhoese** [comment]
Oh also keep in mind the discussion on #1609 which talks about poor performance being seen on certain Windows systems.

**Comment by neurochen** [comment]
Thanks, David. Please see the slightly modified scrolling_plots.py below. Right now, it outputs the time stamp when the callback is entered, in this case, event without a qtimer. The same issue occurred as well.
```python
# -*- coding: utf-8 -*-
# Copyright (c) Vispy Development Team. All Rights Reserved.
# Distributed under the (new) BSD License. See LICENSE.txt for more info.
# vispy: gallery 30
"""
Show 10,000 realtime scrolling plots
"""
from vispy import app, scene
import numpy as np
import time
from qtpy.QtCore import QTimer


canvas = scene.SceneCanvas(keys='interactive', show=True, size=(1024, 768), vsync=False)
grid = canvas.central_widget.add_grid()
view = grid.add_view(0, 1)
view.camera = scene.MagnifyCamera(mag=1, size_factor=0.5, radius_ratio=0.6)

# Add axes
yax = scene.AxisWidget(orientation='left')
yax.stretch = (0.05, 1)
grid.add_widget(yax, 0, 0)
yax.link_view(view)

xax = scene.AxisWidget(orientation='bottom')
xax.stretch = (1, 0.05)
grid.add_widget(xax, 1, 1)
xax.link_view(view)


N = 4
M = 2
cols = int(N**0.5)
view.camera.rect = (0, 0, cols, N/cols)

lines = scene.ScrollingLines(n_lines=N, line_size=M, columns=cols, dx=0.8/M,
                             cell_size=(1, 8), parent=view.scene)
lines.transform = scene.STTransform(scale=(1, 1/8.))


def update(ev):
    m = 50
    data = np.random.normal(size=(N, m), scale=0.3)
    data[data > 1] += 4
    lines.roll_data(data)
    print(time.perf_counter())

timer = app.Timer(connect=update, interval=0)
timer.start()


if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        app.run()
```

**Comment by djhoese** [comment]
So to reword what you're seeing versus what you're expecting:

The callback that is updating the data (the `update` function) is completing in ~1ms (according to you), but you are seeing that the `update` function is only called every ~10ms because Qt is delaying the call until the draw is complete. Right? You expect the `update` function to be called as fast as possible?

FYI here are my results locally with a PyQt5 Python 3.7 Anaconda environment:

```
3.979143961
3.995652826
4.012809237
4.028668406
4.045436065
4.061852308
4.079049914
4.095999966
4.113264304
```

**Comment by neurochen** [comment]
Yes, exactly. That's what I expected and wanted. Do you think it's possible?

**Comment by djhoese** [comment]
How would that work? The `update` function may be *returning* in ~1ms, but it itself is triggering/starting an "update" event in the vispy/Qt system. This update process starts with a check to see if we are already in the update/drawing process and if so, will not redraw. If the `update` function is called faster than vispy/ the GPU can draw things, vispy will "skip" drawing events until the GPU has finished drawing the previous "frame". If it didn't do this you would end up with an infinitely growing series of events to process.

Additionally, Qt operates on the idea of an event loop so your timer adds one single timer event to handle. I **think** Qt only triggers that timer again once it has finished handling the previous timer event (I'm guessing). If there was no drawing or any other event for Qt, then this would happen as fast as possible. However, the `self.update()` call inside `roll_data` is adding its own events to the queue of events for Qt to handle (event loop). Qt will only get to the timer events when it can.

I tested this, but it doesn't look like we are even hitting the "asking for updates faster than the GPU can draw" point. I did the following change:

```
diff --git a/vispy/scene/canvas.py b/vispy/scene/canvas.py
index 7b96edaf..6b83a98c 100644
--- a/vispy/scene/canvas.py
+++ b/vispy/scene/canvas.py
@@ -190,6 +190,7 @@ class SceneCanvas(app.Canvas, Frozen):
         """
         # TODO: use node bounds to keep track of minimum drawable area
         if self._drawing:
+            print("Already drawing")
             return
 
         # Keep things civil in the node update system. Once an update
@@ -198,6 +199,8 @@ class SceneCanvas(app.Canvas, Frozen):
         if not self._update_pending:
             self._update_pending = True
             super(SceneCanvas, self).update()
+        else:
+            print("Update is already pending")
 
     def on_draw(self, event):
         """Draw handler
```

And only saw messages at the beginning while the window was waiting to be opened. So I'm not sure what this means. Maybe that vispy's python code is what's slowing you down? It can't ask the GPU to draw updates fast enough for "exhaust" the GPU. What kind of FPS numbers are you hoping to see?

**Comment by neurochen** [comment]
Got it, reasonable! Your statement about Qt event system is also right. What I want to achieve is only 60 fps, which is super easy with vispy. But I have another critical function running inside the same process together vispy. About 10 ms delay introduced here will basically stop my program. Would it be possible to just check whether GL commands are finished on GPU? I guess what's running inside now is glFinish somewhere in the update process? A non-blocking GPU drawing is enough for my purpose.

**Comment by djhoese** [comment]
Is the critical function drawing anything? If not, I would advise moving it to another background thread. If it is CPU intensive then I would recommend moving it to a separate process if possible.

What Qt allows us to do is as close to a non-blocking GPU drawing process as possible (event loop). As far as I know at least. I think Qt makes the python process wait for drawing processing to finish on the GPU before completely returning. The longest part of this process is probably vispy and the rest of the Qt system figuring out what should be drawn. The ScrollingLinesVisual says `self.update()` which tells vispy to go through the visuals to draw and run the appropriate GL commands. The more visuals; the more time it takes to do this check. Additionally each visual represents a single GL program, so the more visuals, the more GL programs to execute; GL programs run serially. So it is best, if possible, to put as many drawing operations in one GL program if possible by writing more complex (but intelligently written) shaders.

Another idea is that you could maybe set the timer to a value that gives you 60 fps (16.6ms, right?). Reduce the number of times things are called.

**Comment by neurochen** [comment]
Thanks for the suggestions. The fps is 60 hz already. I will try the first suggestion out. BTW, just curious about whether vispy is thread-safe now.

**Comment by djhoese** [comment]
How so? Vispy is dependent on a GUI framework as its backend. The majority (all of the ones I know) of GUI frameworks require that drawing operations/functions be done in the main (GUI) thread. That includes Qt4/5. Therefore, VisPy is only thread-safe during operations where it is not updating things on the GPU.

There are ways around this. For example, I have an application that requires some time to prepare the numpy array images that it displays using vispy. It will first produce a minimum resolution version of the image to do an initial display, then a background thread will generate the full image, set that data as `.data` on my custom Image visual, but then doesn't call `.update()`. Instead it signals the main GUI thread (via Qt signals and slots) that it should redraw. This redraw/update then "sees" that there is new data to use, uploads it to the GPU, and draws this new image data on the screen. You could try to accomplish something like this yourself.

**Comment by djhoese** [comment]
Let me put that another way: vispy is pretty much not thread-safe. It is up to you the user to make sure multiple threads don't update vispy objects at the same time. Given the dependence on the thread-conscious GUI framework, there isn't a huge point for vispy to add thread locking to make things like `roll_data` thread-safe. It would add a performance hit to the more common single-threaded user case.

Note: I am not one of the original vispy developers, but this is my opinion of the system as it is now.

**Comment by neurochen** [comment]
Thanks for the explanation! #632 talks about multithreading specifically.
