### ISSUE TITLE
High CPU consumption when graphics update is stopped

### ISSUE THREAD

**Issue by dalexan** [vispy/vispy#1616]
I was checking the example of cloud of points (https://github.com/vispy/vispy/blob/master/examples/demo/gloo/cloud.py). When the animation is running and cloud is rotated. my CPU usage is below 1% and Intel GPU is 100%. This is what I would expect. However, after pressing 'space' and stopping cloud rotation CPU rises to 20%. Is there a way to reduce it?

**Comment by djhoese** [comment]
My best guess is that is either PyQt deciding if it needs to do anything (looping quickly through events) or a sleep/wait loop in vispy. Are you using PyQt? 4 or 5?

**Comment by dalexan** [comment]
Actually, I happen to run it with glfw 3.2.1. Once I switched to PyQt5, which I a planing to use it with, the problem disappeared.

**Comment by djhoese** [comment]
Interesting. I don't have a lot of experience with the glfw backend and I'm not sure there is much I can do. I'm going to close this for now. If you have other questions or details feel free to reopen.

**Comment by larsoner** [comment]
GLFW does not have a built-in event loop, so we hack it with a `while` loop. It's entirely possible it's too aggressive or uses too naive a strategy

**Comment by dalexan** [comment]
Thank you for clarification.
