### ISSUE TITLE
missing wheel package dependency on pip install process

### ISSUE THREAD

**Issue by nekopep** [vispy/vispy#1617]
Trying to install vispy in a python3.7 venv I get this error:

`pip install vispy`

Collecting vispy
  Downloading https://files.pythonhosted.org/packages/5f/e2/1c9f4534a335f922bddf5fbd7ed1b105b91660b9ac32e21c39fa62544386/vispy-0.5.3.tar.gz (12.3MB)
    100% |████████████████████████████████| 12.3MB 153kB/s 
Requirement already satisfied: numpy in ./py37_pyside2_gui/lib/python3.7/site-packages (from vispy) (1.16.2)
Building wheels for collected packages: vispy
  Running setup.py bdist_wheel for vispy ... error
  Complete output from command /home/nekopep/Documents/python/py37_pyside2_gui/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-419w6_3h/vispy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-yknmuvcr --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  **error: invalid command 'bdist_wheel'**
  
  ----------------------------------------
  Failed building wheel for vispy
  Running setup.py clean for vispy
Failed to build vispy
Installing collected packages: vispy
  Running setup.py install for vispy ... done
Successfully installed vispy-0.5.3
```

**Comment by nekopep** [comment]
I had to do :
`pip install wheel`
Collecting wheel
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
Installing collected packages: wheel
Successfully installed wheel-0.33.1

Then:
`pip install vispy`
Collecting vispy
  Using cached https://files.pythonhosted.org/packages/5f/e2/1c9f4534a335f922bddf5fbd7ed1b105b91660b9ac32e21c39fa62544386/vispy-0.5.3.tar.gz
Requirement already satisfied: numpy in ./py37_pyside2_gui/lib/python3.7/site-packages (from vispy) (1.16.2)
Building wheels for collected packages: vispy
  Running setup.py bdist_wheel for vispy ... done
  Stored in directory: /home/laurent/.cache/pip/wheels/78/4a/81/db541db6561a36f679953cc76037a743923e9862ab5516d227
Successfully built vispy
Installing collected packages: vispy
**Successfully installed vispy-0.5.3**

**Comment by djhoese** [comment]
I think this was overall a setuptools issue, but regardless vispy now provides wheels and sdist formats for releases. This should overall be fixed. If there are still issues with installing vispy please create a new issue.
