### ISSUE TITLE
How to get viewbox size in 'one_scene_four_cams' example

### ISSUE THREAD

**Issue by yepengxj** [vispy/vispy#1626]
How to get viewbox size in 'one_scene_four_cams' example
I need to get viewbox size in 'one_scene_four_cams' example, but I use vbx.size and vbx.canvas.size get wrong size

 ```
print('vb1.size:', vb1.size)     
 print('vb2.size:', vb2.size)      
 print('vb3.size:', vb3.size)      
 print('vb4.size:', vb4.size)
```

> vb1.size: (10, 10)
vb2.size: (10, 10)
vb3.size: (10, 10)
vb4.size: (10, 10)

```
print('vb1.canvas.size:', vb1.canvas.size)
print('vb2.canvas.size:', vb2.canvas.size)
print('vb3.canvas.size:', vb3.canvas.size)
print('vb4.canvas.size:', vb4.canvas.size)
```
> vb1.canvas.size: (800, 600)
vb2.canvas.size: (800, 600)
vb3.canvas.size: (800, 600)
vb4.canvas.size: (800, 600)

I can use grid.gird_size and gird.size to get grid size. Is that means I can use grid size to calculate viewbox size?
```
print("grid.grid_size", grid.grid_size )
print("grid.size", grid.size )
```
> grid.grid_size (4, 4)
grid.size (800, 600)

**Comment by djhoese** [comment]
@yepengxj Did you ever find a solution for this? My original thought (which I apparently forgot to comment) was that you may be checking the size *before* things are actually drawn which may explain the incorrect size.

**Comment by yepengxj** [comment]
@djhoese I calculate viewbox size by using grid.size and grid.grid_size, I find that viewbox size works after resize whole applicaiton.

**Comment by djhoese** [comment]
Would you consider that an acceptable solution to your problem? I'm not sure there is much we can do about the viewbox size being accessed before things are drawn completely. *If* the viewbox still has the wrong size after everything is drawn and shown completely then we have more work to do.

**Comment by yepengxj** [comment]
@djhoese Up to now, it work  fine for my  situation
