### ISSUE TITLE
Potential problem with triangulation

### ISSUE THREAD

**Issue by rougier** [vispy/vispy#1627]
I've just fixed some code in glumpy because of a change in the triangle library and it may impact vispy as well (more specifically https://github.com/vispy/vispy/blob/master/vispy/geometry/triangulation.py).

The original bug report: https://github.com/glumpy/glumpy/issues/214
The fix: https://github.com/drufat/triangle/issues/34

**Comment by djhoese** [comment]
This should be fixed with #1628.
