### ISSUE TITLE
vispy changes qt UI fonts globally

### ISSUE THREAD

**Issue by neurochen** [vispy/vispy#1629]
The latest master vispy changes the font of pyqt apps globally under Windows 10, although the old version 0.5.3 works as expected. Could you please take a look at that? 
```
Python: 3.7.3
OS: Windows 10 build 10.0.17763.437
vispy: 0.6.0dev0
pyqt: 5.11.3
```
This is what looks like now:
![image](https://user-images.githubusercontent.com/10821596/56592381-8fa73a80-65b8-11e9-9df2-4ffd7f550109.png)

**Comment by djhoese** [comment]
And what did it look like before?

You are using PyQt5? The master branch has had a complete overhaul on the PyQt5 backend to use PyQt5's new OpenGL API. There may be differences for you whether you are on a HiDPI display or not and how PyQt5 is handling that. See https://doc.qt.io/qt-5/highdpi.html for details.

Otherwise, this could be CPU versus GPU rendering of text in the TextVisual. I thought master had the same defaults as 0.5.3 as far as that goes.

**Comment by neurochen** [comment]
Just updated the first comment above. I am using pyqt5 5.11.3, not with a high DPI device.

**Comment by djhoese** [comment]
So what did it look like before? Or at least, what is different about it now?

Did you update the version of PyQt5 you were using at all? Any other packages (like fontconfig)?

**Comment by neurochen** [comment]
This issue starts from the first commit for pyqt5's new OpenGL API. 

What looks like with the commits before the new API:
![image](https://user-images.githubusercontent.com/10821596/56595389-8d46df80-65bc-11e9-9c6e-f5f988856450.png)

What looks like now, with the new API:
![image](https://user-images.githubusercontent.com/10821596/56595373-828c4a80-65bc-11e9-95ac-e9c888a261e3.png)
Please pay attention to the difference in the top-left corner of the two images. The font of the qt widget is changed, although it's not created by vispy.

The qt and pyqt5 are the latest versions already. What kind of configuration is required to make vispy work normally under pyqt5?

**Comment by djhoese** [comment]
This is technically an issue with PyQt5 and how it treats fonts with its handling of HiDPI displays. Even though you say you are not using a HiDPI display, PyQt5 may be handling fonts differently to support "legacy" applications (their words).

As I linked to before, PyQt5 has some documentation on how scaling can be configured by the application. Do any of the environment variables mentioned change the results for you? https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt
The section above that talks about Windows HiDPI awareness too which may be something to play with.

If none of these options help, then I'm not sure where to go from here. If something does work, then we can consider setting it by default for vispy but I'm not sure that is the right solution.

One more thing, how are you adding the vispy canvas to your Qt application? Are you adding `.native` as a widget to your layout?

**Comment by djhoese** [comment]
And how are you setting the size for your font (assuming you are customizing it)?

**Comment by neurochen** [comment]
Interesting... Yes, you are right, I just embedded the native canvas to pyqt5. I did not change the size and font of the text in vispy. It looks like I should install the version using old API at the moment. Thanks.

**Comment by djhoese** [comment]
Were you able to try any of the things discussed in that PyQt5 documentation? Did it make a difference?

**Comment by queenish001** [comment]
@neurochen Did you get the answer to this?

**Comment by neurochen** [comment]
> @neurochen Did you get the answer to this?

It's gone after the new vispy release. I am running 0.6.6 without issues.

**Comment by queenish001** [comment]
Okay, Great.
@djhoese This issue can be closed now :)
