### ISSUE TITLE
Window transparency issue in molecular_viewer.py

### ISSUE THREAD

**Issue by moridinamael** [vispy/vispy#1642]
On my Windows 10 machine with a GeForce GTX 1080 Ti (Driver version 430.39) there are serious issues in the visualization of the molecular_viewer.py example code (/examples/demo/gloo/molecular_viewer.py).

The background of the image is black no matter what; but wherever there is any color, the color takes on a strange transparency, where you can see through the display window if the window is superimposed over non-black backgrounds.

Additionally, if you introduce code to take screenshots, the screenshots always show a black background with pure white molecule images.
![image](https://user-images.githubusercontent.com/1059029/58190470-d18bd500-7c79-11e9-89f7-4b26cb0abac6.png)
The image exhibits the undesirable behavior. You can see the shape of my (black) console window placed *behind* the display window.

**Comment by djhoese** [comment]
This is a known issue for past versions of vispy. This should be fixed in vispy 0.6.0+ but it has yet to be released. Please try installing vispy from github (may require a valid C compiler) and see if this changes anything for you.

**Comment by moridinamael** [comment]
Installing and using 0.6.0 does resolve the issue with the active display, but the saved _screenshot images still display the molecules as being completely white with a black background.
```
res = _screenshot()
vispy_file.write_png('test_screenshot.png', res)
```
This results in black&white images.

**Comment by djhoese** [comment]
Can you take a screenshot with your system (not vispy) and show me what the window looks like for you? It looks broken for me too where all of the molecules look mostly white.

@kmuehlbauer if you have a couple minutes if you could also run this on your system and let me know how it looks. Here's mine on OSX with PyQt5 and Python 3.7:

![image](https://user-images.githubusercontent.com/1828519/58253259-a236a000-7d2d-11e9-9d7d-9ff9564f1c46.png)

**Comment by kmuehlbauer** [comment]
@djhoese This is a screenshot with my OpenSuse LEAP15 system and latest vispy github master.
![Screenshot_20190523_144315](https://user-images.githubusercontent.com/5821660/58253707-4d187f80-7d69-11e9-9ffc-af484142944f.png)

**Comment by djhoese** [comment]
@kmuehlbauer what version of python? PyQt5?

**Comment by GuillaumeFavelier** [comment]
On the latest version of master, I obtain the following by system screenshot:

![image](https://user-images.githubusercontent.com/18143289/58253636-2e19ed80-7d69-11e9-9c68-f965f6a24d0f.png)

My configuration:
Platform: Linux-4.19.42-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Python:   3.6.8
Backend: PyQt5

*kmuehlbauer was faster for the screenshot!*

**Comment by kmuehlbauer** [comment]
Added `vispy.sys_info()` output below my screenshot...

**Comment by djhoese** [comment]
I get the proper results with PyQt4 on OSX. With PyQt5 I get the super faded results I showed above with Python 3.6 or 3.7. Hhhmmm great.

**Comment by kmuehlbauer** [comment]
The following I get when using vispy's `_screenshot` and `write_png`. 
![test_screenshot](https://user-images.githubusercontent.com/5821660/58254284-b64cc280-7d6a-11e9-8d48-29175c7a044b.png)

**Comment by GuillaumeFavelier** [comment]
I don't know `_screenshot` so I used `render()` and `write_png`:
```py
if __name__ == '__main__':
    mvc = Canvas()
    app.run()
    import vispy
    img = mvc.render()
    vispy.io.write_png('shot.png', img)
```
![image](https://user-images.githubusercontent.com/18143289/58254719-a71a4480-7d6b-11e9-9050-e2aeb8f1eaab.png)

**Comment by djhoese** [comment]
@GuillaumeFavelier `render` is not recommended. There is an example of `_screenshot` further up, but I'm not sure where people are putting it in the example code. It comes from `from vispy.gloo.util import _screenshot` (we really need to make this public).

**Comment by djhoese** [comment]
@GuillaumeFavelier Do you have an Nvidia GPU?
@moridinamael Same question.

**Comment by GuillaumeFavelier** [comment]
I have indeed an Nvidia GTX960M but I don't use it.
```sh
$ lspci | grep VGA
$ 00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)
```

**Comment by djhoese** [comment]
Ok, I have an AMD/ATI GPU in my mid-2015 macbook:

```
GL version:  '2.1 ATI-2.9.26'
```

I'm going to ask a coworker to try this example on their newer macbook and see what they get.

**Comment by djhoese** [comment]
@moridinamael Very interesting. If I change the shader in the code to:


```
$ git diff
diff --git a/examples/demo/gloo/molecular_viewer.py b/examples/demo/gloo/molecular_viewer.py
index 0a424b32..e6576736 100644
--- a/examples/demo/gloo/molecular_viewer.py
+++ b/examples/demo/gloo/molecular_viewer.py
@@ -87,8 +87,8 @@ void main()
     // GPU drivers...
     float specular = clamp(pow(abs(dot(normal, K)), 40.), 0.0, 1.0);
     vec3 v_light = vec3(1., 1., 1.);
-    gl_FragColor.rgb = (.15*v_color + .55*diffuse * v_color
-                        + .35*specular * v_light);
+    gl_FragColor.rgba = vec4(.15*v_color + .55*diffuse * v_color
+                        + .35*specular * v_light, 1.0);
 }
 """
```

Then mine works fine (haven't tried screenshot yet).

**Comment by moridinamael** [comment]
I verify that the problem is entirely solved by your modification to the shader code. Both screenshots and realtime display are now perfect.

**Comment by djhoese** [comment]
@moridinamael Great! Now I just need to make a pull request. However, I have very little time the next 3 weeks and if I do have time it is unlikely that I'll fix this issue specifically. If anyone else has time to make a pull request for this I'll gladly merge it.
