### ISSUE TITLE
Creating and rendering visuals in real time

### ISSUE THREAD

**Issue by parsoyaarihant** [vispy/vispy#1645]
I am working on a project for which I need to generate and render new visuals on the sketch in real time. However, the frame rate of sketch is suffering significantly whenever a new visual object is declared. 

Is there any way around this?

**Comment by kmuehlbauer** [comment]
Please add some code example which shows this behaviour. Please also add the output of `vispy.sys_info()`.

**Comment by parsoyaarihant** [comment]
### Code
``` python
import numpy as np
from vispy import app, visuals
from vispy import gloo
from random import randint

class Sketch(app.Canvas):
    def __init__(self):
        app.Canvas.__init__(
            self,
            title='p5',
            size=(500, 500),
            keys='interactive',
            resizable=True,
        )

        self.timer = app.Timer(1.0 / 60, connect=self.on_timer)

        self.color = np.array([[1, 1, 1, 1], [1, 1, 1, 1]])
        self.shapes = [visuals.LineVisual(pos=np.array([[0, 0], [800, 800]]), color=self.color, method='agg')]
        self.show(visible=True)

    def on_timer(self, event):
        self.measure_fps(callback=lambda _: None)
        #print(round(self.fps, 2))
        gloo.clear('black')

        viewport = (0, 0, self.physical_size[0], self.physical_size[1])

        pos = [
            [randint(0, 500), randint(0, 500)],
            [randint(0, 500), randint(0, 500)]
        ]
        self.shapes.append(
                visuals.LineVisual(pos=np.array(pos), color=self.color, method='agg')
            )

        for s in self.shapes:
            s.transforms.configure(canvas=self, viewport=viewport) 
            s.draw()

        self.update()

    def on_close(self, event):
        exit()

    def on_draw(self, event):
        gloo.set_clear_color((1, 1, 1, 1))
        pass

    def on_resize(self, event):
        gloo.clear('black')
        viewport = (0, 0, self.physical_size[0], self.physical_size[1])
        gloo.set_viewport(*viewport)
        

sketch = Sketch()
physical_width, physical_height = sketch.physical_size
sketch.timer.start()

app.run()
exit()
```

Without creating new `visuals` objects, I am getting around 60fps speed. When new object is created at every frame, the fps has dropped to 5.

### sys_info()
``` python
Platform: Darwin-18.5.0-x86_64-i386-64bit
Python:   3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy:    1.16.2
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.9.2', '5.9.6')
pyside:   None
pyglet:   None
glfw:     glfw (3, 3, 0)
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None

GL version:  '2.1 ATI-2.8.38'
MAX_TEXTURE_SIZE: 16384
Extensions: 'GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_depth_bounds_test GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod '
```

**Comment by djhoese** [comment]
What is your goal with this code:

```
        for s in self.shapes:
            s.transforms.configure(canvas=self, viewport=viewport) 
            s.draw()
```

If would be best if you weren't updating the viewport except on image resizes or specific events. This may just be a result of your simplified example.

Next, this method of adding new visuals for every "event" is expected to not perform well. At the low-level each Visual object is an OpenGL program. That means that your system has to draw each line (in this example) one at a time (send line 1 GL program, run program, send line 2 GL program, run program, etc). OpenGL performs best if you tell it everything it is supposed to draw at once, if possible. In this example, it would be best if you updated the LineVisual's data with new line segments rather than creating a new visual for every line. This can get very difficult for things that aren't GL primitives (lines, triangles, etc) which is what vispy "collections" are supposed to help with, but these aren't necessarily fully implemented in vispy yet.

**Comment by parsoyaarihant** [comment]
Without updating the viewport, the newly created object will not be configured to render on the canvas. Output when viewport is not updated: 
<img width="503" alt="Screenshot 2019-05-30 at 9 12 12 PM" src="https://user-images.githubusercontent.com/15258498/58645045-2f768780-8320-11e9-9ef1-eed7b6db65a3.png">

The bigger idea of my project is to make a sketchbook library in python using Vispy as backend. I am working on [p5py](https://p5.readthedocs.io) which is a Python version of [Processing](https://processing.org) software. We need to generate and render objects in real time in which will allows the user to sketch any object at any instant. For example, user might want to render a rectangle whenever mouse is clicked on the canvas.

> In this example, it would be best if you updated the LineVisual's data with new line segments rather than creating a new visual for every line. 

Can this approach be extended to other visuals such as Images and Polygons? For example, when I want to create two rectangles, I can update the data of `Polygon` visual to render two rectangles? From the documentation it doesn't seems likely.

**Comment by djhoese** [comment]
> Without updating the viewport, the newly created object will not be configured to render on the canvas. 

Sorry, I must have been thinking of using the SceneCanvas API which must do this automatically. However, this still seems like something that should happen in `on_draw` which should be called by triggering an update event with `self.update()`.

> Can this approach be extended to other visuals such as Images and Polygons? For example, when I want to create two rectangles, I can update the data of Polygon visual to render two rectangles?

No, that's what I meant when I mentioned the collections classes. You'll have to look at the vispy source for this, sorry.
