### ISSUE TITLE
3D volume data format

### ISSUE THREAD

**Issue by YiDuan1221** [vispy/vispy#1647]
I am having trouble understanding the format of 3D volume data, especially when I am trying to custom a 3D volume for display. Can some please explain how should the volume data be formatted so that it can be correctly used with vispy.scene.visuals.volume()? Thanks.

**Comment by kmuehlbauer** [comment]
@YiDuan1221 Is this still an issue for you? 

The VolumeVisual can be driven by a simple 3D numpy array of data values. So if you think about a cube with edge length of 100, you would need a numpy array of shape (100,100,100) filled with your data values.

**Comment by YiDuan1221** [comment]
> 
> 
> @YiDuan1221 Is this still an issue for you?
> 
> The VolumeVisual can be driven by a simple 3D numpy array of data values. So if you think about a cube with edge length of 100, you would need a numpy array of shape (100,100,100) filled with your data values.

Thanks for your reply. So does the data values represent the color? How should I give the data values?

**Comment by kmuehlbauer** [comment]
It can take anything. Internally it will be converted to float32 and fitted between 0 and 1.

**Comment by kmuehlbauer** [comment]
Yes the data represent the color. You can specify the colormap by keyword `cmap`.

**Comment by YiDuan1221** [comment]
> 
> 
> Yes the data represent the color. You can specify the colormap by keyword `cmap`.

Excellent. I will give it a try. Thank you.

**Comment by kmuehlbauer** [comment]
@YiDuan1221 You're welcome. And thanks for your patience, this somehow went under the radar.
