### ISSUE TITLE
setup.py attempts to import numpy before installing it

### ISSUE THREAD

**Issue by os-gabe** [vispy/vispy#1651]
On master `setup.py` imports numpy on line 46 even though numpy is a dependency of vispy so it is not guaranteed it will be installed yet.

This causes `pip install git+https://github.com/vispy/vispy.git` to fail unless you already have numpy installed.

**Comment by djhoese** [comment]
What is the current best practice for getting around this? I think I use this in other projects. I'll have to look it up later.

**Comment by kmuehlbauer** [comment]
@djhoese PEP 518 was suggested for one of my projects. Works good so far.

**Comment by renefritze** [comment]
> @djhoese PEP 518 was suggested for one of my projects. Works good so far.

Yes. We had been struggling with this forever too in projects.
To use that put a `pyproject.toml` in your project root. Pip will then install the dependencies specified in there in an isolated environment and call the build tool to produce a wheel to install in the environment where pip was called from. 

This has some implications if you produce binary wheels for people to install that should not be ignored.

**Comment by larsoner** [comment]
Agreed `pyproject.toml` should work, see also for example how SciPy does it:

https://github.com/scipy/scipy/blob/master/pyproject.toml

**Comment by djhoese** [comment]
I actually don't think we need to go that far unless we want cython to be installed and rebuild every extension. If this is only about the `numpy` issue I looked at how we do it in pyresample and it looks like I just copied and pasted things poorly in to vispy.

In pyresample we defined this special `build_ext` class:
https://github.com/pytroll/pyresample/blob/master/setup.py#L70-L84

We have that in vispy too:
https://github.com/vispy/vispy/blob/master/setup.py#L113

But then ignore it and manually add the numpy include directories:
https://github.com/vispy/vispy/blob/master/setup.py#L308

I think we could just remove this `include_dirs` and the numpy import at the top of setup.py.

**Comment by renefritze** [comment]
I think if vispy is used as a dependency in a project that installs with PEP 518 mechanics, then vispy itself will be installed with build isolation in that build process. So adding the pyproject.toml would make vispy easier to use in those downstream projects.

**Comment by djhoese** [comment]
@renefritze You are absolutely right and not doing a pyproject.toml file is just me being stubborn.

I'll see if I can make a pull request today for it. I don't fully know everything about the PEP and anything special we need, but our build process should be simpler than scipy.
