### ISSUE TITLE
Cannot install notebook extension

### ISSUE THREAD

**Issue by renefritze** [vispy/vispy#1653]
I've tried following the [instructions](http://vispy.org/installation.html#installation-options), but trying to install the extension after `pip install vispy` fails:

```
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 1125, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module vispy is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
```

Excerpt of `pip freeze `
```
ipykernel==5.1.1
ipyparallel==6.2.4
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.6
jupyterlab-server==0.2.0
notebook==5.7.8
vispy==0.5.3
widgetsnbextension==3.4.2
```

**Comment by renefritze** [comment]
This only happens on the somewhat older `0.5.3` release. Master is fine.

**Comment by namcneal** [comment]
Did you get the notebook extension to work with another version of VisPy?  Both Conda Forge and PyPi have `0.5.3` listed as the current version, released in March 2018.

**Comment by Jumbo-007** [comment]
> This only happens on the somewhat older `0.5.3` release. Master is fine.

Since I'm a newbie facing similar problem on - "jupyter nbextension enable --py vispy" could you please elaborate on how you got rid of it and how is the master used.
I am working in an seperate environment within anaconda and also have jupyter installed in it.

**Comment by renefritze** [comment]
To install from master `pip install git+https://github.com/vispy/vispy@master`. I haven't used vispy since though.

**Comment by Jumbo-007** [comment]
Do you think it's better to use opengl as of now, considering vispy is under heavy development ?

**Comment by djhoese** [comment]
> Do you think it's better to use opengl as of now, considering vispy is under heavy development ?

What do you mean?

I apparently haven't mentioned this here yet, but the jupyter extension for vispy is considered experimental. I highly recommend anyone wanting to do anything more than experimenting with the vispy extension to use a more traditional desktop backend (pyqt5, pyside2, glfw, etc).

**Comment by Jumbo-007** [comment]
It was fine that the visualizations opened in a new window while running vispy codes in the jupyter notebook, but the only confusion arises when "jupyter nbextension enable --py vispy" fails with the aforementioned error and still the code is able to be run @djhoese

**Comment by Jumbo-007** [comment]
> This only happens on the somewhat older `0.5.3` release. Master is fine.

This worked fine except that I had to install pytest and yet this one is still pricking

Enabling notebook extension vispy/extension...
      - Validating: problems found:
        - require?  X vispy/extension
