### ISSUE TITLE
Triangulation with holes

### ISSUE THREAD

**Issue by parsoyaarihant** [vispy/vispy#1657]
Is it possible to use ``vispy.geometry.Triangulation`` to triangulate geometry containing holes? From the documentation there doesn't seem to be any support for holes, is there any work around to triangulate shapes with holes?

I have the following shape parameters:
``` python
outer_vertices = [[-40 -40]
      [ 40 -40]
      [ 40  40]
      [-40  40]]
outer_edges = [[0 1]
      [1 2]
      [2 3]
      [3 0]]

# shape parameters of hole
hole_vertices = [[-20 -20]
      [-20  20]
      [ 20  20]
      [ 20 -20]]
hole_edges = [[0 1]
      [1 2]
      [2 3]
      [3 0]]
```

**Comment by djhoese** [comment]
I don't *think* this is possible. I recall another issue where this was discussed in detail but am having a really difficult time finding it now. You may have to look at the triangulation source code for details on how this done to see if it's possible: https://github.com/vispy/vispy/blob/master/vispy/geometry/triangulation.py

Sorry I can't be of more help. I'm not really familiar with the triangulation code.
