### ISSUE TITLE
shadertoy example non-free license

### ISSUE THREAD

**Issue by toddrme2178** [vispy/vispy#1672]
`examples/demo/gloo/shadertoy.py` has code under a [non-free license](https://www.gnu.org/licenses/license-list.html#CC-BY-NC), "Creative Commons Attribution-NonCommercial-ShareAlike 3.0", which means a wide variety of open-source projects cannot ship vispy since they cannot restrict their users from using software for commercial purposes.

**Comment by kmuehlbauer** [comment]
IANAL, but this is an example how to use shader toy examples within vispy, not code which is needed to run vispy. We might just use something from shader toy without non-free license.

**Comment by djhoese** [comment]
Obligatory I am not a lawyer.

I'm not sure this should be a problem for commercial purposes. My thinking is mainly that this is an example script and is not part of the `vispy` library. So there is no way to do `import vispy` or `from vispy import *` where you would possibly import this `shadertoy` example. The only way to do that is to specify the path to the example exactly when running python. As an example it is not meant to be imported or copied in to any user code beyond being an example of how to use vispy.

That said, in the vispy 0.6 release we included all examples in our source distribution (a.k.a sdist), the `.tar.gz` file that is on PyPI. This means that when you download this file you are also downloading this `shadertoy.py` file. **However**, even though it is in the `.tar.gz` it is **not** installed in to your python environment. They are only there for completeness. If you install the binary wheels from PyPI or the binary builds from conda-forge these also do **not** include the examples.

**Comment by toddrme2178** [comment]
The problem is that lots of groups, for example Linux distributions, distribute the sources for all the compiled packages they provide, something a lot of open-source licenses require.   Those sources will include the non-free code because the whole point of providing sources is to allow others to rebuild the package from the pristine sources, meaning they can no longer distribute vispy.

I am packaging it for openSUSE, for example, and we simply cannot distribute the package anymore.  And binary wheels are not an option, either, for security reasons.

**Comment by larsoner** [comment]
My vote is just to get rid of it, it is not crucial to VisPy and these legal things require too much effort to sort out properly

**Comment by djhoese** [comment]
Ok I'll remove it. I have no problem with that. I copied it to a gist just to have it in one other location if people want it and don't want to go through the git history:

https://gist.github.com/djhoese/f4dfa3b423a88739636dc9a95e58e177

**Comment by toddrme2178** [comment]
Thank you!

**Comment by QuLogic** [comment]
For reference, the Non-Commercial versions of CC are at least on the ["Bad" list](https://fedoraproject.org/wiki/Licensing:Main#Bad_Licenses_3) for Fedora.
