### ISSUE TITLE
point cloud edges rendering with artifacts

### ISSUE THREAD

**Issue by Timu777** [vispy/vispy#1675]
When I render dense point clouds I can't seem to eliminate dark edges around the points regardless of the edge_color or edge_width settings I set. Consider the following example code, modified from an example available online:
`import numpy as np
import vispy.scene
from vispy.scene import visuals

#
# Make a canvas and add simple view
canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)
view = canvas.central_widget.add_view()

# generate data
pos = np.random.normal(size=(100000, 3), scale=0.2)

# create scatter object and fill in the data
scatter = visuals.Markers()
scatter.set_data(pos, edge_width = 0., edge_color=(1,1,1,1), face_color=(1, 1, 1, 1), scaling = True, size=0.01)

view.add(scatter)

view.camera = 'arcball'

# add a colored 3D axis for orientation
axis = visuals.XYZAxis(parent=view.scene)

if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()`

This results in the following image:
![Snp1](https://user-images.githubusercontent.com/50713715/61907358-22ba7e00-aee2-11e9-89af-4604b4883fce.PNG)

The points, which are supposed to be solid white disks, have edges. If I zoom in on the cloud I see the following:

![Snp2](https://user-images.githubusercontent.com/50713715/61907452-57c6d080-aee2-11e9-9dec-ec0cb829931c.PNG)

Presumably, I should just be seeing white. These edges are causing lots of irritating artifacts in imagery that looks good in alternative renders. Is there a way I can get these edges to disappear so that the result looks smoother? vispy.sys_info outputs the following:

Platform: Windows-10-10.0.17763-SP0\nPython:   3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]\nNumPy:    1.16.4\nBackend:  PyQt5\npyqt4:    None\npyqt5:    ('PyQt5', '5.9.2', '5.9.6')\npyside:   None\npyglet:   None\nglfw:     None\nsdl2:     None\nwx:       None\negl:      None\nosmesa:   None\n_test:    None\n\nGL version:  '4.5.0 - Build 25.20.100.6373'\nMAX_TEXTURE_SIZE: 16384\nExtensions: <<omitting...>>

**Comment by djhoese** [comment]
Try following the antialias advice at the bottom of https://github.com/vispy/vispy/issues/1583 and let me know if that fixes things for you.

**Comment by Timu777** [comment]
Thanks for the response. Adding scatterer.antialias = 0 does not seem to affect things. To add to the strange behavior, if I rotate the cloud with the mouse, the point markers uniformly reduce in size. 

Look 1 (default upon running):
![Snp3](https://user-images.githubusercontent.com/50713715/61910490-adeb4200-aee9-11e9-8033-0f753930bdee.PNG)

Look 2 (red axis pointing to viewer)
![Snp4](https://user-images.githubusercontent.com/50713715/61910500-b6dc1380-aee9-11e9-8297-6bab7f4a98d4.PNG)

The size of the points smoothly reduce between look 1 and look 2.

**Comment by Timu777** [comment]
Ok - it *does* solve the problem. I didn't realize the line of code has to be added before scatterer.set_data(<etc>) or it will have no effect. I still don't understand why the points seem to disappear if the cloud is rotated, but it does fix the issue with edges. Thank you.

**Comment by djhoese** [comment]
Try unsetting the `scale` parameter. If I recall correctly the scaling logic for the MarkersVisual does not work in 3D space. There was an issue that talked about it more in depth but I can't find it now. Markers were updated in a naive way to support drawing in 3D space but the scaling part of that does not work yet.

**Comment by djhoese** [comment]
To clarify what I mean, the scale parameter tries to calculate how much of the "view" is being seen and adjusts the size of the markers accordingly. It does this by saying how much distance is being covered in the "X" direction and how much in the "Y" direction; if the distance is large then we must be zoomed out so make them small; if it is small them we must be zoomed in so make them larger (or vice versa). When you throw in a Z dimension this calculation no longer works and I couldn't come up with a simple solution at the time the last time it was brought up.

...I really need to find that issue or pull request.

**Comment by djhoese** [comment]
Found it: https://github.com/vispy/vispy/issues/1166

**Comment by Timu777** [comment]
That solves the problem. Having the scale work for 3D plots would be useful for instances in which a zoomed view of the data is needed. Thank you
