### ISSUE TITLE
Jupyter backend extension installation fails

### ISSUE THREAD

**Issue by klarh** [vispy/vispy#1678]
It seems that fresh installations of vispy are still trying to install from a 'static' python package subdirectory that doesn't exist. I'm trying to use the following procedure to install vispy:

```
git clone --recurse-submodules https://github.com/vispy/vispy
cd vispy && git checkout ${commit}
git submodule update --init
pip install .
jupyter nbextension install --py --sys-prefix vispy
```
Which fails with something like:
```
root@81541c995d9c:/vispy# jupyter nbextension install --py --sys-prefix vispy
Installing /usr/local/lib/python3.6/dist-packages/vispy/static -> vispy
Traceback (most recent call last):
File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 267, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 658, in launch_instance
app.start()
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 988, in start
super(NBExtensionApp, self).start()
File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 256, in start
self.subapp.start()
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 716, in start
self.install_extensions()
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 695, in install_extensions
**kwargs
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
destination=dest, logger=logger
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 199, in install_nbextension
_maybe_copy(src, full_dest, logger=logger)
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 1043, in _maybe_copy
if _should_copy(src, dest, logger=logger):
File "/usr/local/lib/python3.6/dist-packages/notebook/nbextensions.py", line 1019, in _should_copy
if os.stat(src).st_mtime - os.stat(dest).st_mtime > 1e-6:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/dist-packages/vispy/static'
```

This procedure first fails at commit 4686d7837981bfab1023e7e7d53671ba6f91e061 (bisecting from 8c36fb7ffd7641ba0972808888911d71e48e8fe5 , which does work for me), which does indeed seem to remove the static directory, although it looks like the intent is to build it into the final wheel (which doesn't seem to happen here). Did the installation method for the notebook extension change with this shift?

In case it helps to reproduce the issue (since jupyter extensions involve so much mutable state that can be hard to get rid of), I made a docker image [here](https://hub.docker.com/r/mspells/vispy_notebook_tests), with source [here](https://gist.github.com/klarh/a924c3f698897c9e41a01cf6a9fc99bb).

**Comment by djhoese** [comment]
I'm guessing you've tested this with current master?

> Did the installation method for the notebook extension change with this shift?

Let's just say everything regarding the extension installation has changed.

Do you have the `npm` command installed on your system? What about the `ipywidgets` python package? Did you enable the `widgetsnbextension` from ipywidgets (https://vispy.readthedocs.io/en/latest/installation.html#jupyter-notebook-extension)? I don't see the vispy installation instructions as part of your docker file.

I'm hoping to release 0.6.1 today so hopefully we can track down your issue before that.

**Comment by djhoese** [comment]
And do you get different results if you add `--recursive` to your git submodule update command?

**Comment by klarh** [comment]
Yes, this is on current master.

> Do you have the `npm` command installed on your system? What about the `ipywidgets` python package? Did you enable the `widgetsnbextension` from ipywidgets (https://vispy.readthedocs.io/en/latest/installation.html#jupyter-notebook-extension)? I don't see the vispy installation instructions as part of your docker file.

I didn't have npm installed (I figured out that I needed that by looking in `setup.py` shortly after posting this), but testing with it gives the same error about a missing static directory. As for enabling `widgetsnbextension`, it is not needed to make the example notebooks run with commit 8c36fb7 , but I'll include it for all future tests. The actual vispy-related parts of the installation process I'm leaving for interactive input inside the container.

**Comment by djhoese** [comment]
Since you are installing vispy in a normal way (not "development" mode) you should be able to skip the nbextension *install* command and instead end with:

```
jupyter nbextension enable --py vispy
```

**Comment by djhoese** [comment]
As for not having to enable `widgetsnbextension` in the past, that may have been a difference in the version of ipywidgets. It is also automatically done when installed with conda if you've done that in the past. It is in their installation instructions that it needs to be done:

https://ipywidgets.readthedocs.io/en/stable/user_install.html#with-pip

**Comment by klarh** [comment]
> Since you are installing vispy in a normal way (not "development" mode) you should be able to skip the nbextension _install_ command and instead end with:
> 
> ```
> jupyter nbextension enable --py vispy
> ```

After a `pip install` of vispy from master or using the version on PyPI, directly doing `jupyter nbextension enable --py vispy` gives:

```
Enabling notebook extension vispy/extension...
- Validating: problems found:
        - require?  X vispy/extension
```

**Comment by klarh** [comment]
OK, this turned out to be from a couple of different sources:

- In my host system (which prompted the bug report in the first place before trying to make it more reproducible by running inside a docker container), I was installing vispy, jupyter, and ipywidgets/widgetsnbextension into a virtual environment created using `--system-site-packages`. Somehow the system version of ipywidgets/widgetsnbextension was interfering with the latest vispy, but not when the package was structured as it was in 8c36fb7 . Uninstalling jupyter, ipywidgets, and widgetsnbextension from outside the virtualenv and following the vispy installation instructions in the documentation fixed this problem. I had always assumed that nbextensions would be found from more-specific to more-global order (i.e. virtualenv/user site directory, then globally-installed packages), but that does not seem to be the case.
- Inside the docker container, `npm` fails to build the javascript as root. It also seemed that the npm version available by default in the ubuntu repository may have been too old to properly build the javascript package.

Thanks for the help @djhoese !
