### ISSUE TITLE
Load .OBJ Model

### ISSUE THREAD

**Issue by infosisio** [vispy/vispy#1680]
I had great success with .stl but nothing with .obj so far, on its own or with its textures, it just shows a blank canvas. I am trying to load with Trimesh. Is this supported? Thanks.

**Comment by djhoese** [comment]
There is the `vispy.io.mesh.read_mesh` function (https://github.com/vispy/vispy/blob/master/vispy/io/mesh.py#L14). If you are reading wavefront files specifically it looks like @almarklein wrote helper classes for reading and writing these files as well: https://github.com/vispy/vispy/blob/master/vispy/io/wavefront.py

You may have some luck looking for `.obj` in past github issues (closed and opened) for examples of people using them. I have never personally worked with them but as far as I know they are supported granted you provided the faces/edges in the right format. If you still have trouble after investigating a bit more please provide some example code and test data so we can try reproducing the issue.

**Comment by infosisio** [comment]
@djhoese Thanks a lot for the tip. Just curious, what surface parameters etc would make the fastest rendering of the model? I am trying to just quickly generate some static thumbnails here. Thanks!

**Comment by djhoese** [comment]
I'm not sure what you mean. I also am not sure I'd know the best answer even if I did. 😕 Sorry.

**Comment by infosisio** [comment]
@djhoese No worries. One last thing I'd like to ask, I've set the fov and the distance but most of the models were not in the area it was capturing. Is there a way to center on the loaded model? Thanks.

**Comment by djhoese** [comment]
Depends what vispy interface you are using, but generally if you are using the cameras then you can change the center position or where it's looking at by setting a property (iirc). Otherwise other interfaces (visuals, gloo, etc) would require modifying the transform or coordinates for your Visual.

**Comment by infosisio** [comment]
@djhoese Thanks again for assisting. For anyone trying to do the same, the way to get the camera looking right above the model is this:

```
canvas.view.camera = vispy.scene.TurntableCamera()
canvas.view.camera.fov = 30
canvas.view.camera.distance = 0
```

It doesn't work if you don't set the distance to zero.

**Comment by djhoese** [comment]
Were the existing utility functions enough for you to get `.obj` files loaded? Can we close this?

**Comment by infosisio** [comment]
@djhoese Yeah, thank you.
