### ISSUE TITLE
Looking for suitable config

### ISSUE THREAD

**Issue by mahmoodn** [vispy/vispy#1684]
Hi,
After installation, I tried to run a simple example, but it failed

```
$ python start.py 
Traceback (most recent call last):
  File "start.py", line 9, in <module>
    canvas = app.Canvas(keys='interactive')
  File "/home/mahmood/.local/lib/python2.7/site-packages/vispy-0.6.2.dev0-py2.7-linux-x86_64.egg/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/home/mahmood/.local/lib/python2.7/site-packages/vispy-0.6.2.dev0-py2.7-linux-x86_64.egg/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/mahmood/.local/lib/python2.7/site-packages/vispy-0.6.2.dev0-py2.7-linux-x86_64.egg/vispy/app/backends/_egl.py", line 161, in __init__
    self._native_config = egl.eglChooseConfig(_EGL_DISPLAY, attribs)[0]
  File "/home/mahmood/.local/lib/python2.7/site-packages/vispy-0.6.2.dev0-py2.7-linux-x86_64.egg/vispy/ext/egl.py", line 295, in eglChooseConfig
    raise RuntimeError('Could not find any suitable config.')
RuntimeError: Could not find any suitable config.
```
May I know how to resolve that?

**Comment by djhoese** [comment]
Could you please provide the output of doing:

```python
import vispy
print(vispy.sys_info())
```

A couple things I wanted to bring up based on what I see from your error message:

1. You are running with the EGL backend. This was only recently updated by @yogi81. They mentioned some additional things that may need to be done to get this working if you don't have certain things installed on your system (like X).

2. Are you running this headless? No screen/display?

3. You are running this with python 2.7. Just so you know vispy 0.6 will be the last version of vispy to support python 2.7. I highly recommend updating to python 3.7 or above if at all possible.

**Comment by djhoese** [comment]
Oops for got to mention @yogi81's comment: https://github.com/vispy/vispy/pull/1637#issuecomment-491343195

**Comment by mahmoodn** [comment]
I used VNC and X forward of SSH.
Is that the case? Should I run with a local display?

**Comment by mahmoodn** [comment]
BTW, with SSH X forward, as I run the command, it stucks with no error and and no display until I press ^C

**Comment by djhoese** [comment]
I believe EGL is supposed to allow for headless (no display) rendering but it has to be set up correctly which may be what @yogi81's comment is referring to. You could also do something like set up a virtual display on the remote machine to render things, but then you wouldn't be able to see them.

Typically, in my experience, connections to remote systems like VNC or Remote Desktop have very limited OpenGL support, if any. Even virtual machines with VMWare require newer versions to support a good amount of OpenGL features. That said, I would have assumed the `start.py` would work in even limited cases.

Do you know if you have a GPU on the remote machine? Do you have OpenGL drivers installed?

**Comment by mahmoodn** [comment]
Currently, I have the following packages

```
$ dpkg -l | grep mesa
ii  libegl-mesa0:amd64                         19.0.2-1ubuntu1.1~18.04.2                    amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1-mesa:amd64                         19.0.2-1ubuntu1.1~18.04.2                    amd64        transitional dummy package
ii  libgl1-mesa-dri:amd64                      19.0.2-1ubuntu1.1~18.04.2                    amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-glx:amd64                      19.0.2-1ubuntu1.1~18.04.2                    amd64        transitional dummy package
ii  libglapi-mesa:amd64                        19.0.2-1ubuntu1.1~18.04.2                    amd64        free implementation of the GL API -- shared library
ii  libglu1-mesa:amd64                         9.0.0-2.1build1                              amd64        Mesa OpenGL utility library (GLU)
ii  libglx-mesa0:amd64                         19.0.2-1ubuntu1.1~18.04.2                    amd64        free implementation of the OpenGL API -- GLX vendor library
ii  libwayland-egl1-mesa:amd64                 19.0.2-1ubuntu1.1~18.04.2                    amd64        transitional dummy package
```

The GPU on the remote machine is M2000. I have to see if I can gain access to local display. But if I can fix that with VNC or SSH, it would be better.

**Comment by mahmoodn** [comment]
Where should I put Yogi's command? It seems to be a C code. But start.py is a python script.

**Comment by djhoese** [comment]
Yeah I think that has to be added to the backend. It was something that they were figuring out, but sounded like we could wait. Do you *need* remote display? Can you run vispy on your local machine?

Backends like PyQt5 may work better for you on a local machine. Using something like miniconda can simplify installing all of the packages (vispy is available from the conda-forge channel already).

**Comment by mahmoodn** [comment]
I will try to see if I can access local display. I will close the issue now. Thanks for the feedback.

**Comment by mahmoodn** [comment]
@djhoese  
What about applications such as anydesk, teamviewer and etc. ?

**Comment by djhoese** [comment]
I don't have any experience or knowledge of those applications. I would recommend testing basic visualizations on a local system and worrying about remote visualization after you've proven that vispy can render things locally. If you have trouble with installation I would recommend installing miniconda and using the conda-forge packages as mentioned before.

If you want to try remote visualization like you have been I would suggest trying a different backend like PyQt5 which is more heavily tested and up to date than EGL. If you need headless rendering then EGL is one option, but I don't have any experience getting it to work (@larsoner and @yogi81?).

**Comment by mahmoodn** [comment]
With local display, there is no problem and I don't get the error before. Thanks.
