### ISSUE TITLE
how to save visual object as image

### ISSUE THREAD

**Issue by yepengxj** [vispy/vispy#1690]
Is that possible save a visual object as a image

**Comment by djhoese** [comment]
You can use `from vispy.gloo.util import _screenshot` to save the currently displayed Canvas. So the answer is "yes", but to be clear you aren't saving a visual you are saving the Canvas (technically you are saving the contents of a drawing buffer but yeah).

**Comment by kmuehlbauer** [comment]
@yepengxj Is this still an issue for you?
