### ISSUE TITLE
[installation problem] GL version:  Empty

### ISSUE THREAD

**Issue by tonyyuandao** [vispy/vispy#1692]
**Problem symptom:**
I follow the installation instruction, and `print(vispy.sys_info())` returns:
> Platform: Windows-10-10.0.16299-SP0
Python:   3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
NumPy:    1.16.4
Backend:  ipynb_webgl
pyqt4:    None
pyqt5:    ('PyQt5', '5.9.2', '5.9.6')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   OSMesa
_test:    None
GL version:  ''
MAX_TEXTURE_SIZE: ()
Extensions: ''
App info-gathering error:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\vispy\util\config.py", line 438, in sys_info
    canvas.close()
  File "C:\Anaconda3\lib\site-packages\vispy\app\canvas.py", line 457, in close
    self._backend._vispy_close()
  File "C:\Anaconda3\lib\site-packages\vispy\app\backends\_ipynb_webgl.py", line 203, in _vispy_close
    raise NotImplementedError()
NotImplementedError

I ran `vispy.test()`, there were many canvas windows popup and disappeared immediately one after another, but all of them are black. 
And the final verdict is:
> Testing failed (['pyqt5', 'osmesa'] failed, ['pyqt4', 'pyside', 'pyside2', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'ipynb_webgl', '_test', 'examples'] skipped) in 112.475 seconds 

**My environment:** 
Fresh installation of Anaconda, python version 3.7.3
OpenGL and Graphic card(Intel & Nvidia, duel monitor connect to Intel card output)
![image](https://user-images.githubusercontent.com/32975930/62672989-47792000-b9cf-11e9-8970-9e8c2980be44.png)
![image](https://user-images.githubusercontent.com/32975930/62672918-054fde80-b9cf-11e9-83b8-81c01126699e.png)
![image](https://user-images.githubusercontent.com/32975930/62673052-77c0be80-b9cf-11e9-8737-08d40749701e.png)
![image](https://user-images.githubusercontent.com/32975930/62673116-c3736800-b9cf-11e9-83ad-fcd17412fa34.png)

**UPDATE:**
However, when I run some sample code, I do see a widget embedded in jupyter notebook showing the graph and I am able to interact with it although there's a significant lag between my maneuver and the graph's reaction. 
![image](https://user-images.githubusercontent.com/32975930/62678431-19520b00-b9e4-11e9-9801-1e1302680771.png)

It seems webgl is used, so I tried `%gui qt` before executing any other code, result is the same, nothing changes. 
What I really want to do is something similar to the realtime_signals.py demo. When I run it, a pitch black widget appeared, and GPU is active. 
![image](https://user-images.githubusercontent.com/32975930/62679890-7059df00-b9e8-11e9-89c4-29a008ae1ed4.png)

**Comment by tonyyuandao** [comment]
I figured it out and here is my solution:
1) First thing to do when open jupyter notebook: execute `%gui qt`
2) Use `vispy.use('PyQt5')` to switch backend to PyQt5 right after `import vispy`

Then everything seems normal:
> Platform: Windows-10-10.0.16299-SP0
Python:   3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
NumPy:    1.16.4
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.9.2', '5.9.6')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   OSMesa
_test:    None
GL version:  '4.5.0 - Build 24.20.100.6223'
MAX_TEXTURE_SIZE: 16384
Extensions: 'GL_3DFX_texture_compression_FXT1 GL_AMD_depth_clamp_separate GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility G...

The real-time plotting example works, impressive!!!
![image](https://user-images.githubusercontent.com/32975930/62683711-ac457200-b9f1-11e9-88a6-6d9141a20b71.png)


However `vispy.test()` still fails the same way.

**Comment by djhoese** [comment]
Is there a reason you are running things in a notebook? By default, vispy will figure out you are in a notebook and run things with the webgl/jupyter notebook backend. As mentioned at the bottom of the installation instructions for the [notebook extension](https://vispy.readthedocs.io/en/latest/installation.html#jupyter-notebook-extension) the webgl backend is experimental. It works, but as you've noticed it is very slow and laggy.

I would recommend running examples from the command line and not in a notebook to avoid any further issues. If you do this, the PyQt5 backend should be used by default based on what you've shown in `sys_info`.

As for the tests, the windows may appear black to you although some may actually be working. You should not run the tests from a notebook as not all vispy features are supported by the webgl backend. Additionally, some tests may not succeed on some environments or configurations or due to other edge cases.

**Comment by kmuehlbauer** [comment]
@djhoese Closing candidate? Should work now with `juypter_rfb` backend and `ipynb_webgl` removed.

**Comment by djhoese** [comment]
The PR to remove ipynb_webgl hasn't been merged yet, but jupyter_rfb is now the default in a notebook when installed. So I think this can be closed.
