### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by paulgoulain** [vispy/vispy#1704]
Hi everyone,

I'm trying to implement a live scroll widget to embedded into a PyQt5 program. My goal is to display in real time some values coming from scientific equipment.

Here is the code I have for now :

https://gist.github.com/paulgoulain/88eeb404932ae5c6bfb6228fa4949246

I'm currently using a QTimer to update the plot every 16ms which correspond to 62.5fps.
On different computer I have different performance level. On my work computer, the fps is capped at 60fps and it is stable. On my laptop, I can't go above 50 fps. Finally on my personal computer, which have a 240hz display, the fps is at 62.5 but drop after to while to end up at 15fps after several minutes.

Any idea why ?

**Comment by djhoese** [comment]
I don't see anything that is obvious to explain performance issues. A couple questions:

1. What version of python?
2. What version of pyqt?
3. What version of vispy?
4. What kind of performance differences do you see if you comment out the padding widget creation?
