### ISSUE TITLE
camera for app.Canvas?

### ISSUE THREAD

**Issue by pcpatfire** [vispy/vispy#1709]
Is it possible to use a camera for a class defined as "class Canvas(app.Canvas)"?

**Comment by djhoese** [comment]
No, sorry. The cameras system is built on top of the SceneCanvas transform interface(s).

**Comment by djhoese** [comment]
You *could* redefine a lot of the camera logic to work with a regular canvas, but it may be smarter/easier to port all of your regular Canvas GL logic to a Visual object which can be added to a SceneCanvas.

**Comment by pcpatfire** [comment]
I am new to Vispy. I was using the example from the gallery, demonstrating a cloud of points, as a basis for an application plotting the atoms of a huge crystal (more than 1600 atoms). I need to understand how to port the code to a Visual object. Thank you.

**Comment by djhoese** [comment]
You're using the `examples/demo/gloo/cloud.py` example right? Lucky for you there is a very similar example that uses the `Markers` (`MarkersVisual`) and uses a camera: `examples/basics/scene/point_cloud.py`.

**Comment by pcpatfire** [comment]
How can I set a different color for each marker?

**Comment by djhoese** [comment]
Please read the docstring for the MarkerVisual.set_data method. See `edge_color` and `face_color` specifically.

https://github.com/vispy/vispy/blob/master/vispy/visuals/markers.py#L509-L536

**Comment by pcpatfire** [comment]
Ok. They can be passed as arrays. Done. Thank you so much for your help!

**Comment by djhoese** [comment]
Just realized this was still open. Looks like we figured out what you needed.
