### ISSUE TITLE
Intersected visuals create defects (z-fighting?)

### ISSUE THREAD

**Issue by h3fang** [vispy/vispy#1716]
I am using vispy 0.6.1 from pypi, pyqt5 backend 5.9.2, linux.

For the following code

```python
import numpy as np
from vispy import scene
from vispy.scene.visuals import Sphere, Cube, XYZAxis
from vispy.visuals.transforms import STTransform

### canvas
canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), bgcolor='#efefef')

### view
view = canvas.central_widget.add_view()
view.camera = 'turntable'

### visuals
XYZAxis(parent=view.scene)

for i in range(10):
    c = Cube(size=0.1+np.random.rand(), color=np.random.rand(3), parent=view.scene)
    c.transform = STTransform(translate=np.random.randn(3))

for i in range(10):
    s = Sphere(radius=0.1+np.random.rand(), color=np.random.rand(3), parent=view.scene)
    s.transform = STTransform(translate=np.random.randn(3))

### run
canvas.show()
canvas.app.run()
```

I get something like this.

<img width="679" alt="vispy" src="https://user-images.githubusercontent.com/1715589/66541034-71ca9380-eb60-11e9-9795-91d9281724c1.png">

It's getting worse when I rotate the camera and looks like z-fighting.

How could I fix this?

**Comment by djhoese** [comment]
Which issue are you specifically worried about? That way the shapes are overlapping? If you zoom out does it look any better?

**Comment by djhoese** [comment]
@rougier Any idea how this can be improved?

**Comment by rougier** [comment]
I think it is a tesselation problem. When you intersect a sphere and a cube, the precision of the intersection depends on the tesselation level of the sphere and the cube. Can you try to have higher tesselation ?

**Comment by h3fang** [comment]
How can I use higher tessellation? There is no documentation about it.

I tried to increase the mesh density by using the following code

```python
c = Cube(size=0.1+np.random.rand(), width_segments=100, height_segments=100, depth_segments=100, color=np.random.rand(3), parent=view.scene)

s = Sphere(radius=0.1+np.random.rand(), cols=500, rows=500, depth=500, color=np.random.rand(3), parent=view.scene)
```

But it only slows the code significantly. The defects don't change much.

<img width="846" alt="screenshot_2019-10-12_15-30-37" src="https://user-images.githubusercontent.com/1715589/66697289-c3148780-ed06-11e9-888e-5a9e297284a0.png">

**Comment by rougier** [comment]
Stupid question: do you have a depth buffer activated ?
Can you reduce the number of objects to exactly and set their position manually such that we can have a better guess at what is going wrong ?

**Comment by h3fang** [comment]
There don't seem to be any arguments to explicitly set depth buffer for SceneCanvas.

The _draw_scene method of SceneCanvas does clear the depth buffer. So I guess it's enabled by default?

https://github.com/vispy/vispy/blob/165447d26d6c7da1a40df2c7ef547c5335b3c79b/vispy/scene/canvas.py#L265

I made a simpler test case.

```python
import numpy as np
from vispy import scene
from vispy.scene.visuals import Sphere, Cube, XYZAxis
from vispy.visuals.transforms import STTransform

### canvas
canvas = scene.SceneCanvas(keys='interactive', size=(800, 600), bgcolor='#efefef')

### view
view = canvas.central_widget.add_view()
view.camera = 'turntable'

### visuals
XYZAxis(parent=view.scene)

c1 = Cube(size=1, width_segments=100, height_segments=100, depth_segments=100, color="red", parent=view.scene)
c2 = Cube(size=1, width_segments=100, height_segments=100, depth_segments=100, color="blue", parent=view.scene)

s1 = Sphere(radius=0.5, cols=100, rows=100, color="green", parent=view.scene)
s2 = Sphere(radius=0.5, cols=100, rows=100, color="cyan", parent=view.scene)

c1.transform = STTransform(translate=(-0.3,0.3,0))
c2.transform = STTransform(translate=(0.3,0.3,0))

s1.transform = STTransform(translate=(-0.3,-0.3,0))
s2.transform = STTransform(translate=(0.3,-0.3,0))

### run
canvas.show()
canvas.app.run()
```

<img width="381" alt="screenshot_2019-10-12_18-28-20" src="https://user-images.githubusercontent.com/1715589/66699958-25c54d80-ed1e-11e9-9b4b-1767c48d39f9.png">

**Comment by rougier** [comment]
For the cubes, I think the rendering problem is expected because they have same size and theur surface coincide hence the problem. Can you make one of the two cubes smaller (.95) ?

**Comment by rougier** [comment]
For the spheres, you can try cols=10,rows=10 to check if the problem occurs at triangle intersection or elsewhere

**Comment by h3fang** [comment]
```python
c1 = Cube(size=1, width_segments=100, height_segments=100, depth_segments=100, color="red", parent=view.scene)
c2 = Cube(size=0.9, width_segments=100, height_segments=100, depth_segments=100, color="blue", parent=view.scene)

s1 = Sphere(radius=0.5, cols=10, rows=10, color="green", parent=view.scene)
s2 = Sphere(radius=0.5, cols=10, rows=10, color="cyan", parent=view.scene)
```

<img width="431" alt="screenshot_2019-10-12_19-34-47" src="https://user-images.githubusercontent.com/1715589/66700784-6d040c00-ed27-11e9-864a-8a87270b5ef9.png">

**Comment by rougier** [comment]
Can your try to add `config={'depth_size': 24}` in you SceneCanvas initialization?

**Comment by h3fang** [comment]
```python
canvas = scene.SceneCanvas(config={'depth_size': 24}, keys='interactive', size=(800, 600), bgcolor='#efefef')
```

<img width="372" alt="screenshot_2019-10-12_20-02-16" src="https://user-images.githubusercontent.com/1715589/66701124-35975e80-ed2b-11e9-8cfd-4afd47cea6d7.png">

**Comment by rougier** [comment]
+ `'depth_test': True` just in case but I'm out of ideas. I think it is a depth buffer problem but I can't identify the exact problem.

**Comment by h3fang** [comment]
```python
canvas = scene.SceneCanvas(config={'depth_size': 24, 'depth_test': True}, keys='interactive', size=(800, 600), bgcolor='#efefef')
```

```
Traceback (most recent call last):
  File "/home/enigma/projects/path-planning/test_vispy.py", line 7, in <module>
    canvas = scene.SceneCanvas(config={'depth_size': 24, 'depth_test': True}, keys='interactive', size=(800, 600), bgcolor='#efefef')
  File "/home/enigma/.local/miniconda3/envs/main/lib/python3.7/site-packages/vispy/scene/canvas.py", line 137, in __init__
    always_on_top, px_scale)
  File "/home/enigma/.local/miniconda3/envs/main/lib/python3.7/site-packages/vispy/app/canvas.py", line 191, in __init__
    self._context = GLContext(config, shared)
  File "/home/enigma/.local/miniconda3/envs/main/lib/python3.7/site-packages/vispy/gloo/context.py", line 100, in __init__
    self._set_config(config)
  File "/home/enigma/.local/miniconda3/envs/main/lib/python3.7/site-packages/vispy/gloo/context.py", line 116, in _set_config
    raise KeyError('Key %r is not a valid GL config key.' % key)
KeyError: "Key 'depth_test' is not a valid GL config key."
```

**Comment by h3fang** [comment]
I tried to enable depth_test like this.

```python
for v in [c1, c2, s1, s2]:
    v.set_gl_state(depth_test=True)
```

But nothing changed.

<img width="418" alt="screenshot_2019-10-12_20-46-34" src="https://user-images.githubusercontent.com/1715589/66701679-65496500-ed31-11e9-961c-81dfb28aad5a.png">

**Comment by h3fang** [comment]
That call should be the right one because if I set depth_test=False, I get.

<img width="365" alt="screenshot_2019-10-12_20-51-53" src="https://user-images.githubusercontent.com/1715589/66701732-236cee80-ed32-11e9-9260-a1c68a4b25fa.png">

**Comment by rougier** [comment]
Weird. Does it still work if you rotate the scene ?

**Comment by h3fang** [comment]
I don't understand your question.

If I disable depth_test and rotate, it works as intended, depth test is disabled.

**Comment by rougier** [comment]
If you disable depth test, the rendering order prevails and if the cyan ball (for example) is rendered last, it will cover everything else, independently of depth. If you rotate, you should observe "weird" rendering (cyan ball always front)

**Comment by h3fang** [comment]
Yes, it is always rendered last no matter how I rotate it.

**Comment by rougier** [comment]
I think it is a depth buffer problem or a projection error in the shader. Can you try to have two rotating cubes starting from from the rotate_cube.py demo and check if intersection is correct ?

**Comment by rougier** [comment]
```
import numpy as np
from vispy import app, gloo
from vispy.util.transforms import perspective, translate, rotate

vert = """
uniform   mat4 u_model;
uniform   mat4 u_view;
uniform   mat4 u_projection;
uniform   vec4 u_color;
attribute vec3 a_position;
attribute vec4 a_color;
attribute vec3 a_normal;
varying vec4 v_color;
void main()
{
    v_color = a_color * u_color;
    gl_Position = u_projection * u_view * u_model * vec4(a_position,1.0);
}
"""

frag = """
varying vec4 v_color;
void main()
{
    gl_FragColor = v_color;
}
"""


# -----------------------------------------------------------------------------
def cube():
    """
    Build vertices for a colored cube.

    V  is the vertices
    I1 is the indices for a filled cube (use with GL_TRIANGLES)
    I2 is the indices for an outline cube (use with GL_LINES)
    """
    vtype = [('a_position', np.float32, 3),
             ('a_normal', np.float32, 3),
             ('a_color', np.float32, 4)]
    # Vertices positions
    v = [[1, 1, 1], [-1, 1, 1], [-1, -1, 1], [1, -1, 1],
         [1, -1, -1], [1, 1, -1], [-1, 1, -1], [-1, -1, -1]]
    # Face Normals
    n = [[0, 0, 1], [1, 0, 0], [0, 1, 0],
         [-1, 0, 1], [0, -1, 0], [0, 0, -1]]
    # Vertice colors
    c = [[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0, 1, 0, 1],
         [1, 1, 0, 1], [1, 1, 1, 1], [1, 0, 1, 1], [1, 0, 0, 1]]

    V = np.array([(v[0], n[0], c[0]), (v[1], n[0], c[1]),
                  (v[2], n[0], c[2]), (v[3], n[0], c[3]),
                  (v[0], n[1], c[0]), (v[3], n[1], c[3]),
                  (v[4], n[1], c[4]), (v[5], n[1], c[5]),
                  (v[0], n[2], c[0]), (v[5], n[2], c[5]),
                  (v[6], n[2], c[6]), (v[1], n[2], c[1]),
                  (v[1], n[3], c[1]), (v[6], n[3], c[6]),
                  (v[7], n[3], c[7]), (v[2], n[3], c[2]),
                  (v[7], n[4], c[7]), (v[4], n[4], c[4]),
                  (v[3], n[4], c[3]), (v[2], n[4], c[2]),
                  (v[4], n[5], c[4]), (v[7], n[5], c[7]),
                  (v[6], n[5], c[6]), (v[5], n[5], c[5])],
                 dtype=vtype)
    I1 = np.resize(np.array([0, 1, 2, 0, 2, 3], dtype=np.uint32), 6 * (2 * 3))
    I1 += np.repeat(4 * np.arange(2 * 3, dtype=np.uint32), 6)

    I2 = np.resize(
        np.array([0, 1, 1, 2, 2, 3, 3, 0], dtype=np.uint32), 6 * (2 * 4))
    I2 += np.repeat(4 * np.arange(6, dtype=np.uint32), 8)

    return V, I1, I2


# -----------------------------------------------------------------------------
class Canvas(app.Canvas):

    def __init__(self):
        app.Canvas.__init__(self, keys='interactive', size=(800, 600))

        self.vertices, self.filled, self.outline = cube()
        self.filled_buf = gloo.IndexBuffer(self.filled)
        self.outline_buf = gloo.IndexBuffer(self.outline)
        self.program = gloo.Program(vert, frag)
        self.program.bind(gloo.VertexBuffer(self.vertices))
        self.view = translate((0, 0, -5))
        self.model = np.eye(4, dtype=np.float32)
        gloo.set_viewport(0, 0, self.physical_size[0], self.physical_size[1])
        self.projection = perspective(45.0, self.size[0] /
                                      float(self.size[1]), 2.0, 10.0)
        self.program['u_projection'] = self.projection
        self.program['u_model'] = self.model
        self.program['u_view'] = self.view

        self.theta = 0
        self.phi = 0

        gloo.set_clear_color('white')
        gloo.set_state('opaque')
        gloo.set_polygon_offset(1, 1)

        self.show()


    # ---------------------------------
    def on_resize(self, event):
        gloo.set_viewport(0, 0, event.physical_size[0], event.physical_size[1])
        self.projection = perspective(45.0, event.size[0] /
                                      float(event.size[1]), 2.0, 10.0)
        self.program['u_projection'] = self.projection

    # ---------------------------------
    def on_draw(self, event):
        gloo.clear()

        model = np.dot(rotate(self.theta, (0, 1, 0)),
                       rotate(self.phi, (0, 0, 1)))
        self.program['u_model'] = model

        # Filled cube
        gloo.set_state(blend=False, depth_test=True, polygon_offset_fill=True)
        self.program['u_color'] = 1, 1, 1, 1
        self.program.draw('triangles', self.filled_buf)
        # Outline
        gloo.set_state(blend=True, depth_test=True, polygon_offset_fill=False)
        gloo.set_depth_mask(False)
        self.program['u_color'] = 0, 0, 0, 1
        self.program.draw('lines', self.outline_buf)
        gloo.set_depth_mask(True)


        model = np.dot(rotate(self.theta+25, (0, 1, 0)),
                       rotate(self.phi+65, (0, 0, 1)))
        self.program['u_model'] = model

        # Filled cube
        gloo.set_state(blend=False, depth_test=True, polygon_offset_fill=True)
        self.program['u_color'] = 1, 1, 1, 1
        self.program.draw('triangles', self.filled_buf)
        # Outline
        gloo.set_state(blend=True, depth_test=True, polygon_offset_fill=False)
        gloo.set_depth_mask(False)
        self.program['u_color'] = 0, 0, 0, 1
        self.program.draw('lines', self.outline_buf)
        gloo.set_depth_mask(True)



# -----------------------------------------------------------------------------
if __name__ == '__main__':
    c = Canvas()
    app.run()
```

**Comment by h3fang** [comment]
The code above works and the intersection is correct.

<img width="557" alt="screenshot_2019-10-13_15-16-59" src="https://user-images.githubusercontent.com/1715589/66712262-84490500-edcc-11e9-80e4-0b47df3b4fc7.png">

**Comment by rougier** [comment]
I've found this potential explanation: https://www.khronos.org/opengl/wiki/Depth_Buffer_Precision

@djhoese Do you know how to access the znear/zfar of the projection matrix?

**Comment by djhoese** [comment]
The `GLContext` object should have access to the `set_depth_range` method:

https://github.com/vispy/vispy/blob/8b61cd439076aa3f50ac5f6dacb4c0af8c1d0684/vispy/gloo/wrappers.py#L113-L123

So `canvas.context.set_depth_range(near, far)` should allow you to change it.

**Comment by rougier** [comment]
I did some tests and I think the camera might be wring because if you set the near plane to 1, you see nothing. It is quite usual to move the whole scene away from cam such as to have a near plane of 1 and maybe avoid the z-buffer precision problem. I looked at the turntable code and I'm unable to understand how it works.

**Comment by h3fang** [comment]
I guess these lines caused the problem

https://github.com/vispy/vispy/blob/8b61cd439076aa3f50ac5f6dacb4c0af8c1d0684/vispy/scene/cameras/perspective.py#L169-L170

And the default `fov` for `TurnTableCamera` is `0.0`

https://github.com/vispy/vispy/blob/8b61cd439076aa3f50ac5f6dacb4c0af8c1d0684/vispy/scene/cameras/turntable.py#L56-L58

I simply set the `fov` for `TurnTableCamera` to `45.0`, the defects are gone.

```python
view.camera = scene.TurntableCamera(fov=45.0)
```

And my little project came back to life as well. Thanks.

**Comment by djhoese** [comment]
Whoa, interesting. So just changing the FOV fixed these issues. That makes me think there is a transform bug somewhere (especially since you point out the `set_ortho` call causing issues). We'll have to look in to this if others have problems with this in the future (don't have time right now).

**Comment by rougier** [comment]
Setting a default `fov=45.0` in the turntable init function might be a temporary fix.

**Comment by djhoese** [comment]
@larsoner @kmuehlbauer Any experience with the Turntable Camera? I've never used it in my own work. Would changing the default fov be a problem for users? I'm guessing it would change the default view of a couple of our example scripts.

**Comment by rougier** [comment]
You're right. But transforming the perspective projection into an ortho projection when fovy=0 is not good either. @h3fang can you open a new issue for the turntable default fovy=0 such that we do not forget this issue ?

**Comment by larsoner** [comment]
I've used it but don't have a strong opinion. I'd defer to @rougier's recommendation here

**Comment by h3fang** [comment]
@rougier I opened a new issue for the default `fov=0` problem.

**Comment by rougier** [comment]
Thanks
