### ISSUE TITLE
How vispy use for real time data plotting 

### ISSUE THREAD

**Issue by manojprasanga** [vispy/vispy#1726]
This is actually not a issue.I am working on vispy with wxpython gui project  for real time  data monitoring and plotting.This is for input data came as numpy 3D coordinates array.Is any one working like this project? Is any ressourses?

**Comment by djhoese** [comment]
I am personally not working on something like you are, but could you give more detail about exactly what you're doing? What are you displaying on the screen? The vispy examples directory in the root of the repository are the best starting point. If you run in to issues or questions feel free to make a new issue (I would first search the existing or closed issues for an issue like you have).

Good luck.

**Comment by manojprasanga** [comment]
Iam real ttime CNC simulator pproject
