### ISSUE TITLE
Python 3.8 RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by dzusan** [vispy/vispy#1729]
`windows`, `vispy 0.6.1`, `x64`

When I have installed python 3.7, vispy 0.6.1 was built successfully with minimal Microsoft Visual C++ 14.0 Build Tools during pip install. And my application ran great.

Now I have python 3.8, and vispy pip installation process fails with the errors. OK, I downloaded .whl from https://www.lfd.uci.edu/~gohlke/pythonlibs and installed successfully. Then I started my app and it crashed with the following:

```
  File "C:\Python38\lib\site-packages\vispy\scene\canvas.py", line 134, in __init__
    super(SceneCanvas, self).__init__(
  File "C:\Python38\lib\site-packages\vispy\app\canvas.py", line 194, in __init__
    self._set_keys(keys)
  File "C:\Python38\lib\site-packages\vispy\app\canvas.py", line 249, in _set_keys
    for key, val in keys.items():
RuntimeError: dictionary keys changed during iteration
```

**Comment by djhoese** [comment]
Looks like you're right. This should probably be updated to create a new dictionary. Pull requests welcome!

**Comment by dzusan** [comment]
Wow, I'm afraid, I have no enough qualification for pull request... although might I will try later. For now I solved the problem in easy mode.

My app called `scene.SceneCanvas.__init__` with `keys='interactive'` and if I remove this argument, it's works as fine as before.

**Comment by djhoese** [comment]
Let me know if you need any help (github has some nice guides somewhere). Otherwise, I've marked this as "hacktoberfest" so anyone needing some last minute pull requests to get their t-shirt will find this more easily.
