### ISSUE TITLE
How to programatically resize the canvas?

### ISSUE THREAD

**Issue by parsoyaarihant** [vispy/vispy#1731]
Is it possible to programatically resize the canvas during runtime? Instead of resizing the window using mouse cursor.

**Comment by GuillaumeFavelier** [comment]
If you're talking about a `SceneCanvas`, I know that it is possible to use the [`size` setter](https://github.com/vispy/vispy/blob/master/vispy/app/canvas.py#L339-L342) inherited from [`vispy.app.Canvas`](http://vispy.org/app.html?highlight=app%20canvas#vispy.app.Canvas)

Here is an example:
```py
from vispy import scene, app
canvas = scene.SceneCanvas(size=(800, 600), show=True) # initial size here

canvas.size = (1000, 300) # <<<< changing the size here

view = canvas.central_widget.add_view()
view.camera = scene.cameras.ArcballCamera(fov=60, parent=view.scene)
scene.visuals.Sphere(shading='flat', parent=view.scene)
app.run()
```

**Comment by djhoese** [comment]
@parsoyaarihant I'm curious, what are you doing that needs this?

Yes, it should be possible as @GuillaumeFavelier pointed out. Normally though I think Vispy leaves it up to the backend GUI framework to change the size. For example, in PyQt5 you would resize the parent of the native canvas Qt widget (the QMainWindow or the QWidget, whichever you've set as parent for your GUI) and the Vispy canvas responds to the resize events.

**Comment by queenish001** [comment]
@parsoyaarihant Is your doubt resolved?

**Comment by djhoese** [comment]
I stand by my previous comment that this should be controlled by the GUI framework or with the `.size` property of the canvas (which may or may not conflict with the layout policy of the GUI backend).
