### ISSUE TITLE
How create canvas on wx  panel

### ISSUE THREAD

**Issue by manojprasanga** [vispy/vispy#1732]
Im trying to do vispy canvas create on wx panel.But it show following error
"AttributeError: 'App' object has no attribute 'Canvas'".
Whats wrong in this.

    import wx
    from vispy import app, gloo, scene, visuals
    import time
    import timeit
    import websocket
    ws = websocket.WebSocket()
    ws.connect("ws://192.168.8.102/")
   
    def splitdat():   #Data split
        global MState
        global MPosX
        global MPosY
        global MPosZ
    
        global WPosX
        global WPosY
        global WPosZ
    
        
        data1 = result.split(",")
        MState = data1[0] #machine state
        MPos_MPosX = data1[1] #MPos:0.000
        MPosY = data1[2] #Y
        MPosZ = data1[3] #Z
        WPos_WPosX = data1[4] #WPos:0.000
        WPosY = data1[5] #Y
        WPosZ = data1[6] #Z
    
        data2 = MPos_MPosX.split(":")
        MPos = data2[0]
        MPosX = data2[1]#Machine coordinates X
    
        data3 = WPos_WPosX.split(":")
        WPos = data3[0]
        WPosX = data3[1]#Work coordinates X
    
    
    ##def dat_on_rec(self,event):
    ##    global result
    ##    result = ws.recv()
    ##    splitdat()
    
    
    
        
    class Canvas(app.Canvas):
        def __init__(self, *a, **k):
            app.Canvas.__init__(self, *a, **k ,size=(800,600))
            view = self.central_widget.add_view()
            view.bgcolor = 'white'
            view.camera =scene.TurntableCamera(up= '+y' , azimuth=100, elevation=15, fov=60)
            axis =scene.visuals.XYZAxis(parent=view.scene)
            self.canvas = Canvas(app="wx", parent=self)
            self.show()
    
            
    class panel_1(wx.Panel):
        def __init__(self, *a, **k):
            wx.Panel.__init__(self, *a, **k,)
            self.SetBackgroundColour(wx.WHITE)
            self.canvas = Canvas(app="wx", parent=self)
    
               
    
    class panel_2(wx.Panel):
        def __init__(self, *a, **k):
            wx.Panel.__init__(self, *a, **k,size=(150,400))
            self.SetBackgroundColour(wx.WHITE)
            self.initialize()
    
    
        def initialize(self):
            self.lb1=wx.StaticText(self, -1,label='Machine State :idle',pos=(20, 30))
            self.lb2=wx.StaticText(self, -1,label='Machine Coordinates',pos=(20, 90))
            self.lb3=wx.StaticText(self, -1,label='X :0.0000',pos=(20, 110))
            self.lb4=wx.StaticText(self, -1,label='Y :0.0000',pos=(20, 130))
            self.lb5=wx.StaticText(self, -1,label='Z :0.0000',pos=(20, 150))
            self.lb6=wx.StaticText(self, -1,label='Work Coordinate',pos=(20, 190))
            self.lb7=wx.StaticText(self, -1,label='X :0.0000',pos=(20, 210))
            self.lb8=wx.StaticText(self, -1,label='Y :0.0000',pos=(20, 230))
            self.lb9=wx.StaticText(self, -1,label='Z :0.0000',pos=(20, 250))
            self.timer = wx.Timer(self)
            self.Bind(wx.EVT_TIMER,self.dat_on_rec, self.timer)
            self.timer.Start(100)
            self.Show(True)
    
        def dat_on_rec(self,event):
            global result
            result = ws.recv()
            splitdat()
    
            self.lb1.SetLabel('Machine State :' + str(MState))
    #        self.lb2.SetLabel('Machine Coordinates')
            self.lb3.SetLabel('X :'+str(MPosX))
            self.lb4.SetLabel('Y :' + str(MPosY))
            self.lb5.SetLabel('Z :' + str(MPosZ))
            self.lb6.SetLabel('Work Coordinate')
            self.lb7.SetLabel('X :' + str(WPosX))
            self.lb8.SetLabel('Y :' + str(WPosY))
            self.lb9.SetLabel('Z :' + str(WPosZ))
    
    
                  
    class MyFrame(wx.Frame):
        def __init__(self, *a, **k):
            wx.Frame.__init__(self, *a, **k, title=" CNC simulator ", size=(800, 600))
    
            box = wx.BoxSizer(wx.HORIZONTAL)
    
            panel1 = panel_1(self)
            box.Add(panel1, 1, wx.EXPAND)
    
            box2 = wx.BoxSizer(wx.VERTICAL)
            box.Add(box2, 0, wx.EXPAND)
    
            panel2 = panel_2(self)
            box2.Add(panel2, 1, wx.EXPAND)
    
            self.SetAutoLayout(True)
            self.SetSizer(box)
            self.Layout()
    
    
    
    
    
    if __name__ == '__main__':
        app = wx.App(True)
        frame = MyFrame(None)
        frame.Show()
        app.MainLoop()

**Comment by djhoese** [comment]
You are overwriting your `app` variable (the vispy module you import) with your `wx.App` at the bottom.

**Comment by manojprasanga** [comment]
What does it mean sir.How i change the code

**Comment by djhoese** [comment]
At the top of your file you are importing the `app` object from vispy:

```
from vispy import app, gloo, scene, visuals
```

Later in your file you do:

```

if __name__ == '__main__':
    app = wx.App(True)
    frame = MyFrame(None)
    frame.Show()
    app.MainLoop()
```

See how you are creating a variable named `app` again? Later in the program your code is using the variable named `app`:

```
app.Canvas.__init__(self, *a, **k ,size=(800,600))
```

This code **expects** the vispy `app` but it is getting the `wx.App(True)` version of `app`.

Solution: Rename your `app = wx.App(True)` to `wx_app` and change `app.MainLoop()` to `wx_app.MainLoop()`.

**Comment by manojprasanga** [comment]
Thank you sir for your immediate response.
