### ISSUE TITLE
How create coordinates system in vispy canvas

### ISSUE THREAD

**Issue by manojprasanga** [vispy/vispy#1733]
I need to create 3D coordinates system in vispy canvas.how do that?

**Comment by kmuehlbauer** [comment]
Please use the [advertised communication channels](http://vispy.org/community.html) depending to your problem. You can also write to the vispy googlegroups (https://groups.google.com/forum/#!forum/vispy)

This is an issue and bug tracker which is not intended for those kind of questions.

**Comment by kmuehlbauer** [comment]
Discussion moved to [google groups](https://groups.google.com/forum/#!msg/vispy/pHd8tcpMASI/SZZTPy0gDAAJ)
