### ISSUE TITLE
Problem with wxpython and vispy combined GUI

### ISSUE THREAD

**Issue by manojprasanga** [vispy/vispy#1735]
Iam create GUI using vispy canvas integrated into wxpython.My problem is when, i zoom the canvas GUI stuck or zooming speed very slowly.Why this happened ?

**Comment by djhoese** [comment]
@manojprasanga Please provide some details. We can't know everything your application is doing based only on it being a wxpython application.

What operating system?
What version of vispy?
Can you give us a simple reproducible example program (python code) that shows this issue?

Help us to help you by providing as much information as you can. The more we understand of your situation the easier it is to help.

**Comment by manojprasanga** [comment]
Sir my PC OS is windows10
Vispy version is  0.6.1
python code: 
import wx
from vispy import app, gloo, scene, visuals


import websocket
import time
ws = websocket.WebSocket()
ws.connect("ws://192.168.8.101/")


##
##def recdat():
##    global result
##    while True:
##        result = ws.recv()
##        print(result)




        
def splitdat():
    global MState
    global MPosX
    global MPosY
    global MPosZ

    global WPosX
    global WPosY
    global WPosZ

    
    data1 = result.split(",")
    MState = data1[0] #machine state
    MPos_MPosX = data1[1] #MPos:0.000
    MPosY = data1[2] #Y
    MPosZ = data1[3] #Z
    WPos_WPosX = data1[4] #WPos:0.000
    WPosY = data1[5] #Y
    WPosZ = data1[6] #Z

    data2 = MPos_MPosX.split(":")
    MPos = data2[0]
    MPosX = data2[1]#Machine coordinates X

    data3 = WPos_WPosX.split(":")
    WPos = data3[0]
    WPosX = data3[1]#Work coordinates X


    
    


class Canvas(scene.SceneCanvas):
    def __init__(self, *a, **k):
        scene.SceneCanvas.__init__(self, *a, **k ,size=(800,600))
        view = self.central_widget.add_view()
        view.bgcolor = 'white'
        view.camera =scene.TurntableCamera(up= '+y' , azimuth=100, elevation=15, fov=60)
        axis =scene.visuals.XYZAxis(parent=view.scene)
        self.show()


class my_panel_1(wx.Panel):
    def __init__(self, *a, **k):
        wx.Panel.__init__(self, *a, **k,)
        self.SetBackgroundColour(wx.WHITE)
        self.canvas = Canvas(app="wx", parent=self)

class my_panel_2(wx.Panel):
    def __init__(self, *a, **k):
        wx.Panel.__init__(self, *a, **k, size=(150,400))
        self.SetBackgroundColour(wx.WHITE)

        lb1=wx.StaticText(self, -1,pos=(20, 30))
        lb1.SetLabel('Machine State :' + str(MState))

        lb2=wx.StaticText(self, -1,pos=(20, 90))
        lb2.SetLabel('Machine Coordinates')
        
        lb3=wx.StaticText(self, -1,pos=(20, 110))
        lb3.SetLabel("X :"+str(MPosX))

        lb4=wx.StaticText(self, -1,pos=(20, 130))
        lb4.SetLabel('Y :' + str(MPosY))

        lb5=wx.StaticText(self, -1,pos=(20, 150))
        lb5.SetLabel('Z :' + str(MPosZ))

        lb6=wx.StaticText(self, -1,pos=(20, 190))
        lb6.SetLabel('Work Coordinate')
        
        lb7=wx.StaticText(self, -1,pos=(20, 210))
        lb7.SetLabel('X :' + str(WPosX))

        lb8=wx.StaticText(self, -1,pos=(20, 230))
        lb8.SetLabel('Y :' + str(WPosY))

        lb9=wx.StaticText(self, -1,pos=(20, 250))
        lb9.SetLabel('Z :' + str(WPosZ))

              
class MyFrame(wx.Frame):
    def __init__(self, *a, **k):
        wx.Frame.__init__(self, *a, **k, title="Remote Real Time CNC simulator ", size=(800, 600))

        box = wx.BoxSizer(wx.HORIZONTAL)

        panel1 = my_panel_1(self)
        box.Add(panel1, 1, wx.EXPAND)

        box2 = wx.BoxSizer(wx.VERTICAL)
        box.Add(box2, 0, wx.EXPAND)

        panel2 = my_panel_2(self)
        box2.Add(panel2, 1, wx.EXPAND)

        self.SetAutoLayout(True)
        self.SetSizer(box)
        self.Layout()





if __name__ == '__main__':

    global result
    while True:
        result = ws.recv()
        splitdat()
        app = wx.App(True)
        frame = MyFrame(None)
        frame.Show()
        app.MainLoop()


#ws.close()

**Comment by manojprasanga** [comment]
Sir my PC OS is win10
vispyversion is   0.6.1
python code:
[pyrhon code.txt](https://github.com/vispy/vispy/files/3778497/pyrhon.code.txt)

**Comment by djhoese** [comment]
Nothing about your code seems "bad" that would effect performance. I'm not sure you need the `while True` loop at the bottom though. Have you tried running your code without all the websocket stuff? I'm having trouble getting wxpython to work on my computer so I can't test this right now.

**Comment by manojprasanga** [comment]
I'll try sir thank you

**Comment by queenish001** [comment]
@manojprasanga Is you query resolved?

**Comment by djhoese** [comment]
Given the age of this issue, I'm going to close this. We can reopen if it is still an issue. If someone else other than @manojprasanga hits this issue, please create a new issue with your own details.
