### ISSUE TITLE
Surface plot (height map) from image 

### ISSUE THREAD

**Issue by brunoeducsantos** [vispy/vispy#1737]
Hi,
I am very beginner with vispy. My question is : Is it possible to load a image as a surface plot?
I checked that vispy allow to load image and draw surface plot from coordinate points. Although, I could not find a way to use a image and pixel intensity to draw a surface plot.

Thanks,

Bruno

**Comment by djhoese** [comment]
There is a `surface` plotting method in the plotting API. This uses the `SurfacePlotVisual`, http://vispy.org/visuals.html#vispy.visuals.SurfacePlotVisual, which you can access directly if you don't need all the extra "stuff" involved with the plotting API.

**Comment by brunoeducsantos** [comment]
Thanks @djhoese  for your feedback.
I wrote something like this:


```
from  vispy.visuals import SurfacePlotVisual
import vispy.scene
import vispy.io as vp

canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)
view = canvas.central_widget.add_view()

data= vp.imread("/home/bruno/maps_database/heightmap.png")

surf = SurfacePlotVisual(x=)


```

Maybe it is a silly question, but how can I get **x , y , z** to fill the surfaceplot ?
Thanks,
Bruno

**Comment by djhoese** [comment]
I'm not familiar with what you're doing and what the data is in `heightmap.png` but it seems you are only using the last value of the image/color data.

But more importantly, the `z` array is meant to be 2D, not 1D. The `x` and `y` are 1D so `x = np.arange(width)` and `y = np.arange(height)` should work for those. The `z` can probably be done `z = data[:, :, 3]` if that's really what you want. However, in an RGBA image this would mean you are only holding on to the transparency/alpha channel.

**Comment by brunoeducsantos** [comment]
Should it be something like:
`surf = vs.SurfacePlotVisual(z=z_h,parent=view.scene)`

**Comment by djhoese** [comment]
You shouldn't need to do `canvas.view` (or the `canvas.unfreeze` call). Otherwise I *think* what you have should work. Another option would be to create your `SurfacePlotVisual` with `parent=view.scene`.

**Comment by brunoeducsantos** [comment]
If I do like this:
```

canvas = scene.SceneCanvas(keys='interactive', show=True)
data= vp.imread("/home/bruno/maps_database/heightmap.png")
z_h= data[:,:,2]

# This time we add a ViewBox to let the user zoom/pan
view = canvas.central_widget.add_view()
view.camera = 'turntable'
view.camera.rect = (0, 0, 800, 800)
surf = vs.SurfacePlotVisual(z=z_h)
view.add(surf)

axis = scene.visuals.XYZAxis(parent=view.scene)

```

I got the following error:
`
AttributeError: 'parent' is not an attribute of class <vispy.visuals.surface_plot.SurfacePlotVisual object at 0x7f481d5a5470>. Call "unfreeze()" to allow addition of new attributes
`

**Comment by brunoeducsantos** [comment]
Thanks for your feedback.

**Comment by brunoeducsantos** [comment]
It working now. Thanks for your help!
