### ISSUE TITLE
axis labels problem

### ISSUE THREAD

**Issue by pcpatfire** [vispy/vispy#1742]
I was using the plot.py example and I got the following problems:
1. the xaxis labels are overlapped to the x axis
2. the xaxis labels values do not correspond to the actual x axis domain; they are adjusted to the correct values after resizing the window.
3. some other problems with yaxis labels and title (see attached picture)

![plot_py_screenshot](https://user-images.githubusercontent.com/50824984/68126482-34191a80-ff14-11e9-9690-9885c0ddc735.JPG)

**Comment by djhoese** [comment]
Some of this seems like the default font size is too large. We've seen the ticks not updating issue before, but I thought we fixed it. What backend are you using?

**Comment by djhoese** [comment]
Here is what it looks like with the current master branch on my Ubuntu system with PyQt5:

![image](https://user-images.githubusercontent.com/1828519/68128912-3ceef980-fede-11e9-9442-3f34bbb2685c.png)

**Comment by pcpatfire** [comment]
I am using PyQt5 on Windows 10. Yes there is also a font size problem. It would be better if the axis_font_size and the tick_font_size could be set from the user application. 
Your plot is better than mine, but, as you can see, the x axis labels are wrong (they should be from 0 to 10) and they touch the tick marks.

**Comment by djhoese** [comment]
You're right about the ticks being wrong. I guess this is still an issue.

The tick labels touching the tick marks may be something that has always existed and was never completely made to look "perfect". @larsoner may remember more.

**Comment by pcpatfire** [comment]
As I noticed that if you move the plot the xaxis is updated with the correct tick labels, I was trying to force an xaxis update setting _need_update=True and calling the update() method, but it didn't work. 

```
fig[0,0].xaxis.axis._need_update = True
fig[0,0].xaxis.axis.update()
```

**Comment by djhoese** [comment]
If I remember correctly, the last time this came up it was caused by a race condition where the ticks would be updated to the correct values and then immediately set back to the incorrect (initial) values. I'm sorry I don't have time to look in to it more right now.

**Comment by pcpatfire** [comment]
Thank you for the link to the bug fixes related to AxisVisual. They seem to concern some other problems.
In my Qt application I found that the x axis domain is correct until the show() method is called. After, it gets wrong. If I update the plot after the show() method is executed, the x axis domain is correct.
Something happens while executing the show() method. 
A strange thing is that only the x axis has this kind of problems.

**Comment by djhoese** [comment]
Yeah, I think I've tried to fix this bug in the past, but never found the real problem or maybe it was that it didn't have an easy solution. Like I mentioned I think it has to do with a basic default x range being set *after* the real data's x range is already set. Solving this bug will require walking through the code and finding when the domain is updated and from where (is it a default value, is it from the data, did the user set it, etc). I won't have time to look in to this any time soon though.

**Comment by pcpatfire** [comment]
This is the code

```
        print('(plot-1) xaxis domain:', self.plot.ax.xaxis.axis.domain)
        print('(plot-1) yaxis domain:', self.plot.ax.yaxis.axis.domain)
       
        self.show()
        
        print('(plot-2) xaxis domain:', self.plot.ax.xaxis.axis.domain)
        print('(plot-2) yaxis domain:', self.plot.ax.yaxis.axis.domain)
        
        self.plot.update_view()
        
        print('(plot-3) xaxis domain:', self.plot.ax.xaxis.axis.domain)
        print('(plot-3) yaxis domain:', self.plot.ax.yaxis.axis.domain)
```

This is the output:

```
(plot-1) xaxis domain: (-3.435610274790101, 3.098064060261222)
(plot-1) yaxis domain: (-0.8999991856813033, 18.900001782059757)
(plot-2) xaxis domain: (-5.046775266898924, -4.957760627687946)
(plot-2) yaxis domain: (-0.8999998271748488, 18.900000467268093)
(plot-3) xaxis domain: (-3.435610297180214, 3.0980642209056075)
(plot-3) yaxis domain: (-0.8999998271748488, 18.900000467268093)
```
The plot-2 x axis domain is the wrong one.

**Comment by pcpatfire** [comment]
The solution I found for my application is not so elegant, but I am satisfied with it. The user will not see the bug anyway.
