### ISSUE TITLE
How can I update plot on this code in a for loop?

### ISSUE THREAD

**Issue by JasonACDsouza** [vispy/vispy#1747]
I have a realtime data coming in with almost 5m points per frame and I want to visualize frames by clearing the old plot. How do I achieve it using this code or any other?

```
import numpy as np
import vispy.scene
from vispy.scene import visuals

canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)
view = canvas.central_widget.add_view()

pos = np.random.normal(size=(100000, 3), scale=0.2)

centers = np.random.normal(size=(50, 3))
indexes = np.random.normal(size=100000, loc=centers.shape[0]/2.,
                           scale=centers.shape[0]/3.)
indexes = np.clip(indexes, 0, centers.shape[0]-1).astype(int)
scales = 10**(np.linspace(-2, 0.5, centers.shape[0]))[indexes][:, np.newaxis]
pos *= scales
pos += centers[indexes]

scatter = visuals.Markers()
scatter.set_data(pos, edge_color=None, face_color=(1, 1, 1, .5), size=5)

view.camera = 'arcball'  # or try 'arcball'

axis = visuals.XYZAxis(parent=view.scene)
view.add(scatter)
view.update()

if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
```

**Comment by kmuehlbauer** [comment]
@JasonACDsouza Did you have a look at the examples, yet?

**Comment by JasonACDsouza** [comment]
> @JasonACDsouza Did you have a look at the examples, yet?

Hi @kmuehlbauer , I did see the examples but could not find anything, could you possibly share a link to the specific example which shows the use in a for loop for plot updates?

Thanks.

**Comment by wgnu6** [comment]
Do this:
```
def update(event):
    scatter.set_data(pos, ...)

timer = app.Timer()
timer.connect(update)
timer.start()
```

**Comment by JasonACDsouza** [comment]
@wgnu6 That worked!!! However, while plotting in realtime I see that the plots become slower and slower as it progresses. Starts off with ~70ms for 5 million points and goes down to ~500ms and further as it progresses. Is there a way to keep it stable for every time a pointcloud is refreshed?

**Comment by djhoese** [comment]
@JasonACDsouza Can you show us what your full code looks like now? Also, if you monitor the process on your system as it runs what happens? I'm guessing the memory usage gets bigger and bigger? You or vispy might be holding on to memory you don't mean to be holding on to.

**Comment by JasonACDsouza** [comment]
@djhoese This is what the code looks like now and yes I think it is vispy holding on to the memory to which I am trying to find a work around but I maybe wrong.
`import numpy as np
import vispy.scene
from vispy.scene import visuals
from vispy import app
import glob
import time

pclds = glob.glob("/media/jolton/LaCie/data_jolton/*.npz")
canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)

view = canvas.central_widget.add_view()

scatter = visuals.Markers()


def update(event):
	global start

	print('time taken per frame', time.time() - start)
	for pcld in pclds:
		pcld = np.load(pcld)
		pcld = pcld['Pts_mtx']

		# pos = np.random.normal(size=(500000, 3), scale=0.2)
		colr = np.random.uniform(low=0, high=1, size=(524288,3))

		# centers = np.random.normal(size=(50, 3))
		# indexes = np.random.normal(size=524288, loc=centers.shape[0]/2.,
		#                            scale=centers.shape[0]/3.)
		# indexes = np.clip(indexes, 0, centers.shape[0]-1).astype(int)
		# scales = 10**(np.linspace(-2, 0.5, centers.shape[0]))[indexes][:, np.newaxis]
		# pos *= scales
		# pos += centers[indexes]

		
		scatter.set_data(pcld, edge_color=(0.5, 0.1, 0, .5), face_color=colr, size=5)
		view.camera = 'arcball'  # or try 'arcball'

		# add a colored 3D axis for orientation
		axis = visuals.XYZAxis(parent=view.scene)
		view.add(scatter)
		start = time.time()
		break


timer = app.Timer()
start = time.time()
timer.connect(update)
timer.start(0.05)


if __name__ == '__main__':
	import sys
	if sys.flags.interactive != 1:
		vispy.app.run()`

**Comment by djhoese** [comment]
Just to make sure, what version of vispy are you running? There was a fix in version 0.6 I think that cut out at least one memory leak in vispy.

**Comment by djhoese** [comment]
Is there a reason you are setting the camera and creating a new axis *every* update and for *every* data file?

**Comment by djhoese** [comment]
To clarify, you are creating new visuals every update and for every iteration of that loop and adding them to the Scene. This is adding new children to the SceneCanvas but **not** deleting the old children.

You should create the visuals, add them to the Scene **once** outside of the update function, and then the update function should only be calling `set_data` on the visual(s) and a final `canvas.update()` at the end.

**Comment by JasonACDsouza** [comment]
> Is there a reason you are setting the camera and creating a new axis _every_ update and for _every_ data file?

Oh I found I was making a silly mistake of creating it inside but now it works real time!! Thank you!!!

**Comment by JasonACDsouza** [comment]
Hi @djhoese,

Is there a way where I can pass data to my **update** function from outside of its scope? I tried passing in a **queue**  but the update function is not able to see it. 

When I run the `vispy.app.run()` it goes into a loop and runs the update function back again.
Now, my requirement is that each time it runs the update function, it should read from a memory 'queue' and update the plot from the content in the queue that I am updating in a separate process on the outside of the update function. Multiprocessing in this scenario is not understood clearly to me. Could you guide on how  to do what I need?

Thanks.

**Comment by djhoese** [comment]
1. This is not a vispy-specific issue.
2. You should do this as a general rule of thumb, but when multiprocessing is involved it is a **must**: put all of your process creation code in a `if __name__ == "__main__":` block or function. Multiprocessing will run your script when it starts up the second process and will end up in an endless loop of creating new child processes...at least I would guess.
3. Look up multiprocessing examples for how to give a queue to the child process. You can't do this with global variables.
4. If I were you I would do this with a separate PyQt thread (assuming that's the GUI framework you are using). In this separate thread you would get your new data and use Qt signals to send this data (or send a notification that it is ready) to the main GUI thread. In the main thread you would connect this Qt signal to a function (similar to what you are doing with the timer). The Qt signal can be set up to pass the data as an argument to the connected function (called a slot in Qt terms) which you can then use to update the vispy GUI. That said, there's not reason what you have shouldn't work if you set up the queue properly.
