### ISSUE TITLE
Faster Framerates

### ISSUE THREAD

**Issue by wgnu6** [vispy/vispy#1750]
Hello,
I'm trying to make a dynamical 3d scatter plot, and I'm using the `scatter = visuals.Markers()`. To update the scene, I use `scatter.set_data(pos)` with `app.Timer()`. My plots involve 1~10 million points and the framerate is below 30 fps. Is there any other way to make it faster?

**Comment by djhoese** [comment]
Can you describe the data more? Are you updating all 1-10 million points for every frame? Are you updating a subset?

Vispy does its best to be generic to work with as many use cases as possible. Although this may make most use cases perform well, there are definitely special cases where the best performance is not possible. The code is written to balance maintainability with performance. This may mean that data is copied more often that you'd like or other calculations are done to provide a simple interface but in one single specific case may be unnecessary.

Additionally, there may be things you are doing in your code that are less than optimal and could be avoided for this high performance case. For example, you may be setting the data, changing colors, or other things, and Vispy is trying to draw these data points for every one of these changes. It would be best to avoid these multiple redundant draws by blocking the draw events from the Scene's event system. Sometimes this is possible, some times it isn't.

Lastly, is there a reason you need to draw *all* 1-10 million points on the screen at once? Would averaging the points before sending them to the GPU be possible? This is a common problem when people try to use tools like matplotlib and plot thousands or millions of points on a plot window that is only 800x600 pixels. The user is only seeing so many points at once. There are ways to avoid doing work on so many unnecessary points.

**Comment by wgnu6** [comment]
The dataset is a sample of a six dimensional likelihood distribution. Each
point will be assigned a color corresponding to the likelihood ratio value.
The color won't change.

I am making a high dimensional visualizer, and this works by applying a 3x6
projection matrix onto the dataset which reduces it down to 3 dimensions.
The projection matrix will change so all data points will change per frame.

Averaging won't work because the dataset is unsorted and will lose quality
of the likelihood distribution.

**Comment by djhoese** [comment]
There are performance issues that can come up when using the high-level Scene API but most of them can be avoided. In the most extreme cases, anything you would do with the low-level gloo interfaces you can do in a custom high-level Visual object. The main difficulty with getting your application to perform well will be limiting how often data needs to be sent to the GPU and the operations that are performed *every* update. Put another way, reduce the number of operations per update and reduce the number of updates.

You will likely need to look at the MarkersVisual code and see what it is doing with your data. If every one of your updates is modifying/updating millions of points then you'll need to make sure that the MarkersVisual (or your own custom visual) doesn't have to do anything to your input data to get it to the GPU; or at least doesn't have to do much.
