### ISSUE TITLE
Some visuals doesn't show in notebooks

### ISSUE THREAD

**Issue by EtienneCmb** [vispy/vispy#1755]
Hello @djhoese , following the discussion on gitter, here's a small example illustrating an image that is properly plotted and markers that doesn't show. Same behavior inside jupyter notebook and jupyter lab. Can you please telle me how to get the log? Because in the terminal I've no errors.

# Displaying the image
```python
import numpy as np

from vispy import scene
from vispy import app
from vispy.scene.cameras import PanZoomCamera

# camera and scene canvas
cam = PanZoomCamera(rect=(-1, -1, 7, 7))
sc = scene.SceneCanvas(bgcolor='black', show=True)
wc = sc.central_widget.add_view(camera=cam)
# image
scene.visuals.Image(np.arange(25).reshape(5, 5), parent=wc.scene)

sc.show()
```
![Screenshot_20191116_094906](https://user-images.githubusercontent.com/15892073/68990696-600e9700-0856-11ea-9860-b7b37d88af12.png)

# Markers are not plotted

```python
# camera and scene canvas
cam_2 = PanZoomCamera(rect=(-1, -1, 7, 7))
sc_2 = scene.SceneCanvas(bgcolor='black', show=True)
wc_2 = sc_2.central_widget.add_view(camera=cam_2)
# markers
pos = np.random.uniform(0, 5, (1000, 2))
scene.visuals.Markers(pos=pos, parent=wc_2.scene, face_color='red')

sc_2.show()
```
![Screenshot_20191116_095115](https://user-images.githubusercontent.com/15892073/68990712-a5cb5f80-0856-11ea-9965-eb4256ae4313.png)

**Comment by djhoese** [comment]
Looks like you found a bug. See if you can comment out the single line in #1756 in your version and see if that fixes it for you.
