### ISSUE TITLE
Positioning labels

### ISSUE THREAD

**Issue by pcpatfire** [vispy/vispy#1760]
Is there a simple way to add a text label at a specified position (x, y, z) in a SceneCanvas or view?

**Comment by kmuehlbauer** [comment]
Does this example shed some light? https://github.com/vispy/vispy/blob/master/examples/basics/scene/text.py

**Comment by pcpatfire** [comment]
When adding the text to the viewbox, the vb.size is set using the canvas coordinates, but how and when the viewbox coordinates are mapped onto the canvas coordinates?

**Comment by djhoese** [comment]
@pcpatfire The default SceneCanvas typically provides a coordinate system for its child Visuals that is the same as its size in pixels. You can add your own transform to your object to map to this space (ex. `my_text_vis.transform = STTransform(...)`) if you'd like to customize the coordinate system you are using.

The coordinates get transformed inside the GPU as part of the transform system set up by the SceneCanvas. A visual has a transform, the viewbox has a transform (optionally controlled by a camera), and the lower level code has transforms to get buffer coordinates inside the GPU.

**Comment by pcpatfire** [comment]
In the text.py example, we have:
`t1.pos = canvas.size[0] // 2, canvas.size[1] // 3`
and 
`t2.pos = 0.5, 0.3`
t1 has `canvas.scene` as parent, and t2 has the viewbox `vb`, defined as the lower part of the canvas. In this case the viewbox coordinate system doesn't seem the same as the canvas' one. Is the viewbox domain (-1,1)x(-1,1)x(-1,1) or anything similar?

**Comment by djhoese** [comment]
Ah ok, so the `t1` object is set up to be relative to the entire window. So it isn't supported to move as you pan/zoom the view around. The view's coordinate system is being controlled by the camera and based on the `.rect = ` line near the top I'm guessing it is a range of 0-1 in the x and y dimension.

**Comment by kmuehlbauer** [comment]
@pcpatfire The vb domain is operated from the associated `camera`, see:

https://github.com/vispy/vispy/blob/0bec2dd27f9ed0b8ad177875c59222f10df767b5/examples/basics/scene/text.py#L18-L23

**Comment by pcpatfire** [comment]
But removing the `vb.camera.rect = 0, 0, 1, 1`, nothing changes. So the is vb domain set by a default value somewhere in the code?

**Comment by pcpatfire** [comment]
This is my application window.
![text](https://user-images.githubusercontent.com/50824984/69178242-81e37480-0b09-11ea-9440-ba23d21b05b9.JPG)
I added the text "OOOO-OOOO" to the ax.view, with the following intructions:
```
t1 = Text('OOOO-OOOO', parent=self.ax.view, color='red')
t1.font_size = 20
t1.pos = 0., 0.
```
I was expecting that the middle of my text would be positioned at (0, 0). Why is it going up there?

**Comment by djhoese** [comment]
> But removing the vb.camera.rect = 0, 0, 1, 1, nothing changes. So is the vb domain set by a default value somewhere in the code?

This is likely set in the camera code. This is the type of stuff I purposely don't remember and usually look at the source code to see. This time I'll leave that as an exercise for the reader :wink: 

> I was expecting that the middle of my text would be positioned at (0, 0). Why is it going up there?

Are you only modifying the example code? Your window/widget looks a little strange, like it has a border around it and the text is starting outside of the canvas or the canvas things it goes further that it seems to. Text is left aligned by default ("GPU, start drawing text here").

**Comment by pcpatfire** [comment]
Thank you for your spending some of your time on my problem. Actually if you check the [text.py](https://github.com/vispy/vispy/blob/master/examples/basics/scene/text.py) example, the t1 text (the one that has the canvas as a parent) is center-aligned by default. Concerning my window it is a different application with a canvas embedded in a PyQt5 window. My text (t1) has `ax.view` as parent, where `ax` is a PlotWidget object. I think that the position (0,0) where the middle of the text is positioned is the origin of the view in terms of canvas coordinates (the `pos` parameter).

**Comment by kmuehlbauer** [comment]
@pcpatfire Your assessment is correct, but have you had a look at the API doc [here](http://vispy.org/scene.html#vispy.scene.visuals.Text) and/or [here](http://vispy.org/visuals.html#vispy.visuals.TextVisual)?

These lead to the code (code never lies :grin:):
https://github.com/vispy/vispy/blob/0bec2dd27f9ed0b8ad177875c59222f10df767b5/vispy/visuals/text/text.py#L403-L414

Here you can examine that there are the `anchor_x` and `anchor_y` keyword arguments which define the alignment of the text at the given `pos`. 

We should update the docstring, that this defaults to `center` for both. Sure this will be a bit more clear then. @pcpatfire Want to become a contributor? PR welcome.

**Comment by pcpatfire** [comment]
I was trying to use `anchor_x` as you suggest:
```
    t1 = Text('OOOO-OOOO', parent=self.ax.view, color='red')
    t1.font_size = 20
    t1.pos = 0., 0.
    try:
        print('t1.anchor_x=', t1.anchor_x)
    except Exception as e:
        print(str(e))
```
but I got the error: `'Text' object has no attribute 'anchor_x'`. What's wrong? I was importing `Text` as follows:

`from vispy.scene.visuals import Text`

Is it the correct `Text` object?

**Comment by kmuehlbauer** [comment]
Yes it is. You need to give it either initialization:

`t1 = Text('OOOO-OOOO', parent=self.ax.view, color='red', x_anchor='left')`

or you use `t1.anchor = ('left', 'top')

**Comment by kmuehlbauer** [comment]
@pcpatfire Somehow your comment prior my last comment vanished. I'll update my comment with your message.

**Comment by pcpatfire** [comment]
Ok. Thank you. That's clear now. What about the coordinates? As you can see from my picture, my data coordinates are in the range (0, 10)x(-1.4, 1.4). How to position the text according these coordinates and not the canvas ones? The `t2` text from the `text.py` is using the same coordinates as the plotted data. Let's say that I want to put my text `t1` in the origin of my data axes. What is needed to do that? Should I use a transform or there is a simpler way?

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
I'm going to close this given the age. @pcpatfire if you're still hoping to get this resolved and haven't found a way to do it, please comment here and we can reopen the issue.
