### ISSUE TITLE
linking cameras

### ISSUE THREAD

**Issue by danielhrisca** [vispy/vispy#1761]
Hello, 

in pyqtgraph one can link two viewboxes on the X or Y axis. I was searching for a similar mechanism in vispy, and so far I see that the only way is to link two cameras but this is done of both axis at once (please correct me if I'm wrong). 

Is there some other way other then rolling your own mechanism using the set_range method?

**Comment by djhoese** [comment]
I don't think there is anything like what you're looking for. The plotting API is one of the less mature parts of vispy and is missing a lot of good features like this. That said, if you can think of a way to implement it, a pull request would be appreciated.

**Comment by danielhrisca** [comment]
That's a bit tricky with the amount of different cameras available

**Comment by djhoese** [comment]
> That's a bit tricky with the amount of different cameras available

Yes, but they should all have a `set_range` method that takes the X, Y, or Z range (since it is implemented in the base camera class). You're right though, this will probably be tricky and there are probably edge cases, but at least I know that you understand why it isn't implemented already :wink:

**Comment by queenish001** [comment]
@danielhrisca Can this issue be closed :)  ?

**Comment by danielhrisca** [comment]
Yes
