### ISSUE TITLE
Change widgets color in runtime

### ISSUE THREAD

**Issue by exor2008** [vispy/vispy#1762]
Hello, guys. A question this time.

If I want to change color of `scene.Line`, I do
`line.set_data(color=mycolor)`

If I want to change color of `scene.Markers`, I do
`marker.set_data(pos=mypos, face_color=mycolor, edge_color=mycolor) #have to specify pos everytime`

If I want to change color of `scene.AxisWidget`, I do
```
axis.axis.axis_color = mycolor
axis.axis.tick_color = mycolor
axis.axis._text.color = mycolor
axis.axis._axis_label.color = mycolor
axis.axis._need_update = True
```

What should I do if I want to change color of `scene.GridLines` lines?

**Comment by kmuehlbauer** [comment]
@exor2008 From looking at the code this is not fleshed out, yet.

You can try for red color for a `grid1`:

```
from vispy.color import Color
grid1 = scene.visuals.GridLines(parent=some.scene)
grid1._grid_color_fn['color'] = Color('r').rgba
```

**Comment by exor2008** [comment]
@kmuehlbauer perfect!
Thank you.

**Comment by kmuehlbauer** [comment]
@exor2008 Please note, that this is not official API and might change in the future.

Better would be, if we add a `color` property to the `GridLines`-class which changes the private `_grid_color_fn` under the hood. Would you be interested? PR welcome.

**Comment by exor2008** [comment]
@kmuehlbauer yeah, it's gonna be cool if you'll add a standard public API for all widgets.
It could be a `color` property or universal `set_data` method, or better both =)

**Comment by kmuehlbauer** [comment]
> > Would you be interested? PR welcome.

> @kmuehlbauer yeah, it's gonna be cool if you'll add a standard public API for all widgets.
> It could be a `color` property or universal `set_data` method, or better both =)

Sure, such a consolidation would be really nice. I strongly encourage you to create a new issue on that topic with some sort of list, where such changes/additions are needed. Also, PR are welcome anytime.

**Comment by exor2008** [comment]
@kmuehlbauer PR?

**Comment by kmuehlbauer** [comment]
@exor2008 **P**ull**R**equest. You fork the repository. make the wanted changes in the code und initiate a [PullRequest](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests). The changes will be reviewed by vispy maintainers and eventually are merged into the main branch.

**Comment by exor2008** [comment]
@kmuehlbauer got it.
I'll try to find a minute for that. I'll start, perhaps, with a new issue.
