### ISSUE TITLE
Recent AxisVisual cause random test failures

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1765]
@astrofrog recently made some changes to the AxisVisual in #1743 related to rotation handling. The test that was added seems to be failing as seen in the CI runs for #1748 (see https://travis-ci.org/vispy/vispy/jobs/616039829).

```
>       assert_allclose(axis2._rotation_angle, -17.056795)

E       AssertionError: 

E       Not equal to tolerance rtol=1e-07, atol=0

E       

E       Mismatch: 100%

E       Max absolute difference: 0.36324159

E       Max relative difference: 0.021296

E        x: array(-16.693553)

E        y: array(-17.056795)
```

I've seen this fixed by just restarting the test. @astrofrog could you look at what's going on?

**Comment by djhoese** [comment]
And now I can't get them to pass by an update. This may be a OSX versus linux thing. @astrofrog what operating system do you use for development?

**Comment by djhoese** [comment]
As mentioned in #1767 this seems to be passing now in travis with new pull requests that people have made. I'll close this for now and reopen if the failures pop up again. I thought it looked like a pytest/pluggy dependency issue, but obviously that isn't the problem given the recent successes.

**Comment by djhoese** [comment]
Ok, this is still a problem. I merged a pull request that was passing tests and then it started failing in master. It doesn't seem to be tied to dependency versions which means it is some kind of race condition or random-ness in the drawing. I've seen issues like this before in other tests. Last resort is to skip (xfail) the test on travis OSX environments.

**Comment by astrofrog** [comment]
We could just increase the tolerance of the test to ~5%?

**Comment by djhoese** [comment]
Yeah that is the other second-to-last option. the master branch was failing and I restarted it 3 times and it started passing.
