### ISSUE TITLE
Since 0.6.3 colors look flat

### ISSUE THREAD

**Issue by thephet** [vispy/vispy#1770]
I am using Python3, and I install vispy from pip. The version I have now is 0.6.3, and the colours of 3D objects that I show with the STL viewers look flat, see the following images.

The moment I load the STL it looks fine:

https://i.imgur.com/eUl3vVH.png

But the moment I move the mouse even a bit, it gets flat:

https://i.imgur.com/XGryEpY.png

This didn't happen before, but when I try to downgrade vispy, it doesnt work.

I cannot downgrade it because it says:

```
Traceback (most recent call last):                                                             
  File "main.py", line 1018, in <module>                                                       
    ex = MyWindow()                                                                            
  File "main.py", line 96, in __init__
    self.initUI()                                                                              
  File "main.py", line 785, in initUI                                                          
    self.stl_viewer = STLViewer((800, 500), self.renders_dir, self.l)                          
  File "/home/juanma/Projects/ChemCAD/ChemCAD/stl_viewer.py", line 50, in __init__             
    vispy.scene.SceneCanvas.__init__(                                                          
  File "/home/juanma/Projects/ChemCAD/ChemCAD/venv/lib/python3.8/site-packages/vispy/scene/canvas.py", line 134, in __init__
    super(SceneCanvas, self).__init__(
  File "/home/juanma/Projects/ChemCAD/ChemCAD/venv/lib/python3.8/site-packages/vispy/app/canvas.py", line 194, in __init__
    self._set_keys(keys)
  File "/home/juanma/Projects/ChemCAD/ChemCAD/venv/lib/python3.8/site-packages/vispy/app/canvas.py", line 249, in _set_keys
    for key, val in keys.items():
RuntimeError: dictionary keys changed during iteration
```

Nevertheless I would prefer to fix it on vispy 0.6.3

**Comment by djhoese** [comment]
Could you clarify a few things:

1. What does `print(vispy.sys_info())` show you? Mainly, what operating system and what backend are you using?
2. Do you have a simple reproducible example we can run to reproduce this?
3. Can you try using python <3.8?
4. Are you running this on the same system with the same GPU?

I wonder if the #1729 fix isn't updating things like it should be. Otherwise I'm not sure which of the recent changes could have broken this. I'm kind of hoping (maybe) that this is a python 3.8 thing rather than a vispy change that was made.

**Comment by thephet** [comment]
Installing 0.6.1 and removing the "keys='interactive'" worked, it let me use 0.6.1, and the objects look fine. Upgrading to 0.6.2 or 0.6.3 makes the objects/colors looked like I showed. So it must be something updated between 0.6.1 and 0.6.2.

I am using python3.8 in archlinux and I think I have no way of downgrading it.

Here is the output for vispy.sys_info()

https://pastebin.com/xmcXdQ2P

The problems are happening in exactly the same computer with the same GPU

**Comment by djhoese** [comment]
Ok. Do you have some code I can see? Or could you at least tell me what visuals you are using and how you are creating them?

Here are all the changes for 0.6.2: https://github.com/vispy/vispy/blob/master/CHANGELOG.md#v062-2019-11-04

The relevant changes could be:

1. https://github.com/vispy/vispy/pull/1730/files
2. https://github.com/vispy/vispy/pull/1728/files
3. https://github.com/vispy/vispy/pull/1712/files

The best guess I have right now without knowing what visuals you are using is that the #1728 changes broke something for you if you were depending on the data being overwritten inside the visual when the clim calculations were being done.

**Comment by djhoese** [comment]
@thephet Do you have any updates on this? Example code we can run?

**Comment by djhoese** [comment]
This has been open for a long time and no update has been given (we need example code) so I'm going to close this. If someone can provide example code that shows some of the issues discussed here we can reopen.
