### ISSUE TITLE
Rename mentions of HUSL to HSLuv

### ISSUE THREAD

**Issue by hmaarrfk** [vispy/vispy#1776]
https://github.com/vispy/vispy/blob/a6ec64bb7b56739b463e3c16245a31940ca4f5f7/vispy/ext/husl.py#L12

https://github.com/mwaskom/seaborn/issues/1361

Edit (2020):

To summarize the discussion below, the HUSL colorspace has been renamed to HSLuv. VisPy currently bundles a version of a library called `husl` internally (`vispy/ext/_bundled/husl.py`) and then imports it at (`vispy/ext/husl.py`). It would be best if we bundled the newer `hsluv` package (https://pypi.org/project/hsluv/) and all usages of `husl`. The new package source can be found here: https://github.com/hsluv/hsluv-python/blob/master/hsluv.py

**Comment by djhoese** [comment]
So to add more detail to this we should rename any mentions to husl to hsluv, but anything that can be made backwards compatible should be (imports that users may have done, string arguments of 'husl', etc).

Right @hmaarrfk?

**Comment by hmaarrfk** [comment]
Not too sure. I was just trying to build packages out for you, and found these few were missing.

**Comment by hmaarrfk** [comment]
Honestly, I could probably package up the old package as well.

**Comment by djhoese** [comment]
Ok so we have the old package bundled in vispy already. I'm noticing though that it actually always imports from the bundled version and if there is an ImportError it falls back to the installed package. I'm not sure how that makes sense.

Anyway, you are saying that we should be using hte https://pypi.org/project/hsluv/ package (which is from 2016). Since the actual colorspace was renamed from husl to husluv, I'm suggesting that we rename any mentions of `'husl'` in the vispy code. From what I can tell this comes down to a single usage of the `husl` package's `husl_to_rgb` function, a base colormap class called `_HUSL`, and a colormap called `husl`.

**Comment by hmaarrfk** [comment]
Something like that. I mean, if it is always using the bundled version, might as well keep bundling it if it is a minor feature.

**Comment by djhoese** [comment]
I've added an edit to the original issue so newcomers can see what is expected for this issue. I think it wouldn't be a bad idea to switch all usages over to hsluv.

**Comment by djhoese** [comment]
This change might as well remove the bundled husl dependency entirely and add a hard requirement on hsluv in `setup.py`. Let's just get rid of all the bundling.

**Comment by hmaarrfk** [comment]
I think bundling was really important before library developers maintained correct versioning requirements and before pip handled dependencies well.

That said, we are getting into trouble with strange architectures with scikit-image and wheels not being available there.

**Comment by hmaarrfk** [comment]
I wouldn't rush to fix this. we had trouble when we unbundled tifffile in scikit-image which caused a bunch of headaches for many users that weren't knowingly using an old version of tifffile.

**Comment by djhoese** [comment]
@hmaarrfk Could you explain the tifffile stuff more? I'm familiar with the module. Are you saying that skimage was using an old bundled version and the new unbundled version caused issues in skimage? Or something else?

**Comment by hmaarrfk** [comment]
Yeah, the transition wasn't as smooth as we had hoped.

All in all, it was a plus. But you know, never without challenges.
