### ISSUE TITLE
QSocketNotifier: Multiple socket notifiers for same socket 1864 and type Read

### ISSUE THREAD

**Issue by hmaarrfk** [vispy/vispy#1787]
When using spyder (3.x and 4), with qt5 as the plotting backend, and vispy with qt5, one gets this mind wrecking warning

```
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 22:01:29) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.10.1 -- An enhanced Interactive Python.

%gui qt

import vispy

vispy.use('pyqt5')
WARNING: QSocketNotifier: Multiple socket notifiers for same socket 1864 and type Read
WARNING: QSocketNotifier: Multiple socket notifiers for same socket 1864 and type Read

print('hello')
hello
WARNING: QSocketNotifier: Multiple socket notifiers for same socket 1864 and type Read

```

that keeps popping up, they consistently pop up, and never stop, really annoying and hinders workflow.

https://vimeo.com/379109772

**Comment by djhoese** [comment]
What about from vanilla ipython in the command line? What about doing the `print` before importing vispy in spyder or vanilla ipython?

**Comment by hmaarrfk** [comment]
That print statement just keeps popping up, at a semi periodic interval.

It is definitely related to these lines of code:

```
try:
    QtCore.qInstallMsgHandler(message_handler)
except AttributeError:
    QtCore.qInstallMessageHandler(message_handler)  # PyQt5
```

**Comment by hmaarrfk** [comment]
what is the harm, for myself, as a quick hot fix, to remove these lines from my distribution of vispy while we find a long term fix?

This is a pretty serious impedement in my team's workflow.

**Comment by hmaarrfk** [comment]
I think it is because spyder installs its own message handler:
https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py#L286

@ccordoba12 any ideas here?

**Comment by ccordoba12** [comment]
You can blacklist the QSocketNotifier message in our handler, I think.

**Comment by djhoese** [comment]
FYI: https://doc.qt.io/qt-5/qtglobal.html#qInstallMessageHandler

**Comment by hmaarrfk** [comment]
I think that documentation is bogus. That documentation states that it should be OK to overwrite the message handler, but my guess is that it is broken.

```%gui qt
# %%
from vispy.util import logger
from PyQt5 import QtCore


# Properly log Qt messages
# Also, ignore spam about tablet input
def message_handler(*args):
    msg_type, context, msg = args
    logger.warning(msg)


QtCore.qInstallMessageHandler(message_handler)
```

This successfully recreates the issue without making a call to `vispy.use`

**Comment by hmaarrfk** [comment]
But yeah, i can't get it to work in `ipython` from the terminal.??? not too sure how that is happening....

I think for today, I'm going to comment out the lines in vispy and distribute my own version of vispy while we figure things out.

**Comment by djhoese** [comment]
What if you reset the message handler to `0` at the beginning of your spyder session, does that "fix" it?

**Comment by hmaarrfk** [comment]
I tried, does nothing. 0 throws an error, `None`, doesn't do anything.

**Comment by codypiersall** [comment]
I wonder if the root issue is something with the IPython QtConsole?  Maybe Spyder is bundling a version of the qtconsole that runs into this issue: https://github.com/jupyter/qtconsole/issues/332

**Comment by hmaarrfk** [comment]
I don't think spyder bundled QtConsole, but rather it depends on it. I think the Console in spyder is from QtConsole so that seems like a likely source ;)

**Comment by hmaarrfk** [comment]
For those that need a workaround while qtconsole/vispy releases something:

```python
import vispy
import logger
vispy.use('pyqt5')
# Logging level gets set to info by default. Have to change it after
# importing vispy.
# https://github.com/vispy/vispy/issues/1790
# https://github.com/vispy/vispy/issues/1787
# https://github.com/vispy/vispy/pull/1714
vispy_logger = logging.getLogger('vispy')
vispy_logger.setLevel(logging.CRITICAL)
```

Thanks all for your quick input!

**Comment by ccordoba12** [comment]
> vispy_logger = logging.getLogger('vispy')
vispy_logger.setLevel(logging.CRITICAL)

So are these the important lines here?

**Comment by hmaarrfk** [comment]
I guess so. now you are having me question where i set these in my codebase ^_^

**Comment by djhoese** [comment]
Remind me: The main issue here is that both spyder and vispy set a message handler and Qt doesn't like that (even though it is supposed to handle it)?

**Comment by Dodelo** [comment]
I'd just like to point out that I have almost the same issue after updating Spyder from 4.1.3 to 4.1.4 (message is "QSocketNotifier: Multiple socket notifiers for same socket 1896 and type Read")

**Comment by ccordoba12** [comment]
I submitted a fix for this to ipykernel (ipython/ipykernel#525).

@hmaarrfk, could you test it locally (it's a very simple change) to see if it fixes your problem?

**Comment by Wildreamz** [comment]
This simple fix did it for me (same issue after updated to Spyder 4.1.4; Windows 10; Anaconda 1.9.12):
>>conda uninstall Spyder
>>conda install Spyder

**Comment by ccordoba12** [comment]
Thanks for the confirmation @Wildreamz!

**Comment by lutschc7** [comment]
I had the same problem as of 10/22/2020, even after uninstalling and reinstalling spyder. These steps seemingly patched the message popup:

1. Install vispy (conda install vispy)
2. If using python 3.8 or greater, change the vispy time.clock() reference (time.clock() is deprecated). In Lib/site-packages/vispy/util/ptime.py, change systime.clock() to systime.perf_counter()
3. Run the modified lines from above in spyder:
 `import vispy`
`import logging`
`vispy.use('pyqt5')`
`vispy_logger = logging.getLogger('vispy')`
`vispy_logger.setLevel(logging.CRITICAL)`
4. Add this code to the startup script to run each time. In _Tools->Preferences->IPython console->Startup->Run code->Lines_ add
`import vispy; import logging; vispy.use('pyqt5'); vispy_logger = logging.getLogger('vispy'); vispy_logger.setLevel(logging.CRITICAL)`

**Comment by djhoese** [comment]
@lutschc7 Thanks for laying out what needs to be done to get this working. Could you verify what version of ipykernel you have installed?

```
$ conda list ipykernel
# packages in environment at /home/davidh/miniconda3/envs/satpy_py37:
#
# Name                    Version                   Build  Channel
ipykernel                 5.3.4            py37h43977f1_0    conda-forge
```

For example ^

Also, your changes in step 2, are those needed in the master branch of vispy too? I could have sworn I fixed all of these but now I'm not sure if I'm seeing the right stuff.

**Comment by djhoese** [comment]
Hm I see I apparently did *not* update that code for python 3.8. @lutschc7 would you mind making a pull request to fix that module? You could also remove the if block at the bottom since we don't support python <3.6 anymore.

**Comment by hmaarrfk** [comment]
I believe this has now been fixed upstream.
