### ISSUE TITLE
default logging_level

### ISSUE THREAD

**Issue by hmaarrfk** [vispy/vispy#1790]
https://github.com/vispy/vispy/blob/57ebceb0f4f01938cc84e398829bcafc23fb5d0a/vispy/util/config.py#L74

In developing a workaround for https://github.com/vispy/vispy/issues/1787 I found that the logging level was set to Info.

Is the desired behaviour to log Info???
Would it be possible to leave it at the previous state if the user doesn't specify it in their config?

**Comment by djhoese** [comment]
That's a good point. If a user doesn't set a logging level for their application/console then we probably shouldn't force them to see INFO messages.

Skimming the code it seems there are three main areas that `logger.info` is used:

1. You load the application with no backend specified, if one of the detected backends fails to import to get an INFO message about it.
2. You try loading a different Qt backend even though you were using a different one.
3. Lower level GL messages when variables or textures are not active but there is a command to set their value.

Some or all of these could easily be a UserWarning or switched to a warning log level. At least that's my initial thought.

@larsoner @kmuehlbauer ?

**Comment by larsoner** [comment]
Fine by me
