### ISSUE TITLE
vispy looking for module named 'vispy.gloo.gl.webgl'

### ISSUE THREAD

**Issue by Lottta** [vispy/vispy#1804]
Hi folks,

despite the documented limitations I'm giving vispy under JupyterLab a try (having installed both via conda). But already the very first statement `vispy.use("ipynb_webgl")` fails with vispy being unable to find the module 'vispy.gloo.gl.webgl', which, as far as I understood, is indeed inexistent.
I have attached the traceback as well as the conda package list. JupyterLab extensions are:
   app dir: /usr/local/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        jupyter-matplotlib v0.4.2  enabled  OK
        jupyterlab-plotly v1.2.0  enabled  OK
        plotlywidget v1.2.0  enabled  OK
        vispy v0.2.2  enabled  OK

[vispy_use-Traceback.pdf](https://github.com/vispy/vispy/files/4031190/vispy_use-Traceback.pdf)
[conda_list.txt](https://github.com/vispy/vispy/files/4031199/conda_list.txt)

**Comment by djhoese** [comment]
We talked a little on gitter and using `vispy.app.use_app` as a workaround is the best idea for now. I think this is a bug in `vispy.use` but I won't have time to look at it for a while.

**Comment by Lottta** [comment]
Yes, I can confirm that
`import vispy.app
vispy.app.use_app('ipynb_webgl')`
works for me. Thanx a lot.

**Comment by queenish001** [comment]
@djhoese
