### ISSUE TITLE
Export an animation to a movie

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#181]
Taking screenshots at each frame and creating a video with e.g. Ffmpeg

**Comment by matejak** [comment]
The discussion here doesn't make it clear whether there is possibility of saving individual frames and just the ability of creating a video at once is missing, or there is no easy way to export even individual frames (I haven't been able to find the latter ability in the documentation).

**Comment by Eric89GXL** [comment]
@matejak for the `scene` you should be able to do `canvas.render()` to get the current frame. Have you tried that at all?

**Comment by matejak** [comment]
I see. It works, thanks - I have been looking for a `savefig` function that doesn't exist in `vispy`. A structured conceptual documentation would be greatly appreciated.

**Comment by braingram** [comment]
I started playing around with this a bit and added a new example using imageio. It saves as a gif and could probably look a little prettier: #1127
