### ISSUE TITLE
symbol lookup error on Ubuntu

### ISSUE THREAD

**Issue by DrAnaximandre** [vispy/vispy#1815]
Hi all, 

on Ubuntu 19.10, when trying to:
`import vispy`
`print(vispy.sys_info())`,

I get 
`symbol lookup error: /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0: undefined symbol: xcb_dri3_get_supported_modifiers`

However, if I do: `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 python -c "import vispy; print(vispy.sys_info())"`
I get 
```
Platform: Linux-5.3.0-7625-generic-x86_64-with-debian-buster-sid
Python:   3.6.9 |Anaconda custom (64-bit)| (default, Jul 30 2019, 19:07:31)  [GCC 7.3.0]
NumPy:    1.14.5
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.14.1', '5.14.0')
pyside:   None
pyside2:  None
pyglet:   pyglet 1.2.0
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.4 Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None

GL version:  '3.0 Mesa 19.2.8'
MAX_TEXTURE_SIZE: 16384
Extensions: 'GL_ARB_multisa[...]
```
I am furthermore able to run the entirety of my code if I preload the library as stated, but it is a bit cumbersome. 
 
1 - Is it a vispy-specific issue ?
2 - Is there a vispy fix that would allow not to preload the library ?

**Comment by djhoese** [comment]
Hi @DrAnaximandre, thanks for filing this. Given that the library reporting undefined symbol and the library that has the symbol are both system-level GL drivers, I don't think this is a VisPy issue. This seems like your video drivers were installed incorrectly, at least that's my guess. If you do `ldd /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0` you should be able to see what libraries (including libxcb hopefully) it is linked to. This may give you an idea why/how this was installed incorrectly.

Another thing, are you trying to run this code over an SSH or other remote desktop-type connection? If so, what happens if you use a direct physically connected display?

**Comment by DrAnaximandre** [comment]
Hi @djhoese, thanks for the fast reply.

Running `ldd /usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0`
gives the following output:
```
linux-vdso.so.1 (0x00007ffda3b7d000)
libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f4315628000)
libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f4315614000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f431560e000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f43154bf000)
libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f4315381000)
libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f4315364000)
libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4315339000)
libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f4315334000)
libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f431532d000)
libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f4315318000)
libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f4315112000)
libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f431510d000)
libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f4315104000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f43150d6000)
libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f43150d0000)
libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f43150cb000)
libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f43150c1000)
libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f4314ebf000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4314e9a000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4314ca9000)
/lib64/ld-linux-x86-64.so.2 (0x00007f4315711000)
libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4314ca3000)
libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4314c9b000)
libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4314c81000)
```
I will try to reinstall the driver.

I am running the code on the built-in display.

**Comment by djhoese** [comment]
Let me know how it goes. It looks like it is linked to the same dri3 that you are using so I'm not sure what could be going wrong.

**Comment by DrAnaximandre** [comment]
No luck in reinstalling every library that was either intel or mesa.

**Comment by djhoese** [comment]
Google gives you nothing? I'm not really sure how much more I can help. Do you have a longer traceback from python that leads to the missing symbol error?

**Comment by DrAnaximandre** [comment]
Unfortunately no to both questions - apart from the `LD_preload` trick. I will close for now; thanks for your help.
