### ISSUE TITLE
How to save output image？

### ISSUE THREAD

**Issue by justinhan22** [vispy/vispy#1823]
Now I use vispy.plot to draw two-dimensional images, I want to save the direct screenshot of the output image，Is there any way to from the code?
Thanks.

**Comment by djhoese** [comment]
You can try looking at the `vispy.gloo._screenshot` function:

https://github.com/vispy/vispy/blob/master/vispy/gloo/util.py#L11

It is currently private (has a `_` at the front of the function name) but I hope to change that before the next release (the `_` version will still be there). You should be able to call this after the Figure is drawn/shown.

**Comment by justinhan22** [comment]
I didn't find this function before. 
Now I looked it up and directly referred to `vispy.gloo.read_pixels()` function.
Very useful. 
Thank you very much.

**Comment by djhoese** [comment]
Although unlikely, I would suggest using `_screenshot` instead of `read_pixels()` in case future fixes/changes are needed and read_pixels() no longer does what you want, but this is up to you.

**Comment by justinhan22** [comment]
OK, I got it. Looking forward new release. 
Thank you!

**Comment by justinhan22** [comment]
Add a question: if it is a dynamic visualization content, is there any way to get a video or GIF from content？

**Comment by djhoese** [comment]
Not built in to vispy, but I've done it for other projects that use vispy. I essentially do a for loop for the number of frames I want, inside the loop I force a draw of the Canvas, run `_screenshot`, and append the image array to a video. I use the `imageio` library along with ffmpeg to create MPEG4 videos.

**Comment by justinhan22** [comment]
Sounds good，I will try.
