### ISSUE TITLE
How to specify GPU id for each rendering program?

### ISSUE THREAD

**Issue by wangg12** [vispy/vispy#1828]
Currently it seems all rendering programs are using GPU 0 even I specified `CUDA_VISIBLE_DEVICES`. I wonder is it possible to assign different gpu ids for different rendering programs?

**Comment by djhoese** [comment]
I'm not familiar with the `CUDA_VISIBLE_DEVICES` environment variable, but VisPy is not using CUDA but rather OpenGL so I'm not surprised it doesn't have an effect. VisPy will use whatever GPU is defined as your main graphics GPU (I'm guessing).

Any method for choosing a GPU that works with the pyopengl (or even lower level OpenGL C drivers) should work with VisPy. If any exist outside of system display preferences I'm not aware of them, but also haven't looked for them.

**Comment by wangg12** [comment]
So do you knoe any method for choosing a GPU that works with pyopengl or vispy?

**Comment by djhoese** [comment]
As I said, I'm not aware of any. I was kind of leaving this as "an exercise for the reader" (you). I was hoping you would do some google searches and find a solution that works for you (it may depend specifically on your GPU or operating system). If you find something and need help getting it working with VisPy then I can try to help. I work on VisPy voluntarily in my free time so I don't have much time to dedicate to it and in this case I don't think I'll be able to find a better solution than you will. I also don't have a system with two GPUs that can be used at the same time (my operating system makes me choose one or the other, not both).

**Comment by wangg12** [comment]
Fine, I guess there is no trivial way to achieve this.

**Comment by djhoese** [comment]
Did your google searches show that this was possible at all? What are the options?

**Comment by wangg12** [comment]
I did, unfortunately no useful information was found.

**Comment by djhoese** [comment]
I did three quick searches and found similar results. Either you have to use the operating systems tools to choose a GPU for a particular monitor or it isn't really possible.

Closing this for now. If someone comes along and is still interested in this feel free to comment if you've found anything new. If anything comes up in normal VisPy work I'll try to remember to comment here anything I discover.
