### ISSUE TITLE
speed drop on ellipse color change

### ISSUE THREAD

**Issue by spewil** [vispy/vispy#1832]
I'm working on a simple realtime plot where I'm pulling data off a queue and using it to set the color of a visual. I can't figure out why I'm seeing FPS drops (to 14), and how to do this speedier. 

I'm subclassing Canvas as for my application I need to run multiple visualizations in separate processes, these dots being one of them. This is just a MWE without pulling data from the queue, and it's still showing 14fps. Looking through the source, there's quite a bit of code to get through for set_data(), and there doesn't seem to be a clear way to update the color, so I assume I'm thinking about this a silly way. Looping through visuals is suboptimal, but it's just a first try.

From reading the issues here, it appears that I'll need to dig into GLSL. I haven't attempted this yet because I've had trouble trying to stuff the event loop into a child process-- the setup below is working well for me with e.g. ScrollingLines, but perhaps I'll need to alter it for this use-case where altering color at 60fps is the goal. 

Thanks! Any thoughts welcome. 

```
import sys
import queue
import numpy as np
import multiprocessing
from vispy import app, scene, color
import utils

WHITE = color.Color((1, 1, 1))
RED = color.Color((1, 0, 0))

class ColorDotPlot(scene.SceneCanvas):
    def __init__(self,
                 event,
                 queue,
                 nlines=36,
                 line_size=1000,
                 dx=1,
                 line_sep=10,
                 resizable=True,
                 fullscreen=False,
                 vsync=True,
                 *args,
                 **kwargs):
        super().__init__(
            keys='interactive',
            resizable=resizable,
            fullscreen=fullscreen,
            vsync=vsync,
            *args,
            **kwargs)
        self.unfreeze()
        self.event = event
        self.queue = queue
        # self.create_native()
        self.view = self.central_widget.add_view(camera='panzoom')
        self.view.camera.aspect = 1
        self.view.size = 1000, 750
        self.view.pos = (0, 0)
        self.nlines = nlines
        self.line_size = line_size
        self.dx = dx
        self.line_sep = line_sep
        self.x_pos = np.arange(10, 50, 10)
        self.y_pos = np.arange(10, 90, 10)
        self.dots = []
        for x in self.x_pos:
            for y in self.y_pos:
                dot = scene.visuals.Ellipse(center=(x, y), color=RED, radius=2)
                self.view.add(dot)
                self.dots.append(dot)
        self.view.camera.set_range()
        self.view.camera.interactive = True
        self.view.camera.set_range((-100, 100), (-100, 100))
        self._timer = app.Timer('auto', connect=self.on_timer, start=True)
        self.num_samples_to_update = 50
        self.samples_updated = 0
        self.pointer = 0
        self.sample = np.zeros((self.nlines, 1))
        self.dotcolor = 'w'
        self.freeze()
        self.show()

    def on_timer(self, event):
        if not self.event.is_set():
            if self.dotcolor == 'w':
                self.dotcolor = 'r'
                for dot in self.dots:
                    dot.color = RED
            elif self.dotcolor == 'r':
                self.dotcolor = 'w'
                for dot in self.dots:
                    dot.color = WHITE
        else:
            print("[DOTS] event set | emptying plot queues")
            while True:
                try:
                    self.queue.get(block=False)
                except queue.Empty:
                    break
            print("[DOTS] finished clearing queue")
            print("[DOTS] closing canvas, quitting app")
            self.close()
            self.app.quit()

class ColorDotConsumer(multiprocessing.get_context("spawn").Process):
    def __init__(self, event, q, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.event = event
        self.q = q

    def run(self):
        self.app = app.Application()
        print("starting ", self.name)
        self.plot = ColorDotPlot(self.event, self.q, app=self.app)
        print(self.name, ": running")
        self.app.run()
        print("app quit")

def main():
    ctx = multiprocessing.get_context("spawn")
    e_dots = ctx.Event()
    q_dots = utils.Queue(ctx=ctx)
    c = ColorDotConsumer(e_dots, q_dots)
    c.daemon = False
    c.start()
    print("s to stop")
    while True:
        for line in sys.stdin:
            if line[0] == "s":
                print("stopping")
                e_dots.set()
                c.join()
                return

if __name__ == '__main__':
    main()


```

**Comment by kmuehlbauer** [comment]
@spewil I've trouble getting this to run because of missing `utils` import.

**Comment by kmuehlbauer** [comment]
Good chance that you could use `collections` for this.  Have a look at the examples [here](https://github.com/vispy/vispy/tree/master/examples/collections).

Do only the colors change?

**Comment by spewil** [comment]
> @spewil I've trouble getting this to run because of missing `utils` import.

apologies! it's just a slight mod on Queue-- to run, remove utils import and replace that line with:
```
    q_dots = ctx.Queue()
```

Collections looks like a good idea! Thanks for that. 

Yes-- I'm just looking to change the color on Timer using recent data from the queue.

**Comment by kmuehlbauer** [comment]
From first glance, the speed drop is due to the iteration over all visuals changing color separately. Every color change on any visual will induce a redraw, which makes it slow. Also `EllipseVisual` might not be the best suited `Visual` for that, because it's based on `PolygonVisual` which in turn is a `CompoundVisual` consisting of `LineVisual` and `MeshVisual` with all it's complexity. 

If you just want to show dots of some sort, you could play with `MarkersVisual`, which allows you to set all dots/markers at once. Example [here](https://github.com/vispy/vispy/blob/master/examples/basics/visuals/markers.py). Exploring Markers would be my next try.

If you need more freedom you would need to use collections, but this might involve adding/changing shader code.

**Comment by spewil** [comment]
Ah, right, I missed the `update` call for each color change. 

I actually started with markers, but because I need to set each dot's color separately switched to `Ellipse`. Would you condone a `Collection` of `Markers` with one dot each?

Happy to dig into the shaders if you think that's the best option. Let me know if you can point me to a relevant example for my setup.

**Comment by djhoese** [comment]
You should be able to set the color of each individual marker in a single Markers Visual object by providing an array. This would be the most performant method. In general, less visual objects means better performance.

**Comment by spewil** [comment]
Thanks both for your patience. 

Straying from the original question: it seems that I'm a little confused about `update` and `draw`. I see from the examples that overloading the builtin events works for mouse clicks and the like, but if I want to integrate a generic `Timer`, I'm having some trouble making things play nice. Tried to pare down my MWE: 

I did try this with `scene.visuals.Markers` as well but wasn't able to get things drawing. I do notice that scene adds in a lot of event handling. I would like to reduce the amount of events to a single `Timer`. 

```
import numpy as np
from vispy import app, scene, color, visuals

WHITE = color.Color((1, 1, 1))
RED = color.Color((1, 0, 0))

class ColorDotPlot(scene.SceneCanvas):
    def __init__(self,
                 resizable=True,
                 fullscreen=False,
                 vsync=True,
                 *args,
                 **kwargs):
        super().__init__(
            keys='interactive',
            resizable=resizable,
            fullscreen=fullscreen,
            vsync=vsync,
            *args,
            **kwargs)
        self.unfreeze()
        self.view = self.central_widget.add_view(camera='panzoom')
        self.view.camera.aspect = 1
        self.view.size = 1000, 750
        self.view.pos = (0, 0)
        self.view.camera.interactive = True
        self.view.camera.set_range((-100, 100), (-100, 100))
        self.timer = app.Timer('auto', connect=self.on_timer)

        self.dotcolor = 'w'
        self.pos = np.array([[0, 0]])

        self.markers = visuals.MarkersVisual()
        self.markers.set_data(pos=self.pos, face_color='white', symbol='o')
        self.freeze()

        print(self.markers.events._emitters)
        self.show()
        self.timer.start()

    def on_draw(self, event):
        self.context.clear(color='black')
        self.markers.draw()

    def on_timer(self, event):
        if self.dotcolor == 'w':
            self.dotcolor = 'r'
            self.markers.set_data(
                self.pos, face_color=RED, size=1000, symbol='o')
        elif self.dotcolor == 'r':
            self.dotcolor = 'w'
            self.markers.set_data(
                self.pos, face_color=WHITE, size=1000, symbol='o')

if __name__ == '__main__':
    external_app = app.Application()
    plot = ColorDotPlot(app=external_app)
    app.run()
```

**Comment by djhoese** [comment]
If you are using `SceneCanvas` you do not need to (read: you should not) override the `on_draw` method. The SceneCanvas will handle drawing the various children for you. That said, you should be using `vispy.scene.visuals.Markers` when using the `SceneCanvas` and providing it with `parent=view.scene` (I think that's it). Try that and this should help get things on the screen.

As for events, the SceneCanvas is going to have a lot of events. That's how the scene handles camera events and transform changes and all the other stuff it needs to keep track of.

**Comment by spewil** [comment]
Argh! That did the trick. Thanks so much.

**Comment by djhoese** [comment]
Try adding `self.update()` to your `on_timer`. That tells the canvas to re-start the drawing process.

**Comment by spewil** [comment]
Yes, of course. `Canvas.update()` =\= `Visual.update`. Thanks! 

```
import numpy as np
from vispy import app, color, visuals

WHITE = color.Color((1, 1, 1))
RED = color.Color((1, 0, 0))

class ColorDotPlot(app.Canvas):
    def __init__(self, resizable=False, vsync=True, *args, **kwargs):
        super().__init__(
            keys='interactive',
            resizable=resizable,
            vsync=vsync,
            *args,
            **kwargs)
        self.timer = app.Timer('auto', connect=self.on_timer)
        self.pos = np.array([[0, 0]])
        self.markers = visuals.MarkersVisual()
        self.markers.set_data(
            pos=self.pos, face_color=WHITE, symbol='o', size=1000)
        self.dotcolor = 'w'
        self.show()
        self.timer.start()

    def on_draw(self, event):
        self.context.clear(color='black')
        self.markers.draw()

    def on_timer(self, event):
        if self.dotcolor == 'w':
            self.dotcolor = 'r'
            self.markers.set_data(
                self.pos, face_color=RED, size=1000, symbol='o')
        elif self.dotcolor == 'r':
            self.dotcolor = 'w'
            self.markers.set_data(
                self.pos, face_color=WHITE, size=1000, symbol='o')
        self.update()


if __name__ == '__main__':
    external_app = app.Application()
    plot = ColorDotPlot(app=external_app)
    app.run()
```
