### ISSUE TITLE
Problem when trying to add a canvas.native as a pyqtwidget

### ISSUE THREAD

**Issue by NicoliHCorrea** [vispy/vispy#1836]
I want to show a canvas as a widget in a pyqt window. I have done this to other two canvas and they worked just fine, but this one isn't.

This is the canvas when running on its own:

![image](https://user-images.githubusercontent.com/58525689/76344746-d7be7100-62e0-11ea-8fd1-6aa53e833fc2.png)

And this is the view for the pyqt widget:

![image](https://user-images.githubusercontent.com/58525689/76344810-f3c21280-62e0-11ea-8416-60df9984f347.png)

The error code is:

RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE
ERROR: Invoking <bound method CanvasHeatMap.on_draw of <CanvasHeatMap (PyQt5) at 0x146ea92cc48>> for DrawEvent
WARNING: Error drawing visual <vispy.visuals.image.ImageVisual object at 0x00000146EAA05348>
The code is:

```
import numpy as np
from vispy import app, gloo, visuals
from vispy.visuals.transforms import STTransform

n_vertical = 10
n_horizontal = 2
tex = np.c_[(np.zeros(shape=(n_horizontal, n_vertical, 1)), np.zeros(shape=(n_horizontal, n_vertical, 1)),
             np.ones(shape=(n_horizontal, n_vertical, 1)), np.random.uniform(size=(n_horizontal, n_vertical, 1)))]


class CanvasHeatMap(app.Canvas):
    def __init__(self):
        app.Canvas.__init__(self, title='Use your wheel to zoom!', keys='interactive', vsync=True, autoswap=True)
        gloo.set_viewport(0, 0, *self.physical_size)
        self.heatmap = visuals.ImageVisual(data=tex, method='subdivide', interpolation='nearest')
        s = (1 / (self.size[0] * self.heatmap.size[0] / (self.size[0] * 2)),
             (1 / (self.size[1] * self.heatmap.size[1] / (self.size[1] * 2))))
        self.heatmap.transform = STTransform(scale=s, translate=(-1, -1))
        self._timer = app.Timer('auto', connect=self.on_timer, start=True)
        gloo.set_state(clear_color='black', blend=True, blend_func=('src_alpha', 'one_minus_src_alpha'))
        self.show()

    def on_timer(self, event):
        self.heatmap.set_data(tex)
        self.update()

    def on_draw(self, event):
        gloo.clear(color='yellow', depth=True)
        self.heatmap.draw()


if __name__ == '__main__':
    c = CanvasHeatMap()
    app.run()
```

**Comment by djhoese** [comment]
Try removing the `gloo.set_viewport` and see if that helps.

**Comment by djhoese** [comment]
And if that doesn't work, what about removing `title` and `keys` from the `__init__` call.

**Comment by NicoliHCorrea** [comment]
@djhoese I figured it out. I just removed the self.show() line and it worked. Anyway, thank you for always helping.
