### ISSUE TITLE
AttributeError: module 'vispy.app.backends' has no attribute '_ipynb_webgl'

### ISSUE THREAD

**Issue by Gautameshwar** [vispy/vispy#1846]
I tried running a p5 sample code and then, the above error appears in output. (AttributeError: ...)
So, i checked vispy by runnning vispy.test() and that showed RuntimeError: FAILURE. 
Tried to see the system info of vispy and it showed this: 

print(vispy.sys_info())
Platform: Windows-10-10.0.18362-SP0
Python:   3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)]
NumPy:    1.18.2
App info-gathering error:
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\vispy\util\config.py", line 422, in sys_info
    app = use_app(call_reuse=False)  # suppress messages
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\vispy\app\_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\vispy\app\application.py", line 49, in __init__
    self._use(backend_name)
  File "C:\Users\Lenovo\anaconda3\lib\site-packages\vispy\app\application.py", line 229, in _use
    mod = getattr(backends, module_name)
AttributeError: module 'vispy.app.backends' has no attribute '_ipynb_webgl'

(I keep getting the same error repeatedly)

Please help!

**Comment by djhoese** [comment]
> p5 sample code

What did you mean by this? PyQt5?

Are you running this code from a terminal or a jupyter notebook?

**Comment by Gautameshwar** [comment]
I ran this code in spyder 4's in-built python terminal. p5 is a visual library that uses vispy to function(for further reference: [https://pypi.org/project/p5/](url)). I'm still doubtful if the problem lies in vispy only.. 

P.S: Thanks for the prompt response :)

**Comment by djhoese** [comment]
Could you try running this outside of spyder in a basic terminal? There is a known issue where VisPy incorrectly thinks it is in a jupyter notebook when run from a spyder environment. The other workaround is to use `vispy.app.use_app('pyqt5')` at the top of the script. This avoids VisPy trying to be smart with the backend it should choose.

**Comment by Gautameshwar** [comment]
I tried running the code in Jupyter notebook and it gave a different error:

AttributeError                            Traceback (most recent call last)
<ipython-input-1-f345ee149ee1> in <module>
     19     background(204)
     20 
---> 21 run()

~\anaconda3\lib\site-packages\p5\sketch\userspace.py in run(sketch_setup, sketch_draw, frame_rate, mode)
    158 
    159     app.run()
--> 160     exit()
    161 
    162 def title(new_title):

~\anaconda3\lib\site-packages\p5\sketch\userspace.py in exit(*args, **kwargs)
    239         p5.sketch.show(visible=False)
    240         app.quit()
--> 241     p5.exit(*args, **kwargs)
    242 
    243 def no_cursor():

AttributeError: module 'p5.core.p5' has no attribute 'exit'

Guess the backend error is in spyder environment..(will be glad to know how to fix it)

I'm attaching the code here. 
[p5_sample.txt](https://github.com/vispy/vispy/files/4409623/p5_sample.txt)

Will really appreciate if you could check if it gives any similar errors in your system...

**Comment by djhoese** [comment]
I said **not** to run it in a notebook. Please try in a regular terminal.

And I already told you about `use_app` as a way to force the backend when using it from spyder.

**Comment by Gautameshwar** [comment]
The code is properly executed in the external terminal. And the workaround seems to solve the backend problem in spyder4. Both the environments show the same error: AttributeError: module 'p5.core.p5' has no attribute 'exit'.

**Comment by djhoese** [comment]
Perhaps their example is out of date? Sorry, I've never used p5.

**Comment by larsoner** [comment]
Closing as a probable Spyder issue, but feel free to make a PR to update our docs if you found a helpful solution @Gautameshwar

**Comment by djhoese** [comment]
Also see #1714
