### ISSUE TITLE
Grouping visuals into one GL Program and other optimization ideas 

### ISSUE THREAD

**Issue by mateo4778** [vispy/vispy#1857]
### Background ###
In my application I am plotting a large amount of real time data continuously. As an example one common use case will be ~20-30 signals, where each signal is receiving new data every ~2-5ms. This needs to continue on for possibly hours resulting in millions of data points. It also needs to function well on lower end hardware using integrated graphics. 

I have spent many hours (rather weeks) deep diving the vispy source and learning about OpenGL in the process. To get to where I am I ended up doing a fair amount of monkeypatching and subclassing.

### What I've done so far ###
- Monkeypatched the gloo.Program draw function to allow glDrawArrays with custom offset/count inputs to limit the draw region to only the vertices that are visible inside the viewbox window.
- Implemented a circular/ring buffer where I have a version in CPU memory and a matching one in GPU memory. Then just keeping track of changed/new data, and send it to the GPU using set_subdata, which completely removes any redundant copying of data.
- To handle the plotting of many points unnecessarily (multiple points per pixel) I implemented a technique similar to that discussed in this paper, by keeping multiple lower resolution chunked versions of the raw data in separate VertexBuffer objects, and activating/plotting the optimal data set based on the pixel width of the window and the number of datapoints per pixel in that range. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3986407/
- Improved mouse event handling performance by switching from the render picking method to picking based on visual bounding rects (being able to pick out sub-items within a visual weren't important to me).

### Where I could use some advice ### 
Performance and optimization. Everything I mentioned above is actually implemented and working extremely well. However even though I have limited the gl DATA commands to almost nothing, and the glDrawArray is only drawing a reasonable number of vertices, I still have the fundamental issue of drawing many separate Visuals, one per Line. The result is that the CPU usage increases proportional to how many signals have been added. At 5-10 signals it is no problem, but when you get above 20+ it becomes significant. 

Currently each signal has its own Visual, similar to LineVisual. How can I attempt to integrate these into a single visual, or at least less, to improve CPU usage. I tried looking into the visuals.collections code, but honestly I was fairly confused by it, and not sure where to begin integrating that with the scene Visuals. Plus I am not even positive they will solve my problems.

I would appreciate any help, input, or comments anyone might have!

**Comment by asnt** [comment]
The adaptations you brought seem already impressive. Congrats!

Did you have a look at #1820? It seems to be doing similar to what you desire. It draws the same mesh many times with different position/colour attributes but stores all of them in a single buffer. There is thus a single draw call for all.

PS: The link should probably be formatted `[url](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3986407/)`

**Comment by mateo4778** [comment]
I had not seen that one yet, lots of interesting discussion. That method is using 'line' instead of 'line_strip' like I am currently. To achieve the non-continuous drawing of elements from the same buffer while also using line_strip I need many draw calls (one per line). If I were to switch to using 'line' I could draw everything from one massive buffer, using one draw call, however I would then require double the memory footprint because the index buffer would have to identify every single segment in each line. Currently I have separate visuals for each signal line, where each visual has its own buffer, its own draw call, and its own program instance.

However another requirement is that each signal line could have a unique transform in the Y axis. All of the x-axis are linked because they are time-linked, but the Y axis can have different zoom levels. Is it possible to have some type of array of transforms for each line? 

And thanks for the link heads up, i'm new to contributing on github haha.

**Comment by djhoese** [comment]
@mateo4778 Do you need to store every data point you receive and plot all of them or do you only display the most recent N points? How many points do you think you are drawing per line?

As for a transform for each line, I don't think the builtins will help you. You could write a custom one but you'd have to be able to identify which vertex belongs to which line (ex. vertex coordinates with y values between y1 and y2 should be scaled and translated this way). Or if X is always the same you could encode this information in the X coordinates. Just an idea.

**Comment by mateo4778** [comment]
> @mateo4778 Do you need to store every data point you receive and plot all of them or do you only display the most recent N points? How many points do you think you are drawing per line?

The user has to be able to zoom in and out, and also pan back to look at previous data. But I have capped the total points per line to 625,000. So technically it has to show up to the last 625,000 points per line. So 30 lines x 625000 = 18,750,000 total raw points. But keep in mind that I am currently using multiple buffers keeping track of "trimmed down" versions of the data, so in reality there will never be more than ~16,000 points visible per line on the screen as I swap the active buffer to minimize over-draw (probably not a real term lol).

> As for a transform for each line, I don't think the builtins will help you. You could write a custom one but you'd have to be able to identify which vertex belongs to which line (ex. vertex coordinates with y values between y1 and y2 should be scaled and translated this way). Or if X is always the same you could encode this information in the X coordinates. Just an idea.

I don't suppose there is any way for the vertex shader to know which index number in the position vertex buffer it is currently acting upon is there? If so I could have a GPU variable that has been set such that indices 0->625,000 use transform 1, indices 625,001->1,250,000 use transform 2 etc... Is that possible? Or alternatively I guess I could have an index buffer the length of the full buffer that indicates which transform to use?

**Comment by djhoese** [comment]
Regarding debugging OpenGL code: I have no idea. Let me know.

Good idea on the gl_VertexID, another idea would be to provide another buffer to the shader that is just the line index. I'm sure there are visuals that do this. Let me see if I can find one.

**Comment by mateo4778** [comment]
Ok so I can maybe use either of those methods (gl_VertexID or a separate VertexBuffer containing the line index) so then I think the last piece is how to have an array of transforms for each line. I'm not sure how that would work?

**Comment by mateo4778** [comment]
I realize now that the 2D linear transforms I am concerned with are basically just two numbers (scale/translate) but now i'm getting lost in how I can get those by hooking into the existing camera and ChainTransform stuff. I am trying to avoid throwing out the entire scene/visual handling and doing everything (including click events) from scratch...

**Comment by djhoese** [comment]
Do the number of lines change through the course of the application? If not, or even if they do I suppose, you could make your own Transform class with your own shaders. I've done something similar in my own application: https://github.com/ssec/sift/blob/master/uwsift/view/transform.py#L629

The code is ugly but the point is that BaseTransform can be subclassed and you can do whatever you want inside. You could have an if statement based on the vertex ID and perform the computation based on that. You could probably define functions inside this transform that are just STTransforms themselves and use those. Like `self.my_shader['transform1'] = STTransform(...)` or something like that (I might be over simplifying it, but then again we're getting into the optimization weeds here).

**Comment by mateo4778** [comment]
Well after lots of work I have pretty much been able to test things out in all the way I wanted to... But am not to psyched about the results.

I was able to emulate glDrawArrays while using a single VBO and single Draw call for all my lines at once. I also got this working with transforms. 

Using only a single draw call and single VBO in one program for all lines results is awesome low CPU usage, even with 40 lines, exactly what I wanted (dropped from ~7% CPU -> 1%). However the result is then that my GPU usage has skyrocketed. I suspect because the Vertex Shader is now having to process every single point in my buffer, just to find out that 90% of them are discarded. When I was using multiple draw calls I was only drawing the sections of the buffer within my clipping range. The GPU usage has gone from ~5% -> 60% so that is almost a non-starter. 

I wish there was some way to mask/drop vertices at or before the Vertex Shader, but from my searching that doesn't seem to be possible. It just seems so inefficient to be processing millions of points in the vertex shader that we just drop in the fragment shader... But I guess that is what multiple draw calls is for. 

It's a bit frustrating after having come this far to basically give up but I am not sure where to go from here.

**Comment by djhoese** [comment]
So we're happy and sad? Sorry to hear that the GPU usage jumped so much. I wonder if there is a way you could use index arrays/buffers in some way, but with your given problem I'm not sure how. Another option would be to only show the last X records and detect when someone looks at previous data and shovel that in to be viewed. Less vertexes to store and process, but more overhead to move the data in and out and do the detection of what they are looking at.

**Comment by mateo4778** [comment]
Happy that after some 20 hours of work this past week I finally got the single VBO drawing and transforms working as intended, sad that it ultimately didn't solve the original problem. But at least I massively expanded my knowledge of OpenGL and writing my own shaders. 

I think I am near a point with the line drawing where I need to accept the current performance, at least within the ballpark of my current implementation. Or at least I need to go back to focusing on optimizing the Axis drawing if I want to get more out.

**Comment by larsoner** [comment]
Closing as I think we have other issues to track this like #831 #1820
