### ISSUE TITLE
Support in colab

### ISSUE THREAD

**Issue by rjsgml5698** [vispy/vispy#1867]
Hello!

I run the vispy example in colab and it doesn't seem to work.

Is vispy not supported yet?

**Comment by djhoese** [comment]
I'm assuming you mean the jupyter widget/extension? I've never used colab so I can only make guesses for things. The main thing is, as stated in the installation instructions, that the jupyter extension/widget is considered experimental and should not be relied upon for operational or long term running code. You didn't provide an error that you are getting so I can't be sure what might be going wrong. We've had some users report installation issues with the jupyter extension recently but overall I think it still works in a jupyter notebook/lab environment.

**Comment by rjsgml5698** [comment]
> I'm assuming you mean the jupyter widget/extension? I've never used colab so I can only make guesses for things. The main thing is, as stated in the installation instructions, that the jupyter extension/widget is considered experimental and should not be relied upon for operational or long term running code. You didn't provide an error that you are getting so I can't be sure what might be going wrong. We've had some users report installation issues with the jupyter extension recently but overall I think it still works in a jupyter notebook/lab environment.

I really appreciate the answer.

It seems that the widget/extension of vispy is not yet supported by colab. I think I have to find another way. 

Thank you!

**Comment by larsoner** [comment]
I think we will get this only once colab automatically once custom widgets are supported / https://github.com/googlecolab/colabtools/issues/498 is solved, so closing as an upstream issue
