### ISSUE TITLE
Terminal emulator with glumpy and vispy backends

### ISSUE THREAD

**Issue by zokrezyl** [vispy/vispy#1868]
I know that this is not the best channel to make a little announcement, but I thought you may be interested to add reference to the project somewhere in the source code or your website:

I am happy to share with you the birth of a little project that was inspired by the glumpy/gloo-terminal example. I took that example to the next level, combined glumpy with libvterm and the result is a real (almost) full featured terminal emulator. As next step wanted to dive into vispy and ported the project to vispy as well. The project wants to be something much more than a dump terminal emulator, but details will come on the projects github place. It is in a very early stage, but/and any suggestions, critics are more than welcome on: https://github.com/zokrezyl/asciterm/issues/2)

https://github.com/zokrezyl/asciterm

**Comment by djhoese** [comment]
Cool! Do you have any screenshots/casts of what things look like?

**Comment by zokrezyl** [comment]
Happy you liked the idea. Well... what would you see on on a screenshot anything else than what you would see on any terminal emulator

**Comment by djhoese** [comment]
Ok so this is a terminal running on OpenGL powered by glumpy (or vispy)? Still cool. :wink:

**Comment by zokrezyl** [comment]
Indeed. But the next step is to design/implement special ANSI like special escape sequences to be able to send shaders, attributes, plot commands etc. to be rendered with OpenGL on the terminal. There are bunch of details to design, like how to render those so that legacy terminal tools work as expected, but the same time you can enrich the terminal to get o bunch of workflows implemented without leaving it. Think about you want to run a command like "top", but instead of running "top" you want to see the graph of the CPU usage, or you want to monitor the FFT of sound input on your jack audio, or maybe the musical note onsets, or just "cut" display the effect of a specific filter on your photo. Or think Jupyter/iPython on the terminal. Or rendering rich text for a log.

**Comment by zokrezyl** [comment]
@djhoese as suggested, here is the first screenshot. In the meantime I implemented the protocol with ansi escape sequences, to send shader programs to the terminal from a client program.

https://github.com/zokrezyl/asciterm/blob/master/res/scr_shot.png

**Comment by zokrezyl** [comment]
@djhoese what do you think, how could I make the project known to the people who may be interested in?

**Comment by djhoese** [comment]
Off the top of my head: vispy mailing list (google group), python-announce mailing list, reddit /r/python, twitter?

**Comment by zokrezyl** [comment]
Thanks! will do so.. first improving it little. BTW.. have a look at the video/gif on https://github.com/zokrezyl/asciterm

**Comment by larsoner** [comment]
Closing as no changes are necessary at the VisPy end I think
