### ISSUE TITLE
How can i clear the figure on canvas

### ISSUE THREAD

**Issue by q-chen95** [vispy/vispy#1877]
`import numpy as np
from vispy import app, scene
from vispy.gloo.util import _screenshot

canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()
view.camera = 'turntable'

xx, yy = np.arange(-1,1,.02),np.arange(-1,1,.02)
X,Y = np.meshgrid(xx,yy)
R = np.sqrt(X**2+Y**2)
Z = lambda t : 0.1*np.sin(10*R-2*np.pi*t)
surface = scene.visuals.SurfacePlot(x= xx-0.1, y=yy+0.2, z= Z(0),
                        shading='smooth', color=(0.5, 0.5, 1, 1))
view.add(surface)
canvas.show()

def make_frame(t):
    surface.set_data(z = Z(t)) # 更新曲面
    canvas.on_draw(None) # 更新Vispy的画布上的 图形
    return _screenshot((0,0,canvas.size[0],canvas.size[1]))[:,:,:3]`

Hello, i can't find out how to clear the figure on canvas and i need some help. Thank you!

**Comment by q-chen95** [comment]
i use (view.add(surface)) in my code to add a SurfacePlot figure, but how can i remove this figure?

**Comment by kmuehlbauer** [comment]
@q-chen95 You can just set the parent of the visual to None:

```python
# add surface to view
view.add(surface)

# do something

# remove surface from view
surface.parent = None

# do something

# re-add surface to view
view.add(surface)
```

If you just want to temporarily disable visualizing it, you also can do 

```python
# do not plot surface
surface.visible  = False

# do something

# make visible again
surface.visible  = True
```

**Comment by q-chen95** [comment]
> @q-chen95 You can just set the parent of the visual to None:
> 
> ```python
> # add surface to view
> view.add(surface)
> 
> # do something
> 
> # remove surface from view
> surface.parent = None
> 
> # do something
> 
> # re-add surface to view
> view.add(surface)
> ```
> 
> If you just want to temporarily disable visualizing it, you also can do
> 
> ```python
> # do not plot surface
> surface.visible  = False
> 
> # do something
> 
> # make visible again
> surface.visible  = True
> ```

**Comment by q-chen95** [comment]
> > @q-chen95 You can just set the parent of the visual to None:
> > ```python
> > # add surface to view
> > view.add(surface)
> > 
> > # do something
> > 
> > # remove surface from view
> > surface.parent = None
> > 
> > # do something
> > 
> > # re-add surface to view
> > view.add(surface)
> > ```
> > 
> > 
> > If you just want to temporarily disable visualizing it, you also can do
> > ```python
> > # do not plot surface
> > surface.visible  = False
> > 
> > # do something
> > 
> > # make visible again
> > surface.visible  = True
> > ```

**Comment by lichengqi0805** [comment]
> @q-chen95 You can just set the parent of the visual to None:
> 
> ```python
> # add surface to view
> view.add(surface)
> 
> # do something
> 
> # remove surface from view
> surface.parent = None
> 
> # do something
> 
> # re-add surface to view
> view.add(surface)
> ```
> 
> If you just want to temporarily disable visualizing it, you also can do
> 
> ```python
> # do not plot surface
> surface.visible  = False
> 
> # do something
> 
> # make visible again
> surface.visible  = True
> ```

How can I delete the visual element from memory, for instance the surface in the above code.

**Comment by djhoese** [comment]
Please file a new issue @lichengqi0805. In python if you want to get rid of an object that only has one reference to it you can do `del surface`.
