### ISSUE TITLE
Slow TurntableCamera

### ISSUE THREAD

**Issue by povik** [vispy/vispy#1878]
Hello!

While trying out vispy (v0.6.4), I set up two view boxes with linked turntable cameras, like so:

```
from vispy import app, gloo, visuals, scene, io
canvas = scene.SceneCanvas(keys='interactive')
canvas.size = 800, 600
canvas.show()
vb1 = scene.widgets.ViewBox(border_color='yellow', parent=canvas.scene)
vb2 = scene.widgets.ViewBox(border_color='blue', parent=canvas.scene)
grid = canvas.central_widget.add_grid()
grid.padding = 6
grid.add_widget(vb1, 0, 0)
grid.add_widget(vb2, 0, 1)
vb1.camera, vb2.camera = scene.TurntableCamera(), scene.TurntableCamera()
vb1.camera.link(vb2.camera)
```

I found the result to be sluggish in that there's noticeable delay between mouse input and redraw when manipulating the camera. Looking at `--vispy-cprofile` output, I noticed there's significant time spent in calculating matrix inverses:

```
         3229935 function calls (2994911 primitive calls) in 10.236 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    9.277    9.277 _default_app.py:58(run)
        1    0.000    0.000    9.277    9.277 application.py:135(run)
        1    0.000    0.000    9.277    9.277 _qt.py:274(_vispy_run)
        1    1.691    1.691    9.277    9.277 {built-in method exec_}
  267/210    0.008    0.000    7.599    0.036 _qt.py:507(event)
  267/210    0.043    0.000    7.590    0.036 {function QtBaseCanvasBackend.event at 0x7f1234a18560}
32621/887    0.274    0.000    7.549    0.009 event.py:405(__call__)

...

     5642    0.036    0.000    2.637    0.000 linear.py:403(inv_matrix)
     5638    0.012    0.000    2.599    0.000 <__array_function__ internals>:2(inv)
    12149    0.225    0.000    2.574    0.000 function.py:184(__setitem__)
     5638    2.414    0.000    2.571    0.000 linalg.py:482(inv)
      704    0.012    0.000    1.919    0.003 turntable.py:137(_rotate_tr)
     1408    0.011    0.000    1.757    0.001 linear.py:446(rotate)
```

I saw that `Base3DRotationCamera._update_camera_pos` and turntable camera's `_update_tr` construct a new transformation matrix by first resetting the matrix encapsulated in `MatrixTransform` held in `self.transform`, then calling a sequence of methods which operate on the encapsulated matrix in-place. This triggers calculation of matrix inverse inside MatrixTransform at each step of the way.

By chaining `np.dot`s, then assigning the finished matrix to MatrixTransform (see [here](https://gist.github.com/povik/27e38f2b30a0344d2a13c2b7fd0eac03#file-newttcam-py-L140)), I was able to improve the response time such that, on my machine, the result is now pleasant to interact with.

**Comment by povik** [comment]
Let me know your suggestions on changes I can make in vispy's code to make the camera faster. I will be happy to prepare a PR.

**Comment by kmuehlbauer** [comment]
@povik Thanks for creating the issue and sharing your improvements.

A PR would be very welcome, as we can better compare the changes and make suggestions.

**Comment by djhoese** [comment]
I don't have time to look through the existing pull requests, but I think a couple people have attempted these types of fixes before. I agree with Kai that a PR with your changes would be a good step in addition to comparing your thoughts with any existing PR solutions.

**Comment by povik** [comment]
Hi @kmuehlbauer, @djhoese.

Take a look at #1884, it has the changes I mentioned above that sped things up.

Ad other existing PRs. I only found #950 which might be relevant, but it seems stale and I cannot assess the impact nor if it was superseded.

**Comment by djhoese** [comment]
Great! I'll try to take a look later today. I think I was thinking of #1600 but it looks like that was for a different transform usage outside of the cameras.

**Comment by povik** [comment]
As #1884 is merged I am closing the issue.
