### ISSUE TITLE
how to get the top view of the original view? (Rotate 90 degrees upward)

### ISSUE THREAD

**Issue by q-chen95** [vispy/vispy#1879]
`import numpy as np
from vispy import app, scene
from vispy.gloo.util import _screenshot

canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()
view.camera = 'turntable'

xx, yy = np.arange(-1,1,.02),np.arange(-1,1,.02)
X,Y = np.meshgrid(xx,yy)
R = np.sqrt(X2+Y2)
Z = lambda t : 0.1np.sin(10R-2np.pit)
surface = scene.visuals.SurfacePlot(x= xx-0.1, y=yy+0.2, z= Z(0),
shading='smooth', color=(0.5, 0.5, 1, 1))
view.add(surface)
canvas.show()

def make_frame(t):
surface.set_data(z = Z(t)) # 更新曲面
canvas.on_draw(None) # 更新Vispy的画布上的 图形
return _screenshot((0,0,canvas.size[0],canvas.size[1]))[:,:,:3]`

![11](https://user-images.githubusercontent.com/65799760/85256248-6b820a80-b496-11ea-8cc9-903ca9d752bf.png)

Hello, the picture is the original view.How can i get the top view of the original view through the code? (Rotate 90 degrees upward, do not change the data)
 Thank you!

**Comment by q-chen95** [comment]
I have another problem.

`self.canvas = SceneCanvas(bgcolor='w', parent=self.ui.vispy_widget)  # (self.ui.vispy_widget is a QWidget by pyqt5)
self.view = self.canvas.central_widget.add_view()
self.view.add(...)
`
![1q](https://user-images.githubusercontent.com/65799760/85356831-84e09080-b542-11ea-97b2-42a9d94f0ffe.png)

Just like the picture: the canvas will not zoom in when pyqt5 mainwindow zoomed in.
How to make the canvas adaptively zoom with the main window？
Thanks!

**Comment by djhoese** [comment]
For your first question, you should be able to adjust the angles by specifying them either when you create the camera:

```
view.camera = TurntableCamera(...)
```

The example doing `view.camera = 'turntable'` is just a shortcut for the above. You can change some properties of the camera after the initial camera is created:

```
view.camera.elevation = 60
```

See http://vispy.org/scene.html#vispy.scene.cameras.TurntableCamera.elevation and the surrounding documentation for other angles you can change.

As for your second question, I'm not really sure what's going on. You'd have to provide some actual code for me to have any idea how to debug it further. My guess is that you aren't adding the widget to the layout properly. You typically not only need to set a parent widget but also add the canvas' native Qt widget to the Qt layout: `my_qt_layout.addWidget(self.canvas.native)`
