### ISSUE TITLE
Pytest missed in dependecies

### ISSUE THREAD

**Issue by Czaki** [vispy/vispy#1887]
in top level `__init__` file there is testing import 

https://github.com/vispy/vispy/blob/b5f6228c7c4ec734206e9556033f5c3e7941616c/vispy/__init__.py#L32

which import `testing._testing`

https://github.com/vispy/vispy/blob/b5f6228c7c4ec734206e9556033f5c3e7941616c/vispy/testing/__init__.py#L43-L51

which import pytest 

https://github.com/vispy/vispy/blob/b5f6228c7c4ec734206e9556033f5c3e7941616c/vispy/testing/_testing.py#L14

It looks intentional (`# noqa` after import) but pytest is not listed in package requirements in `setup.cfg` 

IT should be fixed, or `pytest` should be added to package requirements?

**Comment by djhoese** [comment]
I definitely don't want pytest to be a hard requirement to use vispy. This is likely something we missed when refactoring testing over the last month or so. Looking at the `_testing.py` module, it looks like we are only importing it at the top level so we can use `skipif` throughout the module. I think if we either wrap `skipif` in a function that imports pytest with every call or import pytest everywhere that we use skipif. Or one other option would be a:

```
try:
    import pytest
    skipif = pytest.mark.skipif
except ImportError:
    skipif = None
```

Eh maybe that's a bad idea and won't work either.

**Comment by Czaki** [comment]
but why `test` is imported in vispy init? Maybe it can be omitted?

**Comment by djhoese** [comment]
I have a feeling it is to make it easier for people to do:

```
import vispy
vispy.test()
```

Ah, yep, here it is http://vispy.org/installation.html#testing-installation

**Comment by Czaki** [comment]
Maybe change to this? 
```python 
def test()
    from .testing import test as _test
    _test()
```

**Comment by djhoese** [comment]
Maybe `return _test()`. I'd be ok with that. Good idea. One issue I see is not having this decorator on this new function:

https://github.com/vispy/vispy/blob/b5f6228c7c4ec734206e9556033f5c3e7941616c/vispy/testing/_runners.py#L360

**Comment by Czaki** [comment]
Using `nottest` is problematic, because it is also defined in `testing` module. But I do this annotation manually.

**Comment by Czaki** [comment]
@djhoese 
It looks like vispy has multiple dependencies on `testing` module. 
In my opinion function like `has_matplotlib` should be moved outside `testing` package. I think that best destination is `util` module. 

But maybe you prefer wrap all pytest call (this may increase maintenance cost in future).

What is your opinion?

**Comment by djhoese** [comment]
Good find. I agree `has_matplotlib` should probably be moved to `vispy/utils/` somewhere (new module maybe?).

I think as a summary of this issue so far: I don't think pytest is used anywhere except for the actual tests. We don't want to depend on pytest if we don't have to in the main vispy code (I don't think we do). Some functions from the testing code (has_matplotlib) are being used outside tests and should be moved to a more central/utility location.
