### ISSUE TITLE
Fixed axes for turntable camera

### ISSUE THREAD

**Issue by ZedZeal** [vispy/vispy#1890]
Hello, 
first of all I would like to thank you for this library, I have just began to look at it but I am already amazed but what it can do.
However, by looking at the examples, I did not find exactly what I am looking for.
Given a 3d object like the one in examples/basis/scene/volume.py, would it be possible to have a camera similar to the turntable one, but that moves on a straight line, always looking at the object? I will include with the question a gif in order to better explain myself. I will also include a gif on how the intended result would appear.

Thank you for your time.
![Camera-Linear2](https://user-images.githubusercontent.com/50443714/86804859-97e17d80-c077-11ea-880f-beb16266d403.gif)
![Lenny3D](https://user-images.githubusercontent.com/50443714/86804974-ba739680-c077-11ea-9779-c9c9acd4a323.gif)

**Comment by djhoese** [comment]
Really cool idea. There isn't anything that does this out of the box in vispy. Most of our cameras attempt to give you a full view of the Scene (all the way around) so this doesn't fit that generic use case. You *might* be able to mimic what you want without creating a whole new camera by creating your own mouse event handler on your canvas and have it modify the attributes of the turntable camera when the user drags the Scene around. I think you could look at the turntable source code or the arball camera or even their base class `Base3DRotationCamera` which may give you easy-ish access to the functionality you are looking for.

**Comment by ZedZeal** [comment]
Hi, it has been a while but I wanted to update you on this request. Initially I thought there was an easy way to set the camera in the (x,y,z) space, but I did not find it without having to delve too deep in the code. Having the ability to modify the camera distance and the azimuth, I simply created a copy of the Turntable camera class, with the only modification that I do not allow any elevation movement and I clip the azimuth rotation bewtween -30 and 30 and whenever I move the camera I update the distance accordingly, using trigonometry. I think this recreates the same camera movement as my gif above, what do you tink?
![perspective_3d](https://user-images.githubusercontent.com/50443714/88525765-4d5e7b80-cffb-11ea-89aa-375f68c7889f.png)

**Comment by djhoese** [comment]
Yes! This is exactly what I was thinking, but thought you might be able to hack it with a mouse event handler on your canvas. Making a subclass/copy of the Turntable class is even better. Trigonometry for the win.
