### ISSUE TITLE
vispy.color.Color.hex doesn't encode alpha value

### ISSUE THREAD

**Issue by h3fang** [vispy/vispy#1898]
For example

```python
from vispy.color import Color

print(Color((0.4, 0.6, 0.8, 0.5)).hex)
print(Color((0.4, 0.6, 0.8, 0.5), alpha=0.3).hex)
```
The output is 
```
#6699cc
#6699cc
```

Is this intended or a bug?

**Comment by djhoese** [comment]
I don't think hex colors, by their usual definition and usage in web standards and other places, include alpha. I think they are usually just RGB values (for example https://www.w3schools.com/colors/colors_picker.asp). So I think this is expected/intended. Do you have a use case where you *need* the color in hex with the alpha included?

**Comment by h3fang** [comment]
I want to export colors with alpha value to mapbox. I was thinking of something similar to [https://i3wm.org/docs/userguide.html#_transparency](https://i3wm.org/docs/userguide.html#_transparency).
After your comment,  I found out mapbox's color specification doesn't use RGBA hex values as well.
[https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color](https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#color)
Thank you for the information.
