### ISSUE TITLE
How to unset data?

### ISSUE THREAD

**Issue by stsdc** [vispy/vispy#1901]
After adding some markers, I'm trying to set empty data, so no markers will be visible and present in a view:
```python
self.plot_markers.set_data(np.asarray([]), face_color=np.array([[]], **self.marker_style)`
```

but it throws an error: `ValueError: color must have three or four elements`.

**Comment by kmuehlbauer** [comment]
@stsdc You might use the `visible`-attribute of the markers object to switch it on/off.

**Comment by stsdc** [comment]
To be precise: I have only one marker in a list and  I want it to delete, so I delete it from the list, so list is empty `[ ]`, but I can't put empty list to `set_data` arguments. Visibility property will switch all markers visibility. I'll end up with markers that I didn't want to show with those I want to display.

**Comment by djhoese** [comment]
I'm not sure I understand what you're trying to do (I would have recommended the visible property too), but if you are setting the data to an empty array then do you even need to set `face_color`? That's what the error message is talking about.

To clarify on the visible property, that should be *per visual* so it should only effect the `self.plot_markers` when you do `self.plot_markers.visible = False`.

**Comment by stsdc** [comment]
As I can see from [docs](http://vispy.org/visuals.html#vispy.visuals.MarkersVisual) `face_color` is white if not set. Every marker array data element in _visual_ must have a corresponding element in array of colours. I can't set colour to the empty array, because this is an `assert (isinstance(pos, np.ndarray) and AssertionError`. And also I can't set empty colour array, because this is a `ValueError: color must have three or four elements`.

If I do `self.plot_markers.visible = False` and then add new marker and enable visibility again I'll have two markers.

**Comment by djhoese** [comment]
Ah ok, good point. You can't set `pos` to an empty array.

> then add new marker and enable visibility again I'll have two markers

Why would you have two? `set_data` should overwrite the old data so the following should only give you one marker:

```
pos = np.array([[0, 0]])
self.plot_markers.set_data(pos, ...)
# one marker on screen
self.plot_markers.visible = False
# no markers on screen
# change position of marker:
pos[0, 1] = 1
self.plot_markers.set_data(pos, ...)
# no markers on screen
self.plot_markers.visible = True
# one marker on screen
```

Right? What am I missing? Sorry it's early here.

**Comment by stsdc** [comment]
Well, at some point I don't want to have any markers in visual. But I resolved it in a such way:
1. There is the last marker, that is deleted
2. Set visibility to `False`
3. No markers visible, but the last one persist in `pos`
4. Add new markers, if needed. The last marker will be replaced with a new `pos`

@djhoese Thanks a lot :+1:

**Comment by djhoese** [comment]
Glad that something worked. If you feel strongly about it I'd welcome a PR that allowed for an empty array to the MarkersVisual. Otherwise, I'll close this as it seems you found something that works. Feel free to reopen or keep commenting if you'd like.
