### ISSUE TITLE
Weird behaviour in drawing order

### ISSUE THREAD

**Issue by soraxas** [vispy/vispy#1903]
Hi! I am experiencing some very weird behaviour on the drawing order of nodes.

Based on the documentation, I believe that children nodes are always drawn after their respective parent nodes, and `obj.order` are used to break tie when they are at the same level. But what I experienced is something that I couldn't wrap my head around.

See the following example code used throughout the demonstration:

```python
from vispy import __version__, app, scene, use
from skimage import data
import numpy as np

canvas = scene.SceneCanvas(show=True)
view = canvas.central_widget.add_view()
view.camera = scene.PanZoomCamera(aspect=1)
view.camera.flip = (0, 1, 0)

img = scene.Image(
    data.camera(), 
    parent=view.scene,
    )
markers1 = scene.Markers(
    pos=np.array([[300, 300]]),
    symbol='o',
    size=100,
    parent=img
)
# ellipse = scene.Ellipse(
#     center=np.array([100, 100]),
#     radius=(200,500),
#     color=(1, 0, 0),
#     parent=markers1,
# )
# ellipse.order = -1000

# set the view to show the images
view.camera.set_range((-30, img.size[0] + 30),
                      (-30, img.size[1] + 30))

print(__version__)
print(view.describe_tree())
print(canvas._generate_draw_order())

app.run()
```
with output
```sh
0.6.4
ViewBox
  +--SubScene
     +--BaseCamera
     +--PanZoomCamera
     +--Image
        +--Markers

[(<SubScene at 0x7fb6f7c287b8>, True), (<Widget at 0x7fb6f7c38f28>, True), (<ViewBox at 0x7fb6d4173080>, True), (<SubScene at 0x7fb6d413b2e8>, True), (<BaseCamera at 0x7fb6d41c97b8>, True), (<BaseCamera at 0x7fb6d41c97b8>, False), (<PanZoomCamera at 0x7fb6d4187630>, True), (<PanZoomCamera at 0x7fb6d4187630>, False), (<Image at 0x7fb715e6d400>, True), (<Markers at 0x7fb69f88c630>, True), (<Markers at 0x7fb69f88c630>, False), (<Image at 0x7fb715e6d400>, False), (<SubScene at 0x7fb6d413b2e8>, False), (<ViewBox at 0x7fb6d4173080>, False), (<Widget at 0x7fb6f7c38f28>, False), (<SubScene at 0x7fb6f7c287b8>, False)]
```
produces
![vispy_1](https://user-images.githubusercontent.com/22362177/90716706-ea59bf00-e2f0-11ea-985a-adce16926ed8.png)

**Observation:** I expect `markers1` to be drawn in front of `img` (as `img` is the parent of `markers1`), but the result is the image overlaid the markers.

------------------------------
I uncomment the part of code that draw an ellipse

```python
ellipse = scene.Ellipse(
    center=np.array([100, 100]),
    radius=(200,500),
    color=(1, 0, 0),
    parent=markers1,
)
```
with outputs
```sh
0.6.4
ViewBox
  +--SubScene
     +--BaseCamera
     +--PanZoomCamera
     +--Image
        +--Markers
           +--Ellipse

[(<SubScene at 0x7fb0641b7860>, True), (<Widget at 0x7fb0641c7fd0>, True), (<ViewBox at 0x7fb06040e5f8>, True), (<SubScene at 0x7fb06daf9e48>, True), (<BaseCamera at 0x7fb0603f0390>, True), (<BaseCamera at 0x7fb0603f0390>, False), (<PanZoomCamera at 0x7fb0603bb5f8>, True), (<PanZoomCamera at 0x7fb0603bb5f8>, False), (<Image at 0x7fb00c83fef0>, True), (<Markers at 0x7fb00be38630>, True), (<Ellipse at 0x7fb00be63630>, True), (<Ellipse at 0x7fb00be63630>, False), (<Markers at 0x7fb00be38630>, False), (<Image at 0x7fb00c83fef0>, False), (<SubScene at 0x7fb06daf9e48>, False), (<ViewBox at 0x7fb06040e5f8>, False), (<Widget at 0x7fb0641c7fd0>, False), (<SubScene at 0x7fb0641b7860>, False)]
```
produces
![vispy_2](https://user-images.githubusercontent.com/22362177/90716878-5b00db80-e2f1-11ea-8fff-7489065dd5c6.png)

**Observation:** Somehow adding an `ellipse` causes `marker1` to be able to draw in front of the `img`. However, the `ellipse` should not be behind the `img`.

------------------------------
Finally, I changed the `ellipse`'s parent to be the scene itself, and changed `ellipse`'s order

```python
ellipse = scene.Ellipse(
    center=np.array([100, 100]),
    radius=(200,500),
    color=(1, 0, 0),
    parent=view.scene,  # <=== NOTE this had changed
)
ellipse.order = -1000
```
with output
```sh
0.6.4
ViewBox
  +--SubScene
     +--BaseCamera
     +--PanZoomCamera
     +--Image
     |  +--Markers
     +--Ellipse

[(<SubScene at 0x7f1d3da766d8>, True), (<Widget at 0x7f1d3da86e48>, True), (<ViewBox at 0x7f1d2404a438>, True), (<SubScene at 0x7f1d18ef5208>, True), (<Ellipse at 0x7f1ce568a7b8>, True), (<Ellipse at 0x7f1ce568a7b8>, False), (<BaseCamera at 0x7f1d2402b390>, True), (<BaseCamera at 0x7f1d2402b390>, False), (<PanZoomCamera at 0x7f1d24068438>, True), (<PanZoomCamera at 0x7f1d24068438>, False), (<Image at 0x7f1ce6063eb8>, True), (<Markers at 0x7f1ce565e710>, True), (<Markers at 0x7f1ce565e710>, False), (<Image at 0x7f1ce6063eb8>, False), (<SubScene at 0x7f1d18ef5208>, False), (<ViewBox at 0x7f1d2404a438>, False), (<Widget at 0x7f1d3da86e48>, False), (<SubScene at 0x7f1d3da766d8>, False)]
```
produces
![vispy_3](https://user-images.githubusercontent.com/22362177/90716996-b03ced00-e2f1-11ea-9b78-48deba588c17.png)

**Comment by djhoese** [comment]
Another issue that has a lot on this is https://github.com/vispy/vispy/issues/1541. I think in general you have to worry about the *order* of the visual, the z-level of the visual, and sometimes the depth testing setting. So while your results are unexpected (even for me) I'm not sure they are unexpected for OpenGL. Bottom line: I'm not sure you can depend on parent-child relationships (at least not right now) to determine drawing order.

**Comment by soraxas** [comment]
Yes, I have read that issue (in fact my example code is partly based on it). I think the thing that strikes me most, in this case, is scenario 1 -> 2, where somehow adding an ellipse influence the drawing of other elements (it doesn't really make sense...). As you have said it might be due to some internal issue within OpenGL rather than `vispy` itself, as I had briefly dig into `vispy`'s drawing function (esp. drawing order) and the ordering should have been correct. Therefore, it might be that `vispy` correctly calls OpenGL in the intended order, but OpenGL fails to display the expected result....?

On a side note, I cannot get any opacity working even with the suggested changes in #1541. I wasn't sure if it's because I am using `PyQt5` instead of `PyQt4` as in #1541 (in the issue it stated that PyQt5 backend's handling might be different?), but I am unable to install and test with `PyQt4` on my machine. I've was able to try `pyside2` but no opacity as well. I am stating these just in case these are related to this issue.

However, this issue does not involve opacity in any way, unlike #1541, but the draw order is still behaving very strangely.

**Comment by djhoese** [comment]
Hm PyQt5 is the newly "most supported" backend so I would hope that it would work. That said, I've seen weird things with transparency and PyQt5 in the past. I see that I commented about setting `cam.alpha = 0.5` and now that isn't even available any more. I'll have to look into this more. Memory isn't serving me well today.

**Comment by djhoese** [comment]
Ah it is `.opacity`, works for me in PyQt5:

![image](https://user-images.githubusercontent.com/1828519/90787648-91773000-e2ca-11ea-97d7-88ca84330944.png)

**Comment by soraxas** [comment]
Ahh I see thanks heaps for your kind explanation @djhoese. Previously I also missed your suggestion of setting `z-level` in `STTransform` to be on a different level, which is needed for opacity to work (this is made even more apparent by using **turntable** camera to inspect the result instead of **panzoom**).

I really like `vispy` ever since I discovered it, especially how it enables users to operate the fast OpenGL engine in a high-level manner (while still exposing the lower-level stuff via gloo for poweruser). Previously I have been using the more primitive `pygame` engine for visualising while conducting experiments, which is quite a bit slower but it's easier to understand what's going on with the drawings things on the screen.

**Comment by soraxas** [comment]
I guess due to the nature of how OpenGL draw entities, it is hard for the engine to decide which entities should be displayed at the front if their coordinates coincide at the same `z-level` (especially for 2D view in **panzoom**). 

Is this true, where one should probably manually set `z-level` with translation to correctly decide which entity are in front or in the back?

As in, in contrast to how `pygame` blit pixels on screen (which is easier to control the draw order), OpenGL is fundamentally harder to operate as a 2D engine without manually offsetting the z-level of each entity?

**Comment by soraxas** [comment]
Hi @djhoese thank you for your kind explanation, and I do understand that while this is not intuitive in how to display things in the correct order, this might be more of a quirk of OpenGL rather than vispy.

Because `.order` or `parent`/`child` relationship doesn't really work as intended for this project in terms of display (or at least not as effective as manually offsetting `z-level`), a possible suggestion might be **vispy** automatically setup the elements to the correct relative `z-level` (esp. for 2D view) or as an optional argument that user can tell vispy to automatically resolve the relative `z-level`.

A counter argument might be that this will cause vispy to do too much of dark magic in the background and confuses users. But at least, I think we should have some notes or documentation stating that `.order` or `parent`/`child` relationship might not work as intended due to OpenGL's quirks, and suggest try setting `z-level` if things are not working for them. (i.e. I'm refering to notes in http://vispy.org/ rather than digging through isses in github)

**Comment by djhoese** [comment]
I won't say this will *never* happen, but I can't see this being flexible enough to not cause issues for others. When I'm saying `z-level` we're talking about the Z position in X, Y, Z space. Even if we're only viewing things in 2D, zooming and panning around is still effected by how far things are from each other in the Z dimension. I definitely think this could be added to an FAQ and this is also something the napari project (big user of vispy) is annoyed by (CC @jni @sofroniewn). I recently got the accounting finalized for our CZI grant and hope to use it for things like this; FAQ, contributor's guide, etc.

**Comment by soraxas** [comment]
I completely understand that, as I too do reckon that using `z` position as a way to enforce display order is a dirty (but reliable) hack. And I do agree with you that my proposed approach might cause issues for others; however, considering that this is the current *de facto* way to reliably display some entities in front of other entities, I don't see how vispy doing it would be any different than user doing it.

Having said that, if the rationale behind is vispy as a library shouldn't implement these workarounds and should leave users themselves to implement them, I do understand that. Shouldn't be too hard as well, probably in the lines of tapping into `canvas._generate_draw_order()` and setting the `z` level accordingly.

It is exciting to hear about your upcoming plans and you being able to get grants to support your project. Thanks for your contribution to this great project and good luck with everything.

I will close this issue and leave #1541 open to track this issue (even though its title is about *opacity*, I think the underlying issue remain to be the same).

**Comment by djhoese** [comment]
Thanks for your understanding. I'm hoping the napari team and I can come up with something sensible. At the very least something to document on how handle this consistently.
