### ISSUE TITLE
Fix CSS issues in custom sphinx theme

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1906]
The current website has some CSS issues, at least for me on firefox. Go to http://vispy.org/.

![image](https://user-images.githubusercontent.com/1828519/91510804-b9a2f800-e8a3-11ea-88ae-7005e81d1dd3.png)

The bullet on the left is outside the gray box and I'm not actually sure why Community is the only thing listed there. It is possible there is supposed to be more, but that's likely a separate issue. Additionally there is a double arrow on the navigation part on the top right.

For anyone wishing to help with this see these instructions for how we release the website for a little guidance on generating the html: https://github.com/vispy/vispy/wiki/Releasing-new-version-of-VisPy-python-package#upload-documentation

Of course, feel free to comment here if you have any questions. It may also be a good idea to comment to mention that you plan on working on this.

**Comment by abhishek-pes** [comment]
I would like to work on this.

**Comment by abhishek-pes** [comment]
so I have done these changes

![Capture](https://user-images.githubusercontent.com/54106076/91525162-818ccb00-e91e-11ea-9590-a27d6caed740.JPG)

I have fixed the issue of the content list and also the empty drop down menu.
I have also fixed the UI for all the pages it is linking to 

![Capture2](https://user-images.githubusercontent.com/54106076/91525254-b4cf5a00-e91e-11ea-99fb-32988f83a902.JPG)

please feel free to give any suggestion

**Comment by kmuehlbauer** [comment]
@djhoese I just see, that the site doesn't use `https`. If this is a github pages we should set it there. But I don't have enough power to do so. Who has the means to do so, @larsoner?

**Comment by kmuehlbauer** [comment]
@abhishek-pes Looks good to me. :+1:

**Comment by abhishek-pes** [comment]
so i have made a pull request , please check the pull requests in  : [](https://github.com/vispy/vispy.github.com/pulls) @djhoese

**Comment by abhishek-pes** [comment]
so i have made a pull request in the repository of the GitHub page, please check the pull requests here: https://github.com/vispy/vispy.github.com/pulls  @djhoese

**Comment by abhishek-pes** [comment]
> @abhishek-pes Looks good to me. 👍

thanks

**Comment by abhishek-pes** [comment]
@djhoese  @kmuehlbauer 
You can see the changes I have made here : https://abhishek-pes.github.io/vispy.github.com/

**Comment by djhoese** [comment]
Thanks for looking at this @abhishek-pes. Looking really good. As @kmuehlbauer pointed out this will need to be ported to https://github.com/vispy/vispy-website for us to accept it. The repository you made the PR on is generated from the `vispy-website` repository.

@kmuehlbauer Yes we should do more CI work on the website but we had other decisions to make (see #1374). I was just talking to @jni about this and the https://drdoctr.github.io/ tool. I have more experience with readthedocs which we haven't migrated to but drdoctr would make it easier to use github pages. We are currently using github pages for vispy.org and readthedocs for the same site but at api.vispy.org.

As for the HTTPS certificate stuff. The issue for vispy.org is that github pages is trying to host the site with the github.io certificate and most browsers (at least firefox for me) complains about the certificate not matching the domain. For readthedocs, it is passing vispy.org's certificate along just fine which is interesting. Any changes to this stuff (vispy.org-wise) would have to go through @almarklein who owns the domain and the cloudflare (I think?) server hosting it.

Any opinions?

**Comment by kmuehlbauer** [comment]
@djhoese Same here, more experience with readthedocsy also with hacking together docs from different sources. But I'm open to learn something new. So if `doctr` will fit suit, then why not use it?

**Comment by djhoese** [comment]
We will likely be transitioning to the pydata sphinx theme and will no longer need these CSS fixes. Sorry.
