### ISSUE TITLE
Easily enable 32-bit depth buffer.

### ISSUE THREAD

**Issue by zhou13** [vispy/vispy#1910]
I am trying to create a FrameBuffer with 32-bit depth buffer. This requires OpenGL extension GL_DEPTH_COMPONENT32. It seems that vispy does not have this constant, and the following is the best I could do
```python
fbo = gloo.FrameBuffer(
    gloo.Texture2D(shape=output_size[::-1] + (4,), internalformat="rgba32f"),
    gloo.RenderBuffer(shape=output_size[::-1], format=33191),
)
```

Here, 33191 is the value of GL_DEPTH_COMPONENT32. I don't like the constant here. Is there a more elegant solution to this?

**Comment by kmuehlbauer** [comment]
@zhou13 Thanks for bringing this up.

The vispy constants are derived from the original (khronos) gl header files located in the `codegen` subfolder. AFAICS there is the `gl2ext.h` header which contains the line (0x81A7 == 33191):

`#define GL_DEPTH_COMPONENT32_OES                                0x81A7`

In `createglapi.py` there are means to extract the `OES` extensions by stripping `_OES` from the string. Unfortunately `gl2ext.h` is not processed.

@almarklein worked on this back in the days. Very much appreciate any hints on that topic. Also @larsoner might has some ideas.

**Comment by kmuehlbauer** [comment]
Seems we could create `_constants_ext.py` by adding a parser for `gl2ext.h` to `createglapi.py`. My knowledge of these vispy parts lack very much, so I can't say If this is just as easy as adding the above, or if there is more involved. @djhoese any thoughts here?

**Comment by djhoese** [comment]
I don't have much experience with the codegen stuff. Don't the generated `.py` files have to be manually requested with `use_gl(..)`: https://github.com/vispy/vispy/blob/a9f04f12027b56a444b827c9b8708ff57b1f1e5b/vispy/gloo/gl/__init__.py#L61

Adding a new file there would require more work right? Or I guess if these are just extensions then maybe this would get appended to one of the existing .py files?

**Comment by kmuehlbauer** [comment]
@zhou13 I think it should be possible to access this via `pyopengl`. 

You would need to load vispy with:

```python
import vispy
vispy.use(gl='gl+')
```
Then the constant should be available via (`vispy.gloo.gl.GL...`). If this works for you, this issue might be closed.

**Comment by kmuehlbauer** [comment]
@zhou13 Did you had a chance to test if the above snippet works for you?

**Comment by zhou13** [comment]
@kmuehlbauer  Thank you! That works for me.
