### ISSUE TITLE
Replace bundled "decorator" dependency

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1922]
We currently have a dependency on the "decorator" library, but include it as a bundled module here:

`vispy/ext/_bundled/decorator.py`

and then import it here:

`vispy/ext/decorator.py`

where the `decorator` decorator is only used once here:

https://github.com/vispy/vispy/blob/397c3122d5644692e6e1ae6d281b7b72d741fae6/vispy/visuals/transforms/_util.py#L85-L86

I think this dependency could be removed if `arg_to_vec4` was rewritten to use https://docs.python.org/3/library/functools.html#functools.wraps or a similar standard library utility.

@larsoner you probably know the most about this, any concerns? Otherwise I say we let a hacktoberfest participant handle this.

**Comment by larsoner** [comment]
I can't remember why we went with `decorator` for this one. I'd say get rid of it, hopefully `functools.wraps` is enough nowadays.

**Comment by sgaist** [comment]
Hi,

I am interested in this one.

**Comment by djhoese** [comment]
Thanks @sgaist. You have been assigned to this issue. Let me know if you change your mind. I'll try to check in later to check on your status (after we are in October for a bit).
