### ISSUE TITLE
Remove Python 2.7 wrapper around GzipFile

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1923]
This module: https://github.com/vispy/vispy/blob/9dbe751dcdbaaa1d17d0a5885f15872b9b0741a8/vispy/ext/gzip_open.py

Is used in two places in vispy (one module) and only exists to be used by Python 2.7 environments which we no longer support. This module and it's usages should be replaced by `GzipFile`: https://docs.python.org/3/library/gzip.html#gzip.GzipFile

Usage 1:

https://github.com/vispy/vispy/blob/9dbe751dcdbaaa1d17d0a5885f15872b9b0741a8/vispy/io/wavefront.py#L70

Usage 2:

https://github.com/vispy/vispy/blob/9dbe751dcdbaaa1d17d0a5885f15872b9b0741a8/vispy/io/wavefront.py#L254

And of course the import in that module should be removed.

**Comment by jyoungiv** [comment]
Hello, I would like to contribute, may I be assigned to this issue?

**Comment by Kartik-byte** [comment]
Hey, I would like to work on this too. If it is possible may I be assigned?
Thank you.

**Comment by djhoese** [comment]
@Kartik-byte Only if @jyoungiv has decided not to do it. @jyoungiv do you plan on working on this still?

**Comment by Kartik-byte** [comment]
Okay sure, I just saw that in my  last PR ,by mistake, I took a issue that someone else was assigned to . I felt bad. Not gonna do that this time. Still trying to learn github.
Sorry.
