### ISSUE TITLE
Replace bundled 'pypng' (png) dependency with pillow

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1925]
VisPy currently bundles all or some of the pypng library here:

https://github.com/vispy/vispy/blob/master/vispy/ext/_bundled/png.py

And imports it here:

https://github.com/vispy/vispy/blob/master/vispy/ext/png.py

Where it then uses it here:

https://github.com/vispy/vispy/blob/master/vispy/io/image.py#L14
https://github.com/vispy/vispy/blob/master/vispy/io/image.py#L120

I would like to remove this usage and replace the `Reader` usage with the `pillow` (PIL) `open` function: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open

A dependency should be added on pillow in `setup.py` but since this functionality is only used in examples and tests (it seems) I think it could be added to the `io` extra here:

https://github.com/vispy/vispy/blob/ef75a61255e5cc60d51941134f346984da405bfd/setup.py#L225

We may need to look at modifying some of the environments in `.travis.yml` so they make sure to include pillow and don't try to install pypng/png.

**Comment by dipanshug124** [comment]
I would like to work on this issue

**Comment by Kartik-byte** [comment]
Please review my PR for this issue. #1934 .
Thank You.

**Comment by djhoese** [comment]
Closed by #1934.

**Comment by djhoese** [comment]
And sorry @dipanshug124 I just realized that you commented first and not Kartik. I thought you were the same person. There are still other hacktoberfest issues available. Please let me know if you need help tracking some more down.

**Comment by dipanshug124** [comment]
Its alright @djhoese , I'm done with hacktoberfest challenge. But if there's some other issue regarding Python do consider me.

**Comment by Kartik-byte** [comment]
@dipanshug124 hey I am sorry ,didn't mean to scoop in like that. I failed to notice that you were already assigned.
Sorry.

**Comment by dipanshug124** [comment]
@Kartik-byte there's no problem buddy🙌
