### ISSUE TITLE
Remove 'six' bundled dependency

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1926]
The `six` package is bundled in vispy here: vispy/ext/_bundled/six.py
And imported here: vispy/ext/six.py

This should be removed and *all* usage of the `six` library removed/replaced with python 3 equivalent checks throughout vispy.

**Comment by sgaist** [comment]
Hi,

I'd be interested in taking a shot at this one.

**Comment by djhoese** [comment]
Assigned. Thanks!

**Comment by scshiv29-dev** [comment]
Can I try too?

**Comment by djhoese** [comment]
@scshiv29-dev You can, but you would likely be doing duplicate work and there is a good chance that the PR made first (or the "best" PR) would be the changes I would merge.
