### ISSUE TITLE
unable to install correctly Vispy

### ISSUE THREAD

**Issue by jerome-rollback** [vispy/vispy#1929]
Hi
I m using conda and I will try to use Vispy; but I can't go futher than vispy.test()
(plateform win-64 / conda 4.8.5)
I have tracked all orders on post : **_vispy.test() failure #1453_**
but I have always the same issue.
Could someone give me a solution or advice ?
thanks

```
import vispy
vispy.test()
```
> Skipping backend pyqt4, not installed or working properly
> ----------------------------------------------------------------------
> ----------------------------------------------------------------------
> Running tests with pyqt5 backend:
> _VISPY_TESTING_APP=pyqt5   -m vispy_app_test C:\Users\nathalie\Anaconda3\lib\site-packages\vispy
> Failed: unit failure (2)...

**Comment by djhoese** [comment]
To clarify your issue, you have vispy *installed* but you can't seem to run it. Correct?

Similar to the pip installation method, the vispy conda-forge package does *not* include any backend dependency packages in its default installation. For example, if you'd like to use PyQt5 you should install `conda install -c conda-forge pyqt`. I would say that the "unit failure" error message is a little unexpected, it should fail more gracefully than that, it may also indicate that PyQt5 is installed poorly on your system or not at all. Could you provide more information about what you have installed? Could you run `print(vispy.sys_info())` and provide the output here?

**Comment by jerome-rollback** [comment]
That's correct I can't run anything.
I try 
```
conda create -c conda-forge -n vispy_env python=3.6 vispy pyqt=4* numpy nose pytest
source activate vispy_env
```
I set up the vispy_env or vispy... I tried to installed any package.( nose, pytest..)  Nothing works. same error.
The last cmde : `conda install -c conda-forge pyqt`
give : `# All requested packages already installed.
`
`print(vispy.sys_info())` gives me the following results

> Platform: Windows-7-6.1.7601-SP1
> Python:   3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
> NumPy:    1.14.2
> Backend:  PyQt5
> pyqt4:    None
> pyqt5:    ('PyQt5', '5.6', '5.6.2')
> pyside:   None
> pyglet:   None
> glfw:     None
> sdl2:     None
> wx:       None
> egl:      None
> osmesa:   None
> _test:    None
> 
> GL version:  '2.1.0 - Build 8.15.10.1883'

What s wrong ..?

**Comment by djhoese** [comment]
Hm, are you able to run any of the example scripts from the vispy repository? Something in the `examples/basics/` directory?

Just curious, what type of system are you on? It seems odd that a modern system would only support OpenGL 2.1.0. Are you running this from the Spyder IDE or a jupyter notebook?

**Comment by jerome-rollback** [comment]
I try to display a scene with a simple view... the  python kernel doesn't crash but nothing appears.
I launch the running from a jupyter notebook... may be an extension is missing ...?

Who said I have a modern system ... what minimum version of opengl is supported?

The vispy.test() causes the errors:

> =================================== ERRORS ====================================
> ______________________________ ERROR collecting  ______________________________
> _pytest\config.py:342: in _getconftestmodules
>     return self._path2confmods[path]
> E   KeyError: local('\\Anaconda3\\lib\\site-packages\\astropy
> ')
> 
> During handling of the above exception, another exception occurred:
> _pytest\config.py:373: in _importconftest
>     return self._conftestpath2mod[conftestpath]
> E   KeyError: local('\\Anaconda3\\lib\\site-packages\\astropy
> \\conftest.py')
> 
> During handling of the above exception, another exception occurred:
> py\_path\common.py:372: in visit
>     for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
> py\_path\common.py:410: in gen


what is the easiest way to reinstall everything for anaconda3?

thks

**Comment by djhoese** [comment]
> I launch the running from a jupyter notebook... may be an extension is missing ...?

Ah that's the problem. Did you follow the installation instructions? The jupyter widget for vispy *can* be installed but it is considered experimental. Additionally webgl does not support all of the features that the vispy tests are testing for so it will always fail some tests. I would recommend running from a regular terminal window if possible. Or, in your notebook, you can run examples by specifically specifying a different backend (ex. `vispy.app.use('pyqt5')`) which will open a separate window outside of the notebook to display your visualization.

**Comment by larsoner** [comment]
Closing as this is documented in the installation instructions
