### ISSUE TITLE
Vispy in jupyter lab

### ISSUE THREAD

**Issue by SergeyTsimfer** [vispy/vispy#1935]
Hello everyone

Tried to use `vispy` in my jupyterlab after installing the `vispy` lab extension, `pyqt5`, and `pyopengl`. After running the code, the cell output hangs on `Loading Widget`. The code snippet that I used (taken from one of the issues here):

```
import numpy as np
import vispy
import vispy.scene
from vispy import app
from vispy.scene import visuals
print("VISPY VERSION:", vispy.__version__)
app.use_app('ipynb_webgl')

ca = vispy.scene.SceneCanvas(keys='interactive', show=True)
ca.show()
view = ca.central_widget.add_view()
scatter = visuals.Markers()

color = np.array([
    [255, 0, 0]
])
data = np.random.random((2048, 3))
scatter.set_data(data, edge_color=None, face_color=color/255.0, size=5)
view.add(scatter)

view.camera = 'turntable' # or try 'arcball'

axis = visuals.XYZAxis(parent=view.scene)
app.run()
```

Am I doing something wrong or `vispy` does not support jupyter lab?

Cheers

**Comment by djhoese** [comment]
Try removing the `app.run()` and put the `ca.show()` at the bottom...and remove the `show=True` from the SceneCanvas creation. That *might* work.

Another option I think is to make the last line of the cell the canvas object (`ca`) by itself. I think that should trigger it to be shown properly. This is just a guess. As a reminder, I consider the jupyter widget experimental and it should not be used for "operational" uses.

**Comment by djhoese** [comment]
Any updates on this? I'm going to close this for now. If you're still having issues feel free to comment and we can reopen this. Thanks.
