### ISSUE TITLE
MNT: Stop using ci-helpers in appveyor.yml

### ISSUE THREAD

**Issue by pllim** [vispy/vispy#1944]
To whom it may concern,

If you are using https://github.com/astropy/ci-helpers in your appveyor.yml , please know that the Astropy project has dropped active development/support for Appveyor CI. If it still works, good for you, because we did not remove the relevant files (yet). But if it ever stops working, we have no plans to fix anything for Appveyor CI. Please consider using native Windows support other CI, e.g., Travis CI (see https://docs.travis-ci.com/user/reference/windows/). We apologize for any inconvenience caused.

If this issue is opened in error or irrelevant to you, feel free to close. Thank you.

xref astropy/ci-helpers#464

**Comment by larsoner** [comment]
@djhoese I would just kill AppVeyor entirely and use Azure for windows here. It's fairly easy to set up conda there. I am adapting a current AppVeyor script to use Azure here:

https://github.com/sphinx-gallery/sphinx-gallery/pull/767

Feel free to adapt it if it helps

**Comment by djhoese** [comment]
I personally am not a fan of Azure (the UI and the collaboration between organizational accounts and other's accounts). That said, visual/graphics based stuff doesn't work on Travis-Windows yet so it may be our only realistic option.

**Comment by pllim** [comment]
Hello. We apologize for any inconvenience caused.

If Azure doesn't work, what about Github Actions?

**Comment by larsoner** [comment]
> That said, visual/graphics based stuff doesn't work on Travis-Windows yet so it may be our only realistic option.

Even with gl-ci-helpers? This would be surprising because it injects a software rendering DLL. I'm not sure why this would fail on any Windows 7+ system

**Comment by djhoese** [comment]
@larsoner Last time I checked travis didn't have support for anything that required a virtual display and I think that included using gl-ci-helpers for the project I did it in.

https://travis-ci.community/t/make-running-gui-multimedia-apps-available-in-windows/1557

**Comment by larsoner** [comment]
Ahh I see. I don't know Windows that well but that makes some sense at least

**Comment by djhoese** [comment]
@kmuehlbauer This is done now that you've switched us to github actions, right? Closing now. Feel free to reopen if I'm mistaken.
