### ISSUE TITLE
Triangulation.py, Debug, _add_tri() function, assert problem

### ISSUE THREAD

**Issue by huanghesheng2012** [vispy/vispy#1948]
Hello, thank you for writing such a great program and sharing it. 

Use your program to generate a constrained triangulation, but when running to the _add_tri() function of triangulation.py, this assertion will hit, 

the assertion sentence is "assert (c , b) not in self._edges_lookup",

When I run the program to hit this assertion on my point set data, and stop, I find that these three points are collinear. How can I avoid this abnormal situation?

It's so sad. . . Because of this abnormal situation, the constrained triangulation of these points cannot be generated

**Comment by huanghesheng2012** [comment]
<img width="913" alt="vispy_debug" src="https://user-images.githubusercontent.com/25363766/98194938-85ab1980-1f5b-11eb-986d-8d6ae23bc0ff.png">
look, the three points that marked with yellow, are collinear, then the assertion sentence is hit, and program quit........

**Comment by djhoese** [comment]
This seems very similar to your issue in #1847. Is this the same issue? If this is different could you provide a small example piece of code and **small* bit of input data that shows this issue? Otherwise, I'm not sure I have enough knowledge about triangulation to help with this issue.

**Comment by larsoner** [comment]
Closing as dup of #1847
