### ISSUE TITLE
Can't get colorbar to show

### ISSUE THREAD

**Issue by mariakesa** [vispy/vispy#1950]
Hello:-)

I have a gui where I'm displaying a gray scale image and on top of it a scatter plot with changing colors. I need to show a colorbar for the colors. I don't know how to display the colorbar though! canvas.colorbar.draw() throws a weird error and without it the colorbar is not showing.

Here's the error:

```
WARNING: Error drawing visual <vispy.visuals.colorbar._CoreColorBarVisual object at 0x000001304E096A30>
WARNING: Traceback (most recent call last):
  File "viz_gui.py", line 152, in <module>
    vispy.app.run()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\app\_default_app.py", line 62, in run
    return default_app.run()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\app\application.py", line 152, in run
    return self._backend._vispy_run()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 279, in _vispy_run
    return app.exec_()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\app\backends\_qt.py", line 855, in _vispy_timeout
    self._vispy_timer._timeout()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\app\timer.py", line 163, in _timeout
    self.events.timeout(
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\util\event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "viz_gui.py", line 132, in update
    canvas.colorbar.draw()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\scene\visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\visuals\visual.py", line 595, in draw
    v.draw()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\visuals\visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\visuals\shaders\program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\program.py", line 533, in draw
    canvas.context.flush_commands()
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\glir.py", line 572, in flush
    self._shared.flush(parser)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\glir.py", line 819, in parse
    self._parse(command)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\glir.py", line 787, in _parse
    ob.set_data(*args)
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\glir.py", line 1380, in set_data
    gl.check_error('periodic check')
  File "C:\Users\koester_lab\anaconda3\lib\site-packages\vispy\gloo\gl\__init__.py", line 207, in check_error
    raise err
RuntimeError: OpenGL got errors (periodic check): GL_INVALID_OPERATION
ERROR: Invoking <bound method MainWindow.update of <__main__.MainWindow object at 0x000001304DD5F790>> for Event
WARNING: Error drawing visual <vispy.visuals.colorbar._CoreColorBarVisual object at 0x000001304E096A30>
ERROR: Invoking <bound method MainWindow.update of <__main__.MainWindow object at 0x000001304DD5F790>> repeat 2
WARNING: Error drawing visual <vispy.visuals.colorbar._CoreColorBarVisual object at 0x000001304E096A30>
WARNING: Error drawing visual <vispy.visuals.colorbar._CoreColorBarVisual object at 0x000001304E096A30>
```

Any help would be much appreciated!!!

```
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


import time
import numpy as np
from vispy import app
import vispy

from PyQt5.QtWidgets import *
import vispy.app
import sys

from vispy.app import use_app
use_app('PyQt5')
from vispy import scene
from vispy import color
from vispy.color.colormap import Colormap

import h5py


import imageio
from vispy import visuals

class Canvas(scene.SceneCanvas):

    def __init__(self):
        scene.SceneCanvas.__init__(self,keys='interactive', size=(1024, 1024))

        self.unfreeze()

        self.plane_ind=0

        self.i=0

        self.load_data()

        self.view=self.central_widget.add_view()

        cm=color.get_colormap("cool").map(self.time_s_colors[:,0])

        self.image=scene.visuals.Image(self.raw_data[0,:,:],parent=self.view.scene, cmap='grays',clim=[0,255])
        self.image.set_gl_state('translucent', depth_test=False)

        colors=vispy.color.ColorArray(cm,alpha=0.8)
        Scatter2D = scene.visuals.create_visual_node(visuals.MarkersVisual)
        self.p1 = Scatter2D(parent=self.view.scene)
        self.p1.set_data(self.rois_plane[:,:2], face_color=colors, symbol='o', size=8,
            edge_width=0.5, edge_color='blue')
        print(self.min,self.max)
        colormap = color.get_colormap("cool")
        self.colorbar=scene.visuals.ColorBar(clim=(self.min,self.max),cmap=colormap,orientation='left',size=(500,100),label_str='dF/F')

        self.colorbar.label.font_size = 15

        #self.time=0

        #self.time_text=scene.visuals.Text(str(time),color='white',pos=(100,0),bold=True)




    def create_cell_image(self):
        self.cell_act=np.zeros((1024,1024))
        self.cell_act[self.rois_plane[:,0],self.rois_plane[:,1]]=1
        self.cell_act=np.rot90(self.cell_act,3)

    def load_data(self):
        filename='C:/Users/koester_lab/Documents/Maria/registered/fish17_6dpf_medium_aligned_andreas.h5'
        filename='Y:/Maria/Registered/fish2_6dpf_medium_aligned_andreas.h5 '
        with h5py.File(filename, "r") as f:
            # List all groups
            print("Loading raw data from a plane...")
            start=time.time()
            self.raw_data=f['data'][:,self.plane_ind,:,:].astype('float32')
            end=time.time()
            print('Time to load raw data file: ',end-start)
        for j in range(0,self.raw_data.shape[0]):
            self.raw_data[j,:,:] *= 400.0/(self.raw_data[j,:,:].max()+0.00001)

        #self.time_s=np.load('C:/Users/koester_lab/Documents/Maria/segmented/fish2_6dpf_medium_masked_traces.npy')
        #self.pos=np.load('C:/Users/koester_lab/Documents/Maria/segmented/fish2_6dpf_medium_masked_rois.npy')
        times_file='Y:/Maria/segmented/fish2_6dpf_medium_masked_traces.npy '
        pos_file='Y:/Maria/segmented/fish2_6dpf_medium_masked_rois.npy'
        self.pos=np.load(pos_file)
        self.time_s=np.load(times_file)
        #self.time_s=np.load('Y:/Maria/segmented/fish2_6dpf_medium_detrended_traces.npy')
        #self.pos=np.load('Y:/Maria/segmented/fish2_6dpf_medium_detrended_rois.npy')
        single_plane=self.pos[:,2]==self.plane_ind
        self.rois_plane=self.pos[single_plane]
        self.time_s=self.time_s[single_plane]
        self.time_s_colors=self.time_s/800
        self.min=np.min(self.time_s)
        self.max=np.max(self.time_s)

    #def on_draw(self,event):
        #self.image.draw()
        #self.p1.draw()
        #self.colorbar.draw()


class MainWindow(QMainWindow):
    def __init__(self, canvas=None,parent=None):
        super(MainWindow, self).__init__(parent)
        self.canvas=canvas
        widget = QWidget()
        self.setCentralWidget(widget)
        self.l0 = QGridLayout()
        self.l0.addWidget(canvas.native)
        self.pl_ind_box=QLineEdit()
        self.pl_ind_box.setText("0")
        self.pl_ind_box.setFixedWidth(35)
        self.l0.addWidget(self.pl_ind_box, 0, 4, 1, 2)
        self.pl_ind_box.returnPressed.connect(lambda: self.change_plane_ind())
        widget.setLayout(self.l0)

        self.timer_init()

    def timer_init(self):
        self.timer = vispy.app.Timer()
        self.timer.connect(self.update)
        self.timer.start(0)
        self.timer.interval=0.1

    def update(self,ev):
        cm=color.get_colormap("cool").map(canvas.time_s_colors[:,canvas.i])
        colors=vispy.color.ColorArray(cm,alpha=0.8)
        canvas.p1.set_data(canvas.rois_plane[:,:2], face_color=colors, symbol='o', size=8,
            edge_width=0.5, edge_color='blue')
        canvas.image.set_data(canvas.raw_data[canvas.i,:,:])
        canvas.colorbar.draw()
        #canvas.time+=0.3
        #canvas.colorbar.draw()
        #canvas.draw()
        canvas.update()
        #print(canvas.raw_data[canvas.i,:,:])
        print(canvas.i)
        canvas.i+=1
        if canvas.i>=canvas.raw_data.shape[0]:
            canvas.i=0

    def change_plane_ind(self):
        canvas.plane_ind=int(self.pl_ind_box.text())
        canvas.load_data()
        self.timer_init()

canvas = Canvas()
vispy.use('PyQt5')
w = MainWindow(canvas)
w.show()
vispy.app.run()
#vispy.app.processEvents(
```

**Comment by djhoese** [comment]
Doesn't seem like you ever set the `parent` for the Colorbar (see your other Visuals that are working): `parent=self.view.scene`. Let me know if that helps.

**Comment by mariakesa** [comment]
Thanks so much for your help!!!

The colorbar is still not showing. When I do a .draw inside the timer update it shows a screen filled with colorful rectangles. When I do a .draw inside the canvas class after object initialization the screen is just blank. Here's the current code.

Thanks again!

`from PyQt5.QtWidgets import QApplication, QMainWindow
import sys
from PyQt5 import QtCore, QtGui, QtWidgets


import time
import numpy as np
from vispy import app
import vispy

from PyQt5.QtWidgets import *
import vispy.app
import sys

from vispy.app import use_app
use_app('PyQt5')
from vispy import scene
from vispy import color
from vispy.color.colormap import Colormap

import h5py


import imageio
from vispy import visuals

class Canvas(scene.SceneCanvas):

    def __init__(self):
        scene.SceneCanvas.__init__(self,keys='interactive', size=(1024, 1024))

        self.unfreeze()

        self.plane_ind=0

        self.i=0

        self.load_data()

        self.view=self.central_widget.add_view()

        cm=color.get_colormap("cool").map(self.time_s_colors[:,0])

        self.image=scene.visuals.Image(self.raw_data[0,:,:],parent=self.view.scene, cmap='grays',clim=[0,255])
        self.image.set_gl_state('translucent', depth_test=False)

        colors=vispy.color.ColorArray(cm,alpha=0.8)
        Scatter2D = scene.visuals.create_visual_node(visuals.MarkersVisual)
        self.p1 = Scatter2D(parent=self.view.scene)
        self.p1.set_data(self.rois_plane[:,:2], face_color=colors, symbol='o', size=8,
            edge_width=0.5, edge_color='blue')
        print(self.min,self.max)
        colormap = color.get_colormap("cool")
        self.colorbar=scene.visuals.ColorBar(clim=(self.min,self.max),cmap=colormap,orientation='left',size=(50,10),label_str='dF/F',parent=self.view.scene)

        self.colorbar.label.font_size = 10
        #self.colorbar.draw()
        #self.time=0

        #self.time_text=scene.visuals.Text(str(time),color='white',pos=(100,0),bold=True)




    def create_cell_image(self):
        self.cell_act=np.zeros((1024,1024))
        self.cell_act[self.rois_plane[:,0],self.rois_plane[:,1]]=1
        self.cell_act=np.rot90(self.cell_act,3)

    def load_data(self):
        filename='C:/Users/koester_lab/Documents/Maria/registered/fish17_6dpf_medium_aligned_andreas.h5'
        filename='Y:/Maria/Registered/fish2_6dpf_medium_aligned_andreas.h5 '
        with h5py.File(filename, "r") as f:
            # List all groups
            print("Loading raw data from a plane...")
            start=time.time()
            self.raw_data=f['data'][:,self.plane_ind,:,:].astype('float32')
            end=time.time()
            print('Time to load raw data file: ',end-start)
        for j in range(0,self.raw_data.shape[0]):
            self.raw_data[j,:,:] *= 400.0/(self.raw_data[j,:,:].max()+0.00001)

        #self.time_s=np.load('C:/Users/koester_lab/Documents/Maria/segmented/fish2_6dpf_medium_masked_traces.npy')
        #self.pos=np.load('C:/Users/koester_lab/Documents/Maria/segmented/fish2_6dpf_medium_masked_rois.npy')
        times_file='Y:/Maria/segmented/fish2_6dpf_medium_masked_traces.npy '
        pos_file='Y:/Maria/segmented/fish2_6dpf_medium_masked_rois.npy'
        self.pos=np.load(pos_file)
        self.time_s=np.load(times_file)
        #self.time_s=np.load('Y:/Maria/segmented/fish2_6dpf_medium_detrended_traces.npy')
        #self.pos=np.load('Y:/Maria/segmented/fish2_6dpf_medium_detrended_rois.npy')
        single_plane=self.pos[:,2]==self.plane_ind
        self.rois_plane=self.pos[single_plane]
        self.time_s=self.time_s[single_plane]
        self.time_s_colors=self.time_s/800
        self.min=np.min(self.time_s)
        self.max=np.max(self.time_s)

    #def on_draw(self,event):
        #self.image.draw()
        #self.p1.draw()
        #self.colorbar.draw()


class MainWindow(QMainWindow):
    def __init__(self, canvas=None,parent=None):
        super(MainWindow, self).__init__(parent)
        self.canvas=canvas
        widget = QWidget()
        self.setCentralWidget(widget)
        self.l0 = QGridLayout()
        self.l0.addWidget(canvas.native)
        self.pl_ind_box=QLineEdit()
        self.pl_ind_box.setText("0")
        self.pl_ind_box.setFixedWidth(35)
        self.l0.addWidget(self.pl_ind_box, 0, 4, 1, 2)
        self.pl_ind_box.returnPressed.connect(lambda: self.change_plane_ind())
        widget.setLayout(self.l0)

        self.timer_init()

    def timer_init(self):
        self.timer = vispy.app.Timer()
        self.timer.connect(self.update)
        self.timer.start(0)
        self.timer.interval=0.1

    def update(self,ev):
        cm=color.get_colormap("cool").map(canvas.time_s_colors[:,canvas.i])
        colors=vispy.color.ColorArray(cm,alpha=0.8)
        canvas.p1.set_data(canvas.rois_plane[:,:2], face_color=colors, symbol='o', size=8,
            edge_width=0.5, edge_color='blue')
        canvas.image.set_data(canvas.raw_data[canvas.i,:,:])
        #canvas.colorbar.draw()
        #canvas.time+=0.3
        #canvas.colorbar.draw()
        #canvas.draw()
        canvas.update()
        #print(canvas.raw_data[canvas.i,:,:])
        print(canvas.i)
        canvas.i+=1
        if canvas.i>=canvas.raw_data.shape[0]:
            canvas.i=0

    def change_plane_ind(self):
        canvas.plane_ind=int(self.pl_ind_box.text())
        canvas.load_data()
        self.timer_init()

canvas = Canvas()
vispy.use('PyQt5')
w = MainWindow(canvas)
w.show()
vispy.app.run()
#vispy.app.processEvents(
`

**Comment by djhoese** [comment]
Note the **uncommented** code in your `update` method on your window. It is calling `canvas.update()`. That is the correct way to do this. You should never really need to call `canvas.draw()` or any draw method directly. This is handled for your by `canvas.update()`. This is true with the `SceneCanvas` but not the regular `Canvas` class so keep that in mind. Calling `.update()` on any individual Visual will trigger the drawing of the entire SceneCanvas which is expected (just wanted to mention it since it looks like you are trying to only draw specific components).

Lastly, you'll need three backticks on their own lines before and after a code clock in a GitHub comment to make it treat it as one big code block. I edited your original post this way so it shows up correctly.

**Comment by mariakesa** [comment]
Thanks a bunch also for insightful explanations! There's not a lot of tutorials on vispy around so I just google and try stuff:-D Should write a blog post:-)

It works! I think before I just didn't see it. I changed pos and it works!

**Comment by djhoese** [comment]
Well there is the entire directory of examples in the repository...but I am also rewriting the entire documentation website:

https://github.com/vispy/vispy-website/pull/29

And planning a series of tutorial videos.

**Comment by djhoese** [comment]
If you'd like to write a blog post about how to do what you're doing, I wouldn't be opposed :wink:

So since this works, can this be closed?

**Comment by mariakesa** [comment]
That's cool, thanks! 

It's a great library:-) I read the original paper on it's structure, but it's still a bit difficult to decipher. Practice makes perfect! Thanks for your help! I'll write a blog post, unfortunately can't share the data since it's 200 GB, but I can post some gifs! Here's what it looks like without the colorbar (since I had to finish it fast for a presentation:-D)
[https://github.com/mariakesa/ZebraFishRegistrationPipeline/blob/master/mask_segmented.gif](url)


Sure, you can close it:-)
