### ISSUE TITLE
Support for updating part of a 3D texture / volume

### ISSUE THREAD

**Issue by VolkerH** [vispy/vispy#1951]
Would it possible to add a function to the API that allows updating part of an existing `vispy.Visuals.Volume` with new data?

The volumes are stored as 3D textures and it seems it should be possible to update part of a 3D texture using thre OpenGL function `glTexSubImage3D(...)`.

Possible use case:

Live 3D-visualization of volume acquisition on Z-scanning microscopes. Some people are already working on (@zeroth, @jni) or already using (@AndrewGYork) napari for live visualization of microscopy data during acquisition. In many microscopes volume acquisition is based on scanning through the sample and taking a 2D image and taking a slice image. The final volume is given by the collection of slices. Currently, one needs to wait until the complete volume is collected before passing it as a 3D texture for volume rendering. For large volumes, passing the whole volume into texture buffer also takes some time.

Typically the size of the volume is known a priori (camera x and y dimensions * number of z steps), so one can allocate a suitably sized texture buffer. It would be nice if it were possible to update single slices of this texture buffer on the GPU with new data as it comes in from the camera. This should enable live volume viewing while the volume is still being captured.

**Comment by djhoese** [comment]
I have no issue with this and the ImageVisual could use this too. This would have to be done on top of the work in #1912 and #1920 . I actually think the lower level texture objects already use "SubImage" functions to upload data.

I don't know much about the low-level behaviors of the volume visual, but is there any chance that the shader requires most/all of the data or data from nearby pixels to properly render things? Have you tried uploading an "empty" 3D texture with only a portion of the array filled in? Does it look good with no artifacts? Lastly, thinking about dask here, what is someone provided slices of the volume along a specific axis (dask chunking). Would there be a requirement to have it done in a certain way? For example, cubes of data can be rendered and uploaded one at a time, but 2D slices would fail or look bad in some ways. Just some concerns that I'd like to bring up now.

**Comment by VolkerH** [comment]
Thanks for your quick reply. No, I have not tried anything yet. I've had the idea for a while but I only started looking into whether it is possible to implement today. Will try whether I can get some minimal example. Thanks for pointing out those related open PRs, too.

**Comment by VolkerH** [comment]
After playing around some more it seems that this is already possible using the texture `set_data` method with the `offset` parameter.
I managed to create a mock-up of what I'm envisaging to happen during the acquisition by inserting the following lines into `examples/basic/scene/volume.py`. This was a quick and dirty hack, need to clean this up a bit ...

```
highlighted = np.clip(vol2+100, 0, 255)
volume1._tex.set_data(vol2, copy=True)
i = 0
def highlight_slice(x):  
    global i
    volume1._tex.set_data(highlighted[i:i+2], offset=(i, 0, 0), copy=True)
    
    if i>1:
        volume1._tex.set_data(vol2[i-2:i,...], offset=(i-2, 0, 0), copy=True)
    i = i + 2
    if i>vol2.shape[0]-1:
        i = 0
        volume1._tex.set_data(vol2, copy=True)
    view.update()

canvas.unfreeze()
canvas._timer = app.Timer(0.016, connect=highlight_slice, start=True)
```
This is what it looks like:

![live_slice](https://user-images.githubusercontent.com/2210044/98905387-73a71900-250f-11eb-9af2-e84a0c811f8e.gif)

**Comment by kmuehlbauer** [comment]
@VolkerH Looking at your last comment (nice demo btw), it seems the issue is resolved. Is there anything  more to discuss? If not we might close the issue.

**Comment by VolkerH** [comment]
Hi @kmuehlbauer, I had lost track of this.

In principle I answered my own question, as it is possible to update part of a texture with `set_data` and providing an offset.

From memory, I noticed some peculiar behaviour (potentially a bug), that might be worth its own issue.  It was not possible to update just a single z-slice of the texture. I had to update at least two slices of the texture buffer. This is why the code snippet above looks unneccarily complicated and the plane that is moving through the volume in the animated gif is really a 2-voxel thick plane. 
Not sure whether someone has bandwidth to follow up on that (I currently don't) and whether that's something to track in this issue (potentially renamed) or in a separate, new one.

**Comment by djhoese** [comment]
Not sure on the 2 voxel thing. Maybe we close this and if it bugs someone enough they can make a new issue. Also note that @brisvag and @alisterburt added Volume plane rendering in some of the recent releases of vispy. Might be something to look at to simplify your code if you're still using it.

**Comment by VolkerH** [comment]
Hi @djhoese,

For context:
This was not initially intended for volume plane rendering, the intention was to continuously update a 3D volume in the texture buffer with new data coming in from a camera: https://github.com/napari/napari/pull/1979  .The volume plane highlighting in this case was just a byproduct  to show where the volume data was last updated. 

I am not using any of this at the moment and the initial question is solved, so will close.
