### ISSUE TITLE
Question: using #include statements in Function code 

### ISSUE THREAD

**Issue by clarebcook** [vispy/vispy#1953]
Hello,
I have been using vispy ImageVisuals, and I am now trying to make a modified version that approaches interpolation in a different way. I am trying to follow the method used in the original vispy ImageVisual class, of using vispy/visuals/shaders/Function to build a function from a template code (original included below), and then use that function in the frag. My issue is, my template includes an include statement (as in the original class), and I cannot figure out how to tell the compiler where to look for my included file. Would you be able to explain how this is accomplished?

```
_interpolation_template = """
    #include "misc/spatial-filters.frag"
    vec4 texture_lookup_filtered(vec2 texcoord) {
        if(texcoord.x < 0.0 || texcoord.x > 1.0 ||
        texcoord.y < 0.0 || texcoord.y > 1.0) {
            discard;
        }
        return %s($texture, $shape, texcoord);
    }"""
```

Thank you!

**Comment by djhoese** [comment]
Side note: I edited your post and fixed the formatting of your code by using three backticks on their own lines.

Is the above code the code you are trying to make work or is this the code that is in the visual right now?

**Comment by clarebcook** [comment]
That's the code in the visual right now. I'm doing essentially the same thing, but replacing 'misc/spatial-filters.frag' with my own file.

**Comment by djhoese** [comment]
From my understanding, the search paths are used here:

https://github.com/vispy/vispy/blob/74d9461d716e7b6761e14d22979a82efc7edf9d6/vispy/glsl/__init__.py#L12-L34
The keys/config defined here:

https://github.com/vispy/vispy/blob/74d9461d716e7b6761e14d22979a82efc7edf9d6/vispy/util/config.py#L51-L80

And the user config is:

https://github.com/vispy/vispy/blob/74d9461d716e7b6761e14d22979a82efc7edf9d6/vispy/util/config.py#L314-L321

So it would seem if you create a `.vispy/vispy.json` with:

```
{
    'include_path': ['/your/custom/path'],
}
```

That it might work?

**Comment by clarebcook** [comment]
Thank you! I will give that a try.
