### ISSUE TITLE
GUI control toolbar

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#196]
The idea is to provide a basic GUI for easily controlling Python variables in real-time. Controls include sliders, check boxes, radio buttons.

Similar to:
- [dat.GUI](http://workshop.chromeexperiments.com/examples/gui/#1--Basic-Usage) (Javascript)
- [AntTweakBar](http://anttweakbar.sourceforge.net/doc/) (C++)

![dat.GUI](http://creativejs.com/wp-content/uploads/2011/08/dat-gui_main.jpg)

**Comment by kmuehlbauer** [comment]
> All in all, we may not need to reinvent the wheel with OpenGL-based GUI controls.

Seems we can close this.
