### ISSUE TITLE
Integrate VISPY into WX

### ISSUE THREAD

**Issue by gkft** [vispy/vispy#1965]
Hi everyone,

I am struggling to get the bellow code (MWE) working.

Expected behavior: python quits after closing all windows

Observed behavior: python keeps running

Has anybody a clue why python does not quit?

Kind regards

```
#!/usr/bin/env python
import wx
from vispy import scene


class Canvas(scene.SceneCanvas):
    def __init__(self, *args, **kwargs):
        scene.SceneCanvas.__init__(self, *args, **kwargs,)


class VispyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, "Vispy Frame", wx.DefaultPosition, size=(500, 500))

        self.Bind(wx.EVT_CLOSE, self.on_close)
        self.Bind(wx.EVT_SHOW, self.on_show)

        self.canvas = Canvas(app="wx", parent=self)

    def on_close(self, event):
        print("close")
        self.canvas.app.quit()
        self.canvas.close()
        self.Destroy()

    def on_show(self, event):
        print("show")
        self.canvas.show()


class MainFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, "WX Frame")
        self.panel = wx.Panel(self, -1)
        button = wx.Button(self.panel, label="VISPY")
        self.Bind(wx.EVT_BUTTON, self.newwindow, button)

    def newwindow(self, event):
        secondWindow = VispyFrame(parent=self.panel)
        secondWindow.Show()


app = wx.App(False)
frame = MainFrame()
frame.Show(True)
app.MainLoop()
```

**Comment by djhoese** [comment]
I don't currently have a Wx environment on my system, but maybe you could provide more detail. What exactly isn't working? Do you mean when you close the window (with the 'x' in the GUI window) that it doesn't close?

One thing you could try is using vispy's application that typically wraps the backend's application (in this case `App`) object. So at the bottom you would do:

```
app = vispy.use('wx')
frame = MainFrame()
frame.Show(True)
app.run()
```

The other thing, is you shouldn't need to do any of the stuff you have in your `on_close` method as far as vispy is concerned (no app.quit, no .close). That should be handled automatically (at least it usually is) when you close the window. This all assumes that you've added the Canvas to your GUI Frame/Widget properly. I'm used to using vispy with pyqt GUIs where you typically add the Canvas by adding `self.canvas.native` to the GUI's layout or something similar. That said, you may have that right. Have you looked at the `wx` example:

https://github.com/vispy/vispy/blob/master/examples/tutorial/app/simple_wx.py

**Comment by djhoese** [comment]
Actually, I see the example does the same thing you did regarding `App` so maybe that isn't the problem. I would remove the canvas stuff from your `on_close` and see if that helps. Otherwise, more detail on what isn't working would be the next step.

**Comment by gkft** [comment]
Hi David,
If I remove all lines despite the print statement from ```on_close```` the behavior gets even worse the canvas window is opened every time I click the 'x' in the GUI.

As this is only intended to be a MWE my actual code does more and the canvas is more complex, but the buggy behavior after clicking first on the VISPY button and then on the 'x' in the GUI of the canvas and then the 'x' on the main window some process or task is still running and python does not quit as expected.


What I also noticed is the following, after clicking the VISPY button and then closing the canvas window the following happens,
as you can the on show function is called once again,
```
show
close
show
Traceback (most recent call last):
  File "/data/bar.py", line 28, in on_show
    self.canvas.show()
  File "/data/lib/python3.9/site-packages/vispy/app/canvas.py", line 429, in show
    self._backend._vispy_set_visible(visible)
  File "/data/lib/python3.9/site-packages/vispy/app/backends/_wx.py", line 354, in _vispy_set_visible
    self.Show(visible)
RuntimeError: wrapped C/C++ object of type CanvasBackend has been deleted
```

**Comment by djhoese** [comment]
Oh! I didn't even realize you were using a button to open the canvas. I thought the Canvas was embedded in your main GUI window. What if you keep the `.show()` in the `on_close`, but remove the `app.quit()` and probably the Destory(). Based on the examples I've seen you should call `.Close()`. `.Destroy()` sounds much more...destructive. The `app` the Canvas is using is meant to be the main Wx GUI event loop `App` so it probably shouldn't be quit by you (I assume Wx kills its own event loop when the last window has been closed).

**Comment by gkft** [comment]
Yes the canvas is created after a click on the button.

* If i remove ```self.canvas.app.quit()``` from ```on_quit``` the behavior is still the same.
* If i remove ```self.Destroy()``` from ```on_quit``` the canvas disappears on the first click on 'x' and then a blank window opens up which cannot be closed by clicking on 'x'

That is correct wx kill its own event loop after the last window is closed.
Any alternative how to embedded a canvas into a wx window which can be used to plot data and gets closed afterwards?
What else I still don't get why is the ```on_show``` function called again.

**Comment by djhoese** [comment]
What if you replace the `Canvas` with a regular/empty frame or panel or whatever Wx calls them?

Did you remove both app.quit() and Destory at the same time (that's what I was expecting)? When you say " the canvas disappears on the first click on 'x' and then a blank window opens up", do you mean when you click the "VISPY" button again or does the new blank window open immediately?

Although I'm not sure this matters, it does seem dangerous that you create `secondWindow` but don't assign it to `self.secondWindow`. I'd be worried that it would get garbage collected early if Wx doesn't hold onto it properly.

**Comment by gkft** [comment]
If I modify the MWE accordingly, everything is working as expected clicking the button opens a new window which can be destroyed by a click on the 'x' GUI element, the main window as well.
As soon as I integrate the canvas the buggy behavior occurs.

```
#!/usr/bin/env python
import wx
from vispy import scene


class Canvas(scene.SceneCanvas):
    def __init__(self, *args, **kwargs):
        scene.SceneCanvas.__init__(self, *args, **kwargs,)


class VispyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, "Vispy Frame", wx.DefaultPosition, size=(500, 500))

        self.Bind(wx.EVT_CLOSE, self.on_close)
        self.Bind(wx.EVT_SHOW, self.on_show)

        # self.canvas = Canvas(app="wx", parent=self)

    def on_close(self, event):
        print("close")
        # self.canvas.app.quit()
        # self.canvas.close()
        self.Destroy()

    def on_show(self, event):
        print("show")
        # self.canvas.show()


class MainFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, "WX Frame")
        self.panel = wx.Panel(self, -1)
        button = wx.Button(self.panel, label="VISPY")
        self.Bind(wx.EVT_BUTTON, self.newwindow, button)

    def newwindow(self, event):
        self.secondWindow = VispyFrame(parent=self.panel)
        self.secondWindow.Show()


app = wx.App(False)
frame = MainFrame()
frame.Show(True)
app.MainLoop()

```

**Comment by djhoese** [comment]
:thinking: Wow this is a tough one. I installed Wx and tried a few things. I think the recursion issue was because you needed an `event.Skip()`. Anyway, I've tried a few things including replacing the VispyFrame with a SceneCanvas directly and I get the same issue. Something is sticking around and not letting the MainLoop exit. I'm wondering if this was either:

1. Never tried when the Wx backend was created.
2. Something changing in newer versions of Wx that is making VisPy's Canvas creation not work.

Here is the code for how VisPy handles the parent being passed to the backend:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/app/backends/_wx.py#L233-L259

Just below that is where the GLCanvas is actually made:

https://github.com/vispy/vispy/blob/7f3f6f60c8462bb8a3a8fa03344a2e6990b86eb2/vispy/app/backends/_wx.py#L261-L263

I'll see if I can figure something out. I have one idea...

**Comment by djhoese** [comment]
Nope, my idea was already being covered by your `self.canvas.close()`. I am out of ideas I think. Any idea if there is a way to "ask" Wx what is still alive and why it won't close the MainLoop?

**Comment by gkft** [comment]
I have tried already quite a lot of things even weird things like having a look at all running threads with ```threading.enumerate()``` but without getting a clue why python keeps running.

**Comment by djhoese** [comment]
This worked for me:

```
import wx
from wx import glcanvas
from wx.glcanvas import GLCanvas
import vispy
from vispy import scene


class Canvas(scene.SceneCanvas):
    def __init__(self, *args, **kwargs):
        scene.SceneCanvas.__init__(self, *args, **kwargs,)


class VispyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, "Vispy Frame", wx.DefaultPosition, size=(500, 500))

        self.Bind(wx.EVT_CLOSE, self.on_close)
        #self.Bind(wx.EVT_SHOW, self.on_show)

        self.canvas = Canvas(parent=self)
        self.canvas.show()

    def on_close(self, event):
        print("close")
        self.canvas.close()
        self.Destroy()
        event.Skip()

    def on_show(self, event):
        print("show")
        self.canvas.show()
        event.Skip()


class MainFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, "WX Frame")
        self.panel = wx.Panel(self, -1)
        button = wx.Button(self.panel, label="VISPY")
        self.Bind(wx.EVT_BUTTON, self.newwindow, button)

    def newwindow(self, event):
        self.secondWindow = VispyFrame(parent=self.panel)
        self.secondWindow.Show()


vapp = vispy.app.use_app('wx')
wapp = vapp.create()
frame = MainFrame()
frame.Show(True)
vapp.run()
```

I think the key is how I create the app. When I try doing the `show` with the event, something weird is happening. It seems like closing the vispy frame causes the show event to be triggered again. Maybe the show event happens for opening and closing :man_shrugging:

**Comment by gkft** [comment]
Ok I can confirm the program quits as expected :+1: 

But still my problem remains in my codebase the initialization looks like below, any clue how to get from my init code to the working one?

```
#!/usr/bin/env python

import wx
import vispy
from vispy import scene


class Canvas(scene.SceneCanvas):
    def __init__(self, *args, **kwargs):
        scene.SceneCanvas.__init__(self, *args, **kwargs,)


class VispyFrame(wx.Frame):
    def __init__(self, parent):
        wx.Frame.__init__(self, parent, -1, "Vispy Frame", wx.DefaultPosition, size=(500, 500))

        self.Bind(wx.EVT_CLOSE, self.on_close)

        self.canvas = Canvas(parent=self)
        self.canvas.show()

    def on_close(self, event):
        print("close")
        self.canvas.close()
        self.Destroy()
        event.Skip()


class MainFrame(wx.Frame):

    def __init__(self):
        wx.Frame.__init__(self, None, -1, "WX Frame")
        self.panel = wx.Panel(self, -1)
        button = wx.Button(self.panel, label="VISPY")
        self.Bind(wx.EVT_BUTTON, self.newwindow, button)

    def newwindow(self, event):
        self.secondWindow = VispyFrame(parent=self.panel)
        self.secondWindow.Show()


class MyApp(wx.App):
    pass

# working as expected
# vapp = vispy.app.use_app('wx')
# vapp.create()
# frame = MainFrame()
# frame.Show(True)
# vapp.run()


# does not quit
app = MyApp(False)
frame = MainFrame()
frame.Show(True)
app.MainLoop()
```

**Comment by djhoese** [comment]
You really need to create your own App? Accessing `wapp` from my example isn't enough?

You could try:

```
app = MyApp(False)
vapp = vispy.app.use_app('wx')
frame = MainFrame()
frame.Show(True)
vapp.run()
```

Assuming `MyApp` properly registers itself with Wx, then VisPy should realize the app was already created and reuse it.

**Comment by djhoese** [comment]
We need:

https://github.com/vispy/vispy/blob/master/vispy/app/backends/_wx.py#L159

To return your app. Otherwise, you need to reuse the App that vispy creates.

**Comment by djhoese** [comment]
```
app = wx.App(False)
vapp = vispy.app.use_app('wx')
vapp.create()
frame = MainFrame()
frame.Show(True)
vapp.run()
```

Ok that works for me.

Interestingly, if you don't do the `.create()` it doesn't "register" the wx App with the `_wx.py` vispy backend and then `.run()` will fail. I think you could also do `app.MainLoop()` but to be safe I would say when using vispy in an application you should always run the GUI event loop from vispy's app object.

**Comment by gkft** [comment]
I can confirm the example is working as expected now, thank you! 
I still have to fix my code there the where the same problem remains.
