### ISSUE TITLE
Add Support for PySide6

### ISSUE THREAD

**Issue by Tai-Zhou** [vispy/vispy#1971]
[PySide6](https://pypi.org/project/PySide6/) is released, maybe it can be added to the backend list.

**Comment by djhoese** [comment]
From the small amount that I've read, my understanding was PySide5 -> Pyside6 is meant to be an easy transition. Any idea if this applies to the OpenGL interfaces?

I see no reason not to add it, but it probably won't be driven by me. My usual response to things like this...

Pull requests are welcome!

**Comment by Kusefiru** [comment]
I would like to give it a try, if you are okay with it.

**Comment by djhoese** [comment]
@Kusefiru Go for it. I'm not going to turn down help :grin:

**Comment by Kusefiru** [comment]
Just a quick question, the name of the global variable `QT5_NEW_API` may not make much sense anymore since this also applies to Qt6.

Is it okay to rename it simply `QT_NEW_API` or is there a risk of breaking someone work ?

**Comment by djhoese** [comment]
You should be ok renaming it, but double (triple?) check that the APIs are the same. Or create 2 new variables for a total of:

1. `QT5_NEW_API`
2. `QT6_NEW_API`
3. `QT5P_NEW_API` for "5 plus", meaning this API is in QT5 and 6. Or maybe `QT56_NEW_API` but that seems like it is easy to miss. Or `QT5_AND_6_NEW_API`. Or...just do `if QT5_NEW_API or QT6_NEW_API:` every time the current QT5 global is checked.

**Comment by Kusefiru** [comment]
Okay, I'll use the last solution.

**Comment by Kusefiru** [comment]
You may close this issue as well now ?
