### ISSUE TITLE
Load .obj file with .mtl texture

### ISSUE THREAD

**Issue by nhanminhnhat1998** [vispy/vispy#1984]
Hello everyone,

This is the first time I use your library, it is very cool. I am trying to load my object with the texture but I have not found a good way to do so. Is there any suggestion?

Thanks a lot

**Comment by djhoese** [comment]
Support for textures with meshes has been improved recently and has not yet been released. You can see an example of how it can work with the master branch here: https://github.com/vispy/vispy/blob/master/examples/basics/scene/mesh_texture.py

Let me know if you have any other questions.

**Comment by nhanminhnhat1998** [comment]
That is good news, thank you.

I have tried that example, but my object is big so it has many images for its texture.

**Comment by djhoese** [comment]
Normally (I have very little experience with meshes + textures) but I think the various images are meant to be combined into one image so you can match the mesh vertices with the texture vertices. How many images make up your overall texture? What is your mesh representing?

**Comment by nhanminhnhat1998** [comment]
I have 18 images

the mesh I am trying to visualize is a 3D map in .obj file that I collected from the drone data.

here is the top part of the file 
`mtllib scene_mesh_textured.mtl
v -152.770493 192.972397 -84.893692
v 75.944252 252.182312 -100.503838
v -115.695763 180.321640 -85.367615
v -115.443764 251.681702 -91.971916
v -115.618195 252.061646 -92.264374
v -47.750298 169.887497 -89.397682
v -28.871189 174.117737 -91.535065
v -203.119766 188.252045 -77.185425
v -48.761639 206.926376 -94.243355`

here is the scene_mesh_textured.mtl file

[scene_mesh_textured.txt](https://github.com/vispy/vispy/files/5978822/scene_mesh_textured.txt)


here is my attempt:
![image](https://user-images.githubusercontent.com/21211975/107893274-5191bc80-6f7e-11eb-81c7-2e4e7e958e1c.png)


Thank you for your time

**Comment by djhoese** [comment]
This is way beyond my knowledge. @asnt has been doing a lot of the recent mesh work in VisPy. Maybe they have an idea?

**Comment by asnt** [comment]
@nhanminhnhat1998 @djhoese The current [TextureFilter](https://github.com/vispy/vispy/blob/c4f7ef42988dd9312ef7e7a03f4f10347a8e4b07/vispy/visuals/filters/mesh.py#L10) does not support multiple materials. It assumes a single texture mapping (i.e. material) for the whole mesh. One solution around this, using the current TextureFilter as is, would be to split the mesh into submeshes with a single material per submesh.

**Comment by asnt** [comment]
@nhanminhnhat1998 Would it be possible to share all the files, or at least the entire `.obj` to check how the different materials are referenced?

**Comment by nhanminhnhat1998** [comment]
@asnt yeah sure, thank for you help

the whole folder is more than 100MB, so here is the link to my drive: https://1drv.ms/u/s!AsU8YxCc03399xM6RPe_9KGqcij9?e=CvAXdq

**Comment by nhanminhnhat1998** [comment]
```
import numpy as np

from vispy.scene.visuals import Mesh
from vispy.visuals.filters import TextureFilter
from vispy import app, scene
import trimesh


def attach_headlight(mesh, view, canvas):
    light_dir = (0, -1, 0, 0)
    mesh.light_dir = light_dir[:3]
    initial_light_dir = view.camera.transform.imap(light_dir)

    @view.scene.transform.changed.connect
    def on_transform_change(event):
        transform = view.camera.transform
        mesh.light_dir = transform.map(initial_light_dir)[:3]

# Creating the canvas 1st
canvas = scene.SceneCanvas(keys='interactive', bgcolor='white',
                           size=(800, 600))
view = canvas.central_widget.add_view()


# trimesh.util.attach_to_log()
file_name = './3D_model/scene_mesh_textured.obj'
# m = trimesh.load(file_name)
resolver_path="./3D_model/scene_mesh_textured.mtl"
resolver = trimesh.visual.resolvers.FilePathResolver(resolver_path)

## config viwe
canvas = scene.SceneCanvas(keys='interactive', bgcolor='black',
                           size=(800, 800))
view = canvas.central_widget.add_view()


view.camera = 'turntable'
# view.camera.depth_value = 10 * (vertices.max() - vertices.min())



with open(file_name, 'r') as f:
    # kwargs = trimesh.exchange.obj.load_obj(f)
    kwargs = trimesh.exchange.obj.load_obj(f, resolver=resolver)
# print(len(kwargs["geometry"]))
# print(len(kwargs["graph"]))

for graph in kwargs["graph"]:
    
    geometry_key=graph["geometry"]
    geometry=kwargs["geometry"].get(geometry_key)
    visual=geometry.get("visual")
    # print(kwargs["geometry"].get(geometry_key))
    # print(len(visual.uv),visual.uv)
    img=visual.material.image
   
    faces=geometry.get("faces")
    vertices=geometry.get("vertices")
    # img.show("abc")
    texture = np.array(img)
    texcoords=visual.uv.view(np.ndarray)  
   



    shading = None 
    mesh = Mesh(vertices, faces, shading=shading,color='gray')
    mesh.shininess = 0
    view.add(mesh)
    texture_filter = TextureFilter(texture, texcoords)
    mesh.attach(texture_filter)
    attach_headlight(mesh,view,canvas)
    
    


@canvas.events.key_press.connect
def on_key_press(event):
    if event.key == "t":
        texture_filter.enabled = not texture_filter.enabled
        mesh.update()







if __name__ == "__main__":
    app.run()
```

**Comment by asnt** [comment]
Thanks @nhanminhnhat1998 

Here is a minimal example. It requires `vispy/master` for the texture filter.

```python
import argparse
import pathlib

import numpy as np
import trimesh
from trimesh.exchange.obj import load_obj
import vispy
from vispy.scene.visuals import Mesh
from vispy.visuals.filters import TextureFilter


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("obj")
    return parser.parse_args()


def load_meshes(path):
    with open(path) as mesh_file:
        data_dir = pathlib.Path(path).parent
        resolver = trimesh.visual.resolvers.FilePathResolver(data_dir)
        data = load_obj(mesh_file, resolver=resolver, process=False)

    meshes = data["geometry"]
    meshes = [
        dict(
            vertices=mesh["vertices"],
            faces=mesh["faces"],
            texcoords=mesh["visual"].uv,
            # XXX: Convert to numpy array and flip the y axis (as it is encoded
            # with opposite directions in a Image and an numpy array).
            image=np.flipud(mesh["visual"].material.image),
        )
        for mesh in meshes.values()
    ]

    return meshes


def make_scene(meshes):
    canvas = vispy.scene.SceneCanvas(keys='interactive', bgcolor='white',
                                     size=(800, 600))
    view = canvas.central_widget.add_view()
    view.camera = 'arcball'

    for mesh in meshes:
        mesh_ = Mesh(mesh["vertices"], mesh["faces"], color='white')
        mesh_.shininess = 1e-3

        texture_filter = TextureFilter(mesh["image"], mesh["texcoords"])
        mesh_.attach(texture_filter)

        view.add(mesh_)

    return canvas, view


def main():
    args = parse_args()

    print(f"loading {args.obj}")
    meshes = load_meshes(args.obj)
    print(f"loaded {len(meshes)} meshes")

    canvas, _ = make_scene(meshes)
    canvas.show()
    vispy.app.run()


if __name__ == "__main__":
    main()
```

![screenshot-multiple_uvmaps](https://user-images.githubusercontent.com/830589/108101389-6f971400-7087-11eb-8322-1ba3e1220fcd.png)

**Comment by djhoese** [comment]
@asnt Awesome! Now the mesh by itself (no textures) could be draw with a concatenation of all of the vertices and faces right? Would it be possible to concatenate all of the texcoords and image data to form one texture that could be given to TextureFilter?

**Comment by asnt** [comment]
> Now the mesh by itself (no textures) could be draw with a concatenation of all of the vertices and faces right?

Yes.

> Would it be possible to concatenate all of the texcoords and image data to form one texture that could be given to TextureFilter?

I think so. For example, with the texture images stored in a [GL_TEXTURE_2D_ARRAY](http://docs.gl/es3/glBindTexture) (sampling with `(u, v, i)` for the i-th image),  and with an additional array, indicating for each triangle the index `i` of the texture in the texture array.

**Comment by djhoese** [comment]
You could encode it in a single image couldn't you? You'd have to know "I'm appending this image in the first dimension (axis=0) so the texture coordinates need to have an offset of Y". Oh you'd actually need to collect all the images, figure out the whole image size and then scale and offset the texture coordinates. You *might* run into floating point precision issues with the texture coordinates if you have enough images though. I think this would be super simple though if each input image is the same width (or height).

**Comment by asnt** [comment]
I think that could work, too.

**Comment by djhoese** [comment]
Hhhmmm I wonder if we could make a utility function for that. I'll make an issue. @nhanminhnhat1998 if @asnt's code works for you above then please close this when you get a chance. If you need further optimization then we may need to get this utility function written.

**Comment by asnt** [comment]
@nhanminhnhat1998 See #1996 for an improved solution that should render the scene more efficiently.

**Comment by nhanminhnhat1998** [comment]
@asnt @djhoese , thanks so much for you help, have a good one
