### ISSUE TITLE
Add Roadmap to documentation

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#1987]
It is kind of hard for people to know what we expect from VisPy going forward. Releases are slow (for now :crossed_fingers:) and we only really merge what's possible with the limited maintainer time we have. Even though we don't have a lot of time for new features it would be good to make users and others aware of where we see VisPy going in the future. I plan on using this issue to not only remind me (or someone else) to add a page to the documentation for this roadmap but to link to issues about major tasks that are driving VisPy's future development. @vispy/core feel free to edit this as you think of things.

* #1985 
* #1986
* #1988 
* #1989
* #1991
* #1992

**Comment by kmuehlbauer** [comment]
@djhoese Can this be closed?
