### ISSUE TITLE
why high-light point in darkness?

### ISSUE THREAD

**Issue by yxdragon** [vispy/vispy#1998]
![image](https://user-images.githubusercontent.com/24822467/108518606-b85b0100-7303-11eb-8cfc-0f11137e2a4b.png)

[https://forum.image.sc/t/some-doubt-when-using-vispy-high-light-point-in-darkness/49107](https://forum.image.sc/t/some-doubt-when-using-vispy-high-light-point-in-darkness/49107)

**Comment by djhoese** [comment]
Could you please provide the full script you used to produce this image and maybe some system information (`python -c "import vispy; print(vispy.sys_info())"`?

**Comment by yxdragon** [comment]
@djhoese 
```python
from vispy import scene
from vispy.visuals.transforms import STTransform

canvas = scene.SceneCanvas(keys='interactive', bgcolor='white', size=(800, 600), show=True)
view = canvas.central_widget.add_view()

sphere1 = scene.visuals.Sphere(radius=1, method='ico', color=(1,1,0), shading='smooth', parent=view.scene)

cam = scene.TurntableCamera(elevation=30, azimuth=30)
view.camera = cam

if __name__ == '__main__':
    canvas.app.run()
```

vispy.sys_info:
Platform: Windows-10-10.0.21301-SP0
Python:   3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
NumPy:    1.16.2
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.15.1', '5.15.1')
pyside:   None
pyside2:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       wxPython 4.1.1
egl:      None
osmesa:   None
_test:    None

GL version:  '4.5.0 - Build 24.20.100.6299'
MAX_TEXTURE_SIZE: 16384


I think it is a bug, because even I use vispy.geometry.isosurface to generate a ball from 3d array, the high-light point is also wrong.
(But when I use skimage’s marching_cubes_lewiner, the result is right)

So it seems that, vispy’s geometry algrithsm give a wrong face index sequence? (so that count a invert normal vector)

**Comment by djhoese** [comment]
So good news (?) is I get the same result. I don't know much about how this lighting is implemented, but interestingly if I change the camera with `view.camera = 'panzoom'` it looks like the bright spot is in the right location:

![image](https://user-images.githubusercontent.com/1828519/108536798-78affd00-72a2-11eb-958b-1101f8313299.png)

**Comment by djhoese** [comment]
@asnt Any ideas on this?

**Comment by yxdragon** [comment]
I see the shader code, 
'''C
if ($shininess > 0.) {
        speculark = dot(reflect(v_light_vec, v_normal_vec), v_eye_vec);
        speculark = clamp(speculark, 0.0, 1.0);
        //raise to the material's shininess, multiply with a
        //small factor for spread
        speculark = 20.0 * pow(speculark, 1.0 / $shininess);
    }
'''
the high-light point is generated by count eye-face-light angle. So that need the normal vector.

```python
from vispy import scene
from vispy.color import Color
from vispy.visuals.transforms import STTransform

canvas = scene.SceneCanvas(keys='interactive', bgcolor='white', size=(800, 600), show=True)

view = canvas.central_widget.add_view()

import numpy as np
arr = np.zeros((256,256,256))
coord = np.array(np.where(arr>-1))
dis = ((coord-128)**2).sum(axis=0)**0.5
arr.ravel()[:] = dis

from vispy.geometry.isosurface import isosurface
vts, faces = isosurface(arr, 100)
faces = faces[:,::-1] # invert faces's sequence from ABC to CBA

mesh = scene.visuals.Mesh(vertices=vts, faces=faces, color=(1,1,0), parent=view.scene, shading='smooth')
mesh.transform = STTransform(translate=[-128,-128,-128])
mesh._ambient_light_color = Color((0.3,0.3,0.3,1))
# mesh1.picking = True

cam = scene.TurntableCamera(elevation=30, azimuth=30)
cam.set_range((-100, 100), (-100, 100), (-100, 100))
view.camera = cam

if __name__ == '__main__':
    canvas.app.run()
```

just invert the faces array's sequence, (then will invert the normal vector) the result is right. So I think it is vispy.geometry algrithsm's bug.

**Comment by yxdragon** [comment]
skimage's marching_cubes_lewiner's result is right, So I think the shader code is OK.

**Comment by djhoese** [comment]
@rougier My guess is a lot of this geometry stuff was added from glumpy originally. Any ideas or updates that you may have fixed in glumpy that need to be ported here?

@yxdragon If you can track down the bug a pull request with a fix would be greatly appreciated.

**Comment by asnt** [comment]
I also found, while preparing PR #1463, that this part of the shader mentioned by @yxdragon is producing this unexpectedly strong highlight:
> ```C
> if ($shininess > 0.) {
>     speculark = dot(reflect(v_light_vec, v_normal_vec), v_eye_vec);
>     speculark = clamp(speculark, 0.0, 1.0);
>     //raise to the material's shininess, multiply with a
>     //small factor for spread
>     speculark = 20.0 * pow(speculark, 1.0 / $shininess);
> }
> ``` 

@djhoese I have suggested a fix as part of PR #1463 to follow the standard conventions of shininess in the [Phong reflection model](https://en.wikipedia.org/wiki/Phong_reflection_model#Description). It gives more control over the highlight and visually more pleasing results. See https://github.com/vispy/vispy/pull/1463#discussion_r426243312 .

**Comment by djhoese** [comment]
Thank you! Apparently I need to finally merge that PR. I'll see what I can do next week.

**Comment by yxdragon** [comment]
@djhoese another question, is there a mesh's face_color demo? I pass a (face_n, 3) float32 array, but got a error.

**Comment by djhoese** [comment]
Gitter chat: https://gitter.im/vispy/vispy
Mailing list: https://groups.google.com/forum/#!forum/vispy

Regarding the error, telling us what the error is would be helpful :wink: 

I'm not sure if there is way to have the camera auto-fit all objects. I'm not aware of one at least.

**Comment by rougier** [comment]
I'm not sure the shader is right actually. If you look at https://en.wikipedia.org/wiki/Phong_reflection_model the formula is given and it seems to differ from the one in the shader. I think I recognize my code but it doesn't mean it correct :)

**Comment by sofroniewn** [comment]
Just noting I see this too, I can check if it is fixed by #1463 if it would be helpful

**Comment by yxdragon** [comment]
hi, any fix now?

**Comment by djhoese** [comment]
No, sorry. This is really beyond what I know with OpenGL. @sofroniewn Any updates?

**Comment by yxdragon** [comment]
I think I can know the physics model, but I am not aware of open gl and shader. So we can try to fix it together.

```python
void main() {
    //DIFFUSE
    float diffusek = dot(v_light_vec, v_normal_vec);
    // clamp, because 0 < theta < pi/2
    diffusek  = clamp(diffusek, 0.0, 1.0);
    vec4 diffuse_color = v_light_color * diffusek;

    //SPECULAR
    //reflect light wrt normal for the reflected ray, then
    //find the angle made with the eye
    float speculark = 0.0;
    
    if ($shininess > 0.) {
        speculark = dot(reflect(v_light_vec, v_normal_vec), v_eye_vec);
        speculark = clamp(speculark, 0.0, 1.0);
        //raise to the material's shininess, multiply with a
        //small factor for spread
        speculark = 20.0 * pow(speculark, 1.0 / $shininess);
    }
    vec4 specular_color = v_light_color * speculark;
    gl_FragColor = v_base_color * (v_ambientk + diffuse_color) + specular_color;
}
```
1. reflect(v_light_vec, v_normal_vec)   # get the light reflect by the normal
2. dot(rst_reflect, v_eye_vec)  # got the angle between reflect and eye, the v_eye_vec should be the vertex - eye_position
about the v_eye_vec, I find this line in vertex shader, **is it means vertex - eye_position?**
    vec3 eye = normalize(pos_front.xyz - pos_back.xyz);
    v_eye_vec = eye; //VARYING COPY
3. speculark = clamp(speculark, 0.0, 1.0);  # clip the result, 1 means reflect to eye all.
4. speculark = 20.0 * pow(speculark, 1.0 / $shininess); # count the power from the reflect light
5. ... multiply the light_color then add it to the result.

**Comment by sofroniewn** [comment]
> No, sorry. This is really beyond what I know with OpenGL. @sofroniewn Any updates?

No updates from me. I also didn't get around to checking if it was fixed by #1463, but that might be a good place to start!

**Comment by djhoese** [comment]
Just tested with #1463 and the result is different but still not right.

![image](https://user-images.githubusercontent.com/1828519/117587501-e589a500-b0e3-11eb-8ac1-17b37038df9e.png)

Interestingly with the panzoom camera I don't see any bright spot in the "front facing" view that it defaults to.

**Comment by djhoese** [comment]
@yxdragon Make sure you look at the shader code in #1463. I'm currently working on writing tests for this PR and then plan on merging it. As mentioned above the end result seems to be slightly different due to implementation detail changes, but it is still wrong.

**Comment by asnt** [comment]
@yxdragon @djhoese The highlight in the shadow is fixed with #2028.

![issue-1998-fix_highlight_in_shadow](https://user-images.githubusercontent.com/830589/119803326-a4650380-bedf-11eb-934a-f4ca5a1cda7d.png)

**Comment by almarklein** [comment]
This can be closed, right?

**Comment by djhoese** [comment]
Based on @asnt's comment above I think so. I just ran it with `main` and got a similar result. I do want to point out the odd lighting peak value (bright on 3 surfaces but not the other 3) which may merit tweaking the default parameters, but it may be expected and I don't think it warrants keeping this issue open:

![image](https://user-images.githubusercontent.com/1828519/122316683-ec28ea80-cee1-11eb-8a11-9e933b8be196.png)

**Comment by asnt** [comment]
> I do want to point out the odd lighting peak value (bright on 3 surfaces but not the other 3) which may merit tweaking the default parameters

@djhoese This is part of #2054. It still needs to be fixed.
