### ISSUE TITLE
SurfacePlot color change slower with set_data versus mesh_data.set_vertex_colors

### ISSUE THREAD

**Issue by hippalectryon-0** [vispy/vispy#2001]
Sample code below: a SurfacePlot whose color is updated when "O" is pressed using `mesh_data.set_vertex_colors`.

Problem: the `mesh_data.set_vertex_colors` works if called before adding the surface to the view, but not in later calls.

Temporary fix (thanks @djhoese ): add `surf.mesh_data_changed()` after changing the color.

PS: using `surf.set_data(colors=c)` instead of `surf.mesh_data.set_vertex_colors(c); surf.mesh_data_changed()` also works, but for some reason is much slower

```
import vispy, vispy.scene
import numpy as np

shape =  (200, 200)
Z = np.random.random(shape)*5
B = np.random.random(shape)

##


canvas = vispy.scene.SceneCanvas(keys='interactive', show=True)
view = canvas.central_widget.add_view()

surf = vispy.scene.visuals.SurfacePlot(z=Z, color=(1, 1, 1, 1))

# Add color
def setColor(C):
	C = np.array(C)
	c = vispy.color.get_colormap("hsl").map(C/np.max(C)).reshape(C.shape + (-1,))
	c = c.flatten().tolist()
	c=list(map(lambda x,y,z,w:(x,y,z,w), c[0::4],c[1::4],c[2::4],c[3::4]))
	surf.mesh_data.set_vertex_colors(c)
setColor(B)

# cycle colors on key press
col_cycle_i = 0
def cycle_colors(event):
	key = event.key.name
	if key != "O": return
	global col_cycle_i
	col_cycle_i = (col_cycle_i+1)%2
	print('Setting new coli', col_cycle_i)
	if col_cycle_i == 0:
		setColor(B)
	elif col_cycle_i == 1:
		setColor(Z)
		
canvas.events.key_press.connect(cycle_colors)
view.add(surf)
axis = vispy.scene.visuals.XYZAxis(parent=view.scene)
view.camera = 'fly'
```

**Comment by djhoese** [comment]
Thanks for this. As mentioned on gitter, the `set_data(colors=c)` works but is much slower than touching the mesh_data directly. This is probably because the surface plot is recreating/re-setting the data for the mesh every time it is run. We should be able to optimize that away if we detect that only a color change is needed.
