### ISSUE TITLE
Standardize use of .update() in Visuals

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2003]
It is not clear without reading source code whether `.update()` has to be called on a Visual (or the Canvas). Assigning to some properties of Visuals run an implied `.update()` causing a redraw of the entire Canvas. The problem with this is:

1. It is a performance loss if the user wants to update multiple properties.
2. I don't think it is run on all properties so users end up calling `.update()` themselves. This is especially confusing when users look at gloo examples versus SceneCanvas examples.

Number 1 would not be an issue if it was more public (and functional) to block draw events. This is sometimes possible, but even I don't remember how to do it all the time.

I propose we remove all `.update()` calls that occur inside a Visual and make it the responsibility of the user to call it on the Canvas (or the Visual if they really want to but I think these are equivalent). Objections? Other ideas?

CC @tlambert03 who worked on a `updating_property` decorator in #1792.

**Comment by elboss1** [comment]
when a new visual is drawn on to the canvas does the canvas update automatically? Or you have to call the .update for the canvas?

**Comment by djhoese** [comment]
Depends exactly what you mean. Are we talking the `SceneCanvas`? What do you mean by "drawn on to the canvas"? If you mean added to the view then I don't think it is automatically redrawn.

**Comment by elboss1** [comment]
I am talking about the SceneCanvas, lets say that we add a visual in the view and then we show the canvas. If I then add another visual in the canvas will I have to call the .update() method on the canvas? I am asking because for me it makes sense that if I change the data of visuals I should call the .update() on the visual, but if I add visuals in the view then it sounds more logical to call the .update() on the canvas. I home I make sense.

**Comment by djhoese** [comment]
Ah, sorry, I didn't realize you were asking about canvas versus visual calls to `.update()`. I thought you were talking about whether or not you have to call update at all. This issue is not about removing the `.update` method itself, but rather the implicit calls to it from within the Visual. Right now, it doesn't matter which update method you call as both will cause a redraw of the entire Canvas. I'm not sure that will change any time soon.

**Comment by campagnola** [comment]
Here's the intended behavior:
- Any modification to a visual that requires a redraw will internally call `visual.update()`.
- The update method only informs the canvas that a redraw is needed. The canvas schedules the redraw in the future, after control has returned to the event loop.

If those two things are working correctly, then the user never needs to manually call update() (neither on a Visual, nor the SceneCanvas), and can make multiple sequential changes to the scene without causing multiple redraws. 

A tricky issue here is that some visual modifications are expensive (for example if we need to re-bake some vertex data on the CPU), and each visual needs to decide for itself whether to handle those updates immediately when the user requests them, or later when the scene is rendered again. Neither option is obviously correct; it really depends on the expected use cases for the visual. Occasionally, it may help to make this behavior configurable by the user.

**Comment by djhoese** [comment]
Understood. The idea is that if a user has a function that updates 3 properties (for example), that the `.update()` call in VisPy will add a "redraw" event to the GUI event loop. The user's currently running function doesn't "release" control to the event loop until it is done running so these 3 properties should be able to add 3 draw events to the GUI event loop which should *hopefully* be merged and only one total draw executed. Right?

The series of events, as I understand it, for the regular Canvas is:

```
Canvas.update() -> self._backend._vispy_update() -> (Qt) Widget.update() -> Qt draw event -> Canvas.on_draw -> (user implemented) Visual.draw() -> Visual._prepare_draw(); GL Program.draw()
```

In the SceneCanvas has two complications:

1. SceneCanvas.on_draw includes determining draw order (.order) and visibility (.visible) of Visual Nodes.
2. SceneCanvas.update has some "bounce detection" to only call `.update` if the SceneCanvas isn't either waiting for a draw event or it isn't in the process of drawing.

Now, the whole point of this `.update()` system that you're bringing up @campagnola is that the GUI event loop will filter out duplicate events. As far as I know for PyQt5 (our most popular backend), this isn't the case. It will call draw multiple times. That's why the optimizations in the `SceneCanvas.update` method were implemented in the first place or at least that's how I remember it.

In addition to what you're talking about with expensive modifications like vertex data updates, I want to specifically point out the TransformSystem and cameras in VisPy that may connect a lot of pieces and updates to these may touch more than just a few update methods.

I admit my proposed solution may not be the most obvious, but the bottom line is that VisPy is wasting CPU resources doing updates or calculations for updates that it doesn't need to be doing. This isn't just for the user, there are CompoundVisuals in VisPy that may be updating their child visuals and each of those children will be requesting an update. So not only do we not want the wasted CPU to do this, we don't even want the draw to happen with these inconsistent property changes (one child being updated before all children are updated). There isn't any well documented solution to block these updates until they are all done as far as I know because the `.update()` call is not part of VisPy's "events" system (which has event blocking).

I also admit I could be wrong about some or all of this so feel free to correct me.

**Comment by almarklein** [comment]
> As far as I know for PyQt5 (our most popular backend), this isn't the case.

It should - multiple calls to `update()` should result in a single paint event. I just tried:
```py
from vispy.app import Canvas

class MyFig(Canvas):
    def on_draw(self, event):
        print("draw") 

f = MyFig()
f.show()
```
Then:
```
>> f.update(); f.update(); f.update();
draw
```

It could be that some other backends do not have this feature, and this is why the update-logic was added in `SceneCanvas`. But IMO that logic should be in the respective GUI backends instead.

**Comment by djhoese** [comment]
Well that's pretty clear. I still feel a little funny about a property that updates other properties and results in potentially multiple draws (depending on how long they take)...but ok. I guess I'll close this as it shouldn't generally be needed for "sophisticated" backends.

**Comment by almarklein** [comment]
Do you have an example of how updating two properties results into multiple calls? Would be good to investigate why this happens. I can imagine that some internal event is involved (code listens for a property changing, and when it happens, it updates another property).

**Comment by djhoese** [comment]
Not multiple draw events, but multiple calls to `.update`. The simple one is some of the CompoundVisuals made up of meshes and lines. They have properties like `.color` that will update each of the child visuals and then call `.update`. I couldn't find an example of what I'm thinking of exactly, but this is the same idea:

https://github.com/vispy/vispy/blob/e8d395ddbc7bd0b64c484729ed0cf22fa6df6ef7/vispy/visuals/polygon.py#L68-L91
