### ISSUE TITLE
Conduct VisPy User Survey

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2006]
## Overview

It was brought up by @rossant during the 2021 Feb Sprint that we should conduct a survey of the VisPy community. The main goals being:

1. Who are our community members? What do they use VisPy for?
2. How do they use VisPy (backends, API level, etc)?
3. Anything else.

I can make the survey on Google Forms and send it out to the mailing list and twitter. Please comment with any additional questions you can think of.

## Remaining questions about conducting the survey

A. Any need to record emails/names?

## Proposed Survey Questions

(NOTE: Ordering and grouping not done)

1. What do you use VisPy for?
2. Which of the following are reasons you use VisPy:
   a. Meshes
   b. Volumes
   c. Real-time signals/plots
   d. Performance
   e. Offscreen rendering
   f. GUI framework backends/integration
3. Why do you use VisPy over other solutions?
4. Do you use the "gloo" layer, Canvas + Visuals, SceneCanvas, or Plotting API?
5. Do you write your own shaders (GLSL)?
6. What backend(s) do you use (PyQt, PySide, I don't know, etc)?
7. How important is the specific backend to your application? Are you integrating VisPy into a larger GUI application and would any GUI framework/functionality be acceptable?
8. How important is it to you that VisPy use OpenGL as opposed to a GPU API like Vulkan? If it provided the same high-level functionality would that be OK?
9. How important is it to you that VisPy support older GPUs?
10. How important is it to you that VisPy include mobile platforms and web browsers in the future?
11. How often do you use VisPy (just looking, occasionally, all the time)?
12. How important do you think the following areas are for future VisPy development: simpler interfaces, better performance, web/jupyter support, documentation, tutorials, Vulkan/WebGPU support, other, etc. (important, somewhat, not at all)
13. How do you learn best when it comes to a Python library like VisPy (API documentation, example scripts, text-only tutorials, video tutorials, other, etc)?

**Comment by almarklein** [comment]
Small remark, with "How important is it to you that VisPy use OpenGL?" I can imagine people responding "very important" because they want their code to be fast. So maybe add "as opposed to a GPU API like Vulkan".

**Comment by djhoese** [comment]
Good idea. Updated.

**Comment by djhoese** [comment]
Just to close this out, we've conducted the VisPy User Survey and learned a few things. The shortest summary is that:

* ~50% Linux user, 33% Windows
* Mostly Nvidia GPUs and most people use or need to support a GPU from the last 5 years
* Most people use PyQt/Pyside
* Most users use one single interface (every category had mostly "never use" answers) and the most used is the Visuals and SceneCanvas. People occasionally need custom shaders.
* Most people don't need OpenGL specifically and those that said they do seem to need it due to custom shaders. As discussed on the mailing list, no matter what happens to VisPy or any future sibling projects, GLSL would still be used and there are conversion/transpiling/porting options available.
* Top 3 learning options are API docs, Example scripts, and Text tutorials. Video tutorials are not as popular.
* Everyone needs all types of visualization functionality (plotting, meshes, volumes, etc) :wink: 
* Most important visualization features are speed of handling lots of data with GUI support, offscreen rendering, and screenshots being the next most important.
* Almost everyone wants to be able to run/deploy visualizations on a desktop environment with interactive desktop and jupyter visualizations being second.
* Of the comments on why custom shaders were needed, most seem related to features that could be added directly to VisPy but haven't been yet. Others were related to application specific optimizations that could still probably be included in vispy.
* VisPy is missing easier plotting interfaces and needs to be easier to use
* Steps to improve D&I should include improved tutorials and examples and documentation
* We're doing a great job! But also need to "please finish making vispy" :cry:

**Comment by jni** [comment]
Awesome summary @djhoese! Any surprises for you?

**Comment by djhoese** [comment]
I was a little surprised by the number of users who said they write custom shaders. So surprised that we didn't even think to ask why they needed to write them and had to ask on the mailing list after the fact (since no contact information was left by those people).

The other surprise was how many people are using Qt based GUIs. All the other backends had been chosen by at least 1 person, but Qt had almost everyone using it.

Also, I think some people just take surveys to skew the results. One or two people answered every multiple choice question by selecting every choice no matter how unlikely that is.
