### ISSUE TITLE
Unable to run under conda and M1 mac

### ISSUE THREAD

**Issue by watjurk** [vispy/vispy#2013]
When I try running `import vispy` on my computer I'm getting the following error:

```
➜  python           
Python 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:00:30) 
[Clang 11.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vispy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 158, in <module>
    objc.class_getMethodImplementation_stret.restype = c_void_p
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/ctypes/__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/ctypes/__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x102d87dc0, class_getMethodImplementation_stret): symbol not found
>>> 
```

I've read every issue related to this error and I can't figure that one out...
If you need any additional info about this error I'll be happy to help.

**Comment by djhoese** [comment]
What version of vispy are you using? Could you try installing it from the master branch and see if that changes anything. This error is different than those encountered in #1885 so I'm not really sure what is going on here.

**Comment by watjurk** [comment]
vispy 0.6.6 (installed by pip).
If by `installing it from the master branch` you mean running those commands:
```
git clone --recurse-submodules git://github.com/vispy/vispy.git
cd vispy
git submodule update --init --recursive
pip install -e . --no-use-pep517
```
then when installed from master branch I'm getting the same error (only difference are paths that now point to new vispy location).

**Comment by djhoese** [comment]
Thanks for the info. Could you try downgrading your version of python to 3.9.1 and see if that fixes anything? `conda install python=3.9.1` should work I think.

**Comment by watjurk** [comment]
Unfortunately it does not... getting still the same error. I've tried reinstalling `vispy` and the error is still there.

**Comment by djhoese** [comment]
Unfortunately, I don't have an M1 mac (or mac at all). I've asked some coworkers to explore this for me. We'll update this issue if we find anything. Otherwise, we'll need to get more people with M1s to test some things. Maybe we could check with some of the people from #1185.

**Comment by watjurk** [comment]
Okay, if there is anything I can do to help I'll be happy to contribute.

**Comment by djhoese** [comment]
@sumanthratna or @astrofrog or @goanpeca are you also experiencing this issue if you update Python (or maybe just run it as you had it in #1885). @isuruf, you fixed the issue on conda-forge last time, any idea of a change that might cause a similar issue as described in #1885?

**Comment by isuruf** [comment]
`class_getMethodImplementation_stret` is not available on arm64

**Comment by watjurk** [comment]
So this isn't vispy bug?

**Comment by djhoese** [comment]
> So this isn't vispy bug?

Yes and no. VisPy is using ctypes to talk to the cocoa libraries. It appears that the way this is being done isn't supported on arm64 systems. We (vispy) *might* be able to get around it if we replaced our `vispy.ext.cocoapy` with an external package like https://pypi.org/project/PyCocoa/ (or other wrapper). I'm not sure I know enough about this to say what the right solution is. I'd prefer not to continue maintaining `vispy/ext/cocoapy.py` but also don't want to force mac/M1 users to have to install an additional package.

**Comment by sumanthratna** [comment]
> @sumanthratna are you also experiencing this issue if you update Python (or maybe just run it as you had it in #1885)

With Python 3.8.9 (clang-1200.0.32.29) and vispy 0.6.6, I get this error on import: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.8/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/private/tmp/venv/lib/python3.8/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/private/tmp/venv/lib/python3.8/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/private/tmp/venv/lib/python3.8/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/private/tmp/venv/lib/python3.8/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/private/tmp/venv/lib/python3.8/site-packages/vispy/ext/cocoapy.py", line 1126, in <module>
    NSEventTrackingRunLoopMode = c_void_p.in_dll(
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found
```

With Python 3.8.9 (clang-1200.0.32.29) and vispy HEAD (vispy-0.6.5.dev357+g04d05056.d20210414), I get no errors on import. 

With Python 3.9.4 (clang-1200.0.32.29) and vispy 0.6.6, I get no errors on import. 

(all of the above data is as of ~10 min before the initial posting of this comment)

**Comment by isuruf** [comment]
Just wrap https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L179-L180 around an  `if platform.machine() != "arm64":`

**Comment by watjurk** [comment]
I've added if's as suggested, in those places:
https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L158-L159
https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L179-L180
https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L278-L280

and now it works! After installing glfw `vispy.sys_info()` works file too.

**Comment by sumanthratna** [comment]
@djhoese Looks like the issue was patched in Python 3.8.10 (Homebrew 3.1.5-20-gf018162, macOS Big Sur 11.4 Beta 20F5046g)

**Comment by psobolewskiPhD** [comment]
> I've added if's as suggested, in those places:
> 
> https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L158-L159
> 
> 
> https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L179-L180
> 
> 
> https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/ext/cocoapy.py#L278-L280
> 
> and now it works! After installing glfw `vispy.sys_info()` works file too.

This worked for me on python 3.9.5, Big Sur 11.4, Apple M1, everything from condo-forge.
Thanks!

**Comment by kmuehlbauer** [comment]
From reading the comments it seems the issue is solved. If there is more discussion needed, please comment and we reopen.
