### ISSUE TITLE
Sky view using VisPy?

### ISSUE THREAD

**Issue by cfpark00** [vispy/vispy#2014]
Hi, I am an astrophysicist who got interested in VisPy.

First of all, thank you a lot for this awesome package.

I was wondering if I could visualize the 2-sphere from the inside via VisPy.

Basically something like this:

http://worldwidetelescope.org/webclient/?fbclid=IwAR0jjOErkCeCM79JTnpp39BnW6ciInG2LqyscBm1WXrfOow07B5EZa2IYCY

I think this will be a great use of VisPy for the astrophysicst community.

I will be happy to make this module myself and contribute to VisPy if you can tell me where to start. I think that the part of putting colors on faces of a sphere is already done, I'm actually trying to figure out the camera....which I have failed to do so:

As a camera:
Fixed camera at origin of the sphere, 2d pan and zoom will be great.

Thanks!
-Core

**Comment by djhoese** [comment]
Hi. Seems like a cool project. I don't see why this shouldn't be possible. You might be able to use the "arcball" camera with a large enough sphere to get what you want. You talk about 2d pan/zoom, but wouldn't this be zooming?

You may run into issues if the camera isn't limited for how far it can zoom in/out or if OpenGL things something is "behind" (depth testing) something else and it will decide not to draw it. The idea here is that you are using the arcball around the center of the sphere, but looking "through" the center to the other side. Beyond that, I'm not sure how much of this task is already completed/builtin (there is the ability to add a texture to a mesh in the master branch).

**Comment by cfpark00** [comment]
Thank your for the reply.

I have tried arcball with a very small distance, that does indeed put me inside a sphere

Pan works fine, however zoom doesn't really do what I want since it "zooms" closer to the center and doesn't zoom onto the spherical shell.

**Comment by djhoese** [comment]
Oh that makes sense. I'm not sure the existing PanZoom camera would work unless your Visual object had a transform on it to convert 3D sphere -> 2D surface. At that point though, it'd be better to just do that logic in the camera. I wonder if you could make a subclass of the PerspectiveCamera: https://github.com/vispy/vispy/blob/04d050564b91161b1f8d4949e61c1df3b44af90d/vispy/scene/cameras/perspective.py#L15

This also seems like something the arcball camera should be able to do with some small modifications. I usually beg @rougier for help with stuff like this as he knows of recipes for doing everything in OpenGL.

**Comment by cfpark00** [comment]
Thank you,

I have actually looked into gloo, and made an implementation using OpenGL. Basically, I figured out that "zooming" was simply the fov in the OpenGL perspective transform.

Then, I did some spherical trigonometry stuff to get a plausible control from the mouse.

Basically, I get something pretty satisfying.(zoom, mouse panm, gamma adjust are possible interactively)

![image](https://user-images.githubusercontent.com/41690447/115129464-2ba38b00-9fb4-11eb-9529-1f372ad0591c.png)

Data: https://dustmaps.readthedocs.io/en/latest/license.html (SFD dustmap)

I think that its actually pretty important to change the color values interactively, Right now I am doing that via re-colormapping and sending that to the shader. But as you probably know, this currently requires me to transfer data between the CPU and GPU, even if the actually colormapping can be done on the GPU.
(This might simply be because I don't know how to move this operation to the shader code.)

But anyways, I think that the pytorch, cupy support is indeed very important as you point out.

I will be happy to push my implementation as a VisPy example if you have some instructions for how to do that.

Thanks,
Core

**Comment by djhoese** [comment]
> I have actually looked into gloo, and made an implementation using OpenGL.

Great! It'd be awesome to see this as a camera and a set of Visuals if at all possible.

> I think that its actually pretty important to change the color values interactively, 

The colormaps in VisPy are able to store the colormap as a Texture in the GPU and do the conversion from data -> color there. In a recent pull request I merged the ability to define a floating point texture in the ImageVisual which gets you even more precision in the GPU when converting to colors. The ImageVisual may be a good example of using colormaps like you want.

**Comment by cfpark00** [comment]
I see, thank you for your second advice.

For you first comment, I'm actually kind of confused how Visuals and gloo works together, the examples seems to be pretty separated as well as the documentations.

Could you suggest me an example of where to start?

Thanks

**Comment by cfpark00** [comment]
Well, actually I can start from the ImageVisual for this as well, thanks.

**Comment by djhoese** [comment]
The idea is that if you took a single GL Program (from gloo-land) and put it in a class with a specific set of methods it magically becomes a Visual. If you look at any of the lower-level Visuals like ImageVisual, VolumeVisual, or MeshVisual you'll see how they pass shaders to some base class methods which create a Program. Then the `__init__` and `prepare_draw` methods assign various things to the Program/Shader objects, create textures and buffers, and then finally run the program.

**Comment by almarklein** [comment]
This looks like something where a CubeTexture could be of use - this looks similar to a skybox use-case.

**Comment by kmuehlbauer** [comment]
@cfpark00 It looks like you solved your problem. If there is more discussion needed, please comment and we reopen.
