### ISSUE TITLE
set_data not working in a for loop?

### ISSUE THREAD

**Issue by pcpatfire** [vispy/vispy#2015]
Hi, I modified to `scatter.py `code to display random markers in a loop (without using timer). The problem is that the markers aren't drawn until the end of the `for` loop, as if the `set_data` wasn't working. Why? 
This is the very simple code:

```
# pylint: disable=no-member
""" scatter using MarkersVisual """

import numpy as np
import sys

from vispy import app, visuals, scene

# build your visuals, that's all
Scatter3D = scene.visuals.create_visual_node(visuals.MarkersVisual)

# The real-things : plot using scene
# build canvas
canvas = scene.SceneCanvas(keys='interactive', show=True)

# Add a ViewBox to let the user zoom/rotate
view = canvas.central_widget.add_view()
view.camera = 'turntable'
view.camera.fov = 45
view.camera.distance = 500

def create_random_data():
    # data
    n = 5000
    colors = np.random.rand(n, 4)
    pos = (np.random.rand(n, 3) - 0.5) * 200
    size = np.random.rand(n,) * 30

    return colors, pos, size

# plot ! note the parent parameter
p1 = Scatter3D(parent=view.scene)
p1.set_gl_state('translucent', blend=True, depth_test=True)

for n in range(100):
    colors, pos, size = create_random_data()
    p1.set_data(pos, face_color=colors, symbol='o', size=size, edge_width=0.5, edge_color='blue')

# run
if __name__ == '__main__':
    if sys.flags.interactive != 1:
        app.run()
```

**Comment by pcpatfire** [comment]
I forgot something. If I insert the an `input` after `set_data`:

`input('Hit ENTER to continue...')`

the `set_data `is working well.

**Comment by djhoese** [comment]
So there are a couple things going on here. The bottom line is that doing what you are doing, without a timer, is not going to be reliable without doing other things that are considered bad practice. In a GUI application you have to consider the event loop (something the backend GUI framework creates). The event loop steps through a series of events or actions to get things done. Things like draw events, click events, keyboard events, etc. The GUI framework is continuously stepping through the events on the event loop to make your GUI application function. If an event in the event loop takes a long time to process, that means the GUI backend can't get to the other events until the current one is done. You see this often when someone puts a long running computation on a timer and they are confused at why the GUI "hangs" and stops responding until the computation is complete. The GUI can't "draw" the GUI until the compute step is complete.

In your case though, your for loop is happening before the event loop processing has even started. The event loop is started with `app.run()`. It sees a series of draw events (one for every iteration of your for loop), but the state of the Canvas is already set to a single state (the last iteration of your for loop) so you never see the progression between the iterations. Also, you don't have any sleep time between your iterations so you (as a human) probably wouldn't be able to see the individual iterations anyway. In a normal execution like `python your_script.py` I would not expect `input` to make a difference, so I'm a little surprised it is doing something. Are you running your script like that or are you running it from `ipython` or a tool like Spyder? In the latter case, I could see the `input` giving the GUI event loop time to process events if it was started by a GUI tool like Spyder in which case VisPy is just "borrowing" the event loop.

**Comment by pcpatfire** [comment]
Thank you for your answer. I am running the code from Visual Studio. What I should  actually do is displaying sets of markers - some thousands each - from a file which contains thousands of sets, while they are loaded from the file. It takes more than 10-15 minutes to read a single file (3-6 GB).
It is not clear to me if, for instance, I execute the same command from a menu, in a more complex application, after a while it has been started, the same for loop will work or not. At that time the app.run() should be already working, correct?

PS: My 'set of markers' are the molecules loaded from the output file of a Molecular Dynamics software. It would be great if there were a better way to draw 'atoms' ('spheres') instead of 'o' markers, but efficiently - the molecular viewer example can't handle the display of tenths of millions of atoms at the same time, as required.

**Comment by djhoese** [comment]
So you have multiple files, each file has thousands of sets, and each set is thousands of molecules? Keep in mind: https://vispy.org/faq.html#why-is-my-visualization-slower-when-i-add-more-visual-objects

If you initiate the data loading from a menu then yes your `app.run()` would be going by then, **BUT** then you run into the first problem I talked about. Let's say you added a menu to start the loading, like File -> Open Files... -> <open file dialog> -> User clicks "Open" for some files. Your GUI would be unresponsive until all that data was loaded. Without extra "hacks", the user wouldn't be able to click on anything, close the application normally, and you wouldn't even be able to show a progress bar.

The typical method for doing something like this would be to use a background thread to do the data loading (ex. PyQt has a QThread class). The background thread then communicates with the main/GUI thread (ex. PyQt calls this Signals and Slots). This way, you could load the files in the background thread, creating the numpy array that will be passed to your Visuals, then signal the main/GUI thread that the data is ready, then the GUI thread passes it to `set_data` of the Visual (or creates a new one). That way, the GUI thread only "hangs" while the Visual is being updated/drawn, not while the data is being loaded.

Note that you can't draw in background threads: https://vispy.org/faq.html#is-vispy-multi-threaded-or-thread-safe

As for the best way to draw molecules...I'm not sure. Sorry. If the molecular viewer isn't good enough then that's not good because it is already pretty low level if I remember correctly.

**Comment by pcpatfire** [comment]
Maybe I did not understand well. I was running this code:
```
    def on_view_structures(self):
        nstru = len(stru_files[0])
        if len(stru_files) > 0 and len(stru_files[0]) > 0:

            re_chars = '[0123456789+-]'

            pos_all = stru_files[0][0].xyz_cartn
            colors_all = [ELEM_TO_COLOR[re.sub(re_chars, '', a.element).split('_')[0]] for a in stru_files[0][0]]
            size_all = np.array([float(ELEM_TO_RADIUS[re.sub(re_chars, '', a.element).split('_')[0]]) for a in stru_files[0][0]]) * 0.15

            for n in range(1, nstru):
                s = stru_files[0][n]

                pos = s.xyz_cartn
                colors = [ELEM_TO_COLOR[re.sub(re_chars, '', a.element).split('_')[0]] for a in s]
                size = np.array([float(ELEM_TO_RADIUS[re.sub(re_chars, '', a.element).split('_')[0]]) for a in s]) * 0.15

                pos_all = np.append(pos_all, pos, axis=0)
                colors_all += colors
                size_all = np.append(size_all, size)
                
                self.stru_canvas.plot.set_data(pos_all, face_color=colors_all, symbol='o', size=size_all, edge_width=0.5, edge_color='blue')
        else:
            print('No structures loaded!')
```

I'm getting data from a list of structures with atoms (markers) - already loaded this time - and I'm creating an array markers' positions that is 'increasing' at each for cycle. There are two arrays for colors and markers' sizes. The positions of the same atoms from one structure to another can be a little different, because we are simulating the movements of atoms due to the changing of some external conditions. See the attached picture (with 100 structures).

I added the set_data inside the for loop to create an 'animation' with all the atoms positions, while more and more structures are added... again, as for the other for loops, I get only the drawing of the final step of the for loop. Is there a way to display data at each cycle? Is the process too fast? Should I use a timer?
![CryStIE_2021-04-19](https://user-images.githubusercontent.com/50824984/115292029-c1c2e700-a155-11eb-988d-62694476e085.png)

Thank you for your help.

**Comment by djhoese** [comment]
What is calling this `on_view_structures` method? When is it called?

If you are trying to produce an animation, there has to be some time component to it. The "safest" way to do this is with a timer. Have the timer call a function that produces **one** frame and make the timers interval what you want for the frames per second (FPS) you want. You will also want to add a `canvas.update()` to the end of this function to *force* a redraw of the Canvas when the data has been updated.

Note that if the callback function takes a long time (including drawing) then you won't be able to get the FPS you want. For example, you set the timer interval to `1 / 60.0` to get 60 FPS, but your array creation and `set_data` call take 1 second to finish. You'll never get anything faster than 1 FPS (at best).

Hope that helps...if not, let me know.

**Comment by pcpatfire** [comment]
Yes, it helped! Thank you!
Using the timer is definitely the best solution (probably the only one really working as I need).  The code is cleaner too. I'm setting the 'auto'  value for the timer interval, and the resulting animation is just fine.
I created a new Marker visual for each structure (stored in a list) when drawing a set of structures all together, and I removed them before drawing a new set of structures by setting their parents to 'None'. Is it enough to make Python delete them from memory or should I `clear` the list containing the Markers visuals too?
This is the code (the `on_view_trajectory` function is simply connected to a menu command):
```
    def on_view_trajectory(self):
        if len(globs.stru_files) > 0 and len(globs.stru_files[globs.curr_file]) > 0:
            len_plot = len(self.stru_canvas.plot)
            while len_plot > 0:
                self.stru_canvas.plot[len_plot-1].parent = None
                len_plot -= 1

            self.on_timer_ncurr = 0
            self.timer = app.Timer('auto', 
                connect=self.on_timer_view_trajectory, 
                iterations=len(globs.stru_files[globs.curr_file]), 
                start=True)
        else:
            print('No structures loaded!')

    def on_timer_view_trajectory(self, event):
        self.stru_canvas.plot.append(self.stru_canvas.new_plot())
        s = globs.stru_files[globs.curr_file][self.on_timer_ncurr]

        el = lambda element: re.sub(re_chars, '', element).split('_')[0]

        pos = s.xyz_cartn
        colors = [ELEM_TO_COLOR[el(a.element)] for a in s]
        size = np.array([float(ELEM_TO_RADIUS[el(a.element)]) for a in s]) * 0.15

        self.stru_canvas.plot[-1].set_data(pos, 
            face_color=colors, 
            symbol='o', 
            size=size, 
            edge_width=0.5, 
            edge_color='blue')
        self.on_timer_ncurr += 1
```

**Comment by djhoese** [comment]
>  Is it enough to make Python delete them from memory or should I clear the list containing the Markers visuals too?

Depends what "enough" means. Your code doesn't show where/how the Markers are created but based on your question I'll assume you have a list of marker visuals. If "enough" means that the GPU isn't doing needless work, then yes setting `parent` to None is enough. VisPy should no longer send those visuals to the GPU to be drawn. If you are worried about CPU memory then deleting from the list would be good, especially if they contain a lot of data. However, if you plan on re-viewing these Markers then obviously it would be good to keep them around to quickly make them visible again. Note there is also a `.visible = False` property you could set on Visuals that will also turn them "off" as far as the GPU is concerned. This may give you the best performance if you need to quickly turn some frames/visuals on or off.

**Comment by pcpatfire** [comment]
In my case I don't need to keep in memory the visuals, so I decided to clear the list containing them.
Concerning my first issue - displaying structures while loading them - I followed your suggestion and I found a very simple solution, using Python threading:
```
        import threading

        ...

        if fileformat in ('dlpoly2hist', 'dlpoly3hist'):
            t = threading.Thread(target=globs.stru_files.read, args=(filename, fileformat, nstart, nend))
            t.start()
            print('loading in background...')
```
The `stru_files` variable, which contains the lists of structures loaded from files,  is shared between the GUI thread and the read one, running in parallel, thus allowing a View Structure command - executed from the GUI, that is not freezed now - to plot the structure, while loading. Everything is working as expected!
Thanks again for your help!

**Comment by djhoese** [comment]
Glad you got something working. I should note that I think using regular python threads with a GUI application (like one based on PyQt/PySide) is considered bad practice. I'm not sure if it causes any issues, but it may be something to revisit in the future in your application.

**Comment by pcpatfire** [comment]
I used regular Python threads because the target function contains only
pure Pyhton code without any GUI interaction. Anyway I will consider your
suggestion.

Il giorno gio 22 apr 2021 alle ore 14:03 David Hoese <
***@***.***> ha scritto:

**Comment by djhoese** [comment]
Background QThreads can't use GUI interaction anyway. As I say in the vispy FAQ, all GUI functions have to be done in the main/GUI thread. The advantage of using a QThread would be that Qt knows about it and can manage it. You could also have further, more complicated, interactions with a QThread like sending signals between the main thread and background thread. For example, main thread -> "start reading these files" -> background thread, followed by background thread -> "I finished reading all the files" -> main thread.
