### ISSUE TITLE
Unable to install Vispy under miniforge on M1 mac

### ISSUE THREAD

**Issue by fiamere** [vispy/vispy#2018]
When I try installing `Vispy` I encounter this:
```
(python38) USERNAME@USERNAME-Air ~ % conda install -c conda-forge vispy
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - vispy

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
How can I solve this?

**Comment by djhoese** [comment]
It would seem the conda-forge package needs to be updated to support osx-arm64. I have not seen an automated pull request for this on conda-forge. @kmuehlbauer or @hmaarrfk any ideas (you two have had the most participation with vispy on conda-forge from memory)? Last I remember, rebuilds for osx-arm64 were automated by one of the conda-forge bots right? I don't see a PR for this on the vispy feedstock.

**Comment by hmaarrfk** [comment]
I don't think we have compiled vispy yet, but maybe you can try to manually installing the dependencies.

I'm trying to add it to the migrator.

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1453

**Comment by hmaarrfk** [comment]
Migrator seems to have worked. You should have a package soon:
https://github.com/conda-forge/vispy-feedstock/pull/28

**Comment by kmuehlbauer** [comment]
@fiamere I'll close this issue, but it would be good to know, if this now works for you.
