### ISSUE TITLE
Axis with flipped camera bug (PanZoomCamera)

### ISSUE THREAD

**Issue by FeBe95** [vispy/vispy#2019]
## Issue
Any flipped camera (mostly used for image viewing) results in bugged linked axes. When moving/panning the view the axis moves in the opposite direction, the labels behave strangely as well.
The bug is reproducible with every implementation of the PanZoomCamera (e.g. `view.camera = "panzoom"`, `PanZoomCamera()`, or via a `Fig()`)

## Example code
```python
import vispy.plot as vp
from vispy.io import load_data_file, read_png


fig = vp.Fig(size=(600, 500))
ax = fig[0, 0]

img_data = read_png(load_data_file("mona_lisa/mona_lisa_sm.png"))
image = ax.image(img_data)

ax.camera.flip = (False, True, False)  # flips y-axis

fig.show(run=True)
```

## Example result
![Animation](https://user-images.githubusercontent.com/7470739/117049017-f0bf8800-ad13-11eb-8e14-b16da93f16a9.gif)

## System details
OS: Windows 10
Python: Python 3.9.4
Vispy: 0.6.6

**Comment by djhoese** [comment]
My excuse for this is that I'm guessing the `.camera` is actually supposed to be something the user has public access to.

My solution for it though...I'm really not sure. I'm sure it needs to be handled differently somewhere in here:

https://github.com/vispy/vispy/blob/e33aae23847e8e5f43248ba9d014cc4aea211a90/vispy/scene/widgets/axis.py#L81-L88

But I'm really not sure and not an expert on how the plotting stuff was/is supposed to work. Sorry.

**Comment by Kusefiru** [comment]
Hey,

I noticed the same issue. This is one of the reasons I would like to work on improving the axis widgets (as I said earlier on the gitter chat).
I'll work on it as soon as I can (if someone want to contribute in the mean time, please do so).

**Comment by Kusefiru** [comment]
I've track downed the issue, which was because of this line : 

https://github.com/vispy/vispy/blob/e33aae23847e8e5f43248ba9d014cc4aea211a90/vispy/visuals/axis.py#L415

It flips the ticks positon if the axis is flipped, but it's not what we exactly want.

Say the `major_frac` (major ticks position) we get are `[0.15, 0.35, 0.55, 0.75, 0.95]`
Flipping it, we get `[0.95, 0.75, 0.55, 0.35, 0.15]`
But actually, the position of our ticks should be : `[0.85, 0.65, 0.45, 0.25, 0.05]` !

If we remove the quoted line, and add the following after the `minor_frac` computation : 

```python
if flip:
    major_frac = np.absolute(major_frac-1)
    minor_frac = np.absolute(minor_frac-1)
```

This does the job as you can see : 

![axis](https://user-images.githubusercontent.com/19759836/117977964-a0f34900-b331-11eb-859c-e6c6395ca2d0.gif)

**Comment by djhoese** [comment]
Wow! Nice job!

Just curious, are the tick positions always between 0 and 1? Could you do `1 - major_fac` and skip the absolute call?

**Comment by djhoese** [comment]
Oh and...pull request?

**Comment by Kusefiru** [comment]
> Just curious, are the tick positions always between 0 and 1? Could you do `1 - major_fac` and skip the absolute call?

It does, I'm just dumb.

I'll submit a pull request later - as I said there's a few things I would like to improve as well.

**Comment by djhoese** [comment]
Small fixes like this might be nice to have as individual pull requests if you can find a way to separate it from other work you're doing.

> It does, I'm just dumb.

Hey, you found the bug. Easy to overlook other options when you've been staring at the problem for so long. I'm really glad you found the solution. I was scared this was going to be around forever and I was never going to figure it out.

**Comment by almarklein** [comment]
Is this now fixed? If not, what remains?

**Comment by djhoese** [comment]
Yes, I think this is fully fixed. Closing. If I'm wrong then comment and we can reopen. If someone finds this in the future, please create a new issue and reference this one.
