### ISSUE TITLE
Axis stretch

### ISSUE THREAD

**Issue by juraj6** [vispy/vispy#2023]
Hello,

is it possible to stretch the axis regardless of the size of the array?

Example:

I have an image (visuals.Image) in the ViewBox. Then I have two AxisWidget-s linked to the view. If the image size is 100x200p, the axis ranges are (0-100) and (0-200) as expected. However, I want to stretch one axis, for example the first one from (0-100) to (0-555) without resizing the image.

**Comment by djhoese** [comment]
So you want the axis to refer to different values than what the image coordinates are? Could you provide a small example bit of code? That will make it easier to suggest things that fit into how you're doing things.

**Comment by juraj6** [comment]
Yes, that's correct. I want something like a time axis in normal plot. For example, I have 1000 points with a sampling period 0.2 ms, so the X axis must have a range 0-200 ms and not 0-1000 points.

Here is the sample code.

`
    from vispy import scene, app
    import numpy as np
    
    class Plot(scene.Widget):
        def __init__(self, title="", xlabel="", ylabel="", bgcolor="k", 
                     fgcolor="w", plotcolor="grey", padding=(0,0,0,0), 
                     *args, **kwargs):
    
            super(Plot, self).__init__(bgcolor=bgcolor, *args, **kwargs)
    
            if len(padding) != 4:
                raise ValueError("Padding must be a tuple of 4 elements (top, bottom, left, right).")
    
            self.unfreeze()
    
            self.fgcolor = fgcolor
            self.bgcolor = bgcolor
            self.visuals = []
    
            self.grid = self.add_grid(spacing=0, margin=0)
    
            # padding top
            paddingTop = self.grid.add_widget(None, row=0, col=1, col_span=3)
            paddingTop.height_min = paddingTop.height_min = padding[0]
    
            # padding bottom
            paddingBottom = self.grid.add_widget(None, row=4, col=1, col_span=3)
            paddingBottom.height_min = paddingBottom.height_min = padding[1]
    
            # padding left
            paddingLeft = self.grid.add_widget(None, row=0, col=0, row_span=5)
            paddingLeft.width_min = paddingLeft.width_max = padding[2]
    
            # padding right
            paddingRight = self.grid.add_widget(None, row=0, col=4, row_span=5)
            paddingRight.width_min = paddingRight.width_max = padding[3]
    
            # title
            self.title = scene.Label(title, font_size=16, color=fgcolor)
            titleWidget = self.grid.add_widget(self.title, row=1, col=1, col_span=4)
            titleWidget.height_min = titleWidget.height_max = 20
    
            # colorbar
            self.cbar = self.grid.add_widget(None, row=2, col=3)
            self.cbar.width_max = 1
    
            # X axis
            xaxis = scene.AxisWidget(orientation='bottom', axis_label=xlabel, 
                                     text_color=fgcolor, axis_color=fgcolor, 
                                     tick_color=fgcolor, tick_width=1, 
                                     tick_font_size=9, axis_width=1, 
                                     tick_label_margin=15, axis_label_margin=25)
            xaxisWidget = self.grid.add_widget(xaxis, row=3, col=2)
            xaxisWidget.height_min = xaxisWidget.height_max = 30
    
            # Y axis
            yaxis = scene.AxisWidget(orientation='left', axis_label=ylabel, 
                                     text_color=fgcolor, axis_color=fgcolor, 
                                     tick_color=fgcolor, tick_width=1, 
                                     tick_font_size=9, axis_width=1, 
                                     tick_label_margin=0, axis_label_margin=50)
            yaxisWidget = self.grid.add_widget(yaxis, row=2, col=1)
            yaxisWidget.width_min = yaxisWidget.width_max = 70
    
            # view
            self.view = self.grid.add_view(row=2, col=2, bgcolor=plotcolor, camera='panzoom')
            self.camera = self.view.camera
    
            xaxis.link_view(self.view)
            yaxis.link_view(self.view)
    
            self.freeze()
    
        def image(self, data, cmap='turbo', clim='auto'):
            image = scene.visuals.Image(data, cmap=cmap, clim=clim)
            self.view.add(image)
            self.view.camera.set_range(margin=0)
    
            return image
    
    
    arr = np.random.rand(100,150)
    
    canvas1 = scene.SceneCanvas(show=True)
    plt1 = Plot(padding=(0,0,0,25))
    img = plt1.image(arr)
    canvas1.central_widget.add_widget(plt1)
    
    app.run()
`

**Comment by juraj6** [comment]
And the reason why I'm doing this is the waterfall graph, where one axis must be a time axis.

**Comment by djhoese** [comment]
Off the top of my head:

```
from vispy.visuals.transforms import STTransform
image = scene.visuals.Image(data, cmap=cmap, clim=clim)
st = STTransform(scale=(200 / data.shape[1]))
image.transform = st
```

I think this should do *something* based on the code I'm reading. I'm not sure if there is an easier way in the plotting/widget system right now. This essentially says for every pixel coordinate in the X/column dimension, divide by the number of columns, then multiple by 200. Let me know if that works. It is possible this will make the labels correct but make the image super small.

**Comment by juraj6** [comment]
Yes, this works, thank you.
