### ISSUE TITLE
Create custom sphinx role to link to examples

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2024]
I was just working on #1689 and added some links to the examples. I realized this is very cumbersome, not super flexible, and isn't very nice to look at in the docstring source code. I'm thinking it would be great to create a custom role for the documentation like

```
:example:`basics/scene/mesh_shading.py`
```

This would just replace the text with a link to the example script on GitHub. It could even have support for `~` like the API references. For example, `~basics/scene/mesh_shading.py` could make the text just the "basics/scene/mesh_shading.py" test instead of the full URL. It could also support custom text so doing `Mesh Shading Example <basics/scene/mesh_shading.py>` would show "Mesh Shading Example" but link to the same GitHub page (I assume this <> is supported for any custom role). This is very similar to this sphinx example: https://protips.readthedocs.io/link-roles.html

In the future we could expand this functionality (either with another role or rewrite this one) to show a thumbnail of a gallery image for the example and allow you to click on the thumbnail to go to the source (or the thumbnail hover-window shows multiple links to source, gallery image, etc).

**Comment by djhoese** [comment]
Note this PR would mostly be done in https://github.com/vispy/vispy-website

**Comment by larsoner** [comment]
Have you considered using sphinx-gallery? A lot of this sort of stuff would come for free

**Comment by djhoese** [comment]
Considered it: Yes
Had time to actually do anything with it: No

**Comment by djhoese** [comment]
I assume you mean using something like https://sphinx-gallery.github.io/stable/advanced.html#cross-referencing

**Comment by larsoner** [comment]
SG automatically adds the full path as a link name in the RST when generating it from the Python code like:
```
.. _sphx_glr_auto_examples_plot_whatever.py:

Title
====
```
to each example so that the title of the example becomes a link so you can just do:
```
... see :ref:`sphx_glr_auto_examples_plot_whatever.py` ...
```
which will show up as `Title` with a link. And this is inter-sphinxable as `vispy:sphx_glr_auto_examples_plot_whatever.py` etc.

**Comment by djhoese** [comment]
Replaced by #2122.
