### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by theGiallo** [vispy/vispy#2044]
https://github.com/vispy/vispy/blob/081a1216e336e8c2c9aa4c61b926ba771bb5479f/vispy/glsl/math/double.glsl#L8

Link is dead. I presume the correct page is this one https://blog.cyclemap.link/2011-06-09-glsl-part2-emu/

**Comment by kmuehlbauer** [comment]
@theGiallo Time to make sure we have some link checks in place to get informed. Thanks for catching this. If you feel like fixing this, you might do it together with #2045. 

@rougier Could you check if this is the correct link (it looks very much like it). It seems that this was directly taken from glumpy (https://github.com/glumpy/glumpy/blob/45fb02d3f8365afe458a60a541bd175f49fe1a0e/glumpy/library/math/double.glsl) where #2044 is also still present) so it would need fixing there too.

**Comment by rougier** [comment]
The new link is correct (it can be reached from the former link actually).

**Comment by djhoese** [comment]
Does anyone have time to make a pull request for this?

**Comment by djhoese** [comment]
Fixed in #2050
