### ISSUE TITLE
Copy typo

### ISSUE THREAD

**Issue by theGiallo** [vispy/vispy#2045]
https://github.com/vispy/vispy/blob/081a1216e336e8c2c9aa4c61b926ba771bb5479f/vispy/glsl/math/double.glsl#L49

Return variable is a copy typo from [https://blog.cyclemap.link/2011-06-09-glsl-part2-emu/](https://blog.cyclemap.link/2011-06-09-glsl-part2-emu/), should be `result` and not `dsc`.

**Comment by kmuehlbauer** [comment]
@theGiallo Thanks for catching this. I've checked, the good thing is it's not used anywhere in VisPy currently. Are you aimed at fixing this? PR welcome.

**Comment by djhoese** [comment]
Closed by #2051
