### ISSUE TITLE
Axis out of sync with data

### ISSUE THREAD

**Issue by NicoliHCorrea** [vispy/vispy#2049]
Hi there! I need the axis to be synchronized with the data, so if the data is 0, the data line should be at 0 on the axis. This is not happening. Here is an MRE with a screenshot.
I started the data with np.zeros and then added the number 1 at every iteration.
You can see that they are not in the correct position:
![image](https://user-images.githubusercontent.com/58525689/120512776-058a4c80-c3a2-11eb-8b09-785305c6318b.png)
And when I resize the window, this happens:
![image](https://user-images.githubusercontent.com/58525689/120512881-19ce4980-c3a2-11eb-8236-9a73bbcd502e.png)
It's like the axis is just a line drawn on top of the canvas, but not actually working as an axis. 

Here is the code:

```
import vispy
from vispy import gloo, app, visuals
import NumPy as np
import math

nrows = 2
ncols = 1

m = nrows*ncols

n = 1000

y = np.zeros((m, n)).astype(np.float32)

color = np.repeat(np.random.uniform(size=(m, 3), low=.5, high=.9),
                  n, axis=0).astype(np.float32)

# Signal 2D index of each vertex (row and col) and x-index (sample index
# within each signal).
index = np.c_[np.repeat(np.repeat(np.arange(ncols), nrows), n),
              np.repeat(np.tile(np.arange(nrows), ncols), n),
              np.tile(np.arange(n), m)].astype(np.float32)

VERT_SHADER = """
#version 120
// y coordinate of the position.
attribute float a_position;
// row, col, and time index.
attribute vec3 a_index;
varying vec3 v_index;
// 2D scaling factor (zooming).
uniform vec2 u_scale;
// Size of the table.
uniform vec2 u_size;
// Number of samples per signal.
uniform float u_n;
// Color.
attribute vec3 a_color;
varying vec4 v_color;
// Varying variables used for clipping in the fragment shader.
varying vec2 v_position;
varying vec4 v_ab;
void main() {
    float nrows = u_size.x;
    float ncols = u_size.y;
    // Compute the x coordinate from the time index.
    float x = -1 + 2*a_index.z / (u_n-1);
    vec2 position = vec2(x - (1 - 1 / u_scale.x), a_position);
    // Find the affine transformation for the subplots.
    vec2 a = vec2(1./ncols, 1./nrows)*.9;
    vec2 b = vec2(-1 + 2*(a_index.x+.5) / ncols,
                  0);
    // Apply the static subplot transformation + scaling.
    gl_Position = vec4(a*u_scale*position+b, 0.0, 1.0);
    v_color = vec4(a_color, 1.);
    v_index = a_index;
    // For clipping test in the fragment shader.
    v_position = gl_Position.xy;
    v_ab = vec4(a, b);
}
"""

FRAG_SHADER = """
#version 120
varying vec4 v_color;
varying vec3 v_index;
varying vec2 v_position;
varying vec4 v_ab;
void main() {
    gl_FragColor = v_color;
    // Discard the fragments between the signals (emulate glMultiDrawArrays).
    if ((fract(v_index.x) > 0.) || (fract(v_index.y) > 0.))
        discard;
    // Clipping test.
    vec2 test = abs((v_position.xy-v_ab.zw)/v_ab.xy);
    if ((test.x > 1) || (test.y > 1))
        discard;
}
"""


class Canvas(app.Canvas):
    def __init__(self):
        app.Canvas.__init__(self, title='Use your wheel to zoom!',
                            keys='interactive')
        self.program = gloo.Program(VERT_SHADER, FRAG_SHADER)
        self.program['a_position'] = y.reshape(-1, 1)
        self.program['a_color'] = color
        self.program['a_index'] = index
        self.program['u_scale'] = (1., 1.)
        self.program['u_size'] = (nrows, ncols)
        self.program['u_n'] = n

        gloo.set_viewport(0, 0, *self.physical_size)

        self._timer = app.Timer('auto', connect=self.on_timer, start=True)

        gloo.set_state(clear_color='black', blend=True,
                       blend_func=('src_alpha', 'one_minus_src_alpha'))
        pos_yax = np.array([[35, 455], [35, 155]])
        self.axis_y = vispy.visuals.AxisVisual(pos=pos_yax, axis_color=(1, 1, 1), domain=(-1, 1))
        self.show()

    def on_resize(self, event):
        gloo.set_viewport(0, 0, *event.physical_size)
        self.axis_y.transforms.configure(canvas=self)

    def on_timer(self, event):
        """Add some data at the end of each signal (real-time signals)."""
        k = 1
        y[:, :-k] = y[:, k:]
        y[:, -k:] = 1

        self.program['a_position'].set_data(y.ravel().astype(np.float32))
        self.update()

    def on_draw(self, event):
        gloo.clear()
        self.axis_y.draw()
        self.program.draw('line_strip')

if __name__ == '__main__':
    c = Canvas()
    app.run()

```

**Comment by djhoese** [comment]
So at the heart of this odd behavior is that a lot of this stuff is typically handled for you in the SceneCanvas and its use of the `TransformSystem` (that `.transforms` that you're accessing on the axis visual). I understand you based this off of the realtime signals examples so this is the way it has to be right now. In the future using a LineVisual directly may be better when combined with a SceneCanvas. But let's get this working first.

The resize issue can be fixed if you remove the `axis_y` stuff in `on_resize` and instead move the `transforms.configure` right after the AxisVisual creation:

```python
        self.axis_y = vispy.visuals.AxisVisual(pos=pos_yax, axis_color=(1, 1, 1), domain=(-1, 1))
        self.axis_y.transforms.configure(canvas=self)
```

I'm still trying to figure out the small shift issue.

**Comment by djhoese** [comment]
Ah, your axis positions just aren't centered. Changing it to `pos_yax = np.array([[35, 450], [35, 150]])` works for me.

**Comment by NicoliHCorrea** [comment]
This helped me a lot. The positions that worked for me were [[35, 435], [35, 165]], now it's working the way that I need it. 
I don't fully understand why the position needs to be given by the user instead of the canvas just adjust it based on the data that is being plotted. 
Anyway, do you know if it's possible to change the font size? The numbers are really hard to read.

**Comment by djhoese** [comment]
That's the difficulty with working with the low-level gloo interface that this example is written in. There is no assumption about the connection of pieces. You the user must do it all. That's why the SceneCanvas interface and Plotting interface exist. They do this connection for you and try to make things convenient at the cost of complete flexibility.

As for font size, you should be able to use `tick_font_size` (https://github.com/vispy/vispy/blob/0206a2ce2a69231c6afa9ea04910960b392feb01/vispy/visuals/axis.py#L54-L55).

**Comment by NicoliHCorrea** [comment]
Understood! Thank you very much. It worked!
