### ISSUE TITLE
How can I put an Image in fullscreen?

### ISSUE THREAD

**Issue by NicoliHCorrea** [vispy/vispy#2073]
I have a scene.SceneCanvas with a scene.visuals.Image and I want this image to fill the whole canvas. I tried to resize it as I did with other canvases but it didn't work. 
This is how I would like it to be:
![image](https://user-images.githubusercontent.com/58525689/122106114-e652dc80-cdef-11eb-9ee6-fc1c77cda752.png)

This is how it's right now:
![image](https://user-images.githubusercontent.com/58525689/122106233-0aaeb900-cdf0-11eb-8847-1af60bfedb7a.png)

I can use my mouse to zoom in and move it, but it's not what I need, and even like this, it's not the whole canvas.
![image](https://user-images.githubusercontent.com/58525689/122106316-23b76a00-cdf0-11eb-98b1-a18a0b031a8c.png)

Here is the class definition:

```
class Viridis(scene.SceneCanvas):
    def __init__(self):
        self.data = np.array(np.random.rand(1, 100) * 255, dtype=np.float32)
        scene.SceneCanvas.__init__(self, keys='interactive', bgcolor='w', size=(600, 600))
        self.unfreeze()
        self.dados = fakedata.copy()
        self.view = self.central_widget.add_view()
        self.img = scene.visuals.Image(self.data, interpolation='nearest', cmap='cubehelix', parent=self.view.scene,
                                       method='subdivide')
        s = (1 / (self.size[0] * self.img.size[0] / (self.size[0] * 2)),
             (1 / (self.size[1] * self.img.size[1] / (self.size[1] * 2))))
        self.img.transform = STTransform(scale=s, translate=(-1, -1))
        self.view.camera = scene.PanZoomCamera(aspect=1)
        self.view.camera.flip = (0, 1, 0)
        self.view.camera.set_range()
        self.view.camera.zoom(1, center=(700, 400))
        self.title = 'Viridis image'
```

**Comment by djhoese** [comment]
I don't have time to test the code right now, but what happens if you take the transform off the `self.img` (comment that line out) and comment out the `zoom` call. By default an ImageVisual should fill the whole canvas...I think. Also, your `self.data` in the code above is only 1x100 right? Could you create an example that creates a full image?

**Comment by NicoliHCorrea** [comment]
This is what happens 
![image](https://user-images.githubusercontent.com/58525689/122249257-10afa300-ce9f-11eb-992c-c471320c9e36.png)

While trying to create a MRE I accidently got exactly what I needed, I don't know exactly what happened, but it worked.

**Comment by djhoese** [comment]
So...this can be closed? :smile:
