### ISSUE TITLE
overlapping ImageVisuals with alpha channel are not displayed as expected

### ISSUE THREAD

**Issue by flylover88** [vispy/vispy#2080]
I would like to create a scene with 2 or more overlapping images using the `Image()` class, using the alpha channel to mask out portions of the images. As an example I have two images in my scene with a small overlap in the corner. I set the alpha channel of this corner of one of the image to 0. With this I would expect to see only the other image in this corner, but what is displayed is the background. Here is my code sample: 

```
from vispy import scene, app
from vispy.visuals.transforms import STTransform
import numpy as np

image_1 = np.ones(shape=(100, 100, 4), dtype='uint8') * 255
image_1[..., 0] = 0
image_1[-25:, -25:, 3] = 0

image_2 = np.ones(shape=(100, 100, 4), dtype='uint8') * 255
image_2[..., 2] = 0

s = scene.SceneCanvas(title='actual')
view = s.central_widget.add_view()
im1 = scene.visuals.Image(image_1, parent=view.scene)
im2 = scene.visuals.Image(image_2, parent=view.scene)
im2.transform = STTransform(translate=(75, 75))

s.show()
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        app.run()
```
which produces the following canvas:
![image](https://user-images.githubusercontent.com/46579011/122468467-c0613f80-cf89-11eb-8b7c-cc7aae9a8626.png)

This is the canvas that I would expect/want:
![image](https://user-images.githubusercontent.com/46579011/122468668-fef6fa00-cf89-11eb-97b2-ce40501a4129.png)

The ability to blend images like this would be great for my workflow. I saw #1345 so I am not sure if this is being actively worked on or if there is a solution for my particular needs that I am missing. Any help would be greatly appreciated.

**Comment by djhoese** [comment]
So I'm a little surprised by how hard this was to get working. My initial thought was "oh you need to adjust the transform so they are on different Z levels. But doing that didn't change anything. I also saw weird behavior as I kept investigating where the cyan image would just disappear. I've seen some weird behavior like that before with transform systems not being setup completely so I added a panzoom camera. I then settled on forcing the drawing order which fixes the issue. You could do this either by adding the images to the scene from "back" Z level to "front" Z level or by using `.order = N` to force it.

```python
from vispy import scene, app
from vispy.visuals.transforms import STTransform
import numpy as np

image_1 = np.ones(shape=(100, 100, 4), dtype='uint8') * 255
image_1[..., 0] = 0
image_1[-25:, -25:, 3] = 0

image_2 = np.ones(shape=(100, 100, 4), dtype='uint8') * 255
image_2[..., 2] = 0

s = scene.SceneCanvas(title='actual')
view = s.central_widget.add_view()
view.camera = 'panzoom'
view.camera.set_range(x=(-100, 100), y=(-100, 100))
im1 = scene.visuals.Image(image_1, parent=view.scene)
im2 = scene.visuals.Image(image_2, parent=view.scene)
im2.transform = STTransform(translate=(60, 60, 100))
im2.order = 1
im1.order = 2

s.show()
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        app.run()
```

It's been a long day so I'm sure I'm missing something obvious here, but order is typically our last resort for fixing drawing order and transparency issues (that and `my_visual.set_gl_state(...)` changes). At least you have a work around for now.

**Comment by asnt** [comment]
@djhoese @flylover88 Very useful!

@djhoese Could we make this an entry in the FAQ or rather an example in the repo? Or both?

**Comment by djhoese** [comment]
I like the FAQ option.

**Comment by flylover88** [comment]
@djhoese Thank you for the quick response! I am sorry for piling on after a long day. The solution you gave worked well for that particular example, but I am afraid that I did a poor job of capturing the full problem with my minimal example. Once I took your example and extended to 4 images in a 2x2 array with all images having portions masked out via alpha channel the drawing order does not seem to work (unless I am wrong in my understanding of drawing order, but I tried many different orders and no combination worked). Here is the example code:
```
from vispy import scene, app
from vispy.visuals.transforms import STTransform
import numpy as np

image_1 = np.zeros(shape=(100, 100, 4), dtype='uint8')
image_1[..., 0] = 255
image_1[25:-25, 25:-25, 3] = 255

image_2 = np.zeros(shape=(100, 100, 4), dtype='uint8')
image_2[..., 1] = 255
image_2[25:-25, 25:-25, 3] = 255

image_3 = np.zeros(shape=(100, 100, 4), dtype='uint8')
image_3[..., 2] = 255
image_3[25:-25, 25:-25, 3] = 255

image_4 = np.zeros(shape=(100, 100, 4), dtype='uint8')
image_4[..., :3] = 255
image_4[25:-25, 25:-25, 3] = 255

s = scene.SceneCanvas(title='actual')
view = s.central_widget.add_view()
view.camera = 'panzoom'
view.camera.set_range(x=(-100, 100), y=(-100, 100))
im1 = scene.visuals.Image(image_1, parent=view.scene)
im2 = scene.visuals.Image(image_2, parent=view.scene)
im2.transform = STTransform(translate=(0, 50, 100))
im3 = scene.visuals.Image(image_3, parent=view.scene)
im3.transform = STTransform(translate=(50, 0, 100))
im4 = scene.visuals.Image(image_4, parent=view.scene)
im4.transform = STTransform(translate=(50, 50, 100))

im4.order = 1
im3.order = 2
im2.order = 3
im1.order = 4

s.show()
if __name__ == '__main__':
    import sys
    if sys.flags.interactive != 1:
        app.run()
```
and the resulting canvas (shifted to better show squares)
![image](https://user-images.githubusercontent.com/46579011/122615359-68dcd580-d056-11eb-92bf-c1d31fe39bcb.png)

and this is the image I expected:
![image](https://user-images.githubusercontent.com/46579011/122615672-e6a0e100-d056-11eb-9346-0b756922c8bd.png)

Again thank you for taking the time to help me through this issue!

**Comment by djhoese** [comment]
All your visuals are at the same Z level so how that gets drawn is kind of an undefined behavior OpenGL-wise (at least that's my understanding). Try setting the Z position in your transforms for each so they aren't all at the same level. See this FAQ that @asnt is working on about the issue for more information: https://github.com/vispy/vispy-website/pull/35/files

**Comment by flylover88** [comment]
Awesome! that worked perfectly. Thank you for clarifying!

**Comment by djhoese** [comment]
So I think you've solved this so I'm going to close it. We've also just merged a PR to `main` that should make transparency more predictable when saving screenshots. I'm mentioning it in case someone finds this issue in the future. If you @flylover88 feel this issue is not resolved feel free to comment why and we can reopen it. Otherwise, others finding this issue, please open a new one instead of commenting here.
