### ISSUE TITLE
Qthread, Animations, Scatter 

### ISSUE THREAD

**Issue by rsinghoyla** [vispy/vispy#2086]
I am using vispy 0.6.6 with PyQt5 as the backend for a GUI app.

GUI displays temporal frames of point cloud data (each frame being ~250K points) with incoming frame rate ~10 FPS. 

Point cloud data is loaded from files, processed etc and then visualized using scatter plot.

There are bunch of GUI elements including Pause/Play etc. These have been written using Qt. 

A QtThread loads data and emits signal, data is processed (very light weight) and then scatter.set_data is used  to set the data for the current frame and then canvas.update is called. 

I can reduce the resolution of point cloud to around 80K and this works well, but for original resolution, 250K, the GUI hangs. 

I have written a vispy application that does not use Qt elements, or signals, but loads the data (at 250K resolution), and uses app.Timer (auto) and everything works.

I am unable to debug the GUI hanging problem -- is the problem with Qthreads, or that I am not using app.Timer? My understanding is that QThreads signals that data is ready and hence I am currently using data rate. On the other hand if I used app.Timer then I am using the desired frame rate. Is there a way to use Qthread signal and on_timer in the same code?

Thanks!

**Comment by djhoese** [comment]
I'm very surprised that the timer approach doesn't hang. As for using threads and on_timer, I think you could do it all in "Qt-land" in the secondary thread where the timer is technically running from that worker thread, but I don't think you can guarantee frame rate (it would be close). You could also have a shared array between the background thread and the main thread and put a lock on it. The background thread is constantly updating the shared data and the GUI thread updates the visualization based on a timer, but the two threads use a lock (I think Qt has a QLock for use with their threads) to make sure there are no conflicts (writing while reading, etc).

My guess on performance issues, especially if the timer approach works fine but the thread approach doesn't, is that there is a data copy happening somewhere that is wasteful. In your signal, are you signaling that the data is ready and the GUI thread looks at some shared array? Or are you sending the actual array over the signal? I'm not sure how Qt handles sending generic python objects over signals (copies or shared memory pointer).

**Comment by Oyla-Inc** [comment]
Thank you. Your second paragraph makes total sense and I think I might be doing something wrong there.

As far as the paragraph I kinda understand what you are saying and I am trying to do something using Queue but I will take a look at Lock and arrays.

Thanks!!!

**Comment by rsinghoyla** [comment]
Thank you! Your second paragraph makes total sense and its something I am trying to resolve.

I kinda understand your first paragraph point but I have not been able to get Qt Signals and on_timer to work together as of now. 

Thank you!
ps I may reopen if I have more detailed question

**Comment by djhoese** [comment]
Just a little bit more detail on paragraph 1: it would essentially look like this two stage process:

### QThread

1. Receive new data
2. Use a thread "lock" (common threaded programming practice) to claim "ownership" of some shared memory.
2. Write data to shared memory/array
3. Unlock the lock to mean "I'm no longer modifying the data, do what you wish with it"

### Main GUI Thread

1. Start timer with "best case" trigger interval for desired frame rate
2. Timer callback will acquire the thread lock saying "I want to use this data right now, don't change it"
3. Callback function calls `.set_data` on the visuals, then `canvas.update()` or however you want to tell the visualization to be drawn.
4. Callback releases the lock

There might be some special cases here or race conditions. There might also be problems if the thread doesn't know what to do when the lock is acquired for too long and it has a backlog of data it wants to update.

...just some ideas. Good luck. Thanks.
