### ISSUE TITLE
Unexpected lighting behavior in the basics/visuals/tube.py example

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#2087]
The lighting does not change with the camera, but I think it should. May be part due to the geometry, see #2069, but I suspect the calculation of the light and view vector might be wrong too.

**Comment by almarklein** [comment]
Before I dive in, the light is supposed to be coming from the view-direction, right?

**Comment by almarklein** [comment]
Nevermind, somehow I overlooked that `ShadingFilter` has a `light_dir` argument.

**Comment by asnt** [comment]
The light is fixed in space as you noticed. This was the behaviour before the ShadingFilter as well.

Maybe your issue is with the ambient light? I know realise that there was a default ambient light before the filter, that is now off by default in the filter. So the tube appears black at the back. Moreover, the current ambient component doesn't act on the base color, which it was before. I hesistated during the creation of the filter and finally removed it. Will do PR to see the change it brings.

**Comment by almarklein** [comment]
I was triggered because I expected the light to follow the camera view. Because I saw nothing of a light direction in the example, I was confused. So maybe a spinoff question is: should we support camera-lights (e.g. by setting light-dir to `(0,0,0)`) and make it the default?

But also, after closer inspection, I'm pretty sure the specular reflection is off because of a faulty view_dir.

**Comment by asnt** [comment]
> I was triggered because I expected the light to follow the camera view. Because I saw nothing of a light direction in the example, I was confused. So maybe a spinoff question is: should we support camera-lights (e.g. by setting light-dir to `(0,0,0)`) and make it the default?

I like the idea. It seems like a good default that make things more intuitive.

> But also, after closer inspection, I'm pretty sure the specular reflection is off because of a faulty view_dir.

Indeed. Undoing [this commit](https://github.com/vispy/vispy/commit/549a705a5217b43debb5b451ebe92f9a49553d39) seems to resolve this issue, but I proposed it to fix another issue.

@almarklein I am not sure to understand exactly the computation of the normals and the viewing direction, starting from [here](https://github.com/vispy/vispy/blob/e49191516046572bad1a1ac977e401f6eb8a7c99/vispy/visuals/filters/mesh.py#L130).

**Comment by almarklein** [comment]
This is solved.
