### ISSUE TITLE
PanzoomCamera produces an un-invertable matrix

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2093]
Tests on CI are now failing with:

```
   File "/home/runner/work/vispy/vispy/vispy/scene/cameras/panzoom.py", line 195, in viewbox_resize_event
    self.view_changed()
  File "/home/runner/work/vispy/vispy/vispy/scene/cameras/base_camera.py", line 437, in view_changed
    self._update_transform()
  File "/home/runner/work/vispy/vispy/vispy/scene/cameras/panzoom.py", line 291, in _update_transform
    self.tf_mat.matrix = self.transform.as_matrix().matrix
  File "/home/runner/work/vispy/vispy/vispy/visuals/transforms/linear.py", line 219, in as_matrix
    m.scale(self.scale)
  File "/home/runner/work/vispy/vispy/vispy/visuals/transforms/linear.py", line 445, in scale
    self.matrix = np.dot(self.matrix, scale)
  File "/home/runner/work/vispy/vispy/vispy/visuals/transforms/linear.py", line 401, in matrix
    self.shader_imap()
  File "/home/runner/work/vispy/vispy/vispy/visuals/transforms/linear.py", line 389, in shader_imap
    fn['inv_matrix'] = self.inv_matrix  # uniform mat4
  File "/home/runner/work/vispy/vispy/vispy/visuals/transforms/linear.py", line 407, in inv_matrix
    self._inv_matrix = np.linalg.inv(self.matrix)
  File "<__array_function__ internals>", line 6, in inv
  File "/home/runner/micromamba/envs/vispy-tests/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/runner/micromamba/envs/vispy-tests/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

**Comment by djhoese** [comment]
To be more specific, this example is now failing: `/basics/plotting/scatter_histogram.py`

**Comment by asnt** [comment]
Is it expected that the transformation be singular, e.g. scale is zero in one dimension?
Not sure it solves the ground issue here but `np.linalg.pinv` would return the closest thing to an inverse.

**Comment by djhoese** [comment]
How do you know the scale is zero? I tried updating my numpy to 1.21 and am not able to reproduce this running this example on my local machine.

**Comment by djhoese** [comment]
Also I should note that from what I could tell numpy didn't change anything related to `linalg` in this last release.

**Comment by djhoese** [comment]
My current best guess for this is that the transforms/scales are being set incorrectly based on some initial value that is the result of there being no display so possibly a window with no size.

**Comment by almarklein** [comment]
I think that test does not fail consistently. When I re-rerun CI it usually passes. So there seems to be a random aspect to it. Nevertheless, this seems to happen only since a few days or so.

**Comment by asnt** [comment]
> How do you know the scale is zero? I tried updating my numpy to 1.21 and am not able to reproduce this running this example on my local machine.

This was just an example why the matrix would be singular, e.g. given this line `self.matrix = np.dot(self.matrix, scale)`. And as you said above, suspecting that parameters might not be initialised or initialised to unphysical values.

**Comment by asnt** [comment]
> I think that test does not fail consistently. When I re-rerun CI it usually passes. So there seems to be a random aspect to it. Nevertheless, this seems to happen only since a few days or so.

I cannot replicate locally either.

**Comment by almarklein** [comment]
I'll see if I can find something suspicous (like `np.empty`?) in the test ...

**Comment by almarklein** [comment]
I am actually able to reproduce this if I run the example `basics/plotting/scatter_histogram.py` a couple of times.

**Comment by almarklein** [comment]
I did manage to salvage the matrix that caused the errror:
```py
import numpy as np

matrix = np.array([[2.52820244e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 9.99999997e-07, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

np.linalg.inv(matrix)
```

I verified that fails in both numpy 1.19.5 (what I was previously using) and numpy 1.21.0 (the latest). This suggests that it's not `np.linalg` that got more strict or something. Either this potential bug was there the whole time, or *something* changed that is causing the matrix can get these values.

**Comment by almarklein** [comment]
Could this have been introduced by #2079?

**Comment by djhoese** [comment]
What about #1501?

**Comment by almarklein** [comment]
> What about #1501?

Bingo!

I wrote a little script that runs the example in a while loop. In the last merge before #1501 it runs until 99 without problems. The merge commit of the PR produces the error regularly.

Any idea what change in that PR could be causing it?

**Comment by djhoese** [comment]
Well that is the entire system that determines the gridding of the plots in the Canvas. We switched from cassowary to kiwisolver which does the math to determine how much space each "box" should get to solve a set of constraints. It isn't surprising that it is the cause, but I'm surprised that it isn't always failing.

**Comment by djhoese** [comment]
I guess I should say I'm not surprised such a huge change would cause issues, but I'm surprised it is producing an invalid transform/scale in the PanZoomCamera's transform. I didn't think the PanZoomCamera adjusted itself to changes in the "size" of the elements in the Canvas, but I could be wrong.

**Comment by almarklein** [comment]
Well the camera's transform has a component that includes the viewport size, which is determined by the grid solver ...

**Comment by almarklein** [comment]
That example has three plots (one in the center and two on the bottom and right side. I now have a case open where the viewport of the bottom one is collapsed into zero height. I can fix this by making sure in the camera code that the viewbox is at least one pixel, which should fix the error being raised, but we should probably look into the grid code too.

**Comment by djhoese** [comment]
Without knowing anything about the grid "stuff", I would think we could make a constraint for this 1 pixel minimum size. I just don't know how.

**Comment by djhoese** [comment]
@almarklein What if you update these to be `>` instead of `>=`?

https://github.com/vispy/vispy/blob/89e83cabea4e0e6ae08df5012985e816009924aa/vispy/scene/widgets/grid.py#L390-L391

Does that change your testing?

**Comment by almarklein** [comment]
I've got that bit covered :) 270+ iters without errors.

**Comment by almarklein** [comment]
> Does that change your testing?

Thanks for the suggestions. Let's try ...

**Comment by djhoese** [comment]
See #2100 for the right solution...I hope.
