### ISSUE TITLE
Squash-merge PR's?

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#2101]
In a few other projects I have experienced working with squash-merging all PR's, and have grown to like it. A big advantage is that the history of the `main` branch becomes *a lot* more clean and easier to checkout certain commits because each PR is "atomic" there. And in the PR's itself you don't have to worry about making too small or too many commits. It may also nudge people to make smaller (better confined) PR's, which are easier to review.

Is this an approach we could conciser adopting?

**Comment by kmuehlbauer** [comment]
My experiences are similar. I'd second this.

**Comment by djhoese** [comment]
I mostly agree with this. I don't know if I'd say every PR should be squashed. You lose a lot of history if you do that and I'd be worried that we'd lose some information about different attempts for doing things that were changed. I will try to be better about making smaller PRs and squashing when I think it makes sense (which is most cases).

**Comment by almarklein** [comment]
You can always open the PR (which is linked in the commit message!) and see all original commits.

**Comment by djhoese** [comment]
Good point. I think the 3 of us (and @larsoner ) are the usual few to merge commits. I think we can agree that most of my recent merges could have been squashed and we can all try to do that more in the future. I'll close this as I think the discussion has yielded agreement.
