### ISSUE TITLE
Request for testers for VisPy 0.7

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2104]
Hi everyone! We are getting ready to release VisPy 0.7. This is another **HUGE** release and includes changes anywhere from performance improvements, to obvious bug fixes, to near-total rewrites of some of the major Visuals like the ImageVisual, VolumeVisual, and MeshVisual. We're looking for anyone who can help us test this new version and let us know of any unexpected results or issues. We have only a few small changes remaining, but they shouldn't effect the basic testing needed for this release.

I'm hoping at least some of the napari folks will have time in the next day or two to do some minimal testing with napari.

CC @jni @sofroniewn @alisterburt @tlambert03 @kne42 

Thank you all for any help you can provide.

**Comment by vitsensei** [comment]
Is this something that people who are not heavily involved in the project can help with?
I'm happy to help during this lock down!

**Comment by djhoese** [comment]
@vitsensei All help is appreciated!

**Comment by sofroniewn** [comment]
Both @alisterburt and I have down done some fairly extensive usage and testing in napari with vispy master (0.7) and no longer have any problems, so i think we'll be good for a seamless transition. I'm only using vispy master (0.7) locally now. If you make an `0.7.0rc0` release candidate available on PyPI we will test against that in our CI test against upstream release candidates. That would probably be best for us as then we'll really make sure all systems and all tests are passing. Thanks for all the hard work here @djhoese! I think we'll be able to trim quite some vendored napari code after the release too!!

**Comment by kmuehlbauer** [comment]
Not sure if I suggested this before, but we could think about uploading every push to main to `testpypi`. So everyone has easy access to published commits via `testpypi`.

**Comment by djhoese** [comment]
@kmuehlbauer does testpypi accept the version numbers we're generating with commit hashes in them? Does pip know what to do with that? PRs for the github workflow are welcome and something added to the contributor's guide would be nice.

**Comment by kmuehlbauer** [comment]
@djhoese I'm doing this in one of the packages I maintain. Not with commit hashes, but that should work too. I'll get to this the next days.

**Comment by djhoese** [comment]
One thing that will be a little awkward is that our setuptools_scm usage can only detect some tags...it seems. So even though we have a 0.6.6 release of VisPy, it only sees the 0.6.5 tag on my local system. Regardless, this would likely mean the version numbers going to test PyPI might be something like: `vispy-0.6.5.dev718+g79c8f2ab`.

@sofroniewn I'm about to merge #2106 (waiting on tests) and then I would consider the `main` branch ready for release. If I put an sdist of the current main branch on test pypi would you have time today to run napari tests against it? Would a wheel be easier? I can try doing what @kmuehlbauer is talking about since I also do something similar in some of my other projects but we only do it on tags, not all commits.

**Comment by djhoese** [comment]
Options:

1. Change the versioning scheme to be PEP440 compliant: https://www.python.org/dev/peps/pep-0440/ at the loss of information in the version number.
2. Only push to test pypi on tags (ex. `v0.7.0a0`) and only push to main pypi on github releases.

@almarklein @kmuehlbauer Thoughts?

**Comment by kmuehlbauer** [comment]
OK, so that doesn't work. Couldn't we just remove the hash?

**Comment by djhoese** [comment]
I think so. I'm re-reading the setuptools_scm docs to see what our options are and what is easiest.

**Comment by djhoese** [comment]
Ok I'm glad I figured out the easy way of doing this because I was about to start creating entry_points in the setup.py and pyproject.toml. It was easier than that. I pushed my changes directly to main, deal with it:

https://github.com/vispy/vispy/commit/44c22a4aa1f4cf70681d7d608b95f22644d4dcb7

This should, based on local testing, either produce version numbers of:

1. Tagged released: `vispy-0.7.0.tar.gz`
2. New commits: `vispy-0.7.0devN.tar.gz` where `N` is some positive integer
3. New commits with uncommitted changed: `vispy-0.7.0devN+dirty.tar.gz` (or if no new commits then `vispy-0.7.0+dirty.tar.gz`.

Let's see how the GH actions go...

**Comment by djhoese** [comment]
It works! I need to update the installation instructions but @sofroniewn you should be able to do:

```
pip install --pre -i https://test.pypi.org/simple/ vispy
```

@kmuehlbauer @almarklein Any reason to keep these on test pypi instead of the main pypi? I feel like test pypi is more about testing your workflow, not for test versions of the package.

**Comment by djhoese** [comment]
I'm not sure what my schedule looks like later this afternoon and the rest of the week and I'm taking next week off so I'm going to take a break for lunch and start the 0.7 release process in ~2 hours. Any objections?

**Comment by djhoese** [comment]
Version 0.7.0 tag has been pushed...let's see what breaks.

**Comment by djhoese** [comment]
Version 0.7.0 is out on PyPI! Waiting for conda-forge to pull in the new version. Closing this. Feel free to comment still about the topics discussed here.

**Comment by tlambert03** [comment]
congrats @djhoese!  and thank you as always for all that you do :)

**Comment by sofroniewn** [comment]
Congrats on the release! Very exciting!!

**Comment by alisterburt** [comment]
Congratulations @djhoese and co! 🎉

**Comment by almarklein** [comment]
> Any reason to keep these on test pypi instead of the main pypi?

Maybe pushing to pypi on each commit would not be too friendly for pypi, storing all those blobs etc.? Doesn't testpypi delete all blobs after a certain amount of time? Anyway, just a gut feeling.

**Comment by kmuehlbauer** [comment]
> Maybe pushing to pypi on each commit would not be too friendly for pypi, storing all those blobs etc.?

We could automate this a bit by adding a specific label to the pull request (eg `upload_testpypi`) and only upload when that label is set. So we can decide before merge, if we need this on pypi or not.

**Comment by djhoese** [comment]
I think you can do manual github action jobs. I'm not sure how they work, but that could be an easy way for maintainers to just say "we're at a good stage, put out a test package". Otherwise, if we're doing commit labels we could just do alpha/beta/rc git tags and have the packages go to PyPI.

**Comment by kmuehlbauer** [comment]
> I think you can do manual github action jobs. I'm not sure how they work, but that could be an easy way for maintainers to just say "we're at a good stage, put out a test package".

That would be possible for sure.

> Otherwise, if we're doing commit labels we could just do alpha/beta/rc git tags and have the packages go to PyPI.

I did not mean commit labels, but just tag the pull request with a label (a label like `build`, `code-quality`, `hacktoberfest`).

**Comment by djhoese** [comment]
Oh! So the label gets applied to the PR, the PR gets merged and a GH action sees the label from the PR and enables the upload job? If that works that would be kind of cool. The only downside is it depends on a pull request to be done and has to be done before the pull request is merged, right?

**Comment by kmuehlbauer** [comment]
Exactly that is what I think should work. But yes, there has to be a PR and the label has to be applied before merge. I think your idea of a manual github action which only uploads to pypi is the better approach.

**Comment by almarklein** [comment]
I also like the git tag idea. Then if someone reports an issue of such an in-between release, we can easily `git checkout` it.

**Comment by djhoese** [comment]
Tags and "actual" version numbers might be good for napari too so that one of their PRs could refer to a specific version. Would also be easier to announce to people if we give them traditional alpha/beta/rc numbers. If we go with this more manual process then I vote for putting them on regular PyPI. I'm not sure any of our release process depends on version numbers not including a/b/rc.

I'm also not a fan of what some projects do where they make a/b/rc releases and update their release notes for every pre-release version. It makes it harder for me, the user, to figure out what the stable version includes.

**Comment by almarklein** [comment]
There are probably some tasks (including release notes) that we could do only on regular releases (non-alpha/beta/rc), so that these "in-between" releases are not much more than a `git tag` and `git push`.
