### ISSUE TITLE
LineVisual line smooth and width set after GL state is configured

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2109]
In #2082 @almarklein updated the line visual to call `self.update_gl_state` to change `line_smooth` and `line_width`. The problem is, as I just realized while debugging #2107, that `update_gl_state` doesn't have an immediate effect on GL state. Only when `Visual._configure_gl_state` does the lower-level `gloo.set_state` call get executed. That happens on every `Visual.draw` call *BUT* before `_prepare_draw` is called. `_prepare_draw` is when these line smooth/width changes happen.

https://github.com/vispy/vispy/blob/184d854c7542f4c6df21bb4c7db3dd5b340dd900/vispy/visuals/visual.py#L442-L444

**Comment by djhoese** [comment]
I'm kind of wondering if there are reasons GL state needs to be configured *before* `_prepare_draw`. I can only see `TextVisual` needing this, but it could run that manually if it really needs to. Right now this current behavior means that Visuals GL state is sent/configured on the GPU regardless of if its `_prepare_draw` thinks it should be drawn.

**Comment by asnt** [comment]
> I'm kind of wondering if there are reasons GL state needs to be configured _before_ `_prepare_draw`. I can only see `TextVisual` needing this, but it could run that manually if it really needs to. Right now this current behavior means that Visuals GL state is sent/configured on the GPU regardless of if its `_prepare_draw` thinks it should be drawn.

I was wondering the same. It seems it can be moved down.

**Comment by djhoese** [comment]
I think the one issue may be if the `_prepare_draw` was doing something that depended on the GL state, but I can't think of anything right now. TextVisual is a special case as I mentioned because it has the option of drawing the glyphs on the CPU or GPU and has to change the GL state to due that properly (based on what I saw in the code).

**Comment by djhoese** [comment]
@asnt or @almarklein if either of you want to make a PR that moves the configure call to below the `_prepare_draw` I'd be OK with that. I guess we could assume that if the tests pass then it is an OK change... :fearful:

**Comment by djhoese** [comment]
Let's see what happens in #2111. I thought of some reasons why this might not work and why `_prepare_draw` needs the configuration beforehand.
