### ISSUE TITLE
New Jupyter widget

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#2127]
I'm working on a new implementation of the Jupyter widget. Basically a revival of the "vnc appproach", where the rendering takes place at the server, png's are send to the browser, and the browser sends events to the kernel.

The idea is to make this a separate project/library, that can also be used by other projects. This should also make Vispy's build process easier, if we decided to drop the webgl-based widget.

I have some progress on the code, and would like to put it in a repo. Right now I've called it `jupyrerfb` where `fb` stands for "frame buffer" (and the last `r` could stand for remote), because it's essentially a remote framebuffer solution. I think "vnc" refers too much to the specific application rather than the technology. Any other ideas for a name?

cc @rossant

**Comment by almarklein** [comment]
More specifically, the idea is to provide a base class that does all of the work, that can be easily subclassed/wrapped in vispy and other projects.

**Comment by rossant** [comment]
Very interesting @almarklein thanks for working on this!
I think it would be a great feature for Datoviz too.
If you have time to do some research on this: I would suggest to look into existing video streaming compression algorithm/libraries, especially those that target synthetic images compared to realistic videos. That might provide a way to significantly improve the performance of this approach.

**Comment by djhoese** [comment]
How does this new project compare to the other streaming/video jupyter widgets that already exist out there? What are you doing differently that shouldn't depend on these other existing tools or be contributed back to these projects? A couple of these technologies were mention in #134.

As for the name, is that a typo or is it really `jupyrer` instead of `jupyter`? If this is jupyter-specific then I personally think the name should be `jupyter-something`. Being easy to pronounce would be nice too. This could either be implemented as one project/library that does everything without jupyter and another that adds the jupyter widget wrapper around the first library or one library that combines both of these (functionality and widget).

**Comment by rossant** [comment]
I think having a Jupyter-independent module (in addition to a Jupyter widget leveraging that module) would be great, if possible.

**Comment by almarklein** [comment]
> I would suggest to look into existing video streaming compression algorithm/libraries

Yest, that would be very interesting, though might also pull in more complex dependencies. There might also be gains by working with keyframes and diffs to that. In all of this, it is crucial to first establish where the bottlenecks are. So let's first get it up and running :)

As a side-note, I worked on image/volume rendering in plotly/dash half a year ago, and what we found there is that turning an image into an inline (base64) png is surprisingly efficient, both in memory and especially in speed of display in the browser.

> How does this new project compare to the other streaming/video jupyter widgets that already exist out there?

I did do a quick search, and did not find a close existing solution, though I had overlooked the mention of ipycanvas in #134. I looked into it just now, and it has a much broader scope than what we need (a full canvas api). By focusing on the simple task of sending images one way, and events the other, we can also optimize this easier, e.g. with diff images and/or time-based compression like Cyrille mentioned. It is similar to what the VTK ipywidget does, but more generic (usable for vispy, datoviz, pygfx, etc), and we can probably make it faster.

> As for the name, is that a typo or is it really jupyrer instead of jupyter?

Yes, that was a typo. Yes, jupyter-something would be clearer. I also don't like that `fb` reminds me of some particular company.

I think "jupyter-rfb" would already be more clear, but not pronouncable. Maybe "jupyter-stream"?

> I think having a Jupyter-independent module (in addition to a Jupyter widget leveraging that module) would be great, if possible.

Well, the fact that ipywidgets is handling the IO is great. I don't wanna mess with websockets, at least not at this stage. I used the ipywidgets coockie-cutter, so it should be usable in the notebook, in jupyter lab, and as static html (export?). Anyway, I do try to separate concerns, so that splitting the code later should not be too hard.

**Comment by almarklein** [comment]
BTW, got my first rendering of a wgpu example (I picked wgpu first because I know that code-base best):
![image](https://user-images.githubusercontent.com/3015475/124155820-2fb15600-da97-11eb-8a2f-e2f546567f86.png)

**Comment by almarklein** [comment]
Still WIP, but I created the repo: https://github.com/vispy/jupyter_rfb

**Comment by almarklein** [comment]
Progress:
![animation2](https://user-images.githubusercontent.com/3015475/126013719-946cbbf1-9420-4939-8826-93a1f221add8.gif)
