### ISSUE TITLE
ImageVisual fails if data is all NaN

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2129]
In my application I need to temporarily fill the texture (ImageVisual) with invalid data. I'd like if it showed up as transparent which I think I can handle with a custom shader, but the new NaN/Inf handling in the new scalable textures does not allow this for `clim='auto'` cases. I end up getting:

```
       ValueError: zero-size array to reduction operation minimum which has no identity
```

The reason is pretty obvious when looking at the code:

https://github.com/vispy/vispy/blob/d313742a00da77deaa8e1696d7fa74dc4aad19bc/vispy/visuals/_scalable_textures.py#L38-L40

If none of the data is finite then `data[np.isfinite(data)]` returns an empty array and the min/max fail after. I think a better behavior may be to check for a `0` size and return `0, inf`? Or maybe `-inf, inf`?

**Comment by almarklein** [comment]
These `NaN` continue to hunt us. I guess that's what they do ...

**Comment by djhoese** [comment]
Yeah...it's just new bugs with new features. What do you think on the returned clims for all-Nan/all-Inf data? I guess it could be `-inf, inf` or maybe even `nan, nan`...maybe.

**Comment by almarklein** [comment]
It does not even matter much, does it, since all NaN's will be discarted or snap to the lower clim anyway. Maybe we should aim for the clim values to be finite, so  perhaps `(0, 0)`?

**Comment by djhoese** [comment]
Yeah I suppose that fits with the general idea of what you would get if you did min/max on data that was all the same. Leaves it up to the specific texture subclass on how it wants to handle the equal clims. I'll try making a PR tonight or tomorrow.

**Comment by almarklein** [comment]
>  I'll try making a PR tonight or tomorrow.

already on it
