### ISSUE TITLE
Dropping the webgl backend

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#2130]
When #2127 gets done, we might consider dropping the webgl backend. For one it would avoid the limitations of GL es 2.0, which we already violate in a few places (e.g. 3d textures, special texture formats). Further it may allow us to drop/simplify GLIR. Any other things that dropping the webgl backend would make easier?

On the other hand, do we expect that people who now use the webgfl backend be happy enough with the new Jupyter widget?

Thoughts?

**Comment by djhoese** [comment]
In the documentation for the installation of the backend and if just about every issues/gitter message/conversation I've had with people about the vispy jupyter widget for the last 3 or more years I've said the widget/backend should be considered experimental and should not be used for production/operational use. It is, in my opinion, as described in the roadmap, that VisPy will drop GL 2.0/ES support as we move forward. It just doesn't make sense for us as a project to continue supporting it. We can't talk a big game about fast visualizations and large amounts of data and still target mobile and web platforms that are limited to these versions of OpenGL. Not to mention, the current widget is just not good. I don't know what happened in jupyter or vispy, but it just does not perform well. User interaction -> websocket events -> vispy logic -> GLIR encoding -> transmission over websocket -> decoding -> drawing just takes too long and can't keep up for a responsive visualization.

Here's the roadmap: https://vispy.org/roadmap.html

I think users just want something they can put in a notebook. If it performs well, allows for interaction, and looks good that's all that matters.

You've mentioned it elsewhere, but dropping the webgl backend could simplify the vispy installation process. It also means we can archive the vispy.js repository (visible but read only). As you say we could first simplify the GLIR processing in vispy by removing shader manipulation and checks. This may not be completely true as I think some users still expect to use some GL ES libraries on things like android and maybe raspberry pi's. So we'd have to double check.

**Comment by djhoese** [comment]
If we are able to simplify the shader handling in GLIR, we could even look at GLSL 1.20 -> GLSL 4+ -> SPIR-V conversion. Not sure we really need that, but it wouldn't hurt if it is easy.

**Comment by almarklein** [comment]
Thanks for the explanation. I wasn't sure if we ever "formally" decided to drop it. It looks like we will.
