### ISSUE TITLE
Add ability to pass "fpos" as a parameter to the ColorFilter

### ISSUE THREAD

**Issue by clarebcook** [vispy/vispy#2143]
Hi all,
I am currently trying to use the ```ColorFilter``` (https://github.com/vispy/vispy/blob/main/vispy/visuals/filters/color.py) in a project along with several other filters, which I need to be placed in a specific order. However, right now, ```fpos``` cannot be passed as a parameter to ```ColorFilter```, which is always using 8:
```
    def __init__(self, filter=(1., 1., 1., 1.)):
        super(ColorFilter, self).__init__(fcode=self.FRAG_SHADER, fpos=8)

        self.filter = filter
```

Is it possible to change this so the user can specify any position for this filter?

Thanks so much,
Clare

**Comment by djhoese** [comment]
> Is it possible to change this so the user can specify any position for this filter?

Absolutely! I think this is something people never really needed to do and now that we've had more structure added to filters this should be much easier to standardize as a keyword argument. It seems like almost all the filters (at least the ones in `color.py`, if not more) either use the default position of the base class or have the position hard coded.

Would you mind taking a shot at a pull request to fix one or more of these? You could make the keyword arguments and keep the defaults as they are now.
