### ISSUE TITLE
Scrolling line with history

### ISSUE THREAD

**Issue by pperanich** [vispy/vispy#2145]
I am working on a real time visualization application utilizing vispy and am having trouble creating a visual with the desired effect. Basically, I am looking to combine the history characteristic, i.e. all previous data is not cleared, that is present in the ScrollingImage visual (found in the oscilloscope example), into either the LineVisual, or ScrollingLines visual. I have attempted to integrate (unsuccessfully) the rolling texture function found in ScrollingImage into the ScrollingLines visual, but have not been able to get it working. Any help would be greatly appreciated!

**Comment by djhoese** [comment]
Is there any way you could narrow down your code to a small example that I could see and play with to help you further? You mentioned that you tried some things and they didn't work. If you can make the example include that that'd be great.

**Comment by pperanich** [comment]
I have solved this issue, but am having issues regarding moving the camera in space. Will open another issue for this. Thanks for the response.
