### ISSUE TITLE
Setting the initial camera position for the fly camera

### ISSUE THREAD

**Issue by robw4** [vispy/vispy#2151]
I am trying to change the initial camera position on the fly camera so that it is at `(5, 0, 5)` with respect to the world co-ordinates (as shown by `scene.visuals.XYZAxis()`) and elevated down (pitched) at -30 degrees to the horizontal. I have tried:
```python
view = canvas.central_widget.add_view('fly')
view.add(scene.visuals.XYZAxis())
view.camera.center = np.array([5., 0., 5.])
view.camera.rotation1 = Quaternion.create_from_axis_angle(-np.pi / 6, 0, 1, 0)
```
but to no avail. In what order are `rotation1` and `center` applied with respect to the world origin? I have had a look through the vispy source code but I'm struggling to understand exactly what I need to do.

**Comment by almarklein** [comment]
> but to no avail.

In what way does it not work? IFAIK the rotation is applied after the translation. It's a bit hard to see what's wrong here. A complete but small example would help. E.g. a scene with a cube at the location you want to look at.

Other than that, you could try e.g. using a very small rotation at first and see what it does, then increase the rotation.

**Comment by djhoese** [comment]
> view = canvas.central_widget.add_view('fly')

I have helped maintain vispy for almost 6 years (maybe more) and I honestly didn't realize you could do this. :laughing: 

I agree with Almar, it might be easier for us to find what's wrong if you have a minimal example and tell us what about the example isn't as expected.

**Comment by robw4** [comment]
Thanks for the speedy response. Code below which plots a basic grid, 3D cube and axes.

```python
from vispy import scene, app
from vispy.util.quaternion import Quaternion

import numpy as np

def add_grid(view,  limits=(-10, 10), n=21, z=0.):
    from vispy.scene.visuals import Arrow
    x = np.linspace(limits[0], limits[1], n)
    for xx in x:
        view.add(Arrow(
            pos=np.array([[limits[0], xx, 0.], [limits[1], xx, 0.]])))
        view.add(Arrow(
            pos=np.array([[xx, limits[0], 0.], [xx, limits[1], 0.]])))

canvas = scene.SceneCanvas(show=True)
view = canvas.central_widget.add_view('fly')
view.camera.auto_roll = False

# position camera at (10, 0, 10) <- this works
view.camera.center = np.array([10., 0., 10.])
# pitch down about y axis by -30 degrees below the horizontal?
view.camera.rotation1 = Quaternion.create_from_axis_angle(-np.pi / 6, 0, 1, 0)

view.add(scene.visuals.Box())
view.add(scene.visuals.XYZAxis())
add_grid(view)

if __name__ == '__main__':
    app.run()

```

What I would like to achieve is to position the camera at [10, 0, 10] and pitch the camera down by 30 degrees from the horizontal so that you are slightly looking down on the grid and the cube! Positioning the camera works but I am having trouble getting my head around the rotation.

**Comment by djhoese** [comment]
Thanks for the example. I was able to run it, but I'm sad to say I don't know enough about the fly camera to make this work. @almarklein any idea who wrote the original fly camera?

**Comment by almarklein** [comment]
> any idea who wrote the original fly camera?

Yeah, I did :)

> Positioning the camera works but I am having trouble getting my head around the rotation.

Rotations in 3D are hard :)  So if we'd set the `rotation1` to a null rotation, it will (I think) look down the z axis, and y would probably be up. So there's more than one axis to rotate over ... complicated.

Instead, I ran the example in an interactive session. Rotated (using the fly camera controls) to a nice position, and then:
```
>>> view.camera.rotation1
<Quaternion object -0.685 + 0.24i + 0.2j + 0.658k>
```

So you can replace that line:
```py
view.camera.rotation1 = Quaternion(-0.685, 0.24, 0.2, 0.658)
```

**Comment by robw4** [comment]
Thanks @djhoese and @almarklein for your help on this. Setting the position manually and logging out the Quarternion for `rotation1` works well enough. Awesome package by the way. Thanks for the hard work in putting it together!
