### ISSUE TITLE
Efficiently moving camera in 2D scene

### ISSUE THREAD

**Issue by pperanich** [vispy/vispy#2153]
Hi, I have recently been implementing a real-time data acquisition gui that will display data in real time as it is read off a device. I am currently using the LineVisual for displaying the data as it allows me to use timestamps for the data points rather than assuming a fixed step between each sample. This part of the GUI works well now, however, when I add a continual camera move to track with the data, the processing power required ramps up quite a bit. What are the most efficient ways to move the camera view  within a scene? I am currently manually updating the camera rect, using PanZoom camera, on a timer at a slower rate (~1Hz) then the data points are being updated (~30Hz). Thanks for the help in advance.

**Comment by djhoese** [comment]
Do you have a minimal code example you could provide that shows how you are attacking this problem? That would help me offer advice to your specific implementation. Also, do you *need* to keep all the data on the line and pan/zoom? Could you instead keep the last N records (ex last 200 points of data) and adjust the x coordinates or transform so the line is always in the viewport?

**Comment by pperanich** [comment]
Below is a simple example using fake data. In my actual application, I need to buffer ~3 minutes of real-time data to be displayed and I can not guarantee that the dt between each sample is consistent, hence why I would prefer to use timestamps. Let me know if you can think of a more efficient way to move the viewbox or any other potential solution. Thanks!

```
import numpy as np
from vispy import scene, geometry

class SignalStream(scene.SceneCanvas):
    """ Stream processed camera data for ROIs. """

    def __init__(self, N):
        scene.SceneCanvas.__init__(self, keys='interactive',
                                   size=(400, 800))

        self.unfreeze()
        # Set up a viewbox to display the image with interactive pan/zoom
        self.view = self.central_widget.add_view()
        # Set 2D camera (the camera will scale to the contents in the scene)
        self.view.camera = AlteredPanZoomCamera()

        # flip y-axis to have correct aligment
        self.view.camera.zoom(1, (0, 0))
        self.view.camera.name = "RangedPanZoomCamera"
        
        pos = np.zeros((N, 2), np.float32)
        # pos[:, 0] = np.linspace(0., 1/30, N)
        color = np.ones((N, 4), dtype=np.float32)
        color[:, 0] = np.linspace(0, 1, N)
        color[:, 1] = color[::-1, 0]
        # pos[:, 1] = np.random.normal(scale=1, size=N)
        self.line = scene.visuals.Line(pos=pos, color=color, parent=self.view.scene)
        self.line.transform = scene.transforms.STTransform()
        self.line.transform.scale = (1,1/10)

        self.gridlines = scene.visuals.GridLines(parent=self.view.scene)

        vb = (0, -0.5, 1, 1)
        self.view.camera.rect = vb

        self.N = N
        self.color = color
        self.pos = pos

        self.freeze()

    def roll_data(self, data):
        self.pos = self.pos.copy()
        self.pos = np.concatenate((self.pos[data.shape[0]:], data))
        self.line.set_data(pos=self.pos)


class AlteredPanZoomCamera(scene.PanZoomCamera):

    def move_to_edge(self, val: float, side: str ):
        if side == None:
            assert "Must provide left,right to align camera"
        rect = geometry.Rect(self.rect)
        width = rect.width
        if side =='left':
            rect.left = val
            rect.right = (val+width)
        elif side == 'right':
            rect.right = val
            rect.left = (val-width)
        self.rect = rect


if __name__ == "__main__":
    import time
    from vispy import app
    interval = 1/30
    num_pts = 100
    start = time.time()
    canvas = SignalStream(10000)
    def refresh_data(ev):
        global canvas, interval, num_pts, start
        current_time = time.time() - start
        t_s = np.linspace(start=current_time, stop=current_time+interval, num=num_pts)
        y_s = np.sin(2*np.pi*t_s)
        data = np.array((t_s, y_s))
        canvas.roll_data(data.T)
        canvas.view.camera.move_to_edge(t_s[-1], 'right')
    timer = app.Timer(interval=interval, connect=refresh_data)
    timer.start()
    canvas.show()
    app.run()
```

**Comment by djhoese** [comment]
So I've played with this a little and your `move_to_edge` method could be simplified a little, but it results in the same CPU usage.

```python
        width = self.rect.width
        left = self.rect.left
        self.pan((val - (left + width), 0, 0))
```

This results in ~25% CPU usage on my machine. I'm actually surprised by how smooth and good it looks. Without further optimizing the PanZoom camera I'm not sure that can be improved. The main issue is likely that the PanZoom camera creates and sets a **new** STTransform when it makes changes to the view. Making a *new* STTransform means recompiling the shader code and resending it to the GPU. Hold on a second...

Let me see if I can do something here.

**Comment by djhoese** [comment]
Ok, we would need to do some heavy profiling here. Even with my own local hacks to the base camera that I thought would speed it up, it is still the same CPU usage. I tried the following:

```diff
Index: vispy/scene/cameras/base_camera.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vispy/scene/cameras/base_camera.py b/vispy/scene/cameras/base_camera.py
--- a/vispy/scene/cameras/base_camera.py	(revision 21c64e6d4ce74e5194da46b963ffb09b4a6d8d5c)
+++ b/vispy/scene/cameras/base_camera.py	(date 1627007263191)
@@ -508,7 +508,10 @@
         # transform.changed event
         pre_tr = self.pre_transform
         if pre_tr is None:
-            self._scene_transform = tr
+            if hasattr(self, '_scene_transform') and not isinstance(self._scene_transform, NullTransform):
+                self._scene_transform.matrix = tr.matrix
+            else:
+                self._scene_transform = tr
         else:
             self._transform_cache.roll()
             self._scene_transform = self._transform_cache.get([pre_tr, tr])
@@ -518,7 +521,10 @@
         self._scene_transform.dynamic = True
 
         # Update scene
-        self._viewbox.scene.transform = self._scene_transform
+        if not isinstance(self._viewbox.scene.transform, NullTransform):
+            self._viewbox.scene.transform.matrix = self._scene_transform.matrix
+        else:
+            self._viewbox.scene.transform = self._scene_transform
         self._viewbox.update()
 
         # Apply same state to linked cameras, but prevent that camera

```

The idea here is to avoid creating new transform objects and only update the properties of the existing transforms. However, even with these changes I get the same CPU usage as before. I could dig into the shader compilation and double check that the code isn't being recompiled, but am running out of time tonight.

@almarklein any other ideas? Is this just one of those "yeah it is going to use that much CPU" cases?

**Comment by djhoese** [comment]
@pperanich If you want lower CPU usage then you may need to consider changing your design. For example, do you need the pan zoom capability? You could try not having a camera and just "manually" changing the transform of the view.scene object. This cuts out the complexity of the camera, but is still probably not the major slow down here...maybe.

I'm having trouble thinking of an optimization like I mentioned earlier about keeping the last N records since you have the grid. I'm not sure how to achieve that visualization (moving grid) while only updating the position coordinates of the line to reflect the changing del-t between each point.

**Comment by pperanich** [comment]
Wow, thanks so much @djhoese for investigating this so quick. I was unaware where to start looking to investigate the issue, but you have pointed out some places to start. How/where exactly would you start profiling the library to find where the inefficiencies are? In the future, I may convert to a constant dt via interpolating the received signal and displaying the data in something like a ScrollingLines plot. My issue there would be displaying a time axes that scrolls with the data, since the visual is essentially static in the viewport.

**Comment by djhoese** [comment]
For the time scrolling, what I've done in the past (pre-vispy) was to have the x-axis tick labels show something like -200 to 0 and represent 200 records. I then have the X label say something like "last 200 points" or maybe update the label with the most recent time or in your case I guess you could do "Past 200 seconds" or something like that. Just ideas. Not as helpful to the user as a moving grid.

For profiling, I wonder if the napari (GUI analysis tool that uses vispy) folks have ideas (@tlambert03 @sofroniewn)? I've seen presentations of napari where people did some profiling but I'm not sure what tools they used.

**Comment by sofroniewn** [comment]
> For profiling, I wonder if the napari (GUI analysis tool that uses vispy) folks have ideas (@tlambert03 @sofroniewn)? I've seen presentations of napari where people did some profiling but I'm not sure what tools they used.

This link might help https://napari.org/developers/profiling.html?highlight=profiling

**Comment by almarklein** [comment]
If I ramp it up to `interval = 1/100` I get ~25% CPU usage. If I comment the call to `move_to_edge` its ~12%. I also think that's a bit much for updating a camera.

I added a print-call to `Compiler.compile`, and that only shows up 3 times at the start, so there is no recompilation going on.

**Comment by pperanich** [comment]
That profiling info is good to know. In the future, I likely will interpolate incoming signals to a constant dt and scroll the data since moving the viewport does take a significant portion of the computation. I think this resolves this issue for now.
