### ISSUE TITLE
Markers with an invisible face

### ISSUE THREAD

**Issue by juraj6** [vispy/vispy#2154]
Hello, again with some question. If I have some markers over the image and set the alpha channel of its fill area to zero (see example, `face_color=(0,0,0,0)`), I expected to see the bottom image inside the marker. However it seems that it makes the part of the image under the marker also invisible. Is there a solution to this? I have read some transparency  issues, but I cannot find a solution.

Example code:

```python
import sys
from vispy import scene, app
import numpy as np

canvas = scene.SceneCanvas(size=(400, 400), keys='interactive', show=True)
viewbox = canvas.central_widget.add_view(camera='panzoom')

data = np.array([[20,20],[50,50],[80,80]])
markers = scene.visuals.Markers(pos=data, size=50., edge_width=5, edge_color='y', face_color=(0,0,0,0))
markers.transform.translate = (0.,0.,1.)

data = np.full((100,100), 0, dtype=np.uint8)
image = scene.visuals.Image(data)
image.transform.translate = (0.,0.,2.)

viewbox.add(markers)
viewbox.add(image)

viewbox.camera.set_range((0,100), (0,100), margin=0)

if __name__ == '__main__':
    if sys.flags.interactive == 0:
        app.run()
```

Results (the first picture is what I got, the second is what I expected):
![markers](https://user-images.githubusercontent.com/61293309/126684702-bc08392e-75d3-4be8-844d-99be8b2784d2.png)

**Comment by djhoese** [comment]
Congratulations on confusing me for way longer that I thought I was going to be when trying to answer your question. lol :laughing: 

I took your example and tried and tried to figure out why things were not responding the way I expected. I finally got everything working and here is the final result:

```python
import sys
from vispy import scene, app
import numpy as np
from vispy.visuals.transforms import STTransform

canvas = scene.SceneCanvas(size=(400, 400), keys='interactive', show=True)
viewbox = canvas.central_widget.add_view(camera='panzoom')

data = np.array([[20,20],[50,50],[80,80]])
markers = scene.visuals.Markers(pos=data, size=50., edge_width=5, edge_color='y', face_color=(0,0,0,0))
markers.transform = STTransform(translate=(0.,0.,1.))

data = np.full((100,100), 0, dtype=np.uint8)
image = scene.visuals.Image(data)
image.transform = STTransform(translate=(0.,0.,2.))

viewbox.add(image)
viewbox.add(markers)

viewbox.camera.set_range((0,100), (0,100))

if __name__ == '__main__':
    if sys.flags.interactive == 0:
        app.run()
```

The two key points here:

1. Assign a **new** transform to `.transform`. By default this is a `NullTransform` which doesn't do anything to the coordinates. When you did `.translate = something` you were creating a new property on the instance that didn't actually mean anything to the transform. In my code above I create a new STTransform for each. @almarklein we should maybe either make this raise an error *or* even better we should make all transforms defined with `__slots__` so they are smaller and more efficient.
2. I swapped the order that the visuals are added to the view. This makes it so the image is drawn first and then the markers. You could also control this by doing `markers.order = 1` and `image.order = 2`. This is just a small gotcha with drawing order and how OpenGL handles transparency.

Hope this helps.

**Comment by juraj6** [comment]
Nice, this works perfectly, thank you. I thought that the `STTransform` is created automatically for these 2D visuals, because it did not throw any error when I set the translation values. Next time I should read the code better :slightly_smiling_face:.
