### ISSUE TITLE
SceneCanvas multiple Visual draw events

### ISSUE THREAD

**Issue by pperanich** [vispy/vispy#2155]
I am creating a real-time visualization application using PyQt which has several SceneCanvas widgets that are displaying different Visual objects, each of which updating in real-time (let's call that 30Hz). I had a general question regarding performance of SceneCanvas redrawing in this scenario. I have read that using multiple visuals in a program may cause slow downs since each visual is its own OpenGL program, but I do not believe I am using an alarming amount of visual objects. However, I was wondering if there is an efficient method to update the different SceneCanvas widgets in the application? I.e. a method to synchronize the "gloo.draw" calls you would make if using the lower-level Canvas/gloo interface? The updates for each of the SceneCanvases are not necessarily in sync, so would it be better to trigger a global redraw or allow them to update as data is received/displayed. Thanks!

**Comment by almarklein** [comment]
Hi, interesting question! I don't have a clear-cut answer, and I may make some assumptions that are wrong, but here is my take. Maybe others can chime in to confirm or counter my points :)

Since each canvas is its own qt window (with its own GL context), I would actually suspect things to be more efficient if each is allowed to update at its own pace.

From the point of view of the event loop: let's say you sync them, and have a timer to run each 0.033 s (33Hz). Then every 0.033s it does a lot of work on all canvases, and then sleeps for a bit. It may not be able to do 30Hz. But if they update separately, one canvas could be working to create a new frame, while the others are waiting.

In theory, one canvas could be doing CPU work while another uses the GPU, but I'm not sure if that actually works this way with Python+Vispy+GL.

**Comment by djhoese** [comment]
I'm not sure I'm understanding your situation the same way @almarklein is. Qt can have multiple windows open from the same process but they all still run from the same QApplication. I also believe that this means one single OpenGL context. So unless you start separate applications, I don't think there will be any parallelism between the multiple canvases. I could be wrong on how the context is used/shared, but I don't think I am here. That said, I still think keeping them independent drawing-wise would be good. Let the GUI event loop sort out the order of the draw events.

Some thoughts you may want to consider:

1. One optimization option is to reduce the amount of data. Either by limiting the number of points you actually draw (averaging/smoothing or striding the array) or you could limit how often you draw (data comes in 30Hz, draw every 1 Hz). I know you've realized a lot of this already given your other issues/questions, but it really comes down to what can a human viewer actually see/notice and get out of the plot.
2. If you're really worried about speed, try moving data ingest to separate threads (QThreads) and communicate to the main GUI thread when new data is available. There are a couple different ways to do this and what's best for your application may depend on how much data and how often you need to update. You could have a shared array between the threads and use qt signals/slots to notify the main thread that the data has been updated (may require some sort of locking or a circular buffer). Or you could send the actual updated data over the qt signal. This may require extra serialization overhead and likely require a couple copies of the data to be made.

**Comment by almarklein** [comment]
Whether or not the contexts are shared or not should not affect the rest of what I said :)

**Comment by djhoese** [comment]
True, but:

> Since each canvas is its own qt window (with its own GL context), I would actually suspect things to be more efficient if each is allowed to update at its own pace.

This makes it sound like you are saying having separate contexts allows for separating drawing to the GPU. I assumed/assume that separate GL contexts means independent (parallelize-able) drawing loops. We came to the same suggestion in the end.

**Comment by pperanich** [comment]
Based on my pretty rudimentary knowledge, I think @djhoese is right on the single OpenGL context for a single QApplication. I have tied together the x axis of cameras which are in separate SceneCanvases, which I think could only be done with a single context? I will attach some files to run a rudimentary version of the application I am working on. I am aware it is not optimized well and could be significantly improved in terms of computation, but it does serve to show the origin of some of the issues I have brought forth thus far. For instance, I am using a separate Line visual for each data stream right now, but this could be changed to use a single Line visual to plot the points, but provide the vertices to connect together.

Responding to @djhoese comments above:
1. The data streams I am reading are sampled at ~2kHz, but I am simply aggregating then uploading chunks at 30Hz. As you will see in my example application, I am actually panning the view at a much slower rate (5Hz), so I could make it where the data updates at that rate instead of 30Hz.

2. I have the data ingest and processing happening in a separate Process, with QThreads used to communicate with the Process via multiprocessing Queue and then update the data in the GUI displays. Currently, I am passing the buffered data in chunks within PyQt signals and I do not think this holds me up too much, given that the chunks are not incredibly large.

To run the application: `python3 vispy_multiscene.py`


I have included a requirements.txt to get you up and running as well.
[vispy_issues.zip](https://github.com/vispy/vispy/files/6879385/vispy_issues.zip)

**Comment by djhoese** [comment]
Besides the QThread crash/dump when I close the application it looks pretty cool.

**Comment by pperanich** [comment]
> Besides the QThread crash/dump when I close the application it looks pretty cool.

Still working out the issues. The crash doesn't seem to occur on MacOS, but does seem to happen on Linux I believe.

**Comment by djhoese** [comment]
Yep, I'm on PopOS/Ubuntu. FYI it never kills the background threads/processes and they just run in the background forever. I had to kill them separately. I only knew they were there because my laptop started taking off (fans going hard) and I started searching my system monitor for high CPU usage.

**Comment by almarklein** [comment]
> This makes it sound like you are saying having separate contexts allows for separating drawing to the GPU

For the record: I was assuming that it would help, but honestly I don't know :)
