### ISSUE TITLE
where does _ambient_color, _light_dir gone?

### ISSUE THREAD

**Issue by yxdragon** [vispy/vispy#2165]
after I update vispy, my script about light_dir, light_color, ambient_color raise an error. removed?

**Comment by djhoese** [comment]
Sorry about that. The MeshVisual and the way it handles shading has been completely rewritten. We tried to document things, but obviously missed the obvious property changes. The shading functionality was moved to a separate ShadingFilter:

https://vispy.org/api/vispy.visuals.filters.mesh.html#vispy.visuals.filters.mesh.ShadingFilter

The shading filter has a lot more options than the old shading functionality used to have. You can see more about some of the mesh filters that were added in this example:

https://vispy.org/gallery/scene/mesh_shading.html

You can access the default ShadingFilter object of the MeshVisual by accessing `my_mesh.shading_filter` (or you can add your own, see the example above).

So theoretically to access `light_dir`, you should be able to do `my_mesh.shading_filter.light_dir = X`. You should be able to find similar properties for `ambient_light` and `diffuse_light`. There is also a `specular_light`. Note that these light parameters now allow you to control the color and the intensity of the light.

Let us know if there is anything else you need. @asnt and @almarklein may be able to point you to more specifics if you need it as they have a better understanding of the low-level code.

**Comment by unnati914** [comment]
could i solve this issue?

**Comment by djhoese** [comment]
@unnati914 I don't think there is anything that actually needs fixing here. The properties have moved and I've pointed to where they are now. I'm actually going to close this as I think it is resolved. If there is something you (or anyone else) thinks can be cleaned up or fixed here let me know by commenting here or making a new issue. Thanks for reaching out @unnati914!

**Comment by unnati914** [comment]
surely i will contribute to another issue
Thanks
