### ISSUE TITLE
tkinter example code

### ISSUE THREAD

**Issue by matthiasverstraete** [vispy/vispy#2168]
Hi,

I want to embed a vispy canvas in my tkinter application. However, I can't seem to find any example code for this.
Is there an example available somewhere, or can someone provide me with one?

Thanks!

**Comment by almarklein** [comment]
Hi! Good question. An example with this would be good. I tried to change an existing example, but got stuck because the vispy widget sticks to being 1x1 pixels. I reckon this is my lack of tkinter skills.

```py
import tkinter as tk
import vispy
from vispy import scene
from vispy import app
from vispy.io import load_data_file, read_png

vispy.use("tkinter")

window = tk.Tk()

# greeting = tk.Label(text="Hello, Tkinter")
# greeting.pack()

canvas = scene.SceneCanvas(keys='interactive', parent=window)
canvas.native.grid(row=1, column=1)
canvas.native.size = 800, 600  # < -- does not work

# Set up a viewbox to display the image with interactive pan/zoom
view = canvas.central_widget.add_view()

# Create the image
img_data = read_png(load_data_file('mona_lisa/mona_lisa_sm.png'))
interpolation = 'nearest'
image = scene.visuals.Image(img_data, interpolation=interpolation,
                            parent=view.scene, method='subdivide')

# Set 2D camera (the camera will scale to the contents in the scene)
view.camera = scene.PanZoomCamera(aspect=1)
view.camera.flip = (0, 1, 0)
view.camera.set_range()
view.camera.zoom(0.1, (250, 200))


if __name__ == '__main__':
    app.run()
```

**Comment by matthiasverstraete** [comment]
Ok, thanks for the example!
I used the 'pack' methods in order to get the canvas the correct size.

**Comment by djhoese** [comment]
You could check out this old example code that @ThenTech posted in #1918 when they added the backend:

https://gist.github.com/ThenTech/620d2422a8a2f2529d01bf34e229d7ca

**Comment by tpecar-elaphe** [comment]
Expanded the @ThenTech example into something that could be used as a basis for a tool. Feel free to integrate it into the repo examples.

https://gist.github.com/tpecar-elaphe/438804863d25c57d39cde487ef165e4a

IMO the tkinter + vispy combo holds potential as you get a lot for a relatively compact set of dependencies - I'm getting tired of lugging PyQt around hah.

**Comment by djhoese** [comment]
@tpecar-elaphe Thanks for providing another example with this backend. I skimmed it and I'm not sure I like a "base" example of using a backend in an application that includes custom cameras. It complicates the code and distracts from the "how to include vispy in a tk app" idea of an example. If you would like more feedback or a longer discussion and would like your example code included in the vispy repository then I would recommend making a pull request to start that process.

**Comment by tpecar-elaphe** [comment]
@djhoese Thank you for your feedback! Looking at it I can agree that it isn't exactly in a shippable state, especially in regards to its API use. Sorry for the wrong impression.

I'll take some time to figure out how I can achieve something similar while staying within the intended interfaces and provide it in a separate PR.
