### ISSUE TITLE
Improve documentation for `vispy.gloo.program.draw`

### ISSUE THREAD

**Issue by mscheltienne** [vispy/vispy#2170]
While trying out `vispy`, I feel like the documentation is too sparse on several functions. I am however a new comer to `vispy`.

One of the functions I used lacking documentation is `vispy.gloo.program.draw`.
The different modes are not clear, and I basically had to try them one by one to figure out what they are doing. A better description, or a link to a better description would be very useful.

`‘points’, ‘lines’, ‘line_strip’, ‘line_loop’, ‘lines_adjacency’, ‘line_strip_adjacency’, ‘triangles’, ‘triangle_strip’, or ‘triangle_fan’`

**Comment by djhoese** [comment]
Thanks for making this issue after our discussion on stackoverflow. While I haven't updated the documentation for this, the short term answer is that these parameters come directly from OpenGL. Googling how OpenGL uses them should help explain why you would use one over the other and how.

**Comment by mscheltienne** [comment]
@djhoese That was the main one I remembered on the spot, I'll try to add other issues on the one I don't when I'll encounter them again.

So, I did try to Google some of it. I am not very familiar with OpenGL; and I can only write some simple shaders after going through many examples on the vispy github. The googling didn't really yield great results. The best I got was: https://www.khronos.org/opengl/wiki/Primitive which does explain it a bit.

This is why in the issue I suggested adding a link to external documentation. I'm guessing all those OpenGL settings must be documented somewhere, and simply adding a link would be enough to help newcomers finding the useful information.

**Comment by djhoese** [comment]
Not sure how I missed your comment in August. Sorry about that.

VisPy advertises and documents that the "gloo" level interface is for those with OpenGL experience and is not meant for users who are new to OpenGL. I don't remember everything we discussed on SO, but I thought I could point out here that we do have a References section with tutorials and other third-party documentation on OpenGL:

https://vispy.org/resources.html

There's also the "Modern OpenGL" page which describes some basics of OpenGL and how they differ from older versions of OpenGL: https://vispy.org/getting_started/modern-gl.html

**Comment by mscheltienne** [comment]
> VisPy advertises and documents that the "gloo" level interface is for those with OpenGL experience and is not meant for users who are new to OpenGL.

This sentence summarizes it very well ;)
