### ISSUE TITLE
PyQt6 backend missing

### ISSUE THREAD

**Issue by mars0001** [vispy/vispy#2171]
Hi,

I am using VisPy in FlatCAM application (beta branch) and I have ported my app to PyQt6. But VisPy (nor matplotlib) do not work with PyQt6 at the moment therefore I tried to add this new backend for the VisPy project.

I am not experienced with VisPy (I only use a limited set of features) but what changes I made are enough for my project to run without errors.

My changes are here, perhaps they will help minimize the work to add this backend:
https://github.com/mars0001/vispy

Do you think that I should make a pull request with this?

Best regards,
Marius

**Comment by djhoese** [comment]
> Do you think that I should make a pull request with this?

Of course! It would be greatly appreciated!

**Comment by mars0001** [comment]
Hi,
I have opened a PR here: https://github.com/vispy/vispy/pull/2172 with the proposed changes.
