### ISSUE TITLE
Update volume_plane.py to allow timer to be stopped

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2178]
I noticed the volume_plane.py has keyboard handling for moving the plane through the volume, but it doesn't allow you to stop the animation so these events don't actually mean much.

@alisterburt do you have time to fix this? Tradition is to use the spacebar (`" "`) to toggle the timer start/stop

**Comment by alisterburt** [comment]
oh yeah! Thanks for pointing that out -  I forgot to integrate the animated example with the keybindings, will try get to that sorted this evening

**Comment by djhoese** [comment]
Thanks @alisterburt. So is this something you think you'll have time for today? If not, I can try to find the time and then make a 0.8.0 release with this fix. However, I have a kid staying home sick today so not sure I'll have a bunch of dedicated time. Let me know your availability. Thanks.

**Comment by alisterburt** [comment]
Will have go after lunch - sorry to hear about the illness, hope they get better soon! 🙂

**Comment by djhoese** [comment]
Ha, sorry for bothering you, I realized it wasn't that hard of a task and I had a little time right now so #2179 will fix this. :grin:
