### ISSUE TITLE
Move vispy-website submodule into main repository

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2184]
We currently have the `https://github.com/vispy/vispy-website` (sphinx source) repository made available to this main vispy repository as a git submodule under the `doc` directory. There are pros and cons to this:

* Pro: I think we get separate size quotas/limits per repository. So by having it separate, I think the static files we may or may not add to the website repository to not impact how much we can have on this repository. However, we currently aren't using much space at all. I think GitHub prefers you stay under 1GB with a warning at 5GB (last I heard by reading a stackoverflow answer):

   ![image](https://user-images.githubusercontent.com/1828519/130459187-b264baa5-8428-4ce3-a833-5a35f20e45d4.png)

   Note: I had to add myself individually as an Admin to each of those repositories for that to show up in https://github.com/settings/repositories. It doesn't show up if you only have access via a Team.

* Pro: Separate issue/pull request tracking. However it is pretty rare that an issue with the website doesn't involve something on this main repository.
* Con: Difficult for users, especially those unfamiliar with git, to clone the repository and get all of the components they need. Take for example #2138 where I had to explain the complicated process of "I know you want to work on the website but that actually requires get this repository and following complex instructions to make sure you also get the doc submodule".
* Con: Some tools don't work well with submodules. We have special commands in some of our github workflows to make sure the submodule is pulled. It works, but it is something extra. More importantly we can't use https://holzhaus.github.io/sphinx-multiversion/master/index.html because it doesn't work with submodules.
* Con: Maintenance. We have to always make sure that any changes to the vispy-website source gets reflected in a new commit here in the main repository when we update the git submodule.

**Comment by almarklein** [comment]
What alternatives are there? From what I can think of:

1. Move the whole docs to the main repo. With images possibly being part of the repo this feels a bit "dirty" to me.
2. Keep it in a separate repo but don't do the subrepo thing (does that make sense at all)?
3. Move docs to the main repo but put static files in a separate repo that you download files from during building the docs.

**Comment by djhoese** [comment]
The title of this issue was meant to suggest option 1. I think this is as dirty as needed for what has to be done. Plus a lot of the images in `_static` directory aren't actually used any more. We could probably replace some of the "carousel" with the ones generated by sphinx-gallery when the website is built. Or get rid of the carousel, at least as it is implemented right now. The only other static files necessary in there are fonts, CSS, and logos. Even with all the extra stuff the total space is very limited.

As a separate anything (repos, git submodule, separate static), the maintenance is harder. I could just not be paying attention, but I'm not aware of many projects that use a separate repository for docs source or for static files (at least not the normal smaller ones). Both matplotlib and numpy have a inline `doc` directory.

**Comment by almarklein** [comment]
> The only other static files necessary in there are fonts, CSS, and logos. Even with all the extra stuff the total space is very limited.

Ok, I'm +1 for the simplicity of a single repo then!
