### ISSUE TITLE
key events are parsed incorrectly with tkinter backend

### ISSUE THREAD

**Issue by matthiasverstraete** [vispy/vispy#2206]
Hi,
I have an application that uses vispy key events. I recently switched to the tkinter backend (to avoid a dependency on qt) and noticed the key events no longer work. While special keys are detected correctly, anything that is readable (characters/digits) is detected as a different key or not at all.

I have a minimal example below (it will print out the pressed key):
```python
import math
from vispy import app, gloo

# remove this line to test with other backend and see it works
app.use_app("tkinter")

class Canvas(app.Canvas):

    def __init__(self, *args, **kwargs):
        app.Canvas.__init__(self, *args, **kwargs)

        self.events.key_press.connect(
            self.on_key_press
        )

    def on_key_press(self, event):
        print(event.text)

    def on_draw(self, event):
        gloo.clear(color=True)

if __name__ == '__main__':
    canvas = Canvas(keys='interactive', always_on_top=True)
    canvas.show()
    app.run()
```

The root cause seems that vispy relies on the 'keycode' field of the tkinter event, which doesn't correspond to the ascii value of a character/digit. I've created a pull request which adds two lines of code that check the 'char' field of the tkinter event. This seems to resolve the problem.

https://github.com/vispy/vispy/pull/2205

**Comment by kmuehlbauer** [comment]
@matthiasverstraete Is this resolved with your PR #2205?
