### ISSUE TITLE
Unable to run on Mac with Homebrew

### ISSUE THREAD

**Issue by jaredmoore** [vispy/vispy#2213]
I've followed the instructions for installing p5 and glfw from https://p5.readthedocs.io/en/latest/install.html#macos-linux.  

Using the latest Homebrew installation for glfw and using `brew info glfw` I get the following:

> glfw: stable 3.3.4 (bottled), HEAD
> Multi-platform library for OpenGL applications
> https://www.glfw.org/
> /usr/local/Cellar/glfw/3.3.4 (14 files, 520.9KB) *
>   Poured from bottle on 2021-09-15 at 15:45:43
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/glfw.rb

Using pip to install p5 goes smoothly.  However, when I try to run a script, it appears vispy is failing to find my glfw backend.  Specifically, here is the trace I'm getting: 

> Traceback (most recent call last):
>   File "<redacted>/Creative_Coding/p5py/circles_intro.py", line 1, in <module>
>     from p5 import *
>   File "<redacted>/.pyenv/versions/p5py/lib/python3.9/site-packages/p5/__init__.py", line 19, in <module>
>     from .sketch import *
>   File "<redacted>.pyenv/versions/p5py/lib/python3.9/site-packages/p5/sketch/__init__.py", line 19, in <module>
>     vispy.use('glfw')
>   File "<redacted>/.pyenv/versions/p5py/lib/python3.9/site-packages/vispy/util/wrappers.py", line 98, in use
>     use_app(app)
>   File "<redacted>/.pyenv/versions/p5py/lib/python3.9/site-packages/vispy/app/_default_app.py", line 47, in use_app
>     default_app = Application(backend_name)
>   File "<redacted>/.pyenv/versions/p5py/lib/python3.9/site-packages/vispy/app/application.py", line 47, in __init__
>     self._use(backend_name)
>   File "<redacted>/.pyenv/versions/p5py/lib/python3.9/site-packages/vispy/app/application.py", line 240, in _use
>     raise RuntimeError(msg)
> RuntimeError: Could not import backend "Glfw":
> dlopen(glfw3.framework/glfw3, 6): image not found

I've attempted to rollback my glfw version in homebrew but am running into some inconsistencies in the cache with that so I've updated python from 3.9.1 to 3.9.4.  This was in response to some other errors I saw with vispy and Mac on the issues.  This doesn't seem to fix it unfortunately.  

As near as I can tell, homebrew changed the packaging from glfw3 to just glfw.  Or perhaps I'm missing something obvious at this point?  

Thanks!

**Comment by djhoese** [comment]
What happens if you try setting the GLFW_LIBRARY environment variable that is used here:

https://github.com/vispy/vispy/blob/585266c07a5d0f954523651ba20604bb49793b08/vispy/ext/glfw.py#L46-L48

**Comment by almarklein** [comment]
At the moment, vispy has its own glfw wrapper that targets the glfw DLL.  We should probably change this to use `pip install glfw` (https://github.com/FlorianRhiem/pyGLFW)

**Comment by jaredmoore** [comment]
Setting the GLFW_LIBRARY environment variable to point directly at my libglfw.dylib installed by homebrew does the trick. 

For some context, I teach introductory Python and was looking to integrate "Creative Coding" as some exercises.  p5 looks like a great possibility but the install process isn't quite as smooth as it could be for students coming in without much background.  However, it looks like a great library with vispy doing the heavy lifting in the backend.  I'm not sure it can really be made that much smoother given the need for external graphics drivers to be installed.  I do like the idea of integrating with glfw available through pip although that doesn't address the graphics issue which is outside the control of vispy maintainers.  

Looking forward to working with it.  Thanks for the quick responses, I wish I'd have come here first before trying some hacks for an evening :)

**Comment by djhoese** [comment]
Thanks for filing the issue. I work in academia and too many times my own colleagues will find issues with open source software, but never tell anyone until years later "oh I stopped using that because I couldn't get thing X to work". Thanks for telling us this was an issue for you. We'll see what we can do for the future. For now I think I'll close this and make a new issue for replacing the glfw wrapper in vispy with pyglfw.
