### ISSUE TITLE
Use osmesa backend got IndexError

### ISSUE THREAD

**Issue by ansj11** [vispy/vispy#2218]
Hi, I am using vispy with osmesa backend to render a mesh of scene, but i got IndexError like this
<img width="932" alt="截屏2021-09-23 下午11 50 35" src="https://user-images.githubusercontent.com/24786133/134541662-2ec75c7d-0e7a-43a1-a066-28eea7457b09.png">

Does anyone know the solution to this problem?

**Comment by djhoese** [comment]
@ansj11 Does this happen every time? Do you have a small script that would let us reproduce this? What version of vispy are you using? What operating system is this? What does `python -c "import vispy; print(vispy.sys_info())"` show you?

**Comment by ansj11** [comment]
I changed to another mirror and there is no error, but rendering a 384x224 depth map is very slow. What is the reason?

**Comment by djhoese** [comment]
It sounds like switching to another mirror worked to solve your original problem. For speed let's maybe talk on #2221. Please try to keep the number of issues with similar discussions to a minimum. It is a little difficult to keep track of your comments and concerns across all of these issues you've commented on.
