### ISSUE TITLE
vispy GUI example

### ISSUE THREAD

**Issue by Dive576** [vispy/vispy#2232]
Hello,

I've finished developing a Qt GUI for `vispy` that provides a way to easily plot/animate `pandas` DataFrames:

https://github.com/Dive576/DIVE

Would there be any interest in having this as an example for `vispy`? I know it's rather large for an example, but I feel like it would be useful to someone and I don't want it to go to waste.

**Comment by almarklein** [comment]
A used-by section would be nice indeed.

**Comment by djhoese** [comment]
@Dive576 Do you have a short description that you think we could include in a section like this for DIVE? Maybe one or two sentences. I think we should maybe avoid screenshots just to keep things concise if/when we add more.

@Dive576 How would you like to make a pull request adding this new section to the documentation and adding your entry for DIVE?

**Comment by kmuehlbauer** [comment]
@djhoese Can we close this one?

**Comment by djhoese** [comment]
Closed as part of #2235
