### ISSUE TITLE
problem to run a vispy based script through jupyter-notebook

### ISSUE THREAD

**Issue by crasse2** [vispy/vispy#2249]
Hi There !
I'm trying to run a *.py script that handle a mesh file using vispy through a notebook and it crashes giving this error 

```
~/.local/lib/python3.8/site-packages/vispy/scene/canvas.py in render(self, region, size, bgcolor, crop)
    255         self.push_fbo(fbo, offset, csize)
    256         try:
--> 257             self._draw_scene(bgcolor=bgcolor)
    258             return fbo.read(crop=crop)
    259         finally:

~/.local/lib/python3.8/site-packages/vispy/scene/canvas.py in _draw_scene(self, bgcolor)
    264             bgcolor = self._bgcolor
    265         self.context.clear(color=bgcolor, depth=True)
--> 266         self.draw_visual(self.scene)
    267 
    268     def draw_visual(self, visual, event=None):

~/.local/lib/python3.8/site-packages/vispy/scene/canvas.py in draw_visual(self, visual, event)
    302                         else:
    303                             if hasattr(node, 'draw'):
--> 304                                 node.draw()
    305                                 prof.mark(str(node))
    306                 else:

~/.local/lib/python3.8/site-packages/vispy/scene/visuals.py in draw(self)
     97         if self.picking and not self.interactive:
     98             return
---> 99         self._visual_superclass.draw(self)
    100 
    101 

~/.local/lib/python3.8/site-packages/vispy/visuals/mesh.py in draw(self, *args, **kwds)
    517 
    518     def draw(self, *args, **kwds):
--> 519         Visual.draw(self, *args, **kwds)
    520 
    521     @staticmethod

~/.local/lib/python3.8/site-packages/vispy/visuals/visual.py in draw(self)
    440                              self)
    441         try:
--> 442             self._program.draw(self._vshare.draw_mode,
    443                                self._vshare.index_buffer)
    444         except Exception:

~/.local/lib/python3.8/site-packages/vispy/visuals/shaders/program.py in draw(self, *args, **kwargs)
     99         self.build_if_needed()
    100         self.update_variables()
--> 101         Program.draw(self, *args, **kwargs)
    102 
    103     def build_if_needed(self):

~/.local/lib/python3.8/site-packages/vispy/gloo/program.py in draw(self, mode, indices, check_error)
    531 
    532         # Process GLIR commands
--> 533         canvas.context.flush_commands()

~/.local/lib/python3.8/site-packages/vispy/gloo/context.py in flush_commands(self, event)
    173             else:
    174                 fbo = 0
--> 175             self.shared.parser.parse([('CURRENT', 0, fbo)])
    176         self.glir.flush(self.shared.parser)
    177 

~/.local/lib/python3.8/site-packages/vispy/app/backends/_ipynb_webgl.py in parse(self, commands)
     95             new_commands.append(c)
     96         if new_commands:
---> 97             self._widget.send_glir_commands(new_commands)
     98 
     99 

AttributeError: 'NoneType' object has no attribute 'send_glir_commands'
```

that error comes from this command in the script 
`img = normal_canvas.render()`

however the script works perfectly outside of a notebook, for instance if I'm just executing it in the terminal by calling the *.py file

is there a known problem using vispy commands or calling external vispy scripts in notebooks ?

**Comment by djhoese** [comment]
> is there a known problem using vispy commands or calling external vispy scripts in notebooks ?

Yes. It looks like you are using an old version of vispy as the `_ipynb_webgl.py` the traceback shows no longer exists. More recent versions of vispy use the `jupyter_rfb` package to be able to render things and display them inline in a notebook. Could you try updating vispy, installing `jupyter_rfb`, and try your use case again?

**Comment by crasse2** [comment]
Hi ! Thks for your help !

I updated vispy to the last version 0.9 and installed jupyter_rfb and now this error is gone.
yet the script still does not work when called in jupyter (and still works perfectly when called from terminal)

here is the problematic part : 

i got a mesh called 'normal_canvas' and when I print its informations I got that 
`<mesh.Canvas_view object at 0x7f4b8c6fdaf0>`

then it's rendered : 
`img = normal_canvas.render()`

and then comes an opencv operation : 
`img = cv2.resize(img, (int(img.shape[1] / init_factor), int(img.shape[0] / init_factor)), interpolation=cv2.INTER_AREA)`

that gives the error
`error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/resize.cpp:4048: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'`

my guess is that the `img` placeholder is empty and the `normal_canvas.render()` didn't work as it should

still when called in terminal, the *.py file works perfectly, however when imported and called in the notebook it doesn't

**Comment by djhoese** [comment]
The `jupyter_rfb` backend needs to "latch onto" some other backend. It doesn't actually do the rendering itself, but uses another backend and then forwards the results to the notebook. You likely didn't have any other backend installed (sorry, should have mentioned that). If you are rendering on a backend server that has no display (virtual or physical) then EGL is probably your best bet to make this work.

I'll close this as you said you got it working. Feel free to open up another issue if you (or anyone else reading this) has a similar but different issue.
