### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by pauljurczak** [vispy/vispy#2250]
I installed vispy 0.9.3 on Ubuntu 20.04.3 with Python 3.8.10 in `.vispy` venv, following instructions from https://vispy.org/installation.html:
```
pip install --upgrade vispy
pip install pyglet
```
Example from https://vispy.org/gallery/scene/image.html# produces this error:
```
Traceback (most recent call last):
  File "/home/paul/vis/.vispy/lib/python3.8/site-packages/vispy/io/image.py", line 118, in read_png
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```
`Pillow` installation is needed for this example to work.

**Comment by djhoese** [comment]
Sorry about that, thanks for filing this. Pillow (imported as PIL) is currently an optional dependency as it is really only used to load example image data or as a utility to read image files. Would something like an "Optional Dependencies" section on that installation page be helpful? Other ideas?

Would you feel comfortable submitting a pull request with updated information on this?

**Comment by pauljurczak** [comment]
I mostly copied and pasted your text. Thanks for a quick response.
