### ISSUE TITLE
unable download the demo data

### ISSUE THREAD

**Issue by littlebird-0904** [vispy/vispy#2253]
I want to run the demo of volume.py, but the demo data needed can't download. How can I download the demo data? Thanks!!!

**Comment by almarklein** [comment]
What do you mean with "can't download"? If there is there an error message, could you please post it her?

**Comment by littlebird-0904** [comment]
Thank you for your reply. Here is the issue, there has some error appear when I run the demo of Vloume.py and the volume_plane.py. The screenshots of the error in the attachment. And I think this error is due to the demo-data can't download. Is this correct? How can I solve this? Thanks!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vispy/vispy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vispy/vispy] unable download the demo data (Issue #2253)





 
What do you mean with "can't download"? If there is there an error message, could you please post it her?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by almarklein** [comment]
There is no attachment. I don't think you can send attachments to issue comments.

**Comment by littlebird-0904** [comment]
Here is the error.
#############################################################
=== RESTART: \vispy-main\examples\scene\volume.py ===
Traceback (most recent call last):
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 1317, in do_open
&nbsp; &nbsp; encode_chunked=req.has_header('Transfer-encoding'))
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 1244, in request
&nbsp; &nbsp; self._send_request(method, url, body, headers, encode_chunked)
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 1290, in _send_request
&nbsp; &nbsp; self.endheaders(body, encode_chunked=encode_chunked)
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 1239, in endheaders
&nbsp; &nbsp; self._send_output(message_body, encode_chunked=encode_chunked)
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 1026, in _send_output
&nbsp; &nbsp; self.send(msg)
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 966, in send
&nbsp; &nbsp; self.connect()
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 1406, in connect
&nbsp; &nbsp; super().connect()
&nbsp; File "C:\software\python\python3.7\lib\http\client.py", line 938, in connect
&nbsp; &nbsp; (self.host,self.port), self.timeout, self.source_address)
&nbsp; File "C:\software\python\python3.7\lib\socket.py", line 707, in create_connection
&nbsp; &nbsp; for res in getaddrinfo(host, port, 0, SOCK_STREAM):
&nbsp; File "C:\software\python\python3.7\lib\socket.py", line 748, in getaddrinfo
&nbsp; &nbsp; for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "C:\software\python\python3.7\lib\site-packages\vispy\util\fetching.py", line 239, in _fetch_file
&nbsp; &nbsp; data = urllib.request.urlopen(url, timeout=15.)
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 222, in urlopen
&nbsp; &nbsp; return opener.open(url, data, timeout)
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 525, in open
&nbsp; &nbsp; response = self._open(req, data)
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 543, in _open
&nbsp; &nbsp; '_open', req)
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 503, in _call_chain
&nbsp; &nbsp; result = func(*args)
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 1360, in https_open
&nbsp; &nbsp; context=self._context, check_hostname=self._check_hostname)
&nbsp; File "C:\software\python\python3.7\lib\urllib\request.py", line 1319, in do_open
&nbsp; &nbsp; raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11004] getaddrinfo failed&gt;


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "\vispy-main\examples\scene\volume.py", line 41, in <module&gt;
&nbsp; &nbsp; vol1 = np.load(io.load_data_file('volume/stent.npz'))['arr_0']
&nbsp; File "C:\software\python\python3.7\lib\site-packages\vispy\util\fetching.py", line 67, in load_data_file
&nbsp; &nbsp; _fetch_file(url, fname)
&nbsp; File "C:\software\python\python3.7\lib\site-packages\vispy\util\fetching.py", line 243, in _fetch_file
&nbsp; &nbsp; 'Dataset fetching aborted (%s)' % (url, e))
RuntimeError: Error while fetching file https://raw.githubusercontent.com/vispy/demo-data/main/volume/stent.npz.
Dataset fetching aborted (<urlopen error [Errno 11004] getaddrinfo failed&gt;)



############################################################
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vispy/vispy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 晚上7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vispy/vispy] unable download the demo data (Issue #2253)





 
There is no attachment. I don't think you can send attachments to issue comments.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by djhoese** [comment]
Are you able to go to this URL in your browser: https://raw.githubusercontent.com/vispy/demo-data/main/volume/stent.npz

If not, this suggests that your firewall is blocking access to this URL. If you can access it in a browser then it suggests Python or your terminal is somehow not allowed to access the URL.

**Comment by littlebird-0904** [comment]
I am unable to go to this URL. It seems like the firewall blocking access to this URL. I will try to solve this.

**Comment by djhoese** [comment]
No updates since the original problem but since it seemed to not be vispy's fault I'm going to close this.
