### ISSUE TITLE
unable to apply light_dir on Isosurface

### ISSUE THREAD

**Issue by loctran15** [vispy/vispy#2254]
Hi everyone, in the older version of Vispy, I was able to do the following

surface = scene.visuals.Isosurface(data, level=data.max() / 4.,
                                   color=(0.5, 0.6, 1, 1), shading='smooth',
                                   parent=view.scene)

surface.light_dir = (0, -1, 0)

In the current version of Vispy, I found out that does not work anymore and need to be changed to surface.shading_filter.light_dir = (0,-1,0). However, I got the below error message

```python-traceback
Traceback (most recent call last):
  File "", line 32, in <module>
    surface.shading_filter.light_dir = (0, -1, 0)
  File "", line 455, in light_dir
    self._update_data()
  File "", line 547, in _update_data
    normals = self._visual.mesh_data.get_vertex_normals(indexed='faces')
  File "", line 330, in get_vertex_normals
    faceNorms = self.get_face_normals()
  File "", line 298, in get_face_normals
    self._face_normals = np.cross(v[:, 1] - v[:, 0],
TypeError: 'NoneType' object is not subscriptable
```

If you want to replicate the issue, below is the code

```python
import sys
import numpy as np

from vispy import app, scene

canvas = scene.SceneCanvas(keys='interactive')
view = canvas.central_widget.add_view()


def psi(i, j, k, offset=(25, 25, 50)):
    x = i - offset[0]
    y = j - offset[1]
    z = k - offset[2]
    th = np.arctan2(z, (x ** 2 + y ** 2) ** 0.5)
    r = (x ** 2 + y ** 2 + z ** 2) ** 0.5
    a0 = 1
    ps = ((1. / 81.) * 1. / (6. * np.pi) ** 0.5 * (1. / a0) ** (3 / 2) * (r / a0) ** 2 *
          np.exp(-r / (3 * a0)) * (3 * np.cos(th) ** 2 - 1))
    return ps


print("Generating scalar field..")
data = np.abs(np.fromfunction(psi, (50, 50, 100)))

surface = scene.visuals.Isosurface(data, level=data.max() / 4.,
                                   color=(0.5, 0.6, 1, 1), shading='smooth',
                                   parent=view.scene)
surface.transform = scene.transforms.STTransform(translate=(-25, -25, -50))
surface.shading_filter.light_dir = (0, -1, 0)

axis = scene.visuals.XYZAxis(parent=view.scene)

cam = scene.TurntableCamera(elevation=30, azimuth=30)
cam.set_range((-10, 10), (-10, 10), (-10, 10))
view.camera = cam

if __name__ == '__main__':
    canvas.show()
    if sys.flags.interactive == 0:
        app.run()
```

**Comment by djhoese** [comment]
It seems the MeshVisual (the parent class of Isosurface) requires that the Canvas actual be shown or drawn before the light direction can be set. I'm not sure of an easier workaround besides the following:

1. Move `canvas.show()` to right before the `light_dir` is set.
2. Add `surface._prepare_draw(surface)` right before `light_dir` is set.

@asnt any other ideas how this could be fixed?

**Comment by loctran15** [comment]
> It seems the MeshVisual (the parent class of Isosurface) requires that the Canvas actual be shown or drawn before the light direction can be set. I'm not sure of an easier workaround besides the following:
> 
> 1. Move `canvas.show()` to right before the `light_dir` is set.
> 2. Add `surface._prepare_draw(surface)` right before `light_dir` is set.
> 
> @asnt any other ideas how this could be fixed?

Thank you so much! the workarounds work
