### ISSUE TITLE
visual filter documentation

### ISSUE THREAD

**Issue by kevinyamauchi** [vispy/vispy#2256]
Hello! I am wondering if there is some documentation on the [visual filters](https://vispy.org/api/vispy.visuals.filters.base_filter.html). In particular, I am having trouble understanding what the `vhook`/`fhook` and `vpos`/`fpos` arguments mean.

For  `vhook`/`fhook`, what does setting to `'pre'` vs. `'post'` do? I am guessing it is before/after the visual's built-in shader?

For `vpos`/`fpos` , I am wondering what the "position" means. Is this the order in which the attached filters get called (e.g., a filter with `pos==1` gets called before one with `pos==6`)? Or is it perhaps a position in the rendering pipeline?

Thank you!

**Comment by djhoese** [comment]
Sorry about the lack of documentation on Filters. They were only semi-recently defined well enough to have a base class. I think all of your guesses as to what those parameters do are accurate. The `Xpos` arguments give a priority to one filter over another. The `Xhook` is also as you've said, it is either at the beginning of the `main` part of the vertex or fragment shader or at the end.

**Comment by kevinyamauchi** [comment]
No worries, @djhoese ! Thank you for the quick response!
