### ISSUE TITLE
Clarification of vispy.scene.visuals.Arrow 

### ISSUE THREAD

**Issue by pauljurczak** [vispy/vispy#2260]
Can you explain what does this parameter of `vispy.scene.visuals.Arrow` mean?
```
pos : array
Array of shape (…, 2) or (…, 3) specifying vertex coordinates.
```
Which arrow vertices? Are they different from vertices in `arrows` parameter?

**Comment by djhoese** [comment]
I think it may make the most sense if you play with the `arrows.py` example: https://github.com/vispy/vispy/blob/c68ab04996d6433951d00cb5a6f3ce84a6ed3dbd/examples/basics/visuals/arrows.py

The `pos` defines the positions of the line being drawn. The `arrows` define the arrow head that is drawn somewhere on that line (typically). Looking at that example you can see that the arrows are always defined using the line positions. I don't think there is any requirement that the arrow head be on the line, just that that is what is typically done.

**Comment by pauljurczak** [comment]
I looked at that example, and I'm trying to draw an arrow using arrays with similar patterns. This snippet:
```
p = np.array([[3, 3], [9, 9]])
a = np.array([3, 3, 9, 9])
arrow = Arrow(pos=p, arrows=a, parent=view.scene, color='blue', arrow_type='angle_90', connect='segments')
```
produces incomplete rendering:

![arrow-1](https://user-images.githubusercontent.com/4933032/142745869-27002d93-36ff-4fa5-b6d2-3ba501122812.png)

and this error:
```
IndexError: tuple index out of range
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (Pyglet) at 0x7f45f0cf0070>> for DrawEvent
```

**Comment by djhoese** [comment]
Try putting another set of `[]` around the `a`:

```python
a = np.array([[3, 3, 9, 9]])
```

The array is meant to be 2D, yours was 1D.

**Comment by pauljurczak** [comment]
Thank you, it works. Do you mind if I try to clarify it a bit in the documentation?
