### ISSUE TITLE
How to get TextVisual width 

### ISSUE THREAD

**Issue by juraj6** [vispy/vispy#2265]
Hello,

is it possible to get the width of the `TextVisual`? For example, I have created an `TextVisual` (`scene.visuals.Text`) with text "ABCD" and I want to know the width from letter A to letter D in pixels. Height is easy, it's just `font_size`, but getting width seems more difficult (at least for me). The number of letters, font type or font size can be arbitrary.

**Comment by djhoese** [comment]
There definitely isn't something public that would tell you this. You might be able to hack your way into access the individual font objects that the TextVisual is using:

https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/vispy/visuals/text/text.py#L84-L120

But even then I don't know if the references to "width" here are the size of the character or size of the texture or something else. It might be simpler to use the Pillow library which I think includes ways of doing this for a string of characters. It should be relatively equal to what vispy is doing.

**Comment by juraj6** [comment]
Thank you for your response. Getting the width of the text is not so necessary for me, so if there is no simple solution, I will use some alternative, like monospace font.

**Comment by juraj6** [comment]
Thank you for your response. Getting the width of the text is not so necessary for me, so if there is no simple solution, I will use some alternative, like monospace font.
