### ISSUE TITLE
Performance of animation

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [vispy/vispy#2267]
Im trying to implement an interactive animation; and from the examples I found, it seemed to me like this was the way. Its horrendously slow though; both for pyqt6 and pyside2. How do I update a handful of 4x4 affines, so that I can actually render a few thousand triangles at interactive rates? Im probably missing something stupid, but id like to understand the conceptual model of the event loop better so I get a somewhat better appreciation of what im botching here, for future reference. This approach was 'good enough' for non-interactive rendering an animation to disk; but clearly it isnt how interactive animations are meant to be done. 

Note that fps is fine when manipulating the camera without changing the transforms; but it seems as if every single transform update of a node causes about a 0.1s hickup in the rendering. Clearly these affine updates are to be worked in the event loop in a different manner; but why is this approach that ive seen mentioned in 3 different tutorials not working for me?

```

    # create a simple scene containing a handful of simple mesh visuals, like spheres and cubes
    nodes: List[Node] = create_nodes()
    canvas, view = setup_scene(nodes, size=(800, 600))

    # precompute all affine matrices needed for each frame and node, to minimize slowdown within animation loop
    affines = compute_animation()    # shape [frames, nodes, 4, 4], float

    counter = [0]  # put in list for mutating from scope below

    def update(event):
        counter[0] = (counter[0] + 1) % len(affines)
        for node, affine in zip(nodes, affines[counter[0]]):
            node.transform = vispy.visuals.transforms.MatrixTransform(affine)

    # this works like garbage; even for a single node containing a handful of triangles I cant realize 20fps.
    from vispy import app
    timer = app.Timer(interval=1/20, connect=update, start=True)
    app.run()

```

**Comment by djhoese** [comment]
Good questions. I think I could give you a more useful answer if you could include more information or more code. Specifically how many nodes are you creating? If it is a lot then I think this would be a good start:

https://vispy.org/faq.html#why-is-my-visualization-slower-when-i-add-more-visual-objects

The other performance hit in the way you are doing this is that by creating a new `MatrixTransform` for every update you are requiring vispy to recompile the shaders for that Visual. That's not only the transform's underlying GLSL shader but the entire Visual's shader. There are some checks that will skip this recompile if things are exactly the same, but they aren't that smart. What should perform better is to update the existing transform in-place. If you create your visual nodes and immediately set a MatrixTransform on them then you know that you'll have any MatrixTransform interfaces available to you. The most basic (and apparently not documented) is the `.matrix` setter on the MatrixTransform here:

https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/vispy/visuals/transforms/linear.py#L396-L402

If you go to that bit of the code and scroll down you'll see other methods that may fit how you're describing your matrix more precisely. By making this transform change in-place the shaders should not be updated in place and only the small matrix buffer should be uploaded to the GPU and should be much faster. If you are also able to combine your Visuals into a single (or fewer) MeshVisuals then you'll also have much better performance at the small cost of larger complexity of your positions that you provide to the MeshVisual.

Hope that helps. Let me know how it goes.

**Comment by djhoese** [comment]
To be clear, you should do `node.transform.matrix = new_matrix` or `node.transform.scale(1.5)` or whatever other method you want to use on the transform.

**Comment by EelcoHoogendoorn** [comment]
Thanks for the input. The number of nodes is truly tiny; performance is already noticably choppy with a single cube.

The recompiling of shaders sounds like exactly the kind of thing that might explain this. I did infact try setting the matrix attribute directly; and that causes no slowdown; but also no update of my scene.

I tried a whole bunch of canvas.update(), canvas.on_draw(), view.update(), view.scene.events.transform_change()

But clearly im grasping at straws here, because still nothing is animating. I suppose im only a one-liner away now though!

**Comment by djhoese** [comment]
Hm `canvas.update()` should definitely get this working, but it should have worked as-is anyway. Would it be possible for you to trim down your example code to be self-contained and something I could run locally?

**Comment by EelcoHoogendoorn** [comment]
This works as self contained code on my machine, and reproduces the issue.

`
    import numpy as np
    import vispy

    # number of random boxes    
    N = 10
    
    def make_box():
        box = vispy.scene.visuals.Box(*np.random.rand(3) + 1, color='red')
        box.transform = vispy.visuals.transforms.STTransform(translate=np.random.random(3))
        return box

    def create_nodes():
        return [make_box() for n in range(N)]
    def setup_scene(nodes, size):
        canvas = vispy.scene.SceneCanvas(
            bgcolor='black',
            # app='pyqt6',      # fails when scrolling mousepad
            app='pyside2',
            size=size,

            keys='interactive',
            show=True
        )

        view = canvas.central_widget.add_view()
        view.camera = 'turntable'

        for node in nodes:
            node.parent = view.scene

        view.camera.set_range(x=[-1, 1])

        return canvas, view

    def compute_animation():
        I = np.eye(4)[None, None, ...] * np.ones((100, N, 1, 1))
        I[:, 0, 0, 0] = np.linspace(1, 4, 100)
        return I

    # create a simple scene containing a handful of simple mesh visuals, like spheres and cubes
    nodes = create_nodes()
    canvas, view = setup_scene(nodes, size=(800, 600))

    # precompute all affine matrices needed for each frame and node, to minimize slowdown within animation loop
    affines = compute_animation()  # shape [frames, nodes, 4, 4], float

    counter = [0]  # put in list for mutating from scope below
    def update(event):
        counter[0] = (counter[0] + 1) % len(affines)
        for node, affine in zip(nodes, affines[counter[0]]):
            # node.transform = vispy.visuals.transforms.MatrixTransform(affine)
            node.transform.matrix = affine

    # this works like garbage; even for 10 nodes containing a handful of triangles I cant realize smooth fps.
    from vispy import app

    timer = app.Timer(interval=1 / 20, connect=update, start=True)
    app.run()
`

**Comment by almarklein** [comment]
Hi Eelco! :wave: 

I looked into the example, and think you should use a `MatrixTransform` instead of the `STTransform`.

**Comment by djhoese** [comment]
Specifically this line:

```python
box.transform = vispy.visuals.transforms.STTransform(translate=np.random.random(3))
```

needs to be a MatrixTransform. Hopefully with this change you'll get the performance you are looking for.

**Comment by EelcoHoogendoorn** [comment]
Hey Almar; long time no see!

I was about to give up on this suggestion, but you are correct; If I initialize the transforms I intend to be updating as part of my animation loop as MatrixTransforms, then ```node.transform.matrix = affine``` 'just works', without any calls to canvas.update() or whatever.

Took me another bit of fiddling to get it to work on my actual non-reduced codebase; since there is another layer there to my scenegraph; with other vanilla Nodes, that I also need to hook up with MatrixTransforms (over their default NullTransform) to get it to update correctly. Infact it seems to be only the nodes that require updating that need to be set as MatrixTransform, not all in the graph involved. 

Dont mean to just complain about other peoples OS contributions (which are indeed much appreciated!), but these type of things are hard for me to figure out from what documentation is available... probably should take the time to understand the conceptual model behind BaseTransform etc better before complaining; I suppose there are good reasons for this related to the the tradeoffs in pre-compilation. But yeah its not super straightforward or intuitive, even as someone who has written a fair amount of rendering code in his lifetime.

Anyway, thanks!

**Comment by djhoese** [comment]
@EelcoHoogendoorn if you have any suggestions for how things could be improved (probably an entire section of the documentation site just on transforms) let us know or even better submit a pull request with the updates.

Otherwise it looks like you have this figured out so I'm going to close it. If your problem isn't fixed then we can reopen if needed.

**Comment by EelcoHoogendoorn** [comment]
I dont think my current understanding is sufficiently deep to be writing docs; but yeah closing makes sense; hopefully the issue will remain helpful as ad hoc documentation for others.
