### ISSUE TITLE
Vispy SceneCanvas embedded into PyQt5 becomes black after being removed from layout then add back

### ISSUE THREAD

**Issue by zongyuelu** [vispy/vispy#2270]
I asked the exactly same question on stackoverflow: https://stackoverflow.com/questions/70269388/vispy-scene-embedded-into-pyqt5-application-becomes-black-after-being-removed-fr?noredirect=1#comment124242983_70269388

The problem occurs after I do this series of operations:

1. Put two vispy.scene.SceneCanvas objects into two distinct QWidgets, call them scenewidget1, scenewidget2

2. Show a QWidget, add scenewidget1 and scenewidget2 to its layout

3. Remove scenewidget1 and scenewidget2 from layout, then add them back to layout

**4. One vispy SceneCanvas becomes black and shows nothing, it will recover after the user clicks the scene, is there any way to fix this problem?**

My attempts (Some of attempts are proposed by comments in my stackoverflow question):

1. Since the SceneCanvas will recover after the user clicks the scene, I simulated a PyQt mouseclick after re-adding scenes to layout, but that has no effect. 

2. None of calling ```update(), create_native(), show()``` after re-adding scenes to layout worked. 

3. Adding a delay between removing scenes from layout and re-adding scenes to layout does not work. 

![1](https://user-images.githubusercontent.com/49452586/145327632-05e99cdc-fb3b-4ce7-9a63-db46c24add84.png)
![2](https://user-images.githubusercontent.com/49452586/145327635-27551af2-8370-40f6-997e-13104ad81bd4.png)

Code:

```python
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import vispy.scene as scene
from vispy.scene import visuals

import numpy as np

class SceneWidget(QWidget):
    def __init__(self):
        super().__init__()
        self.layout = QHBoxLayout()
        self.scene = scene.SceneCanvas(parent=self, bgcolor='w')
        self.setLayout(self.layout)
        self.layout.addWidget(self.scene.native)
       
        # add something to the scene
        self.grid = self.scene.central_widget.add_grid(spacing=0)
        self.vb = self.grid.add_view(
            row=1, col=1, camera='panzoom', bgcolor=(1, 1, 1, 1), )
        self.scatter = visuals.Markers()
        self.vb.add(self.scatter)
        self.scatter.set_data(np.array([[0, 0], [1, 1], [2, 2]]))
        self.vb.camera.set_range(x=(-1, 3), y=(-1, 3))


class CentralWin(QWidget):
    def __init__(self):
        super().__init__()
        self.layout = QGridLayout()
        self.scenewidget1 = SceneWidget() # Scene Widget is a QWidget with a SceneCanvas at center
        self.scenewidget2 = SceneWidget()
        self.layout.addWidget(self.scenewidget1, 0, 0, 1, 1)
        self.layout.addWidget(self.scenewidget2, 0, 1, 1, 1)
        self.btn = QPushButton('Remove From Layout Then Add Back')
        self.btn.clicked.connect(self.removeFromLayout)
        self.layout.addWidget(self.btn, 1, 0, 1, 2)
        self.setLayout(self.layout)

    def removeFromLayout(self):
        self.layout.removeWidget(self.scenewidget1)
        self.layout.removeWidget(self.scenewidget2)
        self.scenewidget1.setParent(None)
        self.scenewidget2.setParent(None)
        self.layout.addWidget(self.scenewidget1, 0, 0, 1, 1)
        self.layout.addWidget(self.scenewidget2, 0, 1, 1, 1)


if __name__ == "__main__":

    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
    app = QApplication([])
    win = QMainWindow()
    win.setCentralWidget(CentralWin())
    win.show()

    if (sys.flags.interactive != 1) or not hasattr(Qt.QtCore, 'PYQT_VERSION'):
        QApplication.instance().exec_()
```

My Environment:

- vispy 0.9.3
- pyqt5 5.15.6

**Comment by djhoese** [comment]
You should probably reference the stackoverflow question: https://stackoverflow.com/questions/70269388/vispy-scene-embedded-into-pyqt5-application-becomes-black-after-being-removed-fr?noredirect=1#comment124242983_70269388

One thing I've tried with no luck is to use vispy's app by doing:

```python
import vispy
...

app = vispy.use('pyqt5')
app.create()
... create widgets ...
app.run()
```

Just wanted to put that here in case someone else wanted to try it out.

**Comment by djhoese** [comment]
If I switch to only using the SceneCanvas directly and only use one I still see a black widget.

**Comment by Kusefiru** [comment]
Both widgets can be added back without issues if I comment both of those lines:
```python
        self.scenewidget1.setParent(None)
        self.scenewidget2.setParent(None)
```

However:
- if I comment only the first one, the second canvas becomes black (as in the original code)
- if I comment only the second one, the first canvas becomes black but the second one works

If I save and restore the parent of each widgets, the second canvas appears black again. That said, Qt should manage reparenting the widgets automatically when calling `addWidget()`.

**Comment by zongyuelu** [comment]
> 

Hello @Kusefiru, thanks for your answer. Indeed commenting ```setParent(None)``` worked, but at the same time two canvas will no longer be removed by ```removeWidget()```, they will still exist on the screen. So I think ```setParent(None)``` is necessary, and I am wondering if there is vispy solution to this (like reparenting the native widget), I searched vispy docs for hours but didn't get any useful information to this.

**Comment by Kusefiru** [comment]
If I hide and then show the widgets instead of reparenting them (after removing / adding them back), they don't show as black.
It is also possible to only hide them instead of removing them from the layout.

While it does not delete the widgets, if you intend on adding them back to the layout later on, I guess it could be a solution.

My guess is that the issue occurs because of the reparenting.

**Comment by djhoese** [comment]
My hope (?) is that this is generally a bug in Qt between the QOpenGLWidget and the parent. It would be interesting to see if a Qt6-based backend (PySide6 or PyQt6) has this exact same behavior. More likely it is that the `__init__` of the vispy backend Canvas is doing something related to parenting (or trying to hold on to a handle to the parent) and never updates things when the parent changes. Is there a Qt event that is emitted when a parent changes? Or a method that we are "supposed" to override to handle parent changes? Either way really I'm not really sure what path to go down to fix this.

**Comment by Kusefiru** [comment]
There are `ParentAboutToChange` and `ParentChange` events in Qt. We also may have stuff to do inside the `setParent` of our widgets, but I'm not sure about that.

I'll try to investigate more, but I won't have much time for that in the upcoming weeks.

**Comment by Kusefiru** [comment]
A small update on this.

If I print the parent of both the `SceneWidget`  and native `SceneCanvas` objects, I notice that the reparenting affects only the `SceneWidget` objects.
The Vispy canvas keep its parent, which is the expected behavior, as reparenting a widget does not reparent its children.

I have added the `paintEvent()` method to the `QtBaseCanvasBackend` class to see the received events. What I notice is that after the reparenting / layout adding, **the second canvas does not receive paint events anymore**.
After interacting with the window (by clicking, resizing it...), as noted before, the canvas reappears, and strangely enough, it starts receiving paint events again.
