### ISSUE TITLE
GPU memory leak after canvas.render() command

### ISSUE THREAD

**Issue by crasse2** [vispy/vispy#2272]
Hi !

im currently trying to run a `canvas.render()` function within a loop function and each time around 100 MB are stacked (and I end up with OOM after several loops, depending on the GPU i use)

I tried various regular torch memory cleaning command (gc collect, del variables and so on) but nothing worked, those ~100MB are still being stacked up in the GPU memory after every loops.

the function description in the vispy file says 
"Render the scene to an offscreen buffer..."

is there any way to clear that buffer with a python command ? I never dealt with an offscreen buffer and don't know what to do with it (and if it is the culprit) 

the only information I found out are from the Offscreen Rendering help from the Blender help (don't know if they are takling about the same thing though ) here is what they say

> GPUOffScreen objects are bound to the OpenGL context they have been created in. This means that once Blender discards this context (i.e. the window is closed), the offscreen instance will be freed.

don't know how to put that in perpective with the execution of the function within a notebook

**Comment by djhoese** [comment]
@crasse2 The best place for us to start would be a small minimal example that shows the problem, but is also something that others (me) can run without having to download data or be in any other special environment. Also, what backend are you running your code with? On what OS? You could paste the output of the `python -c "import vispy; print(vispy.sys_info())"` which would include a lot of the information I need to start guessing what might be going wrong here.

**Comment by crasse2** [comment]
Hi djhoese, thanks for your help !

here is some informations : 
first i'm working on ubuntu 18.04 LTS and i'm running the code from a jupyter notebook and EGL app.

here are the informations from the vispy.sys_info() command : 
```
RFBOutputContext()
Platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.27
Python:   3.8.0 (default, Feb 25 2021, 22:10:10)  [GCC 8.4.0]
NumPy:    1.20.3
Backend:  jupyter_rfb
pyqt4:    None
pyqt5:    None
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.5 NVIDIA: OpenGL_ES OpenGL
osmesa:   None
tkinter:  None
jupyter_rfb: jupyter_rfb
_test:    None

GL version:  '4.6.0 NVIDIA 455.32.00'
MAX_TEXTURE_SIZE: 32768
Extensions: a lot of extensions are provided here, tell me if you need them ;)
```

the code it self is quite big, there is lots of 3d informations collected/generated by other processes coming at the end to vispy, within a loop n times because i'm trying to generate n 3d renders from n 3d collected informations. 
at some point in the main loop it comes to a function that execute the 

`img = nrm_canvas.canvas.render()`

i added GPU memory monitors before and after this very line, and each time I got 1% more GPU memory occupied that doesn't get cleared at the end of the loop (where other things as models loaded for example are cleared before the next loop) and each loop this function stack 1% more GPU memory.

**Comment by djhoese** [comment]
Thanks! This is a lot of good information. Is there any chance you could try running this either:

1. Not from a notebook but as a python script.
2. Run with a PyQt backend (ex. PyQt5) instead of EGL. The jupyter_rfb backend should use this automatically because it is a more "preferred" backend than EGL. Note this will require an actual display for PyQt to display windows. This mostly depends if this system is your local system or a remote server.

What I'd like to narrow down is if this is a jupyter notebook issue (jupyrter_rfb perhaps) or a EGL backedn issue or a general vispy issue. Without a smaller example this will likely be me asking you to run various tests and make small tweaks until we can get a reproducible failure or a solution.

CC @almarklein in case he has ideas for where jupyter_rfb may be holding on to something (maybe `.render()` is queuing a frame that never gets used?).

**Comment by crasse2** [comment]
Man ! it worked ! thanks so much !
I installed PyQt5 (got to reinstall opencv after that due shared librairies bug with PyQt) and added the right vispy.use() command

```
Platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.27
Python:   3.8.0 (default, Feb 25 2021, 22:10:10)  [GCC 8.4.0]
NumPy:    1.20.3
Backend:  PyQt5
pyqt4:    None
pyqt5:    ('PyQt5', '5.15.6', '5.15.2')
pyqt6:    None
pyside:   None
pyside2:  None
pyside6:  None
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      EGL 1.5 NVIDIA: OpenGL_ES OpenGL
osmesa:   None
tkinter:  None
jupyter_rfb: jupyter_rfb
_test:    None
```
and no memory leak what so ever at the moment (only run for 5 loops yet, but with jupyter_rfb it already leaked at this point. i'll let it run all the evening to monitor but seems to be resolved :) !
(so somehow the jupyter_rfb backend produce GPU memory leaks.)

thanks again !!

**Comment by crasse2** [comment]
it was egl, I found back the vispy.use command in an external py file called at some point in the process

**Comment by djhoese** [comment]
Your sys_info shows both EGL and jupyter_rfb. Without forcing it with `use` (or the other interfaces for specifying it), `jupyter_rfb` was used. Running vispy from a notebook will always default to `jupyter_rfb`. Running it from a script, the first available backend will be used and I believe the order in `sys_info` is the order/priority that is used (pyqt before EGL). `jupyter_rfb` does not do the drawing itself so it will use this same mechanism to choose the highest priority backend that it available.

So if you had `use` set to `jupyter_rfb` or didn't use it at all but ran from a notebook then `jupyter_rfb` would have been used. In your original `sys_info` you only had EGL available so it would have always used that. If you set `use` to use `'egl'` and still ran it from a notebook then the EGL backend would still be used (no jupyter_rfb).

Hopefully that helps...a little.

**Comment by crasse2** [comment]
yes it clarifies it, thanks ! and as I'm working a lot from notebooks, i'll stick to PyQt ;)

**Comment by almarklein** [comment]
> jupyter_rfb does not do the drawing itself

To clarify some more: `jupyter_rfb` knows nothing about drawing-  its only purpose is to send the frames over (and events back). Therefore, as David pointed out, it *always* needs a real backend to do the rendering.
