### ISSUE TITLE
Code of Conduct Not Found

### ISSUE THREAD

**Issue by Whotakesmyname** [vispy/vispy#2301]
Try to find some possibility contributing to this project. Only found the code of conduct link in the readme.md is broken.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by djhoese** [comment]
It works fine for me. Links to https://github.com/vispy/vispy/blob/main/CODE_OF_CONDUCT.md. What link are you seeing?
