### ISSUE TITLE
Rendered image empty at exterior contour

### ISSUE THREAD

**Issue by manurare** [vispy/vispy#2302]
Hi. I am rendering a sphere mesh with a camera inside. The mesh has no holes. I understand that this means that all pixels should have been rasterized and have a color value. I am using a perspective camera. However, no matter which FoV or canvas size I choose, the external border of pixels have not been rasterized, i.e, the top/bottom row and left/right column. Here is an example of the whole image and the bottom right border. You can see that the pixels on the edge are set to gray (my background color)

<p float="left">
<img src=https://user-images.githubusercontent.com/43776720/154728928-672d7177-2f9f-45a1-9822-a8366d93dc51.png width="400" height="400">
<img src=https://user-images.githubusercontent.com/43776720/154728952-7987ea65-726e-4f93-b0f4-3505b56d09d2.png width="400" height="350">
</p>

**Comment by djhoese** [comment]
Could you provide a minimal code example that shows the problem? Maybe try it with an array of all 0s instead of your image data for easier testing?

**Comment by manurare** [comment]
I am not able to have a minimal example with a `Image` visual instead of a `mesh`. If I change my camera to `arcball` it works and the black image is showing. 

```
import vispy
from vispy import scene
import numpy as np


class MyCanvas():
    def __init__(self):
        self.canvas = scene.SceneCanvas(bgcolor="grey", size=(1000, 1000))
        self.view = self.canvas.central_widget.add_view()
        self.view.camera = 'perspective'
        self.view.camera.fov = 90

        self.image = scene.visuals.Image(np.zeros((500, 500)))0
        self.image.transform = vispy.visuals.transforms.MatrixTransform()
        self.image.transform.rotate(axis=[1, 0, 0], angle=90)
        self.view.add(self.image)
        self.canvas.show()

mycanvas = MyCanvas()
import sys

if sys.flags.interactive != 1:
    vispy.app.run()
```

**Comment by manurare** [comment]
@djhoese Any idea if this can be fixed?

**Comment by djhoese** [comment]
Sorry, but I have very little time to volunteer to vispy right now. I tried running your example code but didn't get any image data only the background color. Also if I tried scrolling with my mouse wheel I got an exception:

```python
  File "/home/davidh/repos/git/vispy/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/davidh/repos/git/vispy/vispy/scene/cameras/perspective.py", line 62, in viewbox_mouse_event
    if self._distance is not None:
AttributeError: 'PerspectiveCamera' object has no attribute '_distance'
```

It is hard for me to understand what's going on but my current best guess is that a default "margin" is being added to the canvas edge and that's what you're seeing. But based on how you've described your usage of this I also wouldn't expect that to show up in this way.

**Comment by manurare** [comment]
Sorry for bothering, didn't know you were busy. I edited the code, I changed `perspective` camera for `arcball` and now you can see the small margin on the canvas. Is there any "elegant" way of removing it? At the moment I'm just cropping the outer edge of the rendered image

**Comment by djhoese** [comment]
> Sorry for bothering, didn't know you were busy.

Not a problem. Just wanted to point out that vispy is mostly a volunteer effort so it is hard to dedicate time to it when other things are going on.

Try passing `border_width=0` to the `add_view` method and see if that fixes things.

**Comment by manurare** [comment]
That was it! Thanks!

**Comment by djhoese** [comment]
Great! There have been talks about removing the default of `border_width=1` and making it `0` for reasons just like this. Thanks for filing the issue and glad we got it fixed.
