### ISSUE TITLE
Saving the picture

### ISSUE THREAD

**Issue by fenfenglitech** [vispy/vispy#2304]
How can i save the vis canvas as eps or png format?thank you!

**Comment by djhoese** [comment]
You can get a copy of the current SceneCanvas as a numpy array by doing:

```python
img_arr = canvas.render()
```

You can then save that using PIL (pillow) by doing:

```python
from PIL import Image
img = Image.fromarray(img_arr)
img.save("some_filename.png")
```

**Comment by fenfenglitech** [comment]
I got it,thank you!!!
and how can i zoom the 3D point cloud view,my code:
    ```
if self.semantics:
      print("Using semantics in visualizer")
      self.sem_view = vispy.scene.widgets.ViewBox(
          border_color='white', parent=self.canvas.scene)
      self.grid.add_widget(self.sem_view)
      self.sem_vis = visuals.Markers()
      self.sem_view.camera = 'turntable'
      self.sem_view.add(self.sem_vis)
      visuals.XYZAxis(parent=self.sem_view.scene)
      # self.sem_view.camera.link(self.scan_view.camera)

```
I got the figure like :
![saved_img2](https://user-images.githubusercontent.com/77180425/156100798-5c3c2242-bf7b-48c0-a13b-02e4e682c166.png)
and i want zoom it like this:
<img width="401" alt="saved_img1" src="https://user-images.githubusercontent.com/77180425/156100935-995a3797-ac93-4437-9cac-48dcb4b0f60b.PNG">

**Comment by djhoese** [comment]
The turntable camera has a `distance` property that you should be able to set:

https://github.com/vispy/vispy/blob/bf793b36010d3cecb8307e1360f6549633fed1e5/vispy/scene/cameras/turntable.py#L34-L37

```python
self.sem_view.camera.distance = some_value
```

Note that this property actually comes from the base class (https://github.com/vispy/vispy/blob/main/vispy/scene/cameras/perspective.py#L172) if you're looking for how it is used.

**Comment by fenfenglitech** [comment]
I have solved problems and thank your great works!!!
