### ISSUE TITLE
Does on_mouse_move event.delta work?

### ISSUE THREAD

**Issue by olinickalls** [vispy/vispy#2307]
I have been implementing my own windowing in vispy and saw the event.delta property for the on_mouse_move event.  This would be very handy for capturing click-drag actions.

The docs are blank for delta so perhaps I have wrong expectations...

Every time I check it's value - including during dragging - it is essentially zero: numpy float64 [0., 0.]
It never seems to contain any actual position delta.
Is Vispy simply forwarding this from the backend GUI? (PySide2 in my case)  so perhaps PySide2 is at fault.

Cheers- 
Oli

my exploratory code:

    @canvas.events.mouse_move.connect
    def on_mouse_move(event):
        if 3 in event.buttons:
            print(f'button: {event.button} '
                  f'buttons: {event.buttons} '
                  f'Delta: {event.delta[0]}, {event.delta[1]}')

**Comment by Kusefiru** [comment]
From my understanding, the `event.delta` is supposed to contain the mouse wheel rotation value.

During a `mouse_move` event, the wheel is not moving, which is why the `event.delta` value is always the same.

If you try reading `event.delta` during a `mouse_wheel` event, you should see it changing.

**Comment by djhoese** [comment]
Yes exactly as @Kusefiru said. `.delta` should be the mouse wheel. There should be a `press_event` and `last_event` property though that should give you the information you are looking for:

https://github.com/vispy/vispy/blob/bf793b36010d3cecb8307e1360f6549633fed1e5/vispy/app/canvas.py#L616-L622

**Comment by olinickalls** [comment]
Ah - ok - that makes sense.

So the suggested way of handling dragging here would be very simply (in pseudocode):
`move_delta = event.pos - event.last_event.pos`

That seems nice and neat- thanks!
