### ISSUE TITLE
Help understanding how close events work with the scene.SceneCanvas.

### ISSUE THREAD

**Issue by JacobBumgarner** [vispy/vispy#2310]
As discussed on the gitter, I'm having a bit of trouble understanding how to catch close events and ensure that canvases are destroyed from memory when being closed. 

Some basic testing around this can be seen below. I look forward to any feedback or explanation!

```python
import sys

import vispy
from vispy import scene
import numpy as np
import skimage

from PyQt5.QtWidgets import QMainWindow, QApplication, QWidget, QPushButton, QVBoxLayout

class Canvas(scene.SceneCanvas):
    def __init__(self, img, name):
        super().__init__(size=(img.shape[0], img.shape[1]),
                         title=name, keys='interactive')
        
        view = self.central_widget.add_view()
        
        interpolation = 'nearest'
        image = scene.visuals.Image(img, interpolation=interpolation, 
                                    parent=view.scene, method='subdivide')
        
        view.camera = scene.PanZoomCamera(aspect=1)
        view.camera.set_range()

        self.show()

    # def close(self):
    #     print ("caught close")
        
        
class MainWindow(QMainWindow):
    canvases = {}
    def __init__(self):
        """Initializer."""
        super().__init__()
        self.setWindowTitle('Test')
        
        self.centralWidget()

        mainWidget = QWidget()
        mainWidget.setLayout(QVBoxLayout())
        self.setCentralWidget(mainWidget)
        
        test_button = QPushButton('Add Canvas')
        test_button.clicked.connect(self.add_canvas)
        
        show_all = QPushButton('Show Canvases')
        show_all.clicked.connect(self.show_canvases)
        
        close_canvases = QPushButton('Clear list')
        close_canvases.clicked.connect(self.close_all)
        
        self.centralWidget().layout().addWidget(test_button)
        self.centralWidget().layout().addWidget(show_all)
        self.centralWidget().layout().addWidget(close_canvases)
        
    def add_canvas(self):
        image = np.zeros((200,200), dtype=np.uint8)
        rr, cc = skimage.draw.circle_perimeter(100,100, radius=np.random.randint(5,20), shape=image.shape)
        image[rr, cc] = 255
        title = str(len(self.canvases.keys()))
        c = Canvas(image, title)
        self.canvases[title] = c
        
    def show_canvases(self):
        for c in self.canvases.keys():
            self.canvases[c].show()
            
    def close_all(self):
        keys = list(self.canvases.keys())
        for c in keys:
            self.canvases[c].close()
            self.canvases.pop(c)
            

if __name__ == '__main__':
    qapp = QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(qapp.exec_())
```

**Comment by djhoese** [comment]
What about the behavior in this example tells you that it isn't closed/deleted?

**Comment by JacobBumgarner** [comment]
Sorry - was in a rush to post and didn’t have time to comment.

Here’s what was unexpected for me. If you add a window, close it manually using ‘q’ or by pressing the ‘X’ window close button, clicking ‘show all’ causes the window to reappear. Is this expected behavior?

I guess what this boils down to is me not understanding exactly how Qt objects are destroyed. I.e., why does calling `.show()` on a closed object still allow it to be shown? I assumed it would be destroyed after closing. Is this not the case?

Thanks @djhoese.

**Comment by djhoese** [comment]
So I'll be honest, usually the way I would do something like this is to reuse the same Canvas object instead of recreating one every time. That doesn't mean what you're doing shouldn't work. If you were doing anything else with the Canvas window I would have assumed that the `.parent` of the underlying QtWidget was being assigned and reused, but doesn't it have to be set to `None` to make the widget show up as a separate window? I can't think of anything else Qt-wise that would hold on to it besides `.parent`, but it has been a while since I've worked on a new Qt app.

I also can't think of anything in vispy-land that should be holding on to that object outside of Qt's own parenting stuff.

**Comment by JacobBumgarner** [comment]
Hmmm. Frankly I'm not sure about the `.parent` assignment. I will check that out.

Basically what I'm imagining would be the parent application having a `canvases` object that contains all of the active canvases. What I could then do is just make sure that the close action from the canvas calls the `canvases` object and removes itself from it.

Honestly to be sure that these objects aren't hanging around, I could just check memory usage after closing them...

**Comment by JacobBumgarner** [comment]
On another note - do you have any knowledge on the difference between the 'q' key command to close the canvas and pressing 'x' on the window? Clicking 'x' alone on the doesn't call the `close()` function from the `app.Canvas`.

Just trying to imagine how I could build on top of the current close function to make sure that the canvases are deleted. 

Thanks again @djhoese.

**Comment by Kusefiru** [comment]
When closing a `QWidget`, it deletes the associated object only if the `Qt::WA_DeleteOnClose` attribute flag is set, which is not by default.

If you specify the following in your `Canvas` object:
```python
self.native.setAttribute(QtCore.Qt.WA_DeleteOnClose)
```
Then closing the window deletes the object. If I try to show it back, I get:
```
RuntimeError: Internal C++ object (CanvasBackendDesktop) already deleted.
```

You are right that the "X" button does not call the `close()` method of the canvas though, it directly calls the `closeEvent()` method of the backend widget.

**Comment by JacobBumgarner** [comment]
Thanks for the detailed explanation @Kusefiru.
