### ISSUE TITLE
Is there a way to draw different types of lines in one Canvas by using visuals.Line() times？

### ISSUE THREAD

**Issue by Tcleslie** [vispy/vispy#2313]
I want to draw different types of lines in the same Canvas, and I used visuals.Line() times, however, it turned out the Canvas could only show the last draw-event, only one type line kept in the Canvas. Is there a way that could work like 'plot' that I can plot different lines by call plot times?

Here is part of code of  using visuals.Line():
```
for i in range(len(white_lane_nodes)-1):
        white_lane = visuals.Line(pos=white_lane_nodes[i],
                           connect=lane_pair,
                           color=white,
                           parent=view.scene,
                           antialias=True)

    for i in range(len(yellow_lane_nodes)-1):
        yellow_lane = visuals.Line(pos=yellow_lane_nodes[i],
                           connect=lane_pair,
                           color=orange,
                           parent=view.scene)
```

**Comment by djhoese** [comment]
I saw your stackoverflow question in my email first so I answered there.

https://stackoverflow.com/questions/71584128/how-to-use-vispy-to-draw-different-types-of-line-by-different-times

Please only post questions in one location. I'm going to close this and we can continue discussion on stackoverflow. If we need to do more "back and forth" then we can come back to this issue.
