### ISSUE TITLE
Adding textures to rotating_cube.py

### ISSUE THREAD

**Issue by adatteq** [vispy/vispy#2318]
Hello,

I started vispy recently, it seems hard to find any kind of tutorial so I am not sure I get exactly how it works, especially with the part at the beginning of some projects, declared with // which looks like declaring attributes. My question is, would it be possible to add texture handling for rotating_cube.py? My ultimate goal would be to be able to apply an image as textures on each face of the cube. Maybe even makes the textures vary over time.

Thanks for your help!
Best.

**Comment by djhoese** [comment]
Welcome! To give you the best help, I have some questions that I'd like to you to answer.

1. What is your python or general programming experience (1 (beginner) - 10 (expert))?
2. How experienced are you with OpenGL?
3. Are you hoping to use the low-level "gloo" interface or would the higher-level "SceneCanvas" interface work for you?

The rotating cube example (at least this one https://vispy.org/gallery/gloo/rotate_cube.html#sphx-glr-gallery-gloo-rotate-cube-py) that you point to is using the low-level "gloo" interface. As it says in a couple spots in the docs, the gloo interface is really meant for those with OpenGL experience or those wishing to learn more about OpenGL.

If you are hoping to make some shapes and put some textures on them, then the MeshVisual and this example might be an interesting place to start:

https://vispy.org/gallery/scene/mesh_texture.html#sphx-glr-gallery-scene-mesh-texture-py

**Comment by adatteq** [comment]
Hello, 
Thanks a lot!
1. I'd say I am 6-7 maybe.
2. I'm not at all.
3. I think, for now, the easier the better, so the code you sent looks great.

I just have some questions about it:
1. Can I load a file on my computer instead of from git as it is now? Also, are .off files compatible with this code?
2. Can I automate a rotation and save this as gif or video?

Thank you !

**Comment by djhoese** [comment]
1. The files are only loaded from git as a central storage location. You can use whatever you want, it just has to be structured in a similar way. The `read_mesh` function in vispy uses the optional `meshio` dependency to load mesh files and that looks like it supports `.off` files: https://github.com/nschloe/meshio
2. You can look at other gallery examples that have an animation and use a timer to "play" an animation. Or you can look at this gallery example that calls `.render` on the SceneCanvas directly to get individual frames of the animation: https://vispy.org/gallery/scene/save_animation.html#sphx-glr-gallery-scene-save-animation-py

**Comment by adatteq** [comment]
Thank, I will look at thoses!
