### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ksohan** [vispy/vispy#2331]
https://github.com/vispy/vispy/blob/8531ff37de32747d2830c166c2ee0ae20df027b2/vispy/util/transforms.py#L57

Here the docstring says a `3*3` matrix but the function is returning `4*4` ndarray. Is the docstring wrong?

**Comment by djhoese** [comment]
Looks like a typo in the docstring to me. This was done a long time ago when this function was first created by @larsoner in:

https://github.com/vispy/vispy/pull/793/files#diff-3964f74506fd410533f57b78bcbd2edfe2fd2df4ca1a054b4e4a10d5496a8bbf

Looks like something that just got mixed up in the rewrite. @ksohan How would you feel about making a pull request to fix the typo?

**Comment by ksohan** [comment]
@djhoese Thanks for the quick reply. Yes, I will make a pull request shortly.
