### ISSUE TITLE
hsluv is no longer on PyPI

### ISSUE THREAD

**Issue by pllim** [vispy/vispy#2336]
FYI -- hsluv/hsluv-python#36

As a result, pulling vispy from PyPI only grab 0.6.6 , not 0.10.0

**Comment by djhoese** [comment]
Great...

Oh looks like that issue is closed. One of the maintainers/contributors uploaded a new version. I'll close this, but if you still find you can't get a new version comment here and we'll reopen.

Thank you so much for filing this.
