### ISSUE TITLE
Update example testing to be more flexible

### ISSUE THREAD

**Issue by djhoese** [vispy/vispy#2342]
I'm starting to think that the example test runner needs to be updated to be fancier. Before #2339 it basically just imported the example module, found a Canvas variable in the global namespace and found the Application object attached to that Canvas and iterated a couple times on the event loop. However, it isn't able to find variables inside `if __name__ == "__main__":` blocks which promotes bad script design in our examples.

`sphinx-gallery` is able to do this by doing some tricky stuff with faking the `__main__` module, but I don't think any of this logic is available in a public API. We already generate the website as part of CI and we have a separate CI job for running the examples as "unit tests". I say we either:

1. Remove the CI unit test version of examples and only depend on the website generation as proof that examples work.
2. Copy what we can from sphinx-gallery in order to trick examples into thinking they are running as scripts so we can access information in `if __name__ == "__main__":` blocks.

Thoughts? @larsoner? @vispy/core?

**Comment by larsoner** [comment]
I would just let CircleCI / doc build be the thing that tests examples. It should have nice output for each failure already

**Comment by djhoese** [comment]
I'm going to close this now that #2339 is merged with the initial version of my realtime data visualization examples. In that PR I turned off the individual test environment for running examples. We now depend on the website building entirely for running examples. This has the benefit of using sphinx-gallery to run the example scripts as scripts and not as imported modules. It reduces the difference between what the gallery sees and what users see running the script.
