### ISSUE TITLE
Mouse event behaviour

### ISSUE THREAD

**Issue by tushar5526** [vispy/vispy#2344]
```
    def on_mouse_press(self, event):    
        print(event.buttons)
```

The [docs](https://vispy.org/api/vispy.app.canvas.html?highlight=mouseevent#vispy.app.canvas.MouseEvent) says 

```
buttons[int, …]
The list of buttons pressed during this event.
```

But, pressing the left click returns an empty list and while holding down the left click and pressing other mouse buttons returns the mouse button key [1], [2] etc.

Is it a bug or I am getting something wrong?

I am using `glfw` as my backend.

**Comment by djhoese** [comment]
Can you post a small example script that I can use to try to reproduce and debug this?

**Comment by djhoese** [comment]
Also, you have the documentation wrong. It doesn't say "pressed" it says "depressed". You may want to play with letting go of the button (depressing) and see if that changes the results. However, I think that would make more sense to check on a `on_mouse_release` event handler. I haven't used mouse events heavily for a while so I could be wrong.

**Comment by tushar5526** [comment]
```
import math
from vispy import app, gloo, use

use("glfw")

class Canvas(app.Canvas):

    def __init__(self, *args, **kwargs):
        app.Canvas.__init__(self, *args, **kwargs)
        
    def on_mouse_press(self, event):
        print(event.buttons)

if __name__ == '__main__':
    canvas = Canvas(keys='interactive', always_on_top=True)
    canvas.show()
    app.run()
```

**Comment by djhoese** [comment]
Ok, apparently as a native english speaker I don't know what "depressed" means. It means currently pressed here. See this code:

https://github.com/vispy/vispy/blob/fbf90ebadbdd1054f3bb3bba4cebc7e60e2082f5/vispy/app/base.py#L188

and the other "buttons" related code in that module. I think to get a list of "all buttons pressed right now" you need to do `.buttons` plus `.button`. I would be open to the idea of a pull request that moves the above linked code so `.buttons` always includes `.button` but I can imagine this causing bugs for some people.

**Comment by tushar5526** [comment]
> you need to do `.buttons` plus `.button` 

Yes, that is what I am doing right now. 

> but I can imagine this causing bugs for some people.

We could then just change the docs to reflect the current behaviour if that's the case, but that might get confusing the ` buttons` contains. 

I would prefer adding the `button` currently pressed to the `buttons` list, that would fix and make the behaviour intuitive as well. 

Output like this is what a user would expect.

```
# left press
Press: event.button=1 | event.buttons=[1]
# left release
Release: event.button=1 | event.buttons=[1]
# right press
Press: event.button=2 | event.buttons=[2]
# right release
Release: event.button=2 | event.buttons=[2]
# left press
Press: event.button=1 | event.buttons=[1]
# right press
Press: event.button=2 | event.buttons=[1,2]
# right release
Release: event.button=2 | event.buttons=[1, 2]
# left release
Release: event.button=1 | event.buttons=[1]
```

> I don't know what "depressed" means

I am confused as well about this. I think it means released or "de-pressed" :p

It would be probably better to hear what others have to say on this to figure out the correct behaviour that one would expect.

**Comment by djhoese** [comment]
Thanks @QuLogic. @vispy/core what are your thoughts? Should the MouseEvent `.buttons` include the newly pressed button (the one causing the "press" event)? See my comment above.

...actually @tushar5526 I'm a little confused by your expected output. I would have thought that the "release" event would not include the released button in the `.buttons`. It is no longer pressed so it should no longer be in the list, right? That is, if we're using "depressed" to mean pressed.

**Comment by tushar5526** [comment]
Sorry for the confusion, I was wrong about what "depressed" means, hence my expected output.

> I would have thought that the "release" event would not include the released button in the .buttons. It is no longer pressed so it should no longer be in the list, right? That is, if we're using "depressed" to mean pressed.

Yes, this should be the correct behaviour. 

We can change "depressed" to "pressed" in the docs, to avoid confusion.

**Comment by djhoese** [comment]
> We can change "depressed" to "pressed" in the docs, to avoid confusion.

Agreed. Let's see what others think (@almarklein, @kmuehlbauer, @rougier any experience with mouse events in other applications?)

**Comment by rougier** [comment]
I also learned what "depressed" means and I agree this brings confusion. "pressed" would be much better.

**Comment by almarklein** [comment]
Is "depressed" a common term in the UX world? To be honest I think of a sad mouse button when I hear it.

**Comment by djhoese** [comment]
Ok so I think we've settled on two changes:

1. "depressed" -> "pressed" in the docstring
2. Add the newly pressed button (the one triggering the press event) to the `.buttons` list.

@tushar5526 agreed? how would you like to make a pull request for these changes?
