### ISSUE TITLE
Canvas mostly black and mouse position is translated

### ISSUE THREAD

**Issue by zjoukhadar** [vispy/vispy#2345]
Hi 

I am trying to run some of the vispy examples for the first time and in all of them I am getting a larger canvas than the plotting area and mouse position is somewhat not 1:1 translated to the plotting area. Does any body have some idea on what might be the cause of this?

**Comment by zjoukhadar** [comment]
<img width="800" alt="2022-06-21_13-47-46" src="https://user-images.githubusercontent.com/61852610/174712561-5b7b7a97-4a42-483f-8483-1e769b5790be.png">

**Comment by djhoese** [comment]
Sorry for the late reply. What backend are you using?

Could you please provide the output of running:

```bash
python -c "import vispy; print(vispy.sys_info())"
```

**Comment by zjoukhadar** [comment]
Thank you for your reply

**Comment by djhoese** [comment]
Could you try installing another backend like pyqt (ex. pyqt5 or pyside2)? I don't have time to find the issue right now, but I think there is a known bug in pyglet or the pyglet backend with retina/HiDPI displays or if you're using display scaling through your operating system. If this is the problem, using a PyQt-based backend should work and should at least let us know that the issue you are running into is the known issue.

**Comment by djhoese** [comment]
The #2326 PR whichfixes HiDPI for the pyglet backend was just merged. Could you try installing vispy from the `main` branch and see if this fixes your issues?

**Comment by zjoukhadar** [comment]
Hi @djhoese 

Thanks, yes using pyglet backend did fix the issue. Thank you.

**Comment by djhoese** [comment]
Do you mean pyqt? Or did you try the new `main` branch?

**Comment by zjoukhadar** [comment]
No, I did not try the main branch. However, I did `conda install -c conda-forge pyglet` then added `vispy.app.use_app("pyglet")` which fixed the issue.

**Comment by djhoese** [comment]
Hm, I'm not sure I understand what was fixed but OK. Glad you got it working.
