### ISSUE TITLE
 I set the x, y, z values ​​of visuals.Text() to change whenever the mouse moves. However, the text is overlapped.

### ISSUE THREAD

**Issue by bybyeol** [vispy/vispy#2358]
```
import numpy as np
import sys
from PyQt5.QtWidgets import *
import vispy.scene
from vispy.scene import visuals
canvas = vispy.scene.SceneCanvas()
view = canvas.central_widget.add_view()


class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        view.add(visuals.GridLines())
        view.camera = 'turntable'
        button = QPushButton('Button')
        button.clicked.connect(self.openfile)
        vbox = QVBoxLayout()
        vbox.addWidget(canvas.native)
        vbox.addWidget(button)
        self.setLayout(vbox)
        self.setWindowTitle('3D point cloud')
        self.setGeometry(600, 207, 800, 600)
        view.camera.center = (0, 0, 0)
        self.show()
        axis = visuals.XYZAxis(parent=view.scene)
    def openfile(self):
        QFileDialog.getOpenFileName(self, 'Open file', './')

    @canvas.events.mouse_press.connect
    def on_mouse_press(event):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(event.pos)
        print(x, y, z)
    @canvas.events.mouse_move.connect
    def on_mouse_move(event):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(event.pos)
        x_text = 'X: %s ' % x
        y_text = 'Y: %s ' % y
        z_text = 'Z: %s' % z
        xyztext = x_text + y_text + z_text
        visuals.Text(xyztext, color = 'white', anchor_x ='left', parent = view, pos=(20, 30))

    def update_text(self):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(self.pos)
        x_text = 'X: %s ' % x
        y_text = 'Y: %s ' % y
        z_text = 'Z: %s' % z
        visuals.Text(x_text + y_text + z_text, color='white', anchor_x='left', parent=view, pos=(20, 30))
        self.update()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyApp()
    sys.exit(app.exec_())

```

**Comment by bybyeol** [comment]
![스크린샷, 2022-07-19 01-33-53](https://user-images.githubusercontent.com/78771202/179559669-88c65b27-8ace-4409-9742-3780be16a794.png)

**Comment by djhoese** [comment]
Thanks for making the issue. You should try creating the TextVisual once and then in the update method call `.set_data` on it to change the text. By doing it your way currently you are creating a new TextVisual every time.

**Comment by djhoese** [comment]
Oops, sorry, it isn't `.set_data` it is a `.text = "new text"` property.

**Comment by bybyeol** [comment]
do you make it like this?
import numpy as np
import sys
from PyQt5.QtWidgets import *
import vispy.scene
from vispy.scene import visuals
canvas = vispy.scene.SceneCanvas()
view = canvas.central_widget.add_view()


class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        view.add(visuals.GridLines())
        view.camera = 'turntable'
        button = QPushButton('Button')
        button.clicked.connect(self.openfile)
        vbox = QVBoxLayout()
        vbox.addWidget(canvas.native)
        vbox.addWidget(button)
        self.setLayout(vbox)
        self.setWindowTitle('3D point cloud')
        self.setGeometry(600, 207, 800, 600)
        view.camera.center = (0, 0, 0)
        self.show()
        axis = visuals.XYZAxis(parent=view.scene)
    def openfile(self):
        QFileDialog.getOpenFileName(self, 'Open file', './')

    @canvas.events.mouse_press.connect
    def on_mouse_press(event):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(event.pos)
        print(x, y, z)
    @canvas.events.mouse_move.connect
    def on_mouse_move(event):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(event.pos)
        x_text = 'X: %s ' % x
        y_text = 'Y: %s ' % y
        z_text = 'Z: %s' % z
        xyztext = x_text + y_text + z_text
        visuals.Text(xyztext, color = 'white', anchor_x ='left', parent = view, pos=(20, 30))

    def update_text(self):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(self.pos)
        visuals.Text = "new text"
        x_text = 'X: %s ' % x
        y_text = 'Y: %s ' % y
        z_text = 'Z: %s' % z
        visuals.Text(x_text + y_text + z_text, color='white', anchor_x='left', parent=view, pos=(20, 30))
        self.update()
if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyApp()
    sys.exit(app.exec_())

**Comment by djhoese** [comment]
Try using three backticks before and after your code blocks and make sure the three backticks are on their own lines (not on the same line as your code). I'm not sure how this code is different than your original code?

**Comment by bybyeol** [comment]
import numpy as np
import sys
from PyQt5.QtWidgets import *
import vispy.scene
from vispy.scene import visuals
canvas = vispy.scene.SceneCanvas()
view = canvas.central_widget.add_view()


class MyApp(QWidget):
    def __init__(self):
        super().__init__()
        self.initUI()

    def initUI(self):
        view.add(visuals.GridLines())
        view.camera = 'turntable'
        button = QPushButton('Button')
        button.clicked.connect(self.openfile)
        vbox = QVBoxLayout()
        vbox.addWidget(canvas.native)
        vbox.addWidget(button)
        self.setLayout(vbox)
        self.setWindowTitle('3D point cloud')
        self.setGeometry(600, 207, 800, 600)
        view.camera.center = (0, 0, 0)
        self.show()
        axis = visuals.XYZAxis(parent=view.scene)
    def openfile(self):
        QFileDialog.getOpenFileName(self, 'Open file', './')

    @canvas.events.mouse_press.connect
    def on_mouse_press(event):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(event.pos)
        print(x, y, z)

    @canvas.events.mouse_move.connect
    def on_mouse_move(event):
        tr = canvas.scene.node_transform(view.scene)
        x, y, z, _ = tr.map(event.pos)
        """visuals.Text = "new text"""
        x_text = 'X: %s ' % x
        y_text = 'Y: %s ' % y
        z_text = 'Z: %s' % z
        xyztext = x_text + y_text + z_text
        visuals.Text(xyztext, color = 'white', anchor_x ='left', parent = view, pos=(20, 30))
        """view.update()"""

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = MyApp()
    sys.exit(app.exec_())

**Comment by bybyeol** [comment]
Added visuals.Text = "new text" and view.update().

**Comment by djhoese** [comment]
Not really what I was thinking. The `.text` property I was talking about is part of the `visuals.Text` object you create. I've rewritten your example using some modern Python features that clean it up a bit. The main important change is that I make a `visuals.Text` object and assign it to `self.text`. Then in the mouse move handler I set `self.text.text` (the `.text` property of the `Text` visual object).

For some reason I had trouble using the event `.connect` decorator with your class so I installed called it manually in the `__init__` method.

**Comment by djhoese** [comment]
I've updated your code example with the three backticks. If you go to "Edit" your comment you can see what I mean about using three backticks for code formatting on github.

**Comment by bybyeol** [comment]
Thank you for answer. I had a lot of difficulties using Python for the first time, but it helped a lot. Have a good day. : )

**Comment by djhoese** [comment]
Glad that works for you. You may want to consider moving your canvas and view creation into your class (ex. `self.canvas = SceneCanvas(...)`) in the future. This may help you in the future with integrating your custom code into a larger Qt-based GUI.
