### ISSUE TITLE
vispy/visual/tube.py does not support python 3

### ISSUE THREAD

**Issue by tralfaz** [vispy/vispy#2369]
It looks like this is specific to python 3.10 and later.

At line 68:

 if not isinstance(radius, collections.Iterable):

This only works for python 2.6 or 2.7.

For python 3 the line would be

 if not isinstance(radius, collections.abc.Iterable):

Or to work with both python 2 and python 3

import sys
if sys.version_info.major > 2:
   from collections.abc import Iterable
else:
   from collections import Iterable

Then change line 68 to:

 if not isinstance(radius, Iterable):

FYI

Michael

**Comment by djhoese** [comment]
This is...very strange.

This example uses the TubeVisual:

https://vispy.org/gallery/scene/marker_spheres.html#sphx-glr-gallery-scene-marker-spheres-py

and was built in a Python 3.9 environment:

https://github.com/vispy/vispy/runs/7997191272?check_suite_focus=true

And succeeded (as it generated the image). :confused:

**Comment by djhoese** [comment]
Ah, the move happened a long time ago (Python 3.3) but wasn't actually removed until Python 3.10. We don't need to support Python 2 or even old versions of Python 3. @tralfaz how would you feel about making a pull request?

**Comment by tralfaz** [comment]
No problem doing that, but I think it costs next to nothing to support aa wide a range of python versions as possible.  Though a bit ugly.

Either by using sys.version_info check or try import except clause.  Python 2 is rapidly becoming a thing of the past, but its still hard for some to move on.

—mdm

**Comment by djhoese** [comment]
We don't support Python <3.7:

https://github.com/vispy/vispy/blob/main/setup.py#L95

And there are way too many parts of VisPy that would have to be changed to support anything older, but more importantly the maintenance burden is not worth it to support users that want new features without upgrading all parts of their environment.

**Comment by tralfaz** [comment]
OK that makes it a simple one liner, but I’ll grep through the code for other instances.

Ran into issue in my VisPy sandbox https://github.com/tralfaz/GUTS <https://github.com/tralfaz/GUTS> :-)

—mdm

**Comment by djhoese** [comment]
Looks like we forgot to close this when #2370 was merged. This should be fixed now. Thanks again.
