### ISSUE TITLE
3D Line Plot Visual set new data issue

### ISSUE THREAD

**Issue by PanagiotisMenounos** [vispy/vispy#2373]
Dear All,

Just starting with vispy and i am really struggling to update a plot with new data.
I have created a temporary repo to demonstrate the issue: [github_repo](https://github.com/PanagiotisMenounos/visPy_test)

[main.py](https://github.com/PanagiotisMenounos/visPy_test/blob/main/src/main.py)

[Pyqt5 widget](https://github.com/PanagiotisMenounos/visPy_test/blob/main/src/designer_plot.py)

Any idea why .set_data causes below warning?
>   File "C:\Users\Panagiotis\Desktop\visPy_test\venv\lib\site-packages\vispy\visuals\line_plot.py", line 85, in set_data 
bad_keys = set(kwargs) - self._valid_kwargs 
AttributeError: 'numpy.ndarray' object has no attribute '_valid_kwargs'

**Comment by djhoese** [comment]
I saw you commented on the video twice and deleted your comment. I had actually written up a reply to your issue and you deleted your comment right before I hit the "Comment" button. I then answered your email you sent to me...and now I'm pasting that reply here. Just pick one form of communication and stick with it :wink: 

Shorter version of my comment is: Don't use "create_visual_node" here:

https://github.com/PanagiotisMenounos/visPy_test/blob/b8f1eebd523b1c26f7cc03fdb5d2a4c636ae2688/src/designer_plot.py#L19

The `create_visual_node` function returns a new version of the Visual class. But this is already done in `vispy.scene.visuals` so you can use `vispy.scene.visuals.LinePlot` directly. Note that `vispy.visuals.LinePlotVisual` should be used with regular "Canvas" applications, while `vispy.scene.visuals.LinePlot` should be used with "SceneCanvas" applications.  When you use that class here:

https://github.com/PanagiotisMenounos/visPy_test/blob/main/src/main.py#L32

You need to assign the result (an instance of the LinePlot class):

self.my_plot = self.designer_plot.Plot3D(self.pos, width=8.0, ...)

Or even simpler:

self.my_plot = vispy.scene.visuals.LinePlot(self.pos, width=8.0, ...)

Let me know if that doesn't work by replying to this email. And yes, in the future filing an issue on vispy's github would be a good start.

**Comment by PanagiotisMenounos** [comment]
Thank you very much for fast reply, the issue is now solved with your suggestion and sorry for reaching you by youtube it was not good idead that is why i deleted my coments.
I will stick with github issues so everyone can benefit. 
Below is final code:

widget:

`from vispy import visuals, scene
from vispy.color import ColorArray
from PyQt5.QtWidgets import*

class Designer_plot(QWidget):
    def __init__(self, parent = None):
        QWidget.__init__(self, parent)
        self.canvas = scene.SceneCanvas(parent=self,keys='interactive', title='plot3d', show=True, bgcolor = ColorArray('black'))

        # Add a ViewBox to let the user zoom/rotate
        self.view = self.canvas.central_widget.add_view()
        self.grid = scene.visuals.GridLines(parent=self.view.scene, scale=(1, 1))
        self.view.camera = 'turntable'
        self.view.camera.fov = 25
        self.view.camera.distance = 60

        # plot
        self.Plot3D = scene.visuals.LinePlot`  

main:

`import numpy as np
from PyQt5 import QtWidgets
from PyQt5.QtCore import Qt
from vispy.color import ColorArray

import sys

from mainwindow import Ui_MainWindow

    
class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.setupUi(self) #import Qtdesigner
        self.x = np.array([1, 2, 3, 6])
        self.y = np.array([1, 2, 3, 4])
        self.z = np.array([1, 2, 3, 9])
        self.pos = np.c_[self.x, self.y, self.z]
        self.my_plot = self.designer_plot.Plot3D(self.pos, width=8.0, color=ColorArray('#3792cb'), marker_size=0, edge_color='r', symbol="disc", face_color=(0.2, 0.2, 1, 0.8), parent=self.designer_plot.view.scene)
        self.update_button.clicked.connect(self.update)

    def update(self):
        self.xx = np.array([4, 2, 4, 6])
        self.yy = np.array([3, 7, 3, 80])
        self.zz = np.array([2, 8, 3, 9])
        self.pos = np.c_[self.xx, self.yy, self.zz]
        self.my_plot.set_data(self.pos)

if __name__ == "__main__":
    QtWidgets.QApplication.setAttribute(Qt.AA_EnableHighDpiScaling) 
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())`  

By the way, is it possible for lines to be pressented with 3D visuals like "cables" or "tubes"?
