### ISSUE TITLE
MatrixTransform.rotate

### ISSUE THREAD

**Issue by zhu2900000** [vispy/vispy#2379]
hello,
How to rotate visuals.Box only one axis at the specified position
exp:rotate(20,[10, 50, 30]) 
I can rotate 30 degrees on the z-axis, but x and y will rotate along with it.If I don't specify xy, it doesn't rotate along the axis at the specified position。

How should I rotate only one axis at a specified position？

**Comment by djhoese** [comment]
I'm going to be honest, I know almost nothing about proper matrix handling in vispy. Maybe @rougier has an idea. Here's the MatrixTransform method:

https://github.com/vispy/vispy/blob/6b9d39c8c7ab75ceb7f15ccccef5f0d27eaeeec1/vispy/visuals/transforms/linear.py#L447-L461

and the utility method it uses:

https://github.com/vispy/vispy/blob/6b9d39c8c7ab75ceb7f15ccccef5f0d27eaeeec1/vispy/util/transforms.py#L56-L80

**Comment by zhu2900000** [comment]
> I'm going to be honest, I know almost nothing about proper matrix handling in vispy. Maybe @rougier has an idea. Here's the MatrixTransform method:
> 
> https://github.com/vispy/vispy/blob/6b9d39c8c7ab75ceb7f15ccccef5f0d27eaeeec1/vispy/visuals/transforms/linear.py#L447-L461
> 
> and the utility method it uses:
> 
> https://github.com/vispy/vispy/blob/6b9d39c8c7ab75ceb7f15ccccef5f0d27eaeeec1/vispy/util/transforms.py#L56-L80

hi,
thanks your reply，My problem has been solved.
I bypassed the problem and reversed the order in which the programs were run.
a = MatrixTransform()
a.rotate(0,[0, 0, 1])
a.translate((x,y,z))
Rotate at the origin before determining the specific position.
In this way, the purpose of rotating a certain axis in a specific position can be achieved.

**Comment by djhoese** [comment]
Glad you got it figured out. Thanks for letting us know.
