### ISSUE TITLE
cannot update mesh in canvas

### ISSUE THREAD

**Issue by petaflot** [vispy/vispy#2401]
in ``Canvas.__init__()` I have 

```python
         self.P = Prismoid() # class that draws a part
         points, faces, normals, colors = self.P.get_mesh()
         meshdata = MeshData.MeshData( vertices=points, faces=faces, edges=None)
         self.mesh = scene.visuals.Mesh(
                 meshdata=meshdata,
                 parent=self.view.scene)
```

then in `Canvas.set_data()`:

```python
    self.P.some_parameter = some_value
    points, faces, normals, colors = self.P.get_mesh()
    meshdata = MeshData.MeshData( vertices=points, faces=faces, edges=None)
    self.mesh = scene.visuals.Mesh(
                 meshdata=meshdata,
                 parent=self.view.scene)
```

Display doesn't change ; when I try to rotate/move/zoom the object, it moves as expected (it's still the old version so it doesn't show what I want), and for every mouse event I get

`WARNING: Error drawing visual <Mesh at 0x7f9b67bb0670>` and sometimes also `ERROR: Invoking <bound method SceneCanvas.on_draw of <Canvas (PyQt5) at 0x7f9b850ab280>> repeat 128`

is it possible to update the mesh without restarting the app?

**Comment by djhoese** [comment]
Don't create a new Mesh every time. You want to call `self.mesh.set_data` with your new meshdata. Also, are you calling the `Canvas.set_data` method that you are creating? That method is not a vispy standard method so it won't be called unless you do it explicitly. Also, make sure you are using a SceneCanvas, not the basic Canvas class (I'm sure you are subclassing SceneCanvas but wanted to be sure).

**Comment by petaflot** [comment]
nice, thanks!

**Comment by petaflot** [comment]
oops, I was a little too eager to close: if the dataset is empty, vispy crashes with `ValueError: colors must have 2 or 3 dimensions` ; if I use None for colors instead of an empty array, crash with `IndexError: arrays used as indices must be of integer (or boolean) type`

How can I hide geometry?

**Comment by petaflot** [comment]
achieved the result I wanted by setting `.parent = None` and then back to `.view.scene`

not sure if that's the way to go, but since it works, I'll close again :-)

**Comment by djhoese** [comment]
> not sure if that's the way to go, but since it works, I'll close again :-)

It depends what your overall goal is. If it is to hide the Mesh because you are not using it temporarily then setting .parent to None is the best option. This will remove the Visual from the "scene graph" and avoid it affecting drawing/processing time since it isn't considered as something to be drawn.
