### ISSUE TITLE
timer cannnot update app parameter: "AttributeError: module 'vispy.app' has no attribute 'something'"

### ISSUE THREAD

**Issue by petaflot** [vispy/vispy#2408]
trying to write a vispy/qt app that displays a bunch of lines and triangles based on the output of a script.

I would like my vispy app to be able to reload the script when it has changed, and update the points/triangles without having to restart the entire program (and setting the view back to where it was, amongst others).

I first tried with a timer (which failed), so I added a keyboard shortcut (this works).

```python
def on_timer(event):
        ''' checks file for modifications and reload source script '''
        import os.path
        global slice_file, slice_mtime

        try:
                if os.path.getmtime(slice_file) > slice_mtime:
                        app.reload_slice()
        except NameError:
                # first run at startup
                pass
        except FileNotFoundError:
                # file is probably being rewritten right now..
                pass
        finally:
                try:
                        slice_mtime = os.path.getmtime(slice_file)
                except FileNotFoundError:
                        # file is probably still being rewritten
                        pass

timer = app.Timer(1, connect=on_timer, start=True)
```

I get this error:

```
WARNING: Traceback (most recent call last):
  File "/home/meta/Documents/pulsar/./supervispy.py", line 611, in <module>
    app.run()
  File "/home/meta/_git/vispy/vispy/app/_default_app.py", line 60, in run
    return default_app.run()
  File "/home/meta/_git/vispy/vispy/app/application.py", line 160, in run
    return self._backend._vispy_run()
  File "/home/meta/_git/vispy/vispy/app/backends/_qt.py", line 335, in _vispy_run
    return exec_func()
  File "/home/meta/_git/vispy/vispy/app/backends/_qt.py", line 943, in _vispy_timeout
    self._vispy_timer._timeout()
  File "/home/meta/_git/vispy/vispy/app/timer.py", line 160, in _timeout
    self.events.timeout(
  File "/home/meta/_git/vispy/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/meta/_git/vispy/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/home/meta/_git/vispy/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/meta/Documents/pulsar/./supervispy.py", line 568, in on_timer
    app.reload_slice()
AttributeError: module 'vispy.app' has no attribute 'reload_slice'
ERROR: Invoking <function on_timer at 0x7f15e80948b0> for Event
```

the keyboard shortcut calls the same reload_slice() function ; `id(app)` returns the same value wherever I call it.

**Comment by djhoese** [comment]
Are you creating a subclass of the Application class? Where does this `reload_slice` method exist?

Do you have more of your code so I can give you a more detailed answer? In general I think your script goes against standard practice when it modifies or depends upon custom methods being on the app object. Another good sign that things are headed in a wrong direction is this bit of code which should never show up in regular python code in my opinion:

```
        except NameError:
                # first run at startup
                pass
```

Initialize the global to `None` and check for that if you have to. However, I think there might be a better way.

You should have a wrapper for your SceneCanvas/Canvas object. You might also want a QWidget subclass that holds on to your Canvas instance. If your on_timer handling function is moved into the Canvas object then you don't need to worry about global variables (use instance variables). If this script that you are calling/loading takes a decent amount of time then I would suggest having it run in a background thread. You can use Qt signals and slots and/or timers to do the triggering and communication between the main GUI thread and the background thread. You could try using this set of examples as a starting point (which I think you and I have discussed elsewhere):

https://vispy.org/gallery/scene/#realtime-data-tutorial

And here's the youtube video series I did on these examples:

https://youtube.com/playlist?list=PL2OQ8odJIDfPU67ML2k-ldvgtISoxJE8b

The reason `app` refers to the same thing but the methods underneath might not is that `vispy.app` is a module that wraps the underlying `run`/`exec` methods of the applications underneath. It is probably best not to subclass or modify `vispy.app` or even a vispy `Application` instance.

**Comment by petaflot** [comment]
well.. I put together something so you could see for yourself, then read your comment again, and realized that putting the timer in the Canvas worked.

then I moved it to the MainWindow() instance, also worked and made more sense.

changed that `except NameError:` line you don't like to `except TypeError:` (with an extra `self.slice_mtime = None` somewhere in the init), then changed it to `except AttributeError:` and removed the initialization. One line less, I find it cleaner.

thanks!

**Comment by djhoese** [comment]
Sounds like you're moving forward with your project. Glad you got it figured it out.
