### ISSUE TITLE
Demo “Create a Point Cloud” running error

### ISSUE THREAD

**Issue by xjllhy** [vispy/vispy#2414]
https://vispy.org/gallery/scene/point_cloud.html

(t3.py:27):scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, .5), size=5, symbol=symbols)

/Users/xjllhy/Desktop/test/py/pointcloud/t3.py:27: DeprecationWarning: The symbol parameter is deprecated. Use MarkersVisual.symbol instead
  scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, .5), size=5, symbol=symbols)
Traceback (most recent call last):
  File "/Users/xjllhy/Desktop/test/py/pointcloud/t3.py", line 27, in <module>
    scatter.set_data(pos, edge_width=0, face_color=(1, 1, 1, .5), size=5, symbol=symbols)
  File "/Users/xjllhy/opt/anaconda3/lib/python3.9/site-packages/vispy/visuals/markers.py", line 700, in set_data
    self.symbol = symbol
  File "/Users/xjllhy/opt/anaconda3/lib/python3.9/site-packages/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/Users/xjllhy/opt/anaconda3/lib/python3.9/site-packages/vispy/visuals/markers.py", line 750, in symbol
    if symbol == self._symbol:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by djhoese** [comment]
Could you please provide the output of running:

```bash
python -c "import vispy; print(vispy.sys_info())"
```

**Comment by djhoese** [comment]
Ah there is a good chance that providing more than one symbol is a new feature that hasn't been released yet. @brisvag added it in https://github.com/vispy/vispy/pull/2361

For now @xjllhy you can remove the `symbols=` keyword argument from the example code and you should be able to see something.

**Comment by xjllhy** [comment]
> Ah there is a good chance that providing more than one symbol is a new feature that hasn't been released yet. @brisvag added it in #2361
> 
> For now @xjllhy you can remove the `symbols=` keyword argument from the example code and you should be able to see something.

Thanks！
