### ISSUE TITLE
Is DPI utils refer to PPI?

### ISSUE THREAD

**Issue by nnop** [vispy/vispy#2450]
As my understanding, a digital screen only have **PPI**(Pixel per inch). **DPI**(dots per inch) is a term used for physical printing device. 
So, is the DPI related utils actually refer to the **PPI**?
https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/vispy/util/dpi/_linux.py#L37-L49

**Comment by djhoese** [comment]
I could be wrong about this, but this is really up to the tools we are using/calling to get the DPI information from the system. For example in the file you linked to there is xdpyinfo and xrandr. We use whatever they provide and it may be different for Windows and OSX, but...

Typically DPI is equivalent to PPI from what I understand and the terms are used interchangeably by most graphic visualization software. Even if it is wrong, we aren't the ones to convince. I found this (possibly old) Nvidia page that uses them as the same thing: http://http.download.nvidia.com/XFree86/Linux-x86/1.0-8178/README/appendix-y.html
