### ISSUE TITLE
How to add an interactive overlay ViewBox?

### ISSUE THREAD

**Issue by nnop** [vispy/vispy#2452]
I want an standalone interactive `ViewBox` overlay the `central_widget`. Here is what I first failed try:
```python
from vispy import app
from vispy.scene import SceneCanvas, visuals, Widget, ViewBox

canvas = SceneCanvas(keys='interactive', bgcolor='w', show=True, size=(1000, 500))
# main view
view1 = canvas.central_widget.add_view()
view1.camera = 'turntable'
axis1 = visuals.XYZAxis(parent=view1.scene)

# sub view
view2 = ViewBox(pos=(0, 0), size=(500, 500), bgcolor='k', parent=canvas.scene)
view2.camera = 'turntable'
axis2 = visuals.XYZAxis(width=2, parent=view2.scene)

app.run()
```
The sub view appears, but the visual is not shown and it seems being not interactive.
![image](https://user-images.githubusercontent.com/23091984/218853048-cce5cf0a-2ff8-4811-b7a6-fbe3fb69a917.png)

However, if I wrap it with a `Widget`, the results is OK.
```python
from vispy import app
from vispy.scene import SceneCanvas, visuals, Widget, ViewBox

canvas = SceneCanvas(keys='interactive', bgcolor='w', show=True, size=(1000, 500))

# main view
view1 = canvas.central_widget.add_view()
view1.camera = 'turntable'
axis1 = visuals.XYZAxis(parent=view1.scene)

# sub widget, why this makes things ok?
widget = Widget(pos=(0, 0), size=(300, 300), bgcolor='k', parent=canvas.scene)
# sub view
view2 = widget.add_view()
view2.camera = 'turntable'
axis2 = visuals.XYZAxis(width=2, parent=view2.scene)

app.run()
```
![image](https://user-images.githubusercontent.com/23091984/218853536-d77bc919-6ee3-465d-b1be-6a941fafc4c4.png)

To my understanding, the `ViewBox` is a subclass of `Widget`, so it should be a `Widget`. Why do I have to wrap the view box with another widget?

**Comment by djhoese** [comment]
After a quick skim of the code my best guess is that `central_widget` is a Widget itself and when you do `add_view()` you're creating a ViewBox whose parent is the `central_widget` widget *not* the `canvas.scene`.

https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/vispy/scene/canvas.py#L170-L172

https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/vispy/scene/widgets/widget.py#L457-L465

https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/vispy/scene/widgets/widget.py#L424-L445

**Comment by nnop** [comment]
Thanks for responding, David.

My confusion is about the `view2`. That doesn't not seems explains why would I have to create a separate widget for `view2`?
```py
# sub widget
widget = Widget(pos=(0, 0), size=(300, 300), bgcolor='k', parent=canvas.scene)
# sub view
view2 = widget.add_view()
```
Specifically, could you explain what the difference with just doing this:
```py
view2 = ViewBox(pos=(0, 0), size=(500, 500), bgcolor='k', parent=canvas.scene)
```

**Comment by djhoese** [comment]
That's what I was trying to address. You have this line in your first example:

```
view2 = ViewBox(pos=(0, 0), size=(500, 500), bgcolor='k', parent=canvas.scene)
```

where the parent is `canvas.scene`. However, if you compare this with how `view1` is created via `canvas.central_widget.add_view()` this is actually creating the ViewBox (view1) with parent set to `canvas.central_widget` (a Widget). I think if you change `canvas.scene` to `canvas.central_widget` in your above `ViewBox` creation it might work. That said, I think you could just do `canvas.central_widget.add_view(**kwargs)` to get the same result instead of manually creating `ViewBox` explicitly.

**Comment by nnop** [comment]
Adding view box to `central_widget` fully overlap the whole window.
```py
view2 = canvas.central_widget.add_view(pos=(0, 0), size=(300, 300), bgcolor='k')
```
![image](https://user-images.githubusercontent.com/23091984/218923293-5d994107-c21f-4cd0-9b5b-1fe088d7c6e5.png)

If only changing the parent to `canvas.central_widget`, the result is not interactive and the axis is not shown.
```py
view2 = ViewBox(pos=(0, 0), size=(300, 300), bgcolor='k', parent=canvas.central_widget)
```
![image](https://user-images.githubusercontent.com/23091984/218924595-6088554b-278f-432c-8aad-f95f9de139ee.png)

**Comment by djhoese** [comment]
Based on this example:

https://vispy.org/gallery/scene/background_borders.html#sphx-glr-gallery-scene-background-borders-py

I got this to work:

```python
from vispy import app
from vispy.scene import SceneCanvas, visuals, Widget, ViewBox

canvas = SceneCanvas(keys='interactive', bgcolor='w', show=True, size=(1000, 500))
grid = canvas.central_widget.add_grid(spacing=0, bgcolor='gray')

# main view
view1 = grid.add_view(row=0, col=1)
view1.camera = 'turntable'
axis1 = visuals.XYZAxis(parent=view1.scene)

# sub view
view2 = grid.add_view(row=0, col=0, size=(500, 500), bgcolor='k')
view2.camera = 'turntable'
axis2 = visuals.XYZAxis(width=2, parent=view2.scene)

app.run()
```

I'm sure with some kwargs you could get the exact look you want with this idea. I think your original approach wasn't working because the two views were competing for "main widget".

**Comment by nnop** [comment]
Grid can't achieve overlapping image above.

**Comment by djhoese** [comment]
Ah sorry. I probably won't have time to look at this today, but I'll keep it on my TODO list for the next couple days.

**Comment by djhoese** [comment]
Ok I think I just noticed something. First, your original code and the `parent=canvas.central_widget` seem to produce almost the same result even though they technically have different parents. And it isn't that the black viewbox isn't responsive, it is that it is not positioned/viewed correctly. If you resize the window then things seem to "pop" into place and the XYZAxis objects in both views move. Now let's see if I can figure out why a resize is required...

**Comment by djhoese** [comment]
And just to make sure, you want the first view to be covered up by the second view?

**Comment by djhoese** [comment]
If I change the `ViewBox` creation to not include the `parent=` kwarg and instead set the parent after it works. For example:

```
view2 = ViewBox(...)
view2.parent = canvas.central_widget
```

It isn't clear to me what's going on. I get a similar fix if I do `view2._update_scene_clipper()`.

**Comment by djhoese** [comment]
Yeah I can't figure this out. There is something lost in communication when the parent is assigned during `__init__` of the ViewBox versus set later. It definitely has something to do with the `_clipper` object which also has something to do with the hierarchy of the objects, but I get lost in tracking down who should do what first.

Current workaround is to set parent for a custom ViewBox like this *after* it is created.

**Comment by nnop** [comment]
Thanks for the solution.
