### ISSUE TITLE
Canvas.show(run=True) returns nothing on Jupyter notebook

### ISSUE THREAD

**Issue by SkandanC** [vispy/vispy#2458]
Running Canvas.show(run=True) on jupyter notebook returns nothing, even thoigh jupyter_rfb is installed and enabled. See here: https://github.com/NanoComp/meep/discussions/2424

**Comment by djhoese** [comment]
@galacticStorm (the user who created that meep discussion) has been commenting on the related issue here: https://github.com/vispy/vispy/issues/2068#issuecomment-1457843406

We may have some more luck continuing the conversation there although the original issue there is closed. I have no experience with WSL and that seems to be the root issue here, right?

Does Canvas.show(run=True) work for other users on other systems (not Windows WSL)?

What version of jupyterlab/jupyter notebook and what version of jupyter-rfb are being installed? @almarklein just made some updates to jupyter-rfb in the last week or two to try to fix compatibility with modern jupyter-widgets/jupyterlab.

**Comment by SkandanC** [comment]
Hello @djhoese,

We can continue the discission there.
