### ISSUE TITLE
no backend in latest colab

### ISSUE THREAD

**Issue by aduchon** [vispy/vispy#2469]
Opening a brand new google colab (GPU or TPU) with simply:
```
!pip install vispy
import vispy
vispy.test()
```
It errors on every backend, ending with 
```
Testing failed (['nobackend'] failed, ['pyqt4', 'pyqt5', 'pyqt6', 'pyside', 'pyside2', 'pyside6', 'pyglet', 'glfw', 'sdl2', 'wx', 'egl', 'osmesa', 'jupyter_rfb', '_test', 'examples'] skipped) in 4.874 seconds
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-1-2164daa7587a>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 import vispy
----> 4 vispy.test()

1 frames
[/usr/local/lib/python3.9/dist-packages/vispy/testing/_runners.py](https://localhost:8080/#) in test(label, extra_arg_string, coverage)
    444     sys.stdout.flush()
    445     if len(fail) > 0:
--> 446         raise RuntimeError('FAILURE')

RuntimeError: FAILURE
```

I hadn't tried using vispy before this week, so I don't know if this ever worked in a colab.  I know other AI-related colabs have recently broken though.   Is there a way to ensure a backend in a colab?

**Comment by djhoese** [comment]
As stated in the install instructions, vispy does not install any backend by default. It is up to the user to install tye necessary dependencies. I don't know what platform colab runs on but you could try installing pyqt and see how that goes. Let us know how it goes.

**Comment by djhoese** [comment]
Feel free to continue to comment here, but I'm not sure this is anything wrong or changed in vispy. Closing now. We can reopen if it turns out to be something needing fixing in vispy.

**Comment by danilw** [comment]
Well this is problem of Vispy it seems, or Google banned single Vispy package from accessing EGL.

```
!pip install vispy

import vispy
vispy.use('EGL')
print(vispy.sys_info())
```

![image](https://user-images.githubusercontent.com/24825887/232853797-02e8668a-e2de-40a4-95da-baaaf15c6098.png)

When on same Colab running moderngl EGL backend - works.

`!pip install moderngl `
and copy example from [moderngl examples](https://github.com/moderngl/moderngl/blob/master/examples/basic_simple_color_triangle.py)

I tried few old versions of Vispy - same result. 
Also tried other backends on Vispy - I have not found any working with OpenGL acceleration working.

**Comment by djhoese** [comment]
Looks like EGL is available but can't be initialized:

![image](https://user-images.githubusercontent.com/1828519/232873892-74d08a88-b1c2-44af-870b-8feb82986cfe.png)

This says to me that something has changed about the EGL installation or that colab used to create a virtual display but doesn't anymore:

https://stackoverflow.com/a/66952101/433202

I'll see if I can learn anything else. I know very little about EGL and no absolutely nothing about moderngl.

**Comment by djhoese** [comment]
How exactly are you running moderngl examples? Did you download moderngl source? The example you linked to imports the relatively available `ported` package in the same directory which accesses a `data` directory in the examples folder.

**Comment by djhoese** [comment]
Looking through moderngl source and its glcontext library I see custom EGL and X11 backends. The X11 default backend doesn't seem to initialize on colab, but EGL does. I'd have to compare their EGL C++ backend to our ctypes EGL backend.

**Comment by djhoese** [comment]
As best I can tell the EGL functions called by `glcontext` are available from a "newer" extension to EGL: https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_platform_base.txt

And are used here: https://github.com/moderngl/glcontext/blob/8a6918336869296565a0cb4a6c7c510f26443762/glcontext/egl.cpp#L208-L237

Vispy's EGL usage does not use (or assume) that this extension is available, but apparently it should as it would make it work in more instances. Here's where Vispy uses these EGL functions:

https://github.com/vispy/vispy/blob/d7763448dd398e5dab91cc21db7378c1aa707c63/vispy/ext/egl.py#L235-L250

CC @almarklein @rougier who I think have more experience with this type of stuff.

**Comment by danilw** [comment]
> How exactly are you running moderngl examples?

`!pip install moderngl`
then copy linked above example https://github.com/moderngl/moderngl/blob/master/examples/basic_simple_color_triangle.py
press Runtime-Run all

![image](https://user-images.githubusercontent.com/24825887/232915618-b6f604f0-ab66-479b-8676-1da726f4bb07.png)
![image](https://user-images.githubusercontent.com/24825887/232915744-9625e669-8454-4f3b-896a-e0832c11ac62.png)

**Comment by danilw** [comment]
> The example you linked to imports the relatively available `ported` package in the same directory which accesses a `data` directory in the examples folder.

**I linked wrong example. sorry.**

Correct example is https://github.com/moderngl/moderngl/blob/master/examples/headless_egl.py
