### ISSUE TITLE
how to delete object from scene

### ISSUE THREAD

**Issue by ericyan71** [vispy/vispy#2473]
if I use scene.Line(...) to create a Line object , then how to delete th line from the scene? thanks

**Comment by djhoese** [comment]
```
line = scene.Line(...)
line.parent = None
```

should do it. This assumes you added the line to the SceneCanvas either by setting the `parent=` kwarg or you added it to a viewbox or widget with `view.add_widget(line)`.

**Comment by ericyan71** [comment]
thanks @djhoese, when I set Line.parent to None, line is unvisible. 
I have another question, setting line's parent to None, the line could still exist, how to delete the line object completely? Do it relate to python, not vispy?

**Comment by djhoese** [comment]
It depends what you're talking about. If you have a SceneCanvas and a LineVisual (`Line` in this case) and you set `.parent = None` it removes the Line from the SceneCanvas' "graph" of things to draw. The `line` variable still holds on to that object, but vispy won't draw it anymore.

You are correct that if you want to get rid of the `line` instance then that's a python problem. You can do `line = None` or do `del line` and Python will garbage collect the LineVisual instance when it gets a chance. Hopefully this makes sense.

**Comment by ericyan71** [comment]
thanks @djhoese, your answer help me, now I can show or hide an object on view, thank you again.
