### ISSUE TITLE
set CompoundVisual.parent=None cause problem

### ISSUE THREAD

**Issue by ericyan71** [vispy/vispy#2479]
hi, I test write a class inherited from CompoundVisual，but when I set it's parent to None, it raise an exception，so I write some simplified code, please do me a favor to check it what cause the exception.

```
import vispy.scene as scene
import vispy.visuals as visuals
import numpy as np
from vispy.scene import PanZoomCamera


class LinesCollection(visuals.CompoundVisual, scene.visuals.VisualNode):
    def __init__(self, subvisuals=[], **kwargs):
        parent = kwargs.pop("parent", None)
        name = kwargs.pop("name", None)
        self.unfreeze()
        visuals.CompoundVisual.__init__(self, subvisuals=subvisuals, **kwargs)
        self.unfreeze()
        scene.visuals.VisualNode.__init__(self, parent=parent, name=name)


if __name__ == '__main__':
    canvas = scene.SceneCanvas()
    view = canvas.central_widget.add_view()
    view.camera = PanZoomCamera(aspect=1)
    canvas.show()

    line = visuals.LineVisual(np.array([(0, 0), (2, 2), (4, 2)]), color='b')
    lc = LinesCollection(parent=view.scene)
    lc.add_subvisual(line)
    # lc.parent = None
    # there is a line shown in view

    view.camera.set_range()
    canvas.app.run()
```
when I uncomment `#lc.parent=None`，a exception was thrown:
```
Traceback (most recent call last):
  File "F:\TECH\Pythons\vis\tests\compoundvisual_add_problem.py", line 27, in <module>
    lc.parent = None
    ^^^^^^^^^
  File "C:\winpython\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\vispy\util\frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "C:\winpython\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\vispy\scene\node.py", line 193, in parent
    self._set_clipper(k, None)
  File "C:\winpython\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\vispy\scene\visuals.py", line 54, in _set_clipper
    self.detach(self._clippers.pop(node))
  File "C:\winpython\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\vispy\visuals\visual.py", line 670, in detach
    v.detach(filt, v)
  File "C:\winpython\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\vispy\visuals\visual.py", line 670, in detach
    v.detach(filt, v)
  File "C:\winpython\WPy64-31101\python-3.11.0.amd64\Lib\site-packages\vispy\visuals\visual.py", line 517, in detach
    view._filters.remove(filt)
ValueError: list.remove(x): x not in list
```

thanks.

(After some trying, I found setting parent to None before add_subvision，it seems works ok, but I don't know why.)

**Comment by djhoese** [comment]
Just to be sure, could you try restructuring your Visual class into two classes: a regular Visual class and then a Visual Node class using the `create_visual_node` function:

https://github.com/vispy/vispy/blob/525504ab61744ef5a50fa06b38298a35f30126c7/vispy/scene/visuals.py#L106

So this would probably means you could remove the entire `__init__` method in your example, rename the class `LinesCollectionVisual` and then afterward do `LinesCollection = create_visuall_node(LinesCollectionVisual)`.

**Comment by djhoese** [comment]
Nevermind, I did these changes and get the same. While this could definitely be handled better, could you explain why you're doing it this way?

**Comment by djhoese** [comment]
FYI I just did another test and using `LineVisual` works *if* you provide it to the `LinesCollection` node object on creation. Doing it after `LinesCollection` already has its parent set will result in the same error.
