### ISSUE TITLE
All mouse events are kept in memory during dragging

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#249]
While dragging the mouse, `event.drag_events()` contains the list of all mouse events. This list can get pretty big when the dragging event is long, resulting in some memory overhead. I'm not sure if that's necessary to keep all those events. I think it would be more convenient to have just the original position.

If one really needs all those events (I'm not sure why they'd want to), they could just do something like `if event.is_dragging: events.append(event)`

**Comment by Eric89GXL** [comment]
I'm going to close this since it seems like this is not impacting performance... @rossant feel free to re-open if you disagree
