### ISSUE TITLE
Add support for OpenGL 3 and 4

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#255]
There are some operations that seemingly cannot be done efficiently with OpenGL 2.1, including 3D textures (see https://groups.google.com/d/msgid/vispy-dev/5374BB62.3070404%40gmail.com), float textures, int vertex buffers, etc. (not to mention all the new shader types)

We need to provide proper support for OpenGL 3 and 4 objects:

* 3D textures
* A wider range of data types for textures and buffers
* Geometry shaders (and, down the road, other shader types as well)
* Vertex array objects
* Full namespace access (issue #185)

We will also have to navigate switching between the various GL APIs we support:

* Can we use a different GL API for each shader program?
* Or do we need the GL API to be consistent across an entire GL context?
* Or do we need the GL API to be consistent across all GL contexts?

The first option is highly preferred (if it is possible at all), because it would allow us to mix GL 2 and GL3/4 objects in a single context. Otherwise, we will be forced to re-implement every visual for every incompatible GL API.

**Comment by Eric89GXL** [comment]
We have this now, closing

**Comment by zhou13** [comment]
I cannot find any document about using OpenGL 3 and 4.  Could anyone give the link to the document?
