### ISSUE TITLE
Question regarding datoviz, backends, gtk

### ISSUE THREAD

**Issue by lucyColeclough** [vispy/vispy#2558]
Hello there, I was not sure if this was better for an issue or an email
I am interested in getting a gpu nd graphing library working for gtk on python.
I attempted to get this working with vispy but ran in to issues listed below.
One thing I presume is that opengl 4.6 used by gtk 4 is not compatible with opengl 2
Gtk does not allow one to specify the profile used when instanciating the gl context, only to query it and also prefers the core profile.
Additionally my calls to glReadPixels were failing whilst using the wayland gtk backend but worked on xorg which is being depracated.

I want to ask, how is the integration with datoviz going? And are there still plans to include custom backend support in vispy 2.0, as datoviz does not have this currently?

All the best, Lucy

**Comment by lucyColeclough** [comment]
Regarding the issues, I am yet to attempt calling /vispy/ext/egl as the _qt backend does
I am also yet to see if any existing offscreen backends like the ipython one work on wayland

**Comment by lucyColeclough** [comment]
I ask about vispy 2.0 as this could circumvent compatability issues, and also could make any work in 1.0 redundant

**Comment by djhoese** [comment]
@rossant is the one who should answer about datoviz and "VisPy 2.0". As far as I know there is no direct work on a vispy -> datoviz compatiblity layer but rather a higher level and more generic protocol for defining visualizations. Any use of it in a operational/user workflow is likely not going to be ready in the near term. I also have zero experience with Wayland compatibility. Sorry.

**Comment by rossant** [comment]
Datoviz is based on Vulkan which does not appear to be supported by GTK (https://discourse.gnome.org/t/how-to-use-vulkan-context-in-gtk4/14997/2).

Also, Datoviz only supports glfw for now. Implementing PyQt support is high priority.

VisPy 2.0 is a medium-term project aiming at rebuilding high-level visualization capabilities on top of Datoviz and other renderers (including possibly VisPy 1.0) via a shared intermediate-level protocol.

So the answer is that unfortunately neither Datoviz nor VisPy 2.0 will allow you to work with GTK, at least not in an easy way.

**Comment by lucyColeclough** [comment]
@djhoese @rossant Thank you both for your clarification.
