### ISSUE TITLE
Memory usage keep increasing

### ISSUE THREAD

**Issue by matthiasho** [vispy/vispy#2585]
Hi.  I am very new to Vispy.  I modified an example to text render 4 running counters (with 4 grids) but I soon realize that there is problem even with 1 running counter.  The display of the counting is okay initially but grind to a halt as more and more memory is being consumed.  I would not call it memory leak, since it could well be incorrect coding, due to my lack of understanding.  Any tips to improve the performance would be much appreciated.  I am on Python 3.10.11, vispy 0.14.2 and OpenGL 4.6.  Here is the code:    

```
import sys
from vispy import app, scene
from vispy.scene.visuals import Text

counting = 0

canvas = scene.SceneCanvas(keys='interactive', show=True)
grid  = canvas.central_widget.add_grid(spacing=0)

viewbox1 = grid.add_view(row=0, col=0, camera='panzoom')
viewbox1.camera.set_range()
t1 = Text('', parent=viewbox1.scene, method= 'gpu') # needed


def update(ev):
    global counting,t1
    counting += 1
    
    t1.pos = 7,50
    t1 = Text( str(counting), parent=viewbox1.scene, color='orange')
    #t1.color= 'orange'
    t1.font_size = 118
    #t1.text = str(counting)
    
#t = app.Timer(interval='auto')
t = app.Timer(interval=0.095)
t.connect(update)
t.start(iterations=60*1000)
t.events.stop.connect(lambda x: app.quit())

if __name__ == '__main__' and sys.flags.interactive == 0:
    app.run()
```

**Comment by djhoese** [comment]
You're creating a new `Text` visual with ever iteration/timer trigger, but the old instances are still sticking around inside vispy (they are all connected to the `viewbox1.scene` parent). Your commented code is more what you want where you change the properties of `t1`. Typically visuals have a `.set_data` method to collect multiple changes at once, but the Text visual doesn't seem to have one so individual properties are the best available for now.

**Comment by aganders3** [comment]
@djhoese is all over it, but here's some code you can try:

```python
import sys
from vispy import app, scene
from vispy.scene.visuals import Text

counting = 0

canvas = scene.SceneCanvas(keys="interactive", show=True)
grid = canvas.central_widget.add_grid(spacing=0)

viewbox1 = grid.add_view(row=0, col=0, camera="panzoom")
t1 = Text("", parent=viewbox1.scene, method="gpu")  # needed
t1.color = "orange"
t1.pos = 7, 50
t1.font_size = 118
viewbox1.camera.set_range()


def update(ev):
    global counting, t1
    counting += 1
    t1.text = str(counting)


t = app.Timer(interval=0.095)
t.connect(update)
t.start(iterations=60 * 1000)
t.events.stop.connect(lambda x: app.quit())

if __name__ == "__main__" and sys.flags.interactive == 0:
    app.run()
```

**Comment by matthiasho** [comment]
Great, the new code works.    I knew I was creating more and more new Text visual but I struggled how to rearrange the code.  The moment I moved some lines of code, I could not achieve the effect I want.  It now make sense to move all color, pos and size setting out of the update.  Many thanks to David and Ashley !

**Comment by matthiasho** [comment]
With the new code, the counter count to 6014 within 2 minutes.  That is about 50 fps.  Is there still something that I can do to make this faster?

**Comment by matthiasho** [comment]
With the new code, the counter count to 6014 within 2 minutes.  That is about 50 fps.  Is there still something that I can do to make this faster?

**Comment by matthiasho** [comment]
@djhoese 
I have already removed the timer interval, that is the reason why I am able to achieve count of 6014 within 2 minutes which is about 50 fps.  The end game is to include 16 or 17 such counters.  Hoping not to end up with 50/16 = 3.125 fps.  Thanks

**Comment by aganders3** [comment]
The timer still has an interval if you don't specify one. It uses `auto`. From [the docs](https://vispy.org/api/vispy.app.timer.html):

> interval
float | ‘auto’
Time between events in seconds. The default is ‘auto’, which attempts to find the interval that matches the refresh rate of the current monitor. Currently this is simply 1/60.

**Comment by matthiasho** [comment]
@aganders3 Thanks.  So what should I change it to, in attempt to speed things up?  The code is now t = app.Timer().  Will t = app.Timer(interval = 0.008333) be faster? (1/120 = 0.008333)

**Comment by aganders3** [comment]
I don't know your requirements well enough. What are you expecting to see with so many counters moving that fast? Is this your goal or is the counter just an attempt to measure fps?

**Comment by matthiasho** [comment]
@aganders3 You are awesome !  I lowered the interval to 0.001333 and the counter now clocked 9801 within 2 minutes.  Yes, there will be multiple counters.  I need this single counter to be super fast, as I expect that by adding more counters, the fps may drop to < 5 to 6 fps.  One further question : Does a smaller font size, result in renderings to be even be faster?

**Comment by aganders3** [comment]
> Does a smaller font size, result in renderings to be even be faster?

I'm not sure. I don't really know much about how the text rendering happens under the hood so I'd probably just test it.

**Comment by djhoese** [comment]
I'd be surprised if it did. Not in any measurable way at least.
