### ISSUE TITLE
ENH: Grid layouts

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#277]
We will need a way to lay out rectangular widgets in grids that resize nicely with the canvas area. Layouts can be a very complex problem, but hopefully that does not mean they must have a complex API. Some features we might like to have:
- Widgets inside a grid may have minimum, maximum, and preferred sizes
- Should be possible to specify that widgets have sizes relative to each other
- Widgets may span multiple rows / columns
- Adding / removing widgets from the layout causes other widgets to adjust dynamically
- HTML table-like features - cell spacing, padding, borders, ...
- User-adjustable boundaries between some rows / columns
- Widgets can also have min / max aspect ratio (but this might be low priority and difficult to implement)

Example: 4 widgets in a row; the first widget has a preferred size of 100px, and min/max of 50 and 150px. The remaining space is divided up between 3 widgets: 50%, 30%, and 20%. In the second row, a single widget has a maximum height of 100px and occupies columns 1-3.

**Comment by njsmith** [comment]
As I was telling @campagnola at the bar last night, I think these days you need a good reason to do layout using anything *other* than something based on Cassowary. (This is also what the matplotlib folks are trying to figure out how to move to, but they have nastier backcompat issues.)

Basically the idea in Cassowary is, your toolkit/user defines a bunch of arbitrary linear inequality constraints ("the left edge of this button must be to the left of the text inside it, and the right edge must be to the right", "these two axes should be the same width", "the left and right edges of this axes should line up with where the points at positions x1 and x2 fall in this other axis after applying that axes's linear view projection"), and then an incremental constraint solver tells you where to put everything to maximally satisfy the constraints and how things should adapt when the window is resized etc. It almost sounds too good to be true, but it's extremely usable in practice; iOS and OS X have been using this as their main layout approach for years now.

Wikipedia: https://en.wikipedia.org/wiki/Cassowary_%28software%29
Quick overview: http://stacks.11craft.com/cassowary-cocoa-autolayout-and-enaml-constraints.html
List of implementations of the constraint solver (pure Python, Python + C++, Javascript, ...): http://overconstrained.io/
Classic paper: https://constraints.cs.washington.edu/solvers/cassowary-tochi.pdf

**Comment by Eric89GXL** [comment]
Sounds like a good approach to me. @njsmith fancy implementing it here? :)

**Comment by almarklein** [comment]
Can we target it with ctypes?

**Comment by MatthieuDartiailh** [comment]
Kiwisolver comes with Python bindings and is in the official conda packages. It is used by enaml for its layout.

**Comment by QuLogic** [comment]
Kiwi has a 1.5 year PR still open for Python 3 support, though.

**Comment by njsmith** [comment]
@Eric89GXL: I appreciate the attempt, but I'm a bit overbooked :-).

There's also the pure python cassowary package -- not a great plan in the long run, but probably sufficient to get a MVP.

**Comment by campagnola** [comment]
Thanks Nathaniel! I checked out the PP implementation and it looks like it
will be straightforward to implement in our grid layouts. If anyone would
like to tinker with this before I get to it, the relevant code is at
vispy/scene/widgets/grid.py:Grid._update_child_widgets().

**Comment by bollu** [comment]
@Eric89GXL: I'm planning on picking this up next. Should I implement the algorithm in Python or use [casuarius](https://github.com/enthought/casuarius) / [pybee-cassowary](https://github.com/pybee/cassowary)?

the [license for pybee-cassowary](https://github.com/pybee/cassowary/blob/master/LICENSE) seems quite relaxed. The JavaScript implementation is Apache, while the Python port has a license that I don't really know which one it is, but seems alright.


Casuarius seems to be LGPL v2.1
>  Casuarius as a whole follows the license of Cassowary itself, LGPL v2.1 or (at your option) a later version of the LGPL. See the files LICENSE and COPYING.LGPL for details.

I would personally like to implement it. I think you meant the same, @campagnola ?

**Comment by Eric89GXL** [comment]
It says that "The original implementation in OTI Smalltalk is in the public domain" -- can you base the work on that? Then we have no licensing issues to deal with.

**Comment by Eric89GXL** [comment]
Oh wait, `pybee-cassowary` looks like the BSD license to me (can you double-check the language)? If so, we're good to use / modify that. We can try putting some minimal form of it in `externals` at first, but if you make substantial modifications then we'll make it part of `vispy` proper somewhere

**Comment by bollu** [comment]
you're right, it's the [BSD-2 License](http://opensource.org/licenses/BSD-2-Clause). And sure, that sounds like a reasonable approach.

**Comment by campagnola** [comment]
This would be awesome. If you take it on, then I'll leave it up to you to decide whether to reuse pybee or write your own implementation. However we should discuss the Widget / Grid API. Things I'd like to be able to do:

* Grid lays out a set of widgets such that they arrange nicely regardless of the window size.
* Widgets can have a minimum size, maximum size, and stretch factor.
* Widgets can span multiple rows and/or columns in the grid. By default, the widget's stretch factor is determined by the number of columns / rows it fills.
* Grids can be nested, and they report an appropriate min/max/stretch based on their contents.
* Cells collapse appropriately if their contents are removed or hidden.

**Comment by bollu** [comment]
I have questions too.

* What exactly is a "stretch factor" and how does it affect the grids? From using it, the current implementation seems to allow it to to apply a scaling factor to the occupied grids.

* What units are the maximum and minimum sizes given in? percentages? unit-less value that gets normalized later? 

*  How would "collapsing" work? would it have to animate? What happens when a collapsed cell is inflated?

**Comment by campagnola** [comment]
> What exactly is a "stretch factor" and how does it affect the grids? From using it, the current implementation seems to allow it to to apply a scaling factor to the occupied grids.

A unitless value used to decide how much space to assign to a widget, in the absence of any other constraints. A widget with SF=2 should get twice as much of the available space as a widget with SF=1.

> What units are the maximum and minimum sizes given in?

Logical pixels.

> How would "collapsing" work? would it have to animate? What happens when a collapsed cell is inflated?

Animation is not necessary. If a widget is hidden, then the grid should resize its widgets as if the hidden widget were never added. Likewise adding a widget to a previously empty cell should give exactly the same result as if the cell had been filled by that widget from the beginning--all other widgets are resized accordingly to make space.

**Comment by kmuehlbauer** [comment]
Closing since Cassowary was implemented in the `Grid` with #1049. Please reopen if further discussion is needed.
