### ISSUE TITLE
Bug with ModularProgram: variables not updated

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#299]
In [this example](https://github.com/vispy/experimental/blob/master/cr_plot/bug.py), using the mouse wheel should allow you to zoom in or out. It doesn't work, but it does if the program is reconstructed at every draw (which can be done by setting `_dirty` to `True` all the time for instance).

This example requires the `scenegraph` branch of Vispy.

**Comment by Eric89GXL** [comment]
@rossant this seems to work fine with some minor modifications now, see:

https://gist.github.com/Eric89GXL/09813f4c7a9449d940cc

Feel free to reopen if it doesn't work for you.
