### ISSUE TITLE
ENH: PNaCl backend

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#329]
It is now possible to run a complete scientific python stack client-side in the browser. We should add support for running vispy via this route as soon as possible. 
See: 
https://colaboratory.jupyter.org/welcome/
https://github.com/jupyter/colaboratory/

**Comment by djhoese** [comment]
PNaCl has been deprecated and is being replaced by web assembly. Closing this and if someone has time to work on updating the jupyter widget or making these various web-based versions of VisPy visualizations then we can make separate issues for them.

https://developer.chrome.com/native-client/migration
