### ISSUE TITLE
Q: modular shaders and cache invalidation

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#379]
Here's a little challenge (mostly for @almarklein): Function and ModularProgram work together to make sure that the program is only rebuilt / recompiled when a change is made that actually results in GLSL changes. Setting `func['var'] = value` should _not_ result in a recompile, unless the new value forces the type of the variable to change. So far this works nicely (in my transform-cache branch). 

We run into a problem when using varyings:

```
frag_func['rgba'] = Varying('rgba', dtype='vec4')
vert_func['output_color'] = frag_func['rgba']
```

In this case, `frag_func` becomes invalidated because it is given a new Varying, which may necessitate a name change from the Varying previously assigned there. How can we avoid this invalidation? Options:
1. **Check for pre-existing varyings in `frag_func.__setitem__`.** This does not work because the new Varying has already been created, and `frag_func.__setitem__` has no way of knowing whether the user intends to use this Varying in exactly the same way. For example:
   
   ```
   v = Varying('rgba', dtype='vec4')
   frag_func['rgba'] = v
   # breaks if frag_func internally decides to re-use an old Varying
   vert_func['output_color'] = v  
   ```
2. **Resurrect the old string-method for generating Varyings**. Like:
   
   ```
   frag_func['rgba'] = 'varying vec4 rgba'
   ```
   
   Now `frag_func.__setitem__` knows with certainty that a pre-existing Varying may be used (I think?). I don't like this because calling `Function.__setitem__(key, string_value)` already has a different purpose (to create a `TextExpression`). 
3. **Require user to manually instantiate `TextExpression`**. This is the same as (2), but calling `Function.__setitem__(key, string_value)` will _only_ create Variable instances, and the user must manually instantiate `TextExpressions` if they want that. 
4. Other options?

**Comment by queenish001** [comment]
@campagnola This issue can be closed now I think :)
