### ISSUE TITLE
Add support for n-dimensional data points in gloo

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#390]
Not sure about whether this should be implemented in gloo, or if we should do it manually every time we need it.

Here is the idea. Attributes are limited to 4 dimensions max. Sometimes, you may want more dimensions for your data points. The typical way to do it is to use multiple attributes. It might be interesting to have a semi-automatic way to deal with n-dimensional data points in GLSL/gloo.

Instead of manually creating `a_position_0, a_position_1`, etc. for every component, this could be handled automatically by Vispy (automatic creation of the component attributes, automatic creation of the vertex buffer with the appropriate data type).

``` python
        """
        attribute float<16> a_position; // shortcut for a_position_0, a_position_1, ..., a_position_15
        void main() {
            // here, a_position_0, a_position_1, etc. are defined
        }
        """

        v_position = rand(1000, 16)
        program['a_position'] = v_position  # bind each column #i to a_position_<i>
```

**Comment by djhoese** [comment]
It seems like there was some confusion on the original request for this. As far as I can tell the request is either:

1. A shorthand for expanding a shader to include multiple attributes to support N dimensional attribute values.
2. A shorthand to create other GL objects to mimic N dimensional attribute values.
3. Something else I'm not seeing

Regardless, I think there are existing solutions in OpenGL or just plain python that can solve this if needed and none of them require special GLSL syntax for vispy to support and maintain and for vispy users to learn:

1. Use some type of Buffer
2. Use some type of texture where really high numbers of dimensions can be encoded/flattened into a 1D/2D/3D shaped texture.
3. Use Python string formatting to slip in some fancy numbered attribute names in the usage.

Given this, I don't think this is something vispy should add support for explicitly. If someone thinks this will be useful to more than one user then feel free to pick it up. For now though, I'm closing this (feel free to reopen).
