### ISSUE TITLE
Slight lack of fluidity on some demos

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#395]
I observe this issue in #391, but it might occur on other demos too. When there is an animated visualization with a fast and smooth movement (60 FPS timer), I can observe a very slight lack of fluidity, with the object's movement being slightly "jerky" (roughly 2 "jumps" per second). I don't know if it's a general issue with Vispy/OpenGL/Windows/screen/etc., or if it only occurs on my laptop/GPU, or just with the Qt backend, etc. 

It's not that inconvenient, but I'm just curious to know what causes it, and whether someone can reproduce this issue too.

**Comment by kmuehlbauer** [comment]
@larsoner I can't reproduce this now. Is this still an issue nowadays?

**Comment by larsoner** [comment]
We can reopen if we see it again
