### ISSUE TITLE
Terminology in vispy.scene

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#398]
I'm trying to understand the scene system. Is there an up-to-date document somewhere explaining clearly and with illustrations on one example the different abstractions like Scene, SubScene, ViewBox, Camera, Widget, Visual, etc.? I think such a document would be quite helpful. This system appears really powerful and flexible, but it needs really good documentation so that users can benefit from it.

Also, I'm wondering whether the terminology for all those components is definitive or not? I think that finding good names is really important here, because a good name can explain what an abstraction does, but a bad name is likely to lead to a lot of confusion.

In particular, I don't completely understand the difference between the ViewBox and the Camera, but maybe that's due to terminology? From my understanding, the ViewBox is equivalent to a "camera" in everyday terms, whereas Vispy's `Camera` is actually more a `Lens`?

Also, I hope we can find a better name than `SubScene`, although I don't see a good alternative right now.

**Comment by kmuehlbauer** [comment]
The wiki page [Tech.-Visuals-and-scene-graph](https://github.com/vispy/vispy/wiki/Tech.-Visuals-and-scene-graph) was added some days after this discussion. 

Assuming that this wiki page has the answers to this question. Closing. Reopen if necessary.
