### ISSUE TITLE
Underscore for private objects

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#399]
I see many modules and function names starting with underscores because they're private. In some occasions, I find this convention slightly overused and cumbersome, and I think that omitting the underscore might enhance readibility sometimes (for example in `vispy.color` or `vispy.util`, the latter looking not very consistent across its files). Besides, I have the feeling we're not always consistent across the different subpackages, but maybe that's just me.

I'm not sure where to draw the line. Should we put an underscore for all modules, functions, classes, that are not supposed to be part of the documented API? For example, should `VispyRenderer` in `mpl_plot` be `_VispyRenderer`? Following such a convention too strictly might not be a good idea in terms of readability. I would argue that it's okay to have some modules or classes that are not supposed to be used in common use cases, not starting with an underscore.

Anyway, I'd be interested to have the opinion of other developers here.

**Comment by kmuehlbauer** [comment]
There is a section about *private stuff* Coding Guidelines in the [wiki](https://github.com/vispy/vispy/wiki/Code.-Guide#private-stuff). 

@larsoner Should some of the discussion be reflected in that wiki-page?

**Comment by davidh-ssec** [comment]
I've mentioned this else where or at least I meant to, but I think there may need to be a decision about subvisuals and if they are private or not. Like a PolygonVisual or a PlotWidget that have `self._line`, but there are things that a user might want to access/modify about those subvisuals that aren't made available in the parent visual/widget. Either the interface needs to make things more available or the subvisual shouldn't have the underscore or users need to get over it.

**Comment by larsoner** [comment]
I think it's okay to expose the subvisuals without the `_`. Maybe in the docstring for the property say that messing with them can possibly lead to an inconsistent state.

**Comment by kmuehlbauer** [comment]
@davidh-ssec This was here https://github.com/vispy/vispy/pull/1292

**Comment by queenish001** [comment]
@rossant Can this issue be closed now :) ?

**Comment by djhoese** [comment]
Given recent work like that by @brisvag in #2227 this has gone even further where shaders have been made available as "private" class attributes for easier subclassing. I think this can be closed and is in general an ongoing issue. My preference is `_` for anything that isn't meant for regular users (subclass-ers are not regular users necessarily so this is a grey area).
