### ISSUE TITLE
Reimplement realtime_signals example with vispy.scene

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#401]
It might be a good test case for `vispy.scene`. We could have both versions in `examples/demo`, one in `gloo`, one in `scene`.

**Comment by kmuehlbauer** [comment]
I'm not really sure, what should be shown here.

We have the [demo/gloo/realtime_signals.py](https://github.com/vispy/vispy/blob/master/examples/demo/gloo/realtime_signals.py) which shows every line in a different color and [demo/scene/scrolling_plots.py](https://github.com/vispy/vispy/blob/master/examples/demo/scene/scrolling_plots.py) which show every line in white. But colors can be added there on a per line basis.

Can this be closed then? @larsoner
