### ISSUE TITLE
Prevent SubScene to have multiple parents

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#402]
I thought that I already mentioned this somewhere, but I cannot find it back. 

The problem with the current camera system is that the camera is an attribute of the ViewBox, but it sets the transform of the ViewBox.Scene. Consequently, if a SubScene is shared between multiple ViewBoxes, their ameras will fight to set the transform of that subscene. Therefore, each SubScene should be restricted to have one parent (and it must be a ViewBox).

**Comment by kmuehlbauer** [comment]
The codebase has changed quite substantially since this report. Also the multiparenting was removed with a601556327851ef520ee72dc929c5b7426e0b501. Closing? @larsoner

**Comment by larsoner** [comment]
Yes sharing is broken and would require a lot of refactoring, and there is an issue for it already IIRC
