### ISSUE TITLE
Arrow visuals

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#417]
Arrows can be implemented in the fragment shader (see [demo](https://www.shadertoy.com/view/ldlSWj) and [implementation with Glumpy](https://github.com/rougier/glumpy/blob/master/examples/gloo-arrows.py)). We could have:
- A simple `ArrowVisual` showing one or several arrows, using point sprites and GLSL arrows in the fragment shader.
- A full quiver plot visual, with the entire plot implemented in the fragment shader (see the link above).

**Comment by kmuehlbauer** [comment]
We have [ArrowVisual](https://github.com/vispy/vispy/blob/master/vispy/visuals/line/arrow.py) and the [QuiverPlot](https://github.com/vispy/vispy/blob/master/examples/demo/gloo/quiver.py). 

Looks like we can close this? @larsoner
