### ISSUE TITLE
New example: grid plot with individual zooming

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#434]
Porting [this example from glumpy](https://github.com/rougier/glumpy/blob/master/examples/collection-custom-lines.py). Requires @rougier's collections (#410).

Further examples that could be ported to Vispy:

https://github.com/rougier/glumpy/blob/master/examples/snippet-cubes.py
https://github.com/rougier/glumpy/blob/master/examples/snippet-lines.py

**Comment by QuLogic** [comment]
2 of 3 links are broken...

**Comment by campagnola** [comment]
This is already possible in the current scenegraph (although it is slow), and in #928 it is a lot faster. At some point we can speed it up further with collections, but perhaps this can be closed with #928?
