### ISSUE TITLE
Remove the `--vispy-` prefix in command-line options

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#440]
As we add more options to the command-line interface, having to type the `--vispy-` prefix everytime becomes cumbersome. However, this is required to avoid potential conflicts with third-party applications using their own command-line interfaces with Vispy.

Maybe a solution could be to:
- remove the `--vispy-` prefix in all of our command-line options
- add an option in `Canvas` to disable all Vispy's command-line options, like:
  
  ``` python
  Canvas.__init__(..., enable_cli=False)
  ```

**Comment by kmuehlbauer** [comment]
Discussion stalled long ago. Reopen when necessary.
