### ISSUE TITLE
New example: presentation slides

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#472]
@almarklein has made his EuroSciPy talk entirely in Vispy, using the scene graph to handle slides. It is very nice, because you can easily add interactive plots with `mpl_plot`, videos, images, and any other Vispy visual.

We could take his code, make it an example, and making it so that it can read contents from a Markdown file (for example). This would allow users to write an interactive presentation in Markdown/Python.

**Comment by kmuehlbauer** [comment]
I'll add just a reference to the [euroscipy2014_talk](https://github.com/vispy/euroscipy2014_talk) repo.

Is still consider this a nice addition. Should we make this a milestone?

**Comment by larsoner** [comment]
If you're motivated to work on it, sure

**Comment by kmuehlbauer** [comment]
Not at the moment, I'm afraid.

**Comment by larsoner** [comment]
My vote is to close, and reopen when someone is motivated to work on it.
