### ISSUE TITLE
Make Vispy work on the Raspberry Pi!

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#495]
It supports OpenGL ES 2.0 apparently, as well as Python of course. Using Vispy would make complete sense as Vispy brings power-efficient interactive visualization through efficient use of the GPU.

**Comment by stuaxo** [comment]
SDL may be an option for the Pi too.

**Comment by jars121** [comment]
Has there been in progress made in this space? I.e. has anyone managed to get hardware accelerated VisPy plotting working on a Raspberry Pi?

**Comment by kmuehlbauer** [comment]
Let's bring this issue to new life. Pinging @jars121, @andresbrocco

Lately there were several requests on the gitter-channel on how to get VisPy working on a raspberry pi. But unfortunately nobody did manage it so far.

What I tried in the past, but did not had time to further investigate:

- use [berryconda](https://github.com/jjhelmus/berryconda) on the pi 
  - installed and worked like his linux equivalent
- tried to get [Qt5/PyQT/PyOpenGL recipes working](https://github.com/jjhelmus/berryconda/issues/15)
  - pyopengl was already packaged
  - PyQt recipe was integrated by @jjhelmus in the [wip_qt](https://github.com/jjhelmus/berryconda/tree/wip_qt/recipes/pyqt) branch
  - I managed to conda-build this recipe and use the package, it uses the Qt system libraries
  - Couldn't get the Qt recipe to build with conda so far
  - I also could not get VisPy to work within the so created conda environment.

Anyway, we can think about using any other backend which might be more easy to build under `berryconda` than Qt. We can also use the new [conda-forge VisPy](https://github.com/conda-forge/vispy-feedstock) recipe to also adapt it to `berryconda`. 

IMHO the `berryconda` approach is the most promising way for reaching the goal. Suggestions, ideas?

**Comment by davidh-ssec** [comment]
> I also could not get VisPy to work within the so created conda environment.

In what way was it not working (I just want details)? It would be cool if we could get at least a `vispy.sys_info()`. Glfw might be a good backend to try next.

**Comment by kmuehlbauer** [comment]
@davidh-ssec I honestly do not remember 😢. Obviously my 8-GB SD-Card was too small to hold the artefacts of the Qt5 build. I then set up on a 64-GB Card but spent all the time on the Qt stuff. Didn't try VisPy again. I think I'll redo all the stuff and come up with some error message. 

For the `berryconda`-approach it would be good to create packages of all possible backends.

**Comment by andresbrocco** [comment]
> In what way was it not working (I just want details)? It would be cool if we could get at least a vispy.sys_info().

My approach was to pip3 install all the packages and backends listed on the installation page. When I run vispy.sys_info(), I get:

`StdErr: libEGL warning: DRI2: failed to authenticate
Platform: Linux-4.9.41-v7+-armv7l-with-debian-9.1
Python:   3.5.3 (default, Jan 19 2017, 14:11:04)  [GCC 6.3.0 20170124]
NumPy:    1.13.1
Backend:  PyQt4
pyqt4:    ('PyQt4', '4.11.4', '4.8.7')
pyqt5:    None
pyside:   None
pyglet:   None
glfw:     glfw (3, 2, 1)
sdl2:     None
wx:       None
egl:      EGL 1.4 (DRI2) Mesa Project: OpenGL OpenGL_ES
osmesa:   None
_test:    None

GL version:  '3.0 Mesa 13.0.6'
MAX_TEXTURE_SIZE: 8192
Extensions: '(a bunch of GL_something)'`

**Comment by kmuehlbauer** [comment]
@andresbrocco I went the berryconda way again and conda build pyopengl and pyqt. Then created a dedicated  environment and installed python3.6 with the mentioned pyopengl and pyqt. Then pip installed vispy into this conda env.

With this I got several examples running. I added 'c.measure_fps' in the gloo/rotate_cube.py. This gave me around 60fps as expected.

This makes me think, that we can utilise berryconda to help getting vispy working on the Pi.

I'll write a little how-to the next days.

**Comment by kmuehlbauer** [comment]
![20171105_212820](https://user-images.githubusercontent.com/5821660/32418836-069b710c-c271-11e7-8ad2-b1d8cb5b2b57.jpg)

**Comment by andresbrocco** [comment]
@kmuehlbauder great! I don't know what you mean by dedicated environment... I Will be greatful If you share the "How to"

**Comment by kmuehlbauer** [comment]
@andresbrocco 

With dedicated environment I mean a conda environment create like this:

```
$ conda create -n vispy python=3.6
$ source activate vispy
(vispy) $ conda install -c file://path/to/local/packages pyopengl pyqt
(vispy) $ pip install vispy
```
The problem with this is, that you need to build pyopengl and pyqt with conda. Real error proofment is only established when we can also get Qt into `berryconda` (which I'm trying to do in the next weeks).

**Comment by stuaxo** [comment]
Various GL environments, (SDL2, Pi3D), work on the Pi, without X, so further in the future it should be possible to get Vispy working without Qt (which I assume needs X).

**Comment by kmuehlbauer** [comment]
@stuaxo Point taken. Can you guide me to some resources applying SDL2? FYI I'm using raspbian.

Since the requests on the gitter channel were specifically  concerning desktop I started with that.

**Comment by kmuehlbauer** [comment]
OK, I made VisPy working on a `Raspberry Pi 3 Model B Rev 1.2`. Issue resolved I would say 👍.

What is lacking is some neat HowTo's for different backends, like PyQt4, PyQt5, SDL2 and possible others. And this doesn't have to do with VisPy in the first place. 

Should these HowTo's, if available, be included in the docs? @davidh-ssec @larsoner Suggestions?

I'm inclined to close this here and reopen an issue in https://github.com/vispy/vispy-website.

**Comment by larsoner** [comment]
> I'm inclined to close this here and reopen an issue in https://github.com/vispy/vispy-website.

Sounds good to me
