### ISSUE TITLE
SMAA is definitely not working

### ISSUE THREAD

**Issue by BonzaiThePenguin** [vispy/vispy#497]
On this page:
https://github.com/vispy/vispy/wiki/Tech.-Antialiasing

The SMAA demo is definitely not working correctly. It's only applying a single shade of gray on one side of the aliased lines.

Someone already went through the trouble of porting SMAA to OpenGL with a cross-platform windowing framework, so I'd recommend using that:
https://github.com/scrawl/smaa-opengl

**Comment by djhoese** [comment]
I'm not sure what demo is being mentioned here, but vispy has a simple agg implementation for lines now and we're looking for improvements. I'm going to close this as a duplicate of #1907 that I just made with more information on what updates could be made.
