### ISSUE TITLE
In the shader composition system, automatically handle discrepancy between vec2, vec3, and vec4

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#501]
Let's take the example of GLSL-based colormaps. We have a bunch of GLSL functions `float --> vec3`. When plugging them into `gl_FragColor = $color`, we would like that to _just work_ instead of converting everything to vec4 by hand. Idem for positions, when using `x,y` coordinates and pushing to `gl_Position`.

It may be possible to handle that automatically in the shader composition system. One possibility would be to always take the convention that the third component should be 0 by default, and the fourth one be 1 by default. This is the same convention for both position and color. So when pushing a `vec3` to a `vec4`, it would automatically add a `1` at the end of the `vec3`.

**Comment by queenish001** [comment]
@rossant

**Comment by djhoese** [comment]
This `default=` logic has existed for a while from what I can tell and I agree with the concerns that you can't assert a "global" default for all cases. I think this can be closed.
