### ISSUE TITLE
Inconsistency in use of transformation matrices (transposed)

### ISSUE THREAD

**Issue by rreilink** [vispy/vispy#507]
In vispy, transformation matrices in util/transforms.py (created by translate etc) have the form
```
( r r r 0)
( r r r 0)
( r r r 0)
( tx ty tx 1)
```
I.e. with the translation as the last row. This is the convention in DirectX if I am correct. However, in OpenGL the convention is to have the translation in the last column:
```
( r r r tx)
( r r r ty)
( r r r tz)
( 0 0 0 1)
```

These are mathematically equivalent ways to store the data, (the matrix is just transposed). In vispy, this is converted in vispy/gloo/variable.py. However, this does cause an issue: with the transposition, the order of multiplication is reversed: `A.T * B.T = (B*A).T`. Thus, lets say we have two matrices A and B, and in the shader language we have two mat4 uniforms `u_x` and `u_y` Now if in the shader we have a statement `u_x` * `u_y`, Then the following two cases have a different effect:
* `u_x = A, u_y = B`
* `u_x = eye(4), u_y = A*B` (A and B ar numpy matrices so * denotes dot product)

The first case would be equivalent to `u_x = eye(4), u_y = B*A`, which is counter-intuitive: in shader language A*B is equivalent to B*A in Python. This file demonstrates the issue: https://gist.github.com/rreilink/9e787d0fa7c939519652 . In the on_timer handler, the uniforms `u_a` and `u_b` are for each frame changed between the two cases named above. This clearly shows that the two cases, which should be equivalent, are not.

I think this is an issue, since the order of multiplication of transformation matrices/ the order of applying operations is a very easy thing to get wrong. Luckily, the solution is not very difficult. 
* Change utils/transformations.py to return matrices according to OpenGL convention
* Change vispy/gloo/variable.py to not transpose matrices when setting the uniforms
* Change scene/transforms/linear.py to use post-multiply (`self.matrix*=translate(...)`) instead of pre-multiply (`self.matrix[...] = translate(...) * self.matrix`) which is currently used in my latest pull-request.

If you agree to this I'd be happy to implement the proposed solution

**Comment by martinruenz** [comment]
This is still an issue, right?

I just ran into the situation that I had to use the following to make my code work:
```
T = np.array([[1,0,0,0],
             [0,1,0,0],
             [0,0,1,0],
             [2,0,0,1]])
my_visual.transform = MatrixTransform(T)
```
or, more generally: `my_visual.transform = MatrixTransform(original_t.transpose())`

Is there going to be a renaming of some sort, to avoid that currently correct applications start to behave falsely?

**Comment by rougier** [comment]
There is no inconsistency. From the OpenGL FAQ:

```
For programming purposes, OpenGL matrices are 16-value arrays with base vectors
laid out contiguously in memory. The translation components occupy the 13th, 14th,
and 15th elements of the 16-element matrix, where indices are numbered from 1 to 16
as described in section 2.11.2 of the OpenGL 2.1 Specification.
```
If you consider this translation numpy array, it is consistent with OpenGL:
```
T = np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0],
              [1,2,3,1]])
print(T.ravel())
array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 3, 1])
```

You can upload this matrix on the GPU and used to translate by multiplication on the left (OpenGL arbitrary convention):

```
mat4 T;
vec4 V, R;
R = T*V
```

On Python, you'll need to multiply on the right side.
```
V = [1,2,3,1]
R = np.dot(V,T)
print(R)
array([2, 4, 6, 1])
```

**Comment by martinruenz** [comment]
I am familiar with OpenGL and how matrices are stored in memory. As user, however, you should **not** be worrying about memory alignment, but rather follow conventions. After reading this discussion, I had the impression that there is change in progress and I was wondering if this might affect my code in the future.

**Comment by rreilink** [comment]
The fact that you need left-multiply in OpenGL and right-multiply in Python
is exactly the inconsistency that this issue is about.

But apparently nobody cared about it for over three years


2017-09-12 19:19 GMT+02:00 Nicolas P. Rougier <notifications@github.com>:

**Comment by rougier** [comment]
Good point. One solution would be to transpose the matrix when uploading the matrix to the GPU. For regular OpenGL there is a transpose option but it is disabled on GLES 2. This would need to be done manually.

**Comment by zhou13** [comment]
I also don't like the inconsistency but I think this won't be changed in the feature. But it might be better to say it clearly in the document.
