### ISSUE TITLE
Write a light numpy.js module

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#514]
Will be useful for some applications with the WebGL backend. This will simplify the translation of some CPU-based code from Python/NumPy to client-side JavaScript code.

This work could be useful to a much broader audience.

A good starting point could be [this module](https://github.com/mikolalysenko/ndarray). We should carefully look at this module and see if it can fit our needs, in which case we could extend it by doing a fork, or with pull requests)

Features:
- [ ] ndarray structure (using [typed arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays)?)
- [ ] matrix structure
- [ ] slicing
- [ ] common NumPy operations: reshape, concatenate, etc.
- [ ] simple and complex data types
- [ ] element-wise operations (+, -, *, /, mathematical functions like cos, exp, etc.) see [this list of modules](https://github.com/mikolalysenko/ndarray/wiki/ndarray-module-list#core-module)

**Comment by darshpandya18** [comment]
Seems good.
Additionally I have recently worked on python and numpy for 4 months which may benefit me.

**Comment by bollu** [comment]
@rossant What's the progress on this? I was hoping I could help with some of the WebGL stuff sometime :)

**Comment by djhoese** [comment]
Similar to the bokeh issue, this is not something that will be implemented in vispy and is out of scope for this project. Additionally, we'll likely be taking advantage of things like web assembly or other low-level technologies rather than writing a converter to javascript.
