### ISSUE TITLE
text aspect ratio locked on to original viewport, during window resize.

### ISSUE THREAD

**Issue by boscoh** [vispy/vispy#515]
When I define a Text visual, the aspect ratio is defined with respect to the original viewport.

During update cycles, if I resize the window, I have two choices to display the text:

1) reset the resized window to the original viewport that the Text visual was defined in, but the resultant text will have the wrong aspect ratio

2) if new window size is larger: define the viewport as a subset of the current viewport to fit the original viewport. the aspect ratio will be correct but it is difficult to access the whole window.

I can try to hack it, but I feel like a principled solution would be better, but I'd like to access the entire viewport and maintain the original aspect ratio of the text, even when I resize the window.

**Comment by Eric89GXL** [comment]
Closing since this seems to work with `scene` and appropriate use of the transform system, @boscoh feel free to reopen if you've tried setting the transform system appropriately but it doesn't work.
