### ISSUE TITLE
Write a basic Python->JavaScript translator

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#516]
We'll need that for the WebGL backend. The idea is to automatically convert to JavaScript basic Python callback functions implementing interactivity.

A [good starting point is this file](https://github.com/skariel/pythonium/blob/master/pythonium/veloce/veloce.py). We should support a minimal subset of Python: binary operators, indexing, function calls, imports, conditional branches, loops (may be completed later).

From a user point of view, it could work like this. They would write their interactivity functions in Python. For example:

``` python
def on_mouse_move(self, e):
    self.program['u_var'] = exp(e.pos[0])
```

In the WebGL backend, this would be implemented on the server by default (for example using GLIR #510). However, if users want to implement this on the client for much better performance, they would add a decorator like `@clientside`. The function would be converted to JavaScript automatically, it would be injected in the notebook, and it would have access to the gloo variables in WebGL (so we'll need a JavaScript implementation of gloo that follows the same API, so that this can be easily translated in JavaScript by the compiler).

**Comment by amirouche** [comment]
Héllo, I am the creator of Pythonium, maybe I can be of some help. If I understand correctly the objective of this ticket is to make available vispy in the browser which means:

- porting gloo to javascript (or create the gloo API on top of webgl with the help of Pythonium)
- porting numpy to javascript (or a subset it)

Is it a ipython notebook specific feature?

**Comment by rossant** [comment]
Hi @amirouche 
thanks for making Pythonium, it's an interesting piece of software. Here is the current plan:

* create an intermediate representation of OpenGL (called GLIR), that sits between OpenGL and gloo (done)
* write Python gloo on top of GLIR (done)
* write Python/desktop GL interpreter for GLIR (done)
* write JS/WebGL interpreter for GLIR (almost done), this was done by writing JS code from scratch
* create a distributed event loop between the IPython notebook and Python (done)
* create a proper WebGL backend for Vispy in the notebook (half done)
* write a light numpy.js (not started)
* write a light Python -> JS converter for simple interactivity functions (not started)

The goal of the Python -> JS converter is to simplify the task of a user who wants to go from a pure Python interactive VisPy app to a pure JS interactive app. We'll probably never achieve entirely automatic conversion, but if there's an assistant that can do much of the repetitive job automatically, it would be great.

**Comment by djhoese** [comment]
I agree with @campagnola on this. This is too much work and things have changed a lot in the last 5 to 6 years both in the web browser world, the jupyter notebook/lab world, and vispy/python world. If someone wants to take the ideas discussed here and actually work on them then comment here and we can discuss it. Until then, closing this.
