### ISSUE TITLE
ENH: Axis visual

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#549]
Should have the following features:
* Rectangular widget that can be stacked in a `Grid` next to a `ViewBox`; displays an axis line with ticks and text.
* Can also be placed inside `ViewBox`
* Responds nicely to non-linear coordinate systems, and ticks appear/disappear smoothly as the view is zoomed (similar to `GridLines`)
* Spacing / length / location of ticks can be specified manually, or automatically by 'linking' the `Axis` to another coordinate system (usually `viewbox.scene`).
* Should be designed with customization in mind, especially wrt. tick selection and text formatting.

**Comment by jvtrudel** [comment]
What is the current status of axis visualization development? Does someone works on it actually?

 I would like to contribute to that feature. Maybe I could begin by porting @rougier 's glumpy work in vispy? Un fortunately, I do not have experience with Vispy, I should I proceed? thanks.

**Comment by rossant** [comment]
I think @bollu is working on it now (correct me if I'm wrong!)

**Comment by bollu** [comment]
@rossant: First porting ```PolygonVisual``` to the new visuals system, 
@Eric89GXL got an ```AxisVisual``` up and running, but this needs to be ported to the new system as well. That will be after polygons by me :)

**Comment by Eric89GXL** [comment]
@bollu I think @campagnola already is working on that bit, see his updated description and code in #928

**Comment by Eric89GXL** [comment]
(working on AxisVisual I mean)

**Comment by PennyQ** [comment]
Hi, I am wondering if any updates or progress on expanding `AxisVisual ` to 3D? Or anyone who is already working on it? :)
