### ISSUE TITLE
ENH: Visual style / options

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#550]
The base `Visual` class should implement a system allowing specification of style options such as antialiasing, opacity, blending behavior, etc. There should be a base set of options accepted by all visuals, and each subclass may optionally define extra options. 

Long ago we also discussed the possibility of having some kind of style inheritance (possibly similar to css): https://groups.google.com/d/msg/vispy/VyUDKeGFe7g/373AGRW8A7wJ
This would allow, for example, to set default colors, line widths, fonts, etc. 

There is a small confound here--in many cases, there is no clear line between "style" and "data". For example, line width might be a natural style option, but it might also be possible to specify per-vertex line widths.

**Comment by queenish001** [comment]
@campagnola Is this issue solved?

**Comment by djhoese** [comment]
:thinking: @almarklein @rossant what do you think? This sounds similar to the gloo `set_state` stuff which as presets for the various OpenGL properties. It isn't quite the flexible idea of that Luke was originally talking about I think, but it is something. I'm also not sure this idea can be applied to all Visuals equally although it would be really really nice from a user point of view.

**Comment by almarklein** [comment]
IMO, the fact that no one has come here to express their needs for this may be seen as a hint that what we have now is enough.
