### ISSUE TITLE
Visuals should make use of document coordinate system

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#551]
Most visuals make the assumption that the document and framebuffer coordinate systems are the same. This can be seen most easily by running `examples/basics/plot/export.pt`  (requires #352) -- the exported image should look roughly the same as the original canvas, but currently the line width and marker sizes are fixed to the framebuffer pixels, rather than to document pixels. 

We can write simple unit tests for this by rendering a scene once at native resolution, and again at 2x resolution, and then checking `image1 == image2[::2, ::2]`. (this requires antialiasing to be disabled to get a good match).

**Comment by Eric89GXL** [comment]
@nippoo se also #99 and #639
