### ISSUE TITLE
SceneCanvas and/or Visuals do not embed in IPython

### ISSUE THREAD

**Issue by izaid** [vispy/vispy#554]
I don't know if this is known or not, but it seems that SceneCanvas and/or Visuals do not work embedded in IPython. Instead, it opens a separate window.

I've tried all the IPython examples, and they all embed fine in Chromium. When I try to migrate a simple Visual example, like 'image_visual.py', it doesn't work. I am currently trying to use the IPython backend via use('ipynb_vnc'), just like in the other IPython examples.

**Comment by djhoese** [comment]
This should generally be fixed, but I still consider the jupyter (yes this issue is so old it is still taking about ipython notebooks) widget/extension experimental.
