### ISSUE TITLE
Testing backends on Py 3.4 spams import warnings

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#555]
When I run `python3 make test pyside` (or any backend) I get this:

```
OK (SKIP=14)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
/usr/lib/python3.4/importlib/_bootstrap.py:2127: ImportWarning: sys.meta_path is empty
/usr/lib/python3.4/importlib/_bootstrap.py:2127: ImportWarning: sys.meta_path is empty
... and 200 or so more of those
```

If I run the full suite, I get this at the end of each backend test.

Apparently, this is a known problem in Python 3.4, see http://bugs.python.org/issue21049 and http://bugs.python.org/issue21052. It seems related to an unclosed open file or socket which is cleaned up very late because its stored at a class or is in a circular reference. The Python shutdown mechanism tries to close the resource, and this somehow invokes an import, which cannot work because `sys.meta_path` is empty.

I've tried to see if I can find the error but to no avail. Maybe @Eric89GXL has an idea? I already tried removing the `with open(os.devnull, 'w') as fid:` in test_app.py. Maybe something related to the subprocesses that we spamn during testing?

**Comment by foxx** [comment]
@Eric89GXL You just saved me hours of debugging, it was driving me insane. Thank you.

**Comment by Eric89GXL** [comment]
Heh -- we actually have the warnings again because we put the `import IPython` back in some of our tests, so I'm going to subscribe to that issue you opened.

**Comment by jakirkham** [comment]
So, I think the issue from this `ResourceWarning` caused by the unclosed `devnull` file handle will be fixed by this ( https://github.com/ipython/ipython/pull/8929 ).
