### ISSUE TITLE
`vispy.plot` interface

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#556]
Discussing about the `vispy.plot` interface.

IMO, this interface should offer a modern, user-friendly, high-level plotting interface for common 2D and 3D visualizations.

Here are a few general principles:

* Forget about `pyplot` and MATLAB plotting API. `vispy.plot` doesn't intend to implement any of this. Everything related to `pyplot` should be implemented in `vispy.mpl_plot`, which offers a backend for matplotlib (which is already largely sufficient). We might also implement a couple of highly common pyplot operations there.

* Take inspiration from `seaborn`, `bokeh`, `ggplot2`, `gadfly` for the interface. The idea is to create ready-to-use high-level functions to create common plots like scatter plots, correlation plots, etc.

* Focus on those types of plots that scale to large datasets. For examples, things like [that](https://developers.google.com/chart/interactive/docs/gallery?hl=fr) (sometimes called "charts") do not really scale to large datasets, and we shouldn't focus on them at first. Although having bar charts might be useful in some occasions, that's not what Vispy users will want.

* 2D and 3D visualizations should both be first-class citizen, and it should be easy to combine them.

* This interface should also provide user-friendly facilities for common interaction patterns like pan/zoon, linked brushing, turntable camera, arcball, etc.

* The plotting functions should focus on the *data*: what data structures will people generally have? If we can answer this, we ensure that most users won't have to transform their datasets to match whatever `vispy.plot` requires.

* `vispy.plot` should not be restricted to scientific plotting; it should allow users to display arbitrary shapes, 3D models, and most visuals we'll implement.

### Questions

* Maps could be accessible here, or in another package `vispy.maps` or something.

* How customizable should this interface be? (CSS-like styling, per-vertex values for most parameters, possibility to write custom shaders using predefined hooks in the visuals?)

**Comment by rossant** [comment]
```
class Plot(scene.widgets.Grid):
    """Grid widget that includes a ViewBox, Axes, and labels."""
    def lines(self, ...):
        """Add plot lines to this Plot, and return the created visual"""
    def image(self, ...):
        """Add image to this Plot, and return the created visual"""
    # many more functions: histogram, volume, bar, scatter, violin, etc.
```

That looks good.

```
def lines(...):  
   canvas = SceneCanvas()
   canvas.plot = Plot(parent=canvas.central_widget)
   canvas.lines = plot.lines(...)
   return canvas
# many other functions corresponding to the Plot methods
```

I find this confusing. Why would `lines` return a canvas? If you want a canvas object, just create it. Or we can have a singleton `singleton_canvas` (or another name) that represents a global SceneCanvas, useful in an interactive session. Then you'd have instead:

```
def lines(...):  
   canvas = singleton_canvas()
   canvas.plot = Plot(parent=canvas.central_widget)
   return plot.lines(...)
```

**Comment by Eric89GXL** [comment]
Closing as a dup of #749 and #742 where we went into more depth on these issues
