### ISSUE TITLE
Improve the design of the website

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#557]
Following @rougier's work on [glumpy](http://glumpy.github.io)

- [x] https://groups.google.com/forum/#!msg/vispy-dev/YiCCPie7MEs/CkpaluAFfn4J
- [ ] https://groups.google.com/forum/#!msg/vispy-dev/TF_OkGS_JD8/BjU_txDetzYJ

**Comment by kmuehlbauer** [comment]
The vispy-website is now using boostrap3 theme as glumpy does. So the first thing is solved.

The second thing, is the proposed README.rst in the examples-folder. This will surely introduce a bit of a maintenance burden, but for repo-visitors this can be quite a useful resource. Suggestions?

**Comment by larsoner** [comment]
`sphinx-gallery` automates this stuff. We should find a way to use it. They currently only support `matplotlib` and `mayavi` screenshot generation, but it's possible we could extend the API to handle it.

**Comment by kmuehlbauer** [comment]
As this is website related, does it need only work at vispy-website or also here in the codebase?

**Comment by davidh-ssec** [comment]
@kmuehlbauer All of the gallery images are generated by the make scripts in this codebase.

**Comment by kmuehlbauer** [comment]
OK, this is good then. This resolves the first part of the issue, but what about the second part with the proposed `README.rst` in the examples-folder? Do we need it?

**Comment by kmuehlbauer** [comment]
Can this be closed? At least it could be marked for the upcoming sprint, @djhoese.

**Comment by djhoese** [comment]
Yeah, I think so. I think the website being rewritten/re-themed was an improvement so at a basic level this is closed. I would like to look into organizing it more based on this presentation: https://www.youtube.com/watch?v=t4vKPhjcMZg
But for now, it is good enough.
