### ISSUE TITLE
Agreement on the target users and the APIs scope

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#568]
We have to agree about the scope of the APIs and the target users before taking any decision. Here are some propositions, please indicate if you disagree with them.

* Most of Vispy's functionality must be easily accessible from its main high-level interface, `vispy.plot`. This is the interface used by 90% of our users. The typical user here is a scientist used to matplotlib who wants a cleaner API and much better performance. We want the API that feels most natural to the average scientist with no specific data visualization knowledge.

* The "scene" API (visuals, scene graph, transforms, shaders, cameras, etc.) is only for **advanced users/developers** who need specific functionality not (yet) implemented in `vispy.plot`. This API will naturally be more complicated than the `plot` API, but that's okay, because advanced users will agree to spend more time understanding Vispy's internals. This interface will not copy any `matplotlib.pyplot` function, nor will it try to be compatible with it. Compatibility with `pyplot` will only be provided in `vispy.mpl_plot`, a Vispy backend for matplotlib (requires the matplotlib package as a dependency). (see #556)

* The most advanced users are those who are comfortable with OpenGL: those will use gloo directly. They can create new visuals. They are free to use the scene API or not. If they do, they can benefit from the component system.

**Comment by Eric89GXL** [comment]
@rossant I think we have converged on these issues... should we put it in the docs or wiki somewhere?

**Comment by rossant** [comment]
Yes we can... but that's not high priority I think.

**Comment by rossant** [comment]
In the meantime we can probably close this!
