### ISSUE TITLE
Agreement on the definitions in the scene API

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#569]
This issue precises the definitions of all terms, abstractions, definitions used in the **scene API**. This API is considered as the "main" internal API of Vispy, only used by us and by the 10% most advanced of our users. (see #568)

There is _no_ discussion about the implementations or the APIs here: just the concepts and abstractions. We can open another issue about the implementation and APIs.

This is only a start: please edit and complete this text.
### Scenegraph

A **scenegraph** is a graph, where nodes represent an object in a scene, and edges represent parent-child relationships between nodes. 

Each node implicitly defines a local coordinate frame through its **transform**, which describes the mathematical transformation from the local coordinate frame to its parent's frame. In this sense, an edge in the scenegraph represents a transformation between two coordinate frames.

The scene graph can compute the transformation from any node A to any other node B by determining a common parent C, and composing the individual transforms along the path A -> C, followed by the inverse transforms along the path C -> B. 

Nodes usually have one parent, although multiple parenting is allowed in some circumstances. This can create ambiguity in computing the transformations, because there may not be a single unique path connecting two nodes. In all practical cases, however, this ambiguity can be easily resolved during drawing and input event handling. A consequence is that nodes should generally _not_ attempt to make transformations to other nodes except during drawing or input events (although exceptions can be made for node subclasses that do not support multiple parenting).

Scenegraphs are rendered using a `SceneCanvas`, which defines a root node `canvas.scene`. Any nodes attached to `canvas.scene` will be drawn when the canvas updates, and any changes to nodes in the scenegraph can trigger a canvas update.
### Visuals

A **visual** is a graphical representation of an object.

A visual can be attached to a node in the scene graph and drawn automatically, or it can be drawn manually in the absence of a scenegraph. Accordingly, most visuals have no explicit dependency on parent/child relationships in the scenegraph. It is allowable, however, to have visual subclasses that only support drawing either with or without a scenegraph.

A visual implements the GLSL code it needs to be rendered with gloo. This code needs to implement shader hooks that other components can attach to.

A visual implements a `draw(transform_system)` function that draws the visual given a certain transform system. A **transform system** details at least three coordinate systems: 
1. `document_cs`, in which a length of 1 represents 1 logical pixel. The transform_system also tracks a `dpi` parameter that allows other physical units to be scaled to this coordinate system. This is necessary for properly drawing line widths, font sizes, etc.
2. `framebuffer_cs`, defined as having the origin at the bottom-left corner of the canvas, and a length of 1 equivalent to 1 physical pixel. This coordinate system is used primarily for antialiasing measurements.
3. `render_cs`, defined as (-1, -1) to (1, 1) on the current glViewport. This is equivalent to normalized device coordinates in GL terminology.

When a visual entity is drawn via a scenegraph, the transform system is automatically provided.

It is the responsibility of the visual to ensure that the transforms defined in the transform system are correctly applied to the rendered output of the visual. 
## Entities

An **entity**, as used in an entity-component-system architecture, is a container for **components**, such that each component modifies the behavior or representation of the entity. The entity-component relationship is under consideration for use in defining the relationships between visuals, nodes, and other components described below.
## Components

A **component** provides functionality that extends the behavior of a visual. Components are used to implement general features that can be applied to any visual, or to a subset of visual subclasses. Examples include:
- clipping to rectangular or arbitrary shapes
- graphical filtering such as opacity adjustment, color adjustment (eg for red/blue anaglyph rendering), and blurring
- picking, in which the component causes the visual to be rendered with a specific ID color
- collision detection

The components described above will require the ability to inject code into the visual's shader program, or to access the underlying geometry and other properties of the visual. Visuals that support the attachment of components must therefore provide methods and GLSL hooks to facilitate this access.

(TODO: camera, viewbox, subscene...)

**Comment by kmuehlbauer** [comment]
This is obviously the discussion which followed after this was partially raised in #398. As the `scene` code is already implemented, this can be closed.
