### ISSUE TITLE
memory continues increasing with mpl_plot?

### ISSUE THREAD

**Issue by barpaum** [vispy/vispy#575]
When I was playing with the example file "/examples/basics/plotting/mpl_plot.py", I moved the plotting inside subplot with mouse, the memory occupation increased dramatically, is it a memory leak or just the mpl_plot functions not mature enough?

**Comment by almarklein** [comment]
I tested and it's fixed now. Pushing a PR in a minute to fix the mpl_plot example (since its broken right now).
