### ISSUE TITLE
properties are unpythonic

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#577]
I have run into this issue several times while working with vispy:  if I misspell a property name when doing an assignment, the error is silently ignored. This makes a situation where bugs are easy to write and difficult to find; quite unpythonic. A less important issue is that we can hide a lot of machinery in property setters, so whereas `visual.size = 10` makes me think of simple attribute assignment, this simple line could be invoking much more complex actions behind the scenes. Using `visual.set_size(10)` is somewhat less misleading in that sense.

I realize these are general python issues, but we might have some options to deal with them in vispy: 

* Add `__setattr__` methods to many classes to catch misspellings. The downside to this is that it is often very convenient to be able to dynamically add new attributes. However a helpful error message could make this work: `"object has no attribute %s; add with object.__dict__[%s] = None"`
* Restrict use of properties to situations where we just want to document a public attribute; anything with more complex behavior uses get/set methods. (but this is ugly)

**Comment by Eric89GXL** [comment]
closing this, feel free to reopen if you come up with another idea @campagnola
