### ISSUE TITLE
assigning to TurntableCamera.center has no effect

### ISSUE THREAD

**Issue by alexflint** [vispy/vispy#579]
If I create a scene and add a camera using `view.set_camera('turntable'...)`, and then some time later, after the scene is visible, I do `view.camera.position = (x,y,z)`, then the camera's position is not updated. However, if I do `view.set_camera('turntable', position=(x,y,z))` then everything works as expected.

**Comment by Eric89GXL** [comment]
Closing this since it should be fixed by a recent camera PR, feel free to reopen if it still doesn't work.
