### ISSUE TITLE
Could not import any of the backends

### ISSUE THREAD

**Issue by tartavull** [vispy/vispy#582]
When running this code from the [cookbook](http://ipython-books.github.io/featured-06/)
```python
import numpy as np
from vispy import app
from vispy import gloo
c = app.Canvas(keys='interactive')
```
I'm getting this error:

```
INFO: Could not import backend "PyQt4":
cannot import name QtOpenGL
INFO:vispy:Could not import backend "PyQt4":
cannot import name QtOpenGL
INFO: Could not import backend "PySide":
Refusing to import PySide because PyQt4 is already imported.
INFO:vispy:Could not import backend "PySide":
Refusing to import PySide because PyQt4 is already imported.
INFO: Could not import backend "Pyglet":
Pyglet version too old (1.1.4), need >= 1.2
You can install the latest pyglet using:
    pip install http://pyglet.googlecode.com/archive/tip.zip
INFO:vispy:Could not import backend "Pyglet":
Pyglet version too old (1.1.4), need >= 1.2
You can install the latest pyglet using:
    pip install http://pyglet.googlecode.com/archive/tip.zip
INFO: Could not import backend "Glfw":
GLFW library not found
INFO:vispy:Could not import backend "Glfw":
GLFW library not found
INFO: Could not import backend "SDL2":
No module named sdl2
INFO:vispy:Could not import backend "SDL2":
No module named sdl2
INFO: Could not import backend "wx":
No module named wx
INFO:vispy:Could not import backend "wx":
No module named wx
INFO: Could not import backend "EGL":
Not ready for testing
INFO:vispy:Could not import backend "EGL":
Not ready for testing
INFO: Could not import backend "Glut":
No module named OpenGL.error
INFO:vispy:Could not import backend "Glut":
No module named OpenGL.error
```
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-b622cb67980d> in <module>()
----> 1 c = app.Canvas(keys='interactive')

/usr/local/lib/python2.7/dist-packages/vispy-0.3.0-py2.7.egg/vispy/app/canvas.pyc in __init__(self, title, size, position, show, autoswap, app, create_native, init_gloo, vsync, resizable, decorate, fullscreen, context, keys, parent)
    134         # Get app instance
    135         if app is None:
--> 136             self._app = use_app()
    137         elif isinstance(app, Application):
    138             self._app = app

/usr/local/lib/python2.7/dist-packages/vispy-0.3.0-py2.7.egg/vispy/app/_default_app.pyc in use_app(backend_name)
     37 
     38     # Create default app
---> 39     default_app = Application(backend_name)
     40     return default_app
     41 

/usr/local/lib/python2.7/dist-packages/vispy-0.3.0-py2.7.egg/vispy/app/application.pyc in __init__(self, backend_name)
     46         self._backend_module = None
     47         self._backend = None
---> 48         self._use(backend_name)
     49 
     50     def __repr__(self):

/usr/local/lib/python2.7/dist-packages/vispy-0.3.0-py2.7.egg/vispy/app/application.pyc in _use(self, backend_name)
    177                 break
    178         else:
--> 179             raise RuntimeError('Could not import any of the backends.')
    180 
    181         # Store classes for app backend and canvas backend

RuntimeError: Could not import any of the backends.
```

**Comment by Eric89GXL** [comment]
A clearer error message is now in `master` to help users with this problem.

**Comment by edisonchensy** [comment]
Traceback (most recent call last):
File "/home/Edison/SSD-6D/ssd-6d-master/rendering/utils.py", line 18, in 
from rendering.renderer import Renderer
File "/home/Edison/SSD-6D/ssd-6d-master/rendering/renderer.py", line 8, in 
app.use_app('pyglet') # Set backend
File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/_default_app.py", line 47, in use_app
default_app = Application(backend_name)
File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/application.py", line 49, in init
self._use(backend_name)
File "/home/Edison/anaconda3/lib/python3.6/site-packages/vispy/app/application.py", line 223, in _use
raise RuntimeError(msg)
RuntimeError: Could not import backend "Pyglet":
Cannot connect to "None"

I have the similar problem on Pyglet, I have no idea what's going on, can you plz take a look?

**Comment by iris0329** [comment]
same problem,  anyone have solved?

**Comment by djhoese** [comment]
@iris0329 Could you please create a new issue with details on your situation (what OS, what backend are you trying to use, are you running in a notebook, what version of vispy are you using, etc)?

**Comment by misterjoa** [comment]
Hello everyone, I had lots of trouble understanding basic requirements to install vispy package. For anyone having troubles regarding weird rendering problems (method calls) or backends, first install a backend such as `pip install pyqt5` and be sure to also install `pip install pyopengl` which is not installed automatically when using `pipenv` !

**Comment by djhoese** [comment]
@misterjoa Do you have a suggestion of a better way to document this requirement? There is a section in the installation instructions for vispy that specifically talk about installing a backend: http://vispy.org/installation.html#backend-requirements.  Additionally I don't think pyopengl is needed, at least not in all situations and for all backends, but having OpenGL drivers installed on your system is a must. If you have suggestions to update the documentation then please make a new issue or submit the contribution as a pull request. Thanks.

I'm locking this issue. This is from 2014. Things have changed and I've already suggested users start a new issue if they have anything resembling these error messages. If you are having issues with importing backends in vispy then please start a **new** issue.
