### ISSUE TITLE
Native, cross-platform, pure Python backend

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#586]
Would it be possible to implement our very own pure Python, cross-platform backend, instead of relying on external dependencies? The major advantage is that Vispy would really be a pure Python project depending solely on NumPy. It would provide its own OpenGL bindings *and* native backend working on all platforms.

I think that's exactly what pyglet does. Could we take out their code and include it in Vispy under the form of a native self-contained backend?

**Comment by Eric89GXL** [comment]
I took a look at the Pyglet code a while back, and it seems like it would be a real pain to make our code work on OSX/Windows/Linux reliably. @rossant okay with you to close this?

**Comment by rossant** [comment]
Yes
