### ISSUE TITLE
Add more info about the backends in the doc

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#589]
We should precise the strengths and shortcomings of every backend in the documentation. Notably, a beginner should understand which backends are more capable (I think PyQt4 and GLFW are the two best backends for now?).

**Comment by queenish001** [comment]
@rossant Is this issue resolved?

**Comment by djhoese** [comment]
I think once #2246 is merged we can close this. I wouldn't say any one backend is necessary more feature filled than another, but some are definitely more heavily used or tested.
