### ISSUE TITLE
Tests should automatically determine location of vispy

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#591]
If I run `make test` from the vispy root, it fails with `ImportError: No module named vispy`. I can correct this with `export PYTHONPATH=...`, but then the example tests will still fail (this seems to be a new bug?). Worse, if I already have vispy installed elsewhere in the system, then that package will be tested instead of the source tree I am running the tests from.

Suggested behavior: tests try to detect whether they are being run from a source tree and insert an entry to the beginning of `sys.path`. If the tests are no run from a source tree, then no entry is added and it is assumed that a system-wide installation is available. 

It would be nice to have the same for examples, but this would necessitate adding an extra import to the top of every example (and objections have already been expressed to this).

**Comment by Eric89GXL** [comment]
@campagnola do you think this is still necessary? I think most folks will use `python setup.py develop` on their development rigs, I think it's fairly standard.

**Comment by campagnola** [comment]
Nah, it seems I'm the only one with this complaint  :)
