### ISSUE TITLE
vispy.config could play a more central role

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#595]
We now have a dict-like object in `vispy.config` which plays a not so pronounced role in configuring vispy. We also have the `vispy.use` functions (and `app.use_app` and `gloo.gl.use_gl`). I think we should:
- Make `vispy.config` _the_ way to communicate config settings, such as the app and backends.
- So `vispy.use`should modify `vispy.config`, and then call `app.use_app()` (which should probably not have any args).
- For every element in `vispy.config` there should be a corresponding command line arg (this is already the case, I think) as well as an environment variable.
- (Better) documentation of the config settings (in the API docs).

In #593 I already implemented the first point a bit: The app backend needs to know what gl backend is selected.

One point I am a bit unsure about is how to deal with the many combinations of app backends and gl backends ... for instance:
- The qt backend can now deal with any gl backend (but needs to know which one is selected to provide either a desktop or EGL context)
- All other app backends cannot be combined with the 'es2' gl backend. 
- Cyrille's 'ipynb_webgl' backend will want to set/force the gl backend to 'dummy', because there should not be any local execution of gl commands ...

How can we deal with this? I see two options: 1) the `use` function is aware of all potential combinations and conflicts;  2) the app backends check/set the gl backend (which may lead to repetitive code). Any ideas?

**Comment by queenish001** [comment]
Is this issue solved @almarklein ?

**Comment by almarklein** [comment]
Meh, there never was a need, so let's indeed close.
