### ISSUE TITLE
Improve the WebGL backend

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#607]
This is a list of things to do to improve the WebGL backend once PR #592 is merged.
### JavaScript loading
- [x] Refactor vispy.js to use browserify instead of requireJS.
- [x] Do not install nbextension if not necessary. The required JS files (notably `vispy.min.js`) are copied into the IPython profile everytime the `ipynb_webgl` backend is used. We could do a simple check to only copy if necessary (unless IPython's `install_nbextension` already does that).
- [ ] Fail gracefully if WebGL is not available (and suggest the user to use the VNC backend)
### vispy.js
- [ ] Improve the GLIR implementation, notably:
  - in SHADERS, after attaching shaders, we should detach and destroy them
  - in TEXTURE, we should use the texture_number from the existing stored texture
  - try more complicated examples, notably with multiple textures
- [ ] Implement framebuffers in vispy.js (they are not supported currently).
### Misc
- [x] ~~Solve issue #606 so that all examples work in the notebook~~ tackle issue #615.
- [x] Use binary WebSockets (implemented in IPython master and upcoming IPython 3.0) to transfer NumPy arrays from Python to JavaScript.
- [ ] Refactor `ipynb_webgl` so that other notebook backends can reuse most of the code (and bring back static and vnc).
- [ ] Rename paint into draw
- [ ] Implement `VispyWidget(DOMWidget)` (see comment below)

**Comment by rossant** [comment]
Note to self:

I would like to make the following possible. I create a VisPy SceneCanvas as usual (e.g. a line plot). Next, I want to easily create an IPython DOMWidget that:

* exposes several trait attributes, for example `line_color`
* displays the SceneCanvas using WebGL in a cell's widget area

Here is how it could work:

```python
# create the SceneCanvas
canvas = ...

class MyWidget(VispyWidget):
    """This class makes the bridge between the VisPy canvas and the WebGL widget.
    It exposes several trait attributes which notification callbacks can be customized.
    A VispyWidget is instanciated with a Canvas instance. Displaying the widget shows the
    WebGL version of the canvas.
    """

    # This trait attribute represent the line's color.
    line_color = 'blue'

    def on_trait_change(self, name, old, new):
        if name == 'line_color':
            self.canvas.myvisual.color = new
            
display(MyWidget(canvas))
```

**Comment by lcampagn** [comment]
Isn't this already possible just by implementing properties on the subclass, like
```
@line_color.setter
def line_color(self, color):
    self.myvisual.color = color
```
?

**Comment by rossant** [comment]
Not exactly it really needs to be a trait attribute so that it works with IPython's MVC system.

**Comment by dragoljub** [comment]
This looks very exciting. Just curious about why the WebGL Backend is only supported on python 3? Will Python 2.7 be supported? Thanks and keep up the great work. :smile:

**Comment by Eric89GXL** [comment]
@dragoljub I think it's only supported on IPython version 3+, but that can be running Python 2.7 or 3.4 under the hood.

**Comment by dragoljub** [comment]
Yup I got it working after I updated to 4.0. 

Thanks.

**Comment by djhoese** [comment]
I think besides possibly the "fail gracefully" task, I think I finished all of these tasks in the 0.6 release. I still consider the jupyter widget experimental (performance is not great), but it "works".
