### ISSUE TITLE
ipython display_points cannot import name use

### ISSUE THREAD

**Issue by stuaxo** [vispy/vispy#608]
Tried using display_points ipython notebook but it gets stuck fairly early:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-49573d03a56f> in <module>()
      1 from vispy import gloo
----> 2 from vispy import app, use
      3 import numpy as np

ImportError: cannot import name use
```

**Comment by djhoese** [comment]
I'm not sure the display_points notebook exists any more and it sounds like most of this stuff should be fixed now. I've done some major updates on the notebook widget so hopefully most import related issues have been resolved but I still consider it experimental.

**Comment by stuaxo** [comment]
Cheers :)
