### ISSUE TITLE
Display problems when activating/deactivating fullscreen

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#619]
Run this script:

``` python
import numpy as np
from vispy import app
from vispy import gloo

VS = '''
attribute vec2 a_position;
void main() {
    gl_Position = vec4(a_position, 0., 1.);
    gl_PointSize = 3.;
}
'''

FS = '''
void main() {
    gl_FragColor = vec4(1., 0., 0., 1.);
}
'''

class MyCanvas(app.Canvas):
    def __init__(self):
        super(MyCanvas, self).__init__(keys='interactive')
        self.program = gloo.Program(VS, FS)
        self.program['a_position'] = np.random.rand(10000000, 2).astype(np.float32)

    def on_resize(self, event):
        gloo.set_viewport((0, 0,) + self.size)
        self.update()

    def on_draw(self, event):
        gloo.clear('black')
        self.program.draw('points')

def _show():
    c = MyCanvas()
    c.show()

if __name__ == '__main__':
    _show()
    app.run()
```

and press F11 to put in fullscreen. Press F11 again to deactivate fullscreen. Notice the weird display bugs that occur. It looks as if the draw events were incorrectly emitted, or at the wrong times, and with the wrong window sizes. The effect disappears if there are less points.

**Comment by Eric89GXL** [comment]
@rossant I don't have this on my OSX machine. Can you check to see if the bug still exists, and let me know what OS and backend you're on?

**Comment by queenish001** [comment]
@rossant

**Comment by djhoese** [comment]
I'm not sure I'm seeing the same thing Cyrille was seeing, but when run on my PopOS system I see two draw events when I go to fullscreen: one when the window position is moved to the top left corner then another one when it is resized to fit the whole screen. It is only seen for a single frame/draw and I'm not sure there is much we can do about that. I'm going to close this as no longer an issue and difficult to reproduce.
