### ISSUE TITLE
Performance of the scene graph

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#628]
The performance and memory consumption of the `SceneCanvas` is currently the main issue that prevents me from using it. Since I'm rather in a hurry, I've implemented a simple `PanZoomCanvas` where I can easily add custom visuals. The visuals implement `$transform()` in the vertex shader. At every draw, I loop through all visuals and I update the `pan` and `zoom` uniform values of the `PanZoomTransform`. This is enough for me because I have scenes with basically a single big custom visual, and maybe a few tiny visuals (text for example).

At least this gives me some way to write custom and highly efficient visuals and to ensure that these visuals will be reusable in the future (since they use the existing visual/shader/transform system). I can more or less go on with my work and somehow replace Galry.

However, this is a rather temporary and precarious solution. For example, displaying text correctly is difficult because I haven't implemented appropriate support for `TransformSystem`. For that, it looks like I would need the `SceneCanvas` (?). Or maybe there's a simple way to implement the necessary machinery to support text in `PanZoomCanvas` (but I don't want to reimplement the whole `SceneCanvas` again for sure!)

I currently have to use a private fork of Vispy, whereas the whole point of the project was to provide a single code base for all use cases! 

So I would like to know what exactly would need to be done in order to have optimal performance with the scene canvas?

Let's consider a concrete example, similar to what I've done with `PanZoomCanvas`. I have one custom visual that implements `$transform()`. The transform I want to use is `PanZoomTransform`. When I pan and zoom, the _only_ steps that should happen in OpenGL in order to achieve optimal performance are:
1. The `u_pan` uniform is updated.
2. The `u_zoom` uniform is updated.
3. The custom visual is redrawn.

No `draw` event should be raised if there's no pan and zoom (even if the mouse moves within the canvas).

When the scene is redrawn, the `u_pan`  and `u_zoom` uniforms should not be updated (they wouldn't change).

Overall, we should ensure that no unnecessary OpenGL commands are emitted. I haven't done extensive profiling of the current SceneCanvas system, but it seems to me that many more OpenGL commands are done in an example like this (notably shader recompilation, constant settings of uniforms, etc.).

So my questions are:
1. Is it possible to improve the current scene system to achieve optimal performance in an example like the one I described?
2. Am I the only one who really needs performance, or do you also have incentive to improve the performance of the current system?
3. Do you know exactly what are the bottlenecks, and how to fix them?
4. How much work is required to achieve optimal performance? Is it just a matter of fixing a few things here and there, or would we need to rework the entire implementation significantly?

A few tentative answers for 3:
- [This?](https://github.com/vispy/vispy/blob/master/vispy/scene/canvas.py#L217)
- [This?](https://github.com/vispy/vispy/blob/master/vispy/visuals/transforms/linear.py#L113) If I have uniform values for `translate` and `scale`, does calling this `_set_st` function results in a simple updates of these uniforms or not?

**Comment by Eric89GXL** [comment]
I have an idea for how we might be able to optionally get performance metrics from our library with an easy API (more or less just adding function decorators) and little to no overhead (at least when debugging is off, which it would be by default). @campagnola Almar mentioned you had some utilities for profiling our code -- does it already work in a similar manner? I wouldn't want to re-invent the wheel...

**Comment by campagnola** [comment]
I just adapted the Profiler class from pyqtgraph. It's pretty nice:
https://github.com/campagnola/vispy/blob/scenegraph-performance/vispy/util/profiler.py

I haven't tested it, but the overhead should be very small except when profiling is enabled.

**Comment by queenish001** [comment]
@rossant Please review this issue once again, if it can be closed now.

**Comment by djhoese** [comment]
As mentioned in #1991, there has been a lot of work on SceneCanvas performance. I'm not sure how many of the concerns described here still exist and future work based on the cycle 4 CZI grant and the roadmap in the documentation discuss other types of improvements that could be made. I'm going to close this mostly due to its age and that it isn't necessarily specific enough to help future discussion.
