### ISSUE TITLE
Alignment wrong computation when aligned on 8 bytes

### ISSUE THREAD

**Issue by nekopep** [vispy/vispy#641]
Hello,

While reviewing code in vispy/glir.py I found this comment that looks erroneous:

```
# we know the alignment is appropriate
# if we can divide the width by the
# alignment cleanly
# valid alignments are 1,2,4 and 8
# put 4 first, since it's the default
alignments = [4, 8, 2, 1]
for alignment in alignments:
    if width % alignment == 0:
        return alignment
```

the issue is that if width is multiple of 8 then the alignment returned will always be 4... since it is always multiple of 4 too.

So either either remove the "8" case for speed or define alignment to [8,4,2,1].

Laurent

**Comment by kmuehlbauer** [comment]
> Using 4 rather than 8 is not a problem, only potentially, using 8 when possible could be faster. So should we ditch the 8 or put 8 first?

Can't we just have `alignments = [8, 4, 2, 1]`? The performance impact is in the 1 percent range, seemingly insignificant. Anyway `alignments = [4, 8, 2, 1]` doesn't make sense at all.

**Comment by larsoner** [comment]
Yes let's do 8/4/2/1 and see if anything breaks
