### ISSUE TITLE
Implement more colormaps

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#648]
- [ ] [seaborn](https://github.com/mwaskom/seaborn/blob/master/seaborn/palettes.py)
- [ ] [colorbrewer][(http://colorbrewer2.org/)
- [x] [cubehelix](https://github.com/jradavenport/cubehelix)
- [x] implement routines to generate special colormaps (diverging, husl, hls...)
- [x] viridis, set as default
- [ ] inferno

**Comment by sh4wn** [comment]
Do we want our own implementation for cubehelix our should we depend on the package? Or just copy the module with proper attribution?

**Comment by almarklein** [comment]
No dependencies please :)  I think we should port the colormap to vispy's system, copying as much code as we can (and attributing it, of course).

**Comment by sh4wn** [comment]
Ok, so I'm currently busy implementing this, but another question: What's the relation between the glsl_map defined in the class of a colormap and the GLSL programs in vispy/glsl/colormaps/[name].glsl? Are they both used?

**Comment by rossant** [comment]
They are redundant, we'll have to merge them at some point. For now I think you can just use those in vispy.colors.

**Comment by Eric89GXL** [comment]
BTW I have the `cubehelix` colormap in my open `vispy.plot` PR, so don't bother with that one...

**Comment by almarklein** [comment]
cc @izaid because he did most of the works on colormaps.

**Comment by ericdill** [comment]
Is this issue complete? There is a referenced PR that has been merged

**Comment by Eric89GXL** [comment]
I think we have some but not all of those colormaps at this point

**Comment by Eric89GXL** [comment]
We should probably switch to the same new default `viridis` as matplotlib:

https://www.youtube.com/watch?v=xAoljeRJ3lU

**Comment by almarklein** [comment]
+1 for viridis

**Comment by rougier** [comment]
Yes, veridis would be a great addition (and the default one maybe)

**Comment by larsoner** [comment]
Closing for more recent discussion in #1397
