### ISSUE TITLE
gloo.gl.tests.test_functionality._draw1 fails

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#649]
Tested on Ubuntu 14.04 and Intel GPU (the test passes on the NVIDIA GPU).

```
======================================================================
FAIL: Test pyopengl GL backend for full functionality.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/data/git/vispy/vispy/testing/_testing.py", line 180, in skipper
    return f(*args, **kwargs)
  File "/home/cyrille/anaconda/envs/py27/lib/python2.7/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 59, in test_functionality_pyopengl
    _test_functonality('pyopengl')
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 96, in _test_functonality
    _draw1()
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 507, in _draw1
    _check_result()
  File "/data/git/vispy/vispy/gloo/gl/tests/test_functionality.py", line 547, in _check_result
    assert_equal(pix1, (0, 0, 0))
AssertionError: Tuples differ: (32, 32, 32) != (0, 0, 0)

First differing element 0:
32
0

- (32, 32, 32)
+ (0, 0, 0)
```

**Comment by Eric89GXL** [comment]
@rossant can you see if this works for you now? this test passes on my intel hardware

**Comment by QuLogic** [comment]
Following up from #949, the failure occurs on all backends that I was able to test. It is the only failure on pyqt4 and pyglet, with a couple other failures occurring on pyqt5.

**Comment by Eric89GXL** [comment]
Do you have pyqt5 working on anaconda? Maybe we should add it to Travis. I
can also try to get it going locally to debug that aspect. Maybe for now we
should add a known fail for Intel. Not satisfactory, but of everything else
works it might be acceptable for now.

**Comment by QuLogic** [comment]
No, I'm running pyqt5 via system packages. But it has to be run by itself, because multiple Qt runtimes cannot be loaded at the same time.

**Comment by QuLogic** [comment]
OK, I'm not really sure why this works, but it seems that removing `a_1` fixes it:
```diff
diff --git a/vispy/gloo/gl/tests/test_functionality.py b/vispy/gloo/gl/tests/test_functionality.py
index 4b64f3e..adf64dd 100644
--- a/vispy/gloo/gl/tests/test_functionality.py
+++ b/vispy/gloo/gl/tests/test_functionality.py
@@ -105,7 +105,6 @@ def _test_functonality(backend):
 # Most variables are nullified however, but we must make sure we do this
 # in a way that the compiler won't optimize out :)
 VERT = """
-attribute float a_1;
 attribute vec2 a_2;
 attribute vec3 a_3;
 attribute vec4 a_4;
@@ -138,7 +137,7 @@ void main()
     vec4 u4 = u_f4 + vec4(u_i4);
     
     // Set varyings (use every 2D and 4D variable, and u1)
-    v_2 = a_1 * a_2 + zero*u_m2 * a_2 * u2 * u1;
+    v_2 = 1.0f * a_2 + zero*u_m2 * a_2 * u2 * u1;
     v_4 = u_m4 * a_4 * u4;
     
     // Set position (use 3D variables)
@@ -264,7 +263,7 @@ def _prepare_vis():
     # Count attribbutes and uniforms
     natt = gl.glGetProgramParameter(hprog, gl.GL_ACTIVE_ATTRIBUTES)
     nuni = gl.glGetProgramParameter(hprog, gl.GL_ACTIVE_UNIFORMS)
-    assert_equal(natt, 4)
+    assert_equal(natt, 3)
     assert_equal(nuni, 4+4+3+1)
     
     # Get names
@@ -279,7 +278,6 @@ def _prepare_vis():
         assert_equal(count, 1)
     
     # Check
-    assert_equal(names['a_1'], gl.GL_FLOAT)
     assert_equal(names['a_2'], gl.GL_FLOAT_VEC2)
     assert_equal(names['a_3'], gl.GL_FLOAT_VEC3)
     assert_equal(names['a_4'], gl.GL_FLOAT_VEC4)
@@ -474,8 +472,6 @@ def _prepare_vis():
     # --- attributes 
     
     # Constant values for attributes. We do not even use this ...
-    loc = gl.glGetAttribLocation(hprog, 'a_1')
-    gl.glVertexAttrib1f(loc, 1.0)
     loc = gl.glGetAttribLocation(hprog, 'a_2')
     gl.glVertexAttrib2f(loc, 1.0, 1.0)
     loc = gl.glGetAttribLocation(hprog, 'a_3')
```

**Comment by Eric89GXL** [comment]
FYI you should be able to do `python make test pyqt5` from the `git` root directory to run tests (that require a backend) using PyQt5.

Re: the fix -- that is really strange, those bits of code sure seem like they should evaluate in identical ways. Have you tried leaving the code in, but moving the `loc ... \ gl.glVertexAtrib1f` lines until after the `a2` and `a3` are set? I'm wondering if there is something weird about the order is happening.

In any case, I guess for now you can comment out the offending lines in GLSL and Python, and then add a comment like `# XXX Uncommenting these lines fails on Intel hardware on Linux (e.g. 4600 HD) for some unknown reason` so we know to have it in the back of our minds.

**Comment by QuLogic** [comment]
> but moving the `loc ... \ gl.glVertexAttrib1f` lines until after the `a2` and `a3` are set?

No luck there. I even tried moving it way up to just after `glUseProgram`, but that didn't help.

**Comment by QuLogic** [comment]
Hmm, even simpler:
```
diff --git a/vispy/gloo/gl/tests/test_functionality.py b/vispy/gloo/gl/tests/test_functionality.py
index 4b64f3e..7bd6b69 100644
--- a/vispy/gloo/gl/tests/test_functionality.py
+++ b/vispy/gloo/gl/tests/test_functionality.py
@@ -138,7 +138,7 @@ void main()
     vec4 u4 = u_f4 + vec4(u_i4);
     
     // Set varyings (use every 2D and 4D variable, and u1)
-    v_2 = a_1 * a_2 + zero*u_m2 * a_2 * u2 * u1;
+    v_2 = (a_1+1.0f) * a_2 + zero*u_m2 * a_2 * u2 * u1;
     v_4 = u_m4 * a_4 * u4;
     
     // Set position (use 3D variables)
```
So, it seems like the attribute doesn't get set at all.

**Comment by QuLogic** [comment]
Soo, an even simpler fix is to just reorder the attributes in the vertex shader. It seems that placing `a_1` first gives it id 0, which without an array seems to have the magical property of not doing anything. Or at least, that's how I've understood it from the `GL_CURRENT_VERTEX_ATTRIB` section of [glGetVertexAttrib](https://www.opengl.org/wiki/GLAPI/glGetVertexAttrib), though oddly enough, this little tidbit doesn't seem to be mentioned on the functions that _set_ attributes.

Looking at [this Mesa bug](https://bugs.freedesktop.org/show_bug.cgi?id=55503), it seems like attribute 0 is aliased when using legacy desktop GL, but shouldn't occur if in some other profile:
>    mesa/vbo: Fix handling of attribute 0 in non-compatibilty contexts
>    
>    It is only in OpenGL compatibility-style contexts where generic
>    attribute 0 and GL_VERTEX_ARRAY have a bizzare, aliasing relationship.
>    Moreover, it is only in OpenGL compatibility-style contexts and OpenGL
>    ES 1.x where one of these attributes provokes the vertex.  In all other
>    APIs each implicit call to glArrayElement provokes a vertex regardless
>    of which attributes are enabled.

**Comment by Eric89GXL** [comment]
Well that's a bummer. @QuLogic can you implement the simpler fix, and add a comment with the insights you have above? It would be good to have some record of these things in case we have future problems on Intel hardware. In the meantime, thanks for fixing this long-standing bug!
