### ISSUE TITLE
memory error when using empty Markers visual

### ISSUE THREAD

**Issue by lcampagn** [vispy/vispy#661]
I get `GL_OUT_OF_MEMORY` errors when running the following code:
```
from vispy import scene, app
import numpy as np

canvas = scene.SceneCanvas(show=True)
vb1 = canvas.central_widget.add_view()
scatter = scene.visuals.Markers()
vb1.add(scatter)
scatter.set_data(np.array([]).reshape(0, 2))
```
Running with `--vispy-gl-debug`, I see that the error occurs immediately after the call to `glDrawArrays` for the Markers visual:
```
. . .
  File "/home/luke/work/vispy/vispy/vispy/gloo/gl/_proxy.py", line 179, in glDrawArrays
    self("glDrawArrays", False, mode, first, count)
  File "/home/luke/work/vispy/vispy/vispy/gloo/gl/__init__.py", line 90, in __call__
    check_error(funcname)
  File "/home/luke/work/vispy/vispy/vispy/gloo/gl/__init__.py", line 180, in check_error
    raise err
RuntimeError: OpenGL got errors (glDrawArrays): GL_OUT_OF_MEMORY
```
With a little more digging, I see that the value of `count` is 5 for this call, when it should probably be 0. I presume this is the source of the error because adding a single item to the data array for the visual causes the error to disappear.

**Comment by jdreaver** [comment]
Should this issue be closed? I am looking through issues to work on and I came across it.

**Comment by rossant** [comment]
I'll let @almarklein answer.

What kind of work would you like to do? Bug fixes, features..?

**Comment by jdreaver** [comment]
I am currently integrating vispy into a commercial application. We have quite a few 2D and 3D plots written in pyqtgraph. I really like pyqtgraph, but I want to use shaders in a lot of visualizations. 

Right now I am implementing panning in `TurntableCamera`, and in the future I would like to get axes and ticks for 2D plots working. So you could say I am working on features :)

Of course, if what I work on makes good examples then I will create examples, and if I find bugs I will report them.

**Comment by rossant** [comment]
Axes and ticks are a high priority for us! ( #677 ) @rougier has some very good WIP in glumpy.

Looking forward to your contribs! :)

**Comment by jdreaver** [comment]
I've seen that issue. The screenshot looks really nice, and I would love that in my plots.

Thanks!

**Comment by almarklein** [comment]
Yes, I thought this would have been auto-closed.
