### ISSUE TITLE
Support image load/store extension?

### ISSUE THREAD

**Issue by karlcz** [vispy/vispy#663]
It would be very nice to be able to use image units and texture image load/store within GLSL code in vispy. https://www.opengl.org/wiki/Image_Load_Store

This would allow things like GPU-based convolution.  One can fake it a little bit with FBOs but not with the same concise code and not at all for 3D textures where the store can modify multiple Z planes.

**Comment by karlcz** [comment]
I don't know if you guys want to keep this issue around or close it.  I have lost interest in the image extension since I haven't actually needed to do general purpose stuff in the interactive rendering frames, and PyOpenCL works fine to process data prior to loading vispy textures...

**Comment by Eric89GXL** [comment]
I'll go ahead and close for now, then -- we can reopen if someone feels the need for the feature in the future
