### ISSUE TITLE
GLIR mechanism to report GLIR consumer capabilities

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#669]
If the glir consumer would have some information about the capabilities of the OpenGL context, like GL version, max texture size, etc. then it could better handle possible limitations, or at least provide more meaningful error messages. (see e.g. #652).

This information should be queried when the context gets created, and be communicated to the glir producer, where it is made available (probably as a dict).

**Comment by Eric89GXL** [comment]
@rossant do you know where the right place to put this would be, at least for the desktop? What object should I add e.g. a `opengl_version`, `max_texture_size`, or `extensions` attributes to?

**Comment by Eric89GXL** [comment]
never mind, I think I got it from the description...
