### ISSUE TITLE
XYZAxisVisuals Override Defaults

### ISSUE THREAD

**Issue by jlaura** [vispy/vispy#671]
It looks like XYZAxisVisual is not overridable in the **init** function for the verts and color arguments?  Passing in `pos=my_custom_verts` results in `TypeError: __init__() got multiple values for keyword argument 'pos'`.

The `**kwds` argument looks like it is being passed through to the Line class, via LineVisual.  Does a method exist to specify the verts, color, and / or connect kwargs?  I am hesitant to submit a PR modifying **kwds since I am not 100% sure how the passing is working.

**Comment by Eric89GXL** [comment]
@jlaura if you're still interested in this, we have started making it so that the kwargs are explicitly specified, so you could make the changes you wanted. If you don't have time let me know and I might be able to do it. (Sorry for the loooong delay.)
