### ISSUE TITLE
Add colormap support to ImageVisual

### ISSUE THREAD

**Issue by millersd** [vispy/vispy#676]
Suggest that a similar interface to matplotlib imshow colormap support be provided in Vispy - see examples [here](http://matplotlib.org/users/image_tutorial.html).

**Comment by bollu** [comment]
So, I'm implementing this.

I took the decision of not allowing passing, say, ```"hot"``` as a string to the constructor and then internally calling ```get_colormaps()```. This feels like simply adding another layer of "magic" when you the colormaps are already exposed through ```vispy.color.get_colormaps()```.

I personally feel that this fits better with Python's style of doing things - _better explicit than implicit_.

**Comment by Eric89GXL** [comment]
@bollu I think you should just pass the `cmap` argument through the `ColorMap` class (I think we have one, right?), in which case you automatically get support for strings, even though it's slightly more implicit...

**Comment by bollu** [comment]
@Eric89GXL: yes, we do have a ```ColorMap``` class. Howeber, as far as I can see, [I don't see any string support](https://github.com/vispy/vispy/blob/master/vispy/color/colormap.py#L322)

The way to get a colormap by name seems to be by using the [```get_colormap``` function](https://github.com/vispy/vispy/blob/master/vispy/color/colormap.py#L457).

I'm really not sure which ```cmap``` class you're referring to that allows you to construct a ```ColorMap``` with the name as a string.

**Comment by Eric89GXL** [comment]
I must have been thinking of Color, never mind for now, then. We can always
add string support later if we want. I agree it's less pythonic, but pretty
much every other visualization library allows you to do it that easily so
users will probably expect it.

**Comment by rossant** [comment]
> every other visualization library allows you to do it that easily so
> users will probably expect it.

+1 to allow string color maps eventually

**Comment by Eric89GXL** [comment]
FYI this is implemented in WIP PR #804
