### ISSUE TITLE
Investigate new container system in travis

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#679]
Might be of interest: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by Eric89GXL** [comment]
I looked into it, and I *think* we can't use it because you can't use `sudo`, so we can't install `xvfb` (at least not easily). But our tests don't take too long anyway, so I think we'll be okay.

**Comment by rossant** [comment]
OK, too bad. Let's keep an eye on it if this changes though.

The tests do seem to go a bit faster than before on Travis, no?

**Comment by Eric89GXL** [comment]
We disabled a bunch of the visual tests about 6 months ago, maybe that was it :)
