### ISSUE TITLE
Colorbar visual

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#682]
* with/without border
* ticks
* tick labels

![colorbar](http://i.stack.imgur.com/l7aJm.png)

**Comment by bollu** [comment]
@rossant:  what should the API for the visual look like?

**Comment by Eric89GXL** [comment]
@bollu please take a look at the existing visuals and propose an API consistent with those, and we can iterate over it here quickly before you implement it. It's likely that your visual will eventually make use of the `AxisVisual`, too, but for now you can just put a box around the colorbar, and put a label at the top and bottom (or left and right, depending on e.g. an `orientation='horizontal' | 'vertical'` parameter).
