### ISSUE TITLE
Bump VisPy version?

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#688]
Should we bump the version to 0.4.0-dev or something? Currently it is 0.3.0, which doesn't seem right.

**Comment by almarklein** [comment]
I think that should be `0.3.0.dev`?

**Comment by Eric89GXL** [comment]
We already released 0.3.0, so I think the .dev should be appended to the
next intended release, either 0.3.1.dev or 0.4.0.dev, whichever we are
aiming for. At least I thought the dev label went on the next intended
version, and not the last released version...

Eric

**Comment by almarklein** [comment]
I suppose we should test whether `3.0.dev > 3.0` or `4.0.dev < 4.0` with whatever function is intended for this. In string comparisons it's certainly the first...

**Comment by rossant** [comment]
@Eric89GXL you're right, the standard practice is to use the next planned version and to append `dev`. So it should be either `0.3.1.dev` or `0.4.0.dev` (or idem with a hypen if we want to stick to http://semver.org/ instead of PEP440). So the question is whether we want to make a maintenance release soon or not. Have there been significant improvements since 0.3.0? I believe the scene graph is faster? Also there's the experimental WebGL backend...

**Comment by rossant** [comment]
String comparison is not a valid way of comparing version numbers. For example:

```
>>> '2.0'<'10.0'
False
```

**Comment by almarklein** [comment]
I know, but people do it. It's why many packages move from e.g. `3.9` to `4.0` even when it's not a real major version bumb.

**Comment by rossant** [comment]
It's not our fault if people do stupid things. :)
I see no reason not to use the standard convention in the computer science world.

**Comment by almarklein** [comment]
No, I agree. Let's used what's most common. I was not aware that `0.3.dev` was considered `< 0.3`.

**Comment by Eric89GXL** [comment]
My vote is for 0.4.dev, shooting for a release after the sprint, but
Cyrille if you're enthusiastic about a 3.1 maintenance release before then
I'm fine with that.

Eric

**Comment by rossant** [comment]
@Eric89GXL If someone else wants a 0.3.1 release, let's do it, otherwise let's forget it. :)

In the future I think it might be good to make a couple of maintenance releases between two big releases.
