### ISSUE TITLE
RenderBuffer is missing from vispy.gloo

### ISSUE THREAD

**Issue by MikHulk** [vispy/vispy#690]
Hello,

I would test vispy in virtualenv but I got some issues when I test this code : http://vispy.org/examples/basics/gloo/post_processing.html. When I import RenderBuffer from vispy.gloo I get an error with this name that does not exist. Did this function was removed or renamed from last version ?
It is referenced in the doc. So I don't understand. I installed vispy with pip install perhaps there is an issue with pip, so I'm trying to install vispy from the source.

**Comment by rossant** [comment]
That should work with the latest GitHub version. We should add a warning on the examples that don't work with the latest stable version (or do a maintenance release).

**Comment by MikHulk** [comment]
Thanks for your reply. I built the latest Github Version. Now I'm building PyQt4 in my virtualenv because PyQt4 provided by debian package seems not to be recognized in virtualenv (I got this issue in the past with wxPython). I hope I will get an operational vispy tonight.

**Comment by hadim** [comment]
To link PyQt4 on any virtualenv under linux (ubuntu) I use this little trick : 
 
- install PyQt4 with synaptic
- activate the virtualenv you want to work with
- execute this bash function

```bash
function symlinkqt(){
    LIBS=( vtk PyQt4 sip.cpython-34m-x86_64-linux-gnu.so Ice* )

    PYTHON_VERSION=python$(python -c "import sys; print (str(sys.version_info[0])+'.'+str(sys.version_info[1]))")
    VAR=( $(which -a $PYTHON_VERSION) )

    GET_PYTHON_LIB_CMD="from distutils.sysconfig import get_python_lib; print (get_python_lib())"
    LIB_VIRTUALENV_PATH=$(python -c "$GET_PYTHON_LIB_CMD")
    LIB_SYSTEM_PATH=$(${VAR[-1]} -c "$GET_PYTHON_LIB_CMD")
    LIB_SYSTEM_PATH="/usr/lib/python3/dist-packages"

    for LIB in ${LIBS[@]}
    do
        echo $LIB
        ln -s $LIB_SYSTEM_PATH/$LIB $LIB_VIRTUALENV_PATH/ 2> /dev/null
    done
}
```

You may want to adapt the code to your case but it should be easy.

Hope it can help.

**Comment by rossant** [comment]
I would recommend to use the free [Anaconda distribution](https://store.continuum.io/cshop/anaconda/) if you have the possibility. All dependencies are already built for all OSes, including Qt and PyQt, and installing them is as simple as `conda install pyqt`.

**Comment by MikHulk** [comment]
@hadim
Ok thank you, I'm going to test this. 
@rossant 
oh yes of course in a second time I think I choose this kind of installation but now I prefer to test in a isolated environment. Thank for you indicated me this distribution whom I didn't know

**Comment by rossant** [comment]
@MikHulk Anaconda does allow you to (1) install an entire Python distribution completely isolated from the rest of the system. You don't even need to have admin rights. And (2) create various environments with different packages installed (for example you could have an environement with Python 3 and another one with Python 2, all of which living in an isolated folder like `~/anaconda`).

**Comment by MikHulk** [comment]
@rossant ok yes, Anaconda has its own system of virtual environments. Thank you I'll look for this distribution.

**Comment by MikHulk** [comment]
@rossant yes our replies are crossing
