### ISSUE TITLE
Add hsv option in ColorArray's constructor

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#692]
```python
ColorArray(hsv=mynx3array)
```

**Comment by bollu** [comment]
how should this interact with the ```color``` parameter of the constructor?

Looking at the constructor, here's what it's like:
```
    def __init__(self, color='black', alpha=None, clip=False):
```

So, well, if we add another ```hsv``` parameter, then what happens to the ```color``` parameter? do we check if both are set and then throw an Exception?

**Comment by rossant** [comment]
> So, well, if we add another hsv parameter, then what happens to the color parameter? do we check if both are set and then throw an Exception?

That's what I would do indeed. @Eric89GXL WDYT?

**Comment by bollu** [comment]
So, in that case, the default value of ```color='black'``` would have to be changed, correct? it would have to be ```color=None```.

This is because if someone opts to set the HSV value (```hsv=<value>```), then the default ```color``` parameter would still be around and would result in an exception. This is clearly wrong.

Is there code that depends on the fact that ```color``` is black by default?

**Comment by rossant** [comment]
Might be better to do color=None, check hsv, possibly raise the exception, and then set color='black' if both color and hsv are unset

**Comment by Eric89GXL** [comment]
+1 this would maintain backwards compatibility and extend functionality

**Comment by QuLogic** [comment]
Or how about `hsv=True` and `color` remains a colour (just in a different colourspace)?

**Comment by Eric89GXL** [comment]
I like that, or `units='rgb' | 'hsv'`, would allow for other types as well without param explosion

**Comment by rossant** [comment]
> I like that, or units='rgb' | 'hsv', would allow for other types as well without param explosion

+1, but is `units` the right term? maybe color_space or space or..?

**Comment by Eric89GXL** [comment]
+1 for `color_space`

**Comment by bollu** [comment]
There are the times I wish python had sum types. ```color_space``` could have been one :)
