### ISSUE TITLE
Picking example

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#693]
Showing how to implement picking or tooltip manually with `on_mouse_press` and `on_mouse_release` (might be better with `on_click` #271 but we don't have that yet), with a scatter plot or a mesh for example.

Useful until picking is properly implemented in the scene graph.

**Comment by Lorqor** [comment]
I'm trying to find out how to pick a point by mouse....and luckily I'm here :)
but.... where's the code?

**Comment by rossant** [comment]
We haven't done it yet... ;)

**Comment by Eric89GXL** [comment]
@rossant is this a dup of #140?

**Comment by rossant** [comment]
No, I'd like to have just one small example of picking that doesn't use the scene graph.
