### ISSUE TITLE
Shaders library / module

### ISSUE THREAD

**Issue by shrx** [vispy/vispy#699]
Would it be possible to include a library or module which would contain a selection of basic 2D and 3D shaders? I find it very non-user friendly that we have to write the shaders ourselves, it basically means that we have to learn another programming language.

**Comment by rossant** [comment]
We've started such a library [here](https://github.com/vispy/vispy/tree/master/vispy/visuals/glsl), it doesn't contain much for now. We'll add many new GLSL snippets soon, and we accept PRs!

Do you have specific needs for GLSL snippets?

**Comment by rossant** [comment]
Also: there are many GLSL snippets in [Glumpy](https://github.com/glumpy/glumpy/tree/master/glumpy/library) that we may want to include in VisPy at some point.

**Comment by Eric89GXL** [comment]
There are also functions and classes in `vispy.scene` and `vispy.plot` that hopefully require little to no knowledge of shaders to get visualizations working.

**Comment by lcampagn** [comment]
I'll second Eric's comment--a library of GLSL snippets is not much use to someone who wants to avoid learning GLSL. In vispy, the `Visual` subclasses are meant to be a complete encapsulation of the OpenGL/GLSL such that the user will not require knowledge of either. I would encourage you to start by looking at `examples/basics/scene` and `examples/basics/visuals`.

**Comment by shrx** [comment]
@rossant 

> Do you have specific needs for GLSL snippets?

I am writing a program with pyqtgraph that displays molecules in 3D - spheres, cylinders, lines, polygons, text - all of which can be transparent or opaque. Since pyqtgraph is going to be replaced with vispy, I'd like to transfer my project as well.

**Comment by rossant** [comment]
Closing for now, feel free to reopen or to open a new issue if you need specific visuals.
