### ISSUE TITLE
Easily update the color, width, and other properties of existing LinePlot

### ISSUE THREAD

**Issue by flutefreak7** [vispy/vispy#718]
I'm exploring Vispy and one of the first simply things I wanted to do that isn't directly supported is updating the color of an existing LinePlot.  The color can be changed, but only by also re-supplying the data with a call like this: 

    line.set_data(x, y, color=(1, 0, 0, 1))
    line.update()

It'd be nice to be able to simply do

    line.set_data(color=(1, 0, 0, 1))
    line.update()

and let the line reuse the existing data. (Instead it errors with "TypeError: Too many positional arguments given (max is 2).")

When interactively exploring data and plotting multiple lines together on a graph, I often want to recolor the lines afterwards to differentiate them, or possibly to highlight one among many.

It appears this could be accomplished very easily since this works:

    line._line.set_data(color=(1, 0, 0, 1))

So the case where line.set_data() receives 0 positional arguments should just pass kwargs to _line and _markers with no `pos` argument.  Currently an error for "Too many positional arguments" is raised, which isn't appropriate for 0 arguments anyway.

I'm fairly new to submitting issues and such, so I apologize if I'm missing any GitHub etiquette.  Thanks for all the hard work!

**Comment by Eric89GXL** [comment]
Being able to do `line.set_data(color=...)` as you propose seems simple enough to me. @almarklein or @campagnola okay with you?

**Comment by Eric89GXL** [comment]
taken care of in #744
