### ISSUE TITLE
Image visual crashes when turntable camera is used.

### ISSUE THREAD

**Issue by FiachAntaw** [vispy/vispy#725]
**Issue**: Adding an Image visual to a scenegraph viewed by a turntable camera causes Vispy to throw a TypeError when the scene is drawn.

**Cause**: InverseTransform does not define the Linear/Orthogonal/NonScaling/Isometric flags correctly, and/or ChainTransform does not correctly handle cases where these flags are NoneType.

The Image visual uses the .Linear property of its transform as an optimization hint during its draw call. In this configuration of the scenegraph the ChainTransform passed to the draw call contains an InverseTransform, which does not define the Linear/Orthogonal/NonScaling/Isometric flags (instead inheriting the flags from BaseTransform, which are initialized to None). When evaulating the flag properties, ChainTransform.Linear '&='s the corresponding properties of its children, which for InverseTransform results in an illegal ```<bool> &= <NoneType>``` operation.

There are two possible solutions to this, but I'm not sure which would be preferred, which is why I'm opening an issue instead of making a pull request:
<ul>
  <li>Have InverseTransform propagate these flags from the inverted transform</li>
  <li>Have ChainTransform check for (and propagate?) None, and change the documentation of these flags to indicate they may be NoneType</li>
</ul> 

Example code (based on examples/basics/scene/image.py):
```python
import sys
from vispy import scene
from vispy import app
import numpy as np

canvas = scene.SceneCanvas(keys='interactive')
canvas.size = 800, 600
canvas.show()

# Set up a viewbox to display the image with a turntable camera
view = canvas.central_widget.add_view()
view.set_camera('turntable')

# Create the image
img_data = np.random.normal(size=(100, 100, 3), loc=128,
                            scale=50).astype(np.ubyte)
image = scene.visuals.Image(img_data, parent=view.scene)

if __name__ == '__main__' and sys.flags.interactive == 0:
    app.run()
```

**Comment by Eric89GXL** [comment]
Can you try running this on #612? It changes a lot of the camera code. It would be good to know if that fixes your problem. If it doesn't, we can tackle the problem after that is merged.

**Comment by FiachAntaw** [comment]
PR #612 fixes this issue (InverseTransform now propagates flags from the inverted transform).
