### ISSUE TITLE
memory leak in visuals.TextVisual

### ISSUE THREAD

**Issue by w10** [vispy/vispy#735]
if you run the example from `examples/basics/scene/text.py` with a slight modification to make the canvas plot as fast as it can you can see the memory rise and rise

so add in the `'__main__'` @ line 41 or so:

    c.measure_fps()
    @c.connect
    def on_draw(event):
      c.update()

I did some digging to find the cause/a fix, here is what I found out:

- Removing the `TextVisual` object with `del` and re-creating does not release the memory
- Creating and updating the text value with the  `.text = 'new text'` setter without plotting does not increase the memory
- Only plotting without changing does increase the memory
- adding the `TextVisual._program` object modifications in `vispy\visuals\text\text.py` 458..478 to the `if self._vertices is None:` condition (adding one indent) stops the memory from increasing every `TextVisual.draw()` call, but still then changing the `TextVisual.text` requires rebuilding the vertices.

I think the problem is with binding the vertices to the program. It looks like there is some memory not released from the old vetices. But I'm not too familiar with opengl (thats why i like your library so much!)

For now I will use the indent fix in  `TextVisual.draw()` and not update the contents of my labels too much.

**Comment by Eric89GXL** [comment]
Thanks for pointing this out. We have had another issue recently about memory usage increases. It seems to be (at least) a problem with circular references. We hope to fix it soon.

**Comment by almarklein** [comment]
This seems fixed when I try it. Closing. Feel free to reopen if the error persists.
