### ISSUE TITLE
Minor style improvements to vispy.plot

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#742]
I'm mostly referring to `vispy.plot.scatter()`, but the other plot functions are also affected.
- Use a white background as a default, more common in plotting applications
- Allow passing an array of scalars for colors, with a colormap
- Choose a default first color other than white
- Define a default colormap
- Cycle through the colors of the colormap for different plots in a given canvas
- `cmap='name'` to choose a different color map (only relevant when the `color` argument consists of numbers)
- Would be great to have some qualitative colormaps in addition to the existing continuous ones
- zoom with right-click is much too sensitive to my taste

**Comment by rossant** [comment]
@bollu this is also something you could do if you want

**Comment by Eric89GXL** [comment]
+1 sounds good to me

**Comment by rossant** [comment]
To give a bit of context, I'm currently writing an article in Linux Magazine about VisPy, and I'd like to feature the plotting interface... I could try to tackle this during the sprint if no one else beats me to it!

**Comment by QuLogic** [comment]
> Use a white background as a default, more common in plotting applications

On the other hand, pyqtgraph is black, paraview is blue-ish, and "media-oriented" applications like shotwell, pitivi, etc. use a dark theme. Not saying one's better, but I guess it depends on the intended use of the result, i.e., interactive or publication, etc.

Or maybe two themes, light and dark. would work, too.

**Comment by rossant** [comment]
> On the other hand, pyqtgraph is black, paraview is blue-ish, and "media-oriented" applications like shotwell, pitivi, etc. use a dark theme

That's why I think it should only be the default for plotting (or at least mpl_plot). A black background works better than white for non-antialiased lines, like in Galry or pyqtgraph; whereas both black and white backgrounds work for high-quality antialiased lines like in VisPy. Personally I prefer black, but I think most people are used to white for plotting (especially 2D) like that's the case in MATLAB, matplotlib, glumpy, Mathematica, Maple, and virtually all 2D plotting applications I know.

**Comment by campagnola** [comment]
For interactive use (especially notebook) and for analyses oriented toward publication, a white background makes a lot more sense. Black backgrounds tend to be preferred for data acquisition / analysis settings (perhaps more reminiscent of oscilloscopes). Given that the former use cases will probably attract more novice users, I think it makes sense to have white be the default background throughout vispy, and provide a one-line call that advanced users can use to invert the color scheme. 

Maybe for now this could be done with the global config: 

    vispy.config.update(foreground='white', background='black')

..and later on we can work out a more comprehensive style system.

**Comment by marekstrelec** [comment]
Can I take this up? Regarding the white background change, I think that other default colours should be changed as well to more conventional templates. For instance markers are often blue with the white background in plotting applications.

**Comment by almarklein** [comment]
> Given that the former use cases will probably attract more novice users, I think it makes sense to have white be the default background throughout vispy, and provide a one-line call that advanced users can use to invert the color scheme. 

+1

**Comment by campagnola** [comment]
@marekstrelec, feel free to open a PR! However, let's be selective about which examples are changed--it probably does not make sense to invert everything. I would start with just a few examples so we can see what the API changes look like, and then we can decide how far to take it.

**Comment by marekstrelec** [comment]
Can you please better describe the points 5 and 6? I'm not really sure what is meant by that. Also, can you give me an example of input for "an array of scalars for colors, with a colormap". Thanks

**Comment by davidh-ssec** [comment]
@larsoner @rossant Any idea what is left for this?

**Comment by larsoner** [comment]
+1 for closing and getting to issues as new users find them / want to change them
