### ISSUE TITLE
Mouse interaction in mesh example is wrong

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#747]
Just try to move the mouse up-down or left-right while left-clicking and you'll see what I mean. (probably something to do with turntable)

**Comment by almarklein** [comment]
Might be fixed (or different) in volume PR, so better await that.

**Comment by rossant** [comment]
Any idea when the volume PR will be merged? before or during the sprint?

**Comment by almarklein** [comment]
Luke and I need to discuss some points. We hope to do it before the sprint, but we need to find a time that we are both available for chat...

**Comment by rossant** [comment]
Closed by #612.
