### ISSUE TITLE
Implement textures for meshes

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#748]
Not sure what the API could be like (need to provide the texture and UV mapping).

**Comment by bollu** [comment]
@campagnola, @Eric89GXL do we have a plan for this? It would be nice if this could be bundled with all the sweeping changes we have right now

**Comment by Eric89GXL** [comment]
I think this can be tackled after the big merge. So you can start working
on it now but we shouldn't put it in Luke's PR.

**Comment by campagnola** [comment]
+1
The less we can bundle, the better. All we really need is for the examples to run and unit tests to pass.
Sorry I've been absent lately; will be back home in a few days.

**Comment by kmuehlbauer** [comment]
@djhoese What has to be done here in addition to what'sn already implemented in #1444?

**Comment by djhoese** [comment]
I guess nothing. The TextureFilter does everything that this issue originally wanted (if I had to guess).
