### ISSUE TITLE
Improve vispy.plot interface and implementation

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#749]
This issue regroups a few thoughs and suggestions about the plot interface.

* Allow marker_size argument in LinePlot
* in `vp.plot()` markers should be optional, and off by default
* All public functions should have a full docstring
* The plot interface should be as close as possible as the scene interface. A user who wants to go from the plot interface to the scene interface for more customization and interactivity options should not need to learn yet another way of doing the same thing.
* We keep a stack of all opened figures (=canvases). When issuing a new plot command, the last opened canvas is used, or a new one is created.
* `vp.figures()` returns the list of opened figures.
* `vp.figure()` creates a new figure and returns it.
* `vp.figure(index=2)` returns the 3 opened figure, or raises an error if it doesn't exist.
* `vp.figure(index='last')` or `index=-1` returns the last opened figure.
* Plot functions return a list of visuals that have been added to the current figure.
* All plot functions will share some set of keyword arguments, and the implementation should factor out that reusable set of functionality among the functions. Example:
  * background color
  * camera
* Subplot API
* Grid, axes, legend, labels...

**Comment by campagnola** [comment]
Most of these look good to me. However I am not really a fan of the matplotlib-style global figure. Although this is nice for CLI plotting, it becomes messy when you transition to writing applications because of the use of global variables. That is the reason (as far as I know) that matplotlib has a second API that does not rely on globals, and it is one of the most common complaints about matplotlib that I have read.

The approach we have taken so far does not rely on global variables, which makes the transition from CLI to application more simple (the global variables are still there, but they do not become a required part of the public API). The design looks like:

```
class PlotCanvas(Canvas):
    def plot(x, y, ...):
        """Add a new plot line to this canvas"""

def plot(x, y, ...):
   """Create a new PlotCanvas and call canvas.plot(x, y, ...) on it"""
```

With this approach, we would do things like:

```
plot(x, y)    # Create a single-use plot

c = plot()   # Create a PlotCanvas that can be reused
l1 = c.plot(x1, y1, ...)
l2 = x.plot(x2, y2, ...)
```

**Comment by rossant** [comment]
I'm not a fan of mpl-style globals either, but I'm not completely convinced by this alternative. I think it would be better if one could do something like:

```python
# A single plot
plot(x, y)

# One canvas with 2 line plots
plot(x1, y1)
plot(x2, y2)
```

In other words, the exact same interface is used to create 1 or n plots on the same canvas. Otherwise, adding a new component to a plot means that you need to slightly change the first command, to transform it from a function call to a method call.

Also, we still have a duplication problem: "I'm confused, should I use `vp.plot(...)` or `c.plot(...)`", which is the same problem as matplotlib.

An alternative could be to discard globals completely, even in interactive mode:

```python
# Need to create canvas explicitly
import vispy.plot as vp
plt = vp.figure()
plt.plot(x1, y1)
plt.plot(x2, y2)
```

If you want quick CLI functions to draw just 1 plot, look at this beautiful hack:

```python
# plt is a special object that automatically creates a figure when needed...
from vispy.plot import plt  
plt.plot(x, y)
```

**Comment by Eric89GXL** [comment]
I think I like this suggested interface the best, it's very clear what is going on:
```Python
import vispy.plot as vp
fig = vp.figure()
fig.plot(x1, y1)
```
It also lends itself nicely to expansion to multiple subplots, etc.:
```Python
import vispy.plot as vp
fig, axes = vp.subplots(2, 2)
axes[0, 0].plot(...)
axes[1, 0].plot(...)
```
I am +1 on avoiding globals if we can, and it seems like it does not cost us much to do so. One can always do this if they really want a quick plot:
```
import vispy.plot as vp
vp.figure().plot(...)
```

**Comment by campagnola** [comment]
Yeah, this looks good.

**Comment by rossant** [comment]
> Yeah, this looks good.

+1

> It also lends itself nicely to expansion to multiple subplots, etc.:
> 
> import vispy.plot as vp
> fig, axes = vp.subplots(2, 2)
> axes[0, 0].plot(...)
> axes[1, 0].plot(...)

What is the advantage of returning two objects `fig, axes` (I think that's a matplotlib thing)? Would it be possible to return a single object that would combine both? For example:

```python
fig = vp.subplots(2, 2)
fig[0, 0].plot(...)
ax = fig[1, 0]
ax.plot(...)
fig.show()
```

**Comment by Eric89GXL** [comment]
It separates the level of the figure from that of its axes. It's matplotlib's way of thinking of the layout, but I think we have similar levels of distinction we might want to keep, too. IIRC our "axes" are basically widgets and our "figures" are SceneCanvas instances that contain those widgets.

**Comment by Eric89GXL** [comment]
...but thinking about it a bit more providing an indexing mechanism like `fig[0, 0]` could potentially work, too. Or altenatively `fig.axes[0, 0].plot` might be okay, too. Then one could do this if they wanted access to the `ax` object itself:
```
fig = vp.subplots(2, 2)
ax = fig.axes[0, 0]
```
They are pretty similar in my mind. I lean slightly toward `fig, axes = ` way of doing it because I think it will make easier transitions for people, and it takes up fewer chars.

**Comment by rossant** [comment]
> I lean slightly toward fig, axes = way of doing it because I think it will make easier transitions for people

It depends on the people. Personally I never use this syntax with matplotlib because I've always thought that the distinction between fig and axes was a bit confusing.

I've always used `plt.subplot()` but I don't really like it! doing `fig[0, 0].plot(...)` or `fig.axes[0, 0].plot(...)` seems more natural to me.

**Comment by almarklein** [comment]
What about:

    fig = figure()
    fig[2, 2, 1].plot(x, y)  # top left
    fig[2, 2, 2].plot(x, y)  # top right
    fig[1, 2, 2].plot(x, y))  # bottom (stretch whole space)

**Comment by rougier** [comment]
```
A,B,C = figure("AB"
               "CC")

A.plot(x, y)  # top left
B].plot(x, y)  # top right
C.plot(x, y))  # bottom (stretch whole space)

A,B,C = figure("AAB"
               "CCC")

A.plot(x, y)  # top left (2 third width)
B].plot(x, y)  # top right (1 third width)
C.plot(x, y))  # bottom (stretch whole space)

```

**Comment by rossant** [comment]
@rougier interesting suggestion!

**Comment by rougier** [comment]
I intended to do it for matplotlib but never found the time.
