### ISSUE TITLE
Multiple button presses are mishandled

### ISSUE THREAD

**Issue by QuLogic** [vispy/vispy#752]
This is a small thing I noticed when trying out some examples from master (7ea5156aa78460fdd4e7acd83fafd6d1f2867ad2). It occurs with pretty much every example (some trigger additional errors afterwards.) The backend name is "PyQt4 (qt)".

Press left mouse button down and don't let go. Then press right button and don't let go. Release the left button. Finally release the right button. You should get this traceback:
```
Traceback (most recent call last):
  File ".../vispy/vispy/app/backends/_qt.py", line 340, in mouseReleaseEvent
    modifiers=self._modifiers(ev),
  File ".../vispy/vispy/app/base.py", line 189, in _vispy_mouse_release
    if ev.button == self._vispy_mouse_data['press_event'].button:
AttributeError: 'NoneType' object has no attribute 'button'
```

If you press and release the buttons like a stack (i.e., let go in reverse), then there is no problem.

**Comment by Eric89GXL** [comment]
I believe I have run into this issue before. @QuLogic feel free to take a stab at fixing it if you get a chance. It's going to be some bug with how our event system handles multiple button presses, it's possible it's not coded properly yet. Or there might be a `.button` and `.buttons` field, in which case the conditional might just need to check if `self._vispy_mouse_data['press_event'] is not None` before the second part of the conditional... not sure.

**Comment by Eric89GXL** [comment]
Should be fixed in `master` now, feel free to re-open if it's not.
