### ISSUE TITLE
Error in mouse event handling

### ISSUE THREAD

**Issue by zaccaro** [vispy/vispy#754]
When the user clicks the mouse button sequence: 
LEFT_CLICK_DOWN, RIGHT_CLICK_DOWN, LEFT_CLICK_RELEASE, RIGHT_CLICK_RELEASE
or 
RIGHT_CLICK_DOWN, LEFT_CLICK_DOWN, RIGHT_CLICK_RELEASE, LEFT_CLICK_RELEASE

Makes crazy all examples and mouse buttons stop working.

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\app\backends\_qt.py", line 340, in mouseReleaseEvent
    modifiers=self._modifiers(ev),
  File "C:\Python27\lib\site-packages\vispy-0.4.0_dev-py2.7.egg\vispy\app\base.py", line 189, in _vispy_mouse_release
    if ev.button == self._vispy_mouse_data['press_event'].button:
AttributeError: 'NoneType' object has no attribute 'button'

**Comment by Eric89GXL** [comment]
Dup of #752 (for reference in case anyone else stumbles upon this)

**Comment by StephenWest** [comment]
How about this :

    def _vispy_mouse_release(self, **kwds):
        # default method for delivering mouse release events to the canvas
        kwds.update(self._vispy_mouse_data)
        ev = self._vispy_canvas.events.mouse_release(**kwds)
        if self._vispy_mouse_data['press_event'] and
 self._vispy_mouse_data['press_event'].button == ev.button:
            self._vispy_mouse_data['press_event'] = None

        if ev.button in self._vispy_mouse_data['buttons']:
self._vispy_mouse_data['buttons'].remove(ev.button)
        self._vispy_mouse_data['last_event'] = ev
        return ev

**Comment by Eric89GXL** [comment]
That might work, I'd have to look more closely at the event code to remember how it works. Feel free to open a PR if you have time!

**Comment by StephenWest** [comment]
Eric

I have tested it and it works in my application.

I am new to GitHub.  Can you please point me to the instructions for
opening a PR etc.

Thanks

Steve

**Comment by Eric89GXL** [comment]
Take a look here:

https://github.com/LABSN/expyfun/blob/master/git_flow.rst#developers

**Comment by Eric89GXL** [comment]
@StephenWest let me know if you have time to do it, otherwise I'll open a PR in a day or two

**Comment by StephenWest** [comment]
Eric

I am having beginner trouble:


I rebased to the head, made a branch called Fix#752, modified the base.py
file and committed it, all with no issue.

But my push failed?

<Snip


ERROR: Permission to vispy/vispy.git denied to StephenWest.

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists.


Snip>


I do have access, because I successfully pulled from master?

I'll keep pounding away, because I want to be able to do this...

**Comment by QuLogic** [comment]
@StephenWest Everyone has pull access to all (public) GitHub repositories; that doesn't mean you automatically have push access. You need to [create your own fork](https://help.github.com/articles/fork-a-repo/) and push your code there.

**Comment by Eric89GXL** [comment]
Yes, make sure you are pushing to your own fork. It needs to use https://
or git@gihub.com protocol, not git://. You can check that with git remote
-v.

**Comment by StephenWest** [comment]
Thanks everyone.  I think I have got the PR done?
