### ISSUE TITLE
Styles for plots

### ISSUE THREAD

**Issue by brickgao** [vispy/vispy#755]
Hi all,

I think if there are some preset style in plot like seaborn, it will be easy to catch the attention of users and draw a viewer in.

For example:

``` python
import vispy.plot as pl

pl.plot([1, 2, 3], style='light')
pl.plot([1, 2, 3], style={'axes.edgecolor':...., ....}) 
```

There are options for the style, could customize the style by using dict like this:

``` python
{'axes.edgecolor': ...,
 'axes.grid': ...,
 'axes.labelcolor': ...,
 'axes.linewidth': ...,
 'font':...,
 'grid.color': ...,
 'markers':...,
 'background':...,
 'line.size':...,
 'line.color':...}
```

I think preset style would be a dict of dict in `vispy.plot()`, just like this:

``` python
preset_style = {
  'dark': {'axes.edgecolor': ..., },
  'light': {'axes.edgecolor': ..., },
  ...
   }
```

For detail, we can check `style` in `kwds` at first:

``` python
if 'style' not in kwds:
    # use default style
elif type(kwds['style']) == str:
    # use preset style
else:
    # use costum style
```

For analysing `style`:

``` python
axes_kwds, line_kwds = {}, {}
for option in kwds['style'].keys():
    if option.startswith('axes.'):
        # maybe some conversion with kwds['style'][option]
        axes_kwds[option] = kwds['style'][option]
    if ...

canvas.axes = visuals.Axes(*axes_args, **axes_kwds)
canvas.line = visuals.LinePlot(*line_args, **line_kwds)
```

**Comment by Eric89GXL** [comment]
I haven't thought too much about this type of API. It has some drawbacks, like the various options might not be automatically detected by doc builders and IDEs, but it also seems pretty convenient. I'll give it some thought.

**Comment by queenish001** [comment]
@larsoner Can this issue be closed?
