### ISSUE TITLE
incomprehensible error message in vispy.app.Canvas.on_draw

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#759]
When there is an error generated in the on_draw function from vispy.app.Canvas, the error message is very hard to understand. An example script is included below, comment out the line 1/0 to generate an error. The normal Python error is something line

<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
</pre>

But using vispy I get

<pre>
...
.7.egg/vispy/app/base.py", line 189, in _vispy_mouse_release
    if ev.button == self._vispy_mouse_data['press_event'].button:
AttributeError: 'NoneType' object has no attribute 'button'
</pre>

An example script:

<pre><code>
from __future__ import division

#%% Load packages
import os,sys
import numpy as np
import vispy.app
from vispy import gloo
from vispy import visuals
from vispy.visuals.transforms import STTransform, TransformSystem
import gc

from PySide import QtGui, QtCore

#%%
# vispy.app.use_app('PySide')

class DosWindow(QtGui.QMainWindow):
    verbose=1
    def __init__(self, image):
        super(DosWindow, self).__init__()
        shape = image.shape
        self.setGeometry(0, 0, shape[1],  shape[0] )
        self.canvas = Canvas(image)
        self.image = image
        layout = QtGui.QVBoxLayout()
        layout.addWidget(self.canvas.native)
        layout.setContentsMargins(QtCore.QMargins(0, 0, 0, 0))
        central_widget = QtGui.QWidget()
        central_widget.setLayout(layout)

        self.setCentralWidget(central_widget)
        self.show()

    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_Q:
            exit(0)

class Canvas(vispy.app.Canvas):
    def __init__(self, image):
        super(Canvas, self).__init__()

        self.size = ((image.shape[1]) , image.shape[0] )
        self.imsize=self.size
        self.setImage(image)

        # Create a TransformSystem that will tell the visual how to draw
        self.transform_systems = []
        for image_transform in self.image_transforms:
            tr_sys = TransformSystem(self)
            tr_sys.visual_to_document = image_transform
            self.transform_systems.append(tr_sys)

        self.measure_fps()

    def setImage(self, image):
        self.images = []
        self.image_transforms = []
        self.images.append(visuals.ImageVisual(image, method='impostor'))
        self.image_transforms.append(STTransform(scale=(1, 1), translate=(0, 0)))

    def on_draw(self, ev):
        gloo.clear(color='white', depth=True)
        gloo.set_viewport(0, 0, *self.size)
        for image, transform_system in zip(self.images, self.transform_systems):
            image.draw(transform_system)

    def on_mouse_press(self, event):
        self.selection_origin_raw = event.pos
        
        print('mouse press: %s' % (event.pos, ))
        # 1/0                        # generates error

        return
 
if __name__ == '__main__':
    import sys

    im=np.random.rand( 300,600)
    print('loaded data...')
    if QtGui.QApplication.startingUp():
        app = QtGui.QApplication(sys.argv)
    else:
        app = QtGui.QApplication.instance()
        
    win = DosWindow(im)
    if sys.flags.interactive != 1 :
        app.exec_()

</code></pre>

**Comment by QuLogic** [comment]
Interesting. This is the same error as #752, so I wonder if the real error there is also being masked.

**Comment by Eric89GXL** [comment]
@eendebakpt I think this has been fixed by a recent PR, I'm going to close -- let me know if you hit the same problem again.
