### ISSUE TITLE
Memory leaking in viewbox.py example

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#771]
Not sure if this is the only case, but I saw it here. Just interact with the demo for a minute or so, and at some point the memory will start to grow. Up to a certain point its stable, so it might be the VRAM which is full and overflows in system RAM. Maybe we're uploading buffer data when we should not? Do we create new buffers without deleting them?

**Comment by Eric89GXL** [comment]
Can you try on my memory fixing branch? This sounds the same as the other bug descriptions.

**Comment by almarklein** [comment]
Let's just wait for that to get merged and we'll try again

**Comment by campagnola** [comment]
This one is caused by ViewBox creating a new FBO at every frame when running in 'fbo' mode. Fixing GL object deletion should correct the problem, but probably the ViewBox should create only one FBO as well.

**Comment by Eric89GXL** [comment]
We should also check that #735 is fixed by whatever fixes we make.

**Comment by almarklein** [comment]
Memory error is fixed. Still need to fix that an FBO is created on each draw, but made #791 for that.
