### ISSUE TITLE
Double Click not supported on Wx

### ISSUE THREAD

**Issue by StephenWest** [vispy/vispy#775]
Wx converts the second mouse press in a double click sequence to a DClick event.
The vispy _wx backend does not currently handle wx DClick events.

The proposed change would be to converts the DClick events into a standard mouse press event,
deferring double click detection to the application.

This should be compatible with other backends.

**Comment by Eric89GXL** [comment]
Sounds good to me. Eventually we want click/doubleclick-type events, too, but we can deal with that later.
