### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by Eric89GXL** [vispy/vispy#78]
It just occurred to me that people have mentioned wanting headless plotting as a feature. Currently Travis does not currently test this case, but it would be very easy to do so by adding a switch to toggle the start of the `Xvfb` service. Is headless mode currently expected to work? If so, I'll add it to Travis. If not, then this issue can stay open until someone manages to add support for it.

**Comment by tedivm** [comment]
Any status on this, or ideas on how to render things headless on linux?

**Comment by Eric89GXL** [comment]
The easy way is to use `Xvfb` if possible. Travis-CI does it and it works well.

The hard way is probably to get EGL working properly. We don't have it fully working yet AFAIK, but @almarklein might know how far away we are.

**Comment by tedivm** [comment]
I'm running Xvfb but everything we render is coming back blank. It's good to know someone else has this working though, as it means I actually have some hope :-)

**Comment by Eric89GXL** [comment]
Take a look at `.travis.yml`, you can see what it does. It manages to run the `visual` tests, which rely on reading the pixel buffers, so it must not be rendering all blank :)

**Comment by tedivm** [comment]
@Eric89GXL thanks for the help- turns out my issue was a mismatch in a shared library causing segfaults. Still tracking down the exact issue but the fact that someone has got this working is useful.

**Comment by Eric89GXL** [comment]
Fixed by #1077
