### ISSUE TITLE
Reuse FBO in viewbox

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#791]
Right now a new FBO object is created each draw, because at the time of writing gloo was not mature enough.

**Comment by Eric89GXL** [comment]
@almarklein is this as simple as creating a FBO at the initialization of the ViewBox and re-using it, instead of instantiating a new one each time?

**Comment by almarklein** [comment]
It should be. Though probably want to create it lazily, since by default a viewbox does not use an FBO.

**Comment by campagnola** [comment]
FBO method has been removed from #928 (because it would need to be reimplemented for the new scenegraph, and there are many higher-priority issues to deal with first). If we ever find the need for ViewBox FBOs again, then hopefully it will be implemented without this issue  :)
