### ISSUE TITLE
Clean up how we handle #version in GLSL

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#796]
We should allow users to specify `#version` on desktop GL. But in about-to-be-merged-per we remo e that pragme. We should undo that. We do something with version in glir.py and in visuals/shader/compiler.py (or something), we should look at that and make sure it's all consistent.

**Comment by autosquid** [comment]
hi, any progress on this?    I met the problem of "#version 330 not supported", and I suppose this issue is the root.

**Comment by j-schroeder-schetelig** [comment]
Hello,
a followup on this problem.
For my project I need to use a shader version 330.
I say vispy to use the full desktop OpenGL with vispy.use(gl='gl+'), but get this error:
"RuntimeError: Currently only GLSL #version 120 is supported."

To work around this problem, I simply deleted the version checking in the file vispy/visuals/shaders/compiler.py.
In method Compiler.compile() I simply remove the following lines:
108                        # check requested version
109                        if m.group(1) != '120':
110                            raise RuntimeError("Currently only GLSL #version "
111                                               "120 is supported.")

So far, this change does not seem to have any implications on the behaviour of vispy.

Is this a bug, or is there another way of using Vispy with modern OpenGL, as asked at the end in issue #255 ?
I think to recall, that somewhere in the documentation of Vispy was stated that Vispy itself only uses OpenGL ES 2.0, but the user is free to use also newer OpenGL. However, I cannot find it anymore.

**Comment by campagnola** [comment]
FYI there is an open PR #1316  that adds support for geometry shaders; this also implements the necessary changes to allow GLSL > 120.

**Comment by djhoese** [comment]
I think this has been resolved now. If someone thinks some of these features are not implemented please open a new PR.
