### ISSUE TITLE
examples/demo/gloo/shadertoy.py throws up a load of warnings

### ISSUE THREAD

**Issue by nippoo** [vispy/vispy#801]
```
WARNING: Variable iSampleRate is not an active uniform
WARNING: Variable iChannelTime[0] is not an active uniform
WARNING: Variable iChannelTime[1] is not an active uniform
WARNING: Variable iChannelTime[2] is not an active uniform
WARNING: Variable iChannelTime[3] is not an active uniform
WARNING: Variable iChannelResolution[0] is not an active uniform
WARNING: Variable iDate is not an active uniform
WARNING: Program has unset variables: {'iMouse'}
```

This also isn't tested by Travis for some reason or another. Probably because of the above warnings.

**Comment by rossant** [comment]
These warnings are normal actually. This example accepts any shadertoy code which may or may not implement all uniforms. I guess these warnings could be made more discrete (they are useful for debugging, not for the normal user).

**Comment by nippoo** [comment]
Hm. I don't think we should be throwing warnings in our default demos.

Why isn't this tested by Travis, anyway?

**Comment by nippoo** [comment]
Perhaps we should reopen this? The referenced PR says "fixes?" questioningly but that shouldn't be enough to close it ;)

**Comment by Eric89GXL** [comment]
@rossant and I had a discussion somewhere (maybe in the PR) where we decided it was okay for that example to have warnings, so long as we added a comment saying that it's normal behavior for it (which we did).

**Comment by rossant** [comment]
or we switch from WARNING to INFO
