### ISSUE TITLE
Interactive WebGL demos in the gallery

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#802]
I can _try_ to convert a couple of demos to standalone interactive WebGL widgets to put on the gallery (galaxy maybe?). This will require to export the list of all GLIR commands emitted during the visualization (cc @almarklein how to do that?). Then I can generate the JavaScript code to render these and implement animations and/or interactivity.

**Comment by djhoese** [comment]
This would be great as an eye candy thing and maybe have some simple example code, but we'll also have to advertise that this is *not* python running in the browser. Might have to do something similar to bokeh where you can define a python event handler or a javascript event handler. The javascript can be used for static standalone pages or interactive python sessions and the python handlers are interactive sessions only.

**Comment by kmuehlbauer** [comment]
Looks like this is very much outdated after removal of webgl backend. Can we close this @rossant?
