### ISSUE TITLE
Port skybox example from Glumpy

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#818]
https://github.com/glumpy/glumpy/blob/master/examples/skybox.py

**Comment by GuillaumeFavelier** [comment]
I tried to investigate this issue and I think the port of the skybox as it is requires the implementation of a `TextureCube` class in `vispy.gloo.texture.py` with eventually some modifications in `vispy.gloo.program.py` too.
Plus, I didn't find any alternative for the `Trackball` interaction used in the example.

**Comment by GuillaumeFavelier** [comment]
As #1589 and [#9](https://github.com/vispy/demo-data/pull/9) has been merged, I think this can be closed right?

**Comment by djhoese** [comment]
Yep, thanks again.
