### ISSUE TITLE
Port Klein bottle example from Glumpy

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#819]
https://github.com/glumpy/glumpy/blob/master/examples/geometry-parametric.py
#817 implements some geometry facilities required by this example.

Need to fix some bugs in `vp.mesh()` first.

**Comment by ericdill** [comment]
Is this issue complete? There is a referenced PR that has been merged

**Comment by Eric89GXL** [comment]
Nope, it hasn't been ported even though some of the necessary sub-functions have been

**Comment by GuillaumeFavelier** [comment]
I would like to take care of this task, what are the constraints of this example? I could reference a prototype using `SceneCanvas`.

**Comment by kmuehlbauer** [comment]
resolved by #1576, thanks @GuillaumeFavelier
