### ISSUE TITLE
Port Cartopy example from Glumpy

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#820]
https://github.com/glumpy/glumpy/blob/master/examples/cartopy.py

Require all kinds of transforms.

**Comment by kmuehlbauer** [comment]
Should be discussed in connection with #1400.

**Comment by djhoese** [comment]
I've changed my mind on this. I thought this glumpy example was using cartopy to do some transformations, but it is just using custom transformation shaders. As far as a cartopy-specific example, I don't think that will happen. Especially considering the recent discussion on #1400. I'm closing this.
