### ISSUE TITLE
Text is misplaced in scene/console example

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#821]
![cdg3](https://cloud.githubusercontent.com/assets/940580/6873155/a27d28da-d4ae-11e4-9a79-b638389294e5.jpg)

**Comment by campagnola** [comment]
Possibly related problems in scene/markers and scene/grid_large

**Comment by Eric89GXL** [comment]
`git bisect` says @almarklein should check this commit:

https://github.com/vispy/vispy/commit/597698ad0c8054a02adf8280b5a4780d180ae210

As @nippoo just said, "commit a little, commit often"...
