### ISSUE TITLE
GLIR exporter

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#825]
For any VisPy visualization I want a very simple way to export to a Python list (or a text file in JSON or whatever) the list of all GLIR commands that have been emitted so far. @almarklein could you help me with this please? How would it work?

Once we have a JSON file with the list of GLIR commands, it becomes very easy to debug failing WebGL visualizations. I can easily write a JavaScript module that loads such a file and displays it using gloo.js.

**Comment by almarklein** [comment]
You'd need to create  a GlirParser that just passes all commands to the default parser but also logs the commands. You set that parser at the start end after a short while you make it export the commands.

**Comment by rossant** [comment]
Ah, makes sense, thanks! I'll give it a try.

**Comment by Eric89GXL** [comment]
Closing since I think @izaid just got this, feel free to reopen if not

**Comment by Eric89GXL** [comment]
@izaid in the future if there are issues you directly address feel free to put "Closes #N" in the PR description, it will auto-close the issue when the PR is merged
