### ISSUE TITLE
Bug in examples/basics/scene/isosurface.py

### ISSUE THREAD

**Issue by jvtrudel** [vispy/vispy#830]
$ python isosurface.py 
    Generating scalar field..
    Traceback (most recent call last):
      File "isosurface.py", line 49, in <module>
        cam.set_range((-10, 10), (-10, 10), (-10, 10))
    AttributeError: 'TurntableCamera' object has no attribute 'set_range'

**Comment by almarklein** [comment]
Are you sure you have the latest Master? It works fine for me.

**Comment by jvtrudel** [comment]
You're right. Sorry.
