### ISSUE TITLE
Cannot determine DPI on Amazon EC2

### ISSUE THREAD

**Issue by izaid** [vispy/vispy#836]
I'm trying to get VisPy going on an Amazon EC2 instance running an IPython notebook server. I've got the IPython notebook working fine, so now it is time to sort out VisPy.

In IPython, I'm getting a runtime error "could not determine DPI" whenever I try to create a canvas, though app.use_app('ipynb_webgl') works fine. Do I need to be running X Windows or something on the server, despite doing all the rendering in the browser?

**Comment by rossant** [comment]
I remember seeing this in a similar use-case. The fix is to implement a handshake for Python/JS where JS tells Python the dpi and other GL-related info. There shouldn't be a need for any X server here because the browser does all the rendering. I think Cedric has worked on this.
cc @nippoo @cgestes

**Comment by izaid** [comment]
@rossant @nippoo @cgestes Can one of you tell me roughly what needs to be done? If yes, then I'll give this a shot today or tomorrow.

**Comment by Eric89GXL** [comment]
I don't think we should in principle raise an error if DPI couldn't be determined (probably warning instead), so I have added this to #834. You should probably still work out the IPython communication even though it will now just be a warning, though :)

**Comment by nippoo** [comment]
Out of interest, what do we need the DPI for in the browser, when the browser itself already does a ton of scaling/resizing/zooming depending on the users' preference? I'm not sure how much we can rely on correct cross-browser DPI reporting, but perhaps it's worth testing...

**Comment by izaid** [comment]
@nippoo If I'm running VisPy in IPython, where should the DPI come from? There is only the browser in that situation, isn't there?

**Comment by nippoo** [comment]
Well yes, obviously - you should be able to do this with https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia. But I don't know what happens if the browser zooms in or out, or how we should even handle those cases (if the user has the browser set at 80% zoom, or 150% zoom because they have bad eyesight, should we scale the DPI down by that zoom level?)

**Comment by rossant** [comment]
Using a default value would be fine. The point is to implement handshake
for other gl caps like max texture size etc

**Comment by almarklein** [comment]
> I'm trying to get VisPy going on an Amazon EC2 instance running an IPython notebook server.

Sweet!

**Comment by izaid** [comment]
@rossant An update on this. Right now, master is setup to return a default DPI (96) with a warning instead of raise an exception. With this change, I get a black screen, which is progress.

I've tried with the ImageVisual and the LineVisual, and all I see is a black screen.

Can you direct me at what should be done to help sort this out? I'm happy to help, but not sure what to do.

**Comment by rossant** [comment]
Do you mean that you get a black canvas on any VisPy example when you use the WebGL backend on a notebook served by Amazon EC2?

Do you get any JS error message? (F12)

**Comment by izaid** [comment]
Yes, exactly that. I've only tried LineVisual and ImageVisual so far, both with just a black canvas.

No JS error.

**Comment by izaid** [comment]
To be clear, I'm literally copying and pasting the examples, except without the app.run and with app.use_app('ipynb_webgl') before anything else.

**Comment by rossant** [comment]
Ah. Might be a WebSocket problem with EC2? Not sure how to configure the
server properly...

**Comment by izaid** [comment]
Amazon EC2 has an option to allow "All traffic", which I've enabled. Still nothing.

This obviously could be a lot of things, ranging from a VisPy issue to something completely independent. Any thoughts on who we might ask?

**Comment by rossant** [comment]
Can you try various IPython widgets?

You use IPython 3 right?

Also you can inspect the websocket frames in the browser dev tools. You
want to see if the comms are being exchanged correctly.

**Comment by izaid** [comment]
Yes to IPython 3. I also confirm the IPython widgets work.

**Comment by rossant** [comment]
Can you give me access to the notebook?
You use the very latest master of vispy? We made a change to webgl earlier
today

**Comment by izaid** [comment]
@rossant Yes, I'm going to give you access to my notebook on EC2. Give me a few minutes, I'll email you.

Master is from minutes ago.

**Comment by izaid** [comment]
Fixed this.
