### ISSUE TITLE
FIX: Guarantee on_resize before on_draw

### ISSUE THREAD

**Issue by larsoner** [vispy/vispy#841]
We should do this for all backends and all platforms, @nippoo has seen it not happen on OSX with either glfw or pyqt4 (or both?).

**Comment by nippoo** [comment]
I guess this isn't a bad idea. At the moment I've refactored all the relevant examples to have an `activate_zoom()` method which is called in the `__init__` as well as `on_resize`. So if we can guarantee that on_resize() will be called before, we should re-factor it back to avoid two calls. At the moment everything works, it's called once in the init then once on subsequent resizes...

**Comment by queenish001** [comment]
@larsoner

**Comment by djhoese** [comment]
I don't feel like finding the relevant issues, but I believe the issues regarding PyQt4 and resizing have been fixed and if not fixed for glfw they have at least been identified in another issue. I think backends generally handle resize events from the GUI framework and for those that play well (PyQt usually) things typically work. I'm going to close this as it hasn't been an identified problem recently. We can reopen if needed.
