### ISSUE TITLE
transparency for linevisual

### ISSUE THREAD

**Issue by eendebakpt** [vispy/vispy#848]
I am trying to plot a semi-transparent line over an image. I use the alpha channel of the LineVisual to set transparency. The line becomes transparent, but the underlying image is not shown through the line.

An example script is included below.

<pre><code>
"""
Simple demonstration of ImageVisual.
"""

import numpy as np
import vispy.app
from vispy import gloo
from vispy import visuals
from vispy.visuals.transforms import STTransform, TransformSystem

image = np.random.normal(size=(100, 100, 3), loc=128,
                         scale=50).astype(np.ubyte)

class Canvas(vispy.app.Canvas):
    def __init__(self):
        self.image = visuals.ImageVisual(image, method='subdivide')
        self.image_transform = STTransform(scale=(7, 7), translate=(50, 50))
        vispy.app.Canvas.__init__(self, keys='interactive')
        self.size = (800, 800)
        self.show()
        
        # Create a TransformSystem that will tell the visual how to draw
        self.tr_sys = TransformSystem(self)
        self.tr_sys.visual_to_document = self.image_transform

        pos=np.array([[10,20],[70,40],[60,80], [50,55], [5,5],[5,10]] , np.float32)
        colors=np.zeros( (6,4), dtype=np.float32)
        colors[:,0]=1
        colors[:,3]=.5
        self.lines = visuals.LineVisual(pos=pos, color=colors, connect='segments', mode='gl', width=6)

    def on_draw(self, ev):
        gloo.clear(color='black', depth=True)
        gloo.set_viewport(0, 0, *self.size)
        self.lines.draw(self.tr_sys)
        self.image.draw(self.tr_sys)

if __name__ == '__main__':
    win = Canvas()
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
</code></pre>

**Comment by campagnola** [comment]
You need to draw the lines after the image and either disable depth testing or ensure that the lines are not obscured by the image.

**Comment by eendebakpt** [comment]
Thanks for the suggestion. I tried the code below, but the result is that the lines are obscured by the image. I also tried the blend=True and 'translucent' options for gloo.set_state, but these did not result in the line being transparent.

<pre>
<code>
import numpy as np
import vispy.app
from vispy import gloo
from vispy import visuals
from vispy.visuals.transforms import STTransform, TransformSystem

image = np.random.normal(size=(100, 100, 3), loc=128,
                         scale=50).astype(np.ubyte)


class Canvas(vispy.app.Canvas):
    def __init__(self):
        self.image = visuals.ImageVisual(image, method='subdivide')
        self.image_transform = STTransform(scale=(7, 7), translate=(50, 50))
        vispy.app.Canvas.__init__(self, keys='interactive')
        self.size = (800, 800)
        self.show()
        
        # Create a TransformSystem that will tell the visual how to draw
        self.tr_sys = TransformSystem(self)
        self.tr_sys.visual_to_document = self.image_transform

        pos=np.array([[-20,20],[70,40],[60,80], [50,55], [5,5],[5,10]] , np.float32)
        colors=np.zeros( (6,4), dtype=np.float32)
        colors[:,0]=1
        colors[:,3]=.5
        self.lines = visuals.LineVisual(pos=pos, color=colors, connect='segments', mode='gl', width=6)
        gloo.set_state(depth_test=False)


    def on_draw(self, ev):
        gloo.clear(color='black', depth=True)
        gloo.set_viewport(0, 0, *self.size)
        gloo.set_state(depth_test=False)
        self.image.draw(self.tr_sys)
        gloo.set_state(depth_test=False)
        self.lines.draw(self.tr_sys)

if __name__ == '__main__':
    win = Canvas()
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
</code>
</pre>

**Comment by campagnola** [comment]
My mistake--setting depth_test will not work in this case because the LineVisual overrides that when it draws. We've discussed allowing that to be overridden, but that has not been implemented yet. As a workaround, you can give each coordinate a z value of -0.1.

**Comment by eendebakpt** [comment]
Settings the z coordinate to a negative value works, so I will close the issue. A working example is included below.

Should this be documented somewhere? I can make an example for transparency and make a pull request, but if the implementation will change in the near future I will skip that.

<pre><code>
import numpy as np
import vispy.app
from vispy import gloo
from vispy import visuals
from vispy.visuals.transforms import STTransform, TransformSystem

image = np.random.normal(size=(100, 100, 3), loc=128,
                         scale=50).astype(np.ubyte)


class Canvas(vispy.app.Canvas):
    def __init__(self):
        self.image = visuals.ImageVisual(image, method='subdivide')
        self.image_transform = STTransform(scale=(7, 7), translate=(50, 50))
        vispy.app.Canvas.__init__(self, keys='interactive')
        self.size = (800, 800)
        self.show()
        
        # Create a TransformSystem that will tell the visual how to draw
        self.tr_sys = TransformSystem(self)
        self.tr_sys.visual_to_document = self.image_transform

        pos=np.array([[-20,20],[70,40],[60,80], [50,55], [5,5],[5,10]] , np.float32)
        pos=np.hstack( (pos, -np.ones( (pos.shape[0],1))) )
        colors=np.zeros( (6,4), dtype=np.float32)
        colors[:,0]=1
        colors[:,3]=.45
        self.lines = visuals.LineVisual(pos=pos, color=colors, connect='segments', mode='gl', width=6)
        #gloo.set_state(depth_test=True, blend=True)

    def on_draw(self, ev):
        gloo.clear(color='black', depth=True)
        gloo.set_viewport(0, 0, *self.size)
        self.image.draw(self.tr_sys)
        self.lines.draw(self.tr_sys)

if __name__ == '__main__':
    win = Canvas()
    import sys
    if sys.flags.interactive != 1:
        vispy.app.run()
</pre></code>
