### ISSUE TITLE
Pick one of 'style', 'method', and 'mode'

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#851]
Visuals can each provide multiple mechanisms for drawing the same data.  We are currently using three different names to describe this: VolumeVisual uses 'style', ImageVisual uses 'method', and LineVisual uses 'mode'. Let's pick one. 

I vote against 'style' because I'd like that to eventually refer to a different set of properties (line width, color, font, etc.)

**Comment by Eric89GXL** [comment]
+1 for method

**Comment by almarklein** [comment]
On 02-04-15 06:15, Eric Larson wrote:
> +1 for method

+1

**Comment by rossant** [comment]
+1

**Comment by Eric89GXL** [comment]
Closing for #853 and #804
