### ISSUE TITLE
Clearer repeat error messages

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#866]
Instead of displaying multiple lines:

```python
...
ERROR: Invoking <function Session._show_view.<locals>.on_draw at 0x7fd48e4f3bf8> repeat 3
ERROR: Invoking <function Session._show_view.<locals>.on_draw at 0x7fd48e4f3bf8> repeat 4
ERROR: Invoking <function Session._show_view.<locals>.on_draw at 0x7fd48e4f3bf8> repeat 5
...
```

it might be clearer to display *one* line with the number of repeats that gets updated in real-time (on the same line):

```python
ERROR: Invoking <function Session._show_view.<locals>.on_draw at 0x7fd48e4f3bf8> repeat 5
```

This is similar to how identical error messages in JavaScript are displayed in Chrome's developer console.

**Comment by Eric89GXL** [comment]
It might be tricky because if other errors are printed in the meantime, the backspace won't work as expected. But it might work enough that it would be worthwhile. It already logarithmically spaces messages, so I personally don't feel like the annoyance of the repeated messages is worth the effort to do it myself, though :)

**Comment by rossant** [comment]
At least replacing the first 10 repeats by a single line would be an improvement :)

**Comment by almarklein** [comment]
> It might be tricky because if other errors are printed in the meantime, the backspace won't work as expected

That's a good point. Fortunately, we only have to remove 1 char (or 2/3 if >10), so if things go wrong, it should not be that bad. I would not call this high priority though.

**Comment by Eric89GXL** [comment]
@rossant would log-2 spacing (1, 2, 4, 8, ...) work for you? I think it's going to work better than assuming backspace will work. I think there are a lot of cases where it might not.

**Comment by rossant** [comment]
+1
