### ISSUE TITLE
Can't import ext.glfw

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#874]
I have glfw 3.1.1 installed from source and the python wrapper version 1.1.1 installed from pip. This is what I get when running examples using the glfw backend:
```
>>> import vispy.ext.glfw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "vispy/ext/glfw.py", line 63, in <module>
    _glfw = ctypes.CDLL(_glfw_file)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libglfw.so.3: cannot open shared object file: No such file or directory
```
However the import works if import glfw manually first: 
```
>>> import glfw
>>> import vispy.ext.glfw
```
Perhaps we need to update ext.glfw?

**Comment by Eric89GXL** [comment]
Probably, yeah, I'll try to look today

**Comment by Eric89GXL** [comment]
Maybe a stupid question, but did you happen to do `sudo ldconfig` after installing `glfw` from source?

**Comment by Eric89GXL** [comment]
...I think your OS should be able to find the library if you've done it, and installed to the default location `/usr/local/lib`

**Comment by Eric89GXL** [comment]
FWIW that wrapper is completely different from ours. Different naming conventions, etc., so we can't just drop it in.

https://github.com/FlorianRhiem/pyGLFW/blob/master/glfw.py

**Comment by campagnola** [comment]
> did you happen to do sudo ldconfig after installing glfw from source?

AH. That was it, thanks.
