### ISSUE TITLE
SceneCanvas does not work in WebGL

### ISSUE THREAD

**Issue by izaid** [vispy/vispy#876]
ccing @rossant @almarklein @campagnola

I tried to port the ImageVisual + SceneCanvas example to IPython, and I'm getting an error in vispy.min.js. I've tried to debug this a bit with @cgestes kind help, but I'm flailing around miserably. This might be related to https://github.com/vispy/vispy/issues/875

**Comment by rossant** [comment]
I have 0 knowledge of the scene graph's internals so I'm afraid I won't be very helpful..
What I can say is that texture support in vispy.js is still limited, and framebuffers haven't been implemented yet. I don't know if the scene graph uses those.
Almar and Luke should know more

**Comment by campagnola** [comment]
Irwin, can you post a bit of code to run in ipython and the error(s) you are getting just so we're all on the same page?

**Comment by Eric89GXL** [comment]
dup of #875
