### ISSUE TITLE
GridlLines not working in 3D

### ISSUE THREAD

**Issue by gabyx** [vispy/vispy#877]
It seems, that the GridLines Visual only works for 2D Scenes so far.

Would be cool to add 3d support :-)

From Luke:  

GridLines only works in coordinate systems that leave the z axis unchanged. I recently fixed the same issue with Image; that solution would probably apply as well in this situation.

**Comment by queenish001** [comment]
@djhoese

**Comment by djhoese** [comment]
I thought this was still an issue, but it looks fine to me in the https://vispy.org/gallery/scene/grid_layout/grid.html#sphx-glr-gallery-scene-grid-layout-grid-py example. Anyone feel free to comment if I'm wrong and we can reopen this.
