### ISSUE TITLE
rename markers visual to scatter visual

### ISSUE THREAD

**Issue by gabyx** [vispy/vispy#879]
This would be more according to all other plotting libraries, matlab, matplotlib, and so on :+1:

**Comment by campagnola** [comment]
I have a slightly different take:
* `MarkerVisual` should remain as it is, and will eventually be superseded by `PointVisual` which will be based on the new `PointCollection`. This will be a general-purpose, primitive visual like `LineVisual` and `MeshVisual`.
* `ScatterVisual` should be a new wrapper around `Marker/PointVisual` that is specifically for drawing scatter plots, and thus will have an API more targeted for scientific visualization.

**Comment by gabyx** [comment]
Good points, so this issue can be closed I think :+1:

**Comment by Eric89GXL** [comment]
Cool. We might as well leave it open as a reminder to follow @campagnola's plan until those points are implemented.

**Comment by djhoese** [comment]
6 years later...

I think to be more inline with where VisPy is now and other things that have been discussed laterly, we may actually keep MarkersVisual as it is and have a higher level ScatterPlotVisual which will act as a wrapper around the various axes, labels, ticks, and the actual scatter (MarkersVisual) components. This is similar in my mind to the LinePlotVisual that currently exists, although that doesn't actually include the axes.

**Comment by kmuehlbauer** [comment]
And another half year later...

@djhoese @larsoner Should we come to a conclusion here?

**Comment by djhoese** [comment]
Closing this. We are not going to rename MarkersVisual at this point. There is no benefit and will only cause issues for users. The plan for a higher level plotting API (including the cycle 4 CZI grant) would make more sense for naming things as "scatter". Markers are not limited to scatter plots.
