### ISSUE TITLE
Add HiDPI helper to TransformSystem

### ISSUE THREAD

**Issue by larsoner** [vispy/vispy#884]
We have this in our code in multiple places:

```
d2f = transforms.document_to_framebuffer
self._program['u_px_scale'] = (d2f.map((1, 0)) - d2f.map((0, 0)))[0]
```

We should add a property to TransformSystem to directly expose this scale factor.

**Comment by campagnola** [comment]
I think this can already be replaced with `prog['px_scale'] = trs.canvas.pixel_scale`.

**Comment by davidh-ssec** [comment]
@larsoner Maybe I'm searching for the wrong patterns but I don't see this `d2f.map` transform anywhere in the code anymore.
