### ISSUE TITLE
Depth testing is broken in master

### ISSUE THREAD

**Issue by inclement** [vispy/vispy#890]

**Comment by campagnola** [comment]
Can you be more specific? It works in the surface plot example.

**Comment by inclement** [comment]
@campagnola When I first noticed this I mistakenly thought it was all Meshes, but actually I'm only seeing it consistently with Tubes and a Mesh merging visual I have, which makes me suspect it may be my fault following recent changes in Mesh. I'll try to narrow it down some more.

**Comment by inclement** [comment]
I bisected this to 8c84c6563290b0150db244f3a6c53bf2051e0c59 or something directly related.

**Comment by inclement** [comment]
Okay, it turns out I already noticed this, reported it at https://github.com/vispy/vispy/issues/871 and acknowledged the fix from lcampagnola in #873 (preventing the Node init overriding the Mesh). But then somehow forgot about it and thought it was resolved in master.

So...quite silly on my part, sorry about that! I'll look forward to https://github.com/vispy/vispy/pull/873 being merged.
