### ISSUE TITLE
Minor volume rendering/camera issues

### ISSUE THREAD

**Issue by larsoner** [vispy/vispy#893]
Found in a recent PR in the volume example, not sure when they popped up:
- camera reset doesn't seem to do anything for me for TurntableCamera, and for Arcball it only resets the distance (not rotation)
- isosurface threshold can be set negative (should probably be limited here >= 0)
- scroll wheel with FlyCamera doesn't seem to work:

```
  File "/Users/larsoner/custombuilds/vispy/vispy/scene/cameras/cameras.py", line 1567, in viewbox_mouse_event
    PerspectiveCamera.viewbox_mouse_event(self, event)
  File "/Users/larsoner/custombuilds/vispy/vispy/scene/cameras/cameras.py", line 764, in viewbox_mouse_event
    if self._distance is not None:
```

cc @campagnola @almarklein

**Comment by midgetfc** [comment]
Hello, I also found a minor problem while toying with the volume exemple : 
If you try to display a full solid (all voxels the same value), you get a division by zero error in visuals/volume.py l459 (set_data, #apply clim).
Should maybe have a test here, setting vol to all ones if self._clim[1] == self._clim[0] and different from zero.

**Comment by bollu** [comment]
@Eric89GXL did you try and ```git bisect``` it to find out the exact commit that introduced the problem?

**Comment by Eric89GXL** [comment]
No, I haven't done it yet.

**Comment by Eric89GXL** [comment]
@midgetfc thanks for the report -- feel free to try a bug fix if you have time. Otherwise we will take care of it while addressing these other issues.

**Comment by midgetfc** [comment]
@Eric89GXL I opened a PR with the small fix. As you may have guessed, I'm completely beginner with git and github, and I'm not sure I use them in a proper way. Please tell the less obtrusive way to contribute, for a beginner.
Thanks

**Comment by djhoese** [comment]
@larsoner Do you have any idea if these are still an issue? I am able to use my scroll wheel with the fly camera with the volume example.

**Comment by larsoner** [comment]
Let's close and reopen if needed
