### ISSUE TITLE
Optimize and complete the scenegraph

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#894]
Thinking out loud: here is my plan for completing the scenegraph and taking care of performance issues.

The major issues right now are (1) multi-parenting in the scenegraph suggests an architecture where visuals do not know their transformations until draw time. Consequently, a lot of unnecessary work is done on every redraw. (2) The scenegraph needs picking and (3) some concept of a "scene" coordinate frame (mainly for lighting). 

- [x] **Visual views:** (#895) similar to @rougier's collection views, this would allow each visual to operate with multiple copies of its shader program, and each copy may have different transforms. This is meant to solve (1) while still allowing a visual to be drawn multiple times per frame. This will also allow creating extra views for exporting at different resolutions, views with picking filters applied, etc. 

    - [x] MultiProgram - Behaves like ModularProgram, but internally wraps multiple copies of the program. This will make it easier for visuals to handle multiple shader programs.
    - [x] New visual class organization: `BaseVisual` defines the basic API (draw, bounds, attach, etc.), `Visual` is anything that can be drawn with a single shader program (or MultiProgram), and `CompoundVisual` consists only of sub-Visuals with no program of its own. This organization will be necessary in order to implement the `BaseVisual` API in a generic way (otherwise each visual would have to reimplement the complete API).
    - [x] Remove multi-parenting from scenegraph and replace with the ability to automatically create a new view on an entire branch of the graph. This allows us to statically define the transform system used by each node in the graph, and only apply changes as they are needed. 
- [x] Scenegraph draw should only involve calling a cached list of functions:

    ```
    def draw_scene():
        if self.draw_order is None:
            self.generate_draw_order()
        for visual in self.draw_order:
            visual.draw()
    ```

- [x] Transforms need a `simplified` property that contains a collapsed (and cached) version of the transform (#832). To avoid re-simplifying chains every time a view changes, we can mark specific transforms as 'dynamic', which will prevent them being joined during simplification. For example, here is a typical transform chain:

    ``` 
    framebuffer -> canvas -> view_transform -> visual_transform1 -> visual_transform2
    ```

    If we collapse this chain to a single matrix transform, then the matrix needs to be recomputed from its constituent pieces every time the view transform is updated. Instead, we can mark the view transform as dynamic, which forces the simplified transform to look like:

    ```
    simplified_transform1 -> view_transform -> simplified_transform2
    ```

- [x] **Picking.** This requires drawing the scene with a constant, flat ID color for each visual.
    - [x] Might be done by creating a separate view of the scene in which an extra picking filter is applied to every fragment shader. Another possibility is to add something like 

        ```
        if( u_picking == 1 ) {
            glFragColor = u_picking_id;
            return;
        }
        ```

       to every fragment shader.
    - [ ] Requires allowing return values from gloo calls.
- [x] **Scene coordinate frame.** Add a 'scene' coordinate frame to `TransformSystem`:

    ```
    render - framebuffer - canvas - scene - visual
    ```

    This will allow us to guarantee correct lighting.
    - [ ] Fix phong shading in MeshVisual
    - [ ] Add a visual example showing correct use of scene cs

Obviously this is a lot of work. Perhaps we can break this into sub-issues and make assignments? Ping @Eric89GXL @almarklein @rossant

**Comment by Eric89GXL** [comment]
This sounds like a good starting proposal to me. I think we can hash out the details in PRs as we go. I agree with the 0.5 milestone.

I'm fine with having to add a special picking switch to all fragment shaders. It's not elegant, but it should get us the functionality in a simple way to start. (We can always try to figure out some other more elegant way later.) I might have time to take that on in the next couple of months.

**Comment by Eric89GXL** [comment]
BTW does this supersede #832?

Any idea about who would be good to work on each issue? I might be able to work on picking this summer (July-ish?), if not sooner.

**Comment by campagnola** [comment]
Yeah, consider this the super-issue of #832 (and potentially others as well) but don't close that one--we will probably want to have a sub-issue for each point raised here. 

I am already working on the first two points. I listed them first because they will involve a major overhaul of visuals and scenegraph. However we should still be able to work in parallel--the transform system will not be affected much, so #832 is safe to work on. Picking first requires being able to return values from gloo calls and a basic gloo example to demonstrate how that will work; that can be done in parallel too.

**Comment by bollu** [comment]
@campagnola: I wouldn't want our work to collide and lead to lost time. so, well, should we separate our tasks out on this so we don't step on each other's toes? If you could point me to something concrete I can help with the SceneGraph (so we can later integrate collections into this as well), that would be great!

**Comment by Eric89GXL** [comment]
@bollu I think you can safely work on:

1. getting return values from `gloo` / `GLIR`
2. getting picking working

That would be a good start.

**Comment by bollu** [comment]
@Eric89GXL How do I test both of them?

For returning values, write a dummy shader and check if you can get the return values?

And as for picking, build a demo where you can pick / select objects?

**Comment by rossant** [comment]
there is a picking demo in glumpy cc @rougier

**Comment by Eric89GXL** [comment]
right now `gloo` commands go through `glir`, and those are one-way -- you can send GL commands, but you can't really get much for return values. For picking we need to be able to get values out. You could start with anything really, but modifying `read_pixels` to go through `gloo` instead of `gl` directly would be a good start. @rossant do you know a good way to do this?

Maybe the first step should be to make it so that it works for desktop / GL-ES2.0 setups, and raise an error if someone tries in on our remote backends. So basically add a small "capabilities" bit to each GLIR consumer, where the new "capability" would be returning values -- and that would only be supported by the desktop GLIR module for now. WDYT?

**Comment by Eric89GXL** [comment]
...after the return-values-from-glir is sorted out, *then* you can move on to picking, which glumpy should be able to understand. Basically you'd need to attach something to all fragment shaders to draw each visual in a scene with a different fixed color -- I think you'd want to start at the level of `scenegraph` for this, at least for the first pass. But let's worry about that after we have return values from GLIR.

**Comment by bollu** [comment]
@Eric89GXL what are the remote backends that exist right now? I'm not aware of them.

So, first get the return values working, and then get the other stuff done? 

And, well, for returning values, what's the method you want to use?

I was considering constructing an FBO and then writing out values to it from the shader, using ```read_pixels``` to read out the data written by the shader.
Is there a better / faster method?

**Comment by rossant** [comment]
i think having return values in glir will be difficult, because it's all asynchronous. I'm not sure how the python glir backend is implemented, @almarklein will know
might be better to bypass glir and use gl directly

**Comment by bollu** [comment]
So, use ```gl``` directly with the FBO approach?

**Comment by rossant** [comment]
I think so yeah

**Comment by bollu** [comment]
hm, all right.

Any particular file / module that I can just start by taking a look at? Like, where in ```gloo``` would have to modify it to go through ```gl``` (since it uses ```glir``` right now). And where is the ```read_pixels``` that should go through ```gloo?```

Is this the right ```read_pixels``` function? [vispy/gloo/wrappers.py](https://github.com/vispy/vispy/blob/5695b93194863c4b15a2423f3abe12e948d9b7ac/vispy/gloo/wrappers.py#L604)

**Comment by Eric89GXL** [comment]
For that approach you wouldn't actually have to modify anything. You'd just want to make sure the Canvas's GLIR queue is flushed, then use `gloo.gl` calls directly. `read_pixels` uses `gloo.gl` already. So I guess you can just about move on to picking?

**Comment by bollu** [comment]
If it is that straight forward, then yes, I suppose I can.

So, why does _each_ visual need a different color when we choose to implement picking? Is it not enough to just  have one _picking_ color? I don't think the problem statement is very clear to me just yet.

what exactly does picking imply? coloring objects that have been selected with the mouse with a custom color? (this is what I assume you meant by picking). Or something else?

**Comment by Eric89GXL** [comment]
So imagine you have 10 objects in a scene, and I want to know which one I clicked on. You draw all 10 in some opaque color (for vertices that weren't transparent before) to a Framebuffer, extract the image, and find out what color was under the cursor. That tells you which object you were on. Make sense?

**Comment by bollu** [comment]
ah, yeah. Makes sense. Since you know what color each object is, you can figure out what color is under the mouse cursor position, which tells you which object is being hovered over, yes?

So, how do you generate unique colors for each object?

**Comment by campagnola** [comment]
@bollu, it might be better to start this work from my `multiprogram` branch. All visuals are currently broken there, but there is a new example in `examples/basics/visuals/line_prototype.py` that is my sandbox for exploring how the new visual system will work. This is what needs to be done:

1. Add a `PickingFilter` class that sets the fragment color to the ID value (and decide whether all visuals should have this filter attached by default). See the `ColorFilter` class for inspiration.
2. The filter class should also have an enabled/disabled flag (perhaps ALL filters should have this?)
3. Need to decide how to tell the visuals that they should draw for picking. I see two possibilities:
    * If all visuals have a default PickingFilter, then we can just say `visual.draw(picking_id=...)` and the visual will handle it (I think I prefer this option). 
    * Otherwise, we could do something like

        ```
        pick_filter = PickingFilter()
        visual.attach(pick_filter)
        . . . 
        pick_filter.enabled = True
        visual.draw(gl_state='opaque')  # don't let ID colors blend
        ```

4. Add to `line_prototype` a mouse press callback that activates an FBO, sets the GL viewport to a 10x10 box around the mouse cursor, draws all visuals, and then reads the IDs back out of the FBO.
5. TransformSystem needs to somehow be aware of the new viewport coordinates and adjust accordingly. My first thought is that we should only modify the viewport via the canvas, and it could emit a viewport_changed event that is caught by the transform system.. 

Let me know which of these (if any) you'd like to work on.

**Comment by Eric89GXL** [comment]
Don't we now have filter support in `master` that could be used?

**Comment by campagnola** [comment]
Yes, however:

* There are so many other things changed in the new visual system (especially wrt 5) that it does not make sense to me to start in master.
* Adding picking will require some changes to the canvas/transforms/gloo triad; it would be much better to base these changes on the new system.
* `line_prototype.py` is relatively simple compared to the existing visuals library, which makes it easier to experiment.

Downside: the new system has not been vetted at all. More on that elsewhere..

**Comment by bollu** [comment]
Also, I'm probably out of my depth here, but don't games solve the exact same problem in a different way?

There's usually a structure that maintains a spatial hierarchy (the most common one that I've seen used in 3d are [octrees](http://en.wikipedia.org/wiki/Octree)).

So, since you have the screen position of the mouse click, you use the inverse of the modelview matrix to convert to world coordinates, after which you raytrace and "pick" the first intersection. 

This requires the existence of spatial partitioning and a way to construct collisions with a ray (using AABB's or something similar). 

[Link to threejs demo of said technique](http://soledadpenades.com/articles/three-js-tutorials/object-picking)

I'm assuming that this technique will not work in this case due to the lack of both a spatial partitioning structute and  ray intersection math support, but I was wondering as to why this approach isn't being considered in the first place.

Thanks!

**Comment by rossant** [comment]
maybe because of perf reasons: games have "few" large objects whereas plots have *many* tiny objects

**Comment by bollu** [comment]
yes, I assumed so too. Supporting millions of point particles with this isn't really scalable.

**Comment by campagnola** [comment]
There's also a simplicity / consistency issue: by using the same system to do both drawing and picking, we can ensure for all visuals that the picked visual is exactly the one that is displayed on screen under the cursor. If picking were implemented in python instead, we would basically have to create a parallel OpenGL-like state machine to ensure that we correctly "guess" which visual is the one on top.

**Comment by campagnola** [comment]
Imagine, for example, a surface plot where the z-value is computed in the vertex shader, which intersects a grid made from 2 triangles where the grid lines are computed in the fragment shader. This situation would be a LOT of work to ray-cast in python.

**Comment by Eric89GXL** [comment]
yeah, I agree that it should be the most robust approach assuming you don't have more than 256*256*256 items you're picking amongs (reasonable enough for now anyway)

@bollu you want to take a look at @campagnola's example mentioned above, and poke around `glumpy` for the picking example to see what you can make of it?

**Comment by bollu** [comment]
@Eric89GXL will do :) I'll check it out and report back.

**Comment by campagnola** [comment]
..actually I think we can get 32-bit IDs by disabling alpha blending.

**Comment by rougier** [comment]
We can have any precision we want using color picking because we can query more than one attribute (see https://github.com/glumpy/glumpy/blob/master/examples/gloo-picking.py)

To answer @bollu question, we cannot use regular inverse transform because some of the transform we use are not invertible at all.

**Comment by bollu** [comment]
@rougier: whoa, interesting. which transforms in the pipeline are non-invertible? I'd never assumed that you'd even *get* non invertible transforms in rendering

**Comment by Eric89GXL** [comment]
@bollu maybe the very first step should be to port @rougier's example to `vispy` as a `gloo` example. That will help you understand the strategy, and put @campagnola's ideas about SceneGraph integration in context.

**Comment by rougier** [comment]
At least, some (future) cartography mapping won't be invertible.

**Comment by campagnola** [comment]
@bollu, FYI I am going to start working on (5) above  (TransformSystem / viewport).

**Comment by bollu** [comment]
@campagnola All right. I'm checking out the picking example :)

**Comment by campagnola** [comment]
@bollu, I am currently tearing up the SceneCanvas code and came across a method I had totally forgotten about: `SceneCanvas.render()`. This allows you to render any region of the scene to a framebuffer and returns the image array. I think this combined with a PickingFilter is all we need to get picking to work (and this could even be done from the current master branch).

**Comment by Eric89GXL** [comment]
ahh right, because you could just render the single logical pixel (could be multiple physical pixels) under the mouse. +1 for that, should hopefully be fairly simple!

**Comment by campagnola** [comment]
Ok, sorry for the toe-stepping, but I'm at the point right now where I can't move forward without picking, and it's just a few lines of code away now that all the supporting features are in place. Picking forthcoming..

**Comment by Eric89GXL** [comment]
cc @bollu looks like picking will be taken care of in this PR, sorry about that.

**Comment by Eric89GXL** [comment]
(it should be more straightforward to see how to proceed after this PR is in)

**Comment by bollu** [comment]
@Eric89GXL whoops, sorry I missed that. Looks like I disabled all of my notifications while I was cleaning things up :| Will bring this back on. sorry!

**Comment by Eric89GXL** [comment]
Closing since this appears to be complete now
