### ISSUE TITLE
"edge_color" parameter of "CubeVisual" and array_like input support.

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#900]
I'll describe first the context of this issue: In the long term I would like to provide [Colour](https://github.com/colour-science/colour) with alternative 3d plotting capabilities and be able to produce plots such as:

![image](https://cloud.githubusercontent.com/assets/99779/7582162/41dddc8a-f88b-11e4-9c56-4d6a2268639e.png)

The main reason for this is that [Matplotlib](http://matplotlib.org) is not really suited for heavy 3d plotting, there are massive z ordering issues and it is also quite slow.

Back to the issue itself, in order to have varying coloured wireframes I would like the `vispy.visuals.cube.CubeVisual` `edge_color` parameter to support array_like input. I have a [patch](https://github.com/colour-science/vispy/commit/8148e4c70b763cf5cba9f07e42bb7a8e32206fe0) to allow this behaviour in our [fork](https://github.com/colour-science/vispy/commit/8148e4c70b763cf5cba9f07e42bb7a8e32206fe0).

Given the following code...

```python
import sys

import numpy as np
from vispy import scene
from vispy.geometry import create_cube
from vispy.scene.visuals import Cube


canvas = scene.SceneCanvas(keys='interactive',
                           size=(800, 600),
                           show=True,
                           bgcolor=(0.5, 0.5, 0.5))

view = canvas.central_widget.add_view()

vertices, _, _ = create_cube()

RGB_f = np.copy(vertices['color'])
RGB_f[..., 3] *= 0.1
RGB_e = vertices['color']

cube1 = Cube(vertex_colors=RGB_f,
             edge_color=RGB_e,  # Relevant statement for the issue.
             parent=view.scene)
vertices = cube1.mesh_data.get_vertices()
vertices[..., 0] -= 1.5
cube1.mesh_data.set_vertices(vertices)

cube2 = Cube(vertex_colors=RGB_f,
             edge_color='k',  # Relevant statement for the issue.
             parent=view.scene)
vertices = cube2.mesh_data.get_vertices()
vertices[..., 0] += 1.5
cube2.mesh_data.set_vertices(vertices)

view.camera = 'turntable'
view.camera.fov = 45

if __name__ == '__main__' and sys.flags.interactive == 0:
    canvas.app.run()
```

... I can render this:

![image](https://cloud.githubusercontent.com/assets/99779/7582550/0ac5e3f6-f88f-11e4-830b-842a5ea454cb.png)

I can do a PR but I have some consistency concerns that will be important as more geometries may be implemented (grid, torus, sphere, etc...):

- With the new parameter capabilities `edge_color` may be renamed `edge_colors`. That would be consistent with the `faces_colors` and `vertex_colors` parameters and there would be:
    - face_colors
    - vertex_colors
    - edge_colors
    - color

- Alternatively a new `edge_colors` parameter can be introduced and the current `edge_color` one renamed to something like `outline_color` as a a result there would be:
    - face_colors
    - vertex_colors
    - edge_colors
    - color
    - outline_color

Notice that in the above `color` is not really explicit on what it is actually colouring.

- Another path would be to have some "intelligent" handling with the `face_colors` and `edge_colors` parameters, if single colour input is provided then all the faces / edges are set with it otherwise the array_like input is used assigning different colours to each faces / edges. I don't really know what are the implications of this one. Although as a result you can get rid of the `color` and `edge_color` parameters:
    - face_colors
    - vertex_colors
    - edge_colors

**Comment by campagnola** [comment]
In the most general case, we want to be able to specify:

* Solid face color
* 1 face color per face
* 1 face color per vertex
* 3 face colors per face
* 1 edge color per edge
* 1 edge color per vertex
* 2 edge colors per edge

I think this is already possible using the `Mesh` visual. Given that `Cube` is just a convenience class, it might make more sense to keep that API simple and use `Mesh` for more complex problems (in your case, you are already generating and discarding the vertex / face data anyway).

**Comment by KelSolaar** [comment]
I would actually like to extend the visuals and add some more primitives. I have just implemented a parametric plane and a parametric box based on it: 

https://gist.github.com/KelSolaar/73143fbbe23bb7301b0f

![image](https://cloud.githubusercontent.com/assets/99779/7592997/2dfb46b6-f8d7-11e4-8d0f-03531783d342.png)

I would be glad to contribute the code to Vispy but the issue I described above is a point that would need to be further investigated for that.

**Comment by Eric89GXL** [comment]
Which issue needs further investigation? The clipping issue you mentioned on `gitter`, or the issue about how to set colors / API changes?

**Comment by KelSolaar** [comment]
I was referring to the API changes one regarding to the `CubeVisual`, a thing I can do for now is contribute the `create_plane` and `create_box` definitions.

As for the clipping issue, what do you suggest? It should probably be handled in a separate issue / gitter directly?

**Comment by KelSolaar** [comment]
I created my own visuals with what I needed so I guess we can close the issue.

![image](https://cloud.githubusercontent.com/assets/99779/7621214/50114d42-f9c5-11e4-853f-7a40f4070665.png)

I'm still keen on knowing how to fix the clipping / transparency issues, it is really ugly at the moment.

**Comment by Eric89GXL** [comment]
Can you try to construct a minimal example, like maybe just using a cube and a SceneCanvas or Canvas? It will help isolate the problem to as few components/lines as possible. It might also be system dependent. We want to fix it either way, but reducing the code as much as possible should help us track it down more easily.

Also, if you think your new visuals will be useful to other people, we welcome a PR!

**Comment by KelSolaar** [comment]
Sure! I have opened a new issue for the transparency issues investigations: #902
