### ISSUE TITLE
Must have features for the v0.4 release 

### ISSUE THREAD

**Issue by jvtrudel** [vispy/vispy#903]
The next version of Vispy is waited by an increasing enthusiasts potential users. To catalyse the work yet to be done before this release, I propose to clarify what we consider mandatory feature for this release. It could allow us to concentrate our effort on these specific aspects.

  - What is the actual list of new features implemented?
  - Which feature do you think should be _absolutetly_ added?

(By feature, I also mean major bug fixes and important modifications of the code design. But I think everything on that side have been achieved during the last sprint. Am I wrong?)

When the _todoList-of-mandatoryFeatures_ is empty, just proceed to the release.

**Comment by Eric89GXL** [comment]
I'd like to see #829 (axes) in w/plotting updates, plus a fix for #878 since collections appear to be broken

**Comment by Eric89GXL** [comment]
ping @rossant @rougier @campagnola @almarklein WDYT?

**Comment by rougier** [comment]
We should make a release very soon, even with missing features just to let know people the project is alive. Then we can target a more proper release by end of summer.

**Comment by rossant** [comment]
+1. I'm about to release a production-ready software and vispy is the only dependency that needs to be installed from github, which feels wrong...

**Comment by Eric89GXL** [comment]
Ahh, fair enough. So fix just #878, then release. Okay with you @campagnola @almarklein?

**Comment by campagnola** [comment]
I'm fine with it.

**Comment by Eric89GXL** [comment]
@almarklein I think you did the last release... anything to do other than:

- create tag / use GitHub release
- push to PyPi
- email lists
- update zenodo ref

?

**Comment by almarklein** [comment]
@Eric89GXL maybe add announcement on website.

**Comment by QuLogic** [comment]
The 0.4 Milestone still contains some open tickets. They should probably be bumped to 0.5 if still relevant.

**Comment by Eric89GXL** [comment]
Indeed, there was a PR with a 0.4 milestone, thanks for the hint

**Comment by QuLogic** [comment]
Also missing a changelog in the docs here: http://api.vispy.org/en/latest/releasenotes.html

**Comment by jvtrudel** [comment]
Thanks @QuLogic for your comment, but this thread is closed. The version 0.4 is already published. Maybe I could open the same kind of issue for the next version?

**Comment by Eric89GXL** [comment]
Fixed the release notes @QuLogic thanks for the reminder
