### ISSUE TITLE
Implement support for visual visibility toggle.

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#905]
It would be great to have a `visible` attribute on the various visuals so that we can toggle their drawing at will without removing them from the scene graph (maybe skipping the `draw` call). I have seen a maye related attribute in the [`vispy.visuals.visual.Visual`](https://github.com/vispy/vispy/blob/master/vispy/visuals/visual.py#L36) class but it doesn't seem to be used.

**Comment by Eric89GXL** [comment]
+1 for `.visible` property that toggles drawing by just returning if it is `False`, okay with you @campagnola?

**Comment by campagnola** [comment]
Sounds good to me. The scenegraph should also handle this by skipping drawing the children of a hidden node.

**Comment by KelSolaar** [comment]
I have just found a `visible` attribute in the [vispy.scene.node.Node](https://github.com/vispy/vispy/blob/master/vispy/scene/node.py#L69) class that seems to be doing the job just fine: https://drive.google.com/file/d/0B_IQZQdc4Vy8YVBTdExYUVJMSUk/view?usp=sharing

I have some unrelated redrawing issues though when I toggle the `XYZAxisVisual`.

**Comment by Eric89GXL** [comment]
Ahh, so visibility can be toggled that way iff you're using scenegraph @KelSolaar? If so, can you think of a place we can improve the docs so that this will be clearer to users?

For the redrawing issue, can you check to see if it's due to the removal of that item, or if it's just due to causing a draw update (like add a keyboard command that just calls update and see if that also causes the issue)?

**Comment by KelSolaar** [comment]
Yes it does work and I'm using it in the screencast above. The attribute is actually documented in the section for the [vispy.scene.node.Node](http://api.vispy.org/en/latest/scene.html#module-vispy.scene.node).

I definitely didn't think about looking at the `vispy.scene.node.Node` class for that since it is specifically a display related attribute. The _looks like it does nothing_ `self._visible = True` statement in [vispy.visuals.visual.Visual](https://github.com/vispy/vispy/blob/master/vispy/visuals/visual.py#L36) class confused me. It is also not really obvious that this class gets mixed with `Node` when looking at the code since it inherits from `object`. Definitely worth a mention in the docstrings about that, especially for people spending more time in the codebase than the documentation.

It is probably a good idea to put a reminder in the [vispy.scene.visuals](http://api.vispy.org/en/latest/scene.html#module-vispy.scene.visuals) introductory paragraph. Something like this maybe:

> The classes in scene.visuals are visuals that may be added to a scenegraph using the methods and properties defined by vispy.scene.Node such as `visible`, `name`, `parents`, etc...

Now that being said, it would make more sense to me to have that attribute defined in the `vispy.visuals.visual.Visual` class.

Regarding the redraw artefacts, it looks like that if I toggle the `XYZAxis` visibility, my wireframe line width increases, it is quite obvious if you watch the video in 720p. I will try to re-create a minimum reproducing example later.

**Comment by campagnola** [comment]
Ah, there's a bug here--the documentation for the VisualNodes (http://vispy.readthedocs.org/en/latest/scene.html#module-vispy.scene.visuals) should have included the 'visible' property..

**Comment by Eric89GXL** [comment]
@KelSolaar it sounds like one of those two visuals is setting a line width `gl` property, when probably both should be doing it. That could cause the width changes you describe. Do you have time to take a stab at the doc changes, `gl` fixes, or both?

**Comment by campagnola** [comment]
> if I toggle the XYZAxis visibility, my wireframe line width increases, it is quite obvious if you watch the video in 720p. I will try to re-create a minimum reproducing example later.

I'll bet this is due to one visual setting `GL_LINE_WIDTH` and the other not..

**Comment by KelSolaar** [comment]
@Eric89GXL I'm quite tight on schedule here, I can certainly take a look at the documentation though. The `GL_LINE_WIDTH` property is another matter and I'm not comfortable enough with Vispy API nor OpenGL to do that quickly I think.

**Comment by Eric89GXL** [comment]
Okay @KelSolaar I'll take a look

**Comment by Eric89GXL** [comment]
@KelSolaar which visuals are you using where you see the line width change, `XYZAxis` and what else?

**Comment by KelSolaar** [comment]
I think it was the `LineVisual`, I don't have the issue anymore though as I changed quite a lot of stuff in my code. In order to mitigate the transparency issues, I'm adding the various visuals in a specific order and if I have to regenerate one, I un-parent them all from the scenegraph, regenerate the relevant visual and re-parent them all back, thus maintaining the order.

**Comment by Eric89GXL** [comment]
@KelSolaar and just to make sure I have a handle on the issue, the `.visible` property from `Node` actually works, right? Or does that need to be fixed, too?

**Comment by Eric89GXL** [comment]
Ignore that last question -- I see the answer above.

**Comment by Eric89GXL** [comment]
@KelSolaar I'm going to close this issue for now since the title and discussion is wrong... I think the LineWidth issue might be solved moving forward as we use collections, since I think those use AGG rendering for lines.

**Comment by Eric89GXL** [comment]
We can open a targeted issue later if/when someone hits the issue again
