### ISSUE TITLE
"bgcolor" parameter has no effect.

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#908]
I'm maybe overlooking something but I don't manage to have the `bgcolor` parameter to work in this example:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from vispy.scene import SceneCanvas
from vispy.app import run


class Canvas(SceneCanvas):
    def __init__(self):
        SceneCanvas.__init__(self, keys='interactive', bgcolor=(0.2, 0.2, 0.2))

        self._grid = self.central_widget.add_grid()

        self._view1 = self._grid.add_view(row=0, col=0)
        self._view1.border_color = 'red'
        self._view1.bgcolor = 'blue'

        self._view2 = self._grid.add_view(row=1, col=0, border_color='green',
                                          bgcolor='yellow')

        self.show()


if __name__ == '__main__':
    canvas = Canvas()
    run()
```

Passing `bgcolor='yellow'` here for example is fine: https://github.com/vispy/vispy/blob/master/examples/basics/scene/nested_viewbox.py#L115

**Comment by Eric89GXL** [comment]
Yep, it does look like the `bgcolor` parameter is not being utilized. @KelSolaar do you have time to track down where the problem is in the `scene` system? If not, I can probably have a look.

**Comment by KelSolaar** [comment]
I can probably take a quick look at it although as I'm in the middle of relocating I'm trying to focus on my codebase.

**Comment by Eric89GXL** [comment]
Don't sweat it, I'll take a look then

**Comment by Eric89GXL** [comment]
@campagnola how is background drawing supposed to work for `fragment` and `viewport` methods? Should each ViewBox just draw a quad before drawing the subscene?

**Comment by Eric89GXL** [comment]
`fbo` is broken on my system, too, BTW, so it seems that there is no reliable way to get backgound color for a ViewBox currently...

**Comment by campagnola** [comment]
Yes, the ViewBox needs to draw a quad.
