### ISSUE TITLE
Add support for "TurntableCamera" translate speed.

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#914]
I have some issues when using a `vispy.scene.cameras.TurntableCamera` with user defined distance.

In my application the camera is sometime set quite close of the origin and I suspect the combination of that distance and the large scene bounding box is enough to generate values in `vispy.scene.cameras.TurntableCamera._dist_to_trans` that predate correct traveling as you can see in this video: https://drive.google.com/file/d/0B_IQZQdc4Vy8S0dTNEd5Q1hLWE0/view?usp=sharing

For now I have created a new camera that inherits from `TurntableCamera` and overrides `_dist_to_trans` as follows:

``` python
    def _dist_to_trans(self, distance):
        translate = np.asarray(TurntableCamera._dist_to_trans(self, distance))
        translate *= self.__translate_speed

        return translate
```

**Comment by jdreaver** [comment]
I had a pull request (#714) that implemented a consistent panning speed for cameras, but the camera code changed so much before it was merged that it didn't work anymore. It worked like this: if you imagine a flat surface in front of the camera, as if there is a glass window in front of you, then panning the view is like grabbing a part of that window and moving yourself. That is, the point under your mouse when you start panning stays under your mouse. I kind of don't like the current panning system because it feels a little "slippery". What you have shown here is an extreme case.

In order to reimplement the PR, I would have to sit down and really understand the camera changes (the camera code is more complex so it could be more general). However, I do explain the concept inside the PR.

**Comment by KelSolaar** [comment]
That looked great and seems to be perfect in my context.

**Comment by Eric89GXL** [comment]
I don't see a problem with having some multiplicative parameter like you have @KelSolaar. @campagnola what did you and @almarklein have in mind for this sort of thing?

@jdreaver yeah we want picking, hopefully one day the "handle" thing will be possible. But for now we might have to go for a less ideal but more easily workable solution. It would be good if you could try to reimplement your changes in the new system at some point, but that will probably take some work.

**Comment by jdreaver** [comment]
> @jdreaver yeah we want picking, hopefully one day the "handle" thing will be possible. But for now we might have to go for a less ideal but more easily workable solution. It would be good if you could try to reimplement your changes in the new system at some point, but that will probably take some work.

Agreed. Simple is definitely best for now.

**Comment by almarklein** [comment]
I agree that the mouse should stay in the same spot. What's shown in the video is just wrong :)

**Comment by KelSolaar** [comment]
Should I do a PR with an attribute like in my first message?

**Comment by campagnola** [comment]
Probably best to wait until #928 is in before starting on this.

**Comment by Eric89GXL** [comment]
@jdreaver we are going to try to merge #928 very soon, will you have time to try to translate your camera changes using the new system? It should be fairly stable once that is merged.

If not, I can implement the simpler solution of just adding a native multiplicative factor for the `dist_to_trans` to solve @KelSolaar's case.

**Comment by jdreaver** [comment]
Cool! I am on vacation for the next few weeks, so I won't have time until
I'm back.

**Comment by Eric89GXL** [comment]
Okay, in the meantime I'll add a simple parameter to allow manual adjustment then. If you could come back to your PR whenever you get time, it would be very helpful.

**Comment by astrofrog** [comment]
@jdreaver @Eric89GXL - any updates on this? This would be very useful to me too!

**Comment by jdreaver** [comment]
I don't think anyone's worked on this :/ I never got around to figuring out the new camera code (well, I guess it isn't so new anymore haha).
