### ISSUE TITLE
Vispy plotting API design

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#918]
So, I've been thinking about Vispy's high level plotting API. I've looked around at similar libraries (both Python and non-python). And, I've come to my own conclusions about plotting API's. I maybe grossly wrong, but I thought I'd put this up for feedback

There seem to be three very popular ways to decompose a graphics API. I'll list al there below along with (my opinion of) the pros and the cons of each approach

### 1: Fluent API###

Libraries using this - [d3](http://d3js.org/)

From their own documentation, this is their mission statement:

           D3 is not a monolithic framework that seeks to provide every conceivable feature. Instead, D3 solves the crux of the problem:
           efficient manipulation of documents based on data
           
Their main idea is that of _selections_, where D3 lets you select elements as you need them and then fill them up with styles / properties.

To create new nodes, you collect some data, ```enter` the data, and then build up visualizations for these nodes.

I've used d3 before, and I really enjoyed using it. However, this does have its drawbacks. 

1. It's much more "low level" that a high level plotting API, since you're describing things in terms of arbitrary objects and not concrete interfaces

2. ```enter()``` / ```exit()``` can get confusing when you're trying to build up something that's pretty complex. Losing track of what you're manipulating in the first place makes it harder

3. The fluent style of API-chaining can read to either very readable code or very ugly messes. The problem that I've faced when learning d3 is that it's hard to figure out what the __intermediates__ are while you're writing code. Since there's no real "stop" to the API. it's hard to figure out what object is present at what step when you start out using it.

4. It's an unfamiliar API to those who haven't used it and people may take time to acclimatize

### 2: Matplotlib style API###

Libraries using this style of API - [matplotlib](http://matplotlib.org/), [seaborn](http://stanford.edu/~mwaskom/software/seaborn/index.html)

The library is very imperative in nature, consisting of an array of functions that let you plot different types of graphs. Take a look at [Seaborn's list of graphs](http://stanford.edu/~mwaskom/software/seaborn/api.html#api-ref). 

These types of API's contain a wealth of functions that let you draw different kinds of plots.

The perceived disadvantages that I see with this is the fact that they're not very composable in nature, so it leads to tons of functions that do slightly different things.

### 3: Grammar of Graphics style API###

Libraries using this - [Gadfly](https://github.com/dcjones/Gadfly.jl), [ggplot2](http://ggplot2.org/)

This style is inspired from the book [The grammar of graphics](http://www.amazon.com/The-Grammar-Graphics-Statistics-Computing/dp/0387245448). The book tries to setup a formal system to describe the problem subset of data visualization. 

the library would be of the style where there is only a single entry point called ```plot()```, a function to which one passes the __data__ and the __style__ separately. That way, the data is decoupled from the rendering scheme.

By constructing the style in different ways, you can plot the data differently. 

I'm drawn towards this approach, both from an API design standpoint and from a usability standpoint. There seems to be backing in the form of major libraries as well. If I had it my way, I would choose to implement this as the plotting API. But, well, I wanted feedback and thoughts on this since you guys have __real-world__ experience maintaining API's :)

**Comment by bollu** [comment]
@Eric89GXL @rossant

**Comment by rossant** [comment]
agreed with this perspective. I also prefer (3), or some combination of (2) and (3). (1) is good for highly reactive applications but maybe not plotting
have you looked at bokeh http://bokeh.pydata.org/en/latest/ ? it chose (3). The API is popular I think, and it should work fine with OpenGL
cc @almarklein who is working a bit on bokeh now

**Comment by Eric89GXL** [comment]
@bollu I will look at this more in a few hours, looks like a comprehensive rundown and I want to give it some thought. cc @campagnola as well

**Comment by campagnola** [comment]
The API we're going for right now is most like (2), but more composable by being based on the scenegraph API which gives much lower-level access to the individual components in the scene. I also like (3), though, so it would be interesting to see how / whether that style could be combined with what we have. 

@bollu, can you maybe give some examples that highlight the strengths and weaknesses of these? I imagine we can design our API with most of these in mind..

**Comment by rossant** [comment]
cc @jvtrudel too

**Comment by jdreaver** [comment]
In my applications, I always wrap plot widgets and items with my own view classes. Using this approach, I have created both Model-View-Presenter and Reactive GUIs for scientific and financial visualization. It is best to give the user something easy-to-use for quick scripts, but also powerful enough that they can extend and customize the system.

I am a huge fan of functional programming, but I think that plotting libraries should be object-oriented, at least at the lowest level. Oftentimes you can wrap the plotting libraries with something more functional Many applications have almost 100% custom visuals and override most of the defaults, which is straightforward to do in a well-designed OO system. For example, using pyqtgraph, I make custom PlotItems so I can control how they react to user input, how they look, and how they interact with the connections I make to other items in the scene.

I think that option 2 (the matplotlib-style API) has a great balance in this regard. You can use it for simple scripts, but you can also wrap it and extend it in something more reactive or functional.

Just my 2 cents :smile:

**Comment by campagnola** [comment]
> I am a huge fan of functional programming, but I think that plotting libraries should be object-oriented, at least at the lowest level.

I think that's exactly where we are headed. The quick-and-easy functional API basically just wraps the lower-level object-oriented API and returns scenegraph objects that can be further modified, recombined, etc. I recommend seeing how the current histogram and spectrogram classes are implemented for examples of this--we would love to hear feedback on this design.

**Comment by bollu** [comment]
@jdreaver:

isn't it also possible to wrap #3 just like one wraps #2?

if you were wrapping, say, a histogram, rather than using ```pylab.hist(data, ...)``` can't one just as well use ```plot(dataset("ggplot2", "diamonds"), x="Price", Geom.histogram)```

The first example is [from matplotlib](http://matplotlib.org/examples/pylab_examples/histogram_demo_extended.html), while the second example is [from Gadfly](http://dcjones.github.io/Gadfly.jl/geom_histogram.html)

I understand what you're saying, but I don't  see how it automatically biases option 2 versus 3.

In my mind, both API's are "equivalent" in the sense that one can perform the same actions with roughly the same number of calls, but the grammar of graphics style seems to "feel" cleaner (i.e, more organized).

It might just be my own bias leaking through :) And yeah, these are just my opinions.

**Comment by campagnola** [comment]
@siddarth, I am not so familiar with either of these APIs. Can you give examples of how you would, for example, change the number of bins in the histograms after they have been displayed?

**Comment by jdreaver** [comment]
@bollu: I'm sorry, I didn't mean to say we shouldn't choose 1 or 3. I was just expressing why I liked option 2. I should have made that clearer. Your points are very valid. However, I think the histogram example in Gadfly only looks so nice because they use a builtin dataset, while matplotlib creates each histogram. In fact, I like the matplotlib example more because it shows a wide variation of histograms and shows how to customize them.

I was just extolling the *pros* of option 2. I think that option 2 should be the lowest level, and maybe we wrap it with `vispy.react` or `vispy.functional` (with better name of course :smile:). In this way, new users can have an awesome API to interact with, but experienced users can change the behavior however they like. @campagnola explained my position exactly.

I too think that pitting examples of each API against one another would make it easier to decide. It's hard to discuss APIs in the abstract haha.

**Comment by bollu** [comment]
@campagnola Sure, I'll create two iPython notebooks, one with Julia and one with python to compare and contrast. Does that sound fair? If you could give me a list of visualizations that you'd be interested in looking at, that would be of help

@jdreaver, @campagnola your criticism stating that the Gadfly example doesn't let you modify is valid. However, that's more the limitation of the library than the design of the API itself.

@jdreaver I also _completely_ agree that a lower level matplotlib style API can be comfortably wrapped into an immutable, functional style or a d3-like style. 

Also, when I gave the two links, I was focusing more on the single line of the plot creation than the data creation :) 

And, @campagnola to answer your (very specific) question about the number of bins:

to change that, you pas ```bincount``` as an argument to the ```Geom.histogram``` constructor like so:

```
plot(data,  x="axis name",Geom.histogram(bincount=30))
```
So there's no further modification of state.

**Comment by campagnola** [comment]
@bollu, I don't have any particular visualizations in mind, I am just hoping to get a clear picture of what the benefits and drawbacks are to each API style. Anything that can be done easily and naturally in one API but is awkward, verbose, or impossible under another API.

**Comment by campagnola** [comment]
(Ultimately we will probably stick to the API style as it is currently laid out, but I hope we can make sure that we have a natural approach to each of these examples.)

**Comment by bollu** [comment]
@campagnola very well. I'll try and come up with some motivating examples tonight :)

**Comment by Eric89GXL** [comment]
I prefer (2) mostly because I think it ends up being simplest for users. It's already where we're headed a bit with `vispy.plot`

**Comment by bollu** [comment]
@campagnola 

I tried to show how a simple histogram plot leads to two different API styles. 

[matplotlib](http://nbviewer.ipython.org/gist/bollu/2911661be16aec5b0f9b)
[gadfly](http://nbviewer.ipython.org/gist/bollu/c57d201a824cb08a5453)

I hope that the example motivates the main goal of the API.

Plotly also use a similar API design. [Here is their webpage on drawing Histograms](https://plot.ly/julia/histograms/)

**Comment by jvtrudel** [comment]
Very interesting reflexion here guys! I'll have a closer look at your comments and I'll contribute with my own views of the vispy's API**s** as soon as I have 2 minutes to write it down. 

I plan discuss about: 
  - Who will be the typical user of vispy and what do we have/want to offer to him
  - General purpose API vs specialized APIs (and the opportunity/interest to develop both)
  - Use cases and workflows for the generation of high quality images with vispy
  - How to take advantage of the interactivity features of vispy

**Comment by bollu** [comment]
@jvtrudel any updates?

@campagnola Do we have a consensus of some sort about what kind to use?

**Comment by jvtrudel** [comment]
Yes, but... I do not want to say stupid things so I am actually thinking. In the mean while, I found an interesting reflexion I posted on google group (march 30):


I would like to share with developers of vispy and with potential users some thoughts about the APIs design. This reflexion may seem very abstract and its probably true. But I think, as Vispy is heading to a mature state, that such a reflexion could stimulate the development of the code and facilitate its appropriation by a large community of users.

Focusing my attention on the strength of Vispy (good compromise between efficiency of the implementation and expressivity of the language, 3D rendering, big data, interactivity), I will try to imagine how we could transform the potential of this project into reality in a not-too-far future.  


## Focus on scientific concepts, not on data: "stupid but specialized users"

Vispy is specialized in (3D) scientific data visualization.

  - Most of potential users don't have any or have low programmation skills
  - Most of potential users are not interested in or do not have time to learn programmation
  - Most of end-users need to manipulate data
  - Most of end-users need to manipulate data now!
  - Most of end-users have a specialized knowledge of their topic and can easily manipulate the underlying concepts.
  - A mapping between the scientific concepts and their mathematical representation exist.
  - Most of the existing good visualization libraries do not offer specialized tools in a language bonded to the scientific concepts.
  - Many of the specialized scientific visualisation tools are bad.
  
Conclusion: there is an opportunity. 

The robust, efficient and flexible implementation of the lower level layers can support various use cases. The expressivity of python, it's ease of development and its interoperability friendliness are obvious advatages to develop a variety of tools on top of vispy.

## Many APIs to support many scientific communities with specific but limited needs

   - The plot module should be seen as a general purpose api. 
   - General purpose api offers no advantage compared to other existing platforms as matplotlib.
   - The plot module should be focused on the different mathematical representation of data. R^1 -> R^1 (2D), R^2 -> R (3D), R^3 -> R (volumesRendering) ... and many others.
   - Input format for each case should be standardise, well documented and extendable (through internal conversion with specialized wrappers).
   - For each range/domain possibility, there exists a maybe exhaustive, but finite number of possible graphical representations.
   - Users should be able to pass or datasets or analytical functions (in the sympy sense). 
   - Style (colors, textures, etc.) should be prepared separately or predefined.
   - Styles should be exportable and loadable.
   - Compositions of scenes containing many datasets should be prepared separately or predefined according to specific community conventions.
   

Implications of this idea:
  - we could focus on a not-too-far future the development toward users' needs.
  - When a feature is requested and then we decide to implement it, we first have to specify the problem mathematically.
  - Graphical representations should be extended when users ask for it. 
  - These general tools could be used to construct specialized representation of data to different scientific community. 
  - The saving/loading of styles and scene composition would facilitate the adoption of vispy by a wide audience of non-programmers supported by a small number of specialists with medium programmation skill. 

Having the specialized api within or outside vispy may be debatable. I prefer within vispy as long as no specialized dependencies are needed.


## Ideas for the organisation of examples and tutorials

After the development of the basic tools, example and tutorials should be a priority to help new developers and users to learn vispy.

  - Examples should be gathered by targeted audience, not by topic
    - Core developers: individual components and low level 
    - API developers: Scene, widgets and other higher level components
    - General use of vispy: Plot module, standard data format, mathematical/graphical representations 
    - End-users: specialized API
  - Tutorial of higher level layers (General and specialied API) should be written to stimulate the development of new APIs by third party developers
  - Realistic example from different field should be written to illustrate the capabilities of vispy (I'm working on it...)

I hope these ideas could be useful. What do you think? How do you see the future of vispy and data visualization?

**Comment by bollu** [comment]
@jvtrudel but, well, taking your R^1 -> R example, there are multiple ways to plot that too, isn't there, depending on you data? If its f(theta) = r, then your plot would be polar. if it's y = f(x), then you may want a line. Or, you may want a histogram of your data to bucket it. So, again, it's a question of data v/s representation

**Comment by jvtrudel** [comment]
Yes @bollu . Its true. First, I would identify  all the mathematical cases that can generate a valid "graph" or plot. Then, as you mentioned, there may be different way to visualize it. These possibilities could also be systematically identified and implement independently.

Heres an example of use cases that could be build with that approach:

**input data and visualise it**

    plt=plot()
    plt.addDataSet(userData1)
    plt.addDataSet(userData2)
    plt.show(method="line")
    plt.show(method="histogram")

Or you could do the same thing in fewer lines if you want to:

    plt=plot(dataSets={userData1,userData2})
    plt.show(method="line")
    plt.show(method="histogram")

Or if you have a _regular_ dataset with the same number of points:    

    plt=plot(dataCoordinates=X, dataValues={Y1,Y2})
    plt.show(method="line")
    plt.show(method="histogram")

**Comment by jvtrudel** [comment]
Standardisation of the data structure + vispy's ability to recognize it would be extremely powerful (in my opinion). 

  - It could allow the user to simply feed vispy with his data.
  - Pretreatment of the data (generating meshes, data interpolation, projection on bezier functions or splines, etc...) could be done automatically.
  - Pretreatment of the data could be specified by the user if needed by selecting the pretreatment method and some (comprehensive) quality or accuracy goals .
  - User could do the same with the style/rendering and post-treatment.
  - Saving/export of the treated data and of the styling parameters should be possible for further use, for batch treatment or to disentangle exploration of the data and final realization of high quality images.

## Example workflow

Feed vispy with your data and visualize it.

    plt.plot(dataSets={userData1,userData2},showMethod="curve")
    plt.show()

After inspection, you think you should interpolate your first dataset to have a better image?

    plt.interpolate(dataSet=1,qualityGoal="medium", method="anotherMethodThanTheDefault")
    plt.show()   

You think it would be better to project this result on bezier curve and save it?

    plt.fit(dataSet=All, method=bezier)
    plt.dataExport("myPostTreatedData.hdf5")
    
Then, it would be nice to configure the style's parameters?

    plt.style(lineColor={"blue","cramoisie"},
                  backgroundColor="yellow",
                  imageSize=800, AspectRatio=scipy.constants.golden,
                  xLabel="time (s)", yLabel="distance (m)",
                  axesLabelFont="Helvetica", ticksFont="Arial",
                  title="Mesured vs estimated trajectories. $Acceleration = \frac{distance}{time^2}$",
                  titleFont="Times New Roman",titleSize="huge", titlePosition="frame northEast")
    plt.show()

Save your style parameters:

   plt.styleExport("iGotaNiceStyle.json")


All this could be done interactively through a simple interface (image + console).

**Comment by Eric89GXL** [comment]
I see how this type of interaction could be very useful. Personally I still
prefer the mpl-type plotting calls. There is a simplicity and transparency
to them (less magic) that appeals to me. I think the mpl style is likely to
lead to fairly simple code, and potentially easier from an implementation
and piecewise progress perspective.

In any case, we currently have mpl style calls in vispy.plot, so I think
the best course of action is to expand that and make it work better. We can
always add this type of data abstraction later on top of or in parallel to
the mpl one. I think our primary goal should be ensuring reasonable
usability of the package for scientific plotting as soon as possible. I
think the mpl style will get us there with the least difficulty while
covering 90% of what users would like to be able to do. My 2c...

**Comment by jdreaver** [comment]
I agree with @Eric89GXL. I think that @jvtrudel's proposal is very interesting, but an mpl-style API is both easy to use *and* easy to implement.

**Comment by jvtrudel** [comment]
I also agree with @Eric89GXL and @jdreaver. Mpl-style is easier and refinement could be done later. What does it take to adapt vispy.plot to mpl-like api? Which new features do we need? How to implement it?

**Comment by Eric89GXL** [comment]
Getting AxisVisual (#980) and improving performance (#928) / integrating collections would be the top two priorities to me. Then it would be integrating the AxisVisual with the PlotWidget, integrating the ColorbarVisual (#979) with the PlotWidget, then expanding the set of visuals and/or expanding the `vispy.plot` module.

**Comment by Eric89GXL** [comment]
Closing as resolved for now

**Comment by datnamer** [comment]
Just an FYI, bokeh seems to be moving in an interesting ggplot type direction with their api: https://github.com/bokeh/bokeh/wiki/Bokeh-Days-Working-Document 

Any chance of integration?
