### ISSUE TITLE
'Isoline' object has no attribute 'set_levels', in "isocurve_for_trisurface_qt.py" example

### ISSUE THREAD

**Issue by stonebig** [vispy/vispy#921]
trying isocurve_for_trisurface_qt.py example on windows/PyQt4/vispy0.4, it seems there is a basic compile error

````
Traceback (most recent call last):
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\Scripts\isocurve_for_trisurface_qt.py", line 127, in <module>
    win = MainWindow()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\Scripts\isocurve_for_trisurface_qt.py", line 88, in __init__
    self.update_view()
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\Scripts\isocurve_for_trisurface_qt.py", line 93, in update_view
    self.props.combo.currentText())
  File "D:\result_tests\winpython-3.4.3.3\python-3.4.3\Scripts\isocurve_for_trisurface_qt.py", line 121, in set_data
    self.iso.set_levels(cl)
AttributeError: 'Isoline' object has no attribute 'set_levels'
````

**Comment by Eric89GXL** [comment]
Indeed, looks like that example was never updated. Can you try changing it to `self.iso.level = cl` and see if that works? If it does, can you open a PR to fix it?

**Comment by stonebig** [comment]
Unfortunately, I have a lot of error in my windows/python3.4 spyder console when I try all these tests, so I can't check it works "well" at the end. 

Please do.

**Comment by stonebig** [comment]
ah, replaying this example in AMD hd5650 mode and the above fix, I get :
- zero message in the console,
- 3 bars referencial in the middle of the sphere, that I don't have when under intel graphics.

In intel and AMD case, buttons are now functional.

Would it mean that the problem is in the drawing of these little 3 bars ?
![isocurve_intel_graphics](https://cloud.githubusercontent.com/assets/4312421/7787882/43c2df2c-0223-11e5-988e-e79c7e6f1388.GIF)
![isocurve_amd_graphics](https://cloud.githubusercontent.com/assets/4312421/7787886/512c61ce-0223-11e5-8d29-907ad1d7e93c.GIF)

**Comment by stonebig** [comment]
seems something like that: http://stackoverflow.com/questions/14558256/unable-to-find-an-entry-point-named-glbindframebuffer-in-dll-opengl32-dll-i

**Comment by campagnola** [comment]
We generally try to keep everything GL2.1 compatible (while still allowing features from GL3+ to be used). If this really is a GL version issue, then at least we should issue a more helpful warning.

**Comment by Eric89GXL** [comment]
@campagnola I thought we were going for OpenGL ES2.0 and above, which does contain glBindFramebuffer. I don't know if GL 2.1 is going to work since framebuffers can't be used there.

In any case, I think we can close this as a dup of #669 since that's open as an issue to deal with reporting and triaging GL version capabilities.
