### ISSUE TITLE
Add a way to retrieve the current "SceneCanvas" instance from the "SceneGraph".

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#927]
It is maybe implemented but I didn't find it, I need a way to find the current `SceneCanvas` instance a `SceneGraph` node, specifically a `ViewBox`, at the moment I'm passing the current `SceneCanvas` instance to my views which is not particularly elegant. I tried to walkup the graph, there is a node named **canvas_cs** up there but I didn't see which attribute links it to the `SceneCanvas` instance, I'm not even sure it is related.

**Comment by campagnola** [comment]
This is already fixed in #928.

**Comment by KelSolaar** [comment]
Ah great news!
