### ISSUE TITLE
Importing gloo should not automatically load the OpenGL library

### ISSUE THREAD

**Issue by rossant** [vispy/vispy#929]
I'm trying to run vispy on a headless server with docker, to use the ipynb webgl backend exclusively. I cannot `import vispy.gloo`:

```
  File "/opt/conda/lib/python3.4/site-packages/vispy/gloo/__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "/opt/conda/lib/python3.4/site-packages/vispy/gloo/gl/__init__.py", line 213, in <module>
    from . import gl2 as default_backend  # noqa
  File "/opt/conda/lib/python3.4/site-packages/vispy/gloo/gl/gl2.py", line 46, in <module>
    raise RuntimeError('Could not load OpenGL library.')
RuntimeError: Could not load OpenGL library.
```

I should not need to have the OpenGL library on a headless server when using a remote backend.

**Comment by Eric89GXL** [comment]
I think it should be fine to not have this happen. It will probably mean nesting some `from . import gl` calls. Do you have time to fix it?

**Comment by rossant** [comment]
Not sure i'll have time in the near future.. for now i just install the libs and it works, but it would be nice to have it fixed eventually!
