### ISSUE TITLE
vispy.test() is broken for pip-installed vispy

### ISSUE THREAD

**Issue by QuLogic** [vispy/vispy#935]
The tarball on PyPI does not include documentation, examples, or the `make` directory. The readme does not indicate any other way of running tests, so I have no way of verifying that my installation is correct (besides running random scripts).

**Comment by jdreaver** [comment]
I was under the impression that PyPI packages should be minimal so they don't take up more space than they need.

**Comment by Eric89GXL** [comment]
@jdreaver indeed. AFAIK this is consistent with what other packages (numpy, scipy, scikit-learn, etc.) do to keep download sizes small.

You should be able to do:
```Python
>>> import vispy
>>> vispy.test()
```
But it's currently broken. I'll change the title here as a reminder to fix it, and update the README to tell people they can run it.

**Comment by QuLogic** [comment]
For sure, leaving out documentation is understandable; I just mentioned it in case it was unintentional.

But it would definitely be good to have those tests working (even if just minimal).

**Comment by QuLogic** [comment]
I tried out `vispy.test()`, and I see this error:
```
Running tests with pyqt4 backend:
_VISPY_TESTING_APP=pyqt4 -m vispy_app_test  --cov vispy --no-cov-on-fail 
usage: -c [options] [file_or_dir] [file_or_dir] [...]
-c: error: unrecognized arguments: --cov --no-cov-on-fail
Failed: unit failure (2)
```
Now, it's obvious that I need `pytest-cov`, but I don't think it should be a requirement anywhere other than Travis (if that's possible.)

**Comment by Eric89GXL** [comment]
Yeah, even with `pytest-cov` installed I get an error that needs to be fixed :) But yes, I agree that shouldn't be required.

**Comment by QuLogic** [comment]
If I comment out the coverage stuff, then I get three errors in `vispy/gloo/gl/tests/test_functionality.py` (for both `pyqt4` and `pyglet` backends), other Qt backends do not run because the first one is loaded, the `nobackend` test seems to load extra tests from _other_ packages, and the remaining backends are skipped because I don't have the dependencies.
