### ISSUE TITLE
In isocurve exemple the contour line disappear

### ISSUE THREAD

**Issue by sylm21** [vispy/vispy#941]
I'm on windows 7, when i  try isocurve example the image appear but the isoline appeant only a small moment ...

**Comment by sylm21** [comment]
A solution more translate the image but why ?

image.transform = visuals.transforms.STTransform(translate=(0, 0, 4.0))

**Comment by Eric89GXL** [comment]
It disappears for you? The image stays just fine on my system. I wonder if this is related to other issues we've had with setting GL state.

**Comment by kmuehlbauer** [comment]
Closing as outdated. Reopen when problem persists.
