### ISSUE TITLE
Must have features for the v0.5 release

### ISSUE THREAD

**Issue by jvtrudel** [vispy/vispy#951]
I propose this issue to brainstorm about the next release. Deciding as early as possible the improvements to include in v0.5 will catalyse our work and accelerate the availability of vispy for non-developers.

**Comment by jvtrudel** [comment]
I my opinion we should work  in parallel on both the core/foundation of vispy (goo, glir, collections, visuals, etc...) and on end-user oriented features (axis, text, styling, ...). But in v0.5, priority should be given to end-user oriented features.

  - Few _minor_ improvements like axis and text (including latex-like) could make a big difference and vispy could be used for serious and professional scientific plotting (which I think is our main goal).
  - We are not ready to deploy vispy to a large audience, but having a small community of users that produce high quality _products_ with vispy is a must.
  - We should use the growing community of user to identify the features essential to them. Then it will be easier to think about the relation with the lower level layers of vispy.
  - Its not clear yet for me what the development status, pros/cons and interrelations of _high level_ components as sceneGraph, plot api, all the widgets, etc... 
  - We started a reflexion on API and developing all the tools for it is essential to implement it. Whatever the API model we choose we will need axis, labels, insets and other styling features... 

But (as you probably already noticed), the top priority in my opinion is the capability of **drawing axis** and **writing text and equations**. I don't want to be unkind, but we cannot pretend to do scientific visualization without these two features.

**Comment by Eric89GXL** [comment]
I agree with most of this -- I think the process will need to be:

1. get some basic axis visual working (in progress #829)

2. integrate axis visuals into `vispy.plot`

3. speed up scenegraph and integrate collections (in progress #928)

I'm not sure the extent to which equations can be supported. If you mean using generic text I think it can, if you mean via `LaTeX` it would probably take someone very devoted to it to get it working.

**Comment by Eric89GXL** [comment]
Closing, I don't think (3) will make it fully but 1 and 2 did

**Comment by bollu** [comment]
@Eric89GXL - which part of (3) didn't happen?

**Comment by Eric89GXL** [comment]
Collections exist, but aren't part of the `scene` system yet. They need to be converted to have the right hooks, and a nice public interface, etc.

**Comment by bollu** [comment]
oh, I see. That'd be interesting to take up. Any pointers on where I can begin?

**Comment by Eric89GXL** [comment]
Search the issues for `scene` and `collections`, hopefully you find some pointers. I'd tackle it by running the `collections` examples, find the simplest one, and try turning it/them into `scene` visuals little by little.

**Comment by bollu** [comment]
Cool, I'll start doing that next week or so in that case :)
