### ISSUE TITLE
Drawing Precision Issues with 3D Cameras

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#953]
I have important drawing precision issues with the 3D cameras that I pinpointed to be coming from the `BaseCamera._get_depth_value ` private method: https://github.com/vispy/vispy/blob/master/vispy/scene/cameras/cameras.py#L128

Oddly the doc string specifies that:

```
For 24 bits and more, we're fine with 100.000,
```

but the value returned is **100000.0**, putting that back to **100** or even **1** fixes the issues.

**Comment by Eric89GXL** [comment]
@almarklein `git blame` says this one is yours. Any thoughts on this one?

**Comment by campagnola** [comment]
I think "100.000" is a typo (bizarrely, the world has not agreed on the meaning of "." vs ",").
GL has a fixed amount of precision in the depth buffer, and in general we cannot predict whether the user will need a very large range or very high precision. All we need here is a way for the user to override these constraints..

**Comment by Eric89GXL** [comment]
@KelSolaar would exposing a public attribute for the scale factor work for your use case? If so, feel free to open a PR to do it or I can fix it in the next couple of days.

**Comment by KelSolaar** [comment]
Yeah I think it should work, I'm not sure what represents that attribute exactly but usually in DCC apps such as Maya, Softimage, 3dsmax, etc... you set the camera near and far clipping planes in order to maximise the drawing precision.

**Comment by Eric89GXL** [comment]
@campagnola should we wait until #928 is merged to add the property, or not? I don't want to create a rebase nightmare for you, but if #928 is going to take a bit longer still it would be good to get this fix in sooner so @KelSolaar can fix his use case.

**Comment by campagnola** [comment]
All changes to the camera system will have to be merged manually (by me) so it's probably best to hold off.

**Comment by KelSolaar** [comment]
There is really no hurry on my side guys, so I can definitely wait :)

**Comment by almarklein** [comment]
> I think "100.000" is a typo

Oh, yes, it probably is, because that means 100,000 in Dutch, and I would not write three zeros after a decimal separator.
