### ISSUE TITLE
mpl_plot example no longer works

### ISSUE THREAD

**Issue by QuLogic** [vispy/vispy#962]
This example currently shows the background and axes, but nothing within.
![screenshot from 2015-06-02 23-12-15](https://cloud.githubusercontent.com/assets/302469/7952015/e9301e06-097c-11e5-9a8b-acc3f6a40a44.png)

**Comment by Eric89GXL** [comment]
If you aren't sick of debugging and contributing to `vispy`, you can use [git bisect] (http://webchick.net/node/99) to figure out whose fault it is :) Otherwise I can try to get to it in the next few days.

**Comment by QuLogic** [comment]
```
a3da64aff000a857c94cc5e93fd83bdb8a24a9c2 is the first bad commit
commit a3da64aff000a857c94cc5e93fd83bdb8a24a9c2
Author: Eric Larson <larson.eric.d@gmail.com>
Date:   Tue May 19 14:17:09 2015 -0700

    FIX: Fix background colors

:040000 040000 6f29bdb23d600a8aa29cee399b7f6a5a73133b30 626fe043168886ed882b07614db468b60f21311d M	examples
:040000 040000 edc6f6888b53f0cdaf862bcba5edcb347b53fd08 02e8b446164ede9c232fa4910fe7d04591bc2322 M	vispy
```

**Comment by Eric89GXL** [comment]
Oh great :) That was a commit that should have fixed how ViewBox backgrounds got drawn. Somehow it must be getting drawn out of order. I'll try to look soon.
