### ISSUE TITLE
Keyboard interactivity for fly camera disabled until view changed

### ISSUE THREAD

**Issue by larsoner** [vispy/vispy#963]
Procedure to reproduce:
1. run examples/basics/scene/volume.py
2. change to fly camera (press "1" twice)
3. use arrow keys -- no response
4. adjust view in any way with mouse
5. use arrow keys -- camera moves

Thanks @QuLogic for the report.

@almarklein any ideas?

**Comment by Eric89GXL** [comment]
Does this have to do with setting which viewbox receives events? In other words, by clicking in the window, you're clicking in the viewbox and thus setting it to be the target of future keypresses? If so, it might make sense to have the first viewbox added to a SceneCanvas be assumed to be the target of keypresses.

**Comment by almarklein** [comment]
Not sure, I *think*  there is no delivery to a viewbox; we simply catch key events at the canvas.

**Comment by djhoese** [comment]
This no longer seems to be an issue. If someone comes up with this, please open a new issue.
