### ISSUE TITLE
Improve transforms.py

### ISSUE THREAD

**Issue by almarklein** [vispy/vispy#97]
See discussion https://github.com/vispy/vispy/commit/76a4e924de4ece56658eb24f8d1d3a1636a8274d

The transforms now do the operation in-place *and* return the result. Better would be to avoid in-place operations and return a new matrix.

Also see http://glm.g-truc.net/0.9.5/index.html

**Comment by almarklein** [comment]
In #505 a start was made, but this has stalled. Anyone wants to wrap this up?

**Comment by Eric89GXL** [comment]
I can get this tomorrow
