### ISSUE TITLE
Test failure in test_font_glyph (possible race condition)

### ISSUE THREAD

**Issue by nippoo** [vispy/vispy#970]
Intermittently, I get:

```
====================================================== FAILURES ======================================================
__________________________________________________ test_font_glyph ___________________________________________________

    def test_font_glyph():
        """Test loading glyphs"""
        # try both a vispy and system font
        sys_fonts = set(list_fonts()) - set(_vispy_fonts)
        assert_true(len(sys_fonts) > 0)
        for face in ('OpenSans', list(sys_fonts)[0]):
            font_dict = dict(face=face, size=12, bold=False, italic=False)
            glyphs_dict = dict()
            chars = 'foobar^C&#'
            if face != 'OpenSans' and os.getenv('APPVEYOR', '').lower() == 'true':
                continue  # strange system font failure
            if 'true' in os.getenv('TRAVIS', '') and sys.version[0] == '3':
                continue  # as of April 2015 strange FontConfig error on Travis
            for char in chars:
                # Warning that Arial might not exist
>               _load_glyph(font_dict, char, glyphs_dict)

vispy/util/fonts/tests/test_font.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vispy/util/fonts/_freetype.py:48: in _load_glyph
    face.set_char_size(f['size'] * 64)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <vispy.ext.freetype.Face object at 0x2af9dc656208>, width = 768, height = 0, hres = 72, vres = 72

    def set_char_size(self, width=0, height=0, hres=72, vres=72):
        error = FT_Set_Char_Size(self._FT_Face, width, height, hres, vres)
        if error:
>           raise RuntimeError('Could not set size: %s' % hex(error))
E           RuntimeError: Could not set size: 0x17

vispy/ext/freetype.py:397: RuntimeError
```

Automating this test 10,000 times passes each time but running it manually (or via the test suite) seems to fail occasionally with the same error - I've repeated it twice.

Ubuntu 14.04 LTS, AwesomeWM (tiling window manager), NVidia GTX 980, Anaconda Python 3.4.

**Comment by Eric89GXL** [comment]
I have seen this one before, can't remember when or why... let me see if I can find a record somewhere

**Comment by Eric89GXL** [comment]
Oh yeah, at one point for some reason we had a problem with this on Travis, and only on Travis. Looks like now you're actually hitting the error. What makes you think it's a race condition?

**Comment by Eric89GXL** [comment]
...and actually I think this conditional above was put in to make it "go away":
```
            if 'true' in os.getenv('TRAVIS', '') and sys.version[0] == '3':
                continue  # as of April 2015 strange FontConfig error on Travis
```

**Comment by Eric89GXL** [comment]
Maybe some hint [here] (https://bugzilla.mozilla.org/show_bug.cgi?id=312105) regarding "HAVE_FT_BITMAP_SIZE_Y_PPEM"?

**Comment by Eric89GXL** [comment]
And/or we might have to check to see if fonts are scaleable:

http://sourceforge.net/p/ftgl/mailman/message/24463642/

Maybe on Py3k the list of system fonts is in a different order and we're accidentally hitting a font that is not scalable...?

I might be able to test this a bit locally by modifying the test to go through *all* system fonts.

**Comment by nippoo** [comment]
I'm only guessing, because it only happens a small fraction of the time (there isn't any randomness in the test, either), and crucially doesn't happen when the test is run thousands of times sequentially. So it makes me think that there might be some race condition with OS font loading (of some sort)...

**Comment by nippoo** [comment]
Ahaaaa.

A bit of debugging shows that `list(sys_fonts)` seems to return in a random order each time.

I've changed the test locally to test all system fonts. (Generally speaking I reallllllly hate non-deterministic tests. We should always test the same font, or a particular subset of fonts, or have an "extended" test for all fonts, but a test shouldn't fail a small fraction of the time or `git bisect` etc are useless!)

FWIW the full set of fonts passed in 0.27 seconds, so I'd vote strongly for testing every font, every time.

Fonts that fail for me:

```

**Comment by Eric89GXL** [comment]
That is a terrible idea... #971

**Comment by nippoo** [comment]
What's a terrible idea?

**Comment by Eric89GXL** [comment]
I was joking -- that PR I just opened does exactly what you suggest :)

Yeah, I bet those fonts don't scale. So we need to beef up our font enumeration and loading to only allow fonts that are scalable.

**Comment by nippoo** [comment]
Ahhh, I figured! Sorry, we don't get sarcasm very well over this side of the pond ;)
