### ISSUE TITLE
Add tests that ensure visuals avoid unnecessary shader modification

### ISSUE THREAD

**Issue by campagnola** [vispy/vispy#973]
There is a lot of sloppy coding in the visuals where we request modifications to the shader programs, causing unnecessary (and expensive) recompiles. These are easy errors to make, so we need a basic set of tests that ensure there are no unnecessary recompiles for:
- Most calls to `visual.set_data(...)`
- Trivial transform updates (those that should only require new uniforms to be uploaded)
- Other property changes (colors, line weights, etc)

**Comment by almarklein** [comment]
+100

**Comment by queenish001** [comment]
@campagnola Was this issue resolved?

**Comment by djhoese** [comment]
I'm pretty sure most of these issues have been resolved over the years.
