### ISSUE TITLE
ImageVisual: set_data function cause modification of shader program

### ISSUE THREAD

**Issue by kmuehlbauer** [vispy/vispy#974]
When using set_data function to load new data to ImageVisual a big amount of time is consumed recreating Texture2D.

See also this thread in vispy forum: https://groups.google.com/forum/#!topic/vispy/N0KpxZO5ay0 covering the problem.

**Comment by kmuehlbauer** [comment]
I've just had a look into #928 regarding the when and why a texture update is needed (image visual).

In my application I set the colorlimits `clim` only once. Then I use `set_data` function to feed new texture data. To speed up things a bit, I also have the colortransform part in a dedicated function, which is called only when `cmap` or `clim` is set to new values. 

There are other things I'm wondering, but this may be due to less knowledge of openGL on my side:

Can the data normalization, which is currently done in python, be done in the shader?
Why do we need the vertex update when setting `clim`? 
There is the `clim`-check (tuple/string) already in the clim-setter, is it necessary to have it in _build_texture again?

Thanks for shedding some light...

**Comment by Eric89GXL** [comment]
I think that eventually it would be good to have the scaling done on the GPU, we are limited by the data type and limits of the texture. We try to maintain OpenGL ES2.0 support, which means restricting the set of usable data types and functions. I'm not sure if we can do the clim setting on the GPU. @rougier do you have ideas?

**Comment by campagnola** [comment]
You are correct that the logic for deciding what should be updated is not good -- the vertices, texture, and colormap all need to be updated independently. If you have the time to sort it out, please open a PR!

**Comment by campagnola** [comment]
Regarding normalization: we certainly should be able to use unclamped 32-bit float textures. This is just another area that needs some attention from a willing contributor. I would also like to use float textures for surface plotting..

**Comment by campagnola** [comment]
(sorry for the flood) 
Actually, it might already be possible if you can just tickle `ImageVisual` into using the correct texture format:  `tex = gloo.Texture2D(data, internalformat='r32f')`

**Comment by Eric89GXL** [comment]
Makes sense to me. Such code wouldn't end up being ES 2.0 / WebGL compatible, though, right?

**Comment by campagnola** [comment]
That's correct.

**Comment by kmuehlbauer** [comment]
Thanks for the explanations. I can try to help on the image_visual update logic. Where should the PR be originated from and where should it have its destination. 

I just checked out the scenegraph-update branch of @campagnola, but it seems that my application doesn't run with that branch. I'll try with a stripped down example again.

**Comment by campagnola** [comment]
`scenegraph-update` would be the best place to make the changes, but perhaps you will need to wait until that branch is actually functional :)

**Comment by kmuehlbauer** [comment]
OK, I will follow `scenegraph-update`. 

I also have some ideas regarding #989. This could also go into `scenegraph-update?

**Comment by kmuehlbauer** [comment]
resolved by campagnola/vispy#8
