### ISSUE TITLE
using a TextVisual leads to unintended scaling of other Visual

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#981]
I'm not sure if creating an issue is the right thing to do, but I haven't been able to debug this, so I decided to go ahead and just create one.

The problem is that when I use a ```TextVisual``` with multiple strings (as the constructor allows, it throws off the scaling _completely_ and causes the entire scene to become really tiny. I don't know why this happens.

Also, it __does  not__ happen if you have a ```TextVisual``` with just one string. This to me is even more perplexing. 

***Example of extreme scaling down:***

![screenshot from 2015-06-07 01 02 36](https://cloud.githubusercontent.com/assets/1694861/8021130/f64e8e92-0cb0-11e5-970a-d05464d2a3fd.png)

[example in which this happens](https://github.com/bollu/vispy/blob/colorbar-visual/examples/basics/visuals/colorbar_visual.py)

[offending line of code](https://github.com/bollu/vispy/blob/colorbar-visual/vispy/visuals/colorbar.py#L195)

***Proper rendering with one ```TextVisual```***

![screenshot from 2015-06-07 01 07 16](https://cloud.githubusercontent.com/assets/1694861/8021149/8eae9c9a-0cb1-11e5-9faa-f8af6a4c952b.png)

**Comment by Eric89GXL** [comment]
So you have this problem with using a single TextVisual with a list of two positions and a list of two strings. Does it happen if you make two text visuals, one with the first position and string, and the other with the second position and string? Can you turn it into a minimal example (e.g., using as few lines as possible on current `master` branch)? That would help isolate the problem.

**Comment by bollu** [comment]
@Eric89GXL: [here is a minimal gist](https://gist.github.com/bollu/3ede93ded395c6a5b283)

***what it looks like initially:***


![screenshot from 2015-06-07 23 13 59](https://cloud.githubusercontent.com/assets/1694861/8025215/fd31f70c-0d6a-11e5-907b-41b191b4671d.png)


***what it looks like after pressing a key _twice_ on the keyboard***

![screenshot from 2015-06-07 23 14 07](https://cloud.githubusercontent.com/assets/1694861/8025219/0f581286-0d6b-11e5-97b8-a9320d0d869f.png)


It's funky, because, here's how the code works:

1. Don't render the ticks
2. Press a key - this renders the ticks. They don't show up onscreen, but the other ```TextVisual``` stays all right
3. Press a key again - this should __disable__ the rendering of the ticks. But, when you do this, the transform goes nuts and the ```TextVisual``` shrinks to nothing.

This is weird. My expected behavior would be that it shrinks __immediately after I press a key__.

I have a feeling I'm missing something very obvious here :/

**Comment by Eric89GXL** [comment]
So the `TextVisual` under the hood actually does its own rendering to create each glyph. This rendering occurs on an offscreen buffer, so it queries the OpenGL state before actually rendering. I have a feeling there are some delayed GLIR queues causing problems where the state is queried and set incorrectly here.

Things to probe:

1. Does it still fail for you if the second TextVisual object is actually only a single string and single position, or does it need to be two? This will help determine if it's actually something about the dual rendering that's a problem.
2. Does it fail if you a) use the same string for all three text bits and b) pass the `font_manager` property from the first TextVisual to the second one? This will help determine if it's due to the changing GL state, since using the same font_manager will make it so it doesn't need to render for the later text objects.

**Comment by bollu** [comment]
@Eric89GXL  I'll try both and get back

**Comment by bollu** [comment]
@Eric89GXL It works perfectly if the second ```TextVisual``` also renders just one string

**Comment by Eric89GXL** [comment]
interesting... I wonder if I did something stupid with the concatenation and position setting. If you have time to investigate (e.g., by adding some debugging `print` statements at various places in the text visual generation and drawing code) please do otherwise I can look tomorrow.

**Comment by bollu** [comment]
@Eric89GXL, I'll try and do it once I finish up the colorbar. I need to learn how to do the right coordinate transforms for it for the pixel width border!

**Comment by Eric89GXL** [comment]
Cool. For now then, just use two TextVisuals in your ColorbarVisual so you can wrap that up, and add a note saying that they should be combined once this issue is closed.

**Comment by bollu** [comment]
all right.

also, once ```AxisVisual``` gets merged, we can use that, correct?

**Comment by Eric89GXL** [comment]
Yeah, but it blows up Luke's system, so don't wait for that. And we'll probably also need to modify it to e.g. allow actually setting what the ticks should be, or the number of ticks. Right now it is basic and just always does 10 spanning the full range of the axis, which might not be great for a colorbar.

**Comment by bollu** [comment]
@Eric89GXL hm, okay then, I'm constructing two ```TextVisual```s in that case with a URL to the issue, so that it can be fixed later.

**Comment by nippoo** [comment]
This might be related to #975.

Is there any progress on this issue? It's been bugging me too...

**Comment by Eric89GXL** [comment]
No, we need to get #928 in before we can make additional progress on these issues. Some of them will be fixed, some won't. But the systems have been changed there so we need to make the fixes to that. If you have time, you could help @campagnola and @bollu port visuals in the new system, which would get us closer to fixing this.

**Comment by campagnola** [comment]
Just fixed a bug in #928 where TextVisual was changing the glViewport; hopefully that's it.

**Comment by Eric89GXL** [comment]
Yeah that's probably the culprit. But it needs to change it during
rendering of SDF. Can you point to the change? I'm curious how you fixed it.

**Comment by campagnola** [comment]
See the most recent commit.

**Comment by Eric89GXL** [comment]
I guess I should have just looked at the commits, sorry about that... looks like flushing at a different point in the code. I bet it will fix this.
