### ISSUE TITLE
Toggling visibility on a "Node" should "optionally" toggle visibility of its children.

### ISSUE THREAD

**Issue by KelSolaar** [vispy/vispy#986]
This one is actually highly debatable: at the moment it is possible to make a `Node` invisible in the `SceneGraph` but its children will still remain visible.

Usually in DCC application, I'm especially thinking about Autodesk Maya as it is the one that is the most used in VFX and Game industries, when you hide a node all the children nodes are getting hidden.

Right now I have to manually walk the `Node` children down to have that behaviour. I will probably end up monkey patching `vispy.scene.visuals.Node` directly as I don't want to create classes for things that I can build with a simple definition (for example a visual that is built around `Markers` and `Lines` with everything parented under a `Node`).

**Comment by campagnola** [comment]
I think this is already fixed in #928.

**Comment by KelSolaar** [comment]
Perfect Luke!

**Comment by almarklein** [comment]
How is it implemented? I think that indeed children should become invisible too (not optionally).

**Comment by campagnola** [comment]
See yourself:
https://github.com/vispy/vispy/pull/928/files#diff-c5071cd0aede5e96f97f6ca7c0dd2addR265
Note that this for-loop is the entire routine for drawing the scene. It is much simpler (and faster) than the DrawSystem we are currently using.

**Comment by KelSolaar** [comment]
The "optionally" thing is coming from the fact that in Autodesk Softimage / XSI one is able to either hide the whole branch or just the node in question. I will be more than happy if everything gets hidden.

Notice that in Autodesk Maya, if you want to make a children visible, all the parents will be made visible until the child is visible.
