### ISSUE TITLE
Example examples/basics/plotting/mpl_plot.html only creates blank subplots

### ISSUE THREAD

**Issue by chipmuenk** [vispy/vispy#987]
When running the example under

http://vispy.readthedocs.org/en/latest/examples/basics/plotting/mpl_plot.html

for the first time, some files are downloaded and then I just get a canvas with three blank subplots.Subsequent runs give the same result (except that no files are downloaded):

![vispy_empty_canvas](https://cloud.githubusercontent.com/assets/4620020/8155665/9f109980-1346-11e5-9195-0bd14ee1d33a.PNG)

Importing matplotlib instead of vispy.mpl_plot gives the expected results:
![matplotlib_vispy](https://cloud.githubusercontent.com/assets/4620020/8155730/642974a8-1347-11e5-9154-48b8cacc3341.PNG)

I have the following software versions installed:

vispy: 0.4.0
Py: 3.4.3 Win7 64b
matplotlib: 1.4.3

After the downloads, the console window stays absolutely blank, no message at all.

**Comment by chipmuenk** [comment]
I found the problem by chance (although I don't understand it):

Replace the last line 

       plt.show(True)
by

       fig.show(True)

and everything works fine.

Working with the Spyder IDE, the run setting needs to be "Interact with the Python console after execution", otherwise the figure will only flash shortly before being deleted.

**Comment by chipmuenk** [comment]
Sorry, hit the wrong button: I think somebody should edit the example as users without OpenGL background will most likely try to run of the high-level API examples.

**Comment by QuLogic** [comment]
This is supposed to work fine, and was broken for 0.4.0, fixed in master (#969), and somehow broken again in the latest master. @Eric89GXL I guess maybe some merged branch broke this again?

**Comment by QuLogic** [comment]
Sorry, my mistake, I was testing a branch. This _is_ fixed in master.

**Comment by Eric89GXL** [comment]
@chipmuenk can you see if it works for you using latest master?

**Comment by chipmuenk** [comment]
Thanx for the quick response - with latest master it does work:
![vispy_canvas](https://cloud.githubusercontent.com/assets/4620020/8181592/7f336b06-1427-11e5-9ee2-3f1166ef8d96.PNG)

However, axes are missing now - should they be working at the time being?

**Comment by Eric89GXL** [comment]
Closing this, then. Axes are currently on the way, but aren't in quite yet :)
