### ISSUE TITLE
Many examples not rendering correctly

### ISSUE THREAD

**Issue by nnmm** [vispy/vispy#992]
Hi,
in both the latest master and 0.4.0 release, many examples, especially from basics, are failing to render correctly. They don't output anything on the console and don't crash. Here's examples/demo/gloo/realtime_signals.py – there are colored specks moving to the left.
![realtime_signals](https://cloud.githubusercontent.com/assets/1933253/8250522/f0c37514-1674-11e5-8ca7-bb815b3580e1.png)
Others that don't work (I haven't tried all examples):
In examples/basics/scene: grid.py, console.py, cube.py, flipped_axis.py, grid_large.py, image.py, iso*.py …
basics/plotting has different problems: mpl_plot like [here](https://github.com/vispy/vispy/issues/987) – changing `plt.show()` to `fig.show()` and invoking with `python -i` to avoid immediate closing works. scatter_histogram has the scatter plot, but not the histograms, spectogram only has the lower part. volume.py doesn't show anything, not sure what export.py is supposed to do, but it's mostly white.
Many of the other examples, e. g. in basics/gloo, work fine.

Background information:
Python 2.7.6
Graphics card: NVIDIA Corporation GF108GL [Quadro 600] (rev a1)
Ubuntu 14.04.2 LTS
numpy==1.8.2
pandas==0.13.1
matplotlib==1.3.1
PyOpenGL==3.0.2
scipy==0.13.3

**Comment by rossant** [comment]
what GPU drivers do you have?

**Comment by nnmm** [comment]
I don't have mesa-utils, hope this helps:
![gpu drivers](https://cloud.githubusercontent.com/assets/1933253/8251652/a5ce43fe-167e-11e5-8d4b-7b307d2eae08.png)

**Comment by rossant** [comment]
can you try the proprietary nvidia drivers?

**Comment by Eric89GXL** [comment]
Yeah, I think the open source drivers probably do not have full 3D support
yet.

**Comment by campagnola** [comment]
I think nouveau is supposed to be fully-functional. It would be nice if we can support it, but I'm not sure how much effort it's worth. If we can pinpoint exactly what's different about these drivers, then at least we should file a bug report upstream.

**Comment by nnmm** [comment]
I switched to the NVIDIA driver version 331.113. This probably doesn't concern vispy, but now I get "RuntimeError: context could not be created" from backends/_qt.py and 'Xlib:  extension "GLX" missing on display ":0".' As an added bonus, I'm unable to log in using Unity.

**Comment by campagnola** [comment]
..and there we have a great reason to want to support nouveau :)

**Comment by Eric89GXL** [comment]
I'm going to close this as a `Nouveau`/driver bug, rather than a `vispy`-specific one
