### ISSUE TITLE
Allow make.py test flake to run docstring tests as well

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#993]
As of now, ```make.py test flake``` does _not_ test the docstrings, which means the docstring tests present at  ```vispy/util/tests/test_docstring_parameters.py``` need to be run separately.

Forgetting that step means waiting for the CI to pass the build, have that fail after 5 minutes, and then fix the docstrings again.

I propose to allow ``make.py test flake``` to run the docstring tests as well (all forms of linting we have, basically)

Thoughts?

**Comment by Eric89GXL** [comment]
I'd rather not expand `make flake` because then it's a bit of a misnomer, maybe add an entry `make docstring` or `make doccheck` or something.

**Comment by bollu** [comment]
sure. I think ```docstring``` is more explicit

**Comment by QuLogic** [comment]
They're more commonly called `doctests`...

**Comment by bollu** [comment]
@QuLogic hm, I wasn't aware of that :) All right. so, ```doctests``` it is? ```python make.py test doctests```?

```python make.py test docs``` seems neater

**Comment by Eric89GXL** [comment]
Doctests are AFAIK different, those check code executing in docstrings.
This checks docstring parameter listing.

**Comment by QuLogic** [comment]
Ah, you're right, they're not the same. `python make.py test docs` is nicer looking though and I don't think there's anything too confusing about it.

**Comment by bollu** [comment]
>The doctest module searches for pieces of text that look like interactive Python sessions, and then
>executes those sessions to verify that they work exactly as shown.
>There are several common ways to use doctest:

@Eric89GXL yeah, looks like it.

**Comment by bollu** [comment]
cool, so ```python make.py test docs``` works?
