### ISSUE TITLE
have dedicated functions for radian / degree conversion?

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#994]
I know that this is a really small issue, but I've been rewriting some ```EllipseVisual``` code, and I would like it if there were standard functions to convert ```radians <-> degrees```. 

I know that it's trivial, but seeing something like ```theta = deg_to_rad(angle)``` is much nicer (IMO) than ```theta = angle * np.pi / 180.```

**Comment by QuLogic** [comment]
[`np.deg2rad`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.deg2rad.html) and [`np.rad2deg`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.rad2deg.html)...

**Comment by bollu** [comment]
@QuLogic oh, cool. Numpy has everything!
