### ISSUE TITLE
Qt4 flickers when window is maximised 

### ISSUE THREAD

**Issue by bollu** [vispy/vispy#997]
The screen flickers constantly when the screen is maximized. This does not happen with `pyglet` as the backend. I suspect it is some archlinux+graphics driver interaction.

```
OS: Arch linux
drivers: mesa open-source drivers
```

**Comment by campagnola** [comment]
Does this happen even for the simplest gloo examples?

**Comment by bollu** [comment]
The example needs to be dynamic (`examples/basic/visuals/cube.py`, `examples/basic/visuals/mesh.py`) both work because they rotate objects. Static examples show no flickering

**Comment by Eric89GXL** [comment]
And here by "both work" you mean "both work to show the bug" i.e. "both have problems", right?

**Comment by bollu** [comment]
Yes. Sorry for the ambiguity. The both cause constant flickering until the window is resized

**Comment by bollu** [comment]
### wrong rendering (backend is qt4)
![screenshot from 2015-06-25 01-36-51](https://cloud.githubusercontent.com/assets/1694861/8340222/bb81b43c-1ada-11e5-876b-b17db0ea3a74.png)

### correct rendering (backend is pyglet)
![screenshot from 2015-06-25 01-39-42](https://cloud.githubusercontent.com/assets/1694861/8340270/1b8341de-1adb-11e5-9e48-628cd2324f85.png)

That was a frame I got.

Things to look for in that:

1. the top left ball isn't rendering right. It should be a solid, red ball.
2. The top right ball has weird jaggies at the edge
3. The bottom left ball is a phong shading example. It's not rendered in this particular frame


This is all on `vispy/master`, commit hash 60966702538d749e72beb82e3b55cbd32afea465

**Comment by kmuehlbauer** [comment]
Given the age of this issue, is this still relevant? @larsoner Can this be closed?
